### ISSUE TITLE
Load a tiff Buffer from ITK image

### ISSUE THREAD

**Issue by abenchaaben** [jcupitt/libvips#1000]
Hi,
I'm trying to create a vips image from buffer using vips_tiffload_buffer. The buffer is an output from an ITK unsigned char image and i tested to create an opevcv image from this buffer and i managed to do it. But when i pass the same buffer to vips_tiffload_buffer, i get an error.

Her what i'm trying to do : 

		OutputImageTypeChar::RegionType region = output_image->GetLargestPossibleRegion();
		OutputImageTypeChar::SizeType size = region.GetSize();
		size_t len = size[0] * size[1];
		unsigned char *imgDataBuffer = (unsigned char*)_TIFFmalloc(len * sizeof(unsigned char));
		memcpy(imgDataBuffer, output_image->GetPixelContainer()->GetBufferPointer(), len);
		VipsImage *out;
		int error = vips_tiffload_buffer(imgDataBuffer, len, &out,NULL);
		vips_tiffsave(out,"img.tiff", "compression", VIPS_FOREIGN_TIFF_COMPRESSION_JPEG, "Q", 90, "tile", TRUE, "tile_width", 512, "tile_height", 512, "pyramid", TRUE, "bigtiff", TRUE, NULL);

Any idea what is the problem.

Thank's

**Comment by jcupitt** [comment]
Hello @abenchaaben, `vips_tiffload_buffer()` expects a memory area containing an image formatted as a TIFF file. 

Do you want to make a vips image from a simple memory array? You need `vips_image_new_from_memory()`:

https://jcupitt.github.io/libvips/API/current/VipsImage.html#vips-image-new-from-memory

**Comment by jcupitt** [comment]
Oh, is this C++? You can also do:

```cpp
OutputImageTypeChar::RegionType region = output_image->GetLargestPossibleRegion();
OutputImageTypeChar::SizeType size = region.GetSize();
size_t len = size[0] * size[1];
void *data = output_image->GetPixelContainer()->GetBufferPointer();
// assuming 1 band, uchar pixels
VImage im = VImage::new_from_memory(data, len, size[0], size[1], 1, VIPS_FORMAT_UCHAR);
im.tiffsave("img.tiff", VImage::option()
    ->set("compression", "jpeg")
    ->set("Q", 90)
    ->set("tile", TRUE)
    ->set("tile_width", 512)
    ->set("tile_height", 512)
    ->set("pyramid", TRUE)
    ->set("bigtiff", TRUE));
```

**Comment by abenchaaben** [comment]
Hi @jcupitt, thank you a lot. vips_image_new_from_memory worked for me. What is the difference between 

`vips_tiffsave(out,"img.tiff", "compression", VIPS_FOREIGN_TIFF_COMPRESSION_JPEG, "Q", 90, "tile", TRUE, "tile_width", 512, "tile_height", 512, "pyramid", TRUE, "bigtiff", TRUE, NULL);`

and

`im.tiffsave("img.tiff", VImage::option()
    ->set("compression", "jpeg")
    ->set("Q", 90)
    ->set("tile", TRUE)
    ->set("tile_width", 512)
    ->set("tile_height", 512)
    ->set("pyramid", TRUE)
    ->set("bigtiff", TRUE));`

Thank's again.

**Comment by jcupitt** [comment]
The second is the libvips C++ API. It's a little safer and easier to use. 

http://jcupitt.github.io/libvips/API/current/using-from-cpp.html

You'll have to rebuild it on Windows unfortunately if you want to use VS.

**Comment by abenchaaben** [comment]
Ah ok. Thank you for the explanation.
