### ISSUE TITLE
Gaussian blur strange artifacts for certain sigma values

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#1001]
I'm seeing some strange results for certain sigma values when using `vips_gaussblur()` on 8.6.3.

The command used for testing:

```
vips gaussblur apples.jpg apples_blur.jpg <sigma>
```

With my sample image a sigma of exactly 10 gives a strange posterization effect, while values like 9.9 or 10.1 are fine.

**Original:**
![apples](https://user-images.githubusercontent.com/909587/41299595-1dc4a764-6e64-11e8-9313-3c00394d16ec.jpg)

**Sigma 10:**
![apples_sigma_10](https://user-images.githubusercontent.com/909587/41299711-568ef91e-6e64-11e8-859f-50815031c735.jpg)

**Sigma 10.1:**
![apples_sigma_10 1](https://user-images.githubusercontent.com/909587/41299764-7a9cdace-6e64-11e8-9562-2a254c0fa3c8.jpg)

**Comment by jcupitt** [comment]
Looks like a bug in the thing that tries to decide if it can use an int path:

```
john@yingna ~/pics $ time vips gaussblur apple.jpg x.jpg 9.9 --vips-info
VIPS-INFO: 16:28:14.950: gaussblur mask width 35
VIPS-INFO: 16:28:14.951: vips_convi_intize: too inaccurate
VIPS-INFO: 16:28:14.951: convi: using C path
VIPS-INFO: 16:28:14.953: vips_convi_intize: too inaccurate
VIPS-INFO: 16:28:14.953: convi: using C path
real	0m0.282s
user	0m1.929s
sys	0m0.012s
john@yingna ~/pics $ time vips gaussblur apple.jpg x.jpg 10 --vips-info
VIPS-INFO: 16:28:20.575: gaussblur mask width 35
VIPS-INFO: 16:28:20.579: convi: using vector path
VIPS-INFO: 16:28:20.582: convi: using vector path
real	0m0.075s
user	0m0.184s
sys	0m0.014s
```

I'll have a look.

**Comment by felixbuenemann** [comment]
Ah, it looks like these artifacts are introduced when using the vector path, I also see them eg. with sigma 8, although less pronounced.

**Comment by jcupitt** [comment]
Yes, the vector path is only 16 bits of precision, so with very large masks it can run out of bits. It's supposed to predict the accuracy and not use the vector path if the errors are too large, but the check is obviously not working. 

I'll rework it.

**Comment by felixbuenemann** [comment]
I noticed that the posterization caused by the vector path is fixed, if I revert eefb2dad980c12922ad15d987be7c4b42a44d5cf.

**Comment by jcupitt** [comment]
Oh argh the whole thing was a typo. Try:

```C
        shift = ceil( log2( mx ) + 1 );
```

Oh dear oh dear. Thank you for finding this dumbness, Felix!

**Comment by felixbuenemann** [comment]
Thanks John, I tried your suggested fix and it works, so I opened PR ä1003 to get it integrated.
