### ISSUE TITLE
vipssave broken on macOS

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#1004]
I'm currently trying to fix the macOS CI build and it's failing all the tests that try to write to a `.v` file.

I also tried `tools/vips vipssave foo.jpg foo.v` on my local mac on master and no output file is created.

**Comment by jcupitt** [comment]
Huh weird, it's working on linux. I'll have a look.

**Comment by felixbuenemann** [comment]
Btw. this is only broken on 8.7.0 / master, 8.6.4 works fine.

**Comment by jcupitt** [comment]
Another typo. It seems to be working now.

Thanks!

**Comment by felixbuenemann** [comment]
Thanks, I can confirm it's fixed!
