### ISSUE TITLE
Unknown action tiffsave on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by modou33** [jcupitt/libvips#1013]
Hello.

I have just installed the package (via apt) libvips on a fresh ubuntu 18.04 LTS. The exact version of vips installed is
`vips-8.6.4-Wed Jun 13 15:24:52 UTC 2018`
However, the command vips tiffsave return an error

`vips: unknown action "tiffsave"`

Did I need to install any others packages.

Thanks !

**Comment by jcupitt** [comment]
Hello @modou33,

I think you must have built libvips yourself -- the one on 18.04 is 8.4.5-1, I think. Perhaps you have a libvips in `/usr/local` as well?

I see:

```
john@yingna ~ $ which vips
/usr/bin/vips
john@yingna ~ $ vips -l tiffsave
        VipsForeignSaveTiff (tiffsave), save image to tiff file (.tif, .tiff), priority=0, any
john@yingna ~ $ ldd `which vips` | grep vips
	libvips.so.42 => /usr/lib/x86_64-linux-gnu/libvips.so.42 (0x00007f463b053000)
john@yingna ~ $ dpkg -S libvips
libvips42:amd64: /usr/lib/x86_64-linux-gnu/libvips-cpp.so.42
libvips-doc: /usr/share/gtk-doc/html/libvips/home.png
libvips-tools: /usr/share/doc/libvips-tools
```

So install `libvips-tools` to get the command-line interface.

**Comment by modou33** [comment]
Hello @jcupitt 

As you advised, I have re-installed completetly vips on a new an clean Ubuntu 18.04. It works nice now.

Thank you for you fast reply !
