### ISSUE TITLE
Issue while resizing png images

### ISSUE THREAD

**Issue by palaiyacw** [jcupitt/libvips#1014]
I came across this issue with ImageMagick and now with libvips. If, I try to resize the png images size of resized doesn't reduce. In few cases, it increases a bit. Moreover, quality factor doesn't have any impact on the resized png images. Could you please explain behavior and how do I achieve the resized png image of smaller size using libvips. FYI, I am not using CLI. I was trying to achieve the same as mentioned below:

```
 options := bimg.Options{
		Width:         desiredWidth,
		Height:        desiredHeight,
		Crop:          true,
		StripMetadata: true,
		Interlace:     true,
		Quality:       90,
	}

	newImg, err = bimg.Resize(inputImagebytes, options)

	if err != nil {
		mj.Notify <- err
		return err
	}
```

**Comment by jcupitt** [comment]
Hello @palaiyacw, 

`Q` (or quality) is for jpg images. For PNG, you need to set the compression factor for the deflate compressor:

```
john@yingna ~/pics $ vips copy supper.jpg x.png
john@yingna ~/pics $ vips copy supper.jpg x9.png[compression=9]
john@yingna ~/pics $ vips copy supper.jpg x0.png[compression=0]
john@yingna ~/pics $ ls -l x*.png
-rw-r--r-- 1 john john 7840443 Jun 25 15:55 x0.png
-rw-r--r-- 1 john john 2264384 Jun 25 15:54 x9.png
-rw-r--r-- 1 john john 2367078 Jun 25 15:54 x.png
```

So `compression=0` (no compression) is 7.8mb, but `compression=9` (the slowest and most expensive) is "only" 2.7mb.

I say "only" because of course that's still a lot. A JPG image is much, much smaller:

```
john@yingna ~/pics $ ls -l supper.jpg 
-rw-r--r-- 1 john john 220965 Apr  6 12:23 supper.jpg
```

Just 220kb, 10x smaller than the best PNG.

**Comment by palaiyacw** [comment]
Hi @jcupitt, 
Just out of curiosity why there is a need of quality or compression factor? Where as you can reduce the file size by doing the chroma sampling.

**Comment by jcupitt** [comment]
Chroma subsampling is lossy -- that's something that JPG does. PNG is a lossless format, so there's no equivalent.

**Comment by palaiyacw** [comment]
Hi @jcupitt,
I tried using `CLI` as you mentioned above for compressing the PNG images as well as using `options` from code. But, I don't see any reduction in the output image. Size remains exactly the same. I don't know how come your png file size reduced. Moreover, when i use `compression=0` it size even further increases. Could you please explain this behaviour.
You can also try downloading png files from [here](https://www.sample-videos.com/download-sample-png-image.php).  

FYI, i am using `vips-8.7.0` on `Ubuntu 16.04.3`

![screenshot from 2018-06-26 12-30-20](https://user-images.githubusercontent.com/10070831/41894646-376c04ee-793d-11e8-98b2-c550247558bc.png)

**Comment by jcupitt** [comment]
I guess your source image is compressed with level 6 (the default) and level 9 is not shrinking it by much more. You'd need to see the exact byte size to tell.

Do you want to reduce the image dimensions? I'm not sure what you are trying to achieve.

**Comment by jcupitt** [comment]
You'd need to ask bimg how their resize method works. On the command-line it's:

```
john@kiwi:~/pics$ vipsthumbnail SamplePNGImage_5mbmb.png -s 512 -o x.png
john@kiwi:~/pics$ ls -l x.png
-rw-r--r-- 1 john john 455956 Jun 26 08:26 x.png
```

to resize to 512 pixels across. In Python it's:

```python
import pyvips

image = pyvips.Image.thumbnail("in.png", 512)
image.write_to_file("out.png")
```

In PHP it's:

```php
$image = Vips\Image::thumbnail("in.png", 512);
$image->writeToFile("out.png");
```

etc. for other languages.

**Comment by palaiyacw** [comment]
Hi @jcupitt,
Yes, actually I am trying to reduce the dimensions of the png images. How do you check the exact compression level of the png? I am attaching addition info here for the same image below:

![screenshot from 2018-06-26 13-04-35](https://user-images.githubusercontent.com/10070831/41896461-48d04218-7942-11e8-9366-1edba8b4ecfc.png)
![screenshot from 2018-06-26 13-05-03](https://user-images.githubusercontent.com/10070831/41896462-4907b1da-7942-11e8-9dee-884ba3e7d7e0.png)
![screenshot from 2018-06-26 13-05-11](https://user-images.githubusercontent.com/10070831/41896463-493ef564-7942-11e8-8325-34ea3755427e.png)

**Comment by jcupitt** [comment]
Don't post screendumps! Just select the text, then SHIFT-CTRL-C to copy, and CTRL-V to paste into your browser. You can put triple backticks above and below the text to have it formatted as monospace.

The PNG file format does not record compression level. The number is just how much effort the library should put into optimizing the deflate tables. The default is six, so it's probably that unless someone did something special.

**Comment by palaiyacw** [comment]
ok, thanks
