### ISSUE TITLE
matching mozjpeg options with vips

### ISSUE THREAD

**Issue by hyperknot** [jcupitt/libvips#1015]
I'm migrating away from a pipeline which used imagemagick resize -> TGA -> mozjpeg command line tool.

What I particularly enjoyed in mozjpeg's cjpeg tool was that it was auto-configuring the right settings based on quality input.

Now, with vipsthumbnail I believe I need to manually figure out the right values. I have compiled vips to use mozjpeg.

I have two use cases for vipsthumbnail:
1. Saving a reference quality, but still managable size image. I'm using Q=90 for this. In mozjpeg this was giving 4:4:4, while in vips this has chroma subsampling. I can disabled that one.
2. Saving most-optimal quality, retina sized images. I was simply using Q=75 for this. In my tests it seems that vipsthumbnail needs to be at Q=65 to match mozjpeg's 75 in file size.

Can you help me how to match the mozjpeg auto-configuration options in the above two cases?

I guess I need no-subsample for Q=90. But what about:
- optimize-coding
- interlace
- trellis-quant (ignored?)
- overshoot-deringing (ignored?)
- optimize-scans (ignored?)

Am I supposed to use these ones or not? For Q=90 I'd prefer quality, for Q=75/65 I'd optimal file size.

**Comment by jcupitt** [comment]
Hello @hyperknot,

Yes, you have to set all the options yourself. From memory, the mozjpeg command-line tool adjusts all the other settings with Q. libvips will turn off chroma subsample for Q>90 (like ImageMagick), but that's all it does. You'll probably have to look at the source for the mozjpg tool and see what heuristics it uses.

**Comment by hyperknot** [comment]
Thanks, as I understand maybe I need to ask these on some mozjpeg mailing list if they exist.

But before that, about the options: vips which has been compiled with mozjpeg, all of trellis, overshoot and optimize-scans are not supported. Is that reasonable, or I misconfigured something at compile time?

**Comment by jcupitt** [comment]
That sounds odd. Yes, those options should all work with mozjpeg, it sounds like a config problem. Let me check.

**Comment by hyperknot** [comment]
Here is the compile command I'm using:
https://github.com/hyperknot/dockerbase/blob/5aeba75a3dd392f36ce6705d63c9f1f4003ee7a0/Dockerfile#L50-L61

**Comment by jcupitt** [comment]
libjpeg is difficult: recent libjpeg uses pkg-config to find libraries, but mozjpeg is an earlier fork and does not. But if you have a libjpeg.pc somewhere, that will override `--with-jpeg-includes` and `--with-jpeg-libraries`.

libvips tries first with pkg-config and only if that fails, it falls back to checking the two `--with` options. Libraries like libjpeg-turbo will have a .pc file. Plus of course things like imagemagick will pull in a libjpeg.pc.

It's very unfortunate that we have at least three versions of such a fundamental library :(

**Comment by hyperknot** [comment]
So is there a way to make sure that it's using mozjpeg? Like not installing some packages first?

If I understand right, I need to remove some packages from apt-get install in the first part, install mozjpeg & vips and only afterwards install the skipped packages?

Here is my full install script:
https://github.com/hyperknot/dockerbase/blob/master/Dockerfile

**Comment by jcupitt** [comment]
I think you'll need to set `JPEG_CFLAGS` and `JPEG_LIBS`:

```
$ ./configure --help | grep -i jpeg
  --without-jpeg          build without libjpeg (default: test)
  --with-jpeg-includes=DIR
                          libjpeg includes are in DIR
  --with-jpeg-libraries=DIR
                          libjpeg libraries are in DIR
  JPEG_CFLAGS C compiler flags for JPEG, overriding pkg-config
  JPEG_LIBS   linker flags for JPEG, overriding pkg-config
```

I'm out of time tonight, I'll have a go at a dockerfile tomorrow. You can use:

```
$ ldd `which vips` | grep jpeg
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007efddbbb9000)
```

to verify that you are picking up the right libjpeg (I'm obviously not).

**Comment by hyperknot** [comment]
Thanks for that verification command. I had to remove both:

- libtiff5-dev
- libjpeg-turbo8-dev

To make sure that jpeg is not installed (it's not really ideal that I lost TIFF support on the way, but I wasn't planning using TIFF at the moment).

Now:
```
libjpeg.so.62 => /usr/local/opt/mozjpeg/lib/libjpeg.so.62
```

I can now run all JPEG options without any warnings.

**Comment by jcupitt** [comment]
That's great. You can build your own libtiff against mozjpeg, of course, when you need it.

**Comment by hyperknot** [comment]
Just for the reference here is what @kornelski answered about mozjpeg options:
https://github.com/mozilla/mozjpeg/issues/294

Basically, for optimal quality/file size I should enable all of:

- Optimize: yes
- interlace: yes
- subsample: enable subsampling to get better file sizes. It's a good choice for photos. Disable subsampling for banners/icons/text (images with saturated colorful edges).
- trellis: yes
- deringing: yes
- optimize scans: yes
- quant-table: 0 for low DPI, 3 for high-DPI.

For Q90, I don't need any of these, as I don't care about file size at that point. It only needs no-subsample in vips.

**Comment by jcupitt** [comment]
That's useful, thanks @hyperknot !

**Comment by thetw** [comment]
I've set the env variable `PKG_CONFIG_PATH=/usr/local/opt/mozjpeg/lib/pkgconfig` in order to tell `pkgconfig` where to look for the mozjpeg libraries. Now i get:
```bash
$ ldd `which vips` | grep jpeg
        libjpeg.so.62 => /usr/local/opt/mozjpeg/lib/libjpeg.so.62 (0x7f70f9fad000)
        libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x7f70f8cca000)
```
Is it critical that vips now has linked both `libjpeg` libraries? Will this potentially cause issues?
The "normal" libjpeg got installed by other packages i've added for a full fat vips build...

**Comment by jcupitt** [comment]
I would guess you have imagemagick built against libjpeg and libvips built against mozjpeg. This is likely to cause horrible confusion, unfortunately.

You'll need to rebuild libraries that libvips depends on that build against libjpeg against mozjpeg, unfortunately.

**Comment by thetw** [comment]
Thanks for clarification! @jcupitt 
I'll rebuild `libtiff`, `libsvg`, `libwebp` and `imagemagick` against mozjpeg and hope this overhead fixes the unwanted linking of the standard `libjpeg` library.
