### ISSUE TITLE
How to add HEIC image support?

### ISSUE THREAD

**Issue by tigranbs** [jcupitt/libvips#1017]
Hi as you may know Apple developed new image type for latest iOS devices, which seems more efficient image compression principle.
We have a web service for delivering static images with some middleware processing with VIPS library ... how can I add HEIC image support to that? Do I need to develop it from scratch or you have some pluggable instruction which could be done during compile time?

Thanks

**Comment by jcupitt** [comment]
Hello @tigranbs,

This has been discussed before:

https://github.com/jcupitt/libvips/issues/671

The tldr seems to be that there are a frustrating range of legal problems and you'll probably need some custom code for mux/demux, plus libde265, which itself violates quite a few patents and is likely to cause legal problems in some parts of the world.

**Comment by tigranbs** [comment]
Ahh now it make sense why there is no that match of a usage for that format.
Thanks for explanation, will try to figure out is it acceptable for us to use FFmpeg's implementation or not.
