### ISSUE TITLE
Apply watermark image at the bottom-right corner of image and issue with clarity

### ISSUE THREAD

**Issue by palaiyacw** [jcupitt/libvips#1018]
I am trying to apply the watermark without passing the `Top` and `Left` parameter. By default, it puts the watermark at the top-left corner of the image. Is there any way by means of which we can put it at the bottom-right corner of the image. 

I guess by default values of top and right would be 0 and 0 respectively in [vipsDrawWatermark](https://github.com/matrix-org/dendrite/blob/a76e31f1b3ff7035b53e755c07058ff8c5f91177/vendor/src/gopkg.in/h2non/bimg.v1/vips.go#L688) function. 

Moreover, I applied the same watermark on the same image using image magick and libvips. If you could see below the clarity in image with watermark generated from libvips is not great. Though, i have tweaked opacity a lot, it didn't help.

**ImageMagick:**
![imagemagick](https://user-images.githubusercontent.com/10070831/41920374-3a02c972-797e-11e8-972b-c5bd5427c967.png)
**libvips:**
![libvips](https://user-images.githubusercontent.com/10070831/41920377-3b5de0a4-797e-11e8-9ef7-b0762f416d7b.png)

**Comment by jcupitt** [comment]
Sorry, I think this is a bimg question. I didn't write that code and I don't use Go. 

https://github.com/h2non/bimg/issues

**Comment by palaiyacw** [comment]
Hi @jcupitt,
But bimg is just a wrapper on top of libvips library. If, you look at here. It calls the same function in libvips which i mentioned above for applying the watermark.
[bimgWaterMark](https://github.com/h2non/bimg/blob/4763cabc0c8ecedbb856b7abfb32f8201e91836a/resizer.go#L364)

**Comment by palaiyacw** [comment]
Hi @jcupitt,
Bimg is just a binding and it uses internally libvips. Having said that If you look at [here](https://github.com/matrix-org/dendrite/blob/a76e31f1b3ff7035b53e755c07058ff8c5f91177/vendor/src/gopkg.in/h2non/bimg.v1/vips.go#L698) it calls the C bindings. Hence, I am asking the question here. If you could please help me.

**Comment by lovell** [comment]
@palaiyacw `vips_watermark_image` is a bimg function, not a libvips function. https://github.com/h2non/bimg/blob/262d0f82b77cbeed7b7577c10f05fb618d8b8df4/vips.h#L490

**Comment by palaiyacw** [comment]
@lovell @jcupitt  thanks you guys.
