### ISSUE TITLE
piecewise affine transform

### ISSUE THREAD

**Issue by wppd** [jcupitt/libvips#1019]
hey, working on a project which needs to do a lot of image processing and have strict requirement on efficiency and time.

I wonder is it possible to do affine transform with src and dest coordinates?

for example, 

I want to transform (0, 750) (0, 560) to (10, 740) (10, 520) respectively

 (0, 750) (0, 560) are src coordinates and (10, 740) (10, 520)  are dest coordinates.

thanks in advance.

**Comment by wppd** [comment]
@jcupitt  thanks for your fast reply. really appreciate that.

something like this http://scikit-image.org/docs/stable/auto_examples/transform/plot_piecewise_affine.html#sphx-glr-auto-examples-transform-plot-piecewise-affine-py

thanks again!

**Comment by wppd** [comment]
imagemagick  way

http://www.fmwconcepts.com/imagemagick/meshwarp/index.php

**Comment by jcupitt** [comment]
Ah, I understand. Yes, you want `mapim`:

http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-mapim

There was a blog post about it a couple of years ago:

http://libvips.blogspot.com/2015/11/fancy-transforms.html

Make a low-res image with your transform in, then upsize with a linear interpolator and use `mapim` to resample.

**Comment by wppd** [comment]
@jcupitt thanks for your help. 

but, unfortunately, I still don't know how to transform src coordinates to given dest coordinates with mapim... 

would you elaborate on this?

**Comment by jcupitt** [comment]
If it's not too big, you can also make the input image from an array. In Python:

```python
image = pyvips.Image.new_from_array([[1, 2, 3], [4, 5, 6]])
```

There's something similar in C.

**Comment by wppd** [comment]
@jcupitt sorry to bother you again.

it seems do not work for me.

would you help me? here is the code

```
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

$image = Vips\Image::newFromFile("crop1.png");
$index = Vips\Image::xyz($image->width, $image->height);

$srcs = file(__DIR__.'/distort/src20180615080109');
$dsts = file(__DIR__.'/distort/dst20180615080109');

foreach ($srcs as $k => $src) {
    list($sx, $sy) = explode(",", trim($src));
    list($dx, $dy) = explode(",", trim($dsts[$k]));
    $index = $index->draw_rect([$sx, $sy], $dx, $dy, 1, 1, ['fill' => 0]);
}


$new = $image->mapim($index);

$new->writeToFile("test.png");
```

the output test.png is same to crop1.png..

here are the  crop1.png and coordinates.
![crop1](https://user-images.githubusercontent.com/919138/42018122-af6839ac-7ae3-11e8-9a0e-f3a8aa7e0822.png)


https://gist.github.com/wppd/d2b204761e7848f6788c4cb0afb614e9

**Comment by wppd** [comment]
@jcupitt 

we get the dest coordinates manually from photoshop.

we want to archive the photoshop distort effect in code.

here is the result we get from [scikit-image](http://scikit-image.org/docs/stable/auto_examples/transform/plot_piecewise_affine.html) by feeding the given source and destination coordinates.

![result](https://user-images.githubusercontent.com/919138/42020037-50a814fe-7ae9-11e8-9cd8-bceb008c6fa7.png)

**Comment by jcupitt** [comment]
It sounds like you need something to fit a regular grid to a set of irregular samples. libvips doesn't have that directly -- you'd need to use something like numpy. Sorry!

**Comment by wppd** [comment]
@jcupitt 

thanks for helping me, though! Really appreciate it. :]
