### ISSUE TITLE
Cropping after thumbnail generates error

### ISSUE THREAD

**Issue by korys** [jcupitt/libvips#1022]
Hi,
I'm trying to resize an image and then trim white borders from image. Here is an example:

Origanl Image
![original](https://user-images.githubusercontent.com/4078538/42089739-e0544284-7b9e-11e8-9abe-7c87c5970405.jpg)
Output image:
![resizecrop](https://user-images.githubusercontent.com/4078538/42089781-0a7f31fe-7b9f-11e8-9024-5a288482fae9.jpg)

Please note trimmed white borders in output image.

I've already implemented resizing and trimming separately, but can't get it work together. I'm using PHP.

Resize:
```
$sFile = file_get_contents('...');
$oImage = \Jcupitt\Vips\Image::thumbnail_buffer($sFile , 200);
$oImage->writeToFile("my-thumbnail.jpg");
```
Trim borders (took this code https://github.com/jcupitt/libvips/issues/233#issuecomment-73486391 and rewritten it to PHP)
```
$sFile = file_get_contents('...');
$oImage = \Jcupitt\Vips\Image::newFromBuffer($this->sFile);
//find the value of the pixel at (0, 0) ... we will search for all pixels 
//significantly different from this
$background = $oImage->getpoint(0, 0);

//we need to smooth the image, subtract the background from every pixel, take 
//the absolute value of the difference, then threshold
$mask = $oImage->median(3)->subtract($background)->abs()->more(10);

//sum mask rows and columns, then search for the first non-zero sum in each
//direction
$project = $mask->project();
$columns = $project['columns'];
$rows = $project['rows'];

//calculate pixels to crop
$left = $columns->profile()['rows']->min();
$right = $columns->width - $columns->flip("horizontal")->profile()['rows']->min();
$top = $rows->profile()['columns']->min();
$bottom = $rows->height - $rows->flip("vertical")->profile()['columns']->min();

// crop image
$oImage->crop($left, $top, $right - $left, $bottom - $top);
$oImage->writeToFile("my-thumbnail.jpg");
```

When passing $oImage object from resize function to trim function instend of reading it from buffer I get following error:
`VipsJpeg: out of order read at line 48
#0 .../vendor/jcupitt/vips/src/Image.php(685): Jcupitt\Vips\Image::errorVips()
#1 .../vendor/jcupitt/vips/src/Image.php(1052): Jcupitt\Vips\Image::errorIsArray(-1) 
#2 .../vendor/jcupitt/vips/src/Image.php(1130): Jcupitt\Vips\Image::callBase('project', Object(Jcupitt\Vips\Image), Array)
#3 .../models/Image/Effect/SmartCrop.php(24): Jcupitt\Vips\Image->__call('project', Array)
...`

So it looks like there is a problem with project() method but I have no clue what's the issue here.
I've seen smartcorp method in libvips docs but don't know how to get 'trimmed whiteborders' effect with that.

Any hints appreciated :)

**Comment by jcupitt** [comment]
Hello @korys,

The `thumbnail` operator streams pixels -- it pulls pixels from the source as it writes the final output image, and pixels are discarded after they are written.

This means you can only use the result of thumbnail once. If you write some code that needs to scan the image twice (for example, once to find the edges, a second time to crop), you'll get an error because the shrunk image will no longer exist for the second pass.

The solution is to thumbnail into a memory image (it shouldn't use too much space, since thumbnails are only small), then from that, search for edges and crop.

Try changing your code to be (untested):

```php
$sFile = file_get_contents('...');
$oImage = \Jcupitt\Vips\Image::thumbnail_buffer($sFile , 200)->copyMemory();
$rect = $oImage->find_trim();
$crop = $oImage->crop($rect[0], $rect[1]. $rect[2], $rect[3]);
$oImage->writeToFile("my-thumbnail.jpg");
```

`find_trim` was added in 8.6:

http://jcupitt.github.io/libvips/API/current/libvips-arithmetic.html#vips-find-trim

**Comment by korys** [comment]
Thank you very much @jcupitt, this is what I was looking for!
I had to change the code a little, because find_trim() returns associative array with named keys:
`$crop = $oImage->crop($rect['left'], $rect['top'], $rect['width'], $rect['height']);`

**Comment by jcupitt** [comment]
Ah yes, of course. It's been a little while since i used it! Thanks for the correction.
