### ISSUE TITLE
Rotating center in affine

### ISSUE THREAD

**Issue by vkkindia** [jcupitt/libvips#1023]
The default rotating center is 0,0 ie left top

How can I move to left middle, or left bottom, or right top, middle, bottom.
I tried vips affine using this command and compared with rotation in gimp, could not achieve the same like in gimp (center at left middle). The command you suggested from other page is
Vips affine in.tif out.tif  "1 0.5 -0.5 1" --oarea "0 250 450 500". Tried with other combinations too.

What I get is a out.tif offset by 0,250
But I need the rotation Center at 0,250 ie left middle of the image.

**Comment by jcupitt** [comment]
Just use the affine equation and map the point you want to preserve through that. This seems to work for me:

```
#!/bin/bash

file=$1

width=$(vipsheader -f width $file)
height=$(vipsheader -f height $file)

# the transform matrix
a=1
b=0.5
c=-0.5
d=1

# the point in the input image we want to keep in the same position (left
# middle in this case)
x=0
y=$(bc <<< "scale=4; $height  / 2.0")

# where does (x, y) move to when transformed?
x_out=$(bc <<< "scale=4; $x * $a + $y * $b")
y_out=$(bc <<< "scale=4; $x * $c + $y * $d")

# so we want to output a rect which is offset by how much that point has moved
left=$(bc <<< "scale=0; $x_out - $x")
top=$(bc <<< "scale=0; $y_out - $y")

vips affine $file x.jpg "$a $b $c $d" --oarea "$left $top $width $height"
```

**Comment by vkkindia** [comment]
Thanks a lot, this works fine.

Need more examples like this so that more people will get good idea.

You yourself can put some exercise tasks, so that people will try to write
scripts.

**Comment by vkkindia** [comment]
I followed this tutorial, and works for resize by aligning corners from
left top 0,0.

http://libvips.blogspot.com/2011/12/task-of-day-resize-image-with-align.html?m=1

I tried to resize by other position, right top or bottom. But couldn't get.
Can you help me.

 Thanks

**Comment by jcupitt** [comment]
Hello, could you open a new issue please? You'll need to include some more explanation to help me understand what you want to do.
