### ISSUE TITLE
Nodejs wrapper?

### ISSUE THREAD

**Issue by viktorstaikov** [jcupitt/libvips#103]
Hi,

First, great job with the lib, man. It really kicks asses.
I saw there is ruby extension, but do you have plans make the library accessible to more platforms? I'm curious about Nodejs, because my server is build with it. Sadly the only two wrappers for libvips are poorly writen and crashes very easily :/

Thanks

**Comment by h2non** [comment]
@viktorstaikov I recently wrote a [small package](https://github.com/h2non/node-imaginary) to provide a fluent interface in node/io.js to [imaginary](https://github.com/h2non/imaginary) HTTP server, which is powered by libvips. With it you can perform common image operations, such as crop, rotate, resize...

**Comment by asilvas** [comment]
For those interested, [image-steam](https://github.com/asilvas/node-image-steam) leveraging the good work of @lovell's [sharp](https://github.com/lovell/sharp):

> A simple, fast, and highly customizable on-the-fly image manipulation web server built atop Node.js.

**Comment by jcupitt** [comment]
Here's a full libvips binding for php, done in a slightly different way:

https://github.com/jcupitt/php-vips-ext

It's 1,600 lines of C with no dependencies, other than libvips. It uses libvips's own introspection stuff to make a single php function called `vips_call` which can run any vips operation. 

On top of that, you then load this php module which layers an OO interface over `vips_call`:

https://github.com/jcupitt/php-vips

That's 1,200 lines of PHP and gives users a nice API. 

I'd think you could do something very similar for node.js. The PHP one was about a week's work.

**Comment by SuhairZain** [comment]
I take it that this is still in the works. @walling Were you able to complete the work on the bindings?

**Comment by jcupitt** [comment]
I've had a go at a node binding:

https://github.com/jcupitt/node-vips

It's based on node-ffi, so there's no native code, though obviously node-ffi is native.

It's dynamic, so it opens the libvips shared library and uses the libvips introspection facilities to expose operations. It seems to work: it has 60 or tests which pass cleanly and with no leaks. It can run code like this:

```javascript
vips = require('vips');

var image = vips.Image.new_from_file('k2.jpg');

var image = vips.Image.new_from_file('k2.jpg', {shrink: 2});

var pixel = Image.black(1, 1).add(value).cast(this.format);
var image = pixel.embed(0, 0, this.width, this.height,
    {extend: 'copy'});
image = image.copy({
    interpretation: this.interpretation,
    xres: this.xres,
    yres: this.yres,
    xoffset: this.xoffset,
    yoffset: this.yoffset
});     
image.write_to_file('x.png');
```

Unfortunately, I know nothing about node, so I've probably done lots of things wrong (naming, packaging, etc. etc.). It really needs a node expert to look it over and fix it up.

I plan to do a little bit more work on it, but then leave it for someone else to pick up and get production-ready (hopefully).

**Comment by asilvas** [comment]
Curious @lovell thoughts on ^ since he has a lot of experience with Node and vips.

**Comment by jcupitt** [comment]
I cross-posted to https://github.com/lovell/sharp/issues/241, discussion should probably move there.

**Comment by jcupitt** [comment]
I'll close, have a look at node-vips and open issues if you're interested. It's now complete and seems fast and stable, but it's probably some way of being suitable for production. A node expert should fix it up.
