### ISSUE TITLE
Magicksave JP2 compression rate option?

### ISSUE THREAD

**Issue by proyb6** [jcupitt/libvips#1031]
Usually in OpenJPEG2000, I would use -r option to apply compression rather than setting -q for quality

In JP2 encoding, they have a ```rate``` which I assume is similar to compression ratio?
https://www.imagemagick.org/script/jp2.php

What option could I use with Magicksave?

**Comment by proyb6** [comment]
@jcupitt is it possible to add rate parameter in libvips?

**Comment by jcupitt** [comment]
Hello, I've added a note on this to the magicksave issue. Thanks for pointing this out!

https://github.com/jcupitt/libvips/issues/839
