### ISSUE TITLE
Applying a watermark with positioning

### ISSUE THREAD

**Issue by janko-m** [jcupitt/libvips#1032]
Hello John,

I'm trying to figure out the best way to apply a watermark to an image with positioning. I've searched for previous questions, but the answers I found were pretty old. I was wondering how would one do it today using the new functions that libvips offers.

I'm trying to do the equivalent of the following ImageMagick command:

```
$ convert input.jpg watermark.png -gravity SouthEast -geometry +55+55 -composite output.jpg
```

This is what I came up with using ruby-vips:

```rb
original  = Vips::Image.new_from_file("path/to/original.jpg")
watermark = Vips::Image.new_from_file("path/to/watermark.png")

watermark = watermark
  .gravity(:centre, watermark.width + 110, watermark.height + 110)
  .gravity(:"south-east", original.width, original.height)

original.composite(watermark, :over)
```

This produces the same result for me as the ImageMagick command. However, it doesn't feel ideal that I have to know the original image dimensions, so I was wondering if there was something more elegant. Though this is still pretty short 😃

**Comment by jcupitt** [comment]
Hi @janko-m, `composite` in 8.7 has x, y parameters, so I guess you could also do:

```ruby
original  = Vips::Image.new_from_file("path/to/original.jpg")
watermark = Vips::Image.new_from_file("path/to/watermark.png")

original.composite(watermark, :over, 
    x: original.width - watermark.width - 55,
    y: original.height - watermark.height - 55)
```

Though it's not really much neater.

**Comment by janko-m** [comment]
Great, thanks for the reply 😃

**Comment by janko-m** [comment]
For future readers: since in my library I wanted to support libvips 8.6+ (and 8.7 isn't out at the moment anyway), this is what I came up with:

```rb
def composite(overlay, mode: "over", gravity: "north-west", offset: nil, **options)
  # makes it so that #gravity will use transparent background (otherwise it's black)
  overlay = overlay.add_alpha unless overlay.has_alpha?

  if offset
    opposite_gravity = gravity.to_s.gsub(/\w+/, "north"=>"south", "south"=>"north", "east"=>"west", "west"=>"east")
    overlay = overlay.gravity(opposite_gravity, overlay.width + offset.first, overlay.height + offset.last)
  end

  overlay = overlay.gravity(gravity, image.width, image.height)

  image.composite(overlay, mode, **options)
end
```

The following call:

```rb
composite(overlay, mode: "over", gravity: "south-east", offset: [10, 10])
```

seems to have equivalent behaviour as the corresponding ImageMagick command:

```
$ convert input.jpg watermark.png -gravity SouthEast -geometry +10+10 -composite output.jpg
```

I checked that this implementation works correctly with negative x/y offsets as well (the original version didn't). Anyway, maybe this helps someone in the future.
