### ISSUE TITLE
/usr/include/vips/vips8:35:25: fatal error: glib-object.h: No such file or directory

### ISSUE THREAD

**Issue by jackjacek** [jcupitt/libvips#1033]
Running Alpine 3.7
Can't seem to be able to `npm install attention` that depends on libvips
Seems to me libvips was installed correctly (compiled from source, not alpine package repo)
~ # pkg-config vips-cpp --cflags --libs
-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libgsf-1 -I/usr/include/libxml2 -I/usr/include/ImageMagick-7 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/orc-0.4 -I/usr/include/OpenEXR -I/usr/include/poppler/glib -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/poppler -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -pthread -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -lvips-cpp -lvips -lgobject-2.0 -lglib-2.0 -lintl

.. and glib-object.h seems to exist too

~ # ls -l /usr/include/glib-2.0/glib-object.h
-rw-r--r--    1 root     root          1478 Apr  9 13:21 /usr/include/glib-2.0/glib-object.h

Any help would be appreciated
Regards!

**Comment by jcupitt** [comment]
Hello @jackjacek, I think`attention` is now part of `sharp`. I would just install that.

`npm install sharp` 

should be all you need. See:

http://sharp.dimens.io/en/stable/api-resize/#crop

```javascript
const transformer = sharp()
  .resize(200, 200)
  .crop(sharp.strategy.attention)
  .on('error', function(err) {
    console.log(err);
  });
// Read image data from readableStream
// Write 200px square auto-cropped image data to writableStream
readableStream.pipe(transformer).pipe(writableStream);
```

**Comment by jackjacek** [comment]
Hello @jcupitt 
Thanks for response!

My coworker ended up using sharp instead, to try and resemble `attention` as close as possible:
```function getDominantColor (pipeline) {
  return pipeline
    .resize(5, 5)
    .crop(sharp.strategy.attention)
    .toBuffer()
    .then(buffer => {
      return sharp(buffer)
        .stats()
        .then(stats => {
          measure()
          console.log('getDominantColor stats', stats)

          const { channels: [r, g, b] } = stats

          return [
            Math.round(r.max),
            Math.round(g.max),
            Math.round(b.max)
          ]
        })
    })
}```
