### ISSUE TITLE
vips_resize downsampling using nearest kernel 'removes' important pixels and funny output

### ISSUE THREAD

**Issue by angelmixu** [jcupitt/libvips#1034]
Hi! 

Just using some resizing on images, I found a curious behaviour.

When resizing half size of an image, and using a nearest filter, some relevant pixels are removed. 
I have uploaded a zip file which contents are the following:

* TesterRGB.tif : original file
* tester_vipsout_050.tif : using an scale of 0.5
* tester_vipsout_049.tif : using an scale of 0.49
* TesterRGB_photoshop_out.tif : using photoshop to resize to half size

I've used this command line:

`vips resize TesterRGB.tif tester_vipsout.tif 0.5 --kernel nearest`

When using scale 0.5 the ruler pixels are missing, and when using 0.49, ruler appears intermittently.
What we are looking for is something like photoshop, the ruler and the top and left black border is is still shown.

[testing_resize_nearest.zip](https://github.com/jcupitt/libvips/files/2184486/testing_resize_nearest.zip)

Any suggestion?
Thanks!

**Comment by jcupitt** [comment]
Hello @angelmixu, yes, `nearest` will do this. Try `linear`, it should be closer to what you need.

**Comment by angelmixu** [comment]
Thanks! 
Linear looks like has some smoothing.
For the moment nearest works better for our needs.
