### ISSUE TITLE
how to do displacement mapping?

### ISSUE THREAD

**Issue by wppd** [jcupitt/libvips#1035]
hey @jcupitt , I know someone posted a similar issue before #937 

I encounter the same issue.

Would you give me some libvips hints on implementing displacement mapping?

thanks in advance!

**Comment by jcupitt** [comment]
Hello @wppd,

There was a blog post about the `mapim` operator, perhaps you saw?

http://libvips.blogspot.com/2015/11/fancy-transforms.html

I would just experiment with that code, I think.

**Comment by jcupitt** [comment]
Oh, that's using the old Python binding. With pyvips it would be:

```python
#!/usr/bin/python

import sys
import pyvips
import gi

def wobble(image):
    # this makes an image where pixel (0, 0) (at the top-left) has value [0, 0],
    # and pixel (image.width, image.height) at the bottom-right has value
    # [image.width, image.height]
    index = pyvips.Image.xyz(image.width, image.height)

    # make a version with (0, 0) at the centre, negative values up and left,
    # positive down and right
    centre = index - [image.width / 2, image.height / 2]

    # to polar space, so each pixel is now distance and angle in degrees
    polar = centre.polar()

    # scale sin(distance) by 1/distance to make a wavey pattern
    d = 10000 * (polar[0] * 3).sin() / (1 + polar[0])

    # and back to rectangular coordinates again to make a set of vectors we can
    # apply to the original index image
    index += d.bandjoin(polar[1]).rect()

    # finally, use our modified index image to distort the input!
    return image.mapim(index)

image = pyvips.Image.new_from_file(sys.argv[1])
image = wobble(image)
image.write_to_file(sys.argv[2])
```

**Comment by jcupitt** [comment]
To see what's going on, try saving the images and then examining them. nip2 works well for this.

**Comment by wppd** [comment]
@jcupitt 

it'd be a stupid question.

I created an image via xyz method. it's interesting that the pixel value in every coordinate is equal to the 
 coordinate, verified by `getpoint` method.

but I don't know how to see the pixel value in photoshop.... all rgb are 1,1,1

**Comment by jcupitt** [comment]
Did you try nip2? Save the image in vips format, then load into nip2 and have a look.

Windows and macOS binaries here, or check your package manager. 

https://github.com/jcupitt/nip2/releases

**Comment by wppd** [comment]
I get it open with nip2.

actually, for the accuracy, we want to create the index image with photoshop.

but due to the special requirement of the index image, we don't know how to set the pixel value correctly.

please let me explain my questions:

we create an image via vips_xyz 2000 2000

with vips_getpoint 1000 1000, we get the pixel value (1000, 1000)

we open it with photoshop and check the pixel values of the coordinate (1000, 1000), the pixel value is rgb 1, 1, 1. 

so, we don't know what the pixel value that vips retrieves is and we don't know how to set the pixel value in photoshop accordingly.

sorry, it'd be a stupid question but CV is not my field....

**Comment by jcupitt** [comment]
Hello again,

I don't think you'll be able to use photoshop. The index image needs to be floating point, and photoshop can't handle floating point images (I think). nip2 should be fine, as long as you use vips (`.v`) format.

What are you trying to achieve?

**Comment by wppd** [comment]
thanks for your help anyway.

we want to bend/wrinkle the t-shirt to make it more real-life.

we've done this with imagemagick via `-compose displace` but the speed is sort of slow.
