### ISSUE TITLE
 g_object_unref: assertion 'G_IS_OBJECT (object)' failed

### ISSUE THREAD

**Issue by tczf1128** [jcupitt/libvips#1042]
so many such errors in my program, how to avoid it?

**Comment by jcupitt** [comment]
Hello @tczf1128,

You need to give more information. What language are you using, what platform are you running on, what code are you executing?

**Comment by tczf1128** [comment]
hi ，I use govips,  in macos and linux, most of its operations would cause this warnning

**Comment by jcupitt** [comment]
Sorry, I don't have anything to do with govips, you'll need to ask there.
