### ISSUE TITLE
No scale property for PNGs?

### ISSUE THREAD

**Issue by wyatt121** [jcupitt/libvips#1045]
Hi John,

I switched file formats for my overlay graphic from SVGs to PNGs.

Now when I run my code, I get this error:

PHP Fatal error:  Uncaught Jcupitt\Vips\Exception: pngload: no property named `scale'
 in /var/www/html/build/vendor/jcupitt/vips/src/Image.php:664

Apparently, I'm unable to use scale with PNGs?  What is the best method for me to embed a PNG overlay without this scale function?

My existing code:

```
"A1" => array ("design_width" => 250,"dx" => 175,"dy" => 120,"da" => 1,),
 );

$apparel = "A1";
$apparel_image = "test1.jpg";   
$design_image = "test.png";  

$design_width = $coordinates[$apparel]['design_width'];
$dx = $coordinates[$apparel]['dx'];
$dy = $coordinates[$apparel]['dy'];


$base = Vips\Image::newFromFile($apparel_image);
$overlay = Vips\Image::newFromFile($design_image);


$base_width = $overlay->width;
$scale = $design_width / $base_width;


$overlay = Vips\Image::newFromFile("$design_image", ["scale" => $scale]);
$overlay = $overlay->similarity(["angle" => $da]);
$overlay = $overlay->multiply([1.0, 1.0, 1.0, 0.9]);
$overlay = $overlay->embed($dx, $dy, $base->width, $base->height);

$out = $base->composite2($overlay, "over");


$str = $out->writeToBuffer(".jpg[Q=95]");
```

Any help is much appreciated.

Regards,

Wyatt

**Comment by jcupitt** [comment]
Hello, you can do:

```php
$overlay = $overlay->similarity(["angle" => $da, "scale" => $scale]);
```

But it'll start to look bad if you scale up too much. SVGs are much better for overlays.

It would probably be better to shrink the shirt image down to match the size of the PNG overlay.

**Comment by wyatt121** [comment]
Hi John,

You're the man!  This worked perfectly.  Thank you very much for your help.

Regards,

Wyatt
