### ISSUE TITLE
vips_rank - no property named 'cryptic'

### ISSUE THREAD

**Issue by Hilarius86** [jcupitt/libvips#1053]
Hi,
I didn't find any mailing list or other place to ask questions, so I try it as an issue.

I am running median filtering using the C API. Works fine on my development machine, but after copying the executables to another machine it crashes with "no property named " and then a cryptic entry.

Compiled the demo which is running fine from the same directory on my second machine.

```C
#include "stdafx.h"
#include <stdio.h>
#include <vips/vips.h>

int
main( int argc, char **argv )
{
  VipsImage *in;
  VipsImage *out;

  if( VIPS_INIT( argv[0] ) )
    vips_error_exit( NULL ); 

  if( argc != 3 )
    vips_error_exit( "usage: %s infile outfile", argv[0] ); 
  
  if( !(in = vips_image_new_from_file( argv[1], NULL )) )
    vips_error_exit( NULL );

  printf( "image width = %d\n", vips_image_get_width( in ) ); 

  if( vips_rank( in, &out, 21, 21, 220 ) )
    vips_error_exit( NULL );

  g_object_unref( in ); 

  if( vips_image_write_to_file( out, argv[2], NULL ) )
    vips_error_exit( NULL );

  g_object_unref( out ); 

  return( 0 );
}
```

I am working on Win7 x64, Visual Studio 2012 and used vips-dev-8.6

Any hints where to start looking for errors?

My initialization

```C
if (VIPS_INIT (inout.WStringToString(__targv[0]).c_str()))
{
	const char* retErr = vips_error_buffer();
	std::string stri (retErr);
	AfxMessageBox(inout.StringToWString(stri).c_str());
}
```

Function that fails

```C
VipsMedianFilter(std::string inImage, std::string outImage)
{
VipsImage *in;
VipsImage *out;

if( !(in = vips_image_new_from_file( inImage.c_str(), NULL )) )
	AfxMessageBox(_T("vips_image_new_from_file"));		

int width = vips_image_get_width( in );
AfxMessageBox(inout.StringToWString(std::to_string(width)).c_str());

if( vips_rank( in, &out, 21, 21, 220 ) )
{		
	const char* retErr = vips_error_buffer();
	std::string stri (retErr);
	AfxMessageBox(inout.StringToWString(stri).c_str());
}

g_object_unref( in ); 

if( vips_image_write_to_file( out, outImage.c_str(), NULL ) )
	AfxMessageBox(_T("write to file"));

g_object_unref( out ); 
}
```

I checked if I am able to run other functions. vips_embed works fine. I read the same file that I would need for vips_rank and saved using the same output file name.

Regards
Felix

**Comment by jcupitt** [comment]
Hello @Hilarius86, yes, fine to ask questions here.

You've forgotten the `NULL` at the end of the `vips_rank()` call. gcc will warn about errors like this, but sadly MSVC will not.

**Comment by jcupitt** [comment]
It's just random. If there happens to be a NULL on the stack in the right place, you'll be OK.
