### ISSUE TITLE
Missing libs in v8.7.0-rc1

### ISSUE THREAD

**Issue by bender22** [jcupitt/libvips#1055]
Hi John,
When using vipsheader.exe from v8.7.0-rc1 (vips-dev-w64-all-8.7.0) I get the following error:
The code execution cannot proceed because libintl-8.dll was not found.
The same error for zlib1.dll
There are no such files in bin directory (suppose there are libintl-9.dll and libz.dll instead)

**Comment by jcupitt** [comment]
Hello @bender22,

I tried here in Wine and it works for me. Could there be a problem with your PATH? Perhaps you have an old libvips on there?

**Comment by bender22** [comment]
Thank you for checking, that was my environment problem
