### ISSUE TITLE
vips_get_image data remains in RAM after unreffing

### ISSUE THREAD

**Issue by Fingolfin1196** [jcupitt/libvips#1056]
Using the following code,

```C++
#include <vips/vips8>
#define PRINT_MEMORY(prefix) printf(#prefix ": %u, %i, %i\n", static_cast<unsigned int>(vips_tracked_get_mem()), vips_tracked_get_allocs(), vips_tracked_get_files());

int main() {
    if (VIPS_INIT ("Test")) vips_error_exit(nullptr);
    vips_leak_set(true);

    PRINT_MEMORY(01);
    auto* image{vips_image_new()};
    PRINT_MEMORY(02);
    vips_gaussnoise(&image, 1 << 14, 1 << 14, nullptr);
    PRINT_MEMORY(03);
    // if (!vips_image_get_data(image)) printf("No data!\n");
    // PRINT_MEMORY(04);
    auto* converted{vips_image_new()};
    PRINT_MEMORY(05);
    vips_gaussblur(image, &converted, 10, "precision", 0.1, nullptr);
    PRINT_MEMORY(06);
    if (!vips_image_get_data(converted)) printf("No data!\n");
    PRINT_MEMORY(07);
    g_object_unref(converted);
    PRINT_MEMORY(08);
    g_object_unref(image);
    PRINT_MEMORY(09);
    return 0;
}
```
I get the following output:
```
01: 0, 0, 0
02: 0, 0, 0
03: 0, 0, 0
05: 0, 0, 0
06: 2368, 8, 0
07: 1073744208, 9, 0
08: 1073744208, 9, 0
09: 1073744208, 9, 0
2 objects alive:
0) VipsImage (0x55d732583010), count=1
VipsImage (image), image class, 1x1 uchar, 1 band, multiband
1) VipsImage (0x55d732583330), count=1
VipsImage (image), image class, 1x1 uchar, 1 band, multiband
memory: high-water mark 1.27 GB
```
I see two issues here:
- The memory that is allocated in ``vips_image_get_data(converted)`` is not freed; this is averted when the part that I commented out is added back in, which wastes a lot of RAM. It is also strange that the ``vips_leak_set`` report does not report this memory.
- The ``vips_leak_set`` report reports two 1x1 uchar images, even when the comment is added back in.

These were encountered using libvips v8.7.0-rc1 compiled by gcc 7.3.0 on Ubuntu 18.04.1 LTS.

**Comment by jcupitt** [comment]
Hello @Fingolfin1196,

You don't need the `vips_image_new()` calls. When you call `vips_gaussnoise()`, a new image object is created and a pointer to it assigned to the parameter. Try:

```C++
VipsImage *image
vips_gaussnoise(&image, 100, 100, nullptr);
```

Of course you should really test the return value, so this is better:

```C++
VipsImage *image
if(vips_gaussnoise(&image, 100, 100, nullptr))
    handle_error();
```

That's the C API. For C++ you can just write:

```
VImage image{VImage::gaussnoise(1 << 14, 1 << 14)};
```

And it'll do all the unrefs and error checks for you.

The memory from `vips_image_get_data()` is associated with the `converted` object, so it is freed when `converted` is freed.  It's being held open by the vips operation cache: set that to cache zero operations and your memory should be freed earlier. 

With this version of your program:

```C++
/* compile with:
 *
 *      g++ -Wall fing.cpp `pkg-config vips-cpp --cflags --libs`
 *
 */

#include <vips/vips8>

#define PRINT_MEMORY(prefix) printf(#prefix ": %u, %i, %i\n", static_cast<unsigned int>(vips_tracked_get_mem()), vips_tracked_get_allocs(), vips_tracked_get_files());

int
main(int argc, char **argv)
{
    VipsImage *image;
    VipsImage *converted;

    if (VIPS_INIT (argv[0])) 
            vips_error_exit(nullptr);

    vips_leak_set(true);
    vips_cache_set_max(0);

    PRINT_MEMORY(1);
    PRINT_MEMORY(2);
    vips_gaussnoise(&image, 1 << 14, 1 << 14, nullptr);
    PRINT_MEMORY(3);
    // if (!vips_image_get_data(image)) printf("No data!\n");
    // PRINT_MEMORY(4);
    PRINT_MEMORY(5);
    vips_gaussblur(image, &converted, 10, "precision", 0.1, nullptr);
    PRINT_MEMORY(6);
    if (!vips_image_get_data(converted)) printf("No data!\n");
    PRINT_MEMORY(7);
    g_object_unref(converted);
    PRINT_MEMORY(8);
    g_object_unref(image);
    PRINT_MEMORY(9);

    return 0;
}
```

I see:

```

john@yingna ~/try $ ./a.out
1: 0, 0, 0
2: 0, 0, 0
3: 0, 0, 0
5: 0, 0, 0
6: 2368, 8, 0
7: 1073744208, 9, 0
8: 0, 0, 0
9: 0, 0, 0
memory: high-water mark 1.18 GB
```

**Comment by Fingolfin1196** [comment]
Thanks a lot! I obviously misunderstood something about the use of ``vips_image_new``, and I completely ignored caching. Actually, I use the C++ version in my project, but for checking where problems arise, I decided to use the C version and not the wrapper.
You're answer was also very helpful in understanding some other problems I had with VIPS in the aforementioned project (nudging me in the right direction), so I'm very grateful.

**Comment by jcupitt** [comment]
Glad it helped!
