### ISSUE TITLE
VipsOperation: class \"magickload_buffer\" not found

### ISSUE THREAD

**Issue by tczf1128** [jcupitt/libvips#1057]
I did this    ./configure --with-magickpackage=GraphicsMagick when I compile vips，but when I load bmp image,it fails.

and it works ok when I use brew insall --with-magickpackage=GraphicsMagick

**Comment by jcupitt** [comment]
Hello @tczf1128,

Perhaps you are missing the GraphicsMagick devel package? You need to check the output of configure. Near the end, I see:

```
* optional dependencies
use fftw3 for FFT: 			yes
Magick package: 			GraphicsMagick
Magick API version: 			magick6
load with libMagick: 			yes
save with libMagick: 			no
```

To verify that your GM is installed correctly, try:

```
john@yingna ~/GIT/libvips (master) $ pkg-config GraphicsMagick --modversion
1.3.28
```

**Comment by tczf1128** [comment]
you are right. sorry
