### ISSUE TITLE
pyvips rotation 270 takes moreeee time

### ISSUE THREAD

**Issue by vkkindia** [jcupitt/libvips#1062]
im = pyvips.Image.new_from_file(input_filename, access="sequential")
im = im.rot90()
tile = im.crop(left_crop, top_crop, width, height)
print "Copying to mem"
tile = tile.copy_memory()
print "Copying to mem Done"

It takes about 4 Secs
if im = im.rot90() is  replaced by im = im.rot180() takes 13s
but If i give im = im.rot270() or im = im.affine(transform, idx=0.5, idy=0.5, background=255)
It takes forever, almost 13 Min
vips rot in out d270 takes 48Secs
The image is a Image Width: 28400 Image Length: 34000 2400dpi
How to improve speed.

**Comment by jcupitt** [comment]
I don't think that program will work, will it? You've enabled sequential access mode and that'll stop any rotate operations working. 

If I run it on a 10k x 10k RGB JPG image, I see:

```
john@kiwi:~/try$ time ./try272.py ~/pics/wtc.jpg 90
rotate transform is [0.0, -1.0, 1.0, 0.0] 
Croping..
Croping Done
Draw rect..
Traceback (most recent call last):
  File "./try272.py", line 38, in <module>
    float(tile.height), fill=255)
  File "/home/john/.local/lib/python2.7/site-packages/pyvips/vimage.py", line 799, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/home/john/.local/lib/python2.7/site-packages/pyvips/voperation.py", line 176, in call
    op.set(name, flags, match_image, args[n])
  File "/home/john/.local/lib/python2.7/site-packages/pyvips/voperation.py", line 81, in set
    value = value.copy().copy_memory()
  File "/home/john/.local/lib/python2.7/site-packages/pyvips/vimage.py", line 440, in copy_memory
    raise Error('unable to copy to memory')
pyvips.error.Error: unable to copy to memory
  VipsJpeg: out of order read at line 9372
```

If I remove the `access="sequential"` it runs quickly, but of course it is not very useful.

You can replace your affine call with

```
im = im.similarity(angle=90)
```

and it'll calculate the transform matrix and call affine for you.

Did you see the chapter about sequential mode? It explains why you can't use it for this type of operation:

http://jcupitt.github.io/libvips/API/current/How-it-opens-files.md.html

**Comment by jcupitt** [comment]
Please reopen if this is still a problem.
