### ISSUE TITLE
Icc transform incorrect color

### ISSUE THREAD

**Issue by kaas3000** [jcupitt/libvips#1063]
Hi,

I am implementing pyvips into an existing python application.
Uploaded photos are currently processed with PIL/pillow and converted from cmyk to srgb when neccessary.
An example cmyk image is:

![jdj5jda0jgznv0tmum45atfhelpmvu9xcwgymnvxuki5r0fkeerzs2putw9frdbrshnhteltufdaahvp](https://user-images.githubusercontent.com/2116782/44146319-5742eab6-a08f-11e8-911a-2aaef2a42540.jpg)

The icc transform as done by PIL looks as follows:
![pil](https://user-images.githubusercontent.com/2116782/44146814-af77fe72-a091-11e8-8086-2ef34142449c.png)

While the Vips transform results in this file:
![vips](https://user-images.githubusercontent.com/2116782/44146836-be94ae32-a091-11e8-9cf0-50c08dedd48b.png)

How can this happen when both libraries use LittleCMS to handle the transform? Is this a bug in libvips?

Thank you very much,
Kees

The vips version used is `vips-8.6.4-Wed Jun 13 15:24:52 UTC 2018`, and the code used to transform both images is this:
~~~python
import pyvips
from PIL import Image, ImageCms

input_filename = '/Users/kees/Downloads/JDJ5JDA0JGZNV0tmUm45aTFhelpmVU9XcWgyMnVxUkI5R0FkeERzS2puTW9FRDBRSHNHTElTUFdaaHVp.jpg'
cmyk_icc_filename = '/Users/kees/Projects/generator/app/profiles/default_cmyk.icc'
srgb_icc_filename = '/Users/kees/Projects/generator/app/profiles/sRGB_v4_ICC_preference.icc'

pil_image = Image.open(input_filename)  # type: Image
cmyk_pil_profile = ImageCms.ImageCmsProfile(cmyk_icc_filename)
pil_image = ImageCms.profileToProfile(pil_image, cmyk_pil_profile, srgb_icc_filename, outputMode='RGB')

vips_image = pyvips.Image.new_from_file(input_filename)  # type: pyvips.Image
vips_image = vips_image.icc_transform(srgb_icc_filename, input_profile=cmyk_icc_filename)


pil_image.save('pil.png')
vips_image.write_to_file('vips.png')
~~~

**Comment by jcupitt** [comment]
Actually, I tried your program with these profiles:

https://github.com/jcupitt/nip2/blob/master/share/nip2/data/cmyk.icm

https://github.com/jcupitt/nip2/blob/master/share/nip2/data/sRGB.icm

And I get identical results:

![vips](https://user-images.githubusercontent.com/580843/44150653-0afe39ea-a098-11e8-91a7-7b22da9d69ea.png)
![pil](https://user-images.githubusercontent.com/580843/44150663-11f70ea2-a098-11e8-9037-75a16fd753b1.png)

So I think there's something fishy about your CMYK profile. Changing the libvips intent might help, or you could try using that cmyk profile.

**Comment by jcupitt** [comment]
Off-topic, but you could change your program to be:

```python
vips_image = pyvips.Image.new_from_file(input_filename, access='sequential')
```

For simple things like ICC transforms, libvips can stream the image from source to destination. This means it can execute PNG load, ICC transform and PNG save in parallel, for a nice speed-up and drop in memory use.

There's a chapter in the manual about this:

http://jcupitt.github.io/libvips/API/current/How-it-opens-files.md.html

**Comment by jcupitt** [comment]
... I tried a benchmark:

```python
import sys
import pyvips

input_filename = sys.argv[1]
output_filename = sys.argv[2]
cmyk_icc_filename = sys.argv[3]
srgb_icc_filename = sys.argv[4]

vips_image = pyvips.Image.new_from_file(input_filename, access='sequential') 
vips_image = vips_image.icc_transform(srgb_icc_filename, input_profile=cmyk_icc_filename) 

vips_image.write_to_file(output_filename)
```

```python
import sys
from PIL import Image, ImageCms

input_filename = sys.argv[1]
output_filename = sys.argv[2]
cmyk_icc_filename = sys.argv[3]
srgb_icc_filename = sys.argv[4]

pil_image = Image.open(input_filename)  # type: Image
cmyk_pil_profile = ImageCms.ImageCmsProfile(cmyk_icc_filename)
pil_image = ImageCms.profileToProfile(pil_image, cmyk_pil_profile, srgb_icc_filename, outputMode='RGB')

pil_image.save(output_filename)
```

And with a 10k x 10k pixel RGB JPG image I see:

```
john@kiwi:~/try$ /usr/bin/time -f %M:%e python try274.py x.jpg x2.jpg ~/vips/share/nip2/data/cmyk.icm ~/vips/share/nip2/data/sRGB.icm 
707644:24.86
john@kiwi:~/try$ /usr/bin/time -f %M:%e python try273.py x.jpg x2.jpg ~/vips/share/nip2/data/cmyk.icm ~/vips/share/nip2/data/sRGB.icm 
59412:4.78
```

**Comment by kaas3000** [comment]
Thank you very much for your help @jcupitt!
The solution was your first comment. Changing the intent to "perceptual" made the output the same.

Not only do you provide an answer, I also get a code review with it :).

Again, thank you so much!

Kees
