### ISSUE TITLE
Building an osx static binary for vipsthumbnail?

### ISSUE THREAD

**Issue by cylott** [jcupitt/libvips#1067]
Hi there, I love VIPS and would like to use it in a free, open source Mac app I'm developing. I was wondering if there is any way to compile a static binary on osx. I did build from source but I see what is created is a small shell script with a 60mb libvips library folder. The functionality I'm hoping to use is confined to vipsthumbnail - performing some basic image operations. Is it possible to build a small binary that can accomplish this? Thanks!

**Comment by jcupitt** [comment]
Hi @cylott,

I would build everything to a private prefix, then write a small wrapper script to set the various environment variables and run the executable. This is what nip2.app does -- there's a build system here:

https://github.com/jcupitt/build-osx

It makes a 25mb dmg for the whole of nip2, gtk and libvips. There's a possible vips wrapper script here:

https://github.com/jcupitt/libvips/blob/master/tools/vips-8.7

A fully static exe would be a lot of work and I think only be slightly simpler to deploy.

**Comment by cylott** [comment]
Hi John, thanks for the reply, I'll check it out!

**Comment by jcupitt** [comment]
A docker image would be another good solution. It's surprisingly quick. Sample Dockerfiles here:

https://github.com/jcupitt/docker-builds

**Comment by cup** [comment]
https://github.com/libvips/libvips/issues/1067
https://github.com/libvips/libvips/issues/1079
https://github.com/libvips/libvips/issues/280
https://github.com/libvips/libvips/issues/365
