### ISSUE TITLE
Median filtering

### ISSUE THREAD

**Issue by Hilarius86** [jcupitt/libvips#1071]
Hi,
I tried your median implementation and it works like a charm. Sadly my images have "empty" pixel that are presented as zeros and therefore included in the filtering. Think of a cluster of data that is surrounded by zeros so it is shrunk by median filtering (with big kernel).
Is there a pixel value like NaN in Matlab, that I can use to exclude pixel from the calculation?
Regards
Felix

**Comment by jcupitt** [comment]
Hi Felix,

How about filling the 0 pixels with their local median, then taking the median again? You should get the right result then (I think).

**Comment by jcupitt** [comment]
In Ruby:

```ruby
# replace 0 pixels by their local median
image = (image == 0).ifthenelse(image.median, image)

# take the median again and it'll be (roughly) as if the 0 pixels were being ignored
image = image.median
```

**Comment by Hilarius86** [comment]
Thanks for your super fast response and the nice idea.
I will try it out, but ... won't the second median again cut the corners from my cluster? I attached the (cropped) raw image and the median result for clarity.
![median](https://user-images.githubusercontent.com/16589816/44411212-481e6980-a566-11e8-8540-f21d8ca5f679.png)
![raw](https://user-images.githubusercontent.com/16589816/44411213-481e6980-a566-11e8-891f-638d6088d0dc.png)

**Comment by Hilarius86** [comment]
Zero should be zero. But I can change that with a mask as well, like in your proposal.

I was thinking of editing the source, but never worked without CMake for a project and also always used Visual Studio. So was hoping for another solution.

**Comment by jcupitt** [comment]
Hmm, the best accuracy would be to use `fill_nearest`, then median, then mask. It wouldn't be very quick though :( The "what's new in 8.6" page has a couple of sample images:

http://jcupitt.github.io/libvips/2017/11/28/What's-new-in-8.6.html

There isn't really a proper zero-ignoring median, unfortunately.

**Comment by Hilarius86** [comment]
I will try it out as well and see if it is applicable.
For the non-zero median, I thought of tracking the number of zeros in die moving window and adjusting the element that needs sorting. But to be honest, with highly optimized algorithms, that may be too naive.

**Comment by jcupitt** [comment]
I had a quick go:

```ruby
require 'vips'

image = Vips::Image.new_from_file ARGV[0]

# replace all 0 pixels with the value in the nearest non-zero pixel ... this
# operator is rather slow, unfortunately
x = image.fill_nearest

# now take the median: along image edges (where it borders a zero region) the
# fill_nearest should mean that 0 pixels are effectively ignored
x = x.median

# now mask out any pixels which were 0 in the original
x = (x == 0).ifthenelse(0, image)

x.write_to_file ARGV[1]
```

It makes this:

![x](https://user-images.githubusercontent.com/580843/45109083-5fe51880-b136-11e8-8548-21111b2023e7.png)

I think it's probably correct, but it is a bit slow :(
