### ISSUE TITLE
Count the pixels in 1 bit tiff to get ink usage

### ISSUE THREAD

**Issue by vkkindia** [jcupitt/libvips#1075]
Good morning,

Is it possible to get pixel count for eg. The tiff size is 80wx70h and filled with 50% dots the count should give 50. If it has multiple halftones also it should give the count.so that the ink consumed details can be known.
How can be done using vips.
Thanks

**Comment by jcupitt** [comment]
Hello @vkkindia,

Sure, it should be easy. Post a sample image and I'll make an example.

**Comment by vkkindia** [comment]
https://drive.google.com/file/d/1MEi2Kw2hRQaNds7gatqZEs-eKlQCYBy2/view?usp=drivesdk


sample image,

normally it will be divided into 16 stripes, of equal col, so this image of
695x568 divided into 16 stripes of equal col, i need the values for each
column.

Thanks

**Comment by jcupitt** [comment]
Using Ruby, this makes a CSV of the columns:

```ruby
require 'vips'

image = Vips::Image.new_from_file ARGV[0]

puts "width = #{image.width}, height = #{image.height}"
puts "column, left, width, percent"

(0..15).each do |i|
    left = (i * image.width / 16).to_i
    right = ((i + 1) * image.width / 16).to_i
    width = right - left
    
    strip = image.crop left, 0, width, image.height
    percent = 100 * (1 - strip.avg / 255)

    puts "#{i}, #{left}, #{width}, #{percent}"
end
```

I see:

```
$ time ruby ~/try/halftone.rb Black.tif 
width = 35200, height = 28800
column, left, width, percent
0, 0, 2200, 11.239084595959593
1, 2200, 2200, 13.452280618686874
2, 4400, 2200, 9.799561237373744
3, 6600, 2200, 12.755184659090911
4, 8800, 2200, 10.749763257575761
5, 11000, 2200, 7.644794823232326
6, 13200, 2200, 10.521111111111114
7, 15400, 2200, 12.500959595959593
8, 17600, 2200, 9.179064078282828
9, 19800, 2200, 7.863574810606055
10, 22000, 2200, 7.500348800505052
11, 24200, 2200, 7.5020707070707076
12, 26400, 2200, 6.475609217171707
13, 28600, 2200, 6.90850536616161
14, 30800, 2200, 8.556182133838385
15, 33000, 2200, 6.157337436868692
```

**Comment by jcupitt** [comment]
... so you use `crop` to extract a column of pixels, then `avg` to calculate the average pixel value. Pixels are 0 for black and 255 for white, so from the average you can calculate the percentage of black.

**Comment by vkkindia** [comment]
Excellent , c or c++ version pls. I forget to mention this.

**Comment by jcupitt** [comment]
It's just crop and avg, it should be very easy to translate to C/C++.
