### ISSUE TITLE
8.6/8.7 compatibility

### ISSUE THREAD

**Issue by remicollet** [jcupitt/libvips#1077]
Hi,

8.7.0-rc2 still use same soname (libvips.so.42), so should be ABI compatible

According to abi-compliance-checker this is not true, see 
https://rpms.remirepo.net/compat_reports/libvips/8.6.5_to_8.7.0-rc2/compat_report.html

At list, prototype change in `vips__get_bytes `and  `vips_region_shrink` are critical (part of the public API).

**Comment by remicollet** [comment]
@jcupitt with 8.7.0-rc2, test suite of pecl/vips fails

TEST 13/28 [tests/013.phpt]
========DIFF========
001+ 
001- pass
========DONE========
FAIL write_to_buffer works [tests/013.phpt]

**Comment by jcupitt** [comment]
OK, git master has a stub for vips_region_shrink(). Thanks for pointing this out!

**Comment by jcupitt** [comment]
There's rc3 now with this fix, please open another issue if that's also broken :( 

https://github.com/jcupitt/libvips/releases/tag/v8.7.0-rc3
