### ISSUE TITLE
Static compile of user c program

### ISSUE THREAD

**Issue by vkkindia** [jcupitt/libvips#1079]
Good morning,

Pls suggest how to compile user c program as static (atleast it includes vips lib), so for easier portability.

 I followed the sample program in 

https://jcupitt.github.io/libvips/API/current/using-from-c.html

Also how to suppress warning messages.
Thanks

**Comment by jcupitt** [comment]
No one really supports static linking any more -- modern libraries are just too complicated. You could try writing the link line yourself, but it won't work well. 

To make a portable binary on linux, I would use docker, flatpak or snap.

I would not get rid of warning messages. Instead, fix the problems in your code. I think you will find warnings make development much safer and simpler.

If you really must hide all useful and helpful warnings, remove the `-Wall` flag from the compile line.

**Comment by vkkindia** [comment]
Ok,

It's not warning during compiling, it's during applying a VIPs command, Ian
getting VIPs warning unsupported tiff tag like that.

**Comment by jcupitt** [comment]
Ah OK. You can set `VIPS_WARNING` to hide messages.

```
$ vipsheader d0189946-3170-48b1-97fb-3c5604972066.tif 
(vipsheader:20431): VIPS-WARNING **: 09:49:03.712: Unknown field with tag 37724 (0x935c) encountered
d0189946-3170-48b1-97fb-3c5604972066.tif: 5552x3840 ushort, 3 bands, rgb16, tiffload
$ VIPS_WARNING=1 vipsheader d0189946-3170-48b1-97fb-3c5604972066.tif 
d0189946-3170-48b1-97fb-3c5604972066.tif: 5552x3840 ushort, 3 bands, rgb16, tiffload
```

**Comment by vkkindia** [comment]
Ok, how to add VIPs warning in my c prog.

**Comment by jcupitt** [comment]
libvips uses the standard glib logging system:

https://developer.gnome.org/glib/stable/glib-Message-Logging.html

So this:

```
static void
my_log_handler( const gchar *log_domain, GLogLevelFlags log_level,
        const gchar *message, gpointer user_data )
{
}

...
    
    g_log_set_handler( "VIPS", G_LOG_LEVEL_WARNING, my_log_handler, NULL );
```

will capture all warning messages.

**Comment by vkkindia** [comment]
thanks that worked. :)

**Comment by cup** [comment]
https://github.com/libvips/libvips/issues/1067
https://github.com/libvips/libvips/issues/1079
https://github.com/libvips/libvips/issues/280
https://github.com/libvips/libvips/issues/365

**Comment by joshuarli** [comment]
FWIW while I wasn't able to convince the build system, it's possible with staticx. Read [here](https://stackoverflow.com/a/62526516/5348393).

**Comment by vkkindia** [comment]
Good it will be helpful for lot of people.
