### ISSUE TITLE
vips_fractsurf without FFTW support

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/libvips#1082]
Hi John,

When libvips is compiled without FFTW support and `vips_fractsurf` is called it will throw this error:
```
VipsOperation: class "fwfft" not found
```
See:
https://github.com/jcupitt/libvips/blob/f9cbc7263d9d933d2bfea3a5b71a09ab9f19359d/libvips/freqfilt/freqmult.c#L101

Perhaps `vips_fractsurf` should be excluded for compilation when there is no FFTW support?

**Comment by jcupitt** [comment]
Hello Kleis,

It could of course, but the error message would just change to `class "fractsurf" not found`. Is that much better? And it would add an extra thing that would need maintaining.

**Comment by jcupitt** [comment]
There are quite a few other operators that will not work if you build without fftw:

```
john@yingna ~/GIT/libvips/libvips (master) $ grep -l fwfft */*.c
freqfilt/freqfilt.c
freqfilt/freqmult.c
freqfilt/fwfft.c
freqfilt/invfft.c
freqfilt/phasecor.c
freqfilt/spectrum.c
```

I think the way you've done your `fractsurf` test is probably the best solution.

**Comment by kleisauke** [comment]
I see. It is indeed better to keep it in this way for reasons of code maintainability and descriptive error messages. Thanks!
