### ISSUE TITLE
If input image doesn't have a transparency band, then output doesn't either

### ISSUE THREAD

**Issue by vibbix** [jcupitt/libvips#1086]
Recently we discovered a [PNG](https://www.kayak.com/provider-logos/airlines/v/EK.png) without a transparency band. When trying to downsize it, we realized our output PNG had black bars added around it. Is there any way to programmatically force an alpha band to be added to the input image, so black bars aren't added when exporting to an alpha-friendly format like WebP or PNG?

**Comment by jcupitt** [comment]
Hello @vibbix,

Sure, what language are you using? In Ruby it's

```ruby
x = Vips::Image.new_from_file "EK.png"
x = x .add_alpha if not x.has_alpha?
```

But I think you shouldn't get black bars, even without an alpha. What version of libvips are you using, and how are you shrinking images? 

I tried:

```
$ vipsthumbnail EK.png -o tn_EK.png
```

And I see:

![tn_ek](https://user-images.githubusercontent.com/580843/45408022-0cf1f080-b663-11e8-8ee8-97f516540c2b.png)

**Comment by jcupitt** [comment]
Ah OK, yes adding alpha to the input is probably your best solution for transparent edges on the output. You can get PNGs with one band as well (ie. mono with no alpha), you might need to handle that too.

What operation are you using for the downsize? I was worried you might be using affine.

**Comment by vibbix** [comment]
I am using {{vips_thumbnail_buffer}} to perform downsizing during the load process, then padding it out with {{vips_embed}} after the initial shrink is performed. using {{vips_addalpha}} during the padding process fixed the issue I was having, I should have realized {{vips_embed}} inherited the bands from the input image. Thank you for the help!
