### ISSUE TITLE
Details:Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Biron36** [jcupitt/libvips#1094]
```
$ PORT=1337 node app.js -n map
An error has occured. error is: Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory and stack trace is: `include-all` attempted to `require(/var/www/map.app.local/api/services/UploadService.js)`, but an error occurred:: 
Details:Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/map.app.local/node_modules/sharp/lib/constructor.js:8:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/map.app.local/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
Process will exit now.
```

node -v v8.12.0
npm -v 6.4.1
vips -v vips-8.7.0-Thu Aug 30 11:56:06 UTC 2018

$ whereis vips
vips: /usr/local/bin/vips

$ whereis libvips
libvips: /usr/local/lib/libvips.so /usr/local/lib/libvips.la /usr/local/lib/libvips.a

$ pkg-config --modversion vips-cpp
8.7.0

How I can fix error?

**Comment by Biron36** [comment]
```
$ ldd node_modules/sharp/build/Release/sharp.node
	linux-vdso.so.1 =>  (0x00007ffdf0747000)
	libvips-cpp.so.42 => not found
	libvips.so.42 => not found
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f94ea063000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f94e9d4f000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f94e9a47000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f94e9745000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f94e952f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f94e9312000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f94e8f51000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f94e8cef000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007f94e8ae6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f94ea4fe000)

```

**Comment by jcupitt** [comment]
OK, I'll close. Glad it's fixed

**Comment by zeroxx1986** [comment]
In case anyone bumps into this issue and tries to solve it for 10+ hours straight in all the possible ways one can think of, and nothing works.. Here's the solution which finally worked for me - dumb me.

0. Install homebrew if you don't have it - look it up, it's a oneliner
1. Install the global version of `libvips` via homebrew: `brew install vips`
2. Optionally, if the `pkg-config` command is not recognized, `brew install pkg-config`
3. Just to make sure everything works, relog into the terminal and then run `pkg-config --modversion vips-cpp` - it should work properly now and provide you with a version number.
4. Remove the existing `sharp` module via `npm remove sharp`, then install it again via `npm install --ignore-scripts=false --foreground-scripts --verbose sharp` (nothing fancy here, just so you'll have logs to check if anything goes sideways..)
5. At this point sharp will not yet work as it won't find `libvips.so.42` nor `libvips-cpp.so.42` - this is where the above linked solution from `johnkeep` helped with earlier; BUT it won't work as-is with the brew install method - so let's solve it..
6. Find where your `libvips.so.42` is really residing on your machine by running the command `find / -name libvips.so.42` - surprise, brew stores it (at least on my installation..) at `/home/linuxbrew/.linuxbrew/lib/libvips.so.42` - so we need to add this directory into the proposed solution instead:
7. Run `sudo nano /etc/ld.so.conf.d/usrlocal.conf` and add the directory into the empty file: `/home/linuxbrew/.linuxbrew/lib/` then save it - your mileage may vary, please make sure you add here the correct directory which you've found earlier. I also don't think the `usrlocal` part of the filename is important, probably you can get away naming it whatever as long as it's a new `file.conf` (does even the .conf matter?..)
8. Run `sudo ldconfig -v` to reload shared libraries
9. Just to make sure everything is found now, inside your node project's root folder, run `ldd node_modules/sharp/build/Release/*.node | grep libvips` - you should see an output where both libvips SOs are properly mapped, and nothing is saying "not found" anymore.

And why did I went through all of this 10+ hours of torture? Just to make sharp work with HEIC files coming out of iphones..

**Comment by jcupitt** [comment]
Hi @zeroxx1986, thanks for the notes. What platform is this?

**Comment by zeroxx1986** [comment]
It's the official ubuntu 22.04 docker image (actually pulled from ubuntu:latest a while ago..).
At this point it's quite stuffed with everything else as beforehand I was also trying to translate the (dockerized) centos7 based sharp-libvips compilation to ubuntu as I couldn't make the centos7 dockerfile to produce a binary which included heif support.

I managed to make my solution above a bit better now, as instead of brew, I'm following libvips' guide on compilation + still having the ld.so.conf.d solution at the end to resolve the missing libvips.so.42 - but as this method does not want to compile the early universe itself too (🤪) it seems not to cause issues with the system if I include the needed path in ld.so.conf.d.

I'll update my solution to this once I clean it up a bit and check what's actually needed for compilation out of a bazillion things I've installed prior in the docker image.

**Comment by jcupitt** [comment]
Ah I see. The libvips in ubuntu 22.04 already supports HEIC, so you might be OK just using that. I see:

```
$ docker run -it --rm -v ~/pics:/data ubuntu:22.04
root@0c543ea268ef:/# apt update
... snip
root@0c543ea268ef:/# apt install libvips-tools --no-install-recommends
...
Need to get 44.3 MB of archives.
After this operation, 160 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
...
root@0c543ea268ef:/# vips copy /data/20200313_115653.heic /data/x.jpg
root@0c543ea268ef:/# 
```

So I would just use `apt install libvips-dev --no-install-recommends`, then install sharp and ask it to use the platform libvips.

**Comment by jcupitt** [comment]
Background: HEIC decode has a range of patent, licence and security issues, so sharp can't bundle the code in the libvips that it distributes. But most recent linuxes have libvips binaries which already include HEIC support, so you can just use those.

**However**, you should be cautious:

1. The ubuntu libvips (for example) includes a number of loaders which are not safe against malicious files, so you need to consider security very carefully. It might be worth building your own libvips with just the loaders you need. There are some sample dockerfiles here, for example:

https://github.com/jcupitt/docker-builds/tree/master/libvips-pdfium-ubuntu20.04

2. libvips 8.13 and later have a new feature which is supposed to make using the platform libvips safer:

https://www.libvips.org/2022/05/28/What's-new-in-8.13.html

   Though sadly this hasn't yet filtered into many of the distros in use. I think ubuntu 22.10 will have it

3. You should also consider patent and licencing conditions (of course).

**Comment by zeroxx1986** [comment]
Thanks John - very good to know these! 
TBH I didn't even bother trying the packaged libvips on ubuntu due to heic's licensing and whatnot, thought I needed to compile it myself - which I did succeed on eventually.
Now I'm going to try to shorten my solution even more with your approach :)
