### ISSUE TITLE
magicksave is not listed in the function list

### ISSUE THREAD

**Issue by janko-m** [jcupitt/libvips#1097]
Hello again 👋 

I noticed that the new `magicksave` saver from the 8.7 version isn't present in the [list of libvips functions](http://jcupitt.github.io/libvips/API/current/func-list.html). It is present in the `VipsForeignSave` documentation, though.

**Comment by jcupitt** [comment]
Ooop there's always so much to remember, duh.

Thanks for pointing this out!
