### ISSUE TITLE
How can I know if libvips build with libjpeg-turbo instead of libjpeg?

### ISSUE THREAD

**Issue by 781545872** [jcupitt/libvips#1098]

**Comment by jcupitt** [comment]
You can swap the jpeg library at runtime, they have the same ABI.

On linux, see which library is being used at runtime with:

```
john@yingna ~/GIT/libvips (master) $ ldd $(which vips) | grep jpeg
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f359c70f000)
```

Then use your package manager to see which package supplied that library.

**Comment by 781545872** [comment]
Thank you very much!
