### ISSUE TITLE
Compiling latest source and running python examples fails with NotImplementedError

### ISSUE THREAD

**Issue by benjamind** [jcupitt/libvips#199]
Ok so I'm on Ubuntu and did the following steps:

```bash
git clone https://github.com/jcupitt/libvips.git
cd libvips
./bootstrap.sh
./configure
make
sudo make install
```

I then setup my environment variables for local usage like so:

```bash
export VIPSHOME=/usr/local
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VIPSHOME/lib
export PATH=$PATH:$VIPSHOME/bin
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$VIPSHOME/lib/pkgconfig
export MANPATH=$MANPATH:$VIPSHOME/man
export PYTHONPATH=$VIPSHOME/lib/python2.7/site-packages
```

Finally I ensured that `/usr/local/lib/girepository-1.0' contained `Vips-8.0typelib` and I ensured this was added to the GI_TYPELIB_PATH with:

```bash
export GI_TYPELIB_PATH=$VIPSHOME/lib/girepository-1.0
```

Now when I try to run the `try3.py` script found in `python/example` I get the following output:

```bash
bdelarre@dev-01:~/libvips/python/example$ ./try3.py ~/test.pnm
Traceback (most recent call last):
  File "./try3.py", line 8, in <module>
    from gi.repository import Vips
  File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 68, in load_module
    dynamic_module._load()
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 289, in _load
    self._overrides_module = importlib.import_module('gi.overrides.' + self._namespace)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Vips.py", line 55, in <module>
    unpack_types = [Vips.Blob, Vips.ArrayDouble, Vips.ArrayImage, Vips.ArrayInt]
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 226, in __getattr__
    raise NotImplementedError(info)
NotImplementedError: <gi.BoxedInfo object (Blob) at 0x0x7fb209dd86e8>
```

**Comment by jcupitt** [comment]
It seems to be fixed again, I'll close. Thanks!

**Comment by benjamind** [comment]
Turns out I have to run on Ubuntu 13.x, so I'm back to trying to fix this bug.

Just installed python-gi, here's the output from dpkg -s python-gi:
```bash
Package: python-gi
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 788
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: pygobject
Version: 3.8.0-2ubuntu1
Replaces: python-gobject (<< 3.0.2-4)
Provides: python2.7-gi
Depends: python (>= 2.7.1-0ubuntu2), python (<< 2.8), libc6 (>= 2.14), libgirepository-1.0-1 (>= 1.32.1), libglib2.0-0 (>= 2.34.2), gir1.2-glib-2.0 (>= 1.34.2)
Pre-Depends: multiarch-support
Suggests: python-gi-cairo
Breaks: python-aptdaemon (<< 1.0), python-gobject (<< 3.0.2-4), python-nautilus (<= 1.1-1), software-center (<< 5.6.0-0ubuntu3)
```
This produces the same NotImplemented error detailed above.

I then uninstalled python-gi and installed python-gobject instead, here's the dpkg:

```
Package: python-gobject
Status: install ok installed
Priority: extra
Section: oldlibs
Installed-Size: 40
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Source: pygobject
Version: 3.8.0-2ubuntu1
Depends: python-gi (>= 3.8.0-2ubuntu1), python-gobject-2
```
Also results in the same error as above.

Any suggestions on where I go from here?

**Comment by jcupitt** [comment]
Hi, that's 3.8,0-2, you need 3.12.0 or later. 

You'll need to build your own python-gi, sorry :( Uninstall the Ubuntu one and install from source to /usr/local. Set PYTHONPATH (you probably have this set already, I guess?) and you should be OK. 

I'll have a go at building the latest one here and see if I can make it work.

**Comment by jcupitt** [comment]
I tried here and got 3.14.0 (the current stable release) working on ubuntu 14.10. Here's what I did:

- don't touch the standard ubuntu python gi stuff, you'll break everything :-( 
- download from http://ftp.gnome.org/pub/GNOME/sources/pygobject/3.14/
- I added `py3cairo` as well from synaptic
- untar, `./configure`, `make`, `sudo make install` as usual

This will install to /usr/local:

```bash
$ ls /usr/lib/python3/dist-packages/gi/
_constants.py                              __init__.py         pygtkcompat.py
docstring.py                               module.py           repository
_gi_cairo.cpython-34m-x86_64-linux-gnu.so  _option.py          _signalhelper.py
_gi.cpython-34m-x86_64-linux-gnu.so        overrides           types.py
_gobject                                   _propertyhelper.py
importer.py                                __pycache__
```

- copy `Vips.py` to that overrides directory
- make sure there's no `Vips.py` in the system overrides area, `/usr/lib/python3/dist-packages/gi/overrides`
- set `PYTHONPATH` to make Python pick up the new `gi` area before the old one: 

```
$ export PYTHONPATH=/usr/local/lib/python3.4/site-packages
```

- start Python and verify that it's picking up the new gi stuff:

```
$ python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Vips
>>> a = Vips.Image.new_from_file("/home/john/pics/k2.jpg")
>>> 
```

**Comment by benjamind** [comment]
Thanks @jcupitt that helped...

Sadly however I'm still mired in upgrading packages, seems like there's a whole slew of dependencies here that I'll need to recompile for 13.x. pygobject-3.14 seems to depend on glib >= 2.38 which isn't available on this version of ubuntu so now I'm off compiling that.

Might be easier to force our sys admins to update all the boxes :-)

**Comment by alexanderharm** [comment]
Hello, I have a similar issue on SLES12 and I have no clue what the problem is. I compiled VIPS from source and it runs fine from command line. However, when I import in Python I also receive a NotImplementedError. Here is the output:
```
ext_harm@neo:~/vips/vips-8.4.2> /usr/bin/python3
Python 3.4.1 (default, Jun 19 2014, 14:40:48) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Vips
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib64/python3.4/site-packages/gi/importer.py", line 68, in load_module
    dynamic_module._load()
  File "/usr/lib64/python3.4/site-packages/gi/module.py", line 289, in _load
    self._overrides_module = importlib.import_module('gi.overrides.' + self._namespace)
  File "/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib64/python3.4/site-packages/gi/overrides/Vips.py", line 101, in <module>
    unpack_types = [[Vips.Blob, lambda x: bytes(x.get())],
  File "/usr/lib64/python3.4/site-packages/gi/module.py", line 226, in __getattr__
    raise NotImplementedError(info)
NotImplementedError: <gi.BoxedInfo object (Blob) at 0x0x7faf9d6e1bc0>
>>>
```

**Comment by jcupitt** [comment]
I would guess your pygobject is too old. Do you know what version you are using?

**Comment by alexanderharm** [comment]
I use `3.12.2`. That is the latest version that is compatible with the `gobject-introspection` package provided by SUSE. Problem is that compiling a later version of  `gobject-introspection` entails a lot more of compiling, due to "outdated" packages.
Should I try and compile `vips-7.42.3`? I want to use `dzsave`, ideally with python bindings.

**Comment by alexanderharm** [comment]
Or use vips as subprocess?

**Comment by jcupitt** [comment]
It sounds like 3.12 isn't working either, sorry.  

I think you don't need to compile very much more. Try 3.14 as noted above:

http://ftp.gnome.org/pub/GNOME/sources/pygobject/3.14/

You don't need to update the whole of gobject-introspection, you just need a newer python interface to it. 

I'm getting cheesed off with gobject introspection, it seems to make more work, not reduce it :( I've just done a php binding which uses a bit of hand-written C instead of GOI, and it's not actually that much effort. Perhaps there should be a new pyvips which does not use pygobject.

**Comment by jcupitt** [comment]
Yes, you can shell out to `vips dzsave` as well, of course, though you won't get things like progress feedback.

**Comment by alexanderharm** [comment]
Thanks a million, that did the trick. Maybe update the `configure` file. One more question if I may: I could not figure out the option to set concurrency from Python. I tried `img.dzsave(dirname, vips_concurrency=1)` and a couple of others...

**Comment by jcupitt** [comment]
Hey, glad it's working. Yes, I'll set the min version to 3.13 and hope that's good enough. 

You can do:

```
Vips.concurrency_set(12)
```

somewhere. It's the same as the C API:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/VipsOperation.html#vips-concurrency-set

You can also set the `VIPS_CONCURRENCY` environment variable.

**Comment by alexanderharm** [comment]
Yes, it is 3.12.2

Problem is that SLES only provides an old version of gobject-introspection and compiling a later version is a headache.
