### ISSUE TITLE
vips warning: vips_tracked: out of memory --- size == 12973MB

### ISSUE THREAD

**Issue by mvictoras** [jcupitt/libvips#215]
I have a ndpi file that is roughly 900MB.

I run 

```vips dzsave in.ndpi out```

and I get a seg fault:

```vips warning: vips_tracked: out of memory --- size == 12973MB
Segmentation fault```

Any ideas?

**Comment by mvictoras** [comment]
Forgot to mention that I am on an openSuse 13.1 with 16G of memory.

**Comment by jcupitt** [comment]
Wow that shouldn't be possible. dzsave allocates enough memory to hold a strip of tiles, so image-width * tile-size * sizeof-pixel. tile-size defaults to 256, so even for a 200,000 pixel wide image it shouldn't need more than a few hundred mb. 

Is there any way you could get me a copy of the image? I could make you an account on my server, if that would help.

**Comment by jcupitt** [comment]
Ah I have an idea, what version of openslide are you using?

ndpi reading was added in openslide 3.4.0. If you try with a version before that, vips will try to read your image with the TIFF reader, since .ndpi uses the tiff container. .ndpi tiffs put the entire image into a single strip, so vips has to allocate enough memory for the entire image before it can load it with libtiff. That could cause your 12gb error.

**Comment by mvictoras** [comment]
That was it!

I was using openslide 3.3.0 and after upgrading to 3.4.0 it works!
FYI: vips configure with 3.3.0 works, I did not get a warning or error
complaining for the openslide error:

```file import with OpenSlide: yes
  (requires openslide-3.3.0 or later)```

Now I am trying to do the conversion in my code (using js), using this
library (https://github.com/mvictoras/sharp) that I extended to work with
deepzoom files. It works with small files, but with the big one I am still
getting the same error. Unfortunately I cannot send you the big file, for
the known medical reasons.

Any ideas?

Victor


On Sat, Jan 10, 2015 at 5:16 AM, John Cupitt <notifications@github.com>
wrote:

> Ah I have an idea, what version of openslide are you using?
>
> ndpi reading was added in openslide 3.4.0. If you try with a version
> before that, vips will try to read your image with the TIFF reader, since
> .ndpi uses the tiff container. .ndpi tiffs put the entire image into a
> single strip, so vips has to allocate enough memory for the entire image
> before it can load it with libtiff. That could cause your 12gb error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcupitt/libvips/issues/215#issuecomment-69450903>.
>



-- 
*Victor Mateevitsi*
PhD Candidate - University of Illinois at Chicago <http://www.uic.edu/>
Research Assistant - Electronic Visualization Laboratory
<http://www.evl.uic.edu/>
mvictoras@gmail.com
www <http://www.vmateevitsi.com> | LinkedIn
<http://www.linkedin.com/pub/5/919/845> | Twitter
<http://twitter.com/mvictoras> | UIC <http://www.uic.edu> | EVL
<http://www.evl.uic.edu>

**Comment by mvictoras** [comment]
I have checked with ldd and it is loading the correct vips and openslide libraries. I have also deleted the old ones and recompiled everything, just to be sure.

**Comment by mvictoras** [comment]
I am also getting these warnings:
vips warning: TIFFReadDirectory: Unknown field with tag 65426 (0xff92) encountered
vips warning: TIFFReadDirectory: Unknown field with tag 65428 (0xff94) encountered

I also tried with a aperio file and it works. Here is the test data that I used:
Aperio file 373MB (works) http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-2.svs
Hamamatsu file 270MB (does not work) http://openslide.cs.cmu.edu/download/openslide-testdata/Hamamatsu/CMU-3.ndpi

**Comment by mvictoras** [comment]
I apologize for the multiple comments, I think I have narrowed it on the sharp library side. I thinks sharp regards it as a TIFF instead of an Aperio, or Hamamatsu and therefore breaks. I am debugging now, will post an update once I have a solution.

**Comment by jcupitt** [comment]
Try at the command-line. If it works there but not in sharp, you have a linking problem. Try removing and rebuilding sharp.

**Comment by jcupitt** [comment]
```
 FYI: vips configure with 3.3.0 works, I did not get a warning or error complaining for the openslide error:
```

Yes, vips will work with 3.3.0, just not with .ndpi.

**Comment by mvictoras** [comment]
Found it! It was a switch case that was not handling the openslide case. It
was trying to open using the tiff loader, instead of the openslide loader!

Thank you for your help!

Victor

On Sat, Jan 10, 2015 at 1:01 PM, John Cupitt <notifications@github.com>
wrote:

>  FYI: vips configure with 3.3.0 works, I did not get a warning or error complaining for the openslide error:
>
> Yes, vips will work with 3.3.0, just not with .ndpi.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcupitt/libvips/issues/215#issuecomment-69465163>.
>



-- 
*Victor Mateevitsi*
PhD Candidate - University of Illinois at Chicago <http://www.uic.edu/>
Research Assistant - Electronic Visualization Laboratory
<http://www.evl.uic.edu/>
mvictoras@gmail.com
www <http://www.vmateevitsi.com> | LinkedIn
<http://www.linkedin.com/pub/5/919/845> | Twitter
<http://twitter.com/mvictoras> | UIC <http://www.uic.edu> | EVL
<http://www.evl.uic.edu>

**Comment by jcupitt** [comment]
Good stuff, I'll close.
