### ISSUE TITLE
Problem with paths

### ISSUE THREAD

**Issue by peterbe** [jcupitt/libvips#216]
It seems `vipsthumbnail` is extremely picky about the path of the output file

```
% ~/tiler/server (master *=)$ vipsthumbnail ./static/uploads/a/bd/2525cb.jpg -s 2048 -o ./static/uploads/a/bd/2525cb-3-2048.jpg
vipsthumbnail: unable to thumbnail ./static/uploads/a/bd/2525cb.jpg
vips__file_open_write: unable to open file "./static/uploads/a/bd/./static/uploads/a/bd/2525cb-3-2048.jpg" for writing
% ~/tiler/server (master *=)$ vipsthumbnail ./static/uploads/a/bd/2525cb.jpg -s 2048 -o static/uploads/a/bd/2525cb-3-2048.jpg
vipsthumbnail: unable to thumbnail ./static/uploads/a/bd/2525cb.jpg
vips__file_open_write: unable to open file "./static/uploads/a/bd/static/uploads/a/bd/2525cb-3-2048.jpg" for writing
% ~/tiler/server (master *=)$ pwd
/Users/peterbe/tiler/server
% ~/tiler/server (master *=)$ vipsthumbnail ./static/uploads/a/bd/2525cb.jpg -s 2048 -o /Users/peterbe/tiler/server/static/uploads/a/bd/2525cb-3-2048.jpg
```

Basically, it's not working until I give the output path a full absolute path. Then it worked.

**Comment by jcupitt** [comment]
Hi Peter, this is actually by design. If you use a relative path with -o, it's relative to the directory of the input file. This lets you do things like:

```bash
$ vipsthumbnail a/*.jpg b/*.jpg -o thumbs/%s.jpg
```

Now the thumbnails will be written to `a/thumbs` and `b/thumbs`. The argument to -o is more like a format pattern than an output file name. I'll see if I can make the docs clearer.

**Comment by jcupitt** [comment]
I added a note to the vipsthumbnail man page.

**Comment by peterbe** [comment]
Wow! That is surely surprising. I can see the feature benefit. 
What would you expect if it was 
```
$ vipsthumbnail a/*.jpg b/*.jpg -o ./thumbs/%s.jpg
```
though?

**Comment by jcupitt** [comment]
Perhaps the problem is the abuse of the `-o` switch. It certainly doesn't behave in the way that `-o` usually does. How about renaming it as `--format`, `-f`, as in, it sets the output format. It might be less surprising.

We could keep `-o` as a hidden, deprecated alias.

**Comment by jcupitt** [comment]
OK, renamed -o as -f, though -o stays as a hidden flag.

**Comment by sachinwalia2k8** [comment]
Sorry to post in an old ticket but I've a question regarding output paths. If I want to specify an absolute output path then is it possible to use -f flag?

**Comment by jcupitt** [comment]
Yes, it should work. Open a new issue if you have problems.
