### ISSUE TITLE
Disable chroma subsampling in tiffsave

### ISSUE THREAD

**Issue by iwbh15** [jcupitt/libvips#218]
Hi John,
is there an option to deactivate chroma subsampling when using jpeg compression in the ‘tiffsave’ command?
I realized that due to the jpeg compression the image content will be corrupted especially in regions of saturated color intensities. I verified that this effect can also be seen using the ‘jpegsave’ command (and even with other software) but will not happen if the option ‘no-subsampling’ is used with ‘jpegsave’.
In ‘tiffsave’ this option ‘no-subsampling’ is not known. Is there anything I can do?
Regards,
Peter

**Comment by jcupitt** [comment]
Hi Peter, no, this isn't possible with tiffsave. I'll see if there's an easy way to add this.

**Comment by jcupitt** [comment]
Actually, I'd forgotten, there's a "secret" flag to tiffsave which disables chrominance subsampling. Try:

```
vips tiffsave x.png x.tif --compression=jpeg --rgbjpeg
```

Here's the issue where this came up before: https://github.com/jcupitt/libvips/issues/99

Thinking about this again, how about disabling chrominance subsampling automatically when Q > 90? I think that's what imagemagick does.

**Comment by jcupitt** [comment]
Seems to work ... chroma subsample now goes off in tiffsave if Q>=90.

**Comment by iwbh15** [comment]
John, many thanks. That's a great news.
