### ISSUE TITLE
vipsthumbnail exit code is 0 on file load error

### ISSUE THREAD

**Issue by alex88** [jcupitt/libvips#219]
Hi there, I was using vipsthumbnail and I've seen that on failure due unknown file format I still get 0 as exit code:

```bash
/tmp $ echo "somefakefile" >> test.jpg
/tmp $ vipsthumbnail --size 128 --output out.jpg test.jpg
vipsthumbnail: unable to thumbnail test.jpg
VipsForeignLoad: "test.jpg" is not a known file format
/tmp $ echo $?
0
/tmp $ vips im_jpeg2vips test.jpg test.v
VipsJpeg: Not a JPEG file: starts with 0x73 0x6f
/tmp $ echo $?
1
```

is that expected?

**Comment by jcupitt** [comment]
Yes, that's expected behaviour. The idea was that if you are doing something like:

```bash
$ vipsthumbnail *.jpg
```

You don't want it to stop with an error on the first bad file.

I suppose it could exit with an error code if one or more conversions fail.

**Comment by alex88** [comment]
Maybe an error if all the conversions fails at first

**Comment by jcupitt** [comment]
I've made it ignore errors, but on final exit if one or more conversions failed, it returns a -1 exit code. Does that seem reasonable?

**Comment by alex88** [comment]
I'm not sure if negative exit status are commonly used but I haven't found anything against that, for me everything different from 0 is ok ;)

**Comment by jcupitt** [comment]
The ERRNO convention is usually positive numbers for system functions, negative for user code, I think. -1 (or 255) is just a generic error. I hope!

**Comment by alex88** [comment]
I don't think many will argue on this, for me it's fine!
