### ISSUE TITLE
Tiff reading problem - ouput is always all black

### ISSUE THREAD

**Issue by Topochicho** [jcupitt/libvips#220]
The bug is exclusive to 8bit tiff, and is actually caused by what I believe is a incorrectly formatted color table, however, every viewer I have tried works around the issue, so our customers are expecting that we should too.  Tifftopnm has the same issue when using the -byrow switch, however is it able to handle the file without byrow.

I have a attached 2 tiffs (I had to had the gif extension to get github to upload them, but if you save them and strip the .gif extension, they should be proper tiffs).  These files are tests files I manufactured by taking the color table from a file with proprietary data and attaching it to files I created with the same dimensions.

If you compare the 2 tiffs in hex (I used "xxd -p -c 1 <in> > <out>" to get a single, plain column for each & then opened them in vim in compare mode "vim -d <file list>") you will see that there is only 1 byte different @ line 99527. ("zR" to show all lines, then "]c" to jump to first difference)

From reading the spec I believe that tiff requires that the color table be encoded as 16bit values.  It appears that you can still use 8 bit values in the table, and just leave the other byte NULL.  However, it would appear that the library that is generating these files is byte swapping the color table.  The files are encoded as Intel, but the color table is motorola.

![8bitprob tif](https://cloud.githubusercontent.com/assets/8440045/5723891/3c89af2e-9b0d-11e4-9b95-2bec79639477.gif)

![8bitgood tif](https://cloud.githubusercontent.com/assets/8440045/5723815/9ef0b1cc-9b0c-11e4-9c75-dd8df0b1013a.gif)

**Comment by jcupitt** [comment]
Hi, I agree, I see a problem here too, I'll investigate. Thanks for the report!

**Comment by jcupitt** [comment]
I'm not sure this is real tiff difference. There's one byte deleted at line 99527 and one byte added at the end. They are actually different at all bytes inbetween, which looks (I think) like the palette arrays are just all shifted right one byte. That would produce what looks like a byte swap.

Reading libtiff, there's TIFFIsBigEndian(), which is used in a few places to byte-swap, but your two files have the same endianness. There's no code to byte swap uint16 arrays read from a file and no official mechanism for doing this.

We could look through the palette arrays and if all top bytes are zero, assume that the writer forgot to lshift before write. It seems a bit hacky to me. 

I'll see if I can see what other libraries are doing for this case. Your two images read the same in eog, though I think that's using TIFFReadRGBA(). There might be some code to check in there.

**Comment by jcupitt** [comment]
Ah, I think I found it, there's some magic code in tif_getimage.c:

```C
static int
checkcmap(TIFFRGBAImage* img)
{
    uint16* r = img->redcmap;
    uint16* g = img->greencmap;
    uint16* b = img->bluecmap;
    long n = 1L<<img->bitspersample;

    while (n-- > 0)
        if (*r++ >= 256 || *g++ >= 256 || *b++ >= 256)
            return (16);
    return (8);
}
```

This tests if an image has an old-style 8-bit colourmap, ie. the top bytes are all zero. If this is true, libtiff skips the >>.

What a horrible hack! I'll put something similar into libvips.

**Comment by Topochicho** [comment]
You are correct, I " fixed" the palette array in the "good" tiff by shifting it, adding 1 byte to the beginning of the array and removing one from the end.
Apparently, the 3rd party tif lib that is being used to create these files has been around for a while and is used in a number of large packages (in my industry) that originated on Unix.  My guess, based on personal experience with just this type of thing, is that when they ported to Windows the palette arrays were the wrong Endian, and instead of paying to fix the bug in the lib, they told they viewers to deal with it.
Of course, now that means that everyone gets to have a nasty little hack buried in their code.
I figured I might have to do the same thing and pre-process the file, but sent it to you hoping there was some kind of hack already built in that just needed to be called.

**Comment by jcupitt** [comment]
If the library that wrote these tiffs is very old, it could just be writing an old-style 8-bit colourmap. You can show the problem like this:

```bash
$ tiff2rgba problem.tif x.tif
problem.tif: Warning, Assuming 8-bit colormap.
```

`tiff2rgba` is a program that ships with libtiff, the message is produced if the checkcmap() function fails and libtiff guesses that this is an old-style cmap.

I think cmaps have been 16 bits for 20 years, but their code could be that crusty. You could show them this issue, they are certainly writing non-standard TIFFs, they might fix it.

**Comment by Topochicho** [comment]
Good to know, I have tiff2rgba but have never played with it.
We have informed the particular offender in this case and the 3rd party lib, and who knows, someone may do something, but I am not holding my breath.

**Comment by jcupitt** [comment]
OK, I'll close. There will be a new vips in a day or two with this fix.
