### ISSUE TITLE
vipsthumbnail: colored background for jpg output

### ISSUE THREAD

**Issue by tkoenig** [jcupitt/libvips#221]
Hi,

I've read that you can provide a background color for converting transparent images to jpeg:

`vipsthumbnail transparent.png -s 1024 -o %s.jpg[background=255]`

I'm not able to figure out the correct format for using a colored background. How can you enter a VipsArrayDouble from the command line (if thats even the correct format)? 

Thanks,
Thomas

**Comment by jcupitt** [comment]
Hi Thomas, try:

```bash
$ vipsthumbnail Opera-icon-high-res.png -o "tiny.jpg[background=128 255 128]"
```

All array elements are separated by spaces in command-line arguments. You need the extra quotes to stop the shell breaking the argument up.

**Comment by jcupitt** [comment]
Did this fix it? Please reopen if it didn't.

**Comment by tkoenig** [comment]
yes, sorry for not letting you know earlier and thanks again for your help! :+1:
