### ISSUE TITLE
Failure when rotating large Tiffs to a non 90 degree angle

### ISSUE THREAD

**Issue by Topochicho** [jcupitt/libvips#222]
I have attached a tiff (I had to put on .gif extension, so rename to *.tif when saving) that fails in VIPS when rotating to a non-90degree angle (I have been specifically testing with 20degrees).  It fails on both linux and windows.  I am using similarity because I may need to scale at the same time too and have also tried im_affinei_all (I know one calls the other, but wanted to make sure).
Output type does not seem to matter, rotation at 90degrees increments is fine, and other input types such as PNG or BMP are able to handle to the rotation, so it does seem to be a tiff specific problem.

The error on Windows is:
"MapViewOfFile failed: vips_mapfile: unable to MapViewOfFile
windows error: Not enough storage is available to process this command.

MapViewOfFile failed: vips_mapfile: unable to MapViewOfFile
windows error: Not enough storage is available to process this command.

vips_mapfile: unable to MapViewOfFile
windows error: Not enough storage is available to process this command.

vips_mapfile: unable to MapViewOfFile
windows error: Not enough storage is available to process this command.

vips_mapfile: unable to MapViewOfFile
windows error: Not enough storage is available to process this command."

![fail tif](https://cloud.githubusercontent.com/assets/8440045/5761884/06c2c892-9ca4-11e4-9e34-ee6cfe8274e1.gif)

FYI: You have been very responsive to bugs, but this is not a high priority problem for us.  We were testing functionality for a potential expansion of capabilities in one of our products & this is something we will eventually add, but I am in no hurry to make the GUI changes required at this point.

**Comment by jcupitt** [comment]
The image is huge! 90,000 x 4,000 pixels. With a 20 degree rotate, you'll get a 90,000 x 35,000 pixel image, or about 12GB. This works:

```bash
$ time vips similarity dead.tif x.tif[bigtiff] --angle 20 --vips-progress
```

but it's horribly slow. For each line of output tiles 128 pixels high, vips needs to scan the whole input image. For 4000 pixels high, it'll need to scan the input more than 30 times. It's going to spend ages stuck in IO.

**Comment by jcupitt** [comment]
It finished in 10 minutes on my laptop:

```
$ time vips similarity dead.tif x.tif[bigtiff] --angle 20 --vips-progress
vips temp-15: 1 x 1 pixels, 4 threads, 1 x 16 tiles, 1280 lines in buffer
vips temp-15: done in 0.000739s          
vips temp-1: 83905 x 34070 pixels, 4 threads, 128 x 128 tiles, 256 lines in buffer
vips /tmp/vips-1-R85DSX.v: 87714 x 4331 pixels, 4 threads, 87714 x 1 tiles, 256 lines in buffer
vips /tmp/vips-1-R85DSX.v: done in 13s          
vips temp-1: done in 574s          
memory: high-water mark 338.06 MB

real	9m38.756s
user	0m53.357s
sys	0m18.824s
```

You can ask vips to process via ram rather than a temporary disc file. This makes it a lot quicker, though obviously needs loads of memory. About 2m 30s:

```
$ VIPS_DISC_THRESHOLD=2g time vips similarity dead.tif x.tif[bigtiff] --angle 20 --vips-progress
vips temp-15: 1 x 1 pixels, 4 threads, 1 x 16 tiles, 1280 lines in buffer
vips temp-15: done in 0.000751s          
vips temp-1: 83905 x 34070 pixels, 4 threads, 128 x 128 tiles, 256 lines in buffer
vips temp-16: 87714 x 4331 pixels, 4 threads, 87714 x 1 tiles, 256 lines in buffer
vips temp-16: done in 4.55s          
vips temp-1: done in 146s          
memory: high-water mark 1.58 GB
70.94user 8.97system 2:32.13elapsed 52%CPU (0avgtext+0avgdata 1673776maxresident)k
7560inputs+22333640outputs (67major+11047minor)pagefaults 0swaps
```

**Comment by jcupitt** [comment]
... the error you were getting was (I think) because the file was too large for TIFF. You need to turn on bigtiff output. Or perhaps there's a Windows problem with MapViewOfFile on very large files?

**Comment by jcupitt** [comment]
Are you still seeing problems on Windows? Please reopen if you are.

**Comment by Topochicho** [comment]
Both methods worked on Linux, but not on Windows.  It could be just hitting the basic limitations of the 32bit binary on Windows.  I will need to recompile as 64bit on Windows to verify... that should be interesting.  That is not something I am going to be able to do right away, so you can consider this case closed until i can get back with further results.

One question though, I did search for environmental variables or options to alter tiff thresholds & memory limits but I did not find "bigtiff" or "VIPS_DISC_THRESHOLD".  Where do I look these kinds of things, or has documentation just not caught up to development yet?

**Comment by jcupitt** [comment]
It should work on 32-bits as well, I'll reopen and try to test on a Windows machine.

VIPS_DISC_THRESHOLD is on vips_image_new_from_file():

http://www.vips.ecs.soton.ac.uk/supported/7.42/doc/html/libvips/VipsImage.html#vips-image-new-from-file

There should probably be an index of environment variables.

bigtiff is part of vips_tiffsave():

http://www.vips.ecs.soton.ac.uk/supported/7.42/doc/html/libvips/VipsForeignSave.html#vips-tiffsave

**Comment by jcupitt** [comment]
There's now a 64-bit Windows binary, which might help:

http://www.vips.ecs.soton.ac.uk/supported/current/win32/vips-dev-w64-8.1.1-1.zip

It includes the .def and .lib files and should be easy to use with VS. It might help this issue.
