### ISSUE TITLE
Rotation around the image center

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#225]
What are the correct "idx", "idy", "odx" and "ody" values to pass to vips_similarity() in order to rotate the image around its center?

I seem to get the good result with this:

     vips_similarity(srcimg, &out, "angle", rotate_angle.get(),
          "idy", (double)-1*srcimg->Ysize/2,
          "ody", (double)srcimg->Ysize/2,
          NULL) )

but I cannot really get the logic behind it...

Thanks for helping!

**Comment by jcupitt** [comment]
Do you want to show an image plus a rotated copy overlaid? Could you just align the image centres?

idx/idy are really to change the sampling convention.xoffset/yoffset will give the position of the input origin in the output, if that helps.

**Comment by aferrero2707** [comment]
After a bit more thinking, I've realized that my question probably does not make much sense... the rotation operation works actually ok for me without any shifting.

Sorry for the spam.
