### ISSUE TITLE
Broken dependency link to libpng-1.6.10.tar.gz when installing on MacOSx using brew 

### ISSUE THREAD

**Issue by yangit** [jcupitt/libvips#226]
brew install vips
==> Installing dependencies for vips: libpng, freetype, fontconfig, gettext, xz, libffi, glib, jpeg, orc, intltool, libgsf, libtiff, fftw, lit
==> Installing vips dependency: libpng
Error: Failed to download resource "libpng"
Download failed: https://downloads.sf.net/project/libpng/libpng16/1.6.10/libpng-1.6.10.tar.gz

According to http://www.libpng.org/pub/png/libpng.html there is vulnerability in versions <1.6.15
So perhaps dependency should be updated in brew profile.

**Comment by jcupitt** [comment]
Hi, vips.rb just asks for libpng, it doesn't ask for a certain version, so it's the libpng.rb formula that needs updating. 

Looking at homebrew, it seems they patched this on Dec 23:

https://github.com/Homebrew/homebrew/commits/master/Library/Formula/libpng.rb

Maybe just a `brew update` would fix it?

**Comment by jcupitt** [comment]
Hi, vips.rb just asks for libpng, it doesn't ask for a certain version, so it's the libpng.rb formula that needs updating. 

Looking at homebrew, it seems they patched this on Dec 23:

https://github.com/Homebrew/homebrew/commits/master/Library/Formula/libpng.rb

Maybe just a `brew update` would fix it?
