### ISSUE TITLE
More reference count problems with vips_resize()

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#227]
From a fresh checkout yesterday:

    ./vips resize ~/Tmp/temp.jpg ~/Tmp/temp2.jpg 0.26 --vips-leak
    1 objects alive:
    0) VipsInterpolateBicubic (0x9115a30), count=1
    VipsInterpolateBicubic (bicubic), bicubic interpolation (Catmull-Rom) 
    memory: high-water mark 32.13 MB

and

    ./vips resize ~/Tmp/temp.jpg ~/Tmp/temp2.jpg 0.25 --vips-leak
    15 objects alive:
    0) VipsImage (0x9b1fdb0), count=3
    VipsImage (image), image class 2130x2130 uchar, 3 bands, srgb
    1) VipsLineCache (0x9b15d00), count=1
    VipsLineCache (linecache), cache an image as a set of lines linecache in=((VipsImage*) 0x9b1fdb0) out=((VipsImage*) 0xb45670a0) -
    2) VipsImage (0x9ac50d0) 812 bytes, count=2
    VipsImage (image), image class 2130x2130 uchar, 3 bands, srgb
    .................

The number of referenced objects changes when the scale factor is equal or less than 0.25, if that can help.

**Comment by jcupitt** [comment]
This is weird, I'm not seeing any of these leaks. Are you sure that's with git master? I see:

```
john@bambam ~/pics $ vips resize k2.tif x.jpg 0.2 --vips-leak
memory: high-water mark 24.25 MB
john@bambam ~/pics $ vips resize k2.tif x.jpg 0.1 --vips-leak
memory: high-water mark 11.87 MB
john@bambam ~/pics $ vips resize k2.tif x.jpg 0.25 --vips-leak
memory: high-water mark 18.94 MB
john@bambam ~/pics $ vips resize k2.tif x.jpg 0.8 --vips-leak
memory: high-water mark 12.15 MB
john@bambam ~/pics $ vips resize k2.tif x.jpg 0.26 --vips-leak
memory: high-water mark 51.14 MB
john@bambam ~/pics $ vips --version
vips-7.42.2-Tue Jan 27 08:44:04 GMT 2015
```

**Comment by aferrero2707** [comment]
Sorry, I had some weird mess in my VIPS set-up... after deleting all vips directories and restarting from scratch, I have no leaks anymore.

**Comment by jcupitt** [comment]
Ah phew.
