### ISSUE TITLE
"Failed to allocate" on large files

### ISSUE THREAD

**Issue by manuelcabral** [jcupitt/libvips#229]
I am trying to use dzsave on a large TIFF file on Windows and I am getting the following error:

    GLib-Error **: gmem.c:170: failed to allocate 4294911304 bytes
    aborting...

This is the command I am using:

    vips dzsave infile.tif out --tile-size 512

Any ideia on how this could be fixed? The vips version is vips-7.42.0-Thu Dec 18 17:34:09 GMT 2014

**Comment by jcupitt** [comment]
It may be to do with the details of the tiff file. Could you run tiffinfo on the file and post the results?

Some varieties of the TIFF format are very difficult to decode in sections and vips is forced to load the entire thing into memory.

**Comment by manuelcabral** [comment]
tiffinfo is not printing anything for this file. I guess this must be a problem with the TIFF file itself.
