### ISSUE TITLE
Question: vips8 C++ resize interpolate parameter

### ISSUE THREAD

**Issue by lovell** [jcupitt/libvips#230]
Hi John,

How would you recommend I pass a VipsInterpolate as the optional `interpolate` parameter of the [resize](https://github.com/jcupitt/libvips/blob/master/cplusplus/vips-operators.cpp#L1824) method in the new C++ API?
```cpp
VImage output = input.resize(scale, VImage::option()->set("interpolate", ???);
```
My attempts at creating a VImage instance with a chain of casts to VipsImage* and/or VipsObject* keep generating `g_value_type_compatible` assertion failures.

Should `VOption` provide another `set` method for a `VipsObject` pointer:
```cpp
VOption *set( const char *name, VipsObject *value );
```
or the more native:
```cpp
VOption *set( const char *name, VObject value );
```
or perhaps even a VInterpolate class wrapper around VipsInterpolate?

Cheers!

**Comment by jcupitt** [comment]
Oh good point, I never tried that. 

I guess we need a wrapper around VipsInterpolate, should be easy, I'll have a fiddle.

**Comment by jcupitt** [comment]
Seems to work! Use like this:

```C++
        VInterpolate interp = VInterpolate::new_from_name( "nohalo" );

        out = in.resize( 0.2, VImage::option()->set( "interpolate", interp ) );
```

**Comment by lovell** [comment]
Perfect, thank you for the swift turnaround, as always.
