### ISSUE TITLE
Thread safe

### ISSUE THREAD

**Issue by DAddYE** [jcupitt/libvips#232]
Hi, 

As far I'm aware recent releases of libjpeg (and I assume the turbo version as well) are thread safe.

Last time I tried libvips in https://github.com/daddye/vips I noticed it was using locks.

Now imagemagick has check for that:

```c
#if JPEG_LIB_VERSION < 80
entry->thread_support=NoThreadSupport;
#endif
```

How libvips handle that?

Thanks!

Source: http://www.imagemagick.org/discourse-server/viewtopic.php?t=25495

**Comment by jcupitt** [comment]
Oh, I don't know. I'll have a look.

**Comment by jcupitt** [comment]
libvips already does this: it can decode several jpeg images in parallel. It won't let more than one thread read from the same image at once, though.

**Comment by DAddYE** [comment]
> libvips already does this: it can decode several jpeg images in parallel. It won't let more than one thread read from the same image at once, though.

Since when? IIRC last time we talk about it you told me that it has locks since libjpeg is not thread safe

**Comment by jcupitt** [comment]
Yes, you can only use one thread on one JPEG image, so vips has locks for this, but you can do several JPEGs at the same time. It's always supported this, I think.  For example, dzsave will write many tiles in parallel.

**Comment by jcupitt** [comment]
I'll close since I think this is done. Please reopen if not.
