### ISSUE TITLE
16 bit PNG losing colors

### ISSUE THREAD

**Issue by nikyoudale** [jcupitt/libvips#234]
Some colors are set to black when resizing a PNG file with a depth of 16 bits.

```
$ vipsthumbnail 16bit.png --size=1024 -o out.png

$ vips --version
vips-7.42.1-Mon Feb  9 10:39:18 AEDT 2015
```

input:
![16bit](https://cloud.githubusercontent.com/assets/907626/6099330/545d927c-b049-11e4-8ae0-58cac78bc5c7.png)

output:
![out](https://cloud.githubusercontent.com/assets/907626/6099332/67182e36-b049-11e4-91fe-d6a8b4f7f923.png)

Is this a known issue?

**Comment by jcupitt** [comment]
Hi @nikyoudale, yes, this was fixed last week:

https://github.com/jcupitt/libvips/commit/0c466b949514c45e8aac9c01ff847c1c7278af9f

The fix is in the current supported version. I must update homebrew, I've not done it yet.

**Comment by jcupitt** [comment]
I've put in a pull request for homebrew.

**Comment by nikyoudale** [comment]
Excellent. Thanks!

**Comment by jcupitt** [comment]
OK, I'll close this, please reopen if it doesn't work for you. 

The new version should give a useful performance improvement for 16 -> 8 conversion as well.
