### ISSUE TITLE
Operating on animated GIF images?

### ISSUE THREAD

**Issue by deuill** [jcupitt/libvips#235]
I'm working on implementing VIPS for an internal image proxy service and the experience has been nothing but exemplary. However, there is one piece of the puzzle remaining, and that is animated GIF support.

I see that GIF support is not available natively, and is provided by ImageMagick/MagickWand/GraphicsMagick and the `vips_magickload()` function, which loads the data as a `VipsImage` and is therefore transparent to any subsequent operations. There even seems to be an `all_frames` option, however I am not sure if this returns an image sequence or stitches all the frames into one image.

What I cannot find is a function for writing the image returned by `vips_magickload()`, or any sequence of images really, to an animation. ImageMagick seems to provide something like this in the [WriteImages](http://www.imagemagick.org/api/constitute.php#WriteImages) function, but I'm not sure what the equivalent would be in MagickWand or GraphicsMagick.

Is it possible to load, operate upon, and save to animated GIFs at this time?

**Comment by jcupitt** [comment]
Hi @deuill. No, vips can load via libMagick (this is how GIF load is done), but there's no save via libMagic, so no GIF save. 

I use the `all_frames` option to load medical images for processing. It puts the frames together, one above the other, in a tall, thin image. You can use things like vips_grid() to change the layout. 

vips doesn't really support image sequences, it just does 2D colour images.

**Comment by jcupitt** [comment]
... I meant to add, so I think you can probably only use vips to show the first frame of the GIF.

**Comment by deuill** [comment]
Thanks for the quick reply, @jcupitt! I'll see if I can hack something by cutting each image as a separate `VipsImage` and stitching them back via the libMagick API directly.

Thank you for this amazing piece of software!

**Comment by jcupitt** [comment]
OK, I'll close. Hope it's working.
