### ISSUE TITLE
vips_magickload_buffer?

### ISSUE THREAD

**Issue by paydro** [jcupitt/libvips#238]
Hello!

Are there any plans to add `vips_magickload_buffer` to the foreign loaders? I know `vips_magickload` exists, but that only works for files. Obviously, I could always write my local buffer to a temp file then have it reload with `vips_magickload` but I'd rather not have to do this if I could. 

Thanks!

**Comment by jcupitt** [comment]
It looks like the blob functions could maybe do it:

http://www.imagemagick.org/api/blob.php

Though I don't see an equivalent of PingImage. I'll add a note to the TODO and leave this issue open as a reminder.

**Comment by paydro** [comment]
Thanks!

**Comment by jcupitt** [comment]
All done, this will be in libvips-8.0.0, due 1st April.
