### ISSUE TITLE
Can't find VIPS libs Fedora 21

### ISSUE THREAD

**Issue by GoGoris** [jcupitt/libvips#239]
Hi I installed VIPS on fedora with yum install vips vips-python. 
I can run vips help in the terminal, this works.
Unfortunately the typelib doesn't seem to be installed in /lib/girepository-1.0 or in /usr/lib/girepository-1.0
I am also missing /usr/lib/python3.4/dist-packages/gi. I have only /usr/lib/python3.4/site-packages and no gi folder. /usr/local/lib is empty too, so that's not a possibility either. 
I can't run the example from the wiki, this is the error: AttributeError: type object 'Image' has no attribute 'new_from_file'

I must say that this is one of my first python scripts. I tried this because it looked like python was the recommended language for vips. What am I doing wrong?

Regards,
GoGoris

**Comment by jcupitt** [comment]
Hi, vips has two Python interfaces, there's the old vips7 one, which is still there and should work on fedora 21, and the much better vips8 one, which is on fedora 22 or later.  If you build the latest vips from source, you should be able to use the new interface on fedora 21.

vips has been going through a rewrite for the last few years and it's been changing a lot :-( It should become much more stable now that the rewrite is done.

**Comment by jcupitt** [comment]
Here are the rather sketchy docs for the vips7 Python interface:

http://www.vips.ecs.soton.ac.uk/supported/7.24/doc/html/vipsmanual/vipsmanualse1.html

Some of the older blog posts have some example code:

http://libvips.blogspot.co.uk/2011/05/image-annotation-with-libvips-and.html

But I'm not sure I'd use it for a new project. I would build vips myself from source, or update to a newer fedora.

**Comment by GoGoris** [comment]
Thank you really much for the clarification, this will help.

**Comment by jcupitt** [comment]
OK, I'll close if this is done.
