### ISSUE TITLE
VIPS for image stabilisation — some questions

### ISSUE THREAD

**Issue by PaulHowson** [jcupitt/libvips#245]
Hi,

I’m working on a tool to stabilise jitter in scanned 16mm film. The jitter is caused by mechanical mis-registration either in the camera or the film scanner.

I have a few questions related to using VIPS for (i) detecting movement between fixed artefacts on different film frames and (ii) applying translations to correct for these movements.

Firstly, is there a VIPS function to translate an image by an (x, y) pixel offset (whole pixels). i.e. no rotation, no scaling, no shear, just translation?

Regarding detecting movement, I was going to sample and compare small areas on different frames. The VIPS correlation functions vips_spcor and vips_fastcor would seem to be the right choice. I have run some command line tests on small test images using vips_spcor and it yields an output image with a peak at the offset (as it should).

Is there a VIPS function to detect the (x, y) location of the centre of the peak?

Sometimes movement can be easily detected when there is a straight vertical or horizontal black-white transition (not razor sharp) as in the edge of a film perforation or the camera gate, etc. In this case detectable movement will be perpendicular to the transition edge, so it would make sense only to do a one-axis correlation, which should also be considerably faster than a two-axis correlation. Is there any way of doing a one-axis correlation in VIPS?

Thanks.

**Comment by jcupitt** [comment]
Hi Paul,

Fast translate by an integer pixel offset with vips_embed(). I'd link the docs but the vips website seems to be down right now. Use vips_affine() for a fast sub-pixel offset.

Use vips_max() to detect peak position. You give it extra "x" and "y" parameters and it gives back the position of the peak. It can detect the top N peaks as well. There's im_maxpos_subpel() as well to estimate the subpixel peak, though that function is currently parked in the "deprecated" area. I should probably undeprecate it.

vips_spcor() is incredibly slow, I would use vips_fastcor(), which just calculates sum-of-squares-of-differences and search for a minimum.

vips operations are fast, but calling vips operations is relatively slow. You probably not be able to call vips_fastcor() many times for each frame. I'll add a vips_fastcor_direct() function for a direct C call to the opereration, it'll be far quicker. I need this myself for something else.

Have you looked at video encoders? They have very fast motion vector estimators, they might be useful for your work.

I think you will probably need to do subpixel motion estimation and translation or you will lose a large amount of detail, perhaps half your resolution.

**Comment by PaulHowson** [comment]
Hi John,

> Fast translate by an integer pixel offset with vips_embed(). I'd link the docs but the vips website seems to be down right now. Use vips_affine() for a fast sub-pixel offset.

So, does vips_embed allow the input and output images to be the same image? i.e. to just offset pixels in an image?

> Use vips_max() to detect peak position. You give it extra "x" and "y" parameters and it gives back the position of the peak. It can detect the top N peaks as well. There's im_maxpos_subpel() as well to estimate the subpixel peak, though that function is currently parked in the "deprecated" area. I should probably undeprecate it.

I don’t understand how this function works. What is the purpose of the extra “x” and “y” params? I thought the function was supposed to find the positions of the maximum value/s in an image.

I’ve noticed that the peaks can be “flat” — i.e. there is an n x n area of identical maximum pixels. The peak would be in the middle of this “flat” area. Does im_maxpos_subpel() find this central maximum?

> vips_spcor() is incredibly slow, I would use vips_fastcor(), which just calculates sum-of-squares-of-differences and search for a minimum.

What about the issue of correlation in one axis only. Would it be difficult to create variations of vips_fastcor() which do correlation in either x or y but not both directions?

> vips operations are fast, but calling vips operations is relatively slow. You probably will not be able to call vips_fastcor() many times for each frame. I'll add a vips_fastcor_direct() function for a direct C call to the operation, it'll be far quicker. I need this myself for something else.

I don’t need to correlate entire frames. That would be too slow and would yield spurious results anyway. Instead it will be sufficient to correlate small pieces of frames where there are “fixed artefacts” around the edges of frames — such as the film perforations. These pieces might be only a few dozen pixels square or a few dozen pixels long by only a few pixels wide.

> Have you looked at video encoders? They have very fast motion vector estimators, they might be useful for your work.

No I haven’t looked at those. I want to pursue simple correlation of small areas first because I think that will do the job.

> I think you will probably need to do subpixel motion estimation and translation or you will lose a large amount of detail, perhaps half your resolution.

How is that so? I have done tests, loading scanned footage into layers in Photoshop, and manually differencing layers then moving layers in 1 pixel steps. I can get almost perfect cancellation. Also, the film scans are available in high resolution — 2048 x 1556 pixels — so that a single pixel shift will provide fine adjustment.

I’ve used C in the past. For this project I’m using Ruby, so was planning to use the ruby-vips gem to access vips. Any thoughts on that?

Thanks,
Paul

**Comment by jcupitt** [comment]
> So, does vips_embed allow the input and output images to be the same 
> image? i.e. to just offset pixels in an image?

It always makes a new image, but it's very fast, it just changes the way the pixels are addressed. You can write back to the source image if necessary, but in most cases it's probably better to make a new image. 

vips has optional output arguments. Use vips_max() like this from C:

```C
double max_value;
int x_pos;
int y_pos;

VImage *image = ...;

if (vips_max (image, &out, "x", &xpos, "y", &yps, NULL))
  error ...;
```

> I don’t need to correlate entire frames. 
> Instead it will be sufficient to correlate small pieces of frames

Exactly, but vips function call overhead is high enough that calling vips_fastcor() many times for each frame will be slow. If you're using Ruby or Python this may not be an issue.

In my opinion sub-pixel estimation is probably helpful. Without it you can be off by up to half a pixel each frame, effectively halving your resolution. Up to you, of course! It might be interesting to experiment with at least, if you have some spare time. 

The ruby-vips binding is nice and works well, but it wraps the old vips7 API. There's a new vips8 API which is much better. The new ruby binding isn't ready yet, but the Python one is done. Docs here:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-python.html

The new ruby binding is here, but currently leaks badly due to a bug in `gir_ffi`:

https://github.com/jcupitt/gir_ffi-vips

I had another go with a different ruby goi system here:

https://github.com/jcupitt/ruby-vips8

That has a different range of problems due to missing features in `ruby-gnome3`, annoyingly. Hopefully one of these two will be production-ready soon.

**Comment by PaulHowson** [comment]
Hi John,

Continuing this thread…

I installed ruby-vips and created some simple examples getting image metadata, doing correlations and using vips_embed to (x, y) translate an image.

Looking up the ruby-vips C source was a useful way to find calling conventions and args.

THEN…I updated my MacBook Pro and migrated files to the new computer.

Most stuff was copied correctly, including the vips installation. Some files were missed and I had to do some manual copying. Command line vips is now functioning again.

However, I’m having trouble installing the ruby-vips gem. Getting this error (from gem install ruby-vips):

extconf.rb:27:in `<main>': no pkg_config for any of following libvips versions: 7.29, 7.28, 7.27, 7.26, 7.24, 7.23, 7.22, 7.20 (RuntimeError)
Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/ruby-vips-0.3.9 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/ruby-vips-0.3.9/ext/gem_make.out

mkmf.log says:
package configuration for vips is not found
package configuration for vips-7.29 is not found
<more lines follow up to vips-7.20>

Something’s obviously missing. Can you point me to what it could be?

Thanks, Paul

**Comment by jcupitt** [comment]
Hi again, you need to set `PKG_CONFIG_PATH`. 

I would wipe your vips install and use homebrew, there are some notes here:

http://www.vips.ecs.soton.ac.uk/index.php?title=Build_on_OS_X

Then just `gem install ruby-vips`.

**Comment by PaulHowson** [comment]
Hi John,

pkg-config was not linked in /usr/local/bin. Fixing that made gem install ruby-vips work. Ruby-vips now working again. Thanks.

**Comment by PaulHowson** [comment]
Hi John,

Making good progress using vips for a project to stabilise jitter in frames of a film scan. Using im.spcor to correlate small samples from the corners of film frames. No problem with speed. The correlation is working well. Then using im.maxpos_avg to find the (average) x, y coordinates of the maximum value (i.e. the correlation peak).

Ran into an error message today out of the ruby_vips method: im.maxpos_avg. This has been working fine, but for certain correlation images produced by im.spcor, vips is throwing the following error:

(run.rb:48692): GLib-GObject-WARNING **: value "nan" of type 'gdouble' is invalid or out of range for property 'out' of type 'gdouble'

Any thoughts?

Paul

**Comment by jcupitt** [comment]
Sounds like an all zero image maybe? It certainly shouldn't happen. Can you send an image which triggers this error?

**Comment by PaulHowson** [comment]
> On 24 Mar 2015, at 8:51 pm, John Cupitt <notifications@github.com> wrote:
> 
> Sounds like an all zero image maybe? It certainly shouldn't happen. Can you send an image which triggers this error?
> 

Image is attached. File name is COR-241-top-left.tif

Error message is:

(run.rb:50284): GLib-GObject-WARNING **: value "nan" of type 'gdouble' is invalid or out of range for property 'out' of type ‘gdouble'

then:

VIPS::Error: VIPS error: avg: parameter out not set

then the start of the call stack:

method maxpos_avg <txmt://open?line=341&url=file:///Users/paul/Dev/projects/MovieStabiliser/code/lib/mps_job.rb>	in mps_job.rb at line 341

At a glance the image attached looks almost the same as a whole series of images for other frames which did NOT trigger this error.

Paul

**Comment by PaulHowson** [comment]
> On 24 Mar 2015, at 8:51 pm, John Cupitt <notifications@github.com> wrote:
> 
> Sounds like an all zero image maybe? It certainly shouldn't happen. Can you send an image which triggers this error?
> 

John,

I have re-run these im.maxpos_avg tests with different ranges of image samples (from a long sequence of film frames). It consistently crashes on the same ones.

Then I tried command line vips on the file I sent to you:

     vips im_maxpos_avg COR-241-top-left.tif

It produces the same error:

(vips:50975): GLib-GObject-WARNING **: value "nan" of type 'gdouble' is invalid or out of range for property 'out' of type 'gdouble'
avg: parameter out not set

It would appear to be a bug?

Paul

**Comment by jcupitt** [comment]
This just bubbled to the top of my TODO list and I've just realised the image wasn't attached, or didn't arrive. Could you upload to something like dropbox? You can drag images into github post forms too, I think.

I'll see if I can reproduce it anyway.

**Comment by jcupitt** [comment]
I've opened a new issue for this bug, could we continue there, please?

https://github.com/jcupitt/libvips/issues/252

**Comment by PaulHowson** [comment]
> On 26 Mar 2015, at 6:40 pm, John Cupitt <notifications@github.com> wrote:
> 
> This just bubbled to the top of my TODO list and I've just realised the image wasn't attached, or didn't arrive. Could you upload to something like dropbox? You can drag images into github post forms too, I think.
> 
> I'll see if I can reproduce it anyway.
> 
Dropbox link to image:

https://www.dropbox.com/s/t074pl8ccphohd9/COR-241-top-left.tif?dl=0

**Comment by jcupitt** [comment]
Thanks, I replied on the new issue.
