### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by ottob** [jcupitt/libvips#246]
www.vips.ecs.soton.ac.uk seems to be down at the moment. It would be nice if the latest src tar ball like vips-7.42.2.tar.gz could be mirrored somewhere else, perhaps here on github?

**Comment by jcupitt** [comment]
It was down over the weekend, it should be up again now.

You're right, we should probably switch to hosting the whole site from github. It needs reworking.

**Comment by ottob** [comment]
Yes, it works again now. Moving the website is probably a big task that you don't want to track here. So I'll close this issue.
