### ISSUE TITLE
merge load-from-stream branch

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#247]
See https://github.com/lovell/sharp/issues/179

It would be nice to be able to write an image to an fd. This could be a pipe back to the user's web browser, for example. The load-from-stream branch adds this, though it's bitrotted.

Fix it up and merge this.

**Comment by jcupitt** [comment]
It's diverged quite a way, it'd be annoying to fix up.

**Comment by LeslieGerman** [comment]
Hello John,

I'm just joining those who think merging stream support in the master branch would be a good idea...

Regards.
