### ISSUE TITLE
Copy all blobs from one VipsImage to another (question)

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#248]
In my program I am sometimes inserting calls to an external library (G'MIC to be precise) in the middle of the VIPS pipeline, and I need to save the whole image data into a temporary file since those G'MIC filters I'm using are not compatible with chunk processing.

However, the input vips images have a certain number of blobs that get lost on the way, unless I explicitly copy them. Is there a VIPS function that allows to copy all the metadata objects (but ONLY the metadata) from one image to another?

**Comment by jcupitt** [comment]
Blobs should not get lost. Are you saving the temporary images in vips format? It should save and restore everything.

**Comment by aferrero2707** [comment]
G'MIC does not understand the VIPS format, so I'm saving and re-loading the images as floating-point TIFFs. Even worse, the ICC profile embedded in the TIFF file gets also lost through G'MIC... therefore I need to restore all the original metadata once I've reloaded the output TIFF image from G'MIC.

**Comment by jcupitt** [comment]
Oh duh, of course you're right.

There's an internal function:

```C
int vips__image_copy_fields_array( VipsImage *out, VipsImage *in[] );
```

where `in[]` is a NULL-terminated array. It's part of the vips7 compatibility stuff, so it's not going anywhere and should be safe to call. It copies ALL metadata, including width and height, so bad things can happen if you're not careful.

Perhaps this should be in the vips8 API as well.

**Comment by aferrero2707** [comment]
Thanks! I think that I can restore the correct width and height using vips_init_fields() in case something changes between input and output.
