### ISSUE TITLE
How to convert jpeg to webp in vips command line

### ISSUE THREAD

**Issue by shilpi230** [jcupitt/libvips#254]
````vips im_vips2webp tobecompressedpdf2.jpeg test.webp```` I tried this but i think this is not correct command.

**Comment by jcupitt** [comment]
Hi, format conversion is automatic:

```
vips copy tobecompressedpdf2.jpeg test.webp
```

You can run the webp converter explicitly with:

```
vips webpsave tobecompressedpdf2.jpeg test.webp
```

Or to see the options it supports, try:

```
vips webpsave
```

**Comment by shilpi230** [comment]
Thank you @jcupitt  i tried this ````vips webpsave tobecompressedpdf2.jpeg test.webp```` but its showing error: `unable to encode`

**Comment by shilpi230** [comment]
Sorry @jcupitt i got it. It was not working because my file resolution is more than 16000 and webp doesn't support it.

**Comment by jcupitt** [comment]
Ah, OK. Yes, webp is rather limited at the moment, it's missing lots of obvious things.

**Comment by shilpi230** [comment]
:(

**Comment by jcupitt** [comment]
Looking at the wiki page, it seems they now have a tiled mode, which would fix this. vips should probably have an option to save as tiled webp.

**Comment by shilpi230** [comment]
Yeah then i can solve my both the issues of high resolution and conversion to webp :)

**Comment by shilpi230** [comment]
From wiki it says that they have already implemented it then why doesn't it works in cwebp ?

**Comment by jcupitt** [comment]
https://developers.google.com/speed/webp/docs/api#simple_encoding_api

The API docs don't mention tiling, I guess you're supposed to read the headers to figure it out.

**Comment by jcupitt** [comment]
I found this post:

https://groups.google.com/a/webmproject.org/forum/#!topic/webp-discuss/Srdsveieat4

It's not clear how well webp tiling works or who supports it or if there are any sample images.

**Comment by shilpi230** [comment]
pngsave doesn't support quality parameter as jpegsave or any other format does?

**Comment by jcupitt** [comment]
libpng calls it `copression. Try `vips pngsave` to see all the options:

```bash
$ vips pngsave
save image to png file
usage:
   pngsave in filename
where:
   in           - Image to save, input VipsImage
   filename     - Filename to save to, input gchararray
optional arguments:
   compression  - Compression factor, input gint
			default: 6
			min: 0, max: 9
   interlace    - Interlace image, input gboolean
			default: false
   profile      - ICC profile to embed, input gchararray
   filter       - libpng row filter flag(s), input VipsForeignPngFilter
   strip        - Strip all metadata from image, input gboolean
			default: false
   background   - Background value, input VipsArrayDouble
operation flags: sequential-unbuffered nocache 
```

**Comment by shilpi230** [comment]
yeah got it thank you :+1:
