### ISSUE TITLE
vipsthumbnail --linear can generate corrupted JPEG output

### ISSUE THREAD

**Issue by lovell** [jcupitt/libvips#256]
Hi John,

```sh
curl -O https://raw.githubusercontent.com/lovell/sharp/master/test/fixtures/2569067123_aca715a2ee_o.jpg
vipsthumbnail --format=%s.default.jpg 2569067123_aca715a2ee_o.jpg
vipsthumbnail --linear --format=%s.linear.jpg 2569067123_aca715a2ee_o.jpg
VIPS_CONCURRENCY=1 vipsthumbnail --linear --format=%s.linear.singlethread.jpg 2569067123_aca715a2ee_o.jpg
```

Here's `2569067123_aca715a2ee_o.linear.jpg` output from the above:

![2569067123_aca715a2ee_o linear](https://cloud.githubusercontent.com/assets/210965/6939370/f4ca92d6-d863-11e4-937f-68b80852138f.jpg)

I'm using the latest libvips from git master. Removing multi-threaded behaviour via `VIPS_CONCURRENCY` doesn't seem to fix it. Not all images suffer this problem, although I have been able to reproduce using images with and without embedded profiles.

I recall seeing something similar from an image via sharp when using `VIPS_ACCESS_SEQUENTIAL` that was "fixed" by switching to `VIPS_ACCESS_RANDOM` but don't have details to hand.

Any ideas? The [tilecache](https://github.com/jcupitt/libvips/blob/master/tools/vipsthumbnail.c#L479-L488) settings perhaps?

**Comment by lovell** [comment]
As part of my experiments into adding [support for mozjpeg](https://github.com/mozilla/mozjpeg/pull/165) (and future libjpeg features) to libvips, I've discovered this corruption was related to its trellis quantisation feature. I should have spotted that it was within 8x8 / 16x16 DCT blocks, so sorry for not noticing this sooner.

I've discovered the use of `vips_image_wio_input` solves this, similar to the approach taken for progressive PNG output. I'll ensure any new JPEG feature detection code does this properly.

**Comment by jcupitt** [comment]
Ah, well done for fixing it.

`_wio_input()` will copy the input image to RAM, which may be a bad idea. It should really clear the sequential hint too, so that people using this operation will know not to be in sequential mode. I expect you know this!

**Comment by lovell** [comment]
> _wio_input() will copy the input image to RAM

Thanks John. Am I right in saying this would only be the final, processed, ready-to-save image being held in RAM (rather than, say, the on-disk original or any intermediate images)?

> It should really clear the sequential hint too

Would something like `vips_image_pipelinev( in, VIPS_DEMAND_STYLE_ANY, NULL );` achieve this?

Given only 16 scanlines behind the current position/region seem to be required, I'm also going to experiment with using a tilecache of 2 rows of 8x8 tiles as an alternative to WIO.

**Comment by jcupitt** [comment]
Looking at the code again, I agree, I think the best solution is to add a small cache to the jpeg writer. I would make it cache 2 tiles, each the width of the image and 16 pixels high. vips_linecache() is supposed to be the thing to use for this.

**Comment by jcupitt** [comment]
On your questions:

1. Yes, `vips_image_wio_input()` means "I'm going to read the whole of this image with a pointer". For images on disc, vips will mmap() the image into RAM, for pipelines, it'll allocate a memory buffer large enough for the entire image, render the pipeline into that, then pass the operation a pointer to that buffer. This is usually pretty bad behaviour, the mode is there for operations that just can't work in chunks, like floodfill, for example.

2. I was confused, don't worry about the seq hint. All savers MUST be strictly sequential due to the way that they are called, so if a saver needs to refer back in its input, it needs to add a cache. Interlaced png write is the worst case: it has to make seven passes over the whole image (augh!) so it just has to use WIO. Tiled tiff write is less crazy: it just caches enough pixels to be able to write a line of tiles. It sounds like mozjpeg is similar.

**Comment by lovell** [comment]
Thanks John. I'm getting a `linecache: no property named 'max_tiles'` error from `vips_linecache`.

Should the [max_tiles](https://github.com/jcupitt/libvips/blob/master/libvips/conversion/tilecache.c#L124) attribute of the abstract `VipsBlockCache` be set in [vips_block_cache_class_init](https://github.com/jcupitt/libvips/blob/master/libvips/conversion/tilecache.c#L395) rather than [vips_tile_cache_class_init](https://github.com/jcupitt/libvips/blob/master/libvips/conversion/tilecache.c#L784) so I can add it as a parameter to `vips_linecache`?

**Comment by jcupitt** [comment]
Ahem, I forgot, linecache auto-sizes. Just set the tile height to 16.

**Comment by lovell** [comment]
Thanks for the help John, as always. Looks like I was bitten by https://github.com/mozilla/mozjpeg/blob/master/jcparam.c#L442-L448 as setting `optimize_coding = TRUE` solved this problem without the need for a linecache.

I'll create a PR for https://github.com/lovell/libvips/commit/d0934e8dda96033863ddac27fe94bf1cd311b58e after I've done some more testing, but any comments you have now are more than welcome.
