### ISSUE TITLE
Add section in the wiki for third-party language libraries which uses libvips

### ISSUE THREAD

**Issue by h2non** [jcupitt/libvips#258]
It could be great creating a new page in the official wiki to add third-party libraries organized by languages which uses libvips internally (binding at C-level or not).

Usually, as developer, you want to see how to use libvips in your current target language, so I think it would be great supporting that for multiple reasons:

- To promote and increase the usage of libvips in common languages
- To provide a centralized and clean place to put different implementations by third-party developers
- More visibility: there're a lot of useful implementations out there which sometimes are difficult to find
- For general user-focused and practical documentation benefits

**Comment by jcupitt** [comment]
That's a great idea. There's a page on the main site for that:

http://www.vips.ecs.soton.ac.uk/index.php?title=Links

But it's not updated very often. I'll add one.

**Comment by h2non** [comment]
What about creating a new page called "Projects using libvips" or "libvips in other languages"?

**Comment by jcupitt** [comment]
I made this:

https://github.com/jcupitt/libvips/wiki/Language-bindings

You're right, there should be a "projects using vips" for photoflow etc.

**Comment by jcupitt** [comment]
I added a projects-using page too:

https://github.com/jcupitt/libvips/wiki/Projects-using-libvips

Though it's rather empty right now.

**Comment by h2non** [comment]
Great! Some similar to [this](http://www.imagemagick.org/script/api.php) could be useful, separated by language. I'll create an initial list as proposal

**Comment by jcupitt** [comment]
You're right, I've reorganised it by language.

**Comment by h2non** [comment]
I created another small project based on libvips. It's a simple HTTP service for image processing which uses bimg internally. I can add it to the wiki as another project which uses libvips.

https://github.com/h2non/imaginary

**Comment by jcupitt** [comment]
Sure, add away!

**Comment by h2non** [comment]
I've just added it. I guess all the changes proposed by this issue were made. 
Feel free to close it if you want

**Comment by jcupitt** [comment]
OK, thanks for the suggestion.
