### ISSUE TITLE
Retrieve the dominant color and palette of an image

### ISSUE THREAD

**Issue by h2non** [jcupitt/libvips#259]
Which is actually the more simple way to retrieve the dominant color of an image? It's available some built-in function to simplify that? 

The idea is exactly the same as this library:
http://lokeshdhakar.com/projects/color-thief/

**Comment by jcupitt** [comment]
There are lots of ways of doing this. A simple one is to take a histogram and then pick the bin with the highest count. vips has a 3D histogram function which works well for this:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-arithmetic.html#vips-hist-find-ndim

Transform to LAB first to get bins which are perceptually uniform. Use vips_max() to find the biggest bin.

**Comment by h2non** [comment]
I'll take a look. Thanks!

**Comment by h2non** [comment]
Hi John, 

This is what I'm doing, but I'm doing it wrong:

First call to colorspace to get the LAB:
```c
vips_colourspace(in, out, VIPS_INTERPRETATION_LAB, NULL);
```
With the new VipsImage I'm calling to:
```c
vips_hist_find_ndim(in, out, NULL);
```
And finally to max:
```c
vips_max(in, NULL, "x", &x, "y", &y", NULLL);
```

After calling `vips_max` I'm getting `x=0` and `y=0` which is a black pixel. I've tested it with multiple images and it doesn't work.

By the way, I'm getting an strange warning when calling `vips_max` (maybe related to #252?):
```c
GLib-GObject-WARNING **: g_object_get_valist: value location for 'gdouble' passed as NULL
```
Which `double` value could I pass there?

Any help will be really appreciated!

**Comment by jcupitt** [comment]
Hi, I'll have a go at a tiny example.

The histogram functions only work on unsigned 8 and 16-bit ints, since they have to be able to use the pixel value as an array index. You'll need to scale and cast the LAB image before you can histogram it correctly.

**Comment by h2non** [comment]
Thank you so much, John.

I'm sorry for the obvious, but I'm starting with libvips and I'm so newbie at this time.
For you this could be trivial, but there're a lot of concepts to understand in order to deal properly with the API. I'll continue reading and playing with it.

Thanks again!

**Comment by h2non** [comment]
Hi @jcupitt,

Sorry for bother you, but I need a brief help with this.

This is the test function I made. The idea is to retrieve the predominant color (more repeated) of an image.  There're some concepts which I don't understand deeply, and this mainly what is blocking me, and I'm sure this is pretty simple to solve for you. As you can see above, the final call to vips_max() would be to retrieve the X/Y coordinates of the pixel with color. 

The function actually doesn't work. What is missing? 
```c
int
vips_predominant_color(VipsImage *in, int **x, int **y)
{
	VipsImage *base = vips_image_new();
	VipsImage **t = (VipsImage **) vips_object_local_array(VIPS_OBJECT(base), 6);
	double *a = 1;

	if (
		vips_cast(in, &t[0], VIPS_FORMAT_UCHAR, NULL) ||
		vips_colourspace(t[0], &t[1], VIPS_INTERPRETATION_LAB, NULL) ||
		vips_hist_find_ndim(t[1], &t[2], NULL) ||
		vips_max(t[2], a, "x", x, "y", y, "size", 1000, NULL)
		) {
		g_object_unref(base);
		return 1;
	}
	
        g_object_unref(base);
	return 0;
}
```

Thank you so much in advanced

**Comment by jcupitt** [comment]
Hi again, I made you a tiny Python program:

https://gist.github.com/jcupitt/ee3afcbb931b41b4d7f4

**Comment by jcupitt** [comment]
... that's just RGB of course, I added another one to do it in LAB space

**Comment by h2non** [comment]
Fabulous. Thank you so much!

I'll try to port that implementation to C.
By the way... I guess it's more reliable and efficient perform that operation based on LAB color space instead of RGB, right?

**Comment by jcupitt** [comment]
RGB is faster, but there will be too many bins in the dark areas, where you can't see different colours, and not enough bins in the light areas. If you use LAB, the bins will be perceptually equally spaced and it'll be more accurate.

**Comment by jcupitt** [comment]
... also, there are loads of other techniques for doing this. 3D histograms are fast and simple, but they will introduce colour distortions. Some sort of clustering technique might be better, it depends on your needs and the sorts of image you are working with.

**Comment by vinvinod** [comment]
Hi John,

I was wondering, is there any utility function in libvips python, for converting the resulting (L,a,b) value to corresponding (R, G, B) value?

**Comment by jcupitt** [comment]
The simplest way is to make a 1x1 pixel image with your source values in, tag it as being a Lab image, then transform to sRGB and pull out the new values. This sounds fiddly, but is actually pretty easy:

```python
import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

value = [50, 2, 2]
from_space = "lab"
to_space = "srgb"

# make a 1x1 pixel image, tag as being in the source colourspace
pixel = Vips.Image.black(1, 1) + value
pixel = pixel.copy(interpretation = from_space)

# transform to dest space
pixel = pixel.colourspace(to_space)

# pull out the pixel from coordinate (0, 0) as an array 
new_value = pixel(0, 0)

print(from_space, " ", value)
print(to_space, " ", new_value)
```

It's easy to write a function to go between any pair of spaces.
