### ISSUE TITLE
Watermark support

### ISSUE THREAD

**Issue by h2non** [jcupitt/libvips#260]
I want to overlay an image over another, just like a watermark. 
I'm using [vips_insert](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-insert), and it works fine, but the PNG transparency is removed. Both `in` and `sub` images are PNG. Can I disable the background param? There's another way to do a watermark more easily?

```c
vips_insert(in, sub, out, left, top, NULL);
```

Actually this is how it looks like:
![test_watermark_out](https://cloud.githubusercontent.com/assets/63402/7056246/79470ab2-de4a-11e4-92e6-cfac521c6249.jpg)

**Comment by Melraidin** [comment]
Have a look at http://libvips.blogspot.ca/2013/07/watermarking-with-ruby-vips.html

You can do much the same, just without having to first generate the text images (assuming you're using an image as the watermark).

**Comment by jcupitt** [comment]
That's right. There's a C version linked from that blog post:

https://gist.github.com/jcupitt/039ecdc172712cbb8969

Hopefully it's easy to follow.

**Comment by h2non** [comment]
Thanks a lot.

I'll try to adapt both implementations to my requirements and I'll let you know.

**Comment by h2non** [comment]
Hi John, 

What about this comment you made in the blog post?
```
I've make vips8 C and Python versions and linked them at the top. They won't work for images with transparency though, I'll add that.
```

There's still no support for PNG images?

**Comment by jcupitt** [comment]
The examples support transparency now, if you read down the comments you'll see it got added (I hope!).

**Comment by h2non** [comment]
Thanks for the help, guys! I think I have what I need. Closing

**Comment by ljs-cxm** [comment]
Is there a golang version for watermarking?

**Comment by jcupitt** [comment]
Sorry, I don't know, you'd need to ask on the issue tracker there.

**Comment by zhaohuxing** [comment]
Hello @jcupitt,
I want to use the watermark process in libvips 8.9.2, what library should be added?

**Comment by jcupitt** [comment]
Hello @zhaohuxing, you don't need to add any other libraries.

Could you open a new issue, please? Say what language you are using, what platform, and give an example of the type of watermark you need.

**Comment by zhaohuxing** [comment]
Hello, @jcupitt
In CentOS 7, I use text watermark, the text is an error. eg:
![watermark](https://user-images.githubusercontent.com/18672896/83022142-a8a4d980-a05d-11ea-837a-53b50cd23461.jpg)

I guess that lacks fonts, but I would install `fontconfig`, Could you give me any advice?

**Comment by jcupitt** [comment]
Yes, it sounds like fonts are missing. Try `fc-list` and see which ones you have installed. You could also try:

```
vips text x.png "hello world"
```

and check that you get a text image.

**Comment by jcupitt** [comment]
... but please open a new issue.
