### ISSUE TITLE
Contrast Limited Adaptive histogram equalization (CLAHE)

### ISSUE THREAD

**Issue by hunter-87** [jcupitt/libvips#268]
hi,
I just found this library and is perfect for processing big tiff images
in my pipeline i really need to use CLAHE (Contrast Limited Adaptive histogram equalization) but i've found only local and global contrast equalization.
can it be implemented using the python bindings?
or a new method should be implemented in the C library? 

Thanks!

**Comment by jcupitt** [comment]
Hi @hunter-87 , I think you'd need to use C for efficiency. It sounds like it should be a fairly simple copy-paste job from hist_local.c:

https://github.com/jcupitt/libvips/blob/master/libvips/histogram/hist_local.c 

Or perhaps hist_local.c should have an optional "limit" argument added?

**Comment by hunter-87** [comment]
i'm trying to learn the new python bindings before changing  hist_local.c
how can i perform local histogram with the new bindings? i can't find it ..

is there a list of all the new api somewhere? 
( pycharm autocompletition doesn't work but the ipython one does, but i could not find the equivalent for vips_hist_local() )

**Comment by jcupitt** [comment]
Hi again, strange, it should work:

```
 python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Vips 
>>> a = Vips.Image.new_from_file("/data/john/pics/k2.jpg")
>>> a.hist_local
<function call_function at 0x7fe3c350a0c8>
>>> help(a.hist_local)
Help on function call_function in module gi.overrides.Vips:

call_function(*args, **kwargs)
    Local histogram equalisation.
    
    Usage:
       out = in.hist_local(width, height)
    Where:
       out        -- Output image, VipsImage
       in         -- Input image, VipsImage
       width      -- Window width in pixels, gint
       height     -- Window height in pixels, gint
>>> help(Vips.Image)
... list of whole API
```

**Comment by jcupitt** [comment]
Hi @hunter-87, I've just added CLAHE to libvips. It'll be in 8.5, due in March 2017, or you can try it now if you build from source.

Thank you for suggesting this useful improvement!
