### ISSUE TITLE
Documentation suggestions for command-line usage

### ISSUE THREAD

**Issue by dg1727** [jcupitt/libvips#269]
Hello, 

Thanks for what look like a fabulous image-processing library & GUI.  I think your image-processing tools should have more recognition on Linux than they do have.  

I've just now compiled vips-7.42.3 (on a Debian-derived Linux) because of the statement in README.md that:  "Building from git needs more packages."  If you prefer I compile from the github ZIP file instead, I can try that.  

The changelog for 8.0 starts with the entry "lots of doc improvements," but with the version I've compiled, I have the issues noted below.  

##### General comments:  

  1.  The Web docs http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-cli.html indicate that an example command line might start with 

  `vips rot`

  i.e., removing the "vips_" prefix from the name listed on http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-rot -- but in fact, all of the operations shown by `vips list` have an "im_" prefix.  

  2.  Furthermore, in this case: 

  `vips list all | grep rot`

  there happen to be 3 convenience operations listed (90 through 270), but nothing called "im_rot".  

  3.  `vips list all` should preferably have an option to group the operations by package, with a heading (consisting of a blank line & the package name) before each group.  This may help, for instance, in looking up an operation in the Web documentation, which is in separate webpages by VIPS package.  

  4.  `vips` with no arguments exits silently; you may want to have it show the help message instead.  

  ##### More specifically about what I'm trying to do:  

  5.  I'm interested in the operations such as "im_lessconst" to convert a colour or greyscale image to a black-and-white bitmap.  
  "im_lessconst" etc. are listed by the `vips` commandline as being in the "deprecated" package.  What is the non-deprecated way to access these operations?  

  6.  The Web docs http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-arithmetic.html say there is an operation called "relational_const", but 

  `vips list all | grep relat`

  doesn't turn up any evidence of such.  (I had thought this might be the recommended replacement for "im_lessconst" etc.)  

  ##### Another general comment:  

  7.  You might consider adding a phrase or sentence (e.g., in the help output from `vips im_lessconst`) to state why each deprecated operation is deprecated.  If an operation has been superseded, then the replacement operation should be listed so the user can tell what operation he or she is supposed to use.  

Thanks again.

**Comment by jcupitt** [comment]
Hi again @dg1727 ,

vips8 isn't really officially out yet, the current supported version is still 7.42, but it ought to work, hopefully. Thanks for your kind words about vips. 

In vips7, all names started with `im_`. If you do `vips list all`, you see the vips7 interface. The whole of vips7 is now deprecated and just there for backwards compatibility.

For vips8, operations are in a class hierarchy. Try:

```
$ vips list classes
```

or to see a summary of the arguments to an operator, try: 

```
$ vips rot
```

In vips8, `im_lessconst` has been replaced with `relational_const`. Try something like:

```
$ vips relational_const x.png y.jpg less "10 20 30"
```

The final argument can be a single number, in which case that value is used for all bands, or a vector, in which case each vector element is used for the corresponding image band.

**Comment by jcupitt** [comment]
I've changed the vips command-line driver program to not show any of the vips7 interface in help. Hopefully this will reduce the confusion a bit.

There's a new `-l` flag to list things. With no argument, it lists all operations. With an argument, it lists all operations below that point in the hierarchy. For example:

```
$ vips -l draw
    VipsDraw (draw), draw operations
      VipsDrawink (drawink), draw with ink operations
        VipsDrawRect (draw_rect), paint a rectangle on an image
        VipsDrawMask (draw_mask), draw a mask on an image
        VipsDrawLine (draw_line), draw a line on an image
        VipsDrawCircle (draw_circle), draw a circle on an image
        VipsDrawFlood (draw_flood), flood-fill an area
      VipsDrawImage (draw_image), paint an image into another image
      VipsDrawSmudge (draw_smudge), blur a rectangle on an image
```

And `vips` with no args now shows help. 

Thanks for the suggestions!

**Comment by dg1727** [comment]
Excellent!  I didn't expect such a fast and complete response.
