### ISSUE TITLE
Building from git - minor issues

### ISSUE THREAD

**Issue by dg1727** [jcupitt/libvips#273]
I'd like to try out the new colour-to-greyscale conversion which is in the Git version of VIPS but isn't in the latest release tarfile 7.42.3.  In building from Git, I found the following issues:  

1.  `README.md` gives a commandline which I have adapted like so:  (including `FLAGS=-O3`)
  `./configure --prefix=/usr/local --disable-introspection --enable-debug=no`
  
  This produces:  
  `configure: WARNING: unrecognized options: --disable-introspection`
  `./configure: line 3294: syntax error near unexpected token '1.30.0'`
  `./configure: line 3294: 'GOBJECT_INTROSPECTION_CHECK(1.30.0)'`

  How do you suggest I resolve this?  

2.  Just before that, when I ran `./bootstrap.sh`, I got a warning which started with:  
  `Please add the files`
  `codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4`
  `progtest.m4`
  `from the /usr/share/aclocal directory to your autoconf macro directory`

  I had to do a Web search to find out:  
  `You can safely ignore the "Please add..." message.  It is benign.`
  (From a developer at Canonical, so it must be right.)  
  A brief statement about this in the `bootstrap.sh` area of `README.md` might keep users from being alarmed.  

3.  The end of `bootstrap.sh` has an error message which mentions SVN, but I take it that Git is being used exclusively now.

**Comment by jcupitt** [comment]
Hi again,

1. Sounds like you're missing a package. You need gobject-introspection (I think) to get the INTROSPECTION_CHECK macro.

2. Yes, benign. 

3. I'll change the SVN, I agree it's misleading.

**Comment by jcupitt** [comment]
I hid the benign message: https://github.com/jcupitt/libvips/commit/3cc408fd1e1b08f5dc60e1f8aeb7edb3eb4982a3

Hopefully that won't also hide error messages.

**Comment by dg1727** [comment]
Yes, installing `gobject-introspection` did the trick.  Thanks for your support.  

You might consider adding a phrase about this to `README.md` like:  

The build system needs ... gobject-introspection *(even with the "configure" option --disable-introspection)* ... 

Italics to show the proposed addition.
