### ISSUE TITLE
Crash on repeated JPEG writes with specific file

### ISSUE THREAD

**Issue by Melraidin** [jcupitt/libvips#274]
I've encountered a case where libvips crashes when attempting to save a JPEG using vips_jpegsave_buffer() repeatedly. It appears to happen only to specific files. I've created this gist:
https://gist.github.com/Melraidin/5a9a3e23a91f4e490b2a

To replicate download this file from Dropbox and save as source.jpg:
https://www.dropbox.com/s/qif76lb375swhcc/real.jpg?dl=0

**Comment by jcupitt** [comment]
Oh, interesting! It works for me with master:

```
$ valgrind --db-attach=yes ./a.out + +
==22809== Memcheck, a memory error detector
==22809== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==22809== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==22809== Command: ./a.out + +
==22809== 
Will save original.
Using vips_copy().
Saving source image.
Starting conversion 0
Starting conversion 1
Starting conversion 2
Starting conversion 3
Starting conversion 4
Starting conversion 5
Starting conversion 6
Starting conversion 7
memory: high-water mark 199.35 MB
==22809== 
==22809== HEAP SUMMARY:
==22809==     in use at exit: 4,096,665 bytes in 7,848 blocks
==22809==   total heap usage: 81,137 allocs, 73,289 frees, 458,475,113 bytes allocated
==22809== 
==22809== LEAK SUMMARY:
==22809==    definitely lost: 0 bytes in 0 blocks
==22809==    indirectly lost: 0 bytes in 0 blocks
==22809==      possibly lost: 0 bytes in 0 blocks
==22809==    still reachable: 97,644 bytes in 1,498 blocks
==22809==         suppressed: 399,009 bytes in 5,732 blocks
==22809== Rerun with --leak-check=full to see details of leaked memory
==22809== 
==22809== For counts of detected and suppressed errors, rerun with: -v
==22809== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

I added a couple of unrefs and a free to fix the leaks.

I'll try against 7.42. Which vips were you using?

**Comment by Melraidin** [comment]
OS X:
```vips --version
vips-7.42.3-Tue Feb 24 22:07:22 EST 2015
```

Let me try building again against master and confirm.

**Comment by Melraidin** [comment]
I can't reproduce the crash against master. In the past we've had an issue that seemingly stemmed from compiling with liborc support so tried both with and without, both completed successfully.

Thanks, guess we'll run against master for now. Any estimate for the next stable release?

**Comment by jcupitt** [comment]
I tried with 7.42.4, the current best 7.42, and it works there too.

**Comment by jcupitt** [comment]
vips8.0 should be as soon as possible :-( It was supposed to be 1st April, but it's slipped a bit. Hopefully very soon. 

I'm trying to fix this blocker: https://github.com/jcupitt/libvips/issues/261

**Comment by jcupitt** [comment]
I'll close this since it seems to be fixed in master.
