### ISSUE TITLE
SVG manipulation taking a little forever

### ISSUE THREAD

**Issue by Jondeen** [jcupitt/libvips#275]
Hi,

I'm attempting to `im_orimage` an image based on a mask drawn in SVG. 
The image is a slide scan, so it is fairly big (pyramidal tiff).
Before Vips outputs any feedback, despite using `--vips-progress`, it hangs for a long time. Then the writing of the output file takes relatively short time, with the expected progress report.
I'm assuming this is because Vips utilizes ImageMagick's libraries for converting from SVG to a usable format by Vips?

Are there other more efficient methods within Vips of dealing with vector shapes?

**Comment by jcupitt** [comment]
Hi, yes that's correct. libvips is using libMagick to load the SVG, and libMagick in turn is calling (I guess?) librsvg to render the SVG to a bitmap.

You can ask it to render at a lower resolution with the `density` option, that would help a bit. It depends how much detail is in your mask I guess. 

libvips has a set of simple drawing operations, you could use those to build the mask. You'd need to allocate a large memory image, then use vips_draw_line() to sketch the mask outline, then use vips_draw_flood() to fill the shape. It's fiddly and uses a lot of memory, but quick.

You could also construct the mask with a set of boolean and relational operators. This is what nip2 does for large masks. It uses very little memory, since areas of the mask will be computed on demand, but it can be slower, depending on mask complexity. 

Where does the SVG come from? Has it been drawn by hand, or is it computed somehow? Can you get at the points that make it up?

I work with large 4D masks on PET scans with libvips with a mixture of computing the mask at runtime and storing parts of masks as large bitmap files. vips supports fax compression, which works well for ROIs.

**Comment by Jondeen** [comment]
`4D masks` Wow - that sounds pretty slick!

My goal is to keep memory consumption low for now, though I may be able to compromise in future.

Yes I've been using boolean operators before with great success (on thresholded images), however trying to run it on the svg directly incurs the libMagick conversion. Any chance of passing parameters to libMagick upon doing an `im_eorimage` e.g. with a `density` parameter?

The coords are computed, but defined by drawing. Shouldnt be hard to extrapolate base coords though if this can help. Can the vips_draw_line() be called on direct/random-access images?



Thanks in advance,

JD

**Comment by jcupitt** [comment]
Yes, when you load the SVG you can give a density. In C:

```
VipsImage *mask;
vips_image_new_from_file("mask.svg", &mask,
  "density", 10,
  NULL);
```

I think it defaults to 72 DPI, so 10 DPI should be a lot quicker. But you may not have enough pixels at low density settings, it depends how much detail there is in your mask. 

Yes, you use vips_draw_line() like this (untested):

```
// make a source of 10,000 x 10,000 black pixels
VipsImage *black;
vips_black(&black, 10000, 10000, NULL);

// write it to a memory image ... this will malloc a huge memory buffer
VipsImage *memory = vips_image_new_memory();
vips_image_write(black, memory);

// draw a white line on the memory buffer
vips_draw_line1(memory, 255, 10, 10, 1000, 1000, NULL); 

// write to disk
vips_image_write_to_file(memory, "x.tif", NULL);
```

**Comment by jcupitt** [comment]
Ooop I notice density is a `char*`, I guess you need "10" as an arg.

**Comment by Jondeen** [comment]
I'm using the python (8) interface. I saw a reference to Vips.Image.black on your wiki, however it is not present as of a fresh build from source. Is the new python interface still being implemented?

**Comment by Jondeen** [comment]
Hi again,

I'm using the python interface, so I'm guessing it should be something like this:
```
im=Vips.Image.new_memory()
im=im.black(1000,1000)

im=Vips.call("draw_line",im,255,0,0,50,50)
im.write_to_file("test2.tiff")
```

However it doesn't generate any lines. What am I missing here? 
I also tried dropping the memory allocation part by calling `Vips.Image.black(1000,1000)` directly, without any further luck.

**Comment by jcupitt** [comment]
Hi, try:

```python
# make a source of black pixels
im = Vips.Image.black(1000, 1000)

# make an image which, when written, will become a memory image
mem = Vips.Image.new_memory()

# use the black pixels to init the memory image
im.write(mem)

# draw a line on the memory image
mem.draw_line(255, 0, 0, 50, 50)

# write to disk
mem.write_to_file("test.tif")
```

**Comment by Jondeen** [comment]
Nope doesn't work, sorry :/

**Comment by jcupitt** [comment]
Oop, sorry, try:

```
mem = mem.draw_line(255, 0, 0, 50, 50)
```

**Comment by jcupitt** [comment]
Hang on, let me actually test it this time ...

**Comment by jcupitt** [comment]
Oh rats I think we have a bug, I wonder when I broke this. I'll have a look.

**Comment by jcupitt** [comment]
Sorry, I was just being dumb, I forgot that images automatically turn into memory buffers. Try:

```python
# make a black image, 100x100 pixels 
# this image does not really exist, it's just a source of pixels ... you
# could make this 1000000x100000 pixels and it'd use no more 
# memory 
a = Vips.Image.black(100, 100)

# draw_line() is tagged as modifying its image argument. The python binding
# see this tag, creates a memory buffer, copies the image into that buffer
# and runs the draw operation. The new memory buffer is returned as the
# result of the operation.
a = a.draw_line(255, 10, 10, 90, 90)

a.write_to_file("x.png")
```

The auto memory buffer and copy behaviour is described in the docs for the py binding:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-python.html#python-modify

There are a few more examples, eg.:

https://github.com/jcupitt/libvips/blob/master/python/example/try10.py

**Comment by Jondeen** [comment]
Hi!

I completely forgot to get back to you -- I made your code work, however the memory consumption was too big to play nicely on the server I was using, so I had to transfer this part of the workflow to another slightly buffed up, but less reliant server.

Thank you so much for followups!
