### ISSUE TITLE
Intermediate outputs when using the commandline

### ISSUE THREAD

**Issue by dg1727** [jcupitt/libvips#276]
I suspect that, unlike with C/C++/Python/nip, which can store intermediate results in memory, command-line usage of VIPS (libvips) requires storing the output from each operation as a disc file for input to the next operation.  

If this is true, maybe it should be stated on http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-cli.html  This would orient commandline users to the fact that they shouldn't expect as much speed as with other versions of the API.  

On the other hand, I've found the following that suggest that commandline output can be cached in memory; can you clarify whether this can indeed be done, or whether the following were published by mistake?:  

* The help output from (e.g.) `vips ppmload` offers the choice of NOT writing the output to disc.  (If the output isn't written to disc, how is it referred to for subsequent operations?)  
* The `access` argument for the image-loading operations (e.g. `ppmload`) refers to how the image is to be stored in memory, but not on disc - am I understanding this?  Or is the `access` argument relevant to the `.vips` file format (and only that format)?  
* How can the commandline operations load from a buffer (pngload_buffer etc.)?  I tried `vips pngsave_buffer` and it printed out `data = 0x7fd860da4010`, but after that, there didn't seem to be any processes in memory with `vips` in the name, so I'm not sure whether the buffer persisted?  Also, if the buffer is of format VipsBlob, how would a user convert this to VipsImage as required by operations such as `colourspace`?  
* By the way, `vips -l` lists a `tiffload_buffer` but no `tiffsave_buffer`.  

If this is already documented somewhere on the Web, a pointer to that page would be great.

**Comment by jcupitt** [comment]
I added a note on chaining to the cli docs: https://github.com/jcupitt/libvips/commit/7ded77cd4de0225fda0d59784082b9d83a0dc37d

All command-line intermediates must be files. If you use vips files (.v) it's pretty quick.

The open-via-disc thing for ppmload and the access flag control the various open modes vips uses, there's a blog post explaining how it works:

http://libvips.blogspot.co.uk/2012/06/how-libvips-opens-file.html

That's right, there's no tiff save to buffer.

**Comment by jcupitt** [comment]
I'll close this, thanks for prompting the docs fix.
