### ISSUE TITLE
Items found in proofreading

### ISSUE THREAD

**Issue by dg1727** [jcupitt/libvips#277]
I happened to notice the following various items:  

* In `libvips/colour/scRGB2BW.c`, the header comment of `vips_scRGB2BW()` says "to sRGB" instead of mentioning greyscale.  

* In `libvips/include/vips/foreign.h` it looks like a search-and-replace of `file` to `foreign` got a little carried away.&nbsp;  :smiley:

* In the output of the `vips -l` commandline there is a duplicate entry for:  
`(extract_area), extract an area from an image` 

* The `vips colourspace` commandline doesn't list scRGB as an allowable colourspace for either input or output.  Is this what was intended?  I notice that scRGB is listed as an available input & output in the `vips_colour_routes[]` table in `libvips/colour/colourspace.c`

* As expected, I was able to convert from colour to greyscale as follows:  
`vips colourspace infile.ppm outfile.pgm b-w`
The following, however, made an all-white output file:  
`vips scrgb2bw infile.ppm outfile.pgm`
Evidently `scrgb2bw` doesn't guess the input colourspace, even though 
http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-cli.html
can be taken to mean that the commandline operations in general do guess the colourspace.  Therefore, in the class hierarchy, it might make sense to move the following eventually to be under `VipsColourTransform (space)` so the user can tell by connotation that these don't auto-convert their input:  
  * `sRGB2scRGB`
  * `sRGB2BW`
  * `scRGB2sRGB`

* You might even state on `using-cli.html` that the specific colourspace converters under the "VipsColourTransform" class are an exception to the input auto-conversion.  

* Or if implicit *file format* conversion doesn't include implicit *colourspace* conversion, then maybe this should be noted on the webpage.  

* `using-cli.html` under "Implicit file format conversion" maybe should say that because of the automatic file format conversion, the `{format}load` operations (`pngload` etc.) are often not needed?  

* The `colourspace` operation makes use of a BW2sRGB operation (mentioned in the `vips_colour_routes[]` array in `libvips/colour/colourspace.c`) which isn't listed in the output of `vips -l`.  Although in most cases the user should probably use `colourspace` (which auto-detects the input colourspace), the complementary `sRGB2BW` is documented for command-line use, so do you want to document BW2sRGB for the command line as well?  

* Possibly, in the output of the `vips -l` commandline, something like a prefixed * could indicate which classes can't be executed (e.g., the `colour` class).  This would help prevent people missing classes like `colourspace`, which can be executed but is listed at the same level as `colour`, which is only an abstract class that can't be executed.  There would need to be a sentence at the beginning of the output to state what the * means.  

Thanks for bearing with me on these sundry issues; I didn't plan to come upon VIPS right before you were going to bump the major version number :smile: but hopefully these items will help prevent the released version being confusing to new users.  Also, if I am misunderstanding any of the above, please let me know.

**Comment by dg1727** [comment]
In addition, http://www.vips.ecs.soton.ac.uk/index.php?title=VIPS has a link (& brief description) as follows:
* **Infrared reflectogram mosaic tour** 
* *Explains how to use nip2 to build reflectogram mosaics.*  

... but the content of the linked page doesn't seem to be specific to infrared, nor to reflectograms.  Maybe something like:  
* **Mosaic tour in nip2** 
* *How to build a mosaic from images of overlapping areas of the same subject, such as infrared reflectograms.*  

... in which I have left in the phrase "infrared reflectograms" so that it can still be found by Web search.

**Comment by jcupitt** [comment]
Hey, thanks for this, I've been working on the vips8 rewrite for years now and I can no longer see simple problems :-( It's very helpful to have a fresh pair of eyes look over it. 

I fixed the doc problems and the missing scrgb, see the commit.

Yes, `extract_area` is there twice. One of them is the `crop` alias.

The ppm thing works for me:

```
$ vips copy k2.jpg k2.ppm
$ vips colourspace k2.ppm k2.pgm b-w
$ nip2 k2.pgm 
```

It won't work for ppms which use something other than 0-255 for black to white, but there's not much it can do I think, there just isn't enough metadata in the format. You can use `vips copy` to tag the image by hand before running `vips colourspace`.

Yes, vips does very little automatic colourspace stuff. For example, if you load a .jpg, you get exactly the values stored in the file, there is no automatic ICC import. Things like that are supposed to be done by the application layer.

**Comment by jcupitt** [comment]
Ooop, I completely misread your point about `scrgb2bw`, sorry. 

scRGB uses float 0 - 1 for black to white, so you need a pfm rather than a ppm and needs to have the right range. 
 
The things that go to and from sRGB  and BW need to be under a different parent class because they can treat alpha differently. The other converters just operate on the first 1 - 3 bands (where the colour info is) and pass any other bands on unmodified. 

This mostly works well, except for 16-bit png and TIFF with alpha. There the later bands need to be scaled down to 0-255 (or up to 0-65535) on conversion.

**Comment by jcupitt** [comment]
I think I've fixed everything you found, I'll close. Please reopen if you spot anything I missed. Thanks for the report.
