### ISSUE TITLE
autotools version compatibility when building from GIT

### ISSUE THREAD

**Issue by RomanHargrave** [jcupitt/libvips#279]
Similar to #273.

It looks like this project was set up using an older revision autools. Trying bootstrap it results in the following output:

```
autoconf: configure.in: No such file or directory
/usr/bin/m4: cannot open `configure.in': No such file or directory
configure.ac:123: installing './config.guess'
configure.ac:123: installing './config.sub'
configure.ac:13: installing './install-sh'
configure.ac:330: error: required file './ltmain.sh' not found
configure.ac:13: installing './missing'
cplusplus/Makefile.am: installing './depcomp'
```

I'm running autoconf version 2.13, aclocal 1.14.1, and have tried using versions 2.50 and 2.64 of autoconf.

Although a `configure` script *is* generated, there are missing files. One such missing file is `Makefile.in`, which is required in order for `configure` to work.

**Comment by jcupitt** [comment]
Hi @RomanHargrave , I'm using whatever current stable Ubuntu uses:

```
$ autoconf --version
autoconf (GNU Autoconf) 2.69
```

It should work with 2.5 and later, I think. I'll try with an older autotools.

**Comment by jcupitt** [comment]
Yes, looks like it won't work with 2.13, but 2.5 and later ought to be fine.

**Comment by jcupitt** [comment]
Did you get this working? I'll close, please reopen if you didn't.

**Comment by RomanHargrave** [comment]
I did not, even with the requisite version. I ended up using a tarball with a preexisting configuration script.

**Comment by jcupitt** [comment]
How strange, it works here. It will need 2.50 or later, since it uses `configure.ac` rather then `configure.in`, but it should work. 

What platform are you using?

**Comment by RomanHargrave** [comment]
Debian Jessie. Autoconf 2.69. That's quite odd. 

Do notice that it complains of a missing ltmain.sh.

**Comment by jcupitt** [comment]
I just tried on a wheezy install here and it worked fine. Very odd!

I had to install glib-2.0-dev, libxml2-dev, swig, gtk-doc-tools, autoconf and gobject-introspection.

**Comment by RomanHargrave** [comment]
That's very odd. This does not look to be a dependency issue, as I have all of those, nor should they affect autoconf's behavior.

In a fresh clone of libvips from this repository on master, this is the output of `bootstrap.sh`

```
testing for glibtoolize ...
using libtoolize
configure.ac:123: installing './config.guess'
configure.ac:123: installing './config.sub'
configure.ac:13: installing './install-sh'
configure.ac:330: error: required file './ltmain.sh' not found
configure.ac:13: installing './missing'
cplusplus/Makefile.am: installing './depcomp'
python/Makefile.am:2: installing './py-compile'
parallel-tests: installing './test-driver'
```

As you can see, autoconf is failing due to `ltmain.sh` not being present.

This is the (end of the) output of the configuration script:

```
configure: creating ./config.status
config.status: creating vips.pc
config.status: creating vipsCC.pc
config.status: creating vips-cpp.pc
config.status: error: cannot find input file: `Makefile.in'
```

The full output [may be seen here](http://sprunge.us/bYBg)

Once again, `configure` should have failed differently if this were a dependency issue, so this makes me wonder if there is some oddity going on with autotools. Have you tried on jessie?

Some more about my autotools environment:

```
$ libtool --version
libtool (GNU libtool) 2.4.2
Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>, 1996

Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
---
Autoconf 2.50 chosen by Debian wrapper script.
For information and tuning advice see autoconf(1).

$ automake --version
automake (GNU automake) 1.14.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

$ autoscan --version
autoscan (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

$ autoheader --version
autoheader (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Roland McGrath and Akim Demaille.
---
Autoconf 2.50 chosen by Debian wrapper script.
For information and tuning advice see autoconf(1).

$ autom4te --version
autom4te (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Akim Demaille.

$ autoupdate --version
autoupdate (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```

Interestingly enough, running `autoreconf --install` *after* running `bootstrap.sh` (and `configure`) will install `ltmain.sh` (whereas the same command would previously fail, complaining that `ltmain.sh` was not present)

Even stranger, is the fact that running configure after the above sequence *works*. AutoTools can really be a strange thing at times.

**Comment by jcupitt** [comment]
I've made a new tag just for this issue and closed it. If anyone has any good ideas, please reopen!

**Comment by RomanHargrave** [comment]
AutoTools (and QMake, among others) will certainly do that! I'm not an AutoTools wizard, but I might look in to this if I get some time.
