### ISSUE TITLE
Static Library for iOS 

### ISSUE THREAD

**Issue by skela** [jcupitt/libvips#280]
I am trying to include libvips in an Xcode project, to be used in an iPhone app to generate deep zoom tiles from big images. So far I've tried to generate static libs for all the various architectures and then using Xcode's lipo tool to combine them into a fat library. At the end of it all I end up with 3 fat libraries that I include in my Xcode project.

	skela@skelimac:~/Desktop/libvips-objc$ lipo -info libvips.a ; lipo -info libvips-cpp.a ; lipo -info libvipsCC.a
	Architectures in the fat file: libvips.a are: armv7 armv7s i386 x86_64 arm64
	Architectures in the fat file: libvips-cpp.a are: armv7 armv7s i386 x86_64 arm64
	Architectures in the fat file: libvipsCC.a are: armv7 armv7s i386 x86_64 arm64

I've updated my project's Header search paths and library search paths, but getting linking errors and complaints about undefined symbols.

	Ld /Users/skela/Library/Developer/Xcode/DerivedData/DrawingTest-bcabavjuthzdnjbzvwnjpqxekpmc/Build/Products/Debug-iphoneos/DrawingTest.app/DrawingTest normal armv7
	    cd /Users/skela/code/introlabs/constructor/ios/Tests/DrawingTest
	    export IPHONEOS_DEPLOYMENT_TARGET=8.2
	    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
	    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk -L/Users/skela/Library/Developer/Xcode/DerivedData/DrawingTest-bcabavjuthzdnjbzvwnjpqxekpmc/Build/Products/Debug-iphoneos -L/Users/skela/Desktop/PhotoScrollerNetwork/libturbojpeg -L/Users/skela/code/introlabs/constructor/ios/Tests/DrawingTest -L/Users/skela/Desktop/libvips-objc -F/Users/skela/Library/Developer/Xcode/DerivedData/DrawingTest-bcabavjuthzdnjbzvwnjpqxekpmc/Build/Products/Debug-iphoneos -F/Users/skela/code/introlabs/constructor/ios/Tests/DrawingTest/Pods/OpenCV -F/Users/skela/code/introlabs/constructor/ios/Tests/DrawingTest -filelist /Users/skela/Library/Developer/Xcode/DerivedData/DrawingTest-bcabavjuthzdnjbzvwnjpqxekpmc/Build/Intermediates/DrawingTest.build/Debug-iphoneos/DrawingTest.build/Objects-normal/armv7/DrawingTest.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -ObjC -lPods-DrawingTest-ARTiledImageView -lPods-DrawingTest-EKTilesMaker -lPods-DrawingTest-NAMapKit -lPods-DrawingTest-SDWebImage -lstdc++ -framework AVFoundation -framework Accelerate -framework AssetsLibrary -framework CoreGraphics -framework CoreImage -framework CoreMedia -framework CoreVideo -framework Foundation -framework ImageIO -framework QuartzCore -framework UIKit -framework opencv2 -fobjc-arc -fobjc-link-runtime -stdlib=libc++ -miphoneos-version-min=8.2 -lc -lc++ -framework QuartzCore -framework Accelerate -framework CoreGraphics -framework CoreFoundation -lvips -lvips-cpp -lvipsCC -framework ImageIO -lPods-DrawingTest -Xlinker -dependency_info -Xlinker /Users/skela/Library/Developer/Xcode/DerivedData/DrawingTest-bcabavjuthzdnjbzvwnjpqxekpmc/Build/Intermediates/DrawingTest.build/Debug-iphoneos/DrawingTest.build/Objects-normal/armv7/DrawingTest_dependency_info.dat -o /Users/skela/Library/Developer/Xcode/DerivedData/DrawingTest-bcabavjuthzdnjbzvwnjpqxekpmc/Build/Products/Debug-iphoneos/DrawingTest.app/DrawingTest

	Undefined symbols for architecture armv7:
	  "_fftw_plan_dft_c2r_2d", referenced from:
	      _rinvfft1 in libvips.a(invfft.o)
	  "_fftw_execute_dft_c2r", referenced from:
	      _rinvfft1 in libvips.a(invfft.o)
	  "_cmsCreateTransform", referenced from:
	      _vips_icc_build in libvips.a(icc_transform.o)
	  "_cmsCreateLab4Profile", referenced from:
	      _vips_icc_export_build in libvips.a(icc_transform.o)
	      _vips_icc_import_build in libvips.a(icc_transform.o)
	  "_cmsCreateXYZProfile", referenced from:
	      _vips_icc_export_build in libvips.a(icc_transform.o)
	      _vips_icc_import_build in libvips.a(icc_transform.o)
	  "_cmsGetColorSpace", referenced from:
	      _vips_icc_profile_needs_bands in libvips.a(icc_transform.o)
	      _vips_icc_build in libvips.a(icc_transform.o)
	      _is_pcs in libvips.a(icc_transform.o)
	  "_cmsIsIntentSupported", referenced from:
	      _vips_check_intent in libvips.a(icc_transform.o)
	  "_cmsOpenProfileFromMem", referenced from:
	      _vips_icc_load_profile_image in libvips.a(icc_transform.o)
	      _vips_icc_export_build in libvips.a(icc_transform.o)
	  "_fftw_plan_dft_r2c_2d", referenced from:
	      _rfwfft1 in libvips.a(fwfft.o)
	  "_fftw_plan_dft_2d", referenced from:
	      _cfwfft1 in libvips.a(fwfft.o)
	      _cinvfft1 in libvips.a(invfft.o)
	  "_fftw_destroy_plan", referenced from:
	      _cfwfft1 in libvips.a(fwfft.o)
	      _rfwfft1 in libvips.a(fwfft.o)
	      _rinvfft1 in libvips.a(invfft.o)
	      _cinvfft1 in libvips.a(invfft.o)
	  "_TIFFReadEncodedTile", referenced from:
	      _write_copy_tiff in libvips.a(vips2tiff.o)
	  "_GetImagePixels", referenced from:
	      _get_pixels in libvips.a(magick2vips.o)
	  "_g_realloc", referenced from:
	      _write_buf_grow in libvips.a(vipspng.o)

+ More lines of errors like that (201 errors)

I'm just wondering if you guys have heard about any (hopefully successful) attempts at using this library on iOS before, or if not, whether you have any tips as to what I need to do in order to get this thing to run.

I can stick what I've done in a git repo if there's an appetite for it, but just wondering if I'm on the right track or not.
![screen shot 2015-04-23 at 13 00 33](https://cloud.githubusercontent.com/assets/58268/7290869/e98db86a-e9b8-11e4-931a-9fa86c0210fe.png)

**Comment by jcupitt** [comment]
Sorry, I can't point you to any iOS users, though I should think it would work pretty easily. 

Looks like your libvips.a didn't build correctly, it's missing things like libMagick, libfftw3, liblcms2 and so on. I'd go back and see how it was made. 

vips can use lots and lots of sub-libraries to let it support various formats and various image processing operations. You probably don't need them, so I'd disable most of the optional features, like fftw3 and libMagick. Run configure again and check the summary at the end. I guess you're using --enable-static?

You won't be able to generate a completely static library, I expect you know. 

`libvipsCC.a` is the vips7 C++ binding, libvips-cpp.a is the vips8 C++ binding, you probably don't need both. On mobile, I'd probably just use the C API, so you only need `libvips.a`.

Good luck!

**Comment by jcupitt** [comment]
I meant to say, if you get it working, could you post some quick notes here? I'm sure other people would find it useful.

**Comment by skela** [comment]
Yeah, I'll post it as soon as I get something working :D 

What do you mean by I won't be able to generate a completely static library ?

I don't really have to take the static lib route, but I just couldn't think of another approach to use this stuff in iOS. Adding some .a files and headers is simple enough. I'm certainly open to suggestions.

Thanks, I assumed that libvipsCC.a and libvips-cpp.a wasn't needed, was just clutching at straws to try and make it work. Thanks for the  libgsf and libjpeg message, thats super helpful, I'll try and strip away all the un-needed stuff, and yeah I wasn't actually using --enable-static, silly me. 

Atm this is what I do to create stuff (I do this for each architecture):

	./configure --prefix="$pwd/output/$target" --disable-shared --enable-static --host=$hosttarget-apple-darwin
	make clean
	make
	make install

I just noticed that I get an error at the end of make install that might explain what the problem is:

	Making install in tools
	/bin/sh ../libtool  --tag=CC   --mode=link /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -miphoneos-version-min=8.3 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -o vips vips.o -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pango/1.36.8/include/pango-1.0 -I/usr/local/Cellar/orc/0.4.23/include/orc-0.4 -I/usr/local/Cellar/little-cms2/2.6/include -I/usr/local/Cellar/libtiff/4.0.3/include -I/usr/local/Cellar/libpng/1.6.16/include/libpng16 -I/usr/local/Cellar/libgsf/1.14.30/include/libgsf-1 -I/usr/local/Cellar/libexif/0.6.21/include -I/usr/local/Cellar/imagemagick/6.9.0-10/include/ImageMagick-6 -I/usr/local/Cellar/harfbuzz/0.9.38/include/harfbuzz -I/usr/local/Cellar/glib/2.42.2/lib/glib-2.0/include -I/usr/local/Cellar/glib/2.42.2/include/glib-2.0 -I/usr/local/Cellar/freetype/2.5.5/include/freetype2 -I/usr/local/Cellar/freetype/2.5.3_1/include/freetype2 -I/usr/local/Cellar/fontconfig/2.11.1/include -I/usr/local/Cellar/fftw/3.3.4_1/include -I/usr/include/libxml2 -D_REENTRANT -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 ../libvips/libvips.la -L/usr/local/Cellar/imagemagick/6.9.0-10/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16  -L/usr/local/Cellar/libpng/1.6.16/lib -lpng16  -L/usr/local/Cellar/libtiff/4.0.3/lib -ltiff  -lz   -L/usr/local/Cellar/glib/2.42.2/lib -L/usr/local/opt/gettext/lib -lgmodule-2.0 -lxml2 -lgobject-2.0 -lglib-2.0 -lintl  -L/usr/local/Cellar/pango/1.36.8/lib -L/usr/local/Cellar/glib/2.42.2/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/fontconfig/2.11.1/lib -L/usr/local/Cellar/freetype/2.5.5/lib -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lfontconfig -lfreetype  -L/usr/local/Cellar/libgsf/1.14.30/lib -L/usr/local/Cellar/glib/2.42.2/lib -L/usr/local/opt/gettext/lib -lgsf-1 -lgobject-2.0 -lglib-2.0 -lintl -lxml2  -L/usr/local/Cellar/fftw/3.3.4_1/lib -lfftw3  -L/usr/local/Cellar/orc/0.4.23/lib -lorc-0.4  -L/usr/local/Cellar/little-cms2/2.6/lib -llcms2       -L/usr/local/Cellar/libexif/0.6.21/lib -lexif  -lm
	libtool: link: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -miphoneos-version-min=8.3 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -o vips vips.o -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pango/1.36.8/include/pango-1.0 -I/usr/local/Cellar/orc/0.4.23/include/orc-0.4 -I/usr/local/Cellar/little-cms2/2.6/include -I/usr/local/Cellar/libtiff/4.0.3/include -I/usr/local/Cellar/libpng/1.6.16/include/libpng16 -I/usr/local/Cellar/libgsf/1.14.30/include/libgsf-1 -I/usr/local/Cellar/libexif/0.6.21/include -I/usr/local/Cellar/imagemagick/6.9.0-10/include/ImageMagick-6 -I/usr/local/Cellar/harfbuzz/0.9.38/include/harfbuzz -I/usr/local/Cellar/glib/2.42.2/lib/glib-2.0/include -I/usr/local/Cellar/glib/2.42.2/include/glib-2.0 -I/usr/local/Cellar/freetype/2.5.5/include/freetype2 -I/usr/local/Cellar/freetype/2.5.3_1/include/freetype2 -I/usr/local/Cellar/fontconfig/2.11.1/include -I/usr/local/Cellar/fftw/3.3.4_1/include -I/usr/include/libxml2 -D_REENTRANT -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0  ../libvips/.libs/libvips.a -L/usr/local/Cellar/imagemagick/6.9.0-10/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/lib -L/usr/local/Cellar/freetype/2.5.5/lib -L/usr/local/Cellar/xz/5.2.1/lib -L/usr/local/Cellar/libpng/1.6.16/lib -L/usr/local/Cellar/libtiff/4.0.3/lib -L/usr/local/Cellar/glib/2.42.2/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/pango/1.36.8/lib -L/usr/local/Cellar/fontconfig/2.11.1/lib -L/usr/local/Cellar/libgsf/1.14.30/lib -L/usr/local/Cellar/fftw/3.3.4_1/lib -L/usr/local/Cellar/orc/0.4.23/lib -L/usr/local/Cellar/little-cms2/2.6/lib -L/usr/local/Cellar/libexif/0.6.21/lib /usr/local/Cellar/imagemagick/6.9.0-10/lib/libMagickWand-6.Q16.dylib /usr/local/Cellar/imagemagick/6.9.0-10/lib/libMagickCore-6.Q16.dylib -llzma -lbz2 -lltdl -lpng16 -ltiff -lz -lgmodule-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lgsf-1 -lgobject-2.0 -lglib-2.0 -lintl -lxml2 -lfftw3 -lorc-0.4 -llcms2 -lexif -lm -pthread
	clang: warning: argument unused during compilation: '-pthread'
	ld: library not found for -lltdl
	clang: error: linker command failed with exit code 1 (use -v to see invocation)
	make[1]: *** [vips] Error 1
	make: *** [install-recursive] Error 1

**Comment by jcupitt** [comment]
True static linking isn't really supported any more. You'll need to link dynamically against at least libc and libpthread, I think.

Yes, you'll need to get ltdl working, I think. 

If you don't need static linking, just go dynamic, it's simpler. You just copy the dylibs into your target lib area and make sure DYLD_PATH or whatever it's called points there, they will get picked up. This is how I do the OS X .app for nip2. 

You can use jhbuild to automate the building of the things that vips depends on, did you see the build on os x package?

https://github.com/jcupitt/build-osx

**Comment by skela** [comment]
I realise now that I've never had to do any kind of dynamic linking before for mobile. But unfortunately, I'm finding lots of information about how dynamic linking is not supported or even allowed on iOS, so this cannot be done that route (Apple rejects the app when you try to upload it to the App Store if dynamic libs are found).

So its either static linking, but maybe I could look into attaching the code to the Xcode project directly.
Just in case you didn't know, iOS development is done in Objective-c , and you can include both C and C++ code in your projects.

I wasn't able to get jhbuild working, but ill keep that in mind.

**Comment by skela** [comment]
If anyone is interested here's the repo of the current state of my attempt to build libvips for iOS
https://github.com/skela/libvips-objc

My build script copies lib_build.sh into the libvips folder and then runs it, then after its done, it runs lipo to glue the architectures together into a fat library.

If I am to take the static route, it does look like I might have to do this for each of the dependancies (libpng which depends on zlib, libjpeg, etc), and I'm not sure thats gonna be possible as I can't really guarantee that each of these dependancies can be compiled for armv7, armv7s or arm64 etc.

**Comment by bgilbert** [comment]
Take a look at the GStreamer SDK.  It includes quite a bit of Linux multimedia software, including many of VIPS' dependencies, and ships binaries for iOS.  You can probably reuse their build scripts so you don't have to figure out how to build the dependencies yourself.

(Unfortunately, if you're going to distribute your app to others, you may not be able to use their *binaries*, since they don't provide complete corresponding sources for the LGPL libraries and it's not completely straightforward to deduce what those are.)

**Comment by jcupitt** [comment]
Ah, I didn't realize dynamic linking was banned. Yes, @bgilbert's gstreamer SDK idea sounds like a good one.

**Comment by jcupitt** [comment]
I'll close this, it seems to be answered.

**Comment by cup** [comment]
https://github.com/libvips/libvips/issues/1067
https://github.com/libvips/libvips/issues/1079
https://github.com/libvips/libvips/issues/280
https://github.com/libvips/libvips/issues/365
