### ISSUE TITLE
im_global_balance in command line doesn't work as task in nips

### ISSUE THREAD

**Issue by hksonngan** [jcupitt/libvips#281]
Hello, I'm new with vips, I try mosaic two image, it works but when I test im_global_balancef I always got error message mosaic root not found in desk file.
But same this files works in nip2
this files is 16 bit grey.

E:\DR_Project\vips-dev-7.42.3\bin>vips im_tbmosaic E:\ASANHospital\Stitch\wholebody\3-Hip.tiff E:\ASANHospital\Stitch\wholebody\4-Knee.tiff testvipsHIP_KNEE.v 0 73 2553 0 0 5 15 0 90

E:\DR_Project\vips-dev-7.42.3\bin>vips im_global_balance testvipsHIP_KNEE.v testvipsHIP_KNEE_out.v 1.6

I try debug and it stuck in this function generate_trn_leaves line 		

if( !node->im ) {
			im_error( "im_global_balance", 
				_( "unable to open \"%s\"" ), node->name );
			return( node );
		}

**Comment by jcupitt** [comment]
Hi, global_balance only works within a process, so I'm afraid it won't work from the command-line. 

I would use Python or nip2 to do the mosaicing operation. You can use nip2 from the command-line as well, if that helps.

**Comment by hksonngan** [comment]
thank you for your answer. So it means that it same situation when I call global_balance in when link via libvpis library right. How can I attack to process for global_balance from c++ (sorry I don't know well about Python)?

**Comment by hksonngan** [comment]
thank you for your answer. 
As I call in C, I convert file to vips format and keep absolute path of these files when call im_open, and im_tbmosaic. global_balance will use these files to check overload and calculate gama value.
