### ISSUE TITLE
Please add macro wrap around __attribute__ to compile in Visual Studio

### ISSUE THREAD

**Issue by hksonngan** [jcupitt/libvips#282]
I try to compile in Visual Studio the main issue is Visual Studio don't support __attribute__. So I temporary remove it, and compile and debug success.

**Comment by jcupitt** [comment]
Hi @hksonngan , there is already a macro to do this:

https://github.com/jcupitt/libvips/blob/master/libvips/include/vips/vips.h#L100

As long as __GNUC__ is not defined, __attribute__ declarations should vanish. Is this not working for you?

**Comment by hksonngan** [comment]
thanks, I forgot update to new version.
