### ISSUE TITLE
im_vips2raw hang when export multiband

### ISSUE THREAD

**Issue by hksonngan** [jcupitt/libvips#283]
Hello,
I export tiff file with multi-band (4 band, 16bps), same code work with libvips 7.20.7 but with new version 7.42.3 it hang and nothing notify.
here is file to test https://github.com/hksonngan/mosaic/blob/master/Data/spine0_noRule.tif

And I have question can I export only seperate band to seperate file? or only 1 band export from multi band?

			if( !( img_convert = im_open( output_file_v, "w" ) ) )
				error_exit( "find_mosaic: unable to open %s for input", output_file_v );

			err_no = _sopen_s(&fd, output_file_raw, _O_CREAT|_O_WRONLY|_O_BINARY|_O_TRUNC, _SH_DENYNO, _S_IREAD | _S_IWRITE);

			im_tiff2vips( argv[ i ], img_convert );
			im_vips2raw(img_convert, fd);
			close(fd);

**Comment by jcupitt** [comment]
Hi @hksonngan , I made this test program:

https://gist.github.com/jcupitt/dcdb7ab0e38385c85cb7

It seems to work for me with vips 8.0:

```bash
$ gcc -g -Wall try223.c `pkg-config vips --cflags --libs`
$ ./a.out ~/Desktop/spine0_noRule.tif x
$ ls -l x
-rw-r--r-- 1 john john 72000000 Apr 29 10:48 x
```

Which is the correct number of bytes. I'll try with 7.42.

**Comment by jcupitt** [comment]
Yes, working for me on 7.42 as well. What platform are you on? Is it Windows?

Could you try doing the conversion at the command-line? Try:

```
$ vips rawsave ~/Desktop/spine0_noRule.tif x
```

and see if `x` is the correct size.

**Comment by jcupitt** [comment]
I'm not sure I understand your band question. Do you want to save a single band from your multi-band tiff as a raw?

**Comment by hksonngan** [comment]
Hi, yes I test in Visual Studio, Windows 7 64bit. strange it works in command line but doesn't work in visual studio. I test with minGW, it works. anyway I will change to compile my code in minGW.

In this file spine0_noRule.tif is saved in RGBA format and 16bits. I export to raw format of R band. Is this possible?

**Comment by jcupitt** [comment]
You can do it at the command-line in two stages. First, extract band 0 (R) to the vips file x.v:

```
$ vips extract_band spine0_noRule.tif x.v 0
```

Then convert that to raw:

```
$ vips rawsave x.v x.raw
$ rm x.v
```

Of course this means you have to write, read and delete a (potentially) large file. You can do it in one step in C, C++ or Python.

**Comment by hksonngan** [comment]
I try to top bottom mosaic two image 
https://github.com/hksonngan/mosaic/blob/master/Data/spine0_noRule.tif
https://github.com/hksonngan/mosaic/blob/master/Data/spine1_noRule.tif

in Nip2 but I always get error: Macro error, bad properties.
And when I change size of Windows and Object in preference diaglog Nip2 crash.

And I write small test in C++, but im_tbmosaic return wrong position, it change position so far
in here trans_x = 35, trans_y 2195 but im_tbmosaic change this position to 21 and 2235.

                im_tbmosaic( sourceimg, targetimg, tmpOut[k], 0, trans_x, trans_y, 0, 0, 5, 15, 0, 100 );

But test with other images in Nip2, it works.

here is ws file:

<?xml version="1.0"?>
<root xmlns="http://www.vips.ecs.soton.ac.uk/nip/7.42.1">
  <Workspace window_x="214" window_y="280" window_width="1378" window_height="846" view="WORKSPACE_MODE_REGULAR" scale="1" offset="0" locked="false" lpane_position="100" lpane_open="false" rpane_position="400" rpane_open="false" local_defs="// private definitions for this tab&#10;" name="tab2" caption="Default empty tab" filename="E:\DR_Project\WB2img.ws">
    <Column x="0" y="0" open="true" selected="false" sform="false" next="4" name="A">
      <Subcolumn vislevel="3">
        <Row popup="false" name="A1">
          <Rhs vislevel="2" flags="5">
            <iImage window_x="813" window_y="105" window_width="750" window_height="750" image_left="1840" image_top="1780" image_mag="-5" show_status="false" show_paintbox="false" show_convert="false" show_rulers="false" scale="1" offset="0" falsecolour="false" type="true"/>
            <Subcolumn vislevel="0"/>
            <iText formula="Image_file &quot;E:\\DR_Project\\spine0_norule.tif&quot;"/>
          </Rhs>
        </Row>
        <Row popup="false" name="A2">
          <Rhs vislevel="2" flags="5">
            <iImage image_left="0" image_top="0" image_mag="0" show_status="false" show_paintbox="false" show_convert="false" show_rulers="false" scale="0" offset="0" falsecolour="false" type="true"/>
            <Subcolumn vislevel="0"/>
            <iText formula="Image_file &quot;E:\\DR_Project\\spine1_norule.tif&quot;"/>
          </Rhs>
        </Row>
      </Subcolumn>
    </Column>
    <Column x="0" y="258" open="true" selected="false" sform="false" next="11" name="B">
      <Subcolumn vislevel="3">
        <Row popup="false" name="B2">
          <Rhs vislevel="2" flags="5">
            <iArrow>
              <iRegiongroup/>
            </iArrow>
            <Subcolumn vislevel="0"/>
            <iText formula="Mark A1 35 2195"/>
          </Rhs>
        </Row>
        <Row popup="false" name="B3">
          <Rhs vislevel="3" flags="7">
            <iArrow>
              <iRegiongroup/>
            </iArrow>
            <Subcolumn vislevel="1"/>
            <iText formula="Mark A2 0 0"/>
          </Rhs>
        </Row>
        <Row popup="false" name="B5">
          <Rhs vislevel="3" flags="7">
            <iImage window_x="1850" window_y="419" window_width="750" window_height="750" image_left="3312" image_top="3204" image_mag="-9" show_status="false" show_paintbox="false" show_convert="false" show_rulers="false" scale="1" offset="0" falsecolour="false" type="true"/>
            <Subcolumn vislevel="0"/>
            <iText formula="Tasks_mosaic_item.Mosaic_1point_item.Top_bottom_item.action A1 A2"/>
          </Rhs>
        </Row>
      </Subcolumn>
    </Column>
  </Workspace>
</root>

**Comment by jcupitt** [comment]
Your ws file is joining the two images (A1 and A2) not the two regions (B2 and B3). You need to move B£ as well, it's at (0, 0).

I get this result:

![spine](https://cloud.githubusercontent.com/assets/580843/7413010/018bb412-ef40-11e4-8092-d9b6989ab54f.png)

No great, to be honest :-( I think your subject moved too much between the xrays, and a 2D mosaic won't work well on a 3D object, unfortunately.

**Comment by hksonngan** [comment]
It doesn't both in Windows and Unix. I change to B2 and B3 or delete everything to restart I always get error in nip2 like this:

Error in row B11.super.value: VIPS library error.
Error calling library function "im_tbmosaic" (top-bottom mosaic of in1 and in2).
VIPS library: max: parameter out not set

You passed:
   ref - 3000x3000 16-bit unsigned integer, 4 bands, RGB16
   sec - 3000x3000 16-bit unsigned integer, 4 bands, RGB16
   bandno - 0
   xr - 35
   yr - 2195
   xs - 0
   ys - 0
   halfcorrelation - 2
   halfarea - 7
   balancetype - 0
   mwidth - 10

Usage:
CALL operator "im_tbmosaic"
top-bottom mosaic of in1 and in2, from package "mosaicing"
"im_tbmosaic" takes 11 arguments:
   ref  - image
   sec  - image
   bandno  - integer
   xr  - integer
   yr  - integer
   xs  - integer
   ys  - integer
   halfcorrelation  - integer
   halfarea  - integer
   balancetype  - integer
   mwidth  - integer
And produces 1 result:
   out  - image
Flags:
   (PIO function) (coordinate transformer) (area operation) (operation can be cached)

As I set blendwidth to 500 here is result from C++, look better :D

![finalstitch 1 0 25](https://cloud.githubusercontent.com/assets/780912/7414380/482bf394-ef8d-11e4-8beb-e6fae06961d8.jpg)

**Comment by jcupitt** [comment]
Your workspace works for me after I adjusted the points, here:

https://gist.github.com/jcupitt/1b67f2d06ffc783a9bd5

**Comment by hksonngan** [comment]
Thanks. It works now after I update to last version of nip2.

An I have another question. Does libvips support private tag?
Because when I open this file: https://github.com/hksonngan/mosaic/blob/master/Data/WB1.tiff
in nip2 it works but open with vips.exe I got error like this:

E:\DR_Project\vips-dev-8.0.2\bin>vips im_tiff2vips e:\dr_project\wb1.tiff wb1.v
vips warning: TIFFReadDirectory: Unknown field with tag 65277 (0xfefd) encountered
vips warning: TIFFReadDirectory: Unknown field with tag 65277 (0xfefd) encountered
vips warning: linecache: error reading tile 0x3008: TIFFFillStrip: Invalid strip byte count 0, strip 1
tiff2vips: read error

E:\DR_Project\vips-dev-8.0.2\bin>vips -v
vips-8.0.2-Tue May  5 15:46:00 BST 2015

I can open in ImageJ and Nip2.

**Comment by jcupitt** [comment]
I think your file is corrupt. If I open in nip2 I see:

```bash
$ nip2 ~/Desktop/WB1.tiff
vips warning: TIFFReadDirectory: Unknown field with tag 65277 (0xfefd) encountered
vips warning: TIFFReadDirectory: Unknown field with tag 65277 (0xfefd) encountered
vips warning: TIFFReadDirectory: Unknown field with tag 65277 (0xfefd) encountered
vips warning: linecache: error reading tile 0x3008: TIFFFillStrip: Invalid strip byte count 0, strip 1
tiff2vips: read error
```

And if you look at the bottom of the file, you'll see the final chunk is missing. ImageJ misses the final chunk too. 

Private tags is a strange one. The design of libtiff unfortunately means it's not possible too read tags unless you know the format in advance. You'll find `tiffcp` fails on your file as well, and fails to copy the private tag:

```bash
$ tiffcp ~/Desktop/WB1.tiff x.tif
TIFFReadDirectory: Warning, Unknown field with tag 65277 (0xfefd) encountered.
/home/john/Desktop/WB1.tiff: Warning, using top-left orientation.
TIFFFillStrip: Invalid strip byte count 0, strip 1.
/home/john/Desktop/WB1.tiff: Error, can't read strip 1.
```

**Comment by hksonngan** [comment]
Thanks. 
And libvips current doesn't support 12 and 14 bps tiff format. Do you have plant add this?

**Comment by jcupitt** [comment]
It could be added I guess, I've never need 12 or 14 bit. Open a new issue and attach a couple of sample images and we can have a look.

**Comment by jcupitt** [comment]
I'll close this, it seems to be done.
