### ISSUE TITLE
Multi pages PDF

### ISSUE THREAD

**Issue by DrorSegev** [jcupitt/libvips#284]
Trying to convert multi page pdf into multiple-tiled Tiffs
Tried:
vips msb b.pdf output_image*.tif[compression=jpeg,tile=256x256,pyramid]
vips msb b.pdf output_image%03d.tif[compression=jpeg,tile=256x256,pyramid]

with no luck. Always getting the first pdf page.
Is it possible with vips?
Thanks
Dror

**Comment by jcupitt** [comment]
Hi @DrorSegev , it's not great, but you can use the `all_frames` option:

```
$ vips copy a.pdf[all_frames] a.tif
```

You'll get a tall, thin image with all of the pages written one after the other. You'll need to cut out each page, convert to 8-bit and save each page as a tiff. 

In Python, something like:

```python
#!/usr/bin/python

import sys

from gi.repository import Vips

# dpi to render PDFs at, has to be a string
DENSITY = "200"

# get size of each page
pdf = Vips.Image.new_from_file(sys.argv[1], 
                               density = DENSITY)

page_width = pdf.width
page_height = pdf.height

# open again, this time get all the pages run together
pdf = Vips.Image.new_from_file(sys.argv[1], 
                               density = DENSITY, all_frames = True)

n_pages = pdf.height / page_height

for page_number in range(n_pages):
    print("writing page %d ..." % page_number)
    page = pdf.crop(0, page_number * page_height, page_width, page_height)
    page = page.msb()
    page.write_to_file("page-%d.tif" % page_number)
```

**Comment by jcupitt** [comment]
Did this fix your issue? Please reopen if it didn't.

**Comment by jcupitt** [comment]
vips now has it's own PDF loader (it used to use the ImageMagick one) which lets you pull out a page or range of pages. See:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-VipsForeignSave.html#vips-pdfload
