### ISSUE TITLE
How can i simply change the the type of the image?

### ISSUE THREAD

**Issue by shilpi230** [jcupitt/libvips#285]
I have lot of images with different formats like jpeg,png,bmp,gif etc. Does vips has some unified command which can run on every type of format instead of using jpegsave, pngsave etc.

**Comment by shilpi230** [comment]
Never

**Comment by jcupitt** [comment]
`magickload` will use imagemagick to load the image. This can be much, much slower than the native vips loaders.

From the command-line, just use the file format extension, for example:

```
vips copy x.tif y.jpg
vips invert x.gif z.png
```

From C, use `vips_image_new_from_file()` and friends:

```
VipsImage *input = vips_image_new_from_file ("x.tif", NULL);
vips_image_write_to_file (input, "y.png", NULL);
```

**Comment by shilpi230** [comment]
I can use copy with any filetype to any filetype ?

**Comment by jcupitt** [comment]
Sure. It picks the loader and saver for you automatically. 

Loaders are chosen by looking at the first few bytes of the file for a magic number, savers are picked by looking at the filename extension.

**Comment by shilpi230** [comment]
Thank you. I also want quality parameter as we have in webpsave. And can you please write documentation on vips command line usage. It will be very helpful for everyone. :)

**Comment by jcupitt** [comment]
Do you mean you want to be able to set the webp quality with `vips copy`? Try:

```
$ vips copy x.tif y.webp[Q=90]
```

The docs are here:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/index.html

The command-line interface is documented in the first chapter:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-cli.html

**Comment by shilpi230** [comment]
Thank you. No, i need the quality for reverse i.e from webp to any other image format. command that you gave is not working.

**Comment by jcupitt** [comment]
You can set Q for jpeg save. Is that what you mean?

**Comment by shilpi230** [comment]
yes how do we do for jpegsave no ```vips jpegsave x.gif y.jpeg --Q=60``` Same way i need it for ```vips copy```.

**Comment by jcupitt** [comment]
Try:

```
vips copy x.tif y.jpg[Q=90]
```

This is in the docs, see the last section:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-cli.html#using-command-line-conversion

**Comment by shilpi230** [comment]
yes i saw that but Its not working. Its telling ```No matches found```.

**Comment by jcupitt** [comment]
Do you have some extra spaces in there? Copy-paste the exact command that's failing and the exact error.

**Comment by shilpi230** [comment]
```vips affine k2.jpg x.jpg[Q=90,strip] "2 0 0 1"```
```zsh: no matches found: x.jpg[Q=90,strip]```

this proper documentation example itself is failing.

**Comment by jcupitt** [comment]
Ah, you're using zsh. It has strange quoting rules, you'll need to check the docs for your shell. Maybe try `"` around the output argument?

```
vips affine k2.jpg "x.jpg[Q=90,strip]" "2 0 0 1"
```

**Comment by shilpi230** [comment]
oh.. yeah it works now.. thank you so much :D

**Comment by shilpi230** [comment]
For Png images Quality parameter Q didn't work. :(

**Comment by jcupitt** [comment]
Hi again, you can see the parameters if you run the save operation directly. Try:

```
$ vips pngsave
save image to png file
usage:
   pngsave in filename
where:
   in           - Image to save, input VipsImage
   filename     - Filename to save to, input gchararray
optional arguments:
   compression  - Compression factor, input gint
			default: 6
			min: 0, max: 9
   interlace    - Interlace image, input gboolean
			default: false
   profile      - ICC profile to embed, input gchararray
   filter       - libpng row filter flag(s), input VipsForeignPngFilter
   strip        - Strip all metadata from image, input gboolean
			default: false
   background   - Background value, input VipsArrayDouble
operation flags: sequential-unbuffered nocache 
```

So you need:

```
$ vips copy k2.jpg x.png[compression=1]

```

**Comment by shilpi230** [comment]
Thank you it works :) but what about other image types does every different type requires different type of quality parameter?

**Comment by jcupitt** [comment]
Yes, each image format write library has a different set of parameters. For example, libtiff has `compression` to mean compression type, so jpeg, lzw, deflate, ccitt, and so on. libpng uses `compression` to mean deflate compression factor, an integer in 0 - 9. It has no effect on image quality, just on file size. 

vips lets you pass parameters to the image format libraries, it's the libraries that set the names and meanings of the parameters.

**Comment by shilpi230** [comment]
Ohh i got it. Then for images like bmp,gif etc what to do ?

**Comment by jcupitt** [comment]
libvips can't write bmp or gif. It can read them via libMagick, check `magickload` for the parameters.

**Comment by shilpi230** [comment]
ohh god is it ? even vips copy won't work ?

**Comment by jcupitt** [comment]
That's right, no gif or bmp write.
