### ISSUE TITLE
VipsForeignLoad: pdf is not a known file format

### ISSUE THREAD

**Issue by DrorSegev** [jcupitt/libvips#287]
Hi,

The following cmd line is working perfectly on my dev comuter, but returning error on another computer with same settings.

vips msb 172.pdf doutput_image.tif[compression=jpeg,tile=256x256,pyramid]

we are using vips 7.42.3

The error is: VipsForeignLoad: "172.pdf" is not a known file format

Thanks,

Dror

**Comment by DrorSegev** [comment]
Got it. It was missing GS

**Comment by upardhi** [comment]
I am getting same error 

C:\vips-dev-w64-web-8.6.4\vips-dev-8.6\bin>vips.exe msb E:\SPP\80HON\1.pdf E:\SPP\80HON\uma.tif[compression=jpeg,tile=256x256,pyramid]
VipsForeignLoad: "E:\SPP\80HON\1.pdf" is not a known file format

**Comment by jcupitt** [comment]
The `-web` Windows binary does not include the PDF loader. Try `-all`.

**Comment by kevinhq** [comment]
> Got it. It was missing GS

what does this mean? i run through the same issue.

**Comment by jcupitt** [comment]
I think @DrorSegev means GhostScript, but this won't fix the issue, it'll just load (very slowly) via imagemagick.
