### ISSUE TITLE
Missing soname bump in 8.0?

### ISSUE THREAD

**Issue by bgilbert** [jcupitt/libvips#288]
09b81b75 and 8d09db7c removed symbols (without, incidentally, dropping the corresponding prototypes from `vipscompat.h`) but the soname was not bumped for 8.0.  I'm not sure whether the double underscore was meant to imply that the symbols were intended only for internal use, but they *were* exposed in public headers.

**Comment by jcupitt** [comment]
Yes, they were internal things, relics of the vips7 -> vips8 process. I've removed them from the headers, thanks.

Are you sure I need a soname bump too? I think I bumped for 7.42 -> 8.0.

**Comment by bgilbert** [comment]
The soname version has been 40 since 7.42.1.  I would personally bump the ABI out of caution (since a third-party program could conceivably have used those APIs) but it's up to you.

**Comment by jcupitt** [comment]
OK, soname bumped, thank you @bgilbert
