### ISSUE TITLE
Cross compilation of libvips for Android

### ISSUE THREAD

**Issue by po9794** [jcupitt/libvips#289]
Hi,

Is it possible -at least theoretically- to cross compile libvips for android?
I would like to generate a .so lib that i could use in my python program (using cython).

**Comment by jcupitt** [comment]
Yes, it should work. I cross-compile the windows binaries on the VIPs
website from a Linux machine.

You'll need android builds of the various dependencies. Pygobject is the
obvious weird one, is that available for android?

**Comment by po9794** [comment]
I will check on that.
Just to be sure, will i need the .typelib?

**Comment by jcupitt** [comment]
Yes, but you can just copy it from the Linux or OS x build, it's portable.
That's what the windows build script does.

**Comment by po9794** [comment]
Thanks, i will let you know how that will go. I really hope that will work because it seems that python lacks of a memory efficient library for large image processing.

**Comment by jcupitt** [comment]
I'll close, please update if you manage to get it working.

**Comment by CrackerKSR** [comment]
> Thanks, i will let you know how that will go. I really hope that will work because it seems that python lacks of a memory efficient library for large image processing.

Hi, any update

**Comment by rushikeshsuryawanshi** [comment]
> Thanks, i will let you know how that will go. I really hope that will work because it seems that python lacks of a memory efficient library for large image processing.

Hey, did it worked for Android ? 
I'm looking for the same
