### ISSUE TITLE
VImage::write_to_buffer(suffix,buf, sizeoptions) work inproperly

### ISSUE THREAD

**Issue by huskier** [jcupitt/libvips#290]
Dear Cupitt,

I cannot make the following code work properly.
        size_t size;
        void *buf;
        out_img.write_to_buffer("PNG",&buf,&size);
I am quite sure that out_img(VImage type) is valid. I don't know what kind of "strings" for suffix parameter, and I've already tried out ".png", "PNG" etc.

BTW, I like the new C++ interface of VIPS8, however, there is no clear docs for the new interface by my best knowledge, and I have to guess the APIs, such as in_img.colourspace(), in_img.resize(), in_img.cast etc. Dear Cupitt, where can I find the new C++ APIs?

Thanks for your effort for providing such handy image library and tool, and they are served my every day use.

Simon

**Comment by jcupitt** [comment]
Hi @huskier I guess you saw these docs:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-cpp.html

All the vips8 APIs are supposed to be the same: they are made automatically from the main C API with a few simple rules. 

Yes, it should be `".png"`. I'll make you an example.

**Comment by jcupitt** [comment]
Oh dear, you're right, there's a reference counting bug. I'll fix it.

**Comment by jcupitt** [comment]
This example works for me now:

https://github.com/jcupitt/libvips/blob/master/cplusplus/examples/buffer.cpp

```bash
$ ./a.out ~/pics/k2.jpg x.tif --vips-leak
loaded 1450 x 2048 pixel image from /home/john/pics/k2.jpg
written to memory 0x7f495099b010 in png format, 3146655 bytes
loaded from memory, 1450 x 2048 pixel image
written back to  x.tif
memory: high-water mark 13.55 MB
```

**Comment by jcupitt** [comment]
I added a program to test the C++ API:

https://github.com/jcupitt/libvips/blob/master/cplusplus/examples/test.cpp

Hopefully this is fixed properly now. Please reopen if not.

**Comment by jcupitt** [comment]
Also, thank you for reporting this bug!

**Comment by huskier** [comment]
Works wonderful! Thank you very much.
