### ISSUE TITLE
`vips_affine` for upsampling introduces black fringes on bright edges in transparent image

### ISSUE THREAD

**Issue by gasi** [jcupitt/libvips#291]
Based on my reading, this is a common occurrence when resampling images with alpha channel and using non-`nearest` interpolation, but I don’t know how to work around it when using `vips_affine`. I uploaded a Gist with sample script comparing VIPS vs ImageMagick and some reference input and output images: https://gist.github.com/gasi/769cfb9f2359a1fbedc5

Please note the dark fringes around the white edges in the center when using `vips_affine` with non-`nearest` interpolation.

I assume I am missing something obvious. Does it have to do with premultiplying the alpha channel? http://www.peachpit.com/articles/article.aspx?p=520187&seqNum=3

Related:
- https://github.com/gasi/sharp/pull/3
- https://github.com/lovell/sharp/pull/211

**Comment by jcupitt** [comment]
I agree, it should multiply by the alpha before resampling. I found this page:

http://entropymine.com/imageworsener/resizealpha/

which seems to explain it very clearly.

**Comment by jcupitt** [comment]
... thinking out loud, I guess this should go into `vipsthumbnail` rather than vips_affine(). Sharp would need to implement this separately. Do you have an opinion @lovell?

I'll try some tests.

**Comment by lovell** [comment]
Yes, adding this to `vipsthumbnail` makes sense, thanks John. I'm happy to copypasta the improvements into sharp.

**Comment by gasi** [comment]
@jcupitt @lovell Thanks for weighing and confirming our theory. I have written some code to do premultiplication/unpremultiplication of the alpha channel yesterday and would love to get your input as I’d like to incorporate this into `sharp` as a short-term workaround: https://github.com/gasi/sharp/blob/3020ba41b438d3b999a803147a933db9848cf71a/src/resize.cc#L527-L572

**Comment by lovell** [comment]
@gasi I think the `vips_multiply` and friends needs to occur before the use of `vips_convsep`.

Does "unpremultiply" == "divide"? ;)

Am I right in thinking this problem affects 4 band colour+alpha only? If so, that can be the conditional (and therefore no external JS API is required - hooray).

Please can you create a PR for this into sharp's master branch.

**Comment by gasi** [comment]
> @gasi I think the vips_multiply and friends needs to occur before the use of vips_convsep.

Yes, I added it before/after doing any of the VIPS transformations (resizing, shrinking, blurring, etc.)

> Does "unpremultiply" == "divide"? ;)

LOL, yes! Taking suggestions, although it seems to be fairly standard according to Google.

> Am I right in thinking this problem affects 4 band colour+alpha only? If so, that can be the conditional (and therefore no external JS API is required - hooray).

Indeed, yay!

> Please can you create a PR for this into sharp's master branch.

Opened one against `knife` as it affected `Composite` to avoid double premultiplication :+1:

**Comment by jcupitt** [comment]
I did a little test. Here's a nip2 workspace that does premultiplication:

https://gist.github.com/jcupitt/8e8d792ec0f72411123e

Drag a PNG with an alpha into A1. You can click the "pre-multiply" toggle to turn premultiplication on and off. Doubleclick on C19 and zoom in on a detail, then toggle the premultiply. You can change any of the steps and watch the pixels change. 

Things I learned:

* linearization doesn't seem to make any significant difference in practice
* you need to clamp the alpha after the resize, or over and undershoots will produce some very odd effects

**Comment by jcupitt** [comment]
Here's the same thing in Python, in case it's clearer:

https://gist.github.com/jcupitt/bddfda77d2ef6e0a601c

The only tricksy bit is the premultiplication. We need to multiply RGB by alpha/255, but leave alpha itself untouched. One solution would be to split the image to separate RGB and alpha, scale, then reattach:

```python
alpha = image[3]
rgb = image[0:3]
norm_alpha = alpha / 255
rgb = rgb * norm_alpha
image = rgb.bandjoin(alpha)
```

But all that chopping and reattaching is rather slow. It's faster to make a four band image where the first three bands are the scale factor, and the fourth band is a constant 1.

```python
alpha = image[3]
norm_alpha = alpha / 255
scale = n.bandjoin([n, n, 1])
image = image * scale
```

**Comment by jcupitt** [comment]
... also, I didn't realize you were working on paper. I have that on my ipad, the kids love it. Cool!

**Comment by gasi** [comment]
@jcupitt Thanks for the pointers. I will try installing nip2 and learn how to play around with your workspace. In case you didn’t see it, here’s how I resolved the issue in C: https://github.com/gasi/sharp/blob/18d434afb53dce22db6adf76329c7b316a8688ce/src/composite.c#L110-L169

> ... also, I didn't realize you were working on paper. I have that on my ipad, the kids love it. Cool!
That’s great! In fact, would you mind emailing me at daniel@fiftythree.com? We at FiftyThree would like to send you a token of appreciation for your work on VIPS and always being so supportive — VIPS plays an important role in the platform for our [Mix](https://mix.fiftythree.com/) community :)

**Comment by jcupitt** [comment]
I made an experimental branch with vips_premultiply() and vips_unpremultiply() operations:

https://github.com/jcupitt/libvips/tree/add-premultiply

So you can now write that bit of python as:

```python
image = Vips.Image.new_from_file(sys.argv[1])

image = image.premultiply()
image = image.resize(0.1)
image = image.unpremultiply()
 
image.write_to_file(sys.argv[2])
```

It roughly doubles the speed of shrinking, so that's nice. I'm not sure about the operation though, I'll tinker with it a bit.

**Comment by gasi** [comment]
Sweet, I’d love to leverage this natively in VIPS. We are currently still on 7.40.11, mostly because that’s the latest that the Heroku buildpack supports: https://github.com/alex88/heroku-buildpack-vips/commits/master

**Comment by gasi** [comment]
How hard would it be to backport this into an older version of VIPS?

**Comment by jcupitt** [comment]
Very easy, I'll let you know when it's done.

**Comment by lovell** [comment]
Thanks John, if you're happy adding this to the core of libvips itself then that's great news.

Once you're happy with the API, sharp can use a pre-processor conditional to take advantage of the new methods should they be available.

**Comment by jcupitt** [comment]
It seems OK to me now, you should be able merge the changes in this branch into 7.40, I think. 

https://github.com/jcupitt/libvips/tree/add-premultiply

I'll merge to master and get `vipsthumbnail` to use it.

**Comment by jcupitt** [comment]
git master `vipsthumbnail` now uses vips_premultiply(), here's the patch, might help show how to use it:

https://github.com/jcupitt/libvips/commit/25bf910f217380ab27e6dc83e1061005c359e277

**Comment by gasi** [comment]
This is great, thanks, John :bowtie:

**Comment by jcupitt** [comment]
OK, I'll close.
