### ISSUE TITLE
parsing 12bits of Tiff file

### ISSUE THREAD

**Issue by hksonngan** [jcupitt/libvips#292]
Here is the sample file: https://github.com/hksonngan/mosaic/blob/master/Data/AP_12bit.tiff
Actually I can use magick2vips but it return 16 bits.

**Comment by jcupitt** [comment]
I made a branch for adding this feature:

https://github.com/jcupitt/libvips/tree/nbit-tiff-reader

**Comment by jcupitt** [comment]
Actually, looking at the tiff spec, I'm not sure tiff really supports this:

http://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf

They talk about 8 and 4 bits per pixel, but not 12 or 14. Stackoverflow also doubts if this standard: 

http://stackoverflow.com/questions/7068183/writing-10-12-bit-tiff-files-with-libtiff-c

I had a quick hack and it sort-of works, but the bit order is not correct. It's not obvious what the correct bit order will be for things like 24 bits per pixel, nor what the scanline alignment rules will be, nor how fill order affects things. For example, can it be reversed?

I'm inclined to abandon this unless support is really vital.

**Comment by jcupitt** [comment]
I finished the branch and it seems to correctly decode all the test images I have. I'm not very confident it'll for for all n-bit images, so I'm inclined not to merge this. I'll leave the code around for reference.

**Comment by jcupitt** [comment]
I don't think it's possible to support this well, so I'll close.
