### ISSUE TITLE
support non-ascii characters in filenames on Windows (was: vipsthumbnail cyrillic (russian) output file name is corrupted)

### ISSUE THREAD

**Issue by shershenator** [jcupitt/libvips#294]
Am I missing something or cyrillic (russian) output file names not supported? They are corrupted, like "йцуке.jpg" -> "Р№С†СѓРєРµ.jpg" . I am trying the latest vipsthumbnail.exe . Thank you.

**Comment by jcupitt** [comment]
Hi, it's not been very well tested with non-C locales on Windows, there are obviously some problems. I'll have a look.

**Comment by jcupitt** [comment]
I checked on linux:

```bash
$ vipsthumbnail йцуке.jpg 
$ ls -l
total 60
-rw-rw-r-- 1 john john  2408 May 12 11:30 tn_йцуке.jpg
-rw------- 1 john john 54985 May 12 11:30 йцуке.jpg
```

and it's working there, so it seems to be just on Windows. 

On Windows, filenames are encoded in UTF-16, vips is all UTF-8. So I suppose there needs to be some translation between filename encoding and locale encoding whenever strings move backward or forward. Perhaps:

https://developer.gnome.org/glib/stable/glib-Character-Set-Conversion.html#g-filename-to-utf8

**Comment by shershenator** [comment]
Thank you for reply! It's been a long time since I saw console program that doesn't work correctly with non-english :) The interesting thing is that vips 'understand' russian input filename, but produces not correct output filename =| I have a quick look at the link you provided, but dont get how it can help me to use vips binaries with cyrrilic file name...

**Comment by jcupitt** [comment]
No problem, the link was a note for me :) 

I'll try to look into it.

**Comment by shershenator** [comment]
How's it going? any luck? ^_^

**Comment by jcupitt** [comment]
Hi again, I tried using wine on Linux, but it seems to handle filename encoding in a strange way, your `йцуке.jpg` example is already `?????.jpg` by the time `vipsthumbnail` sees it. I think I'd need a real Windows machine to implement this, but I don't have easy access to one, it's all Linux and OS X here.

They have a Windows machine down the hall, I'll see if I can borrow some time on it.

**Comment by shershenator** [comment]
Could you please find some time to fix it, i'll will greatly appreciate it! :)

**Comment by bgilbert** [comment]
There are at least two problems here:

- On Windows, `fopen()` [expects filenames in a legacy codepage](https://msdn.microsoft.com/en-us/library/yeby3zcb.aspx).  If you want to pass Unicode, you need to convert to UTF-16 and use `_wfopen()`; [here's how OpenSlide does it](https://github.com/openslide/openslide/blob/bbc8ae2757a0e62187a7f79e427445c960f35ff7/src/openslide-util.c#L165-L194).  Or, as I just discovered, you can use [`g_fopen()`](https://developer.gnome.org/glib/stable/glib-File-Utilities.html#g-fopen), which has [equivalent logic](https://github.com/GNOME/glib/blob/037719c27c541e5e529c7f0dc8a14792a26303c9/glib/gstdio.c#L713-L749).

- `main()` receives `argv` in a legacy codepage, and any unrepresentable characters are smashed to `?`.  You can declare [`wmain()`](https://msdn.microsoft.com/en-us/library/bky3b5dh.aspx) instead, which receives `argv` in UTF-16, but it's easier to just ignore `argv` and use [`g_win32_get_command_line()`](https://developer.gnome.org/glib/stable/glib-Windows-Compatibility-Functions.html#g-win32-get-command-line).

Note that the libtool wrapper program [also has the second problem](https://bugzilla.redhat.com/show_bug.cgi?id=1124436), so if you test the VIPS command-line tools directly from the build directory, you'll always see mangled filenames.

**Comment by bgilbert** [comment]
If VIPS and glib might use different libc's (which is possible on Windows), you shouldn't use `g_fopen()`.  (It could return a `FILE *` which VIPS' C library wouldn't be able to use.)

**Comment by jcupitt** [comment]
Well argh, Thank you for the tips @bgilbert.

I'll see if `g_win32_get_command_line()` will let me test under wine, that sounds like one of the problems I was seeing.

**Comment by jcupitt** [comment]
Just to confirm @bgilbert, `openslide_open()` expects a utf-8 string, is that correct?

**Comment by jcupitt** [comment]
Here's a branch for this issue:

https://github.com/jcupitt/libvips/tree/windows-unicode

Not quite there yet.

**Comment by jcupitt** [comment]
It seems to be half-working, at least under wine:

```
$ ~/GIT/build-win64/8.3/vips-dev-8.3/bin/vipsthumbnail.exe йцуке.jpg
$ ls tn_*
tn_йцуке.jpg
```

That's only with jpg images. All of the file format modules need checking for wchar support, I'll start reading them.

**Comment by bgilbert** [comment]
`openslide_open()` expects UTF-8 [only on Windows](https://github.com/openslide/openslide/commit/89bba00be872c27fdd1f7ef08a59e15546165c72#diff-69e37060289f754520bac929a6b2d9f8R65) (and only in Git master; older versions are broken).  On other platforms, any superset of ASCII should work, but I haven't actually tested that.

**Comment by sleman** [comment]
Not yet working for me on windows 7 using latest exe build for vipsthumbnail.exe. `VipsForeignLoad: file "..." not found

**Comment by jcupitt** [comment]
You have to build the `windows-unicode` branch from source at the moment. I'll upload a beta Windows build when I've done a few more formats.

**Comment by jcupitt** [comment]
It seems to be mostly done and working, at least under Wine. I've put up a test build here:

http://www.vips.ecs.soton.ac.uk/development/8.4/

That's an 'all' build, ie. it has all of the supported loaders built in, including a complete copy of imagemagick. Obviously not for production use. 

Working:

- All vips command-line programs now accept unicode arguments on Windows
- All vips calls to the host OS now translate to `wchar_t` on Windows 
- I've been though the file format support and fixed or verified jpeg, tiff, csv, vips, gif, openslide (needs git master openslide, I think), ppm, png, pdf, rad, svg, webp 

Not working:

- fits will not work -- they have no support for Windows unicode
- Matlab will not work -- again, no Windows unicode support
- OpenEXR will not build in mingw, so no Windows support there either
- ImageMagick looks like it should work, but does not, this would need investigating

To do:

- [ ] Error messages (for example, try to load a unicode file that does not exist) are printed to the console in utf8 and come out scrambled. I'm not sure what to do about this, fixing it seems complicated, for example: http://stackoverflow.com/questions/10882277/properly-print-utf8-characters-in-windows-console
- [ ] Add some tests for unicode filename handling on Windows

Any more testing would be great!

**Comment by jcupitt** [comment]
OK, all done and merged to master, this will be in 8.4.

**Comment by digital-flowers** [comment]
i did investigate ImageMagick it seems they have this issue and they fixed it starting from ImageMagick-7.0.3-1 see https://github.com/ImageMagick/ImageMagick/commit/7c63cd3c5cc38057bd777fba385c7cae647cf2b1 
but sadly ImageMagick 6.8.9 is the latest version works with libvips, so maybe i will try to fork it and just fix this issue until libvips support ImageMagick 7

**Comment by jcupitt** [comment]
libvips 8.4 has a new image magic loader which supports IM7, it should work. It is however horribly slow: IM7 uses double for all pixel values and it really crawls. More than twice as slow on

http://www.vips.ecs.soton.ac.uk/index.php?title=Speed_and_Memory_Use

**Comment by digital-flowers** [comment]
I see maybe i didn't set the dependencies correctly for ImageMagick 7 inside vips.modules

**Comment by jcupitt** [comment]
It should be automatic: just have IM7's `.pc` files first on `PKG_CONFIG_PATH` and you'll see this in libvips's `configure` output:

```
Magick package: 			MagickCore
file import with libMagick: 		yes (magick7)
```

**Comment by jcupitt** [comment]
I forgot to say, thanks for the news about IM7 fixing this issue.

**Comment by digital-flowers** [comment]
ok i will try again :)
