### ISSUE TITLE
JPEG 2000 processing

### ISSUE THREAD

**Issue by anuragji** [jcupitt/libvips#295]
Hello,

I am trying to create a DZI file from a JPG2000 file, but am getting the following error msg:

    vips dzsave JP2/PCA_BP_001_0001.jp2 DZI/PCA_BP_001_0001
    VipsForeignLoad: "JP2/PCA_BP_001_0001.jp2" is not a known file format`

I installed `vips-8.0.2` via Homebrew on OSX 10.10. I was under the impression that `vips` can handle JP2 files _out-of-the-box_.

Any ideas on how to remedy this?

**Comment by jcupitt** [comment]
Hi, vips reads jp2k via libMagick. You need to enable it, try:

```bash
brew install vips --with-imagemagick 
```

**Comment by anuragji** [comment]
Thanks! Do I need to install imagemagick with JP2 support or is that enabled by default?
