### ISSUE TITLE
Methods missing from Python

### ISSUE THREAD

**Issue by bobobo1618** [jcupitt/libvips#298]
On my Mac, the following code runs without issue:

```
from gi.repository import Vips
image = Vips.new_from_file_RW('test.jpg')
bw_image = image.sRGB2scRGB().scRGB2BW()
```

on my Fedora installation, I receive `AttributeError: 'Image' object has no attribute 'sRGB2scRGB'`.

I'm not sure what's going on here. I don't think it's a bug, just an issue with my build/installation.

I have two systems:
- A MacBook Pro running OS X 10.10 and Vips 8.0.2 installed from Homebrew: `brew install vips --with-webp --with-graphicsmagick --with-mozjpeg`
- A Fedora 21 system running Vips 8.0.2 built from source with the following `configure` output:

```
* build options
native win32:				no
native OS X:				no
open files in binary mode: 		no
enable debug:				no
build deprecated components:		yes
build docs with gtkdoc:			no
gobject introspection: 			yes
build vips7 Python binding:		yes
install vips8 Python overrides:		yes
  (requires pygobject-3.12.0 or later)

* optional dependencies
use fftw3 for FFT: 			no
Magick package: 			GraphicsMagick
file import with libMagick: 		yes
accelerate loops with orc: 		yes
  (requires orc-0.4.11 or later)
ICC profile support with lcms: 		yes (lcms2)
file import with OpenEXR: 		yes
file import with OpenSlide:		yes
  (requires openslide-3.3.0 or later)
file import with matio: 		yes
file import with cfitsio: 		yes
file import/export with libwebp:	yes
text rendering with pangoft2: 		yes
file import/export with libpng: 	yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
file import/export with libtiff:	yes (pkg-config libtiff-4)
file import/export with libjpeg:	yes
image pyramid export:			yes
  (requires libgsf-1 1.14.27 or later)
use libexif to load/save JPEG metadata: yes
```

I've also tried building from Git and swapping Magicks with no luck.

Just pressing Tab twice in ipython on my Mac results in a ton of other methods showing that are absent on Fedora. Am I missing something in my build?

**Comment by jcupitt** [comment]
Hi, it sounds like the overrides have not been installed on Fedora. 

The Python binding comes in two parts: first, there's a typelib that's generated from the vips sources which lists the main entry points and types. This is loaded by pygobject from your `GI_TYPELIB_PATH` when you `import Vips` and makes the base of the binding. 

There's also a large set of overrides called `Vips.py` which clean up this very basic binding and try to make it nice to use. These are loaded automatically by pygobject from the `gi/overrides` directory at the end of the  import. 

Unfortunately this overrides directory is part of pygobject, there is only one of them, and as var as I know there's no path or environment mechanism to let you add another. This means if you install vips to one prefix (eg. `/usr/local`) and use pygobject installed to another prefix (eg. the system one, `/usr`), the vips overrides will not be picked up.

The only (and very ugly) solution is to copy `Vips.py` to the system area. Try something like:

```bash
$ cd vips-8.x/python
$ sudo cp Vips.py /usr/lib/python2.7/dist-packages/gi/overrides
$ sudo cp Vips.py /usr/lib/python3/dist-packages/gi/overrides
```

You'll need to adjust the paths.

**Comment by bobobo1618** [comment]
Yup, that was the problem. It was installed to `/usr/lib/python2.7/site-packages/gi/overrides` but the actual directory being used, where the rest of the overrides (`GObject.py` is the one I searched for) are, was `/usr/lib64/python2.7/site-packages/gi/overrides`. 

Not sure why `lib64` is the standard, on most systems I see it being a straight symlink to `lib` but copying `Vips.py` there worked.

**Comment by jcupitt** [comment]
Oh,  weird. Glad it's working anyway.
