### ISSUE TITLE
Error while installing on Mac

### ISSUE THREAD

**Issue by alehano** [jcupitt/libvips#299]
```
brew install vips --without-fftw --without-libexif --without-libgsf \
>   --without-little-cms2 --without-orc --without-pango --without-pygobject3 \
>   --without-gobject-introspection --without-python
==> Installing vips from homebrew/homebrew-science
==> Downloading http://www.vips.ecs.soton.ac.uk/supported/8.0/vips-8.0.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/vips-8.0.2.tar.gz
==> ./configure --prefix=/usr/local/Cellar/vips/8.0.2
==> make check
============================================================================
make[3]: *** [test-suite.log] Error 1
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
couldn't understand kern.osversion `14.3.0'

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

```

**Comment by lovell** [comment]
Cross-posted at https://github.com/DAddYE/vips/issues/20

**Comment by interactionist** [comment]
Same here :(
```bash
bash-3.2$ brew install homebrew/science/vips --with-webp --with-graphicsmagick
==> Installing vips from homebrew/homebrew-science
==> Downloading http://www.vips.ecs.soton.ac.uk/supported/8.0/vips-8.0.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/vips-8.0.2.tar.gz
==> ./configure --prefix=/usr/local/Cellar/vips/8.0.2 --with-magick --with-magickpackage=GraphicsMagick
==> make check
============================================================================
make[3]: *** [test-suite.log] Error 1
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues
```

**Comment by jcupitt** [comment]
It's working here:

```bash
$ brew install homebrew/science/vips --with-webp --with-graphicsmagick
==> Installing vips from homebrew/homebrew-science
==> Installing homebrew/science/vips dependency: graphicsmagick
==> Downloading https://homebrew.bintray.com/bottles/graphicsmagick-1.3.21.yosem
######################################################################## 100.0%
==> Pouring graphicsmagick-1.3.21.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/graphicsmagick/1.3.21: 467 files, 13M
==> Installing homebrew/science/vips
==> Downloading http://www.vips.ecs.soton.ac.uk/supported/8.0/vips-8.0.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/vips-8.0.2.tar.gz
==> ./configure --prefix=/usr/local/Cellar/vips/8.0.2 --with-magick --with-magic
==> make check
==> make install
🍺  /usr/local/Cellar/vips/8.0.2: 183 files, 13M, built in 2.5 minutes
```

I'd guess it's probably an issue with your brew install. Have you tried looking through the troubleshooting guides? What does `brew doctor` output? The linked thread suggests `xcode-select --install`.

**Comment by interactionist** [comment]
@jcupitt 
```xcode-select --install ```:
 ```xcode-select: error: command line tools are already installed, use "Software Update" to install updates```

* * *
```brew doctor```:

```bash
Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.
You should probably `chown` them:

    /usr/local/share/man/man8

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
[…]
```

**Comment by jcupitt** [comment]
It sounds like your homebrew install is messed up. I think you must have done `./configure; make; sudo make install` at some point, and it's destroyed lots of stuff. I would wipe the whole of /usr/local and reinstall homebrew, it shouldn't take long.  

If you use homebrew, you can't install to `/usr/local` yourself, homebrew manages that part of the system. If you need to install something from source, either write a homebrew formula for it, or install to a different prefix with eg. `./configure --prefix=/Users/john/local` and then adjust your paths so your personal local is picked up.

**Comment by interactionist** [comment]
Hmm. Everything else is working fine. I never did ```/configure; make; sudo make install``` and I never directly installed stuff into /usr/local too – always used ```brew```.

I cannot wipe the whole ```/usr/local``` as I have other stuff installed there as well (npm, babel, node etc.)

**Comment by interactionist** [comment]
I debugged this further to update you:

```brew install vips --with-webp --with-graphicsmagick``` ==> fails
```brew install vips --with-graphicsmagick``` ==> fails
```brew install vips --with-webp``` ==> fails
```brew install vips``` ==> works

Not sure why the options throwing that error …

**Comment by jcupitt** [comment]
I don't think you're allowed to have anything else in `/usr/local` if you are using homebrew. You need to use their node, or install your node somewhere else (`/opt` ?). I would guess that one of these other packages is also installing a copy of one of the magicks to `/usr/local` and homebrew is becoming confused. 

It is curious that it's failing at `make test`. What do the logs say? Which tests are failing?
