### ISSUE TITLE
Possible memory leak with vips_jpegsave_buffer

### ISSUE THREAD

**Issue by arnecls** [jcupitt/libvips#301]
Hi there,
I'm currently writing a small Go binding for vips but I'm running into a memory problem.
The code looks fine to me, i.e. everything is deallocated by the methods found in the documentation / the 
libvips codebase.

The following code causes memory to steadily increase.
If I remove vips_jpegsave_buffer memory is stable again.

You might notice that pJpegBuffer is freed before return. I did this as a debugging help to make sure to avoid missing frees during the C/Go transition. The "production" code does of course not free the buffer prior to returning it but does so later in the code (after transitioning to Go).
Am I missing something here or is this a bug?

```
void* Resize(const char* a_pFile, int a_Width, int a_Height, int* a_pBufferSizeByte) {
    VipsImage* pImage = vips_image_new_from_file(a_pFile, NULL);
    if (!pImage) {
        return NULL;
    }
    double scaleX = (double)a_Width / vips_image_get_width(pImage);
    double scaleY = (double)a_Height / vips_image_get_height(pImage);
    double scale = (scaleX < 1.0 && scaleY < 1.0) ? MIN(scaleX,scaleY) : MAX(scaleX,scaleY);

    void *pJpegBuffer = NULL;
    VipsImage* pResized = NULL;
    VipsInterpolate* pInterpolate = vips_interpolate_new("bilinear");

    vips_resize(pImage, &pResized, scale, "interpolate", pInterpolate, NULL);
    VIPS_UNREF(pInterpolate);
    VIPS_UNREF(pImage);

    if (pResized != NULL) {
        size_t bufferSize = 0;
        vips_jpegsave_buffer(pResized, &pJpegBuffer, &bufferSize, NULL);
        //*a_pBufferSizeByte = (int)bufferSize;
        VIPS_UNREF(pResized);
        VIPS_FREE(pJpegBuffer)
    }
    return pJpegBuffer;
}
```

**Comment by arnecls** [comment]
*closed* Garbage collection totally explains this.
The returned buffer is copied to a heap allocated object in Go which is of course managed by the GC and stays in memory for some time until deallocated.

**Comment by jcupitt** [comment]
Glad it's working. There's a test suite in Python here:

https://github.com/jcupitt/libvips/tree/master/test

including tests of save to and load from buffer:

https://github.com/jcupitt/libvips/blob/master/test/test_foreign.py#L98

which passes and does not leak, so hopefully it should all be fine. Though it doesn't test all the save and load options.
