### ISSUE TITLE
HSV/HSL/HSB

### ISSUE THREAD

**Issue by Jondeen** [jcupitt/libvips#303]
Hi again,

I see there are no colourspaces defined for the HS*-formats. Are there any shortcuts to these formats I'm not aware of?

Thanks!

**Comment by jcupitt** [comment]
Hi, libvips is based on the CIE colourspaces, so LCh is roughly HSL. L is 0 - 100, C is about 0 - 100, h is 0 - 359 degrees. LCh is CIELAB with polar coordinates for a*, b*, is that's any clearer.

**Comment by Jondeen** [comment]
Thanks for hasty reply,

I'm dependent on compatibility with other colour conversion schemes in other systems, and as such I'm not sure if roughly "HSL" is sufficient -- it depends on what level of deviance you're implying...?

Would you be interrested in a patch for including an sRGB2HSV-conversion in colour.h et. al if I made one?

**Comment by jcupitt** [comment]
LCh is like a perceptually uniform HSV, or more uniform anyway, so it should do the same job, but much better. If you have parameters tuned for adjustments in HSV, they won't work directly in LCh, the ranges and the magnitudes will be wrong. 

I don't like HSV myself, it's mostly meaningless. RGB is very poorly defined (even sRGB has multiple slightly different versions) and HSV is even more poorly defined. Make an HSV adjustment on one RGB image and it can look different to the same adjustment on another image. Make an HSV adjustment in one piece of software on an image, make the same adjustment on the same image in another piece of software, it can look different. Adding HSV support would just encourage people to use it :-(  LCh has a very clear definition, as long as you can get into and out of the world of CIE colorimetry in a sane way. 

http://en.wikipedia.org/wiki/HSL_and_HSV#Disadvantages

_Now that users can choose colors visually, or choose colors related to other media (such as PANTONE), or use perceptually-based systems like L*u*v* and L*a*b*, HSB and HLS should be abandoned._

I agree it could be useful to have for compatibility. How about putting RGB<->HSV into a support library somewhere? I wonder if you could just glue some vips operations together and get something fast enough? What's the application you have in mind?

**Comment by Jondeen** [comment]
Thanks for clarifying,

You make a good point on discouraging use of HSV by omitting it -- however it could be convenient for compatibility as you say. That being said I should probably do something similar to my own systems - I haven't spent much time or thought with LCh, but will do so now ;-) 
The only reason I went into using HSV was due to its usability for segmenting specific colour profiles in some of my images, but LCh will most likely do the same job (better!).

I'm using the conversions for thresholding. Currently my process is pseudolike this:
```
RGB_Image->(LAB or HSV)
LAB[0] >= Lmin
LAB[1] >= Amin
LAB[2] >= Bmin
...etc
```

Currently I'm doing this in python.

**Comment by jcupitt** [comment]
Oh OK, if this is fresh code then LCh should perform much better. It's really good for segmentation.

Convert your sRGB to  LCh with `x = x.colourspace("lch")`, then to find pixels close to a certain hue do:

```python
mask = ((target_hue + threshold) % 360 - x[2]) % 360 < 2 * threshold
```

Erm, I've probably messed that up. Anyway, `x[2]` will get band 2, the hue. You probably need to exclude very dark pixels and pixels near the neutral axis as well, so something like:

```python
mask &= x[1] > 10 & x[0] > 10
```

**Comment by jcupitt** [comment]
... nip2 is useful for prototyping this kind of thing, you can just type that stuff ^^, adjust the parameters and see what pixels turn on and off. It uses `x?2` for band indexing.

**Comment by Jondeen** [comment]
Hi again :D
I've been looking into implementing the sRGB2HSV (for backwards compatibility), and get a `bad enum` error when adding the HSV enum to `image.h`:

```
...
	VIPS_INTERPRETATION_scRGB = 28,
	VIPS_INTERPRETATION_HSV = 29,
	VIPS_INTERPRETATION_LAST = 30
...
```
replaces

```
...
	VIPS_INTERPRETATION_scRGB = 28,
	VIPS_INTERPRETATION_LAST = 29
...
```

I'm assuming this arises from `image.c`:
```
		if( image->BandFmt < -1 || 
			image->BandFmt > VIPS_FORMAT_DPCOMPLEX ||
			(image->Coding != -1 &&
				image->Coding != VIPS_CODING_NONE && 
				image->Coding != VIPS_CODING_LABQ &&
				image->Coding != VIPS_CODING_RAD) ||
			image->Type > VIPS_INTERPRETATION_scRGB ||
			image->dtype > VIPS_IMAGE_PARTIAL || 
			image->dhint > VIPS_DEMAND_STYLE_ANY ) 
			vips_buf_appends( buf, "bad enum\n" );
```

Am I correct to assume that a more up-to-date implementation of this would be to swap the `scRGB`-line with the following?
```
image->Type >= VIPS_INTERPRETATION_LAST ||
```

**Comment by jcupitt** [comment]
Yes, that's a good idea.

I made you a branch with the boilerplate for HSV in:

https://github.com/jcupitt/libvips/tree/add-hsv

You need to fill in the implementations for HSV2sRGB and sRGB2HSV:

https://github.com/jcupitt/libvips/blob/add-hsv/libvips/colour/HSV2sRGB.c
https://github.com/jcupitt/libvips/blob/add-hsv/libvips/colour/sRGB2HSV.c

**Comment by Jondeen** [comment]
Awesome! Almost there...

Running into this upon saving an image converted to HSV:
```
VIPS:ERROR:header.c:523:vips_image_guess_interpretation: assertion failed: (0)
```

**Comment by jcupitt** [comment]
Ooop, good catch:

https://github.com/jcupitt/libvips/commit/c3ff482ed74e46dc82272f13c5bcb02921a424f4

let's remove the assert() as well, safer without that

**Comment by Jondeen** [comment]
No no it's fine -- it's from header.c, missing `VIPS_INTERPRETATION_HSV`:

```
	case VIPS_INTERPRETATION_XYZ: 
	case VIPS_INTERPRETATION_LAB: 
	case VIPS_INTERPRETATION_RGB: 
	case VIPS_INTERPRETATION_CMC: 
	case VIPS_INTERPRETATION_LCH: 
	case VIPS_INTERPRETATION_sRGB: 
	case VIPS_INTERPRETATION_scRGB: 
	case VIPS_INTERPRETATION_HSV:
	case VIPS_INTERPRETATION_YXY: 
		if( image->Bands < 3 )
			sane = FALSE;
		break;
```

**Comment by Jondeen** [comment]
Whoppa didn't see that patch.

...still I'm segfaulting from some glibstuff now on the save.

May be my setup, I'll get back to you.

```
Program received signal SIGSEGV, Segmentation fault.
g_slice_alloc (mem_size=16) at gslice.c:985
985       tmem = thread_memory_from_self ();
```

**Comment by jcupitt** [comment]
Maybe memory corruption? The add-hsv branch is working here:

```
$ vips colourspace k2.jpg x.v hsv
$ vipsheader x.v
x.v: 1450x2048 uchar, 3 bands, hsv, jpegload
``` 

Though of course it doesn't do anything.

**Comment by Jondeen** [comment]
Still looking into it. By using command line method you just stated I trace this through gdb:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b9b248 in vips_image_pipelinev (image=0x2f2a330, hint=VIPS_DEMAND_STYLE_THINSTRIP) at generate.c:405
405             for( i = 0; i < MAX_IMAGES &&
```
I'm guessing it is definitely something err-ing in my code, however saving the bands individually (through python interface) works fine. Saving partly and whole through another interpretation works fine.

**Comment by jcupitt** [comment]
Oh, strange. Do you have your stuff on github somewhere? I could try building here if you like.

**Comment by Jondeen** [comment]
https://github.com/Jondeen/libvips/tree/add-hsv

Haven't been C-ing for a while, but successfully tested a less optimized version here: https://github.com/Jondeen/libvips/tree/HSV

Not sure if I broke that build though.

**Comment by jcupitt** [comment]
Off to bed now, I'll try in the morning.

**Comment by Jondeen** [comment]
Awesome :+1: 

Thanks!

**Comment by Jondeen** [comment]
Update:
I replaced the conversion code of my initial (HSV-branch) implementation (in `LabQ2sRGB.c`) with the new algorithm, and it works as expected without any segfaults.

The initial structure was blindly copied off of `sRGB2scRGB` and its `vips_col_sRGB2HSV`, which, queerly, was situated in `LabQ2sRGB.c`. As far as I can tell, all other adaptations are similar to the the changes you made to the boilerplate branch, with the exception of small mods on cplusplus-files and POTFILES, whatever that is. Like I said it was a blind copy ;-)

The add-hsv branch was attempted with compilation on two different systems, alas with very similar setups. 

Attempting a last build on third independent system unless my head falls asleep.

**Comment by jcupitt** [comment]
I copy-pasted your srgb->hsv code from here:

https://github.com/Jondeen/libvips/blob/add-hsv/libvips/colour/sRGB2HSV.c

into my add-hsv branch, and it all seems to work:

https://github.com/jcupitt/libvips/commit/cda594d6454d45ad5761c0b2ee75294177b861e5

```
$ vips colourspace k2.jpg x.v hsv
$ nip2 x.v
```

If I check the pixels in x.v it looks reasonable.

I think you maybe don't have the best base class for your sRGB2HSV operator. You need to derive from `VipsColourCode` to get handling of casting and extra bands (like alpha). I think!

**Comment by jcupitt** [comment]
... `sRGB2scRGB` is quite a bit more complicated than you need. It has to handle 8- and 16-bit images (I guess 8-only is OK for HSV?), it has to have extra code for alpha channels, since scRGB is always 0-255 for alpha, and it has to build a large LUT to make linearization quick.

If you base off `Lab2LabS` you only need to handle three-band 8-bit data and the base class will handle alpha and bit depth conversion for you.

**Comment by Jondeen** [comment]
>I think you maybe don't have the best base class for your sRGB2HSV operator. You need to derive from VipsColourCode to get handling of casting and extra bands (like alpha). I think!

I'm not sure what you mean by this -- should there be any further changes to` sRGB2HSV.c`?

**Comment by Jondeen** [comment]
UPDATE:
Converting to VIPS file format succeeds, converting to JPEG fails:
```
12:59 $ vips colourspace testcols.jpg t.v hsv
memory: high-water mark 3.05 MB
✔ ~
12:59 $ vips colourspace testcols.jpg t.jpg hsv
Segmentation fault (core dumped)
✘-SEGV ~
```

**Comment by jcupitt** [comment]
Hey, getting close!

I think it's failing because jpg save is trying to convert to sRGB for save, but hsv->srgb is not there or not working yet.

Try:

```
vips colourspace testcols.jpg t.v hsv
vips colourspace t.v t2.v srgb
```

and see if you get sensible numbers in t2.v.

**Comment by Jondeen** [comment]
Oh of course.

But how are those two lines different from the one-liner?

Oh and shouldn't a dummy-HSV2sRGB be present in the boilerplate?

**Comment by Jondeen** [comment]
From HSV2sRGB.c - I wonder if there is a mixup of interpretations in the init function. In transit atm, will double check when in at work.

**Comment by jcupitt** [comment]
Yes, that was it, with this patch:

https://github.com/jcupitt/libvips/commit/5e9edbd6d51f2d34055870ee87716917511b8658

the segv is gone fopr me in the `add-hsv` branch.

**Comment by Jondeen** [comment]
Ahh... Awesome. It works here too.

I'll make a pull-request when I've got HSV2sRGB inplace, and I still need to double check boundaries of the sRGB2HSV.

Thanks for patience and guidance.

**Comment by Jondeen** [comment]
By the way, the line you mention above should have some parenthesis. 
>mask &= x[1] > 10 & x[0] > 10

Like this:
`mask &= (x[1] > 10) & (x[0] > 10`)

Just in case any one else attempts the same --- it makes a big difference! I just did the same mistake on my own and it bit me in a bad place.

**Comment by jcupitt** [comment]
Ooops, good point.

**Comment by jcupitt** [comment]
I think this is all done, I'll close. Thanks for the code!
