### ISSUE TITLE
Problem with vips/intl.h include

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#304]
When compiling my user code that uses both LibVIPS and gettext, I am obliged to explicitly define *ENABLE_NLS*, otherwise I get compilation errors. 

Are vips__gettext() and vips__ngettext() supposed to replace the standard gettext() and ngettext() functions in user code? Or should vips/intl.h be moved to an "internal" header, which is not included via vips/vips.h?

**Comment by jcupitt** [comment]
Hiya, yes, I believe you are supposed to define ENABLE_NLS if you use gettext. I've not checked for years though, is that no longer the case?

The `vips/intl.h` header should only be included by vips code, not by user code, so yes, you can have your own gettext macros.

**Comment by aferrero2707** [comment]
Hi! Thanks for the clarifications, I've fixed my code and now all compiles fine.
