### ISSUE TITLE
bootstrap.sh script and ltmain.sh

### ISSUE THREAD

**Issue by Jondeen** [jcupitt/libvips#305]
Hi again,

I'm been trying ot set up a pipeline for running tests off-server to ease bugtracking, and following steps provided in #48 for a make dist I continue to run into a missing `ltmain.sh` on one of my dev servers. Looking into `bootstrap.sh` I find that the script cleans up the directory, including removing any `ltmain.sh` files it finds.

Running `./bootstrap.sh` on a recently checked out git:
```
$ ./bootstrap.sh
testing for glibtoolize ...
using libtoolize
configure.ac:123: installing `./config.guess'
configure.ac:123: installing `./config.sub'
configure.ac:13: installing `./install-sh'
configure.ac:330: required file `./ltmain.sh' not found
configure.ac:13: installing `./missing'
cplusplus/Makefile.am: installing `./depcomp'
python/Makefile.am:2: installing `./py-compile'

$ ./configure --enable-gtk-doc=yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
[...]
checking for headers required to compile python extensions... found
configure: creating ./config.status
config.status: creating vips.pc
config.status: creating vipsCC.pc
config.status: creating vips-cpp.pc
config.status: error: cannot find input file: `Makefile.in'
```

By running `aclocal` and `libtoolize` in advance I get same results, since `./bootstrap.sh` removes the `ltmain.sh` provided by `libtoolize`.

Further, by removing the `ltmain.sh` from initial cleanup section of `./bootstrap.sh` I am successfully able to build.

```
$ aclocal
$ libtoolize
libtoolize: putting auxiliary files in `.'.
libtoolize: linking file `./ltmain.sh'
libtoolize: `AC_PROG_RANLIB' is rendered obsolete by `LT_INIT'

$ ./bootstrap.sh
testing for glibtoolize ...
using libtoolize
configure.ac:123: installing `./config.guess'
configure.ac:123: installing `./config.sub'
configure.ac:13: installing `./install-sh'
configure.ac:13: installing `./missing'
cplusplus/Makefile.am: installing `./depcomp'
```

It may be that this is caused by a flaw on my build system, however I have not seen this problem on other builds.

**Comment by jcupitt** [comment]
Strange, bootstrap runs libtoolize near the end, it should regenerate the ltmain.sh for you. It does:

```
aclocal
autoconf
autoheader
$LIBTOOLIZE --copy --force --automake
automake --add-missing --copy
```

**Comment by Jondeen** [comment]
If I exit the `bootstrap.sh` script after...
```
$LIBTOOLIZE --copy --force --automake
```
... then the ltmain.sh is missing.

**Comment by Jondeen** [comment]
Versions:
```
aclocal (GNU automake) 1.11.6
autoconf (GNU Autoconf) 2.69
autoheader (GNU Autoconf) 2.69
libtoolize (GNU libtool) 2.4.2
automake (GNU automake) 1.11.6
```

**Comment by jcupitt** [comment]
Very mysterious! I see:

```
john@kiwi:~/GIT/libvips (master)$ rm ltmain.sh 
john@kiwi:~/GIT/libvips (master)$ libtoolize --copy --force --automake
john@kiwi:~/GIT/libvips (master)$ ls ltmain.sh 
ltmain.sh
john@kiwi:~/GIT/libvips (master)$ libtoolize --version
libtoolize (GNU libtool) 2.4.2
Written by Gary V. Vaughan <gary@gnu.org>, 2003
```

**Comment by Jondeen** [comment]
Ok...

What actually fixed it was the `automake --add-missing` in advance of libtoolize. I have no clue why, but it leaves instructions for libtoolize to link ltmain.sh.

I'm not familiar with the autofamily. Maybe you have some ideas...?

**Comment by jcupitt** [comment]
I tried swapping the libtool and automake lines in my bootstrap, but then I started getting the `ltmain.sh` errors myself. I wiped my libvips area and cloned from git again and it ran cleanly. 

I think I can only chalk this up to some madness in some autotools installations. I'll tag as baffling and close, if anyone has any good ideas, please reopen.
