### ISSUE TITLE
VIPS can't find libgsf-1-114 on Ubuntu

### ISSUE THREAD

**Issue by prohtex** [jcupitt/libvips#306]
I'm trying to build VIPS 8.0.2 from source on Ubuntu trusty 14.04.

./configure reports:

image pyramid export:			no
  (requires libgsf-1 1.14.27 or later)

but libgsf-1-114 is installed and is the correct version:

dpkg -s libgsf-1-114
Package: libgsf-1-114
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 321
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: libgsf
Version: 1.14.27-2ubuntu2

How do I point to the installed package?
Thanks!

**Comment by jcupitt** [comment]
Hi, you need the -dev version of the package to build code that uses it:

```
$ dpkg-query -l "libgsf*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  libgsf-1       <none>       <none>       (no description available)
ii  libgsf-1-114   1.14.30-2    amd64        Structured File Library - runtime
ii  libgsf-1-commo 1.14.30-2    all          Structured File Library - common 
ii  libgsf-1-dev   1.14.30-2    amd64        Structured File Library - develop
un  libgsf-gnome-1 <none>       <none>       (no description available)
```

vips uses `pkg-config` to find packages, so this command needs to work:

```
$ pkg-config libgsf-1 --modversion
1.14.33
```

**Comment by prohtex** [comment]
Hey Thanks! I got 8 compiled and I'm seeing much better image quality in vipsthumbnail when scaling down large images.

**Comment by jcupitt** [comment]
Yes, the resize algorithm was improved in 7.42, it's now lanczos2, the same as imagemagick's default.
