### ISSUE TITLE
Best class to base a point-in-polygon binary operator on

### ISSUE THREAD

**Issue by Jondeen** [jcupitt/libvips#308]
I'm looking to make a computationally cheaper method of isolating specific regions based on a ROI of either arbitrary coordinates or SVG origin, than the previously discussed draw_line + fill + AND.

If there are other options I've missed I'd be glad to hear of them, but the method I used (as above) cost me nearly 12G of memory which is not viable on my systems.

I'm thinking the easiest would be to simply use a polygon described by a list of coordinates and using a line trace algorithm for each individual line, performing either a boolean or blanking operation as it passes.

I'd be happy to draft something up, if only for my own usage, if you could give me a tip on which class I could use as a basis for writing it.

**Comment by jcupitt** [comment]
Hi again, did you try the nip2 thing for doing this?

* Load an image, it can be any size at all, I tried with a 100,000 x 100,000 NDPI slide.
* Open a view window and zoom out so you can see the whole thing.
* Ctrl-click a series of points in the view window, perhaps five or six.
* Back in the main nip2 window, click on the first point (A2 I guess?), shift-click on the last, and select Edit / Group.
* In Toolkits, select Image / Select / Polygon.
* Open a view window for the result and it should just be the poly you marked.
* Try dragging some of the marks on your original image around, it should all update smoothly.

That's done with a straight implementation of the winding rule for the points you selected. It won't work well for very large numbers of points, but it's fine for up to 20 or so on my laptop, and doesn't use any memory. You could probably make it quite a bit quicker with a little Python programming. 

Previous discussion for reference: https://github.com/jcupitt/libvips/issues/275

**Comment by jcupitt** [comment]
If you've got too many points for the nip2 thing to be practical, a special operator might be the best thing.

`buildlut` takes a large array and makes a 1D lookup table. `zone` makes a 2D image. Maybe combine those two somehow?

**Comment by Jondeen** [comment]
Ahhh I've really underestimated the power of the Nip!

Still not sure how to map an equivalent method to the python interface though. Are there specific methods to iterate rows?

Otherwise I'll look into extrapolating what I see in the buildlut-class, if nothing else for my own education of the vips internals!

Thanks for awesome pointers.

**Comment by jcupitt** [comment]
You don't need to iterate: it does it for you. You just type in the standard equations and it runs them for all x/y. You split the poly into a set of line segments, then for each straight line test if a point is above or below the line. Then combine all the tests using the winding rule to make an ROI.

https://en.wikipedia.org/wiki/Point_in_polygon

**Comment by Jondeen** [comment]
>You just type in the standard equations

I've worked with booleans operations before, but never referenced x/y pixel positions in python. I may be a bit slow, but how do I make an evaluation based on pixel positions? Is it documented somewhere -- maybe I missed it?

**Comment by Jondeen** [comment]
(***Thanks for patience***)

**Comment by jcupitt** [comment]
Sorry, I'm not being very clear. Use vips_xyz() to make an image where pixel values are equal to coordinates:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-create.html#vips-xyz

It can make up to 5D images, but defaults to 2D. Then just run arithmetic operations on that, for example:

```python
from gi.repository import Vips
x = Vips.Image.xyz(100, 100)
x -= [50, 50]
y = (x[0] ** 2 + x[1] ** 2) ** 0.5 < 25
y.write_to_file("y.jpg")
```

So that makes a 100 x 100 pixel two-band image where the first band has the x coordinate of the pixel and the second band has the y coordinate. It has (0, 0) at the top-left, so subtracting 50 from each channel moves the origin to the centre. You could just do `x -= 50` of course, but it seems clearer to have the coordinates as a pair. You can use `x[0]` to pull out band 0, then `y` is obviously a circle of radius 25. Finally, `y.jpg` is a one-band black image with a white circle at the centre. 

In just the same way, you can draw any poly by ANDing together a set of above-or-below-the-line tests, this is what nip2 is doing.

**Comment by Jondeen** [comment]
Wow, I keep getting stunned by the eloquence of the Vips <-> Python implementations.

Thanks for taking the time to explain, much more than much appreciated!

**Comment by jcupitt** [comment]
Don't be too impressed, it's a standard way to do this kind of thing :-( 

It does scale nicely in libvips, which is cool. Most systems only let you do this for rather small images.

**Comment by Jondeen** [comment]
> ~~it's a~~ ***it SHOULD be a*** standard way to do this kind of thing

Regardless, it's a good piece of library.

I've been looking into the winding number algorithms, and found they're tough to implement without delegating a signed array for counting the turns. Is that how it is done in nip2?

By doing a simpler approach, using crossing numbers I find it should be possible to do the following, since one only need to keep track if the current number is odd or even.

I've tried to set up my code as this (or see http://stackoverflow.com/questions/30965559/crossing-number-winding-number-polygon-test-expressed-as-binary-python):

```.py
#Original points:
pts=[[100,100],[200,200],[300,100],[400,300],[300,400],[200,300],[100,100]]

#Extremas:
min=[pts[0][0],pts[0][1]]
max=[pts[0][0],pts[0][1]]
for i in pts:
  for j in range(2):
    if i[j]<min[j]:
      min[j]=i[j]
    if i[j]>max[j]:
      max[j]=i[j]

#New dimensions:
w=max[0]-min[0]
h=max[1]-min[1]
if len(sys.argv) > 2:
  xyz=[int(sys.argv[1]),int(sys.argv[2])]
else:
  xyz=[200,100]

#Normalize by cutting off lower than minimum, higher than maximum:
for i,p in enumerate(pts):
  pts[i]=[p[0]-min[0],p[1]-min[1]]
x=0
y=1
logic=None
counting=0
for i in range(len(pts)-1):
  test=(  ( (pts[i][y] <= xyz[y]) and (pts[i+1][y] > xyz[y]) ) or \
           ( (pts[i][y] > xyz[y]) and (pts[i+1][y] <= xyz[y]) ) ) and \
             (xyz[x] < pts[i][x] + ( (xyz[y]-pts[i][y])/(pts[i+1][y]-pts[i][y]) ) * (pts[i+1][x] - pts[i][x]))
  if logic is None:
    logic=test
  else:
    logic^=test
  if test:
    counting+=1
``` 

Unfortunately, it yields some buggy results (one image from each iteration below).
I'll figure it out sooner or later, but if you have some quick instinctual thoughts on fixes here, I'd appreciate it massively.

BTW, my collated code for web-interfaced microscope slide analysis will be pushed to the Gits towards this fall. I hope by then it will be something of value to other people as well.

![image](https://cloud.githubusercontent.com/assets/763025/8282919/2e674932-18f4-11e5-9fc5-bed0b013dc24.png)

**Comment by Jondeen** [comment]
Update!

`&`!==`and` and `|`!==`or`.

**Comment by jcupitt** [comment]
Do you have a complete test program you can post? Make a gist with the code in.

**Comment by Jondeen** [comment]
Yes I've been planning to upload it, however need to clean up my hacked and slashed code first :D

**Comment by jcupitt** [comment]
This has mostly moved to #310, I'll close.
