### ISSUE TITLE
Massive TIFF deep zoom is rendered entirely black.

### ISSUE THREAD

**Issue by Aaron-Pool** [jcupitt/libvips#309]
Hey there, I'm trying to use vips to create deep zoom pyramids of massive TIFFS (Roughly a Gig in size). Unfortunately, when I try to create the pyramids using the command:

```vips dzsave IMG_NAME.TIF temp2 --tile-size 256 --overlap 0 --vips-progress --vips-leak --layout zoomify --suffix .jpg[Q=90]```

I get a few vips warning about "TIFFReadDirectory: Unknown Field" (which I'm pretty sure isn't a big deal), and it runs in about 45 seconds. Unfortunately, every single tile is rendered black. Any ideas?

**Comment by jcupitt** [comment]
Hiya, I'd try with a small tiff RGB and check that it works correctly on that, then try to see what''s strange about the huge one. Could it be RGBA, or CMYK , or compressed with a non-standard codec?

`tiffinfo` is a great tool for checking for strange tiff format issues.

**Comment by Aaron-Pool** [comment]
Thanks! Appreciate the quick response.

**Comment by jcupitt** [comment]
Hi, did you get anywhere with this? If you can upload a tiff that fails somewhere I'll have a look.

**Comment by Aaron-Pool** [comment]
Hey John,

Sorry for the lack of response. Shortly after posting this, my higher ups told me I was required to use GDAL for the project we were working on. Unfortunately, it wasn't my choice. In any case, I didn't have time  to pursue the issue further.

**Comment by jcupitt** [comment]
Ah shame. I'll close then.
