### ISSUE TITLE
Can't convert some TIFF files to JPEG

### ISSUE THREAD

**Issue by peacemaker17** [jcupitt/libvips#311]
When I try to convert the below TIFF file to JPEG I receive an empty file in the output directory with zero file length:

I use the next command:
vips.exe im_shrink "d:\Daminion User Files\bier.tif" "d:\Daminion User Files\bear_thumb.jpg" 1 1

The warning is displayed then:
"vips warning: TIFFReadDirectory: Unknown field with tag 37724 (0x935c) encountered
VipsJpeg: Bogus marker length"

Tested with 7.42 and 8.01 versions.

**Comment by jcupitt** [comment]
Hi @peacemaker17, I had a look, the problem is the XMP data on that image. It has over a megabyte of XMP, and the vips JPEG writer does not handle XMP over 64kb. I had no idea XMP could get that large.

I'll get the jpeg writer to output multiple 64kb XMP chunks, just as it does for large ICC profiles. 

As a workaround, if will function if you delete the XMP metadata. For example:

```
$ vipsthumbnail bier.tif -o %s.jpg[strip]
```

**Comment by peacemaker17** [comment]
Unfortunately this file came from a Daminion user, so I can't recommend him to delete this. I'll wait for an update. Thank you, John!

**Comment by jcupitt** [comment]
It doesn't delete the XMP from the source file, it just stops it being written to the thumbnail. You probably don't want this huge XMP block in the thumbnail anyway, plus it'll make the thumbnail a LOT smaller. 

Try the `vipsthumbnail` command above ^^ it should work.

**Comment by peacemaker17** [comment]
I had some issues with using vipsthumbnail in the past (some files weren't properly rendered). So can I use the Strip argument with vips.exe?

**Comment by jcupitt** [comment]
It's more complicated. Your TIFF file is CMYK, so at the command line you'd need to do something like:

```
vips icc_transform bier.tif tempfile.v /path/to/srgb/profile.icm --embedded
vips shrink tempfile.v thumb.jpg[strip]
```

ie. transform to srgb first, then shrink. `vipsthumbnail` does this for you automatically and without needing a temporary file.

I'd try `vipsthumbnail` again. Do you have the files that were failing? I don't know of any bugs, but if it's not working, I'll try to fix it.

**Comment by jcupitt** [comment]
Actually, thinking about it, you should swap those two commands. It would be better to shrink before converting to srgb.

Also, don't use `im_shrink`, that's the old vips7 interface. Use plain `shrink` instead. This uses the vips8 API and you get things like automatic streaming. It should be noticeably quicker. 

`vipsthumbnail` uses a much better downsizing algorithm than plain `shrink`, so you should really use that if you can.

**Comment by peacemaker17** [comment]
John, I appreciated your assistance and for the new VIPS 8 version. I am using vipsthumbnail now according to your advice and it works like a charm. Tested with about 70 TIFFs received from a lot of Daminion users (some of them are up to 700 MB). So far so good!

Thanks a lot!

**Comment by jcupitt** [comment]
Hey, glad it's working! If you find any files it breaks with, please let me know and I'll fix it.

You should see a nice improvement in quality too. I'll close if this is done.

**Comment by jcupitt** [comment]
Oh, wait, I'll fix that oversize XMP problem, I forgot about that.

**Comment by jcupitt** [comment]
After some digging it seems that every large object type has picked a different way to encode itself as multiple jpeg markers, it's not possible to write a generic "write a large object to jpg" routine.

I've changed the jpg writer to warn and ignore large objects:

```
$ vips copy chicken-legs.tif x.jpg
vips warning: VipsJpeg: field "xmp-data" is too large for a single JPEG marker, ignoring
```

which is better than not working at all. To write large XMP it seems you need to parse the whole XMP object, pull out the most important fields, code just them into the main XMP block, then write any remaining XMP objects into a set of extended XMP markers. Nuts to that!

http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/xmp/pdfs/XMPSpecificationPart3.pdf
