### ISSUE TITLE
Replace existing (older) files with dzsave

### ISSUE THREAD

**Issue by Bragolgirith** [jcupitt/libvips#312]
I'm creating tiles for a high-res image using dzsave like this:

    vips dzsave test.png test
This works just fine.

However if I were to run the same command again, it now throws the following error:

    VipsRegion: valid clipped to nothing
    rename: unable to rename file ".\test-KNJ70X/test_files" as "./test_files", Permission denied

Is there currently a way to circumvent this?

I understand that from a developer's perspective this is all logical and due to the fact that the old `"./test_files"` folder still exists and can't be overwritten. 
I would however argue that from a user's perspective the current behaviour - leaving both the old folder AND the temporary folder with a random name - is not helpful in any way. 

Since the typical use-case for that scenario is the user trying to update an image, the default behavior should be to force-overwrite the old content. (alternatively there could be an optional cli paramater for this). 
That change will make it a lot easier to run update scripts on a large number of images, without the need to clean up first.

I'm running a Windows 7 system with the 8.0.0 version of vips. 

P.S. Does anyone know whether the same happens on UNIX?

**Comment by jcupitt** [comment]
Hi @Bragolgirith 

This is fiddly to fix: for various reasons, dzsave has to write to a temporary directory first and then rename to the final name. If there is already a directory of that name, you can't do a simple rename, you'd need to do some kind of intelligent merge, perhaps comparing file sizes or dates, and removing files which should no longer exist. It just doesn't seem like a good idea to build all of that into dzsave.

I agree the current behaviour is not great. We could add a check early on that the final directory name is available, at least then it would stop early and with a useful error message.

Have you tried zip output, by the way? It should be quite a bit faster on Windows than building a directory tree. Something like:

```
vips dzsave test.png test.zip
```

Plus once it's built, it's much easier to copy around, of course. 

Yes, you get the same irritating behaviour on linux:

```
$ vips dzsave k2.jpg x
$ vips dzsave k2.jpg x
rename: unable to rename file "./x-LJXB1X/x_files" as "./x_files", Directory not empty
```

**Comment by jcupitt** [comment]
I changed it to stop earlier. I now see:

```
$ vips dzsave k2.jpg x
$ vips dzsave k2.jpg x
dzsave: output directory ./x_files exists
```

And you don't get the `x-7645` temporary directory.

**Comment by Bragolgirith** [comment]
Hello @jcupitt,

Great - not leaving unwanted artifacts is definitely a better way to handle this. 

And just as an idea - we currently have a simple solution in place where we check if a folder with the same name exists, in which case we first delete it and _then_ rename the temp folder. 
This spares us from having to performing an intelligent merge (although maybe at a higher performance cost in certain cases). 

There's the possible side effect where an important folder could get deleted if we use an unfortunate name, which is a good argument why this should be an optional flag and not the default implementation - but the same thing happens if we use the zip output anyway - the .zip file gets overwritten without as much as a word - so at least it will be consistent between implementations. :)

**Comment by jcupitt** [comment]
Yes, exactly, having folder delete inside libvips would make me very nervous. If our caller is doing this, at least it's their fault if something goes wrong. 

I'll close if you're OK with this. libvips 8.1 will have the new code.

**Comment by Bragolgirith** [comment]
That makes perfect sense - and thank you for the swift replies!

**Comment by HackerMD** [comment]
I just ran into a problem that seems to be related to this issue.

I'm using Vips `8.1` installed from source (git) on a SLURM cluster with NFS v4.

The following code creates a little test pyramid:

```python
import os
from gi.repository import Vips
import tempfile

output_dir = os.path.join(tempfile.gettempdir(), 'test_pyramid')

if not os.path.exists(output_dir):
    os.mkdir(output_dir)

img = Vips.Image.new_from_array([[1, 2, 3], [1, 2, 3]])
img.dzsave(output_dir, layout='zoomify', suffix='.jpg[Q=100]')
```

It works fine on my local machine, but breaks when I run it on the cluster node, where I get the following error message:

```python
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-8-41c94a798966> in <module>()
----> 1 img.dzsave(output_dir, layout='zoomify', suffix='.jpg[Q=100]')

/usr/lib/python2.7/dist-packages/gi/overrides/Vips.py in call_function(*args, **kwargs)
    610         @add_doc(generate_docstring(name))
    611         def call_function(*args, **kwargs):
--> 612             return _call_instance(self, name, args, kwargs)
    613 
    614         return call_function

/usr/lib/python2.7/dist-packages/gi/overrides/Vips.py in _call_instance(self, name, args, kwargs)
    390 # here from getattr ... try to run the attr as a method
    391 def _call_instance(self, name, args, kwargs):
--> 392     return _call_base(name, args, kwargs, self)
    393 
    394 @classmethod

/usr/lib/python2.7/dist-packages/gi/overrides/Vips.py in _call_base(name, required, optional, self, option_string)
    340     logger.debug('_call_base got op2 %s' % op2)
    341     if op2 == None:
--> 342         raise Error('Error calling operator %s.' % name)
    343 
    344     # rescan args if op2 is different from op

Error: Error calling operator dzsave.
  glib: /tmp/test_pyramid: File exists
```

Do you have any idea of what might cause this error?

**Comment by jcupitt** [comment]
Hi again, yes, `dzsave` likes to create the output directory itself. Make sure `/tmp/test_pyramid` is removed, not created, before calling it.

**Comment by HackerMD** [comment]
Indeed!

```
import os
from gi.repository import Vips
import tempfile
import shutil

output_dir = os.path.join(tempfile.gettempdir(), 'test_pyramid')

if os.path.exists(output_dir):
    shutil.rmtree(output_dir)

img = Vips.Image.new_from_array([[1, 2, 3], [1, 2, 3]])
img.dzsave(output_dir, layout='zoomify', suffix='.jpg[Q=100]')
```

solves the problem. Weird that it worked locally with the directory present.

Anyways.. Thank you for your great support! I really appreciate it!

Vips is awesome!!

**Comment by jcupitt** [comment]
Glad it's working!
