### ISSUE TITLE
Virus alert by Avast for iconv.dll

### ISSUE THREAD

**Issue by peacemaker17** [jcupitt/libvips#314]
Avast displays a virus alert for iconv.dll from latest VIPS 8.01 package:
https://www.virustotal.com/ru/file/d8209c02adcceef30f4e26c54f6631db951dd048b22fb8aaf023346aabbda5a1/analysis/

**Comment by jcupitt** [comment]
Oh dear, that's bad, I'll investigate. Hopefully just a false positive.

**Comment by jcupitt** [comment]
Yes, I think it's a false positive, my `iconv.dll` is just the standard GNOME one stripped. I see this:

```
$ wget http://www.vips.ecs.soton.ac.uk/supported/8.0/win32/vips-dev-8.0.2.zip
... download trimmed
$ unzip -qq vips-dev-8.0.2.zip 
$ md5sum vips-dev-8.0.2/bin/iconv.dll
dffdbb0755530bc6fcfa98801cace1ca  vips-dev-8.0.2/bin/iconv.dll
```

If I compare to the GNOME iconv:

```
$ wget ftp://ftp.gnome.org/pub/GNOME/binaries/win32/dependencies/win-iconv-dll_tml-20100912_win32.zip
$ unzip -qq win-iconv-dll_tml-20100912_win32.zip
$ strip --strip-unneeded bin/iconv.dll 
$ md5sum bin/iconv.dll 
dffdbb0755530bc6fcfa98801cace1ca  bin/iconv.dll
```

So I don't think the vips download has been poisoned. Thank you very much for reporting this though, it's very important to keep a close eye on things like this.

**Comment by peacemaker17** [comment]
Ok. I've sent the request to Avast to about this wrong alarm.

**Comment by peacemaker17** [comment]
Avast team reported that they fixed this issue with the wrong alert:
https://www.virustotal.com/ru/file/d8209c02adcceef30f4e26c54f6631db951dd048b22fb8aaf023346aabbda5a1/analysis/1437578226/

**Comment by jcupitt** [comment]
Hey, great! It's nice they are so responsive. I'll close this issue, and thanks for reporting and fixing it.
