### ISSUE TITLE
vipsthumbnail auto-rotation

### ISSUE THREAD

**Issue by andrewgleave** [jcupitt/libvips#319]
I'm attempting to use vipsthumbnail to generate sets of thumbnails from some source jpgs that have EXIF orientation metadata. Some crop and resize fine, others don't. Here's an example of the arguments and source I'm using. 

```
vipsthumbnail -t -s 170x96 -c img.jpg -o "out.jpg[Q=80,optimize_coding,strip]"

```
I can't tell if I'm missing something or not. Could it be related to #243 ?

**Edit**: *Strange, the image appears flipped inline in this issue, but when opened as its own image, is the correct way around...*

![img](https://cloud.githubusercontent.com/assets/100615/8942048/566eeba4-356b-11e5-9e25-9b364dfaff95.jpg)

**Comment by jcupitt** [comment]
Hi @andrewgleave, it seems to be working for me. If I look at your source image in nip2 (which does not autorotate, it shows exactly the pixels stored in the file) it appears to be upside down. If I look at the header, I see:

```bash
$ vipsheader -a orientation-test2.jpg | grep -i orienmemory: high-water mark 0 bytes
exif-ifd0-Orientation: 3 (Bottom-right, Short, 1 components, 2 bytes)
```

If I thumbnail it, I see:

```bash
$ vipsthumbnail -t -s 170x96 -c orientation-test2.jpg -o "out.jpg[Q=80,optimize_coding,strip]"
$ vipsheader -a out.jpg | grep -i orien
$ 
```

ie. the `Orientation` tag has been removed. If I look at `out.jpg` in nip2, it is the correct way up, ie. it has been rotated.

**Comment by andrewgleave** [comment]
Hmm, ok. Thanks for investigating. It appears to be down to the viewer doing some autorotation when viewed in different viewers: webkit inlined image does not take the exif in to account and shows it upside down, opening the image directly show it correctly.

Just so I can get this straight: the autorotation feature does not rotate the source image to the orientation defined in the metadata before performing further conversion? If not, do you have any suggestion as to how I can ensure the image is correctly orientated before passing it to vipsthumbnail?

Thanks for your help

**Comment by jcupitt** [comment]
`vipsthumbnail` autorotate really does rotate the image. It looks at the EXIF and, if there's an `Orientation` tag, it flips the image as instructed. It then removes that tag from the header. 

Yes, inline images in browsers don't autorotate. The reason is that autorotate could change the width and height if it's a 90 degree rotate, and that could break page layout.

**Comment by andrewgleave** [comment]
Apologies, I've now discovered why I wasn't getting the same results as you.

Vips had been built with ```--no-libexif```

**Comment by jcupitt** [comment]
Ah that would explain it, I hadn't thought of that. 

`vipsthumbnail` should probably warn if you use the `rotate` flag and there's no EXIF support. I'll make this into an enhancement.

**Comment by jcupitt** [comment]
I added a warning to vipsthumbnail for this case. Thanks for pointing this out.
