### ISSUE TITLE
Add option to not build docs

### ISSUE THREAD

**Issue by irnnr** [jcupitt/libvips#320]
We're trying to build vips on Travis as part of our build process. Unfortunately ATM package gtk-doc-tools cannot be used with Travis' container infrastructure as it is not white listed yet. (I have created [an issue](https://github.com/travis-ci/apt-package-whitelist/issues/764) on their end to get it in).

As an alternative approach, would it be possible/make sense to add an option for `bootstrap.sh` to not call `gtkdocize`? I'm not sure whether gtk-doc-tools might be needed in later places.

**Comment by jcupitt** [comment]
Unfortunately you have to have gtkdoc to make the build system, there's no way around it (as far as I know). If you look at `configure.ac` you'll see:

    GTK_DOC_CHECK([1.14],[--flavour no-tmpl])

so you must have the gtkdoc macros present to make `configure`. 

This is only a problem if you want to build from git. Could you build from a tarball instead? They have much lower requirements:

http://www.vips.ecs.soton.ac.uk/supported/current/

**Comment by irnnr** [comment]
yeah, currently building from git. Will check tar. Thx!

**Comment by irnnr** [comment]
works
