### ISSUE TITLE
tiffsave in ImageScope

### ISSUE THREAD

**Issue by jagielski** [jcupitt/libvips#321]
I have been using the tiffsave operation to convert the base image of Aperio svs files into a tiff. For some reason, this makes them unreadable by Aperio ImageScope and ImageJ, prompting 'errorCode 189 - 32 bits per pixel not supported' in ImageScope, and ImageJ just crashes.

Could you suggest a workaround for this? I haven't been able to find any conversion tool so far in vips that will allow it to be opened in ImageScope. It works fine when being opened in nip2 or even Windows Photo Viewer.

For reference, I have the command has been
bin/vips tiffsave x.svs x.tiff --vips-progress
Nothing extra.

**Comment by bgilbert** [comment]
VIPS' OpenSlide loader returns RGBA pixel data.  I'd guess that the alpha channel is confusing ImageScope and ImageJ.  What happens if you [export only the RGB channels](https://github.com/openslide/openslide/wiki/OpenSlideAndVIPS#basics)?
