### ISSUE TITLE
64-bit support ?

### ISSUE THREAD

**Issue by matanshukry** [jcupitt/libvips#323]
From looking at your side ( http://www.vips.ecs.soton.ac.uk/ ), it seems only 32bit development files are available.

Does that mean you officially do not support 64bit?

**Comment by jcupitt** [comment]
Hi, libvips is 64-bit on most systems and always has been. The pre-built Windows DLLs are 32-bit, but you should be able to make 64-bit versions if you build yourself. 

When I set up the Windows build system a few years ago, 64-bit Windows was still a bit wonky, so I stuck with 32-bit for simplicity. It would be good to get it making 64-bit binaries too.

**Comment by matanshukry** [comment]
I'll try to work on it and see what you're talking about; Hopefully I'll make a PR soon, which will be making it to create as 64-bit targets as well.

I'm assuming once I do it and everything will be working, you will also build them your self and release them, together with the 32-bit targets?

**Comment by jcupitt** [comment]
This is the thing that makes the 32-bit Windows binaries:

https://github.com/jcupitt/build-win32/

For 64-bit binaries to become a standard thing that I do, that needs extending to build 64-bit targets as well. It's probably not too hard to do. Unfortunately, you will have to work on Linux or OS X for that. 

I don't think I could make use of a native Windows build system, so if you go that route you'd be responsible for maintaining it going forward.

**Comment by jcupitt** [comment]
The reason for the *nix-based cross-compiler build system:

libvips and nip2 have an autotools build system. There are cross-platform build systems, like cmake, but they have various problems, such as poor support for cross-compiling. There are (obviously) native Windows build systems, but then I'd have to maintain two separate build systems, and I don't have time for that.

You can make autotools work natively on Windows with cygwin (it does not make native Windows binaries though, unfortunately) or msys/mingw. msys works OK for single projects, but it does not build a whole stack, you need to script that separately. The standard whole-stack build system for g* projects is jhbuild. This has a set of quite complex dependencies (needs python, perl, a specific perl XML parser, etc. etc.) which are not easily met on Windows.

Therefore, jhbuild on Linux or OS X, with the gcc-mingw cross-compiler, is the simplest way to make the whole stack for a large project. Or as far as I know, anyway.

**Comment by CharlesB2** [comment]
Few months ago we've been trying to cross-compile from linux to win64 binaries, and we didn't succeed. We have managed to build binaries, after many obstacles, but the resulting DLLs don't link correctly  with windows runtime libraries.

Unfortunately our experience in cross-compiling with autotools is limited, and we gave up, but I can still make a PR with the few stuff we dug if anyone is interested.

If I were to start over I would directly use Visual Studio to compile libvips, by using https://github.com/hexchat/gtk-win32, who provides 64bit versions of the GTK environment.

**Comment by jcupitt** [comment]
I've opened an issue on the build-win32 package to add 64-bit support.

**Comment by jcupitt** [comment]
There's now a separate build-win64 project:

https://github.com/jcupitt/build-win64

No yet done, but it is making 64-bit binaries successfully. Just not the whole stack yet.

**Comment by jcupitt** [comment]
Update: win64 is all done now and the official binaries are 64-bit:

https://github.com/jcupitt/build-win64

http://www.vips.ecs.soton.ac.uk/supported/current/win32/

It uses docker to build too, so it should be very simple to make your own. The README has notes.
