### ISSUE TITLE
image magick precedence

### ISSUE THREAD

**Issue by paolochiodi** [jcupitt/libvips#324]
Just a question: if I will compile libvips with imagemagick support will it be used to load all image format or only the unsupported ones (e.g.: gifs, bmps)?

Thank you

**Comment by jcupitt** [comment]
Hi @paolochiodi , libvips has a priority system for loaders. The magickload one is set here:

https://github.com/jcupitt/libvips/blob/master/libvips/foreign/magickload.c#L101

vips sorts all the loaders by priority and tries them one by one from highest to lowest. 

So: libMagick is right at the back of the queue, as you say, it'll be used for things like BMP or DCM.

**Comment by paolochiodi** [comment]
Thank you for your explanation.
