### ISSUE TITLE
How to convert an image to RGBA? How to make sure two images have the same number of bands?

### ISSUE THREAD

**Issue by denilsonsa** [jcupitt/libvips#325]
[I've originally posted this question on StackOverflow](https://stackoverflow.com/questions/32337500/).

I'm writing an script to join several images, but it is failing because some input images are RGB and others are RGBA.

    $ vips insert foo3.png foo4.png foo.png 64 0 --expand --background '0 0 0 0'
    insert: images must have the same number of bands, or one must be single-band
    
    $ file foo?.png
    foo3.png: PNG image data, 1 x 1, 8-bit/color RGB, non-interlaced
    foo4.png: PNG image data, 1 x 1, 8-bit/color RGBA, non-interlaced

Is there any way to convert them to RGBA using `vips`? Even better if it does not need an intermediate file.

    $ vips --version
    vips-7.40.6-Thu Dec  4 13:43:24 UTC 2014

Bonus question: How to do it in `nip2`?

**Comment by jcupitt** [comment]
You're right, I don't think there is a one-step way to add a extra constant band from the command-line, I guess there should be. 

You can do it in two steps as:

```
in="/home/john/pics/k2.jpg"
width=$(vipsheader -f width $in)
height=$(vipsheader -f height $in) 
vips black alpha.v $width $height
vips linear alpha.v alpha2.v 1 255
vips bandjoin "$in alpha2.v" x.png
```

In nip2, there's `image_new` to make a new image, so:

```
in = Image_file "..."
alpha = image_new in.width in.height 1 in.format in.coding in.type 255 0 0
out = in ++ alpha
```
alpha =

**Comment by jcupitt** [comment]
I added `bandjoin_const` to add extra constant bands to images. You can now do:

```
vips bandjoin_const a.png b.png "1 2"
```

and `b.png` will be `a.png` with two extra bands, the first all 1s and the second all 2s. 

https://github.com/jcupitt/libvips/compare/3ed0904fab...ca51b46e9a

The python interface will automatically use `bandjoin_const` when possible. 

Thanks for suggesting the feature!
