### ISSUE TITLE
How to convert '.jp2' or '.tif' images to '.svs' images using VIPS or other possible softwares ?

### ISSUE THREAD

**Issue by taohuang123** [jcupitt/libvips#328]
I have 'jp2' and '.tif' images, and want to generate corresponding '.svs' images. 
I know we can open 'jp2' and '.tif' images in ScanScope, and extract parts of the images as '.svs' images. However, I want to transform the entirely images as '.svs' and make it possible for a lot of images, meaning that it should be automatic.
What can I do?
Thanks.

**Comment by jcupitt** [comment]
Hi, libvips uses openslide to read svs images. Unfortunately openslide (by design) only supports svs image read. You'll need to find some other way to write svs, perhaps your vendor's software can do this?

**Comment by taohuang123** [comment]
Another question, when I convert 'svs' file to 'tif' using VIPS, is it possible to specify the compression ratio using JPEG2000?
I know we can use the command: vips extract_band 1.svs 1.tif[pyramid,tile,compression=jpeg] 0 --n 3
to convert 'svs' to 'tif' using JPEG compression. However, I want to use JPEG 2000 compression, and specify the compression ratio.
It seems that in VIPS, the compression option for 'tif' includes:
"none" - no compression
"jpeg" - JPEG compression
"deflate" - ZIP (deflate) compression
"packbits" - TIFF packbits compression
"ccittfax4" - CCITT Group 4 fax encoding
"lzw" - Lempel-Ziv compression' 
So how to convert 'svs' into 'tif' using JPEG2000 compression, and specify the compression ratio? I need to test something under different compression ratios.
Thanks.

**Comment by taohuang123** [comment]
Or do you know other tools or softwares to do this job ?
Thanks.

**Comment by jcupitt** [comment]
libtiff, the standard tiff writer, does not directly support jpeg2000 compression, so libvips does not either.

Some manufacturers do use jp2k inside tiff files, but they (I think) each do it in a slightly different way with their own code and there's little standardization.

Probably your best solution would be to just use jp2k file format. libvips does not support this, unfortunately, so you would need to use something like ImageMagick.

**Comment by taohuang123** [comment]
Thanks for your help.

**Comment by taohuang123** [comment]
Then how to convert 'svs' to 'jp2' and specify the compression ratio using VIPS?
When I load the 'svs' file into matlab, use the command 'f=imread('1.svs','Index',1,'PixelRegion',{row, conl})' to read parts of the full resolution image of 'svs', why did I get a black 'f' ?
It is not only black image using 'imshow', it has 0 values in RGB channels.
When I read the full resolution image of some other 'svs' files like above in matlab, the image can be shown normally. Another option is that I load parts of the full resolution image and use 'imwrite(f,'f.jp2','compressionratio',100)' command to convert the 'svs' into 'jp2'. And maybe all the 'jp2' patches can be combined together to form a large 'jp2'.
But it would be great if VIPS can convert the full resolution image of 'SVS' into a large 'jp2' directly.
Thanks.

**Comment by jcupitt** [comment]
Hi again, you can't convert svs directly to jp2 with vips. You would need to use something like ImageMagick, assuming it supports svs format (I don't know). You might have to use vips to convert svs to tiff, then use ImageMagick to convert tiff to jp2.

matlab does not support svs. It is trying to load the svs image as a tiff file (since svs looks rather like tiff) and failing.

**Comment by jcupitt** [comment]
I agree that jpeg2000 support in vips would be useful. OpenJPEG is a reasonable jp2k library, libvips should probably just use that.

**Comment by taohuang123** [comment]
Thanks.

**Comment by 03-134202-096** [comment]
Hi, Anyone guide me that can we convert regular image(png,jpg etc) to svs format?

**Comment by jcupitt** [comment]
Please don't add to closed issues. Open a new discussion instead.

(SVS is hard to write since it's a non-standard TIFF-like format that's not really TIFF. I wouldn't try to write it)
