### ISSUE TITLE
Individual pixel readout

### ISSUE THREAD

**Issue by Jondeen** [jcupitt/libvips#329]
Hi - hopefully this will be a quick one;

How do I read individual pixel values at position x,y from an image im in python syntax?

**Comment by jcupitt** [comment]
Hi Jonas, you need `getpoint`:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-arithmetic.html#vips-getpoint

```bash
$ vips getpoint
read a point from an image
usage:
   getpoint in x y
where:
   in           - Input image, input VipsImage
   x            - Point to read, input gint
			default: 0
			min: 0, max: 100000000
   y            - Point to read, input gint
			default: 0
			min: 0, max: 100000000
outputs:
   out-array    - Array of output values, output VipsArrayDouble
```

In Python:

```bash
$ python
Python 2.7.10 (default, Jul  3 2015, 01:23:30) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Vips
>>> x = Vips.Image.new_from_file("k2.jpg")
>>> x.getpoint(0, 0)
[13.0, 3.0, 2.0]
>>> x(0, 0)
[13.0, 3.0, 2.0]
>>> 
```

The vips Python binding also overrides `()` as `getpoint`, but it might be a little cryptic. It overrides `[]` as get band, so there's a parallel there. 

You'll find `getpoint` is too slow to be useful for any serious processing, it's only useful for things like reading values from histograms.

**Comment by Jondeen** [comment]
>You'll find getpoint is too slow to be useful for any serious processing, it's only useful for things like reading values from histograms.

Which was exactly what I was doing. Thanks a lot :D

**Comment by jcupitt** [comment]
Oh haha! Well, carry on then. 

Have you seen `profile`? It's useful for searching a histogram for the first non-zero value:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-arithmetic.html#vips-profile

**Comment by sergeevabc** [comment]
![image](https://github.com/libvips/libvips/assets/373718/3e4cf34a-6602-4d80-8748-5ed2c69442b2)

``` console
$ vips getpoint image.png 185 134
255 0 0
```
Output seems to be RGB, is there a flag to get it as HEX? ImageMagick [can do that](https://stackoverflow.com/questions/69697173/imagemagick-get-pixel-color-by-x-y-coordinates).

**Comment by jcupitt** [comment]
Hey @sergeevabc,

No, libvips has very few options, you're supposed to combine it with other tools for things like that, so bash / python / etc.

In this case, perhaps:

```
pixel_in_hex=$(for x in $(vips getpoint ~/pics/k2.jpg 0 0); do printf '%02x' $x; done)
echo '#'$pixel_in_hex
```

I expect there's a better way (there always is with bash).

**Comment by sergeevabc** [comment]
> I expect there's a better way (there always is with bash).

Indeed, there are [plenty of ways](https://codegolf.stackexchange.com/questions/13132/color-rgb-int-to-hex) to convert RGB to HEX.
PowerShell has just served me well under Windows 7 as follows

``` console
$ vips getpoint image.png 185 134 | pwsh -c "-join(-split $input|%{'{0:X2}'-f+$_})"
FF0000
```

But at the end of the day we need a native way to achieve this (e.g. `--format hex`).

**Comment by jcupitt** [comment]
> But at the end of the day we need a native way to achieve this (e.g. --format hex).

I think that's out of scope for libvips -- it's not aiming to be a complete solution, you can use the invoking programming language for tasks like that.
