### ISSUE TITLE
Python logging configuration

### ISSUE THREAD

**Issue by HackerMD** [jcupitt/libvips#330]
Somehow the import of *Vips* screws up the whole logging configuration.

```{python}
import logging

logger = logging.getLogger(__name__)

def configure_logging():
    FORMAT = '%(asctime)-15s %(message)s'
    logging.basicConfig(format=FORMAT, level=logging.DEBUG)

if __name__ == '__main__':

    configure_logging()

    logger.info('blabla')
``` 

results in the following console output:

```{bash}
2015-09-25 18:16:16,461 blabla
```

while the same code with import of *Vips* doesn't output anything

```{python}
import logging
from gi.repository import Vips

logger = logging.getLogger(__name__)

def configure_logging():
    FORMAT = '%(asctime)-15s %(message)s'
    logging.basicConfig(format=FORMAT, level=logging.DEBUG)

if __name__ == '__main__':

    configure_logging()

    logger.info('blabla')
```

**Comment by jcupitt** [comment]
How strange! `Vips.py` doesn't do anything odd:

```
$ grep logg *.py
Vips.py:import logging
Vips.py:    logging.debug('imageize match_image=%s, value=%s' % (match_image, value))
Vips.py:        logging.debug('Error %s %s', self.message, self.detail)
... etc.
```

I suppose it maybe should make a module logger instead, but I don't know why using the top-level logger would break things. 

Do you have any insight into why this might be happening?

**Comment by jcupitt** [comment]
I made `Vips.py` use its own logger and it seems to fix it. With your program I now see:

```python
!/usr/bin/python

import logging

from gi.repository import Vips

logger = logging.getLogger(__name__)

def configure_logging():
    FORMAT = '%(asctime)-15s %(message)s'
    logging.basicConfig(format=FORMAT, level=logging.DEBUG)

if __name__ == '__main__':
    configure_logging()

    logger.info('blabla')
```

```
$ ./log1.py 
2015-09-26 12:05:55,750 blabla
memory: high-water mark 0 bytes
```

ie. we have your logger and `Vips.py` cooperating.

**Comment by jcupitt** [comment]
There's a new vips release coming in a few weeks which will include this change, or you can install from git master.

**Comment by HackerMD** [comment]
Awesome! Thanks a lot for the quick fix!

**Comment by jcupitt** [comment]
Please reopen if it doesn't work. Thanks again.

**Comment by HackerMD** [comment]
Hi thanks again for your fix.

I fixed the file locally and this worked. However, I have problems to install libvips from github:
I cloned the repository and installed dependencies as follows:

```
git clone https://github.com/jcupitt/libvips.git $HOME/libvips

sudo apt-get install build-essential
sudo apt-get install glib2.0-dev
sudo apt-get install pkg-config
sudo apt-get install libxml2-dev
sudo apt-get install python-gi-dev
sudo apt-get install ibgirepository1.0-dev
sudo apt-get install gobject-introspection
sudo apt-get install python-gobject
sudo apt-get install libtiff5-dev
sudo apt-get install libjpeg-turbo8-dev
sudo apt-get install libgsf-1-dev
sudo apt-get install swig
sudo apt-get install gtk-doc-tools
```

When I run `.configure` or `CFLAGS="-g -Wall" CXXFLAGS="-g -Wall" ./configure --prefix=/home/ubuntu/libvips` I get the following error:

```
configure: error: Package requirements (glib-2.0 >= 2.6 gmodule-2.0 libxml-2.0 gobject-2.0) were not met:

No package 'glib-2.0' found
No package 'gmodule-2.0' found
No package 'libxml-2.0' found
No package 'gobject-2.0' found
```

This is weird because at least some of the dependencies are installed (see above).

**Comment by jcupitt** [comment]
Looks like `pkg-config` isn't working. You should see something like:

```
john@katamata ~ $ pkg-config glib-2.0 --modversion
2.44.1
```

Does it need installing, maybe?

**Comment by HackerMD** [comment]
```
ubuntu@frontend002:~$ pkg-config glib-2.0 --modversion
2.40.2
```

**Comment by jcupitt** [comment]
How strange! Take a look at `config.log`, it should have the details of what went wrong during configure.

**Comment by HackerMD** [comment]
I found the problem. I set the `PKG_CONFIG_PATH` and was still in the same terminal window. When I logged out and logged in again it worked. Sorry my bad!

Thanks for your help! Great support!!

**Comment by HackerMD** [comment]
I could finally build successfully. In order to be able to use the Python bindings via `from gi.repository import Vips`, I had to include the following lines into my `.bash_profile` file:

```
export VIPSHOME=/usr/local
export GI_TYPELIB_PATH=$VIPSHOME/lib/girepository-1.0
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VIPSHOME/lib
```

Thanks again and also to "drmaquino" who figured this out in [issue 237](https://github.com/jcupitt/libvips/issues/237)

**Comment by HackerMD** [comment]
The only thing still missing is the `OpenSlide` functionality.

How can I install Vips with OpenSlide on ubuntu?

I installed OpenSlide as follows:

```
sudo apt-get install openslide-tools
sudo apt-get install python-openslide
```

But somehow openslide is not picked up.

**Comment by bgilbert** [comment]
You need `libopenslide-dev` to compile programs with OpenSlide.

**Comment by HackerMD** [comment]
Perfect! Thanks!
