### ISSUE TITLE
Cannot use vips_text: VipsOperation: class "text" not found

### ISSUE THREAD

**Issue by h2non** [jcupitt/libvips#336]
I'm experiment some particular issues in different platforms when using `vips_text`. I've tested it in both `7.42` and `8.x`. Probably this issue can be trivially fixed, but I can't realize at all which is the real origin.

I guess it's related to the dependencies based on the specific target OS. 
I'm able to work with `vips_text` perfectly in OSX, however running the same code in Ubuntu throws the following error: `VipsOperation: class "text" not found`.

I'm not sure if this is related some unsatisfied dependency such as `pango` library, which is part of GTK. 
Some ideas?

**Comment by jcupitt** [comment]
Hi, yes, it's probably `pangoft2`. What does the output of `configure` look like? There should be an item at the end for this.

**Comment by h2non** [comment]
I'm using the latest version of `libpangoft2`, as well of `libpango`, available in the official Ubuntu repositories. I'm sorry, but I cannot completely understand what you're pointing about `configure`.

**Comment by jcupitt** [comment]
Do you have the -dev versions of those packages? At the end of `./configure` you should see:

```
text rendering with pangoft2: 		yes
```

vips finds the package with `pkg-config`:

```
$ pkg-config pangoft2 --cflags
-pthread -I/usr/include/pango-1.0 -I/usr/include/harfbuzz ...
```

**Comment by h2non** [comment]
Oh, thanks, that's clear now. I'll try configuring `pkg-config`. The `dev` packages should be there too.

**Comment by h2non** [comment]
The `libpango` dependency is required and it was [properly documented](https://github.com/jcupitt/libvips#pangoft2) too, so I've nothing more to add.

Thank you, @jcupitt.
