### ISSUE TITLE
resize pdf to picture not working to correct dimenions

### ISSUE THREAD

**Issue by ttback** [jcupitt/libvips#337]
`vipsthumbnail pdfs/test.pdf --size 397x747`
`identify pdfs/tn_test.jpg`

result: pdfs/tn_test.jpg JPEG 378x747 378x747+0+0 8-bit sRGB 76.3KB 0.000u 0:00.000

Is there any reason why the width is off?

**Comment by jcupitt** [comment]
Hi, `--size` sets the box which `vipsthumbnail` sizes the image to fit within. So here your source image is a little narrower than the `--size` box, so width ends up shorter.

You could try using the `--crop` option. This shrinks so that the smallest axis fits within the box, then crops the larger one down. In this case you should see both width and height match the box, but strips will have been cut from the top and bottom.

**Comment by ttback** [comment]
@jcupitt thanks. I realize regardless if I enlarge or shrink the image, the result thumbnail seems very blurred (text not readable), is there any way to keep the resolution like imagemagick's density option?

**Comment by ttback** [comment]
Think what I am trying to do is similar to here https://github.com/jcupitt/libvips/issues/284
Except it's a single page pdf that I want to keep the 300 DPI.

**Comment by ttback** [comment]
Also I got following error when trying out the python script on 284:
````
Traceback (most recent call last):
  File "vips.script.py", line 9, in <module>
    pdf = Vips.Image.new_from_file(sys.argv[1],
AttributeError: type object 'Image' has no attribute 'new_from_file'
````

Did the library get updated with new api?

**Comment by lovell** [comment]
@ttback Support for `density` was added in https://github.com/jcupitt/libvips/pull/200 so you should be able to use something like:

```sh
vipsthumbnail pdfs/test.pdf[density=300] ...
```

**Comment by jcupitt** [comment]
The error:

```
AttributeError: type object 'Image' has no attribute 'new_from_file'
```

usually means there's an install problem, probably the `Vips.py` overrides file is not in the right place.

The start of the "vips from python" chapter has some notes on this:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-python.html

**Comment by jcupitt** [comment]
Is this resolved? Please reopen if not.
