### ISSUE TITLE
Inplace operations via Command Line Interface does not work

### ISSUE THREAD

**Issue by AndreasSchmid1** [jcupitt/libvips#340]
When I use the inplace operators from command line. The functions returns successfully but inside the images no result is shown. For excample I want to draw a line or another image into a image.

"$vips im_draw_line out.tif 250 250 1000 1000 155" .

Am I doing something wrong or is this a bug?

Thank you guys in advance

**Comment by jcupitt** [comment]
Hi @AndreasSchmid1 you need to use an image format that supports direct modification. In your example, the image `out.tif` is being decompressed into memory, the line is being drawn, and then the program terminates. The modified image is not written back to disc again.

The simplest format for this is `.v` (vips) format. Try:

```
$ vips copy k2.jpg k2.v
$ vips draw_line k2.v 255 0 0 200 200
$ vips copy k2.v x.jpg
```

Now look at `x.v`, it should have a line on. 

This works because vips format can be opened directly from disc, there's no read phase. The `draw_line` command modifies the disc file as it executes. 

In something like Python it's much simpler, of course, since you can control read and write. For example:

```
$ python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Vips
>>> x = Vips.Image.new_from_file("k2.jpg")
>>> x = x.draw_line(255, 0, 0, 200, 200)
>>> x.write_to_file("x2.jpg")
```

and `x2.jpg` will have a line on.

**Comment by AndreasSchmid1** [comment]
Hi @jcupitt . Thank you very much for your fast and detailed answer! 
You are right. Your excample worked and I also successfully used "vipsdrawimage".
Unfortunately I got an error (unable to MapViewOfFile) with very large files (50000px X 50000px). (Basically I try to recreate a pyramid tiled bigtiff file from the highest zoomlevel of a deepzoom pyramid). 

I think I will take your advice and look into Python.

**Comment by jcupitt** [comment]
Yes, on Windows vips is only 32-bit, so it can't map more than a couple of GB. To draw on huge files, you'll need to cut out a bit of the image, draw, then paste it back.

Could you explain the problem you are trying to solve? Do you want to make a single huge image from a deepzoom directory? Yes, I would use Python. It's a bit of a pain to install on Windows, unfortunately. I'll try to find a guide for you, someone did post one.

**Comment by jcupitt** [comment]
Sorry, can't see it. The steps would be roughly:

* install Python
* install pygtk (you need gobject-introspection and this is an easy way to get it) and check it works
* add the vips-dev area to your path
* you need to get the vips `.typelib` into the gobject-introspection `GI_TYPELIB_PATH` ... probably adding `GI_TYPELIB_PATH` as a new environment variable would be the best way to do it
* check it works: you should be able to 'from gi.repository import Vips' in Python
* you need to copy the vips overrides file `Vips.py` to the overrides area in pygtk
* check it works: see if `x = Vips.Image.new_from_file("somefile.jpg")` works

... good luck. Some day all this will be simpler :-(

**Comment by AndreasSchmid1** [comment]
Yes, I try to write a deepzoom to tiff converter!

Thank you very much again! I will look into this.

**Comment by jcupitt** [comment]
I made you a tiny dz rebuilder:

```python
#!/usr/bin/python

import sys
import os
import glob
import re

from gi.repository import Vips

if len(sys.argv) != 3:
    print("usage: %s outfile deepzoom-directory" % sys.argv[0])
    sys.exit(1)

# scan the deepzoom dir and work out the image size
all_files = glob.glob(os.path.join(sys.argv[2], "*_*.jpeg"))

max_x = 0
max_y = 0
for filename in all_files:
    match = re.search("([\d]+)_([\d]+).jpeg", filename)
    max_x = max([max_x, int(match.group(1))])
    max_y = max([max_y, int(match.group(2))])

print("image is %d tiles across, %d tiles down" % (max_x, max_y))

# open the tile at position (x, y)
def open_tile(x, y):
    filename = os.path.join(sys.argv[2], "%d_%d.jpeg" % (x, y))
    tile = Vips.Image.new_from_file(filename, access =
                                    Vips.Access.SEQUENTIAL_UNBUFFERED)

    return tile

# join a set of tiles horizontally to make a strip
def join_strip(y):
    strip = open_tile(0, y)
    for x in range(1, max_x + 1):
        strip = strip.join(open_tile(x, y), Vips.Direction.HORIZONTAL)

    return strip

# join a set of strips vertically to make the image
image = join_strip(0)
for y in range(1, max_y + 1): 
    image = image.join(join_strip(y), Vips.Direction.VERTICAL)

image.write_to_file(sys.argv[1])
```

That'll only work for smallish images. Many systems will start to have problems if you open more than 1,000 files at once, so you'll have to join the images in sections.

It doesn't take account of DZ images with tile overlaps. You might need to use `.crop()` to take off the right and bottom edge of each tile.

**Comment by AndreasSchmid1** [comment]
Oh WOW, you are my hero, I will test it as soon as I got Python working.

**Comment by AndreasSchmid1** [comment]
It worked. Thank you so much! 
In the next days/weeks I will try to adapt your Phyton script to C# via P-Invoking the libvips binaries.

**Comment by jcupitt** [comment]
You got vips working on Windows with Python? That's great.

If you could make a quick post explaining what you did, that would be very helpful.

**Comment by AndreasSchmid1** [comment]
Unfortunately I was not the guy who implemented it... As far as I know my colleague setted up a Linux environment to prove that it is working. Our final solution will be a C# application. 
But I will ask him the next time!

**Comment by jcupitt** [comment]
A full C# binding would be a week or two's work. The C++ one might make a good starting point:

https://github.com/jcupitt/libvips/tree/master/cplusplus

**Comment by AndreasSchmid1** [comment]
Totally agree. Thank you for the link.
