### ISSUE TITLE
dzsave strips trailing bracket pairs from output directory

### ISSUE THREAD

**Issue by ChrisHSandN** [jcupitt/libvips#342]
Hi, I seem to be having an issue with vips dzsave removing brackets (and their contents) if they are the last part of the output path string. Brackets used in other parts / non paired brackets don’t seem to have the same issue.

Command:
`vips dzsave 0.jpg '0(foobar)'`

Actual Output:
`0.dzi  0_files`

Expected Output: 
`0(foobar).dzi  0_(foobar)files`

The ‘(foobar)’ part of the output directory is silently removed. As a quick fix for my app, is there any known way to escape the brackets?

    vips –version
    vips-8.0.2-Tue Jun 30 12:44:36 BST 2015

**Comment by jcupitt** [comment]
Hi Chris, yes, vips lets you put options in brackets at the end of filenames. For example:

```
vips copy x.tif y.jpg[Q=90]
```

and `y.jpg` will be written with Q factor 90. There's usually an extension at the end, so you can still have brackets in the body of the filename and they won't be mistaken for options. In the case of  `dzsave` I can see it's very easy for there to be mixups. I'll have a look at the code and see if I can improve the behaviour in this case.

A quick workaround might be to use the deepzoom filename extension, `.dz`. For example:

```
$ vips dzsave k2.jpg x.dz
$ ls x*
x.dzi

x_files:
0  1  10 11 2  3  4  5  6  7  8  9
```

A bit strange, but it should fix it.

**Comment by ChrisHSandN** [comment]
Thanks for your excellent feedback :) For now I have added on a fake extension to the output path and all works as expected.

**Comment by jcupitt** [comment]
I added a note about this:

https://github.com/jcupitt/libvips/commit/9cad049051757bd7477d98c835668596893b90f8

It looks like removing `()` options would be the best solution. At the moment you can enclose options in any of `<>`, `()`, `[]`, `{}`, which is probably too flexible (and confusing). I'll make it `[]` only for the next version.
