### ISSUE TITLE
Vips Error at Compilation at libMagickCore-6.Q16.so

### ISSUE THREAD

**Issue by sadaqatullahn** [jcupitt/libvips#343]
Following the instructions on [vips website](http://www.vips.ecs.soton.ac.uk/index.php?title=Build_on_Ubuntu) for Ubuntu, I get errors of *undefined reference* while running the *make* after *./configure*. After googling for 2 days I give up and am posting a issue. 
Following is the list of the errors:
`/bin/bash ../libtool  --tag=CC   --mode=link gcc -std=gnu99  -g -O2   -o vips vips.o -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -fopenmp -I/usr/local/include/ImageMagick-6 -I/usr/local/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/x86_64-linux-gnu -I/usr/include/pango-1.0 -I/usr/include/libxml2 -I/usr/include/libpng12 -I/usr/include/libexif -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/include/freetype2 -I/usr/include/OpenEXR -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 ../libvips/libvips.la -L/usr/local/lib -lMagickWand-6.Q16 -lMagickCore-6.Q16   -lpng12   -ltiff   -lz -ljpeg  -Wl,--export-dynamic -pthread -lgmodule-2.0 -lxml2 -lgobject-2.0 -lglib-2.0   -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype    -lfftw3    -L/usr/local/lib -llcms2   -pthread -lIlmImf -lz -lImath -lHalf -lIex -lIlmThread    -lcfitsio -lpthread     -lexif   -lm 
libtool: link: gcc -std=gnu99 -g -O2 -o .libs/vips vips.o -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -fopenmp -I/usr/local/include/ImageMagick-6 -I/usr/local/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/x86_64-linux-gnu -I/usr/include/pango-1.0 -I/usr/include/libxml2 -I/usr/include/libpng12 -I/usr/include/libexif -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/include/freetype2 -I/usr/include/OpenEXR -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -Wl,--export-dynamic -pthread -pthread  ../libvips/.libs/libvips.so -L/usr/local/lib /usr/local/lib/libMagickWand-6.Q16.so /usr/local/lib/libMagickCore-6.Q16.so -lpng12 /usr/lib/x86_64-linux-gnu/libtiff.so -ljpeg -lgmodule-2.0 -lxml2 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 /usr/lib/x86_64-linux-gnu/libfreetype.so -lfftw3 /usr/local/lib/liblcms2.so /usr/lib/x86_64-linux-gnu/libIlmImf.so -lz -lImath -lHalf -lIex -lIlmThread -lcfitsio -lpthread -lexif -lm -fopenmp -pthread
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPathStart'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetViewbox'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetFont'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetStrokeColor'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawColor'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPopPattern'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetFillPatternURL'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetStrokeDashArray'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawAllocateWand'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `PushDrawingWand'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPathClose'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `PixelSetRedQuantum'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawScale'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetTextUnderColor'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawLine'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `PopDrawingWand'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DestroyPixelWand'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetFontSize'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawTranslate'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPathMoveToAbsolute'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawAnnotation'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetStrokeAntialias'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPushDefs'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPathFinish'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DestroyMagickWand'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawRoundRectangle'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPopDefs'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `PixelSetQuantumColor'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetFillColor'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawComposite'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetClipPath'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawRender'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawEllipse'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawComment'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPathLineToAbsolute'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `PixelSetBlueQuantum'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetStrokeLineJoin'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPushPattern'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `PixelSetColor'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPushClipPath'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetStrokeLineCap'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawArc'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `NewMagickWandFromImage'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `PixelSetOpacityQuantum'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPopClipPath'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetClipRule'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `NewPixelWand'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawRotate'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawRectangle'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DestroyDrawingWand'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetStrokeWidth'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawPathEllipticArcAbsolute'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `DrawSetStrokePatternURL'
/usr/local/lib/libMagickCore-6.Q16.so: undefined reference to `PixelSetGreenQuantum'
collect2: error: ld returned 1 exit status
make[2]: *** [vips] Error 1
make[2]: Leaving directory `/home/sadaqatullah/vips-8.1.0/tools'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/sadaqatullah/vips-8.1.0'
make: *** [all] Error 2
`
I have tested the ImageMagick and it is working fine. But when running compilation of **vips** with `make` it fails with above ending messages. I have tried a lot of methods to try and make it work but nothing seems to work. A little help or direction to get this done will be amazing help.

**Comment by jcupitt** [comment]
Hi, sorry it's being difficult. That looks like an imagemagick bug to me: they have calls to the drawing wand API in magickcore, but their magickcore `.pc` file does not include the drawing library. Or maybe the draw library has not been compiled into magickcore for some reason, but they've forgotten to remove their own calls to it. 

Are you sure you need the latest imagemagick? Unless this is a very old Ubuntu, I would just use the system one. 

If you really do need latest the imagemagick, you'll need to fix this bug for them.

**Comment by jcupitt** [comment]
I had a look, and current imagemagick (6.9.2-4) seems to be broken. 

They have split their library into two parts, magickcore (the low-level core library) and magickwand (extra high-level functions). Wand depends on core, so you can either use just core, or you can use wand and use core indirectly. However, they've recently added calls from core into wand (ie. from the low level to the high level), creating a circular dependency. 

I'm not sure how to fix this. I would fall back to an older imagemagick.

**Comment by jcupitt** [comment]
What Ubuntu are you using? I have 15.10 and it's using imagemagick-6.8.9-9 (I think), so that version at least seems to work.

**Comment by jcupitt** [comment]
I found a simple solution -- configure vips like this:

```
./configure --with-magickpackage=Wand
```

And it seems to work with 6.9.2-4. I'll look into why this fixes it.

**Comment by sadaqatullahn** [comment]
Thanks it worked smoothly. :+1: 
I am using Ubuntu 14.04. Initially I tried older version of ImageMagick that gave me the similar errors. Then I tried latest version of ImageMagick and recieved similar error. But your solution worked perfectly and it is installed perfectly.

**Comment by jcupitt** [comment]
I've started a thread on the IM board about this:

http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=28603

this probably needs addressing before the next vips release. I've reopened as a reminder.

**Comment by jcupitt** [comment]
I've found the problem, see:

http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=28634&p=127217

You need to configure imagemagick with `--with-modules` or linking will fail. This feels like an imagemagick bug to me, though I don't expect them to fix it.
