### ISSUE TITLE
vips doesn't convert "float" images to pngs properly

### ISSUE THREAD

**Issue by bawolff** [jcupitt/libvips#344]
So, we've been trying to shrink images, followed by a sharpening using the command line vips program. Specifically we do something like

vips shrink input.tiff shrunk.v 10 10
vips im_convf shrunk.v out.png sharpen.conv

where sharpen.conv is a file containing the following:
5 5 1.24692300108 0
-0.000480064559676 -0.00500238758371 -0.0109262190164 -0.00500238758371 -0.000480064559676
-0.00500238758371 -0.0521260756148 -0.113853816622 -0.0521260756148 -0.00500238758371
-0.0109262190164 -0.113853816622 1.99648680501 -0.113853816622 -0.0109262190164
-0.00500238758371 -0.0521260756148 -0.113853816622 -0.0521260756148 -0.00500238758371
-0.000480064559676 -0.00500238758371 -0.0109262190164 -0.00500238758371 -0.000480064559676

This seems to work great for most tiff files. However, 16-bit greyscale tiff files (Example: https://upload.wikimedia.org/wikipedia/commons/1/1f/Fifth_avenue_after_snow_storm_4a12278a.tif ) do not work, and result in a pure black box. (But only when converting to PNGs. In an older version it didn't seem to work for jpegs too, but that seems to have been fixed).

It appears vips is somehow getting confused about converting the float type images to a png, if originally they were ushort type (16bit).

As a work around, we're planning to do something like:

vips shrink input.tiff shrunk.v 10 10
FORMAT=`vips im_header_int shrunk.v`
vips im_convf shrunk.v sharp.v sharpen.conv
vips im_clip2fmt sharp.v out.png $FORMAT
(roughly speaking, we're not doing this in a shell script, but you get the gist)

However, I believe this is a bug, and we probably shouldn't be having to do this work around.

Version: We are using 7.38.5. However, I compiled vips from the git master branch just now, and can confirm this bug is present in master.
Downstream bug: https://phabricator.wikimedia.org/T116947

**Comment by jcupitt** [comment]
Hi again, I agree, I think this is a bug, it looks like a problem with uint16 images and the float convolution operator, I'll look into it. 

As a workaround, int convolution seems to be fine. I made `sharpen_int.mat`, int version of your mask:

```
5 5 131 0
0 0 -1 0 0 
0 -5 -11 -5 0 
-1 -11 199 -11 -1 
0 -5 -11 -5 0 
0 0 -1 0 0 
```

(that's just everything * 100) then ran:

```
$ vips conv shrunk.v x.png sharpen_int.mat 
```

and it seems fine.

**Comment by jcupitt** [comment]
Have you looked at the vips `resize` operator? It does a fast, high-quality shrink, approximately lanczos2, it should be noticeably better quality than `shrink` + `sharpen`. It's the thing tumblr and others are using now.

The algorithm is roughly:

* box filter down to approximately twice the final output size with `vips_shrink()`
* apply an antialiasing filter with `vips_gaussblur()` with sigma tuned to the stencil size of the interpolator in the next step
* reduce to the final size with `vips_affine()` and, by default, a bicubic interpolator
* apply a finishing filter -- a mild sharpening 

You probably handle all this already, but the `vipsthumbnail` sources have code for colour management, exif autorotate, alpha transparency (you have to premultiply any alpha channels before shrinking), and some other things. 

https://github.com/jcupitt/libvips/blob/master/tools/vipsthumbnail.c

**Comment by jcupitt** [comment]
There's some background on the tuning of `resize` on this issue, if you're curious: https://github.com/lovell/sharp/issues/121

**Comment by bawolff** [comment]
vips resize isn't in the version of vips that's currently on the wikimedia cluster (7.38.5).

Most of the code for MediaWiki interfacing with vips was written by someone else a while back. I'm not exactly sure why one command was chosen over another (Although possibly it was written prior to vipsthumbnail existing, which might explain the design choice). Anyways, sounds like something we should look into.

> alpha transparency (you have to premultiply any alpha channels before shrinking)

we don't do that currently. Although we only use vips for large tiffs and pngs. Small pngs (where transparency usually crops up) are still handled by image magick currently.

**Comment by bawolff** [comment]
I'm filing https://phabricator.wikimedia.org/T117355 at the wikimedia bug tracker to investigate doing that (Hopefully at some point we will actually investigate it. Image related issues in MediaWiki/Wikimedia tend  not to receive the love they deserves)

**Comment by jcupitt** [comment]
There's an old issue for this too: https://phabricator.wikimedia.org/T49311

**Comment by jcupitt** [comment]
I've tried to improve the rules for converting 16-bit images. Your example works as expected now anyway.

This change will be in 8.2, thanks for reporting the issue!

**Comment by jcupitt** [comment]
I improved the way it converts float masks to int for int convolution. You can now run:

```
vips conv Fifth_avenue_after_snow_storm_4a12278a.tif x.png mediawikimask.mat 
```

and see the expected result. That's using a rather imprecise mask -- the *100 scaled one above would be much more accurate.
