### ISSUE TITLE
Cannot specify different page when using vips shrink on a multi-page tiff

### ISSUE THREAD

**Issue by bawolff** [jcupitt/libvips#345]
I want to be able to scale very large tiff files (In the GB range or around 250 megapixels) using at most 500 MB of ram, with the command line vips tools

We've been using vips shrink, which has been very effective at this task. However, it doesn't allow specifying format options for the input file, so there's no way to specify "use page number x" (That I can see). Thus we've been using vips im_shrink for other pages of a multipage tiff files (appending ":<page number>" to the input filename). This works not bad, but tends to run out of memory on the really big files.

Is there any way to shrink files using the command line vips tools, well specifying a page that's not 1, and that works in sequential mode to use a constant amount of memory? If not, this is a feature request for such a thing.

Thanks.

Downstream bug for reference: https://phabricator.wikimedia.org/T117349

**Comment by bawolff** [comment]
After poking around some, I just discovered that you can do

vips shrink foo.tiff[page=2] out.png

Perhaps this could be included in the documentation more prominently? Sorry about filing the bug that's not a bug.

**Comment by jcupitt** [comment]
Hi @bawolff, yes the `im_` functions are the old vips7 interface, the unprefixed names are the new vips8 interface. The docs are here:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-cli.html

There's a section on "Implicit file format conversion" that covers this stuff.

The new vips8 interface is smart enough to turn on sequential mode for you automatically, so hopefully it should run in a small amount of memory.

**Comment by bawolff** [comment]
Ah, that is the doc I was looking for. I must have missed it when looking through the docs. Spent too much time trying to read through man pages, and didn't notice the other docs.

If you're curious, the thing that clued me in to the correct syntax was your blog post from a while back: http://libvips.blogspot.ca/2013/11/tips-and-tricks-for-vipsthumbnail.html#!/2013/11/tips-and-tricks-for-vipsthumbnail.html

Thanks.

**Comment by jcupitt** [comment]
Ah OK, yes all the docs have moved into that manual now, we've dumped the man pages.
