### ISSUE TITLE
Vips.Image.new_from_array() in Python gives wrong format

### ISSUE THREAD

**Issue by HackerMD** [jcupitt/libvips#346]
The `new_from_array()` method available for the Vips8 bindings installed via homebrew on OSX 10.10.5
```
$ brew install vips
```
results in wrong formats:

```
import numpy as np
from gi.repository

array = np.zeros((10,10)).astype('uint16')
img = Vips.Image.new_from_array(array.tolist())
print img.get_format()
```

This gives `VIPS_FORMAT_DOUBLE`.

When I installed libvips on ubuntu from source (from git repository) the `new_from_array()` is not available.
What's the status of the Python-Vips binding on homebrew? Are there any plans to update it in the near future?

**Comment by jcupitt** [comment]
Hi @HackerMD, `.new_from_array()` is for things like:

```python
tiny_image = vips.Image.new_from_array([[1, 2, 3], [4, 5 ,6]]))
```

ie. tiny images for things like convolution masks. You need to make an image from an area of memory, which is `.new_from_memory()` or `.write_to_memory()`.

The C docs are here:


http://www.vips.ecs.soton.ac.uk/supported/8.0/doc/html/libvips/VipsImage.html#vips-image-write-to-memory

http://www.vips.ecs.soton.ac.uk/supported/8.0/doc/html/libvips/VipsImage.html#vips-image-new-from-memory

You use them in Python like this:

    >>> from gi.repository import Vips
    >>> x = Vips.Image.new_from_file("/home/john/pics/k2.jpg")
    >>> y = x.write_to_memory()
    >>> type(y)
    <type 'str'>
    >>> z = Vips.Image.new_from_memory(y, x.width, x.height, x.bands, Vips.BandFormat.UCHAR)
    >>> x.avg()
    102.79218031609196
    >>> z.avg()
    102.79218031609196

This should be clearer :-( I'll add a note to the docs about this. 

The vips on homebrew is up to date, I believe. I plan to keep it updated. 

If `.new_from_array()` wasn't working on Ubuntu you probably have an install problem. It sounds like the overrides files was not copied to the system overrides area. Try something like:

```
cd vips-x.y/python
sudo cp Vips.py /usr/lib/python2.7/dist-packages/gi/overrides
sudo cp Vips.py /usr/lib/python3/dist-packages/gi/overrides
```

It's very unfortunate, all override files must be in the single system overrides area. The "vips-from-python" docs have a short note about this at the start.

**Comment by HackerMD** [comment]
Hi!

Thanks for the immediate feedback! I've written my own function to convert a numpy array to a vips image using `numpy.getbuffer()` and `Vips.Image.new_from_memory()`. This works with some additional rotations.
I just stumbled upon the `new_from_array()` behaviour when writing a unit test for my function. Adding a note to the docs and maybe also to the [reference manual](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-python.html) would be great.

Thank you also for the hint regarding the install problem on Ubuntu. I will look into it..

**Comment by jcupitt** [comment]
I've updated the [reference manual](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-python.html) to include a new section on reading and writing areas of memory. Does it look OK? 

The install stuff at the start ought to be clearer too, I hope, does that make sense too?

**Comment by HackerMD** [comment]
Great thanks! One more question: is it possible to define the location where Vips.py should end up during the installation process to ensure it will be placed in the correct *gi/overrides* directory?

**Comment by jcupitt** [comment]
No, sorry, not as far as I know.

There's only a single `gi/overrides` directory allowed, and it's on the prefix that the gio package was installed to. If you know that you are using the Ubuntu gio, you can be sure it'll be one of:

```
sudo cp Vips.py /usr/lib/python2.7/dist-packages/gi/overrides
sudo cp Vips.py /usr/lib/python3/dist-packages/gi/overrides
```

Depending on whether you are py2 or py3.

When Ubuntu finally switches to vips8 and installs this for users this problem will go away. Until then ... :(

**Comment by HackerMD** [comment]
Copying works! Will stick to that approach then. Thanks!

**Comment by HackerMD** [comment]
I would like to consult you with regard to the function for conversion of a numpy array to a vips image.


```
def np_array_to_vips_image(nparray):
    '''
    Convert a `numpy` array to a `Vips` image object.

    Parameters
    ---------------
    nparray: numpy.ndarray

    Returns
    ----------
    gi.overrides.Vips.image
    '''
    # Look up what VIPS format corresponds to the type of this numpy array
    vips_format = np_dtype_to_vips_format(nparray.dtype)

    # VIPS reads the buffer as if the data is saved column by column (column major)
    # but numpy saves it in row major order.
    nparray_trans = nparray.T
    buf = np.getbuffer(nparray_trans)
    height, width = nparray_trans.shape
    img = Vips.Image.new_from_memory(buf, width, height, 1, vips_format)

    # Resulting image has the wrong orientation
    #
    #      |  rotate 90 CW and flip
    #     _|       ------>           ___|
    #
    # (same as horizontal flip and 90 deg CCW, but VIPS can't seem to do CCW rotations)
    img = img.rot(1)
    img = img.flip('horizontal')

    return img.copy()
```

When I use this function on my Mac with Vips installed via homebrew, I can do the following:

```
import numpy as np

array = np.random.random((10,10))
vips_image = np_array_to_vips_image(array)
vips_image.avg()
vips_image.min()
```

**Comment by jcupitt** [comment]
Oh strange. Could you paste a complete example somewhere so I can try it?

For 90 degree CCW in vips, try:

```
im = im.rot('d270')
```

**Comment by HackerMD** [comment]
Here you go! Sorry, forgot to include the other type mapping function.

```
from gi.repository import Vips
import numpy as np

def np_dtype_to_vips_format(np_dtype):
    '''
    Map numpy data types to VIPS data formats.

    Parameters
    ----------
    np_dtype: numpy.dtype

    Returns
    -------
    gi.overrides.Vips.BandFormat
    '''
    lookup = {
        np.dtype('int8'): Vips.BandFormat.CHAR,
        np.dtype('uint8'): Vips.BandFormat.UCHAR,
        np.dtype('int16'): Vips.BandFormat.SHORT,
        np.dtype('uint16'): Vips.BandFormat.USHORT,
        np.dtype('int32'): Vips.BandFormat.INT,
        np.dtype('float32'): Vips.BandFormat.FLOAT,
        np.dtype('float64'): Vips.BandFormat.DOUBLE
    }
    return lookup[np_dtype]

def np_array_to_vips_image(nparray):
    '''
    Convert a `numpy` array to a `Vips` image object.

    Parameters
    ----------
    nparray: numpy.ndarray

    Returns
    -------
    gi.overrides.Vips.image
    '''
    # Look up what VIPS format corresponds to the type of this np array
    vips_format = np_dtype_to_vips_format(nparray.dtype)

    # VIPS reads the buffer as if the data is saved column by column (column major)
    # but numpy saves it in row major order.
    nparray_trans = nparray.T
    buf = np.getbuffer(nparray_trans)
    height, width = nparray_trans.shape
    img = Vips.Image.new_from_memory(buf, width, height, 1, vips_format)

    # Resulting image has the wrong orientation
    img = img.rot(1)
    img = img.flip('horizontal')

    return img.copy()

array = np.random.random((10,10))
vips_image = np_array_to_vips_image(array)
vips_image.avg()
```

**Comment by HackerMD** [comment]
I installed Vips as follows:

```
apt-get install libx11-dev
apt-get install build-essential
apt-get install glib2.0-dev
apt-get install pkg-config
apt-get install libxml2-dev
apt-get install python-gi-dev
apt-get install libgirepository1.0-dev
apt-get install gobject-introspection
apt-get install python-gobject
apt-get install libtiff5-dev
apt-get install libjpeg-turbo8-dev
apt-get install libgsf-1-dev
apt-get install swig
apt-get install gtk-doc-tools
apt-get install openslide-tools
apt-get install python-openslide
apt-get install libopenslide-dev

export VIPSHOME=/usr/local
export GI_TYPELIB_PATH=$VIPSHOME/lib/girepository-1.0
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VIPSHOME/lib

git clone https://github.com/jcupitt/libvips.git $HOME/libvips
cd $HOME/libvips
./bootstrap.sh
./configure
make
make install
cp /usr/local/lib/python2.7/site-packages/gi/overrides/Vips.py /usr/lib/python2.7/dist-packages/gi/overrides
```

**Comment by jcupitt** [comment]
I tried with 8.1 on Ubuntu and get:

```
$ ./try227.py 
avg = 0.48211456429
```

(I added a thing to print the avg), but with the 8.1 branch I see:

```
$ ./try227.py 
avg = -3.78800600903e+126
```

Which is obviously crazy. I'll see if I can fix master.

**Comment by HackerMD** [comment]
Thank you for looking into it!

How can I install 8.1 on Ubuntu? I tried `apt-get install libvips`, but I didn't get it to work with the Python bindings despite copying the `Vips.py` file.

**Comment by jcupitt** [comment]
You can checkout the 8.1 branch from git, or download a 8.1 tarball here:

http://www.vips.ecs.soton.ac.uk/supported/current/

**Comment by HackerMD** [comment]
Sorry, maybe I'm not getting the point. Which versions did you test? You said

> I tried with 8.1 on Ubuntu and get ...

and

> but with the 8.1 branch I see ...

What's the difference between the two? The latter is the git branch, but what's the former?

In other words, is there a branch (version) that I could install for now (until master is fixed) where the problem doesn't occur?

**Comment by jcupitt** [comment]
I tried with the 8.1 branch, but the tarball is almost the same, I think. Either should work.

**Comment by HackerMD** [comment]
Sweet switching to branch `8.1` solved the problem. My tests run without error.

Thank you very much for your help!

**Comment by jcupitt** [comment]
Ooops, this had drifted off my to-do list.

Looking at it again, I think the problem is with the lifetime of the thing that numpy is giving us via `getbuffer`. If I change your code slightly to be:

```python
    nparray_trans = nparray.T
    buf = np.getbuffer(nparray_trans)
    height, width = nparray_trans.shape
    img = Vips.Image.new_from_memory(buf, width, height, 1, vips_format)
    x = img.avg()
```

ie. call `vips_avg()` immediately after `vips_image_new_from_file()`, then run in gdb, I see:

```
Breakpoint 1, vips_image_new_from_memory (data=0x13ff690, size=800, width=10, 
    height=10, bands=1, format=VIPS_FORMAT_DOUBLE) at image.c:1994
1994		vips_check_init();
(gdb) p ((double*)0x13ff690)[0]
$12 = 0.67904167149935779
```

So `vips_image_new_from_memory()` is being passed the address 0x13ff690 for the buffer, and that address indeed seems to contain a sensible number. If we next break on `vips_avg_build()` we see:

```
Breakpoint 3, vips_avg_build (object=0xb86f20) at avg.c:94
94		VipsStatistic *statistic = VIPS_STATISTIC( object ); 
Breakpoint 3, vips_avg_build (object=0xb86f20) at avg.c:94
(gdb) n
95		VipsAvg *avg = (VipsAvg *) object;
(gdb) p statistic->in->data
$16 = (VipsPel *) 0x13ff690 "\260+7\365\377\177"
```

So the input image to `vips_avg()` has the correct value in the data pointer, but:

```
(gdb) p ((double*)0x13ff690)[0]
$14 = 6.9533468685218769e-310
```

This area of memory has been modified! I guess by Python somehow, perhaps it has moved. 

Because the array no longer contains valid data, `vips_avg()` fails. 

Summary: I don't think `getbuffer` will work for this, we'll need a better way to get the underlying data out of numpy.

**Comment by jcupitt** [comment]
I tried a souble of other things. You can write:

```
addr, readonly = array.__array_interface__['data']
```

And now `addr` is the true underlying address of the array that we need to pass to vips, but it's an int, not a buffer, so we can't pass that to `vips_image_new_from_memory()`.

I'm not sure what the best solution is here. Probably you need to make a private copy of the numpy array as a binary string, but I don't know how to do that.

**Comment by jcupitt** [comment]
I think the best solution is to add a new constructor which takes a copy of the memory, rather than relying on the caller to pass or control a memory area. I've added `vips_image_new_from_memory_copy()` ... it works just like `.new_from_memory()`, but takes a private copy.

Here's a version of your test program that seems to work with git master vips:

```python
import numpy
import scipy.ndimage

from gi.repository import Vips

#import logging
#logging.basicConfig(level = logging.DEBUG)

def np_dtype_to_vips_format(np_dtype):
    '''
    Map numpy data types to VIPS data formats.

    Parameters
    ----------
    np_dtype: numpy.dtype

    Returns
    -------
    gi.overrides.Vips.BandFormat
    '''
    lookup = {
        numpy.dtype('int8'): Vips.BandFormat.CHAR,
        numpy.dtype('uint8'): Vips.BandFormat.UCHAR,
        numpy.dtype('int16'): Vips.BandFormat.SHORT,
        numpy.dtype('uint16'): Vips.BandFormat.USHORT,
        numpy.dtype('int32'): Vips.BandFormat.INT,
        numpy.dtype('float32'): Vips.BandFormat.FLOAT,
        numpy.dtype('float64'): Vips.BandFormat.DOUBLE
    }
    return lookup[np_dtype]

def np_array_to_vips_image(array):
    '''
    Convert a `numpy` array to a `Vips` image object.

    Parameters
    ----------
    nparray: numpy.ndarray

    Returns
    -------
    gi.overrides.Vips.image
    '''
    # Look up what VIPS format corresponds to the type of this np array
    vips_format = np_dtype_to_vips_format(array.dtype)
    dims = array.shape
    height = dims[0]
    width = 1
    bands = 1
    if len(dims) > 1:
        width = dims[1]
    if len(dims) > 2:
        bands = dims[2]
    img = Vips.Image.new_from_memory_copy(array.data,
        width, height, bands, vips_format)

    return img

array = numpy.random.random((10,10))
vips_image = np_array_to_vips_image(array)
print 'avg =', vips_image.avg()

array = scipy.ndimage.imread("test.jpg")
vips_image = np_array_to_vips_image(array)
print 'avg =', vips_image.avg()
vips_image.write_to_file("test2.jpg")
```

**Comment by jcupitt** [comment]
I meant to say, I found I didn't need the transpose / flip / rotate. It seems to load and save correctly without them.

**Comment by HackerMD** [comment]
Sweet! This works! Thank you!

**Comment by moon6pence** [comment]
Hi, all. I found this issue finally to use numpy arrays with vips. 

The function @jcupitt wrote works like a charm. How about update the [reference manual](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-python.html) to use `new_from_memory_copy()`? Or it would be better to provide the function `np_array_to_vips_image` in the reference manual. 

By the way, `new_memory_copy()` function takes several seconds for larger (over 10000x10000) images, maybe due to copying large memory buffer. Is there any way to use the buffer in numpy array directly? How about using `getstring()` instread of `getbuffer()`?

**Comment by jcupitt** [comment]
Good idea, I added a note to the docs.

Yes, `new_from_memory_copy()` will be slow for large images. I think you can use plain `new_from_memory()`, but you will need to be very careful to keep the memory area alive. 

It would be great to be able to use the buffer system to share memory between vips and numpy safely, but unfortunately I think this is not possible with gobject-introspection.

**Comment by mistahw00** [comment]
Hi all, thank you for the discussion here.

The conversion functions above were very helpful for me.

I had some trouble converting the numpy.ndarray form of a 3-channel RGB image into a Vips.Image object. 

I found out that `Vips.Image.new_from_memory_copy()` requires the input to be a simple 1D array in RGBRGB order.
I saw it here: https://lazka.github.io/pgi-docs/Vips-8.0/classes/Image.html#Vips.Image.new_from_memory

Perhaps this has already been fixed in the latest release (I'm currently using 8.0), but if it's okay, I'd like to post it here also so that other newbies like me could save a bit of time.

I added one more line of code in the existing `np_array_to_vips_image()` implementation to reshape the image array into a form processable by `Vips.Image.new_from_memory_copy()`.

I apologize beforehand for not formatting the code using markdown; I'm not yet comfortable using it.

...
bands = dims[2]

#added ---------------------------------------------
array = numpy.reshape(array, height * width * bands, order = 'C')
#------------------------------------------------------

img = Vips.Image.new_from_memory_copy(array.data,
    width, height, bands, vips_format)
...


Many thanks.

**Comment by jcupitt** [comment]
Hello @mistahw00, there's a new (much better) Python binding for libvips here:

https://github.com/jcupitt/pyvips/

It just installs with `pip install pyvips`.

The docs have some notes on swapping images between NumPy, PIL and pyvips:

https://jcupitt.github.io/pyvips/intro.html#numpy-and-pil

**Comment by jcupitt** [comment]
The new pyvips binding supports Python buffer objects, so you can now move images between these systems without copying them. It's much quicker!

**Comment by mistahw00** [comment]
Thanks for the reply and the suggestion, @jcupitt.
I'll keep that in mind the next time I use Vips.
Thank you for your contributions.
