### ISSUE TITLE
Black tiles when resizing with vips 8.1.1

### ISSUE THREAD

**Issue by jamestyrrell** [jcupitt/libvips#347]
When resizing certain JPGs with vips 8.1.1 on Ubuntu some tiles are black. It appears to be load related as I am unable to replicate on a lightly loaded machine. An example of this is presented below.

![resized-print-0-40-720x960](https://s3.amazonaws.com/jim.canva.com/black-tiles-resized.jpg)

The original image can be found [here](https://s3.amazonaws.com/jim.canva.com/black-tiles-original.jpg).

**Comment by jcupitt** [comment]
Oh dear, that's bad. What are you using to resize, James? Is this vipsthumbnail?

I'll see if I can make a stress test that reproduces this.

**Comment by jcupitt** [comment]
I have some more questions after looking through the code. Do you see anything on stdout or stderr? How many cores does this hardware have? Is it possible to find the exact pipeline of operations that's failing?

**Comment by jcupitt** [comment]
I made a tiny soak test:

https://gist.github.com/jcupitt/405cbc738ca446dc4a3e

Which might show it. I'll leave it running for a few hours.

**Comment by jcupitt** [comment]
The test finished in about 40m on OS X and on Ubuntu, with no reported errors :(

**Comment by jamestyrrell** [comment]
@jcupitt Thanks for looking into this, in the interim I have downgraded to 8.0.2 and the problem has gone away.

Yeh, I am using vipsthumbnail. There are a tonne of `stderr: vips warning: linecache: error reading tile 0x88: vipspng: out of order read at line 1272`, which appear to be red herrings, but no errors relating to JPGs. The machine is a heavily loaded 8 vCPU AWS machine.

**Comment by jcupitt** [comment]
The "out of order read" warnings are serious, unfortunately, they will give you black areas in the output.

I'll investigate some more.

**Comment by jcupitt** [comment]
A workaround would be to disable vips's threadpool. 

Try adding `--vips-concurrency=1` or setting the environment variable `VIPS_CONCURRENCY`to 1. This sets the number of image worker threads to 1, so they can't get out of order. 

It makes very little difference for image sizing anyway, most CPU time is spend in the image read library, which is always single-threaded. Turning it off can actually give a speed-up.

**Comment by jamestyrrell** [comment]
Interesting re. "out of order read" being serious, we have been getting since we start using vipsthumbnail and it hasn't been an issue.

What I also find strange is that the issue only appears on select JPGs, PNGs are not affected.

Thanks for the tip, I will try out `--vips-concurrency=1` in the next release.

**Comment by jamestyrrell** [comment]
Even with `vips-concurrency=1` I am still seeing errors like:
```vips warning: linecache: error reading tile 0x0: vipspng: out of order read at line 1152```

**Comment by jcupitt** [comment]
Oh rats, I'll keep digging. Thanks for your patience.

**Comment by jcupitt** [comment]
I think I might have it. I've made a test 8.1.2 with a new shrink operation:

http://www.vips.ecs.soton.ac.uk/development/vips-8.1.2.tar.gz

would you be able to test it? This is 8.1.1, but with the rewritten box shrink from 8.2 backported. The new shrinker is faster and more memory-efficient, but also much better at avoiding non-local references. It ought to be impossible to get out of order reads with it.

I could be wrong, of course :-(

**Comment by jcupitt** [comment]
I came up with a better way to think about the max size requirements of the cache in `vips_resize()`. Here's yet another test version which (I think?) should now not give the `out of order` error under any circumstances. 

http://www.vips.ecs.soton.ac.uk/development/vips-8.1.2-1.tar.gz

I'm probably wrong, of course :-(

**Comment by jcupitt** [comment]
Here's what I think was going wrong, for reference.

`vipsthumbnail` uses a total of three caches or tile buffers while running. 

1. Backing up the load operator, there's a line cache which keeps the last N scanlines as the image is read. N is enough to be able to run the output stage (stage 3 below) in the worst case. 

2. After the block shrink is another line cache. The block shrink can magnify thread stalls: if a thread stalls by 50 scanlines on the output stage and the block shrink is reducing the input image by a factor of 10, that stall will become a 500 line stall on the input image, possibly breaking the line cache in 1. There's also a subsequent filtering operation which can cause a further non-locality, so there's a bit extra. Again, this cache is sized large enough to run stage 3 below.

3. The output stage keeps two line buffers: one for the image write library to send to output, and one to fill with data from the worker threads. Tiles are allocated across each buffer: if the front buffer has been completely allocated and the back buffer has not yet been written by the image write library, tile allocation stalls until the delayed threads catch up.

What was happening: the cache sizing in 2. was not taking account of the second stage affine shrink, which can cause a further *3 non-locality. On a heavily-loaded system a thread could become delayed enough that the lines it needed from cache 2 were no longer available, and 3. would then see a black tile for that allocation.

Cache 2 is now sized taking account of the affine shrink as well. Phew!

**Comment by jcupitt** [comment]
Hi again, did you get a chance to test this fix? I'd like to get this into 8.2, due out RSN.

**Comment by jcupitt** [comment]
This is in 8.2, please reopen if that fails.
