### ISSUE TITLE
Drop JFIF and EXIF headers from Deep Zoom pyramids

### ISSUE THREAD

**Issue by bgilbert** [jcupitt/libvips#349]
Of the 1037 MB ZIP produced by

```shell
vips dzsave "CMU-3-40x - 2010-01-12 13.57.09.vms" cmu-3.zip --overlap=0
```

49.9 MB are used by EXIF headers and 4.5 MB are taken by JFIF headers.  It seems as though those headers shouldn't be necessary.  (OpenSeadragon renders just fine without them, at least in Chrome.)  Perhaps they should be disabled by default?  It's possible to disable the EXIF headers using `--suffix .jpeg[strip]` but that option doesn't disable the JFIF headers for some reason.

**Comment by jcupitt** [comment]
I agree `strip` should probably remove the JFIF stuff as well, I'll have a look. I'm not sure if strip could be made the default, I'll try to think about it.

**Comment by jcupitt** [comment]
Thanks for suggesting this Benjamin, you're right, it's sensible to have this as the default, and it's actually a very simple change. 

With these two patches, JFIF headers are removed with [strip] and tiles are always written stripped.
