### ISSUE TITLE
How to install libvips with OpenEXR support, sharing the libraries at runtime?

### ISSUE THREAD

**Issue by binarykitchen** [jcupitt/libvips#350]
If you look over at https://github.com/lovell/sharp/issues/304 you can see that I am experiencing issues running sharp because of this error

```
Error: libIlmImf.so.6: cannot open shared object file: No such file or directory
```

I installed libvips with `sudo apt-get install libvips-dev` on Ubuntu 15.04 but that does not work and gives the above error.

When I try just to install `libvips` then I get this warning

```
$ sudo apt-get install libvips
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libvips is a virtual package provided by:
  libvips38 7.40.6-2build2~ubuntu14.04.1~ppa1
  libvips38v5 7.40.6-2ubuntu2
You should explicitly select one to install.

E: Package 'libvips' has no installation candidate
```

Clueless here what to do. Any hints?

**Comment by jcupitt** [comment]
How weird, I'm on 15.10 now but I'm pretty sure I was using vips on 15.04 without issue. Perhaps it's been broken in a recent update?

I'll install 15.04 in a VM and check.

**Comment by lovell** [comment]
`7.40.6-2build2~ubuntu14.04.1~ppa1` suggests this is an Ubuntu machine that was upgraded from 14.04 to 15.04. If so, you'll need to disable any old 14.04-only PPAs.

**Comment by jcupitt** [comment]
I tried a fresh 15.04 in a VM and it seemed to work. There's `libvips` and `libvips38`, the 38 version is compatible with an older library ABI, but otherwise there didn't seem to be anything odd.

As @lovell says, do you have any other PPAs added to your system? Could one of them have a conflict?

**Comment by binarykitchen** [comment]
Thanks guys. Correction: I was on Ubuntu 15.04 when I installed libvips and then did a `do-release-upgrade` for Ubuntu 15.10 and then this happened.

How can I find out the PPAs associated to libvips38 and libvips38v5?

**Comment by lovell** [comment]
@binarykitchen http://askubuntu.com/questions/307/how-can-ppas-be-removed/310#310 might help.

**Comment by binarykitchen** [comment]
Thanks. No luck with ppa-purge. Tried `sudo ppa-purge 7.40.6-2build2~ubuntu14.04.1~ppa1` but no luck. Also tried many other combinations. All fail. Weird.

**Comment by binarykitchen** [comment]
Ah, I finally found the bad PPA package and removed it. Now, with `apt-get install libvips` I could install it.

It is this one version I am having:

```
$ vips --vips-version
libvips 8.1.1-Tue Nov 17 21:12:23 NZDT 2015
```

But still, I see the same error:
```
Error: libIlmImf.so.6: cannot open shared object file: No such file or directory
```

Hmmm ....

**Comment by jcupitt** [comment]
That looks like a vips you've built yourself -- the system vips in 15.04 is 7.40.6 (I think?).

Remove your own vips and you should be able to use the system one. Or you could rebuild the home-made one, that might work now.

**Comment by binarykitchen** [comment]
Hmmm, good point. Did I ever built one myself? Do not remember. If so, how do I remove it?

**Comment by jcupitt** [comment]
Try `which` and `ldd` to see what binaries and libraries you are picking up. 

```
$ which vips
```

will give the path of the vips executable you are seeing, and:

```
$ ldd $(which vips)
```

will run `ldd` on that file to display the paths of all the dynamic libraries it is using. It's a long list -- you can search for just the vips ones:

```
$ ldd $(which vips) | grep vips
```

To uninstall, if there's nothing else in `/usr/local/` you are using, you can just nuke the whole thing. Otherwise you'll have to pick over the area removing files by hand. If you get rid of anything in `/usr/local/bin` and `/usr/local/lib` with vips in the name, that should be enough. 

Install the system `libvips-tools` to get the system `vips` program installed.

**Comment by binarykitchen** [comment]
Thank you so much @jcupitt - your support is impressive. It worked. But I found few more fragments with the `find / | grep -iname "vips"` command and deleted these as well.

My built libvips is in Nirvana and the one version installed via apt-get is fine now.

But now, when I re-install the sharp node package using libvips, I see a new error

```
> sharp@0.11.4 install /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp
> node-gyp rebuild

Package openslide was not found in the pkg-config search path.
Perhaps you should add the directory containing `openslide.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openslide', required by 'vips', not found
gyp: Call to 'PKG_CONFIG_PATH=":$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --cflags vips glib-2.0' returned exit status 1. while trying to load binding.gyp
```
Hmmm, what the heck?

@lovell any ideas?

**Comment by binarykitchen** [comment]
Never mind. `apt-get install libvips-dev` solved the above. All problems solved. Phew!

Thanks again guys, you two. I wouldn't have got such good advice if it were proprietary software.

**Comment by jcupitt** [comment]
I'll close if this is done. Glad it's working!
