### ISSUE TITLE
How can I manually uninstall libvips on Ubuntu 15.10 without make?

### ISSUE THREAD

**Issue by binarykitchen** [jcupitt/libvips#351]
Because I built it a while ago and do not have the project folder and its `make` anymore.

Thanks for any clues

**Comment by binarykitchen** [comment]
FYI I have these locations

```
$ sudo find / -iname vips
/usr/local/include/vips
/usr/local/include/vips/vips
/usr/local/bin/vips
``

**Comment by jcupitt** [comment]
You could install the same version again to the same prefix, then do `sudo make uninstall`. 

You could also wipe `/usr/local/` completely and rebuild it with just the packages you want. 

I tend to install vips to a private prefix, eg. `./configure --prefix=/home/john/vips`, and add the `~/vips` area to my environment. It means I can cleanly wipe and rebuild by just removing that directory.

**Comment by binarykitchen** [comment]
Good idea. Will remember that for next time. Thanks again!
