### ISSUE TITLE
Join or insertplace ?

### ISSUE THREAD

**Issue by geektortoise** [jcupitt/libvips#354]
Hello.

I'm a newbie with the image manipulation so, I'm sorry of this question seems stupid. :-)

I have a lot of jpeg tiles to merge into one big image (tiff) (no overlapping).
I have a working way to do it but it is slow and I wonder if it will be faster with another command.

My way : 
1. I get the height and width of the final image.
2. I create a big black image with the command "vips im_black ..."
3. For each tile (and this is the slowest part) I use "vips im_insert_place ..." (I saw it is deprecated so I will change to im_draw_image if there is nothing better) at the right X and Y
4. At the end, as I want a tiff, I run "vips im_vips2tiff ..."

But I see other functions that are maybe more appropriate :
* vips join as in Issue #120 
* [vips_merge] (http://www.vips.ecs.soton.ac.uk/supported/7.42/doc/html/libvips/libvips-mosaicing.html#vips-merge) (What's the difference with vips join ?)

As it is not inplace, I think I could try to join all the tiles of the same rows (with multi-threading) then join all the rows.

So, my question is "What's the more efficient way to do it ? Merge ? join ? Or it is not more efficient than insertplace ?"

Thank you.

Have a nice day !

**Comment by jcupitt** [comment]
Hi, yes, you could go a lot faster if you use Python, would that be possible?

Here's a Python program which does more or less what you need:

```python
#!/usr/bin/python

import sys

from gi.repository import Vips

if len(sys.argv) < 4:
    print "usage: %s n image-out image1 image2 ..." % sys.argv[0]
    print "   make an n x n grid of images"
    sys.exit(1)


size = int(sys.argv[1])
outfile = sys.argv[2]
tile = Vips.Image.new_from_file(sys.argv[3])

img = Vips.Image.black(size * tile.width, size * tile.height)

i = 3
for y in range(size):
    for x in range(size):
        tile = Vips.Image.new_from_file(sys.argv[i], 
                                        access = Vips.Access.SEQUENTIAL_UNBUFFERED)
        i += 1
        img = img.insert(tile, x * tile.width, y * tile.height)

img.write_to_file(outfile)
```

Run like this:

```
$ time ./join2.py 6 x.v join/*
memory: high-water mark 80.41 MB
real	0m0.905s
user	0m1.344s
sys	0m0.800s
$ vipsheader join/1.tif
join/1.tif: 2000x2500 uchar, 3 bands, srgb, tiffload
$ vipsheader x.v
x.v: 12000x15000 uchar, 3 bands, srgb, tiffload
```

That's joining 36 2000x2500 pixel tif images to make a 12,000 x 15,000 pixel image. 

You'll probably need to change strategy a bit if you have more than 1,000 or so images.

**Comment by geektortoise** [comment]
Cool.
Thank you for your fast answer ! :-)
