### ISSUE TITLE
vips dzsave saves tiles with incorrect size because it ignores the overlap parameter

### ISSUE THREAD

**Issue by erdmann** [jcupitt/libvips#357]
I'm using a recent version from git (ff1dd39432672d0fb36698f83e5090faeebcb173).  There is apparently a regression where the size of deepzoom-flavored tiles is incorrect, because, although it writes the correct overlap value into the .dzi file it creates, the tiles it creates always have overlap=0.

This differs with its former behavior and with that of OpenSlide.

For a tile-size of 256 and an overlap of 1, I believe internal (non-edge) tiles should have pixel dimensions of 258x258, while edge tiles should have sizes of 257 on their respective edges.  This is the behavior of OpenSlide, and was the former behavior of dzsave.

Here's a transcript that shows the problem:

First I make a tiny 1024x1024 image:

    erdmann@bosch:~$ vips black sample.tif 1024 1024

Then save this to deepzoom format

    erdmann@bosch:~$ vips dzsave sample.tif sample --tile-size=256 --overlap=1

The following .dzi file is correct for the options I specified:

    erdmann@bosch:~$ cat sample.dzi
    <?xml version="1.0" encoding="UTF-8"?>
    <Image xmlns="http://schemas.microsoft.com/deepzoom/2008"
      Format="jpeg"
      Overlap="1"
      TileSize="256"
      >
      <Size 
        Height="1024"
        Width="1024"
      />
    </Image>

The problem is seen here, looking at the full-resolution corner tile, which should be 257x257:

    erdmann@bosch:~$ identify sample_files/10/0_0.jpeg 
    sample_files/10/0_0.jpeg JPEG 256x256 256x256+0+0 8-bit PseudoClass 256c 1.08KB 0.000u 0:00.000

And here, where it should be 258x258:

    erdmann@bosch:~$ identify sample_files/10/1_1.jpeg 
    sample_files/10/1_1.jpeg JPEG 256x256 256x256+0+0 8-bit PseudoClass 256c 1.08KB 0.000u 0:00.000

To compare, I then save the same image specifying overlap of zero, which again yields a correct .dzi file:

    erdmann@bosch:~$ vips dzsave sample.tif sample_no_overlap --tile-size=256 --overlap=0
    erdmann@bosch:~$ cat sample_no_overlap.dzi 
    <?xml version="1.0" encoding="UTF-8"?>
    <Image xmlns="http://schemas.microsoft.com/deepzoom/2008"
      Format="jpeg"
      Overlap="0"
      TileSize="256"
      >
      <Size 
        Height="1024"
        Width="1024"
      />
    </Image>

The following shows that the tiles it is creating are identical between the overlap=1 and the overlap=0 setting:

    erdmann@bosch:~$ diff sample_files/10/1_1.jpeg sample_no_overlap_files/10/1_1.jpeg 

For comparison, here is what is created by OpenSlide:

    erdmann@bosch:~$ src/openslide-python/examples/deepzoom/deepzoom_tile.py sample.tif --size=256 --overlap=1 --output=sample_openslide
    Tiling slide: wrote 29/29 tiles
    erdmann@bosch:~$ cat sample_openslide.dzi 
    <?xml version='1.0' encoding='UTF-8'?>
    <Image Format="jpeg" Overlap="1" TileSize="256" xmlns="http://schemas.microsoft.com/deepzoom/2008"><Size Height="1024" Width="1024" /></Image>

    erdmann@bosch:~$ identify sample_openslide_files/10/0_0.jpeg 
    sample_openslide_files/10/0_0.jpeg JPEG 257x257 257x257+0+0 8-bit DirectClass 1.78KB 0.000u 0:00.000
    erdmann@bosch:~$ identify sample_openslide_files/10/1_1.jpeg 
    sample_openslide_files/10/1_1.jpeg JPEG 258x258 258x258+0+0 8-bit DirectClass 1.78KB 0.000u 0:00.009

Additionally, note that the documentation for dzsave says it uses a default of 0 pixels of overlap, but that it writes an overlap value of 1 pixel into the .dzi files it saves:

    erdmann@bosch:~$ vips dzsave
    save image to deep zoom format
    usage:
       dzsave in filename
    where:
       in           - Image to save, input VipsImage
       filename     - Filename to save to, input gchararray
    optional arguments:
       layout       - Directory layout, input VipsForeignDzLayout
    			default: dz
    			allowed: dz, zoomify, google
       suffix       - Filename suffix for tiles, input gchararray
       overlap      - Tile overlap in pixels, input gint
    			default: 0
    			min: 0, max: 8192
       tile-size    - Tile size in pixels, input gint
    			default: 256
    			min: 1, max: 8192
       centre       - Center image in tile, input gboolean
    			default: false
       depth        - Pyramid depth, input VipsForeignDzDepth
    			default: onepixel
    			allowed: onepixel, onetile, one
       angle        - Rotate image during save, input VipsAngle
    			default: d0
    			allowed: d0, d90, d180, d270
       container    - Pyramid container type, input VipsForeignDzContainer
    			default: fs
    			allowed: fs, zip
       properties   - Write a properties file to the output directory, input gboolean
    			default: false
       strip        - Strip all metadata from image, input gboolean
    			default: false
       background   - Background value, input VipsArrayDouble
    operation flags: sequential-unbuffered nocache 
    erdmann@bosch:~$ v dzsave sample.tif sample_defaults
    vips temp-1: 1024 x 1024 pixels, 12 threads, 128 x 128 tiles, 512 lines in buffer
    vips temp-1: done in 0.0801s    

Note: 1 pixel overlap indicated in the .dzi file (though as shown above, it really is 0 pixels in the tiles).
      
    erdmann@bosch:~$ cat sample_defaults.dzi 
    <?xml version="1.0" encoding="UTF-8"?>
    <Image xmlns="http://schemas.microsoft.com/deepzoom/2008"
      Format="jpeg"
      Overlap="1"
      TileSize="256"
      >
      <Size 
        Height="1024"
        Width="1024"
      />
    </Image>

Many thanks in advance.

**Comment by jcupitt** [comment]
Hi @erdmann that's a great bug report, think you very much. Yes, the dzsave overlap handling was revised here: 

https://github.com/jcupitt/libvips/issues/326

There was a problem with overlaps in google maps mode. I obviously broke it for deepzoom :-( I'll investigate.

**Comment by jcupitt** [comment]
I think the overlap parameter is working, it's just wrong. If I run:

```
$ vips dzsave k2.jpg x --suffix .png --depth one
```

I get a set of 256 x 256 tiles with the tiles positioned in steps of 255, that is, with one column of pixels in common at edges. So the right edge of the first tiles should equal the left edge of the second:

```
$ vips crop x_files/0/0_0.png left.v 255 0 1 256
$ vips crop x_files/0/1_0.png right.v 0 0 1 256
$ vips subtract left.v right.v diff.v
$ vips abs diff.v adiff.v
$ vips max adiff.v 
0.000000
```

However this is completely misunderstanding the deepzoom spec, where overlap is really more like margin or border, and tile-size is more like tile-step. I'll fix it.

**Comment by jcupitt** [comment]
I think git master is fixed now, and I updated the test suite too. Hopefully this can't happen again.

Sorry for the mixup, this was my fault. The last time I revised dzsave I simplified the extremely complicated overlap handling, but in the process misremembered the confusing definitions of exactly what `overlap` and `tile_size` meant.

Thank you very much for the detailed report @erdmann

**Comment by jcupitt** [comment]
I meant to say, I don't suppose you'd be able to test this? It'd be great to have it double-checked.

**Comment by erdmann** [comment]
On the cases I just tested it seems to work for me.  Many thanks for the fast response!
