### ISSUE TITLE
Export OpenSlide properties with tiffsave as OME metadata

### ISSUE THREAD

**Issue by AndreasSchmid1** [jcupitt/libvips#358]
Does it make sense to optionally export OpenSlide image properties as metadata in form of a OME xml when using tiffsave?
I found a very similar feature request ralated to the dzsave command here https://github.com/jcupitt/libvips/issues/137
As an addition to the advantages described in issue 137 an OME-TIFF feature would increase the compatibility and push OME as an "open" whole slide imaging format.

**Comment by jcupitt** [comment]
Hi @AndreasSchmid1 I looked up OME XML:

https://www.openmicroscopy.org/site/support/ome-model/ome-xml/

The metadata stuff sounds useful. I'd think it would be fairly simple to make a basic OME XML file from the XML we have now with XSLT or whatever, though I've never actually done anything with xslt. 

Their scheme seems extremely unsuitable for image storage, though it sounds like they are considering a high-performance version.

I've leave this open as a reminder to look at xslt.

**Comment by AndreasSchmid1** [comment]
Hi @jcupitt thank you for looking at it.

The OME-XML is so comprehensive that it maybe would make sense to autogenerate a OME-XML from the OME-XSD and just modify the relevant nodes.

What exactly do you mean by unsuitable? I converted the CMU-2.ndpi openslide sample to an ome tif file with the open micrsocopy command line tools (“$ bfconvert -compression JPEG CMU-2.ndpi output.ome.tiff”.) It took a good half hour for a 300mb file but in the end I got a ome.tif with a simular but somehow different image data structure than the openslide generic tiled tif and the OME-XML inside the imagedescription tag.

As a probably more quick feature. Would it be possible to enable the --properties parameter also with the tiffsave command to save the already developed openslideproperties.xml to the imagedescription tag of the tif file?

**Comment by jcupitt** [comment]
Oh that sounds more reasonable. I saw the stuff in the spec about embedding image pixel data inside the XML as deflate-compressed base64, which will absolutely not work for large images. Attaching xml to a standard tiff sounds much better.

Yes, the imagedescription sounds pretty easy, I'll have a look.

**Comment by AndreasSchmid1** [comment]
Totally agree. 
I guess they just added this to allow the storage of image metadata (like icons, overview image,etc) inside the ome-xml.

Ok, thank you very much!

**Comment by jcupitt** [comment]
I added a --properties flag to tiffsave:

https://github.com/jcupitt/libvips/commit/73436ddfc2c39fd9371f29a3dc6077cfc2bc3c0d

So now:

```
$ vips copy wtc.tif x.tif[properties]
john@mm-jcupitt5 /data/john/pics $ vipsheader --field image-description x.tif
<?xml version="1.0"?>
<image xmlns="http://www.vips.ecs.soton.ac.uk/dzsave" date="2015-12-21T14:45:58.521081Z" version="8.2.0">
  <properties>
    <property>
      <name>width</name>
      <value type="gint">9372</value>
    </property>
    <property>
      <name>height</name>
      <value type="gint">9372</value>
    </property>
.... etc.
```

And the other patch makes `TIFFTAG_IMAGEDESCRIPTION` available to the various bindings and copies it between TIFF files.

**Comment by AndreasSchmid1** [comment]
That was quick! Thank you!

**Comment by jcupitt** [comment]
This is in 8.2, so I'll close.
