### ISSUE TITLE
vips_buffer_dump_all() removed from ABI

### ISSUE THREAD

**Issue by bgilbert** [jcupitt/libvips#361]
3d163bb4 dropped `vips_buffer_dump_all()` from the build.  This is technically an ABI break, though I'm not sure how public the functions in `private.h` are meant to be.  Was the removal intentional?  It looks as though the function could just be replaced by an empty stub when `!DEBUG`.

Noticed by [abi-compliance-checker](http://ispras.linuxbase.org/index.php/ABI_compliance_checker).

**Comment by jcupitt** [comment]
Hi, yes, that's an internal debugging thing, it prints a table of active pixel buffers plus some usage stats. It was always compiled into the library in 8.1, but I've now moved it inside `DEBUG` to knock a few bytes off the install size. 

Do you think we need a compatibility stub?

**Comment by jcupitt** [comment]
OK ... added a stub and bumped to 8.2.1. Thanks for the report and happy new year.
