### ISSUE TITLE
Sparc64 build error

### ISSUE THREAD

**Issue by gcsideal** [jcupitt/libvips#364]
Building VIPS 8.2.1 on Sparc64 fails with:
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I../../libvips/include -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -fopenmp -I/usr/lib/sparc64-linux-gnu/hdf5/serial/include -I/usr/lib/sparc64-linux-gnu/glib-2.0/include -I/usr/include/sparc64-linux-gnu//ImageMagick-6 -I/usr/include/sparc64-linux-gnu -I/usr/include/pango-1.0 -I/usr/include/orc-0.4 -I/usr/include/openslide -I/usr/include/libxml2 -I/usr/include/libpng12 -I/usr/include/libgsf-1 -I/usr/include/libexif -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/include/freetype2 -I/usr/include/OpenEXR -I/usr/include/ImageMagick-6 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -c lbb.cpp  -fPIC -DPIC -o .libs/lbb.o
lbb.cpp: In function 'void vips_interpolate_lbb_interpolate(VipsInterpolate*, void*, VipsRegion*, double, double)':
lbb.cpp:855:1: error: unable to find a register to spill in class 'FP_REGS'
 }
 ^
lbb.cpp:855:1: error: this is the insn:
(insn 1538 1595 1606 5 (set (reg:DF 64 %f32 [orig:2603 D.24887 ] [2603])
        (float:DF (reg:SI 3 %g3 [orig:2604 MEM[base: p_122, index: _3446, offset: 0B]+-3 ] [2604]))) lbb.cpp:746 155 {floatsidf2}
     (expr_list:REG_DEAD (reg:SI 3 %g3 [orig:2604 MEM[base: p_122, index: _3446, offset: 0B]+-3 ] [2604])
        (expr_list:REG_EQUIV (mem:DF (plus:DI (reg/f:DI 14 %sp)
                    (const_int 2383 [0x94f])) [0  S8 A64])
            (nil))))
lbb.cpp:855: confused by earlier errors, bailing out

Full build log: https://buildd.debian.org/status/fetch.php?pkg=vips&arch=sparc64&ver=8.2.1-1&stamp=1452536741

**Comment by jcupitt** [comment]
I don't know enough about gcc internals, but there's a lot of `inline` in that file, could it be trying to allocate registers for the whole file in one go?

You could try removing the `inline` declarations and see if it fixes it.

**Comment by jcupitt** [comment]
Sorry, I don't think I can fix this, without help, I'll close.
