### ISSUE TITLE
How can I link vips-dev-w64-8.2(or any other 8.x libvips) statically to Qt/MinGW 4.9.2 project?

### ISSUE THREAD

**Issue by Belgorodsky** [jcupitt/libvips#365]
How can I link vips-dev-w64-8.2(http://www.vips.ecs.soton.ac.uk/supported/current/win32/) or any other 8.x libvips statically to Qt 5.5.1 statically builded  by MinGW 4.9.2 project(https://github.com/RISK46kaf/Practise/tree/processes/shchukin/ImageCutter) on Windows 7 64 bit (and late)?

**Comment by jcupitt** [comment]
Hi @Belgorodsky, it should work, I think. What error are you seeing?

**Comment by Belgorodsky** [comment]
Hi @jcupitt,thanks for answering.

Make
[Makefile.Release.txt](https://github.com/jcupitt/libvips/files/87005/Makefile.Release.txt)
[errors.txt](https://github.com/jcupitt/libvips/files/87007/errors.txt)

**Comment by jcupitt** [comment]
Your errors.txt is missing the error message. What happens if you copy-paste that line to the command prompt?

I would try making a tiny "hello world" program and building that first. Something like:

```C
/* compile with
 *
 * gcc -Wall hello8.c `pkg-config vips --cflags --libs`
 */
 
#include <stdio.h>
 
#include <vips/vips.h>
 
int
main (int argc, char **argv)
{
  VipsImage *im;
  double avg;
 
  if (VIPS_INIT (argv[0]))
    vips_error_exit ("unable to start VIPS");
 
  if (argc != 2)
    vips_error_exit ("usage: %s <filename>", g_get_prgname ());
 
  if (!(im = vips_image_new_from_file (argv[1], NULL)))
    vips_error_exit ("unable to open");
  if (vips_avg (im, &avg, NULL))
    vips_error_exit ("unable to find avg");
  g_object_unref (im);
 
  printf ("Hello World!\nPixel average of %s is %g\n", argv[1], avg);
 
  return (0);
}
```

To compile on Windows with mingw, you'll need something like:

```
gcc \
    -mms-bitfields -march=i686 \
    -I/home/john/GIT/build-win32/7.32/inst/include \
    -I/home/john/GIT/build-win32/7.32/inst/include/glib-2.0 \
    -I/home/john/GIT/build-win32/7.32/inst/lib/glib-2.0/include \
    hello8.c \
    -L/home/john/GIT/build-win32/7.32/inst/lib \
    -lvips -lz -ljpeg -lxml2 -lfftw3 -lm -lMagickWand -llcms2 \
    -lopenslide -lcfitsio -lpangoft2-1.0 -ltiff -lpng14 -lexif \
    -lMagickCore -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 \
    -lgmodule-2.0 -lgthread-2.0 -lglib-2.0 -lintl \
    -o hello.exe
```

Once that's working, try to get it linking statically, then try with `g++`, then get cmake to generate the right stuff.

**Comment by Belgorodsky** [comment]
C:/Qt/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lxml2
C:/Qt/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lfftw3
C:/Qt/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lopenslide 
C:/Qt/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lpng14
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [release/ImageCutter.exe] Error 1
 mingw32-make: *** [release] Error 2

**Comment by Belgorodsky** [comment]
@jcupitt i'm asking abuot 8.x libVips

**Comment by jcupitt** [comment]
Sorry, now I look at the zip I see there are no static libraries, only DLLs. I'll see if I can make a static (or semi-static?) `libvips.a` for you.

Are you certain you need a static libvips? What are you trying to achieve?

**Comment by jcupitt** [comment]
I had a look, and quite a few of the projects that vips depends on, such as libxml2, do not distribute static libraries. Making the entire stack static would be quite a lot of work: we'd need to build our own versions of another 14 packages, I think. 

I don't think I have the time to do this. Is there some other way you can get the effect you need?

**Comment by Belgorodsky** [comment]
I was trying to build static, because I have some problem with vips-dev-... package dll. Because of I don't know  which compiler build vips-dev-...

**Comment by jcupitt** [comment]
Yes, vips-dev is built by this thing:

https://github.com/jcupitt/build-win64

So it's built with mingw. You should be able to link to the C++ DLL from mingw on win7, or if you use the C API you can use any compiler.

**Comment by Belgorodsky** [comment]
I got "the procedure entry point __gxx_personality_v0 could not be located in the dynamic link library libstdc++6" error and copy MinGW libstdc++6.dll to executable file directory can't resolve it.

**Comment by jcupitt** [comment]
I'm using mingw 5.2.1 so I guess the compilers are not compatible. 

You can either use the C API, which is easy, though a bit verbose, or you can rebuild just the C++ part of libvips. This is what people who use MSVC do, it should be very easy, there are just four .cpp files you need to copy into your project:

https://github.com/jcupitt/libvips/tree/master/cplusplus

You have the matching headers already in the vips-dev zip.

**Comment by jcupitt** [comment]
Hi, were you able to make progress on this?

**Comment by jcupitt** [comment]
I'll close, please reopen if this issue is still important.

**Comment by cup** [comment]
https://github.com/libvips/libvips/issues/1067
https://github.com/libvips/libvips/issues/1079
https://github.com/libvips/libvips/issues/280
https://github.com/libvips/libvips/issues/365

**Comment by cup** [comment]
https://github.com/cygwinports/mingw64-x86_64-libxml2/issues/1
https://github.com/libvips/libvips/issues/1271
https://github.com/libvips/libvips/issues/365
