### ISSUE TITLE
vips subsample runs extremely slowly on non-direct-access input files

### ISSUE THREAD

**Issue by erdmann** [jcupitt/libvips#370]
Recently, `vips subsample` has been taking an extremely long time to process even tiny images, except, apparently, images in the .v format or uncompressed tiled tiff files.

Here are some demonstrations of the problem using a tiny image.  First, I make a 6x6 black image in several formats, including tif with and without tiling:

    $ vips black black.tif 6 6 # n.b. not tiled
    $ vips black black_tiled.tif[tile] 6 6
    $ vips black black.jpg 6 6
    $ vips black black.png 6 6
    $ vips black black.v 6 6

Then I attempt to subsample it into a 2x2 image:

    $ time vips subsample black.tif reduced_black.tif 3 3

    real	1m0.046s
    user	0m0.028s
    sys	0m0.035s

    $ time vips subsample black.png reduced_black.tif 3 3

    real	1m0.052s
    user	0m0.034s
    sys	0m0.046s

    $ time vips --vips-progress --vips-info --vips-novector --vips-concurrency=1 subsample black.jpg reduced_black.tif 3 3
    vips temp-1: 2 x 2 pixels, 1 threads, 2 x 16 tiles, 512 lines in buffer
    vips temp-1: done in 60s          

    real	1m0.057s
    user	0m0.035s
    sys	0m0.045s

The following behave as expected, however:

    $ time vips subsample black.v reduced_black.tif 3 3

    real	0m0.044s
    user	0m0.021s
    sys	0m0.029s

    $ time vips subsample black_tiled.tif reduced_black.tif 3 3

    real	0m0.052s
    user	0m0.025s
    sys	0m0.045s

Machine info:

    $ uname -a
    Linux bosch 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I'm not sure the best approach to debug this, but maybe the following is helpful.  If I run `strace` to attach to the running `vips` process during the one-minute wait for it to finish, I obtain something like the following.  It spends virtually all of its time in `FUTEX_WAIT_PRIVATE`, and the process consumes essentially zero CPU during that time.

    # strace -p $(pgrep vips)
    Process 5228 attached
    futex(0x130f624, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
    futex(0x130f5c0, FUTEX_WAKE_PRIVATE, 1) = 0
    futex(0x130a774, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x130a770, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
    futex(0x130a710, FUTEX_WAKE_PRIVATE, 1) = 1
    futex(0x130eb44, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x130eb40, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
    futex(0x130eae0, FUTEX_WAKE_PRIVATE, 1) = 1
    lseek(3, 0, SEEK_END)                   = 8
    write(3, "\0\0\0\0", 4)                 = 4
    lseek(3, 0, SEEK_END)                   = 12
    lseek(3, 4, SEEK_SET)                   = 4
    write(3, "\f\0\0\0", 4)                 = 4
    lseek(3, 198, SEEK_SET)                 = 198
    write(3, "\377\377\377\377\fy<\36", 8)  = 8
    lseek(3, 206, SEEK_SET)                 = 206
    write(3, "\377\377\377\377\fy<\36", 8)  = 8
    lseek(3, 12, SEEK_SET)                  = 12
    write(3, "\17\0\0\1\3\0\1\0\0\0\2\0\0\0\1\1\3\0\1\0\0\0\2\0\0\0\2\1\3\0\1\0"..., 186) = 186
    close(3)                                = 0
    close(4)                                = 0
    munmap(0x7f3ab751a000, 4096)            = 0
    exit_group(0)                           = ?
    +++ exited with 0 +++

Please let me know if you need additional information to diagnose the problem, and many thanks in advance.

**Comment by jcupitt** [comment]
How strange! I'll have a look, thanks for the report, @erdmann.

**Comment by jcupitt** [comment]
I think that's fixed it. It was:

```
$ time vips subsample black.tif reduced_black.tif 3 3
real	1m0.030s
user	0m0.020s
sys	0m0.008s
```

I now see:

```
$ time vips subsample black.tif reduced_black.tif 3 3
real	0m0.030s
user	0m0.020s
sys	0m0.008s
```

The problem was sequential mode: the manager operation became confused when subsample skipped ahead and missed out some scanlines. It thought a thread had run ahead and needed to be stalled until the missing lines were requested.

This change is in 8.2.2, I'll make a new release in a few days.

**Comment by jcupitt** [comment]
... if you have a chance to test this fix, that would be great. Thanks!

**Comment by erdmann** [comment]
It works for me now.  Thanks!

I was recently having similar issues with vipsthumbnail, though I haven't had a chance to test it again.  Is this likely the same root cause?

**Comment by jcupitt** [comment]
Glad it's working! I'll close. Thank you very much for reporting this dumbness. 

Yes, `vipsthumbnail` has triggered this behaviour at various points in its life :-( it's a hard thing to prevent. The current version has been revised (yet again) and it should now be impossible for this to happen. I hope.

If it does misbehave, please open an issue.
