### ISSUE TITLE
vips frees invalid pointer after attaching a color profile to a TIFF image

### ISSUE THREAD

**Issue by erdmann** [jcupitt/libvips#371]
After attaching a color profile to a TIFF file, `vips` attempts to free an invalid pointer.  Note, however, that the file it creates is apparently fine in every way, so this is not urgent since the only real effect is the need to work around the error condition when using vips in Makefiles, e.g.
 
    $ vips --vips-leak black test_attach.tif[profile=eciRGB_v2.icc] 1 1 --bands=3
    *** Error in `vips': free(): invalid pointer: 0x0000000002489b60 ***
    Aborted

    $ exiftool test_attach.tif 
    ExifTool Version Number         : 9.46
    File Name                       : test_attach.tif
    Directory                       : .
    File Size                       : 2.2 kB
    File Modification Date/Time     : 2016:01:22 16:26:42+01:00
    File Access Date/Time           : 2016:01:22 16:24:04+01:00
    File Inode Change Date/Time     : 2016:01:22 16:26:42+01:00
    File Permissions                : rw-r--r--
    File Type                       : TIFF
    MIME Type                       : image/tiff
    Exif Byte Order                 : Little-endian (Intel, II)
    Image Width                     : 1
    Image Height                    : 1
    Bits Per Sample                 : 8 8 8
    Compression                     : Uncompressed
    Photometric Interpretation      : RGB
    Strip Offsets                   : 8
    Orientation                     : Horizontal (normal)
    Samples Per Pixel               : 3
    Rows Per Strip                  : 128
    Strip Byte Counts               : 3
    X Resolution                    : 10
    Y Resolution                    : 10
    Planar Configuration            : Chunky
    Resolution Unit                 : cm
    Sample Format                   : Unsigned; Unsigned; Unsigned
    Profile CMM Type                : ADBE
    Profile Version                 : 2.4.0
    Profile Class                   : Display Device Profile
    Color Space Data                : RGB
    Profile Connection Space        : XYZ
    Profile Date Time               : 2007:03:02 10:07:41
    Profile File Signature          : acsp
    Primary Platform                : Unknown ()
    CMM Flags                       : Not Embedded, Independent
    Device Manufacturer             : 
    Device Model                    : 
    Device Attributes               : Reflective, Glossy, Positive, Color
    Rendering Intent                : Perceptual
    Connection Space Illuminant     : 0.9642 1 0.82491
    Profile Creator                 : bICC
    Profile ID                      : 9c6d34a5ada445f6146d98b0510c126d
    Profile Copyright               : Copyright (C) 2007 by Color Solutions, All Rights Reserved. License details can be found on: http://www.eci.org/eci/en/eciRGB.php
    Profile Description             : eciRGB v2
    Media White Point               : 0.9642 1 0.82491
    Red Tone Reproduction Curve     : (Binary data 1412 bytes, use -b option to extract)
    Green Tone Reproduction Curve   : (Binary data 1412 bytes, use -b option to extract)
    Blue Tone Reproduction Curve    : (Binary data 1412 bytes, use -b option to extract)
    Red Matrix Column               : 0.65027 0.32028 0
    Green Matrix Column             : 0.17804 0.60205 0.06783
    Blue Matrix Column              : 0.13588 0.07767 0.75708
    Image Size                      : 1x1

In case the particulars of the color-management and other libraries are relevant, here's the output of `configure`:

    * build options
    native win32:				no
    native OS X:				no
    open files in binary mode: 		no
    enable debug:				no
    build deprecated components:		yes
    build docs with gtkdoc:			no
    gobject introspection: 			yes
    build vips7 Python binding:		yes
    install vips8 Python overrides:		yes
      (requires pygobject-3.12.0 or later)
    
    * optional dependencies
    use fftw3 for FFT: 			yes
    Magick package: 			MagickWand
    file import with libMagick: 		yes
    accelerate loops with orc: 		yes
      (requires orc-0.4.11 or later)
    ICC profile support with lcms: 		yes (lcms2)
    file import with OpenEXR: 		yes
    file import with OpenSlide:		yes
      (requires openslide-3.3.0 or later)
    file import with matio: 		yes
    file import with cfitsio: 		yes
    file import/export with libwebp:	yes
    text rendering with pangoft2: 		yes
    file import/export with libpng: 	yes (pkg-config libpng >= 1.2.9)
      (requires libpng-1.2.9 or later)
    file import/export with libtiff:	yes (pkg-config libtiff-4)
    file import/export with libjpeg:	yes
    image pyramid export:			yes
      (requires libgsf-1 1.14.27 or later)
    use libexif to load/save JPEG metadata: yes
    
Thanks!

**Comment by jcupitt** [comment]
Yup, seeing a crash here too, I'll investigate.

**Comment by jcupitt** [comment]
Fixes it for me, adding some tests now.

**Comment by erdmann** [comment]
Seems to work for me too.  Thanks!

**Comment by jcupitt** [comment]
This fix is in 8.2.2 which is now released. I'll close.
