### ISSUE TITLE
How to use vips_image_new_from_buffer

### ISSUE THREAD

**Issue by Nadot** [jcupitt/libvips#373]
const char* strImg = binStr.get();
            size_t strImgSize = binStr.length();
            VipsImage *imageIn0;
            imageIn0 = vips_image_new_from_buffer(strImg, strImgSize, NULL, NULL);
What is wrong ?
errors : 
(vips:3849): GLib-GObject-WARNING **: unable to set property 'buffer' of type 'VipsBlob' from value of type 'gchararray'
(vips:3849): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
(vips:3849): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
(vips:3849): GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
(vips:3849): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
(lldb) 

Merci ?

**Comment by Nadot** [comment]
After many verifications, strImg et strImgSize are OK. The problem comes from the fisrt NULL.
With :
 imageIn0 = vips_image_new_from_buffer(strImg, strImgSize, "access=VIPS_ACCESS_SEQUENTIAL", NULL);
I have only 2 two errors :
(vips:4230): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
(vips:4230): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

Where is the documentation for the options, witch are present almost in very much api functions ??? !!!

**Comment by jcupitt** [comment]
Hi @Nadot, I'm sorry this isn't working for you. I made you a tiny test program:

```C
/* Compile with:
 *
 * gcc -g -Wall buffer.c `pkg-config vips --cflags --libs`
 */

#include <stdio.h>
#include <stdlib.h>

#include <vips/vips.h>

int
main( int argc, char **argv )
{
        char *buffer;
        size_t length;
        GError *error;
        VipsImage *image;

        if( VIPS_INIT( argv[0] ) )
                vips_error_exit( NULL );

        if( !g_file_get_contents( argv[1], &buffer, &length, &error ) ) {
                fprintf( stderr, "unable to read file %s\n%s\n",
                        argv[1], error->message );
                g_error_free( error );
                exit( 1 );
        }

        if( !(image = vips_image_new_from_buffer( buffer, length, "", NULL )) )
                vips_error_exit( NULL );

        if( vips_image_write_to_file( image, argv[2], NULL ) )
                vips_error_exit( NULL );

        return( 0 );
}
```

So it reads any image file into a memory buffer, decompresses to a `VipsImage`, then writes out again. It works like this:

```
$ gcc -g -Wall buffer.c `pkg-config vips --cflags --libs`
$ ./a.out ~/pics/k2.jpg x.tif
$ eog x.tif
```

And I can see `x.tif` is a copy of `k2.jpg`.

**Comment by jcupitt** [comment]
Regarding the options documentation, for `vips_image_new_from_buffer` it depends upon the load operation. The JPEG loader, for example, is documented here:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-VipsForeignSave.html#vips-jpegload

And the options are listed at the start. You can put options as strings into `option_string`, or append then as name-value pairs. For example:

```C
        image = vips_image_new_from_buffer( buffer, length, "[shrink=2,autorotate]", NULL );
        image = vips_image_new_from_buffer( buffer, length, "",
                "shrink", 2,
                "autorotate", TRUE, 
                NULL );
```

The string options are there because many parts of vips use filenames with embedded options. You can write (for example):

```
$ vips copy k2.jpg[shrink=2,autorotate] x.tif
```

And it's often convenient to be able to use the same syntax for coding options for buffer loads. Of course, from C, a set of name-value pairs is usually much better.

Other operations have options too, for example:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-embed

The options are `"extend"` and `"background"`. You can use the `vips` command-line interface to look these up:

```
$ vips embed
embed an image in a larger image
usage:
   embed in out x y width height
where:
   in           - Input image, input VipsImage
   out          - Output image, output VipsImage
   x            - Left edge of input in output, input gint
			default: 0
			min: -1000000000, max: 1000000000
   y            - Top edge of input in output, input gint
			default: 0
			min: -1000000000, max: 1000000000
   width        - Image width in pixels, input gint
			default: 1
			min: 1, max: 1000000000
   height       - Image height in pixels, input gint
			default: 1
			min: 1, max: 1000000000
optional arguments:
   extend       - How to generate the extra pixels, input VipsExtend
			default: black
			allowed: black, copy, repeat, mirror, white, background
   background   - Colour for background pixels, input VipsArrayDouble
operation flags: sequential-unbuffered 
```

I looked at the vips-from-C section of the manual again and it doesn't introduce the options stuff, that seems like an oversight, I'll add some notes.

**Comment by jcupitt** [comment]
I just tried and you can set `option_string` NULL in `new_from_buffer`. So this is also OK:

```C
        image = vips_image_new_from_buffer( buffer, length, NULL, NULL );
```

**Comment by jcupitt** [comment]
I added some more notes to the using-C docs and updated the copy on the website. DOes this look better?

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-c.html

There's a C++ interface too which is a bit easier to use, I guess you saw?

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-cpp.html

**Comment by Nadot** [comment]
I am unpardonable...
I had left "vips_shutdown();" before using VImage.
But, this was very usefull for me, because I read more and more documentation.
All works (almost...) OK and in C++.

Merci de votre aide précieuse

**Comment by jcupitt** [comment]
Oh hehe, ah well. Glad it's working.
