### ISSUE TITLE
Working with buffer

### ISSUE THREAD

**Issue by Nadot** [jcupitt/libvips#375]
My code
            binarystring binStr(pgResult1[ijk][1]); // convert bytea of posqgresql 
            void *strImg0 = (void *)binStr.get(); // to void *
            size_t strImgSize0 = binStr.size();
            cout << "strImgSize0 : " << strImgSize0 << endl; // 2929520

            ofstream fileOut0 ("/Users/rn/Pictures/Wherbarium/Aux/Aimage0.jpeg", ios::out|ios::binary|ios::ate);
            fileOut0.write ((char *)strImg0, strImgSize0); // write buffer to file with c++, size 2929520
            fileOut0.close();
           
           wxFile file("/Users/rn/Pictures/Wherbarium/Aux/Aimage1.jpeg", wxFile::OpenMode::write);
            file.Write(strImg0, strImgSize0); // write buffer to file with wxWidgets ; same result as previous

            VImage imageIn0 = VImage::new_from_buffer(strImg0, strImgSize0,"", NULL);
            
            size_t newSize3;
            void *buf3;
            imageIn0.write_to_buffer(".jpeg", &buf3, &newSize3, NULL/*VImage::option()->set("", 0)*/);
            cout << "newSize3 : " << newSize3 << endl; // 731887
            ofstream fileOut3 ("/Users/rn/Pictures/Wherbarium/Aux/Aimage3.jpeg", ios::out|ios::binary|ios::ate);
            fileOut3.write ((char *)buf3, newSize3); // the file is correct JPEG, but size of file is 25% of the previous size, but width and height are the same
            fileOut3.close();
            
            size_t newSize4;
            void *buf4 = imageIn0.write_to_memory(&newSize4); //!!! marche pas
            cout << "newSize4 : " << newSize4 << endl; // 14971392
            ofstream fileOut4 ("/Users/rn/Pictures/Wherbarium/Aux/Aimage4.jpeg", ios::out|ios::binary|ios::ate);
            fileOut4.write ((char *)buf4, newSize4); // the file is not a correct JPEG, with a size 500% 
            fileOut4.close();

Why  imageIn0.write_to_buffer or imageIn0.write_to_memory does not provide a buffer with the initial size (2929520) ?

Merci de l'aide.

**Comment by jcupitt** [comment]
Hi again @Nadot.

I expanded that demo program:

```C
/* Compile with:
 *
 * gcc -g -Wall buffer.c `pkg-config vips --cflags --libs`
 */

#include <stdio.h>
#include <stdlib.h>

#include <vips/vips.h>

int
main( int argc, char **argv )
{
	char *buffer_in;
	size_t length_in;
	GError *error;
	VipsImage *image;
	char *buffer_out;
	size_t length_out;

	if( VIPS_INIT( argv[0] ) )
		vips_error_exit( NULL );

	/* Load source image into memory. This image will be in some format,
	 * like JPEG.
	 */
	if( !g_file_get_contents( argv[1], &buffer_in, &length_in, &error ) ) {
		fprintf( stderr, "unable to read file %s\n%s\n", 
			argv[1], error->message );
		g_error_free( error );
		exit( 1 );
	}

	/* Make a vips image from the memory buffer. This image will
	 * decompress from buffer_in as required.
	 */
	if( !(image = vips_image_new_from_buffer( buffer_in, length_in, 
		NULL, NULL )) ) 
		vips_error_exit( NULL );

	/* Create an output memory buffer. Again, this buffer will contain an
	 * image packed into some format, it will not be an array of pixel
	 * values.
	 */
	if( vips_image_write_to_buffer( image, 
		".jpg", (void **) &buffer_out, &length_out, NULL ) ) 
		vips_error_exit( NULL );

	if( !g_file_set_contents( argv[2], buffer_out, length_out, &error ) ) {
		fprintf( stderr, "unable to write file %s\n%s\n", 
			argv[1], error->message );
		g_error_free( error );
		exit( 1 );
	}

	g_object_unref( image ); 
	g_free( buffer_in );
	g_free( buffer_out );

	return( 0 );
}
```

So `write_to_memory` and `write_to_buffer` return the buffer through an argument. It's so they look like `write_to_file`, which returns an exit status.

**Comment by jcupitt** [comment]
Oh, use that prog like this:

```
$ gcc -g -Wall buffer.c `pkg-config vips --cflags --libs`
$ ./a.out ~/pics/k2.jpg x.jpg
$ eog x.jpg 
```

and check that `x.jpg` is indeed a copy of `k2.jpg`, hopefully.

**Comment by Nadot** [comment]
Rien à faire !
k2.jpg : 1982142
x.jpg : 394401

Very strange.
Certainly, I am doing smething wrong. But What ?

May be my configiuration is not correct ?

I installed vips whith MacPorts...

Merci

**Comment by jcupitt** [comment]
It won't be exactly the same, vips saves with the JPEG Q default of 75, so if your original image is Q 100, the vips copy will be a lot smaller. Have look at the output of the program with an image viewer and check it can be decoded as JPEG.

**Comment by Nadot** [comment]
Yes, the output is jpeg.

But I want to get an output file which is exactly the same as input file.

"vips saves with the JPEG Q default of 75"
How to do to obtain JPEG Q default to 100" ?

**Comment by jcupitt** [comment]
Sorry, I missed your post.

You can't decompress a jepg and recompress it and get exactly the same file, unfortunately, it's not possible. You can do some lossless transforms, but they are very limited. The jpeg tools package has a few specialist programs for this. 

In vips, you can set the Q for jpeg write like this:

```
$ vips copy k2.jpg x.jpg[Q=85]
```

ie. you can put options into the file name. You can also set Q from your code like this:

```C
    if( vips_image_write_to_buffer( image, 
        ".jpg", (void **) &buffer_out, &length_out, 
        "Q", 85,
        NULL ) ) 
        vips_error_exit( NULL );
```

So see all the options, try this at the command-line:

```
$ vips jpegsave
save image to jpeg file
usage:
   jpegsave in filename
where:
   in           - Image to save, input VipsImage
   filename     - Filename to save to, input gchararray
optional arguments:
   Q            - Q factor, input gint
			default: 75
			min: 1, max: 100
   profile      - ICC profile to embed, input gchararray
   optimize-coding - Compute optimal Huffman coding tables, input gboolean
			default: false
   interlace    - Generate an interlaced (progressive) jpeg, input gboolean
			default: false
   no-subsample - Disable chroma subsample, input gboolean
			default: false
   trellis-quant - Apply trellis quantisation to each 8x8 block, input gboolean
			default: false
   overshoot-deringing - Apply overshooting to samples with extreme values, input gboolean
			default: false
   optimize-scans - Split the spectrum of DCT coefficients into separate scans, input gboolean
			default: false
   strip        - Strip all metadata from image, input gboolean
			default: false
   background   - Background value, input VipsArrayDouble
operation flags: sequential-unbuffered nocache 
```

Or of course there are the docs:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-VipsForeignSave.html#vips-jpegsave

**Comment by jcupitt** [comment]
Hopefully this is resolved, please reopen if not.
