### ISSUE TITLE
does it possible to run dzsave with color profile option?

### ISSUE THREAD

**Issue by mogadanez** [jcupitt/libvips#377]
I have 2 kind of images:
1. CMYK colorspace
2. Embeded  color profile

if i run `convert -profile sRgb.icm in out` before dzsave  - result is OK
Can i skip convert step and do it with dzsave command directly?

**Comment by jcupitt** [comment]
Hi, you can send any vips operation to `dzsave` by using the `.dz` suffix. Try:

```
vips icc_import wtc.tif x.dz
```

This will:

* Import the TIFF file to PCS (LAB colourspace by default) using the embedded profile,
* Send the result to `dzsave`,
* Write each tile out with the jpeg saver,
* JPEG save will automatically convert the LAB image to sRGB before writing.

You can give parameters to dzsave with the usual bracket syntax, eg.

```
vips icc_import wtc.tif x.dz[overlap=0]
```

**Comment by jcupitt** [comment]
Did this fix it? Please reopen if not.
