### ISSUE TITLE
created jpeg image has no color BUT tif format OK

### ISSUE THREAD

**Issue by apacheark** [jcupitt/libvips#378]
Hi, I am new to VIPS and so far loving it.  I am using the Python interface to libvips with vips 8.2.2 on Ubuntu 14.04.
I am creating a large mosaic (2300 images) and that works just fine, if I use TIF as the output format.
If I output to JPG, there is no color.

Each single image is an RGB composite made from 3 single band B/W jpgs.  I am using im.bandjoin to create the 3-band composite image.
If I call the Python code below as "python test.py in.jpg out.tif", the resulting out.tif file as the colors I expect from the 3 bands.
If I call the code as "python test.py in.jpg out.jpg", the resulting jpg image is B/W with perhaps only one band shown.

If I use the command line, "vips copy in.tif out.jpg", the resulting jpg looks fine (with color).
Ultimately, I want to use dzsave to generate a large zoomable mosaic image made up of the images. Since jpg is the default output format for dzsave, I have to get the color working in the jpg images.

Any ideas as to what I am doing wrong?

Here is the code:

import sys
from gi.repository import Vips

b_name="Tile000500.jpg"
r_name="Tile002804.jpg"
g_name="Tile005108.jpg"

rim = Vips.Image.new_from_file(r_name)
gim = Vips.Image.new_from_file(g_name)
bim = Vips.Image.new_from_file(b_name)

myimg2=rim.bandjoin([gim,bim])

myimg2.write_to_file(sys.argv[1])

**Comment by apacheark** [comment]
Meant to add, Using vips 8.2.2 on Ubuntu 14.04.

**Comment by jcupitt** [comment]
Hi @apacheark, when you join mono images together, the extra bands are seen as alpha channels. So after this line:

```
myimg2=rim.bandjoin([gim,bim])
```

You have a greyscale image with two alpha channels. The JPEG saver knows that JPEG does not support alpha, so it drops those channels and you just get mono.

To fix this, tag the image as sRGB using `.copy()`. Change the end of your code to be:

```python
myimg2=rim.bandjoin([gim,bim])
myimg2 = myimg2.copy(interpretation = "srgb")
myimg2.write_to_file(sys.argv[1])
```

**Comment by apacheark** [comment]
Thank you!  That worked .  I must say that VIPS is turning out to be very useful.  I cut my mosaicing and deepzoom pyramid generation to 1/3 the time it was taking with our current approach.  And I am likely not doing it the most efficient way and not !

PLEASE keep up the good work and VIPS (and the python hooks)!

**Comment by jcupitt** [comment]
Glad it's working, I'll close.
