### ISSUE TITLE
Better PDF support

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#379]
It would be great if libvips had a direct binding to a pdf library to allow efficient generation of eg. thumbnails from PDFs.

vips currently can read pdfs via imagemagick or graphicksmagic, but both of these are very slow and memory inefficient at that.

I think a good candidate could be libpoppler which has a cairo output device ([Usage in pdftocairo utility](http://cgit.freedesktop.org/poppler/poppler/tree/utils/pdftocairo.cc)).

**Comment by felixbuenemann** [comment]
Some examples to show the huge performance differences of different pdf libaries/tools:

**Convert first page from a 340 MB PDF containing an embedded 5120x2880px JPEG image to a 150x150 thumbnail:**

**imagemagick with the default gs delegate:**

```bash
convert -version
Version: ImageMagick 6.9.3-0 Q8 x86_64 2016-02-06 http://www.imagemagick.org

/usr/bin/time -l convert wp.pdf'[0]' -resize 150x150 -quality 75 thumb.jpg
       17.90 real        17.32 user         0.19 sys
  26521600  maximum resident set size
# spawns gs process with ~25MB RSS:
gs -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 -sDEVICE=pngalpha -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r72x72 -dFirstPage=1 -dLastPage=1 -sOutputFile=/var/tmp/magick-60913ntRSLNLq2kNB%d -f/var/tmp/magick-60913GtrNJVg7XPsI -f/var/tmp/magick-60913SjbyBDK83pHM

identify thumb.jpg
thumb.jpg JPEG 150x84 150x84+0+0 8-bit sRGB 3.27KB 0.000u 0:00.000
```
Interestingly, in the above example convert spends roughly 17 seconds burning cpu time reading through the entire pdf file for no apparent reason, then symlinks the source file to a tmp path and calls gs to extract the image :confused:

**graphicksmagick withd efault gd delegate:**

```bash
gm -version
GraphicsMagick 1.3.23 2015-11-07 Q8 http://www.GraphicsMagick.org/

/usr/bin/time -l gm convert wp.pdf'[0]' -resize 150x150 -quality 75 thumb.jpg
       15.96 real        15.10 user         0.67 sys
  22814720  maximum resident set size
# spawns gs process with ~14MB RSS:
gs -q -dBATCH -dMaxBitmap=50000000 -dNOPAUSE -sDEVICE=ppmraw -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r72x72 -dFirstPage=1 -dLastPage=1 -sOutputFile=/var/folders/dp/qz_3lx1s76gct7_0f93fxbs40000gn/T/gmJgL7IO -- /var/folders/dp/qz_3lx1s76gct7_0f93fxbs40000gn/T/gmQUFxiN -c quit

identify thumb.jpg
thumb.jpg JPEG 150x84 150x84+0+0 8-bit sRGB 3.65KB 0.000u 0:00.000
```
Behavior is very similar to imagemagick, most time is spent reading the source file and at the very end gs is spawned.

**Same task with libpoppler using `pdftocairo` (with patch to add `-jpegquality` switch):**

```bash
pdftocairo -v
pdftocairo version 0.40.0

/usr/bin/time -l pdftocairo -jpeg -jpegquality 75 -singlefile -scale-to 150 wp.pdf thumb
        0.59 real         0.54 user         0.03 sys
   5955584  maximum resident set size

identify thumb.jpg
thumb.jpg JPEG 150x85 150x85+0+0 8-bit sRGB 3.79KB 0.000u 0:00.000
```

**Pure ghostscript (very pixellated due to no interpolation)**

```bash
gs -V
GPL Ghostscript 9.18 (2015-10-05)

/usr/bin/time -l gs -sDEVICE=jpeg -o thumb.jpg -dJPEGQ=75 -dFirstPage=1 -dLastPage=1  -dPDFFitPage -dDEVICEWIDTHPOINTS=150 -dDEVICEHEIGHTPOINTS=84 wp.pdf
GPL Ghostscript 9.18 (2015-10-05)
Copyright (C) 2015 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
Processing pages 1 through 1.
Page 1
        0.55 real         0.50 user         0.02 sys
  19185664  maximum resident set size

identify thumb.jpg
thumb.jpg JPEG 150x84 150x84+0+0 8-bit sRGB 8.07KB 0.000u 0:00.000
# size difference due to "noisy" image
```

**Using mudraw from mupdf tools:**

```bash
mutool -v
mutool version 1.8

/usr/bin/time -l mutool draw -o thumb.jpg -w 150 -h 150 wp.pdf 1
        0.21 real         0.18 user         0.01 sys
  19247104  maximum resident set size

identify thumb.jpg
thumb.jpg PNG 150x85 150x85+0+0 8-bit sRGB 28.1KB 0.000u 0:00.000
# different jpg quality, no option to set
```

As can be seen, both gm and im are about the worst choices to use for converting pdf to images.

**Comment by jcupitt** [comment]
Wow, I had no idea the performance problems were so large. I thought since IM just delegated to GS, speed should be reasonable.

I agree, poppler sounds like a good choice. I'll have a look at adding a loader for it.

**Comment by felixbuenemann** [comment]
Thank you John! I'm too inexperienced with C languages to help with the implementation, but I'm happy to do testing, benchmarking, etc.

It would be great if vips could replace imagemagick as the defacto standard for imageprocessing on servers.

**Comment by jcupitt** [comment]
I made a branch for adding libpoppler support:

https://github.com/jcupitt/libvips/tree/add-libpoppler

You can open files, but it's not reading pixels yet.

**Comment by jcupitt** [comment]
It seems to be working! I see a nice drop in CPU and memory. For example, with a single-page ISO chart (a small file but with heavy graphics rendering) I see:

```
$ time vips magickload ISO_12233-reschart.pdf x.v --density 300
real	0m1.112s
user	0m0.996s
sys	0m0.236s
peak memory: 180MB
```

And with the new operator:

```
$ time vips popplerload ~/pics/ISO_12233-reschart.pdf x.v --dpi 300
real	0m0.397s
user	0m0.364s
sys	0m0.088s
peak memory: 75MB
```

With a 70-page, 1.5MB PDF (the nip2 manual) I see:

```
$ time vips magickload ~/GIT/nip2/doc/pdf/nipguide.pdf x.v --density 300 
real	0m55.004s
user	0m52.300s
sys	0m3.184s
peak memory: 170MB (70MB for vips, 100MB for external gs process)
$ time vips popplerload ~/GIT/nip2/doc/pdf/nipguide.pdf x.v --dpi 300 
real	0m0.115s
user	0m0.080s
sys	0m0.068s
peak memory: 62MB
```

... good grief, 500x faster.

`popplerload` is the default PDF handler, so all `.pdf` files will use it, if it's enabled. There's a `--page` switch to pull a certain page out. 

There are a few things that need fixing:

* It currently outputs BRGA, so blue and green need swapping.
* The way it forms URIs is a bit broken at the moment, so you must give it absolute pathnames. 

And some remaining questions:

* Do we need a way to get the number of pages in a document?
* Is DPI the best way to specify output resolution?
* Is transparency useful? We could flatten it out.
* What about page edges? At the moment, some documents will come out with large black borders.
* poppler exposes some other document metadata, we could expose that.

**Comment by jcupitt** [comment]
Oh, one more nice thing, `popplerload` generates the output image in sections on demand, so memory use is low even for very large output. For example:

```
$ time vips popplerload ~/GIT/nip2/doc/pdf/nipguide.pdf x.v --dpi 1000 --page 12
real	0m3.377s
user	0m2.424s
sys	0m0.604s
peak memory: 96MB
```

That's making a 400MB output page.

**Comment by felixbuenemann** [comment]
That's great news, I wasn't sure if poppler had the proper apis to be able to render the image progressively.

To answer your question above:
> Do we need a way to get the number of pages in a document?

Yes, but I think for some documents it can be expensive, so it should probably be lazy.

> Is DPI the best way to specify output resolution?

I think it's very unintuitive. The output resolution should be specified in pixels, with a sane default for the dpi. It should probably still be possible to override the dpi to do supersampling for higher quality output images (that's roughly the same effect as anti-aliasing, but more expensive).

> Is transparency useful? We could flatten it out.

It depends on the output image. If you export to a file with alpha channel, you might want to keep it.

> What about page edges? At the moment, some documents will come out with large black borders.
poppler exposes some other document metadata, we could also expose that.

There are several boxes that marks sections of the page relevant for different uses. PDF was made for print media, so a page contains a MediaBox, that is similar to the size of the media it is printed on. The outer edges often contain print marks, that are used for cutting the page to a smaller format. Inside the MediaBox there is a BleedBox and inside it a TrimBox. Because you don't want to cut away important texts there's some wiggle room between the Trim and Bleed where solid colors and Images overlap so you don't need to be very precise when cutting. There is also a CropBox, that defines the visible area for the PDF viewer. Usually the CropBox is similar to the TrimBox. So if you want to export an image, you should only export the area defined by the Cropbox.

[This image](https://www.dropbox.com/s/5l88smbvbevle68/Screenshot%202016-02-08%2013.38.20.png?dl=0) I snapped from O'Reilly "Developing with PDF" shows the different boxes.

This is a simple page object with MediaBox and CropBox:

```postscript
<<
    /Type /Page
    /Parent 532 0 R
    /MediaBox [ 0 0 612 792 ]
    /CropBox [ 0 0 500 600 ]
    /Contents 564 0 R
    /Resources <<
        /ExtGState << /GS0 571 0 R /GS1 572 0 R >>
        /Font << /T1_0 566 0 R >>
        /XObject << /Im0 577 0 R >>
    >>
    /Trans << /S /Dissolve >>
    /Rotate 90
    /Annots 549 0 R
    /AA << /C 578 0 R /O 579 0 R >>
>>
```
If no CropBox is present, just use the MediaBox.

If you'd like to better understand the PDF structure, I could get you a digital copy of the above mentioned book. It's much shorter and easier to understand the the official [Adobe standard documents](http://www.adobe.com/devnet/pdf/pdf_reference.html).

There are also some interesting optimizations possible, if the PDF page contains only an embedded image, eg. for scanned documents, it's possible to extract the image data and convert that instead of first rendering the image at whatever resolution. (The `pdfimages` command from poppler can do that on the command line.)

**Comment by felixbuenemann** [comment]
Btw. you can use either pdftk or qpdf to decrypt and uncompress pdfs on the command line, so you can look at the postscript code. Not sure if poppler ships a similar utility.

**Comment by jcupitt** [comment]
I don't suppose you have a complete sample file with different media/trim/crop boxes? Everything I've tried so far just has (0, 0, width, height) when I call poppler_page_get_crop_box().

I've added metadata read.

**Comment by felixbuenemann** [comment]
I've prepared a small sample pdf with all the boxes. All PDF viewers I've tested show only the cropbox area. The other boxes are only shown in Acrobat Pro, if I edit the page bounds from the print tools. The green box in [this screenshot](https://www.dropbox.com/s/0savwne0cr65xf9/Screenshot%202016-02-08%2021.47.31.png?dl=0) shows the TrimBox, which is equal to the current CropBox of the file.

If you want too see the whole page in other viewers, change the CropBox to match the MediaBox and change the `startxref` value to 1158 (cause you removed two bytes).

```postscript
%PDF-1.6
1 0 obj
<< /Creator (Felix Buenemann)
/Producer (VIM 7.4)
>>
endobj
2 0 obj
<< /Kids [5 0 R]
/Type /Pages
/Count 1
>>
endobj
3 0 obj
<< /Type /Catalog
/Pages 2 0 R
>>
endobj
4 0 obj
<< /Length 541
>>
stream
% paint red hexagon
1 0 0 rg
136 286 m
236 336 l
336 286 l
336 186 l
236 136 l
136 186 l
f
% add strokes to make it look like an isometric box
4w
1 0.3 0.3 RG
136 286 m
236 236 l
336 286 l
236 236 m
236 136 l
S
% blue box in left top corner, reaching into bleed
0 0 1 rg
10 582 200 200 re
f
0 0 0 RG
% left bottom crop marks
0 20 m
10 20 l
20 0 m
20 10 l
% right bottom crop marks
602 20 m
612 20 l
592 0 m
592 10 l
% left top crop marks
0 772 m
10 772 l
20 782 m
20 792 l
% right top crop marks
602 772 m
612 772 l
592 782 m
592 1792 l
S
Q
endstream
endobj
5 0 obj
<< /Contents 4 0 R
/Type /Page
/MediaBox [0 0 612 792]   % letter format 8.5x11" at 72 dpi
/BleedBox [10 10 602 782] % bleed box offset 10 pts from each edge
/TrimBox [20 20 592 772]  % trim box offset 20 pts from each edge
/CropBox [20 20 592 772]  % crop box for viewer matches trim box
/ArtBox [136 136 336 336] % art box around the red isometric box
/Parent 2 0 R
>>
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000077 00000 n 
0000000134 00000 n 
0000000183 00000 n 
0000000774 00000 n 
trailer
<< /Info 1 0 R
/Size 6
/Root 3 0 R
>>
startxref
1160
%%EOF
```
You can get the proper offset in vim with `:echo eval(line2byte(line("."))+col(".")-2)` while at the beginning of the `obj` or `xref` lines, provided your vim has python support.

**Comment by felixbuenemann** [comment]
Btw. you can print info about the boxes using `pdfinfo -box <filename>` from poppler:

```bash
pdfinfo -box page_boxes.pdf
Creator:        Felix Buenemann
Producer:       VIM 7.4
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      572 x 752 pts
Page rot:       0
MediaBox:           0.00     0.00   612.00   792.00
CropBox:           20.00    20.00   592.00   772.00
BleedBox:          10.00    10.00   602.00   782.00
TrimBox:           20.00    20.00   592.00   772.00
ArtBox:           136.00   136.00   336.00   336.00
File size:      1356 bytes
Optimized:      no
PDF version:    1.6
```

**Comment by jcupitt** [comment]
That's fantastic! Thank you @felixbuenemann !

I think I am getting the crop box automatically. If I run this:

```
$ vips pdfload cropbox.pdf x.png
```

I see this:

![x](https://cloud.githubusercontent.com/assets/580843/12899793/126130fa-ceab-11e5-8223-cf88f94c5a76.png)

ie. we have the cropbox, but with a transparent background. I'm not sure if that's correct or not.

I've been through the other items on the TODO and done them all, I think. There's now a `pdfload_buffer`, so you can load from a memory area. I've added another sizing control, `--scale`. You can now set the render size by either setting a specific DPI, or by requesting a relative scale.

Remaining issues I can think of:

* `vipsthumbnail` needs to know about `pdfload` ... it can open the PDF, see what width / height it gets, then open again with scale set to get the width / height it needs. 
* PDF supports page thumbnails ... these could be extracted as metadata, they might help `vipsthumbnail`.
* As you say, clever things with whole-page images might be possible.
* vips defaults to black as the background when flattening out alpha. This is probably not correct for PDF, we should flatten against white.

**Comment by felixbuenemann** [comment]
> ie. we have the cropbox, but with a transparent background. I'm not sure if that's correct or not.
There is no background color in the pdf, it's similar to a vector graphic or word document in that regard.

For `vipsthumbnail` and other vips cli tools there should probably be an option to set the page range per file and where to put the page number in the output filename:
```bash
$ vipsthumbnail 'foo.pdf[0]' 'bar.pdf[1-3,5]' twopage.pdf hello.jpg -o 'tn_%s%02d.jpg[Q=70]'
# generates
tn_foo_00.pdf
tn_bar_01.pdf
tn_bar_02.pdf
tn_bar_03.pdf
tn_bar_05.pdf
tn_two_00.pdf
tn_two_01.pdf
tn_hello_00.pdf
```
The same mechanism could be used to access frames in gifs or pages/layers of tiff.

Using embedded page thumbnails if available and of high enough resolution is a good idea.

> vips defaults to black as the background when flattening out alpha. This is probably not correct for PDF, we should flatten against white.

Shouldn't the default always be white? I can't remember a time where I actually wanted to flatten to a black background. I think vips should be consistent here. Either always use black as default or always white and allow the user to override if needed. The cli tools could have a `--background` switch that takes a rgb hexcode or comma separated list of rgb values.

**Comment by jcupitt** [comment]
> there should probably be an option to set the page range per file and where to put the page number in the output filename

That's there now, you do:

```
vipsthumbnail mydoc.pdf[page=12]
```

And it'll thumbnail page 12. It works for TIFF as well. There's no option for page ranges though, you can only pick out single pages.

> Shouldn't the default always be white? I can't remember a time where I actually wanted to flatten to a black background. 

I think it's black because black is zero whatever the bit depth. A 16-bit PNG needs 65535 for white, for example. A black default is simpler.

> I think vips should be consistent here. Either always use black as default or always white and allow the user to override if needed. The cli tools could have a --background switch that takes a rgb hexcode or comma separated list of rgb values.

Yes, this is there as an option now. You can write:

```
vips copy mydoc.pdf[page=12] x.jpg[background=255]
```

And it'll flatten against a white background during JPEG save.

Perhaps we are OK then. I'll add something to `vipsthhumbnail` for PDF handling.

**Comment by jcupitt** [comment]
I added `pdfload` support to `vipsthumbnail`. It's rather quick!

```
$ time vipsthumbnail nipguide.pdf 
real	0m0.045s
user	0m0.036s
sys	0m0.012s
```

Current git master, going via libMagick, is a little slower:

```
$ time vipsthumbnail nipguide.pdf 
real	0m9.539s
user	0m9.424s
sys	0m0.196s
```

**Comment by jcupitt** [comment]
I had a horrible thought: what does this code do with CMYK PDFs? I guess they will be converted to sRGB, but I've no idea how. 

Do you have a sample CMYK PDF I could test with?

**Comment by felixbuenemann** [comment]
I'll create a CMYK PDF for you and try out the code later today. Had some autotools trouble yesterday, but compile works fine now.

**Comment by felixbuenemann** [comment]
I have created a [CMYK Test PDF](https://www.dropbox.com/s/reqygmn79ci1623/cmyktest.pdf?dl=0) and some examples of proper/improper color management during conversion using imagemagick.

The document was authored in Illustrator using CMYK and FOGRA 39 Coated v2 color profile (a standard print profile) and saved without embedded color profiles.

Color Patches:

* 100% C
* 100% M
* 100% Y
* 100% K
* CMYK 0/100/100/0 (Red)
* CMYK 100/0/100/0 (Green)
* CMYK 100/100/0/0 (Blue)
* CMYK 91/79/62/97 (a Superblack, equal to RGB 0/0/0, print more likely uses CMYK 40/30/30/100)

Profiles:

* [CMYK Fogra 39 Coated v2](https://www.dropbox.com/s/dd9cbrm4rimufs8/ISOcoated_v2_eci.icc?dl=0)
* [sRGB 2.1](https://www.dropbox.com/s/nfx2nasgjvgsjvv/sRGB_IEC61966-2-1_black_scaled.icc?dl=0)

**Convert to RGB JPEG using profiles (proper colors):**

```
convert cmyktest.pdf \
  -profile ISOcoated_v2_eci.icc \
  -profile sRGB_IEC61966-2-1_black_scaled.icc \
  -colorspace sRGB cmyktest-with-profiles-rgb.jpg
```

![cmyktest-with-profiles-rgb.jpg](https://www.dropbox.com/s/osvctwtft2sxoxv/cmyktest-with-profiles-rgb.jpg?dl=1)

**Convert to RGB JPEG without profiles (colors oversaturated):**

```
convert cmyktest.pdf \
  -colorspace sRGB cmyktest-without-profiles-rgb.jpg
```

![cmyktest-without-profiles-rgb.jpg](https://www.dropbox.com/s/botf46hrzd2ifid/cmyktest-without-profiles-rgb.jpg?dl=1)

**Convert to CMYK JPEG using profiles (proper colors):**

```
convert cmyktest.pdf \
  -profile ISOcoated_v2_eci.icc \
  -colorspace CMYK cmyktest-with-profiles-rgb.jpg
```

![cmyktest-with-profiles-cmyk.jpg](https://www.dropbox.com/s/k72u74nl328j43u/cmyktest-with-profiles-cmyk.jpg?dl=1)

**Convert to CMYK JPEG without profiles (colors muted):**

```
convert cmyktest.pdf \
  -colorspace CMYK cmyktest-without-profiles-cmyk.jpg
```

![cmyktest-without-profiles-cmyk.jpg](https://www.dropbox.com/s/nin6wbj9tazpeva/cmyktest-without-profiles-cmyk.jpg?dl=1)

I just used imagemagick here, because I know how it handles color profiles. I think none of the conversions above is wrong, but it's unlikely that a CMYK document does not use a color profile, while in RGB space sRGB is often the norm. I also tried exporting the PDF with embedded profiles, but at least imagemagick does not seem to use them.

Both the Acrobat and Mac OS X PDF viewer showed the PDF with proper colors and I didn't see a difference, when I embedded the color profiles into the file, but they probably ship with their own set of standard profiles. Both PDF viewers produced an image that looked pretty much the same as in Illustrator, while imagemagick's conversion looks less neutral/warmer, might be because the viewers convert to the display's icc profile, which might be using a wider color range than sRGB.

**Comment by felixbuenemann** [comment]
Btw. if I'm not mistaken poppler, vips and imagemagick all use lcms2 for color management.

**Comment by felixbuenemann** [comment]
The original cmyktest.pdf used ZIP compression for images, which is illustrators default. I've also exported a [copy using JPEG compression](https://www.dropbox.com/s/7oxj82jumaai2fr/cmyktest2.pdf?dl=0):

```
pdfimages -list cmyktest2.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     500   333  cmyk    4   8  jpeg   no        11  0   102   102  123K  19%
```

**Comment by felixbuenemann** [comment]
I tested the pdf from the initial post with 625e0fb:

```bash
/opt/vips/bin/vips -v
vips-8.3.0-Tue Feb  9 19:17:53 CET 2016

/usr/bin/time -l /opt/vips/bin/vipsthumbnail wp.pdf -s 150 -o thumb.jpg'[Q=75]'
        0.61 real         0.55 user         0.05 sys
  20,385,792  maximum resident set size

identify thumb.jpg
thumb.jpg JPEG 150x85 150x85+0+0 8-bit sRGB 3.81KB 0.000u 0:00.000
```

That looks very promising! I'll have to do some more tests with different files.

Thanks for the work you've put into it so far!

Doing `vips copy` is currently slower than expected, not sure why.

In the above case, the first page has a 5120x2880 JPEG embedded, but when rendering at 72 dpi it is only 1228x691, but doing `vips copy wp.pdf'[page=0]' x.jpg` is pretty slow:

```bash
/usr/bin/time -l /opt/vips/bin/vips copy wp.pdf'[page=0]' x.jpg
        3.51 real         3.22 user         0.22 sys
  29,339,648  maximum resident set size

identify x.jpg
x.jpg JPEG 1228x691 1228x691+0+0 8-bit sRGB 183KB 0.000u 0:00.000
```

pdftocairo handles this case much faster:

```bash
/usr/bin/time -l pdftocairo -jpeg -jpegquality 75 -singlefile -r 72 wp.pdf y
        0.60 real         0.55 user         0.04 sys
  12,517,376  maximum resident set size

identify y.jpg
y.jpg JPEG 1228x691 1228x691+0+0 8-bit sRGB 183KB 0.000u 0:00.000
```

**Comment by felixbuenemann** [comment]
Mystery solved, `vips copy` still uses imagemagick, even if compiled with libpoppler.

**Comment by felixbuenemann** [comment]
No, it's not using imagemagick. It's acutally faster in this case to use vips-8.2.2 with imagemagick:

```
# vips 625e0fb with poppler:
/opt/vips/bin/vips --vips-progress --vips-leak copy Abstract.pdf x2.jpg
vips temp-5: 5120 x 2880 pixels, 4 threads, 5120 x 16 tiles, 256 lines in buffer
vips temp-5: done in 12,7s
memory: high-water mark 45,94 MB

# vips 8.2.2 with imagemagick:
/usr/local/bin/vips --vips-progress --vips-leak copy Abstract.pdf x2.jpg
vips temp-4: 5120 x 2880 pixels, 4 threads, 128 x 128 tiles, 256 lines in buffer
vips temp-4: done in 0,519s
memory: high-water mark 8,06 MB
```
So, something is not quite right here.

**Comment by felixbuenemann** [comment]
I've uploaded the original [5120x2880 JPEG](https://www.dropbox.com/s/ogd3g54sgi1qdol/Abstract.jpg?dl=0), as well as the [5120x2880 PDF](https://www.dropbox.com/s/dsvxo07sm0cecqn/Abstract.pdf?dl=0) that embeds it. The PDF contains a single page with the same dimensions as the image that embeds the data from the JPEG without conversion.

Copying the original JPEG is quite fast:

```
/opt/vips/bin/vips --vips-progress --vips-leak --vips-profile copy ~/Wallpaper/Abstract.jpg x2.jpg
vips temp-3: 5120 x 2880 pixels, 4 threads, 5120 x 16 tiles, 256 lines in buffer
recording profile in vips-profile.txt
vips temp-3: done in 0,297s
memory: high-water mark 14,06 MB
```

**Comment by jcupitt** [comment]
It's to do with `pdfload` progressive rendering.

To keep memory use down, `pdfload` renders the image in strips of 128 scan lines. Your PDF is 2880 pixels high, so that's 23 strips. Each time it renders a strip, it has to decode the image and just paint the bits that hit the current strip.

On my laptop, I see:

```
$ time vips copy Abstract.pdf x.jpg
real	0m14.994s
user	0m14.536s
sys	0m0.720s
```

If I change this line to have a tile height of 2880:

https://github.com/jcupitt/libvips/blob/add-librsvg/libvips/foreign/pdfload.c#L300

I see:

```
$ time vips copy Abstract.pdf x.jpg
real	0m0.823s
user	0m0.988s
sys	0m0.028s
```

With imagemagick it's:

```
$ time vips magickload Abstract.pdf x.jpg
real	0m13.441s
user	0m13.560s
sys	0m0.180s
```

Though of course that's not doing progressive rendering.

I'm not sure what the best solution is. We could expose the `tile-height` parameter as an option, but that seems rather ugly. Perhaps this slowdown is just inevitable for large images which span many chunks?

**Comment by jcupitt** [comment]
We have another problem: I can't find a way to make Poppler produce CMYK bitmaps. The two output paths are Cairo, which is sRGB-only, since it is designed for painting displays; and PS, which is targeting printers and is not a bitmap. 

The magickloader is still there, of course, perhaps users will have to select that if they want CMYK.

By default, conversion to srgb:

```
$ vips copy cmyktest.pdf x.tif
$ vipsheader x.tif
x.tif: 595x841 uchar, 4 bands, srgb, tiffload
```

Via libmagick (and therefore GS):

```
$ vips magickload cmyktest.pdf x.tif
$ vipsheader x.tif
x.tif: 595x842 ushort, 4 bands, cmyk, tiffload
```

**Comment by jcupitt** [comment]
I changed the way the `pdfload` cache is sized. You can now do:

```
$ time vips copy Abstract.pdf x.tif --vips-tile-height=2880
real	0m0.821s
user	0m0.672s
sys	0m0.220s
```

which at least makes the chunking controllable.

**Comment by jcupitt** [comment]
It looks like mupdf supports true CMYK bitmap output, I'll have a go at using that instead.

**Comment by felixbuenemann** [comment]
At least jpeg-turbo master supports partial decoding of scanlines, which could avoid re-rendering the whole jpeg. See the changelog on github for details.

**Comment by jcupitt** [comment]
mupdf has a thing where you can keep the decoded assets between renders to avoid repeated scans. I'll see if I can get that working. 

Mupdf is not free for commercial use, unfortunately, I don't know if that's a serious blocker.

**Comment by felixbuenemann** [comment]
Oh and I think mupdf uses lots of vendored libs it statically compiles in by default, so while it's fast it might not be the greatest codebase to work with. At least it seems to be unproblematic for commercial use, which is not true for ghostscript.

**Comment by felixbuenemann** [comment]
Oops, I thought mupdf did not have that restriction.

**Comment by jcupitt** [comment]
On http://mupdf.com/ they say:

```
 MuPDF is free software: you can redistribute it and/or modify it under the terms of the Affero GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

MuPDF is Copyright 2006-2015 Artifex Software, Inc.

For commercial licensing please contact sales@artifex.com.
```

ie. you need a license for commercial use, I think. It's also only available as a static GPL3 library, so libvips would become GPL3 as well (I think?).

I think it would be possible to make `mupdfload` as a plugin, then it's the user's responsibility to ensure compliance.

**Comment by felixbuenemann** [comment]
I think this is the reason imagemagick / graphicsmagick use `gs` as a delegate by default, instead of linking to libgs. You could probably do an optional mupdf loader, but there should be a free default.

**Comment by jcupitt** [comment]
Oh argh, and there's another problem, of course because mupdf is only available as a static library, it forces libvips to be static too. So you can't make a plugin that uses it either.

**Comment by lovell** [comment]
-1 for MuPDF (balanced with a +1 for Poppler).

Static linking limitations aside, Affero libraries are a no-go for commercial users of sharp+Node.js as everything runs in the same process.

**Comment by felixbuenemann** [comment]
Btw. the cmyk pdf to cmyk image case should be very rare, it's fine to leave that to magick. Most of the time you want to display a print pdf on a screen.

I'm all for avoiding ghostscript and mupdf, I've had no pleasant experiences with the team behind it.

**Comment by jcupitt** [comment]
OK, I'll abandon mupdf. Poppler is RGB only, but users can still go via libMagic if they want true CMYK bitmaps.

**Comment by jcupitt** [comment]
I've merged to master, I think we're done, except for lots of testing.

Colour management with PDFs is not in great shape :-( but that's really a poppler issue and not something we can do much about. 

Let's close this and open new issues for any problems that come up. Thank you very much for your test images, @felixbuenemann, I've included `cmyktest.pdf` in the vips test suite, hope that's OK.

**Comment by felixbuenemann** [comment]
Fine with me.

Btw. about the jpeg-turbo stuff mentioned above:

> Added a new libjpeg API function (jpeg_skip_scanlines()) that can be used
to partially decode a JPEG image.  See [libjpeg.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/libjpeg.txt#L733) for more details.

**Comment by jcupitt** [comment]
Just a quick note, libpoppler is GPL, so there may be some issues using that from vips (an LGPL library) as well. It should be OK on a webserver at least.

I noticed while testing the `svgload` importer that ImageMagick handles SVG by shelling out to `inkscape`. Ouch!

I wrote up some notes and benchmarks on this work on the vips blog:

http://libvips.blogspot.co.uk/2016/02/new-image-loaders.html

**Comment by felixbuenemann** [comment]
Nice writeup! Do you load only frame 0 in magickload for pdfs or gifs? That should give a noticeable speedup.

**Comment by jcupitt** [comment]
It's unclear. `magickload` calls `ReadImage()` and then either uses `GetNextImageInList()` to pull out all the frames, if `all_frames` is set, or just returns the first image. But at what point the IM GIF loader actually scans the input file, I don't know.

GIF has no field in the header for number-of-frames, you have to scan the whole file until you see the end record. So perhaps IM has to load the whole image before it can return from `ReadImage()`?

**Comment by felixbuenemann** [comment]
I think you need to append `[0]` to the filename, just like with the cli tools.

**Comment by jcupitt** [comment]
Oh haha, I didn't know about that, duh. Yes, it's a huge speedup.

I'll need some way of setting that programattically, I can't find it in the docs. I tried:

```
SetImageOption( read->image_info, "scene", "0" );
```

Just before `ReadImage()`, which from looking at the sources you might think would do it, but nope. I'll keep digging. 

I've made an issue for this: https://github.com/jcupitt/libvips/issues/384

**Comment by jcupitt** [comment]
I finally figured out how to do this, git master vips is now much quicker. It was about 7s, but it's now:

```
$ time vips magickload nipguide.pdf x.png
real	0m0.213s
user	0m0.212s
sys	0m0.020s
$ time vips pdfload nipguide.pdf x.png
real	0m0.076s
user	0m0.068s
sys	0m0.016s
```

Though not quite as fast as the direct call to libpoppler. I'll update that blog post.

**Comment by felixbuenemann** [comment]
Sorry, I missed your last reply. Looks like 8.3 will be a great release!

**Comment by shilpi230** [comment]
In what version I can get the pdfload with poppler ? Is it available now ?

**Comment by adityapatadia** [comment]
> I'm not sure what the best solution is. We could expose the `tile-height` parameter as an option, but that seems rather ugly. Perhaps this slowdown is just inevitable for large images which span many strips?

Sorry to comment on old thread but is there a way to change `tile-height`? It's required for our use-case where memory usage is not an issue but processing time must be fast.

**Comment by adityapatadia** [comment]
> > I'm not sure what the best solution is. We could expose the `tile-height` parameter as an option, but that seems rather ugly. Perhaps this slowdown is just inevitable for large images which span many strips?
> 
> Sorry to comment on old thread but is there a way to change `tile-height`? It's required for our use-case where memory usage is not an issue but processing time must be fast.

Nevermind, I missed comment. I found what I needed.

**Comment by adityapatadia** [comment]
I have tried the commands but I am getting the same results.

```
root@machine# time vips copy bizz_2176220.pdf x.jpg  --vips-tile-height=4096

real    0m1.898s
user    0m1.829s
sys     0m0.072s
root@machine# time vips copy bizz_2176220.pdf x.jpg  --vips-tile-height=128 

real    0m1.857s
user    0m1.827s
sys     0m0.036s

```

This is PDF file: https://img.folders.eu/live/publsh/bizz/217/62/20/bizz_2176220.pdf

Also I am not able to extract specific page using `page` argument.

**Comment by jcupitt** [comment]
Hello @adityapatadia, please open a new issue.
