### ISSUE TITLE
Build issue in gtk-doc due to markup error

### ISSUE THREAD

**Issue by mayoung** [jcupitt/libvips#382]
I was trying to build vips which failed during the gtk-doc stages. I traced the problem to libvips/conversion/premultiply.c and libvips/conversion/unpremultiply.c which have |] rather than ]| . 
I have attached a possible patch to illustrate the error.

[markupfix.txt](https://github.com/jcupitt/libvips/files/126725/markupfix.txt)

**Comment by jcupitt** [comment]
Ooops! Thank you very much @mayoung
