### ISSUE TITLE
An Amalgamation

### ISSUE THREAD

**Issue by gaillard** [jcupitt/libvips#383]
It would be great if you could produce an amalgamation like the sqlite one so it is easy to include in other projects. Is that feasible?

**Comment by jcupitt** [comment]
Hi @gaillard, for Windows there's an all-in-one binary. It has all the DLLs, libs and headers you need to use vips in your project. It should work well in a VS project. 

http://www.vips.ecs.soton.ac.uk/supported/current/win32/

It's not an easy thing to make, it's 18 other projects patched and compiled together, it's much, much more complicated than sqlite. It would be very hard (or impossible?) to make a single source tree that could be included. 

If you want to try building it yourself, here's the thing we use to build:

https://github.com/jcupitt/build-win64

I would guess it would be at least a week's work by an experienced dev to reproduce that in VS. And then every time one of the 18 projects that make up vips changes, you will need to do at least part of that week's work again.

On linux and os x, vips is in the package managers, so it's just `brew install vips` or whatever to add it to your project and keep it updated, there's no need for an all-in-one.

**Comment by gaillard** [comment]
Hi @jcupitt, so I'm trying to setup a cross compile - custom toolchain :( - in docker. Currently I have zlib, libjpeg-turbo and libpng being built correctly. However the vips configure is telling me I will need glib-2.0 >= 2.6 gmodule-2.0 libxml-2.0 gobject-2.0 as well. But it looks like glib has a bunch of dependencies too, so I am losing this battle, any suggestions as to how to get vips built?

**Comment by jcupitt** [comment]
Sorry, it's just a huge, hairy thing :-( there's no easy way. The build-win64 system compiles 18 packages from source and downloads pre-compiled binaries for another 7. Some of those pre-compiled binaries may depend on more than one other package, I don't know.

On the upside, you won't need all those. I doubt if you'll want ImageMagick import, or FITS import. The set of minimal packages for vips is relatively small, just glib-2.0 and libxml-2.0, plus libraries for any image file formats you need. 

I think I would try to modify the build-win64 system. It uses jhbuild, which is pretty flexible, you should be able to get it to drive your toolchain. You edit this file:

https://github.com/jcupitt/build-win64/blob/master/8.2/jhbuildrc#L23

And change the definitions in the obvious way. There are lots of comments. You can use the build-win64 Dockerfile to make the build environment for you.

If your target system is very strange, perhaps glib-2.0 would be the first thing to try. If you can't get that to build, vips is probably a non-starter :(

**Comment by lovell** [comment]
@gaillard https://github.com/lovell/sharp/blob/master/packaging/lin/Dockerfile in conjunction with https://github.com/lovell/sharp/blob/master/packaging/build.sh#L21-L24 builds libvips and a number of its dependencies as shared libraries.

**Comment by gaillard** [comment]
That docker file helped, I have written my own now that supports cross compiles. It differs a good bit though from that one. I'll get it up on github at some point soon.
