### ISSUE TITLE
Unable to open JP2 images

### ISSUE THREAD

**Issue by bithive** [jcupitt/libvips#385]
I had vips-7.38.5 working with JPEG2000 images via ImageMagick on Debian 7.9.  I'm trying to recreate this situation on Debian 8.3 but I always get `mat2vips: unsupported class type 5` when trying to use `vips dzsave`, even though the ImageMagick utilities like `convert` work just fine.

Is there any advice you can provide?  I've tried vips-7.38.5, vips-7.40.6, and vips-8.2.2 and I've also tried the various `--with-magickpackage` options, to no avail.

My `./configure` output always contains these lines:

```
file import with libMagick:             yes
file import/export with libjpeg:        yes
```

I did have to rebuild ImageMagick from source to get it working, so, I believe I have all the dependencies installed, but I always get `mat2vips: unsupported class type 5` no matter how I try to build VIPS.

**Comment by jcupitt** [comment]
Hi @bithive, thank you for the report.

`mat2vips` is part of the Matlab loader. Looking at the code, it seems that `libmatio`, the decoding library that vips uses, thinks it can decode at least some JP2 images. vips is then passing the file to the Matlab loader and getting the error.

I'll see if there's some way I can make the `is_a` test for matlab files more specific. As a workaround, you could build without Matlab support, try:

```
./configure --without-matio ...
```

**Comment by jcupitt** [comment]
I think that patch should fix it, it makes the test for is-matlab much more specific. Would you be able to test?

**Comment by bithive** [comment]
Thanks for the quick response.  Unfortunately I get a segfault running `vips dzsave` against my JP2 image when I compile `--without-matio` (both 7.38.5 and 8.2.2), and with the patch applied to 8.2.2 (with and without matio).  Running with `strace` indicates it's crashing right after it starts to read the file.

Here is an example file: http://people.reed.edu/~meinzerj/vips-test/4888.jp2

**Comment by jcupitt** [comment]
Thanks for the test file, I'll have a look.

**Comment by jcupitt** [comment]
It's beginning to look like an openjpeg bug, I'm seeing some strange behaviour in valgrind. I'll keep digging, though I'm off on holiday tomorrow. 

Within the last year (I think) IM switched from openjpeg 1.5 to openjpeg 2.1, so downgrading to IM 6.8.x might be a workaround in the short term.

**Comment by bithive** [comment]
Thanks much for looking into this.  I will try IM 6.8.x this week and leave my findings in this thread.

**Comment by jcupitt** [comment]
I think I've found the problem: it's a library versioning issue.

IM 6.9.x has switched to openjpeg 2.1, but the Debian packages of some of the other projects that vips uses, like openslide, are still on the openjpeg 1.5 API. This means, if you have IM and openslide both enabled, vips will link to both versions of the library. 

Sadly, when openjpeg changed their API they did not change their symbol prefix, so both libraries define things like `opj_create_decompress()`. So you can't link to both at the same time without causing crashes. I guess this is why Debian currently ship an IM package with jp2 disabled. 

The solution is to rebuild everything with openjpeg 2.1, or to just disable vips options which will pull in something that links to openjpeg 1.5. 

I built openjpeg2.1 like this:

```
cmake . -DCMAKE_INSTALL_PREFIX=/home/john/vips -DCMAKE_BUILD_TYPE=Debug
```

Then IM 6.9.3-4 like this:

```
CFLAGS="-g -Wall" CXXFLAGS="-g -Wall" ./configure --prefix=/home/john/vips --with-modules
```

Then vips master like this:

```
CFLAGS="-g -Wall" CXXFLAGS="-g -Wall" ./configure --prefix=/home/john/vips --without-openslide
```

And it seems to work!

```
$ vipsheader 4888.jp2 
4888.jp2: 4368x2912 uchar, 3 bands, srgb, magickload
```

**Comment by bithive** [comment]
Success, rebuilding VIPS `--without-openslide` seems to do the trick.  Thanks again for your help!

For other Debian users in my situation, the workaround seems to be along these lines:

1. `apt-get build-dep imagemagick`
2. `apt-get install  libopenjpeg-dev libopenjp2-7-dev`
3. `apt-get --build source imagemagick`
4. `dpkg -i *.deb` (install the packages from the last step)
5. `apt-get build-dep libvips38`
6. Manually build VIPS `--without-openslide`

**Comment by jcupitt** [comment]
Great, I'll close.

Do you need both `libopenjpeg-dev` and `libopenjp2-7-dev` in your step 2? `libopenjpeg-dev` is the old openjpeg 1.5 API, which I think is what was causing the problems.
