### ISSUE TITLE
Vips is taking whole lot of space in memory.

### ISSUE THREAD

**Issue by shilpi230** [jcupitt/libvips#386]
I am using vips thumbnail for images of resolution 5k and its taking too too long. And because sucking all memory its bringing my server also down. :( Is there anyway we can optimise it more?

**Comment by jcupitt** [comment]
Oh dear, I'm sorry you're having problems. 

It ought to be fine, for example, on my laptop with a 10,000 x 10,000 pixel RGB image I see:

```
$ time vipsthumbnail wtc.jpg
real	0m0.320s
user	0m0.316s
sys	0m0.004s
peak memory 30MB
$ time vipsthumbnail wtc.tif
real	0m1.222s
user	0m1.144s
sys	0m0.080s
peak memory: 50MB
```

I measured memory by running this command;

```
$ for i in {1..10000}; do ps aux | grep vipsth | grep -v grep; sleep 0.01; done
```

And watching the RSS column.

What types of image are you thumbnailing, what version of vips are you using, how did you install it, what platform are you running on, what parameters are you giving vipsthumbnail, how much memory use are you seeing, how much CPU use are you seeing?

**Comment by shilpi230** [comment]
Ohh hey @jcupitt I am really sorry just now only I saw your reply, was busy somewhere.  My some of files are like 25000x25000 :P I guess because of that its taking too much of memory, but for now I have stopped processing those huge files. :)

**Comment by jcupitt** [comment]
It should be fine even with huge files. For example, on this laptop I see:

```
$ vipsheader eso1242a-pyr.tif 
eso1242a-pyr.tif: 108199x81503 uchar, 3 bands, srgb, tiffload
$ time vipsthumbnail eso1242a-pyr.tif 
memory: high-water mark 83.50 MB
real	5m13.006s
user	4m59.104s
sys	0m1.744s
```

It takes a while for a huge file, but it should work, and it shouldn't use much memory.

I need to be able to reproduce your problem, can you tell me how you got the bad behaviour?

**Comment by jcupitt** [comment]
Hi again, did you make any progress on this? Please reopen if you still have problems.
