### ISSUE TITLE
`make install` should do an `ldconfig` at the end

### ISSUE THREAD

**Issue by jf** [jcupitt/libvips#389]
Or else the following results:
```
vips: error while loading shared libraries: libvips.so.42: cannot open shared object file: No such file or directory
```

**Comment by jcupitt** [comment]
I'm not sure this is a good idea. ldconfig is only right on some platforms and in some cases, it depends how the system has been set up and how configure was run. I think it would be difficult to make a script that only invoked it when it was really necessary.

**Comment by lovell** [comment]
As nice as it would be to have `ldconfig` run *automagically* on the occasions when I'm `make install`ing libvips to `/usr` as `root` on Linux, I agree with John here. `make install` can do so to any location and as any user.

**Comment by jf** [comment]
This is new to me. Only right on some platforms? Could you point me to where I might find out more about this? I proposed an ldconfig because I'm used to seeing it when compiling stuff (`make install` always includes some note about the libraries at the end, and as I gather from the text, doing an `ldconfig`). On whether it's necessary: even if it's not, is there any harm in running it?

**Comment by jf** [comment]
@lovell `make install` can do any number of things. Is there anything specific to `ldconfig` that you're worried about?

**Comment by jcupitt** [comment]
Yes, I usually install vips to a private prefix, like `~/vips`, so `make install` doesn't need root and I don't need ldconfig. Or I cross-compile to Windows, so again, no ldconfig. 

As @lovell says, there are some circumstances in which you do need to run it, but not many. The message you sometimes get about ldconfig is generated by libtool, but even libtool, a huge, mature and well-tested thing, is too scared to run ldconfig for you in case it makes a mistake and trashes something. 

There's maybe a philosophical thing too: people expect install to just copy files. Any reconfiguring of the target system is usually done by the package manager or by the user after install has completed.

**Comment by jcupitt** [comment]
I'll close, but thank you for the idea.

**Comment by jf** [comment]
got it. Thanks for the explanation!
