### ISSUE TITLE
checking for not found.

### ISSUE THREAD

**Issue by gaillard** [jcupitt/libvips#390]
How do we check for file not found when going through jpeg/png load? Without matching against the string returned from vips_error_buffer.

**Comment by jcupitt** [comment]
You can only get success/fail from the file loaders, and they can fail for a great many reasons. 

From C/C++ I would use the standard `access()` function to check for file exists.

**Comment by jcupitt** [comment]
I think the design problem here is that image file load libraries don't all support error codes that expose this kind of information. If libvips wanted to have a particular code that it could reliably return for file not found, it would need to call `access()` itself, and then what's the point, why not push that overhead on to applications that really need that information.

**Comment by gaillard** [comment]
I am already checking right before, but of course that is racy but it will suffice. Was really wondering if I was missing something. So far the library is performing very well, thanks!

**Comment by jcupitt** [comment]
Glad it's working, I'll close.

Yes, it's a bit racy, but I think that's unavoidable given the diversity of image load libraries.

If you really want to be race-proof, one solution would be to load the file to memory and then decode from there. You'll take a performance hit though, and limit the range of image formats you can support.
