### ISSUE TITLE
Adding text to image

### ISSUE THREAD

**Issue by zippy84** [jcupitt/libvips#391]
I would like to add a simple text to an existing image. The image is of type JPG or TIF. The text should be white and aligned to the upper left corner of the image.  It is a simple task, but not in vips. What is the best way to do this in C?

**Comment by jcupitt** [comment]
Hi @zippy84, I made you a sample program:

https://gist.github.com/jcupitt/c725865e90850e15b0a4

It's not perfect, it won't work for 16-bit TIFFs, for example (the text will be too dark), but it should be fine for 8-bit RGB, RGBA and CMYK images. You can put pango markup in the argument, eg.

```
$ ./a.out ~/pics/wtc.jpg hello.tif "hello <i>world</i>"
```

What kinds of image do you need to be able to write on?

**Comment by jcupitt** [comment]
It's much simpler in Python, I don't know if that's an option for you:

```python
#!/usr/bin/python
        
import sys
from gi.repository import Vips
 
text = Vips.Image.text(sys.argv[3], width = 500, dpi = 300)
im = Vips.Image.new_from_file(sys.argv[1], access = Vips.Access.SEQUENTIAL)
im = text.ifthenelse(255, im, blend = True)
im.write_to_file(sys.argv[2])
```

**Comment by zippy84** [comment]
Thanks for your very fast response and the detailed answer. It solves my problem. In addition, I would like to know, how to set any color instead of white? The color is RGB in its hexadecimal form.

**Comment by jcupitt** [comment]
In Pythion you can just pass an array, so;

```python
im = text.ifthenelse([255, 0, 0], im, blend = True)
```

would be red. 

In C you need to make a red pixel, I updated the gist.

This will only work for RGB images, it won't work for RGBA or CMYK or mono. For them, you'd need to decide how you wanted to represent the colour red and how you wanted to handle transparency.

vips is rather a low-level library :(

**Comment by jcupitt** [comment]
There's a watermarking example here:

https://gist.github.com/jcupitt/db972e738cfacdf8055f

That tries to handle mono and RGBA nicely. It would need more work to handle CMYK and 16-bit as well.

**Comment by jcupitt** [comment]
I'll close. Please reopen if it's not working.

**Comment by zippy84** [comment]
Your example with an arbitray color does not work. The whole image loses his color. I used our example in C.

**Comment by jcupitt** [comment]
Ooops, sorry, I'm sure I tested it. 

You need to tag the background colour image as sRGB, or vips will assume it's mono with some alpha. Add:

```
                vips_copy( t[4], &t[5], "interpretation", VIPS_INTERPRETATION_sRGB, NULL )
```

I've updated the gist.

**Comment by sergeevabc** [comment]
So there is no easy command-line way to add a piece of text to image?
`$ vips add_text -font X -size Y -coordinates Z "Message" in.png out.png`

**Comment by jcupitt** [comment]
Hi again @sergeevabc,

This has improved since 2016. You can now write:

```
vips text label.v "hello world!" --dpi 600 --rgba
vips composite2 base.png label.v result.png over --x 400 --y 500
```

The libvips command-line is deliberately very limited. Imagemagick has an extremely complex command line driver, it's almost a complete programming environment, and needs a *lot* of development effort to maintain.

The idea behind the design of libvips was to keep it very simple, make it easy to call from other programming languages (the core of the libvips python binding is just 300 lines of pure python), and let them handle the programming part. It's less effort for us, and better for users too, since they don't need to learn yet another programming system, just an API.
