### ISSUE TITLE
Getting exif datas from jpeg

### ISSUE THREAD

**Issue by Nadot** [jcupitt/libvips#394]
Bonjour
Using libvips 8.2, c++

How to get a list of all exif tags in a jpeg ?

For instance,  `cout << "Orientation : " << in.get_string("exif-ifd0-Orientation") << endl; `
is OK.

I can reformulate my question :
How to get all the tags like "exif-ifd0-Orientation" in libVips?

Merci

**Comment by jcupitt** [comment]
Hi @Nadot, try `vipsheader -a something.jpg` at the command line, it'll list all the tags in a file.

**Comment by Nadot** [comment]
Merci

How to do the same thing programmatically ?
Something like
`Vimage image; image.getHeaderList;`

**Comment by jcupitt** [comment]
You have to use the C API:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-header.html#vips-image-map

Something like:

```C++
VImage fred = ....
void *my_data = ...

vips_image_map(fred.get_image(), my_header_func, my_data);

void *
my_header_func(VipsImage *image,
                   const char *field,
                   GValue *value,
                   void *my_data)
{
        char *str_value;

        str_value = g_strdup_value_contents(value);
        printf("%s = %s", field, str_value);
        g_free(str_value);

        return NULL;
}
```

**Comment by Nadot** [comment]
Fine. That works !

I have a warning :
`vips warning: VipsJpeg: bad exif meta "exif-ifd3-GPSVersionID"`
for a jpeg where
`exif-ifd3-GPSVersionID+ => 2.3.0.0 (2.3.0.0, Byte, 4 components, 4 bytes)`

A version of libexif ? other ?

**Comment by jcupitt** [comment]
Oh, sorry, I don't know. Could you put that jpeg up somewhere for me to have a look at?

**Comment by Nadot** [comment]
I suppose the 2.3.0.0 version is the last version of exif : 
[http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf ](url)
[http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html](url)

Look at ftp : nadot.net robert-depot anonyme 21
IMG_0073.JPG

nb: the warning is pactically not very important ( only for consistency)

**Comment by jcupitt** [comment]
I had a look and it seems `exif_tag_from_name("GPSVersionID")` is returning 0, that is, unknown tag. But I have libexif 0.6.21, and that does have `GPSVersionID` in the tag table. Strange!

**Comment by jcupitt** [comment]
Looks like a bug in libexif. `EXIF_TAG_GPS_VERSION_ID` has value 0, but that's what `exif_tag_from_name()` returns for not-found errors.

Someone's logged this already:

https://sourceforge.net/p/libexif/bugs/100/

Six years ago :-( maybe vips should switch exif libraries.

**Comment by jcupitt** [comment]
I'll close, please reopen if it's not working.

**Comment by ottob** [comment]
Ran into this today with an image that vipsthumnail auto rotate didn't handle properly:

```
$ vipsthumbnail -t -s 100 20160323_130313.jpg 
vips warning: VipsJpeg: bad exif meta "exif-ifd3-GPSVersionID"
```
Thumbnail (looks ok here, but not when viewed in preview on OSX):
![tn_20160323_130313](https://cloud.githubusercontent.com/assets/67104/14464614/c2f5fc24-00cf-11e6-8ebe-8d0b72c66ee3.jpg)

Original:
http://s000.tinyupload.com/index.php?file_id=64680758736264335982

**Comment by jcupitt** [comment]
I think I've fixed this in git master, thank you for the test image.

The problem was that your image has two `Orientation` tags. It's now much more careful about removing them all after applying the rotation. This fix will be in 8.3, due in a day or two.

As a workaround, you can write stripped thumbnails. This should work:

```
$ vipsthumbnail -t -s 100 20160323_130313.jpg -o thumb.jpg[strip]
```

**Comment by tsmgeek** [comment]
I am having the same issue on latest build.

`vips warning: exif: bad exif meta "exif-ifd3-GPSVersionID"`

**Comment by jcupitt** [comment]
Hello @tsmgeek, that warning is caused by a bug in the EXIF parsing library that libvips uses. They have it on their system:

https://sourceforge.net/p/libexif/bugs/100/

Logged eight years ago and no one has fixed it :(

**Comment by maxvoltar** [comment]
+1 to this.

**Comment by jcupitt** [comment]
It's an annoying message, but it's harmless, in case anyone is concerned.

**Comment by kleisauke** [comment]
It looks like https://sourceforge.net/p/libexif/bugs/100/ is now by design instead of being classified as a bug, see:
https://github.com/libexif/libexif/blob/b03f1e1b49732dbf14d3760b12147f7722548493/libexif/exif-tag.h#L217-L218

@jcupitt Do you think this patch makes sense? 
```diff
From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: Kleis Auke Wolthuizen <github@kleisauke.nl>
Date: Fri, 17 Jul 2020 20:26:51 +0200
Subject: [PATCH 1/1] Ensure that the GPSVersionID exif tag is correctly parsed

See: https://sourceforge.net/p/libexif/bugs/100/

diff --git a/libvips/foreign/exif.c b/libvips/foreign/exif.c
index 1111111..2222222 100644
--- a/libvips/foreign/exif.c
+++ b/libvips/foreign/exif.c
@@ -1204,7 +1204,11 @@ vips_exif_image_field( VipsImage *image,
 		return( NULL ); 
 	}
 
-	if( !(tag = exif_tag_from_name( p + 1 )) ) {
+	/* the tag not found value cannot be distinguished from 
+	 * exif-ifd3-GPSVersionID, argh
+	 */
+	if( !(tag = exif_tag_from_name( p + 1 )) &&
+		strcmp( field, "exif-ifd3-GPSVersionID" ) != 0 ) {
 		g_warning( _( "bad exif meta \"%s\"" ), field );
 		return( NULL ); 
 	}
```

**Comment by jcupitt** [comment]
Haha yes perhaps we should not just wait for a fix. Sure, let's put this patch in, thanks Kleis.

**Comment by jcupitt** [comment]
(this improvement will be in libvips 8.10)

**Comment by jcupitt** [comment]
Hang on, is this somehow fixed already? Without this patch, I see:

```
$ vipsheader -a test.jpg  | grep GPSVer
exif-ifd3-GPSVersionID: 2.0.0.0 (2.0.0.0, Byte, 4 components, 4 bytes)
```

ie. it's reading the `GPSVersionID` tag correctly. This is on Ubuntu 20.04 with the standard exif package.

**Comment by kleisauke** [comment]
Ah, the commit message is a bit misleading, I didn't test it properly. Try this:
```bash
$ vips copy test.jpg x.jpg

(vips:17404): VIPS-WARNING **: 00:07:35.346: bad exif meta "exif-ifd3-GPSVersionID"
```
(that's with libexif 0.6.22)

This problem therefore only occurs when re-attaching EXIF-data. Using `x.jpg[strip]` doesn't seem to help.

**Comment by jcupitt** [comment]
Ahh, gotcha. OK, applied!

**Comment by kleisauke** [comment]
Thanks!

As an aside, I was wondering if the `vips__exif_update` call is necessary when the `strip` option is enabled? 
https://github.com/libvips/libvips/blob/0a23bf35780f409c7f7d59bd4ea969345c9327b1/libvips/foreign/vips2jpeg.c#L238-L242

**Comment by jcupitt** [comment]
Yes, that's true. I moved the rebuild nearer the save so it can be skipped.

**Comment by kleisauke** [comment]
Great! Perhaps `heifsave` needs also a `!save->strip &&` here (?):
https://github.com/libvips/libvips/blob/3b57e1345230cd400b008e76fb1d8614be2cb4df/libvips/foreign/heifsave.c#L335-L336

I'll redo the micro benchmarks mentioned in https://github.com/libvips/libvips/issues/1290 to check if these changes could improve performance.

**Comment by jcupitt** [comment]
OK, did that one too. Phew!

**Comment by kleisauke** [comment]
Here's a benchmark with saving a stripped version of a JPEG image with large amount of EXIF data (65533 bytes). See commit https://github.com/kleisauke/vips-microbench/commit/90d8522bb74cccccc2adf2f7faae8c48ce38ec72 for details.

<details>
  <summary>Benchmark results</summary>

`v8.10.0-rc1` tag
```bash
$ ./bin/vips-microbench-exif --benchmark_repetitions=10
2020-07-19 12:23:14
Running ./bin/vips-microbench-exif
Run on (6 X 4300 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x6)
  L1 Instruction 32 KiB (x6)
  L2 Unified 256 KiB (x6)
  L3 Unified 9216 KiB (x1)
Load Average: 0.67, 0.59, 0.55
---------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations
---------------------------------------------------------------------------------------
BM_jpeg_exif_strip/original/real_time               131 ms         9.76 ms            5
BM_jpeg_exif_strip/original/real_time               129 ms         9.61 ms            5
BM_jpeg_exif_strip/original/real_time               129 ms         9.82 ms            5
BM_jpeg_exif_strip/original/real_time               128 ms         9.70 ms            5
BM_jpeg_exif_strip/original/real_time               128 ms         9.97 ms            5
BM_jpeg_exif_strip/original/real_time               128 ms         9.87 ms            5
BM_jpeg_exif_strip/original/real_time               128 ms         9.95 ms            5
BM_jpeg_exif_strip/original/real_time               129 ms         9.82 ms            5
BM_jpeg_exif_strip/original/real_time               129 ms         10.0 ms            5
BM_jpeg_exif_strip/original/real_time               129 ms         9.98 ms            5
BM_jpeg_exif_strip/original/real_time_mean          129 ms         9.85 ms           10
BM_jpeg_exif_strip/original/real_time_median        129 ms         9.84 ms           10
BM_jpeg_exif_strip/original/real_time_stddev      0.775 ms        0.131 ms           10
```

`master` branch
```bash
$ ./bin/vips-microbench-exif --benchmark_repetitions=10
2020-07-19 12:29:22
Running ./bin/vips-microbench-exif
Run on (6 X 4300 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x6)
  L1 Instruction 32 KiB (x6)
  L2 Unified 256 KiB (x6)
  L3 Unified 9216 KiB (x1)
Load Average: 0.28, 0.33, 0.47
---------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations
---------------------------------------------------------------------------------------
BM_jpeg_exif_strip/original/real_time               128 ms         9.43 ms            5
BM_jpeg_exif_strip/original/real_time               128 ms         9.50 ms            5
BM_jpeg_exif_strip/original/real_time               129 ms         9.41 ms            5
BM_jpeg_exif_strip/original/real_time               128 ms         9.51 ms            5
BM_jpeg_exif_strip/original/real_time               127 ms         9.63 ms            5
BM_jpeg_exif_strip/original/real_time               128 ms         9.74 ms            5
BM_jpeg_exif_strip/original/real_time               127 ms         9.47 ms            5
BM_jpeg_exif_strip/original/real_time               128 ms         9.48 ms            5
BM_jpeg_exif_strip/original/real_time               127 ms         9.63 ms            5
BM_jpeg_exif_strip/original/real_time               127 ms         9.53 ms            5
BM_jpeg_exif_strip/original/real_time_mean          128 ms         9.53 ms           10
BM_jpeg_exif_strip/original/real_time_median        128 ms         9.51 ms           10
BM_jpeg_exif_strip/original/real_time_stddev      0.564 ms        0.105 ms           10
```
</details>

So, it's a tiny benefit.

**Comment by jcupitt** [comment]
I'm impressed it's even measurable heh. Anyway, a small improvement.
