### ISSUE TITLE
How to process files having brackets in their name?

### ISSUE THREAD

**Issue by shilpi230** [jcupitt/libvips#395]
I am trying to create thumbnail for a file with output file name as `thumb (900).jpeg`

```vipsthumbnail "input_file" -s "250x250" -o "thumb (900).jpeg[background=255]"```

It works fine in ZSH terminal but in bash its throwing this error 

```VipsForeignSave: "thumb (900).jpeg[background=255]" is not a known file format```

**Comment by jcupitt** [comment]
Oh dear, that's a bug. I've fixed it with the patch above. I'll do a new vips release including this fix.

Thanks you very much for reporting this @shilpi230

**Comment by jcupitt** [comment]
As a short-term workaround, you could thumbnail in two stages:

```
vipsthumbnail "input_file" -s "250x250" -o x.jpg[background=255]
mv x.jpeg "thumb (900).jpeg"
```

**Comment by shilpi230** [comment]
Thank you so much @jcupitt for fixing it :) Let us know when you are releasing new vips waiting for pdf conversion also :+1: Till then
