### ISSUE TITLE
combining 4 bands into one RGB image

### ISSUE THREAD

**Issue by apacheark** [jcupitt/libvips#397]
I am trying to convert some python/numpy code over to using VIPS with the python binding.
I am using vips8.2 on ubuntu14.04.
The function I am trying to recreate is given below.  n summary, the function combines 4 bands (0-3) into an RGB image.

However, I am not sure how/if I can perform math on the individual pixels in an image.  Any help would be appreciated.

Python code to convert to using VIPS:
'def merge4ChannelsToRGB(bands):

    rchan = np.zeros(bands[0].shape)
    gchan = np.zeros(bands[0].shape)
    bchan = np.zeros(bands[0].shape)

    rchan += bands[0]
    gchan += bands[1]
    bchan += bands[2]
    rchan += bands[3]
    gchan += bands[3]
    bchan += bands[3]

    for r in range(rchan.shape[0]):
        for c in range(rchan.shape[1]):
            #scale = np.sqrt(rchan[r,c]**2+gchan[r,c]**2)
            while rchan[r,c] > 255.0 or gchan[r,c] > 255.0 or bchan[r,c] > 255.0:
                scale = 255.0 / max(rchan[r,c],gchan[r,c],bchan[r,c])
                rchan[r,c] *= scale
                gchan[r,c] *= scale
                bchan[r,c] *= scale 
    return [rchan,gchan,bchan]
'

**Comment by jcupitt** [comment]
Hi @apacheark, you don't do math on individual pixels, that would be too slow, you do math on whole images. Something like (untested):

```python
r = bands[0] + bands[3]
g = bands[1] + bands[3]
b = bands[2] + bands[3]

# a float image giving a scale factor for each pixel
scale = 255.0 / max(r, g, b)

# a boolean image tagging high scales
mask = scale > 1

# use the mask to chose between our original scale image
# and a constant 1 ... this will chop off any >1 scales
scale = mask.ifthenelse(1, scale)

# you could also write "(scale > 1).ifthenelse(1, scale)", of course

return [r * scale, g * scale, b * scale]
```

**Comment by apacheark** [comment]
Thanks for your explanation and example code.
I implemented your suggestion (see code below) and I am getting the following values:
The original image band max values (RGB-4th color): 65520.0 65520.0 63152.0 26112.0
The scaled image band values (RGB): 69792.0 71856.0 65535.0039062

I don't understand why the max values in each band are above 65535.0 AFTER I have applied the scales (second print statement).
 
    ' r = rim + yim
    g = gim + yim
    b = bim + yim
    print rim.max(),gim.max(),bim.max(),yim.max() # orig image bands

    # a float image giving a scale factor for each pixel
    #scale = 255.0 / max(r, g, b)
    scale = 65535.0 / max(r, g, b) # srgb image (16 bits)

    # a boolean image tagging high scales
    mask = scale > 1

    # use the mask to chose between our original scale image
    # and a constant 1 ... this will chop off any >1 scales
    scale = mask.ifthenelse(1, scale)

    # you could also write "(scale > 1).ifthenelse(1, scale)", of course
    #return [r * scale, g * scale, b * scale]
    rmpimg= r*scale
    gmpimg= g*scale
    bmpimg= b*scale
    print rmpimg.max(),gmpimg.max(),bmpimg.max()`

**Comment by jcupitt** [comment]
Oh, I didn't know these were 16-bit images. I'll have a look.

**Comment by jcupitt** [comment]
Oh, I think `max(r, g, b)` isn't behaving as I expected. Swap the `max(r, g, b)` for:

```python
r = rim + yim
g = gim + yim
b = bim + yim

m1 = (r > g).ifthenelse(r, g)
m2 = (m1 > b).ifthenelse(m1, b)

# a float image giving a scale factor for each pixel
scale = 255.0 / m2
```

I wonder what `max()` was calculating, I'll look into it.

**Comment by jcupitt** [comment]
Oh, of course `if image_a > image_b:` is always true, so `max(r, g, b)` is just `r`.

Anyway, use two `.ifthenelse()` instead.

**Comment by apacheark** [comment]
Thanks, that did the trick for the scaling part. having an issue with colors of resulting image.
I am then combining the scaled rgb bands (max of 65535) using bandjoin and then using the following command to make sure that the resulting image is rgb16.  This new image has max=65535 an min=1696, hoewver when I write_to_file("test.jpg") I see only a fully white image.  vipsheader says that test.jpg is a uchar, 3 bandsrgb, jpegload image.

`cropimg=cropimg.copy(interpretation='rgb16') `

**Comment by jcupitt** [comment]
Actually, there's a neater way, you can write:

```
mx = Vips.Image.bandrank([r, g, b], index = 2) 
```

bandrank puts an array of images on top of each other, then at each point sorts the pixels and picks out the one at `index`. So 2 will be the max at each point.

**Comment by jcupitt** [comment]
Hmm, this works for me:

```
im = im.copy(interpretation = 'rgb16')
```

What version of vips are you using?

**Comment by jcupitt** [comment]
Here's a complete program that works for me for 8 or 16-bit input and 8 or 16-bit output.

```python
#!/usr/bin/python

import sys
from gi.repository import Vips

im = Vips.Image.new_from_file(sys.argv[1])

if im.bands != 4:
    print 'four band images only'
    sys.exit(1)

rim = im[0]
gim = im[1]
bim = im[2]
yim = im[3]

r = rim + yim
g = gim + yim
b = bim + yim

mx = Vips.Image.bandrank([r, g, b], index = 2)

# max pixel value for this image type
if im.interpretation == Vips.Interpretation.RGB16:
    max_value = 65535
else:
    max_value = 255

# a float image giving a scale factor for each pixel
scale = max_value / mx

# use the mask to chose between our original scale image
# and a constant 1 ... this will chop off any >1 scales
scale = (scale > 1).ifthenelse(1, scale)

rmpimg = r * scale
gmpimg = g * scale
bmpimg = b * scale

# print rmpimg.max(), gmpimg.max(), bmpimg.max()

out = rmpimg.bandjoin([gmpimg, bmpimg])

# back to the start format again
# this shouldn't be necessary, but there's vips bug converting float rgb16 ->
# srgb that this fixes
out = out.cast(im.format)

out.write_to_file(sys.argv[2])
```

The cast at the end is necessary because of a vips bug. It gets confused if you have a float image (which you will after the scale) tagged as rgb16, it fails to convert to 8-bit correctly. Casting the float down to u16 helps it.

I'll fix this problem in master.

**Comment by jcupitt** [comment]
Final version of the program. This is for vips master, you'll need to change the bandrank and add a cast for vips 8.2 and earlier.

```python
#!/usr/bin/python

import sys
from gi.repository import Vips

if len(sys.argv) != 3:
    print 'usage %s infile outfile' % sys.argv[0]
    sys.exit(1)

im = Vips.Image.new_from_file(sys.argv[1], 
                              access = Vips.Access.SEQUENTIAL)

# ask vips to report peak memory use
Vips.leak_set(True)

if im.bands != 4:
    print 'four band images only'
    sys.exit(1)

r = im[0] + im[3]
g = im[1] + im[3]
b = im[2] + im[3]

mx = r.bandrank([g, b], index = 2)

# max pixel value for this image type
if im.interpretation == Vips.Interpretation.RGB16:
    max_value = 65535
else:
    max_value = 255

# a float image giving a scale factor for each pixel
scale = max_value / mx

# use the mask to chose between our original scale image
# and a constant 1 ... this will chop off any >1 scales
scale = (scale > 1).ifthenelse(1, scale)

# rejoin bands and scale them
out = r.bandjoin([g, b]) * scale

out.write_to_file(sys.argv[2])
```

**Comment by apacheark** [comment]
I am using vips 8.2 and will give your first set of changes a try!  Very much appreciate the quick replies and informative answers.

**Comment by apacheark** [comment]
I am having an issue with the following code. The blah.jpg image produced only shows the rmpimg image.  
The rim through yim images are all GREY16 as they are generated in greyscale.   I combine them into the r,g,b images and then use your suggested code to find the max and scale images. I think the problem is that I am not casting to u16 propely (in the vips-python syntax).  It is something like im.cast(uint16)?  Not sure how to define the u16 type for the cast method.

' 

    r = rim + yim
    g = gim + yim
    b = bim + yim
    mx = Vips.Image.bandrank([r, g, b], index = 2)

    scale = 65535 / mx

    # use the mask to chose between our original scale image
    # and a constant 1 ... this will chop off any >1 scales
    scale = (scale > 1).ifthenelse(1, scale)

    rmpimg= r*scale
    gmpimg= g*scale
    bmpimg= b*scale
    myimg2=rmpimg.bandjoin([gmpimg,bmpimg])
    myimg2 = myimg2.cast(rim.format)
   
    myimg2.write_to_file("blah.jpg")
'

**Comment by apacheark** [comment]
I found some documents on vips that had the enum for uint16.  So, I used im.cast(2) and that did the trick.  Does that make sense?

**Comment by jcupitt** [comment]
You can do `im.cast("ushort")` or `im.cast(Vips.BandFormat.USHORT)`, or 2.

**Comment by jcupitt** [comment]
And yes, you need to tag your images as RGB if you want colour output, otherwise the jpeg saver will think it's greyscale + alpha. 

Add `im.copy(interpretation = "srgb")` before the write.

**Comment by apacheark** [comment]
Thanks very much.  I now have everything working as expected!  For future reference, this is the code that works for combining four grey16 images (rim through yim) into one RGB image.

    # rim,gim,bin,yim are grey16 images
    r = rim + yim
    g = gim + yim
    b = bim + yim

    # a float image, m2, with the maximum values from the three images, rgb
    m1 = (r > g).ifthenelse(r, g)
    m2 = (m1 > b).ifthenelse(m1, b)

    # a float image giving a scale factor for each pixel
    scale = 65535.0 / m2

    # a boolean image tagging high scales
    mask = scale > 1

    # use the mask to chose between our original scale image
    # and a constant 1 ... this will chop off any >1 scales
    # you could also write "(scale > 1).ifthenelse(1, scale)"
    scale = mask.ifthenelse(1, scale)

    #myimg2=rim.bandjoin([gim,bim])
    myimg2=r.bandjoin([g,b])*scale
    myimg2=myimg2.cast(Vips.BandFormat.USHORT) # necessary for 16-bit images (vips <= v 8.2)
    myimg2.write_to_file"(composite.jpg")

**Comment by jcupitt** [comment]
I'll close, looks like we're done. Please reopen if not.

**Comment by Aiosa** [comment]
I would like to pinpoint the importance of conversion if you don't use RGB/RGBA images. I thought that simply by joining single bands of grayscale images will give me RGBA composition (since `bandjoin()` by name seems to perform the inverse to `bandsplit()` but that's not necessarily true) to save performance when processing the data, but it does band-wise composition (in my case).

```
#get grayscale
a = pyvips.Image.new_from_file("a").copy(interpretation="srgb")[0]
b = pyvips.Image.new_from_file("b").copy(interpretation="srgb")[0]
...
# or create empty band for alpha or any other channell
empty = pyvips.Image.black(vis.width, vis.height, bands=1)
    
a.bandjoin([b, ... empty, ...]).write_to_file("c")

```

This saved me:
https://stackoverflow.com/questions/55460277/pyvips-image-composite-not-working-as-expected, maybe someone will find this useful :)
