### ISSUE TITLE
webp: Add decoder scaling / cropping

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#398]
vips/vipsthumbnail currently supports decoding jpeg at lower resolutions when the size of the target image is smaller.

WebP also supports downscaling and cropping in the decoder, but those features are currently not used.

Here's a small comparison when creating a 128x128 thumbnail from a 10000x10000 source image.

```sh
vips --version
vips-8.3.0-Wed Feb 24 11:39:08 CET 2016

# decode jpeg using libjpeg-turbo HEAD (Feb 10)
vipsthumbnail earth10k-q90.jpg -s 128 -o out-128.tif'[compression=none]'
memory: high-water mark 7.18 MB
0.25s user 0.02s system 99% cpu 0.268 total

# decode png using libpng 1.6.21
vipsthumbnail --vips-leak earth10k.png -s 128 -o out-128.tif'[compression=none]'
memory: high-water mark 32.81 MB
1.41s user 0.63s system 103% cpu 1.970 total

# decode webp using libwebp 0.5.0
vipsthumbnail earth10k-q90.webp -s 128 -o out-128.tif'[compression=none]'
memory: high-water mark 303.27 MB
1.41s user 0.63s system 103% cpu 1.970 total

# decode webp at full res using dwebp (using libwebpdecoder 0.5.0, decode only libwebp)
dwebp earth10k-q90.webp -tiff -quiet -mt -o out-10k.tif
memory: 299 MB RSS
1.10s user 0.50s system 116% cpu 1.373 total

# decode webp at output res using dwebp
dwebp earth10k-q90.webp -tiff -quiet -mt -resize 128 128 -o out-128.tif
memory: 12 MB RSS
0.93s user 0.02s system 131% cpu 0.724 total

# the difference gets larger at lower qualities
vipsthumbnail --vips-leak earth10k-q50.webp -s 128 -o out-128.tif'[compression=none]'
memory: high-water mark 303.27 MB
1.03s user 0.62s system 109% cpu 1.507 total

# dwebp requires only 50% cpu and memory compared to q90
dwebp earth10k-q50.webp -tiff -quiet -mt -resize 128 128 -o out-128.tif
memory: 6 MB RSS
0.56s user 0.01s system 160% cpu 0.353 total
```

So libvips could save lots of memory and get a huge decoding speedup by implementing this features. It also seems that libvips does not use multithreaded webp decoding (max cpu ~100% vs 130% in dwebp), even through it tries to enable it.

The relevant settings can be found in the `dwebp` sources:

* [-mt / use_threads](https://github.com/webmproject/libwebp/blob/master/examples/dwebp.c#L621)
* [-resize / use_scaling](https://github.com/webmproject/libwebp/blob/master/examples/dwebp.c#L636)
* [-crop / use_cropping](https://github.com/webmproject/libwebp/blob/master/examples/dwebp.c#L630)

**Comment by jcupitt** [comment]
Good ideas. Also, the webp decoder should use the incremental decoding API. At the moment it reads the whole image into memory before calling the decoder, hence the high mem use. 

https://developers.google.com/speed/webp/docs/api#advanced_decoding_api

webp does not support incremental write, sadly, it has to analyze the whole image before it can write the first output byte.

**Comment by jcupitt** [comment]
I added shrink-on-load support, and `vipsthumbnail` knows about it:

```
$ time vipsthumbnail wtc.webp 
memory: high-water mark 267.88 MB
real	0m2.948s
user	0m3.504s
sys	0m0.412s
```

Now:

```
$ time vipsthumbnail wtc.webp 
memory: high-water mark 156.55 KB
real	0m1.365s
user	0m1.716s
sys	0m0.012s
```

Threaded load isn't doing anything, I'm not sure why. 

And I don't see how to do streaming load :( I had a mail from one of the webp developers a while ago about this. He said it was possible with `WebPIDecGetRGB`, but I'm not sure it is. 

libwebp is still missing supported for large images, so for now it's probably not too important. 

@lovell, I guess webp shrink-on-load support is yet another feature for sharp's to-do list?

**Comment by felixbuenemann** [comment]
@jcupitt This is great, vipsthumbnail performance on master and it also seems to be using more than one core:

```sh
time dwebp earth10k-q50.webp -tiff -quiet -mt -resize 128 128 -o out-128.tif
memory: ~6 MB RSS
0.60s user 0.01s system 158% cpu 0.388 total

# vips 8.2.2
time vipsthumbnail earth10k-q50.webp -s 128 -o out-128.tif'[compression=none]'
memory: ~322 MB
1.13s user 0.66s system 98% cpu 1.811 total

# vips 8.3.0-19a8384
time /opt/vips/bin/vipsthumbnail earth10k-q50.webp -s 128 -o out-128.tif'[compression=none]'
memory: ~22 MB
0.58s user 0.02s system 157% cpu 0.386 total
```

This is a great improvement. Thanks, John!

I agree that WebP encoding performance still leaves  a lot to be desired, especially in lossless mode. Encoding a 10000x10000 jpeg to webp lossless eats up 2,4 GB memory using `cwebp` and the `-low_memory` option doesn't seem to help at all.

However with these changes in Vips WebP becomes a viable choice for storing near-originals with alpha channel at high resolution while still being able to quickly generate smaller versions from it, which does not work well with either png or tiff – and jpeg does not support alpha channels. My only real alternative in that area that I came up with was to store the alpha channel as a separate grayscale jpeg and combine them in vips if transparency is needed.

Do you want me to keep the issue open?

**Comment by jcupitt** [comment]
I thought I wasn't seeing any SMP improvement, but you're right, now I test again it does seem to be threading.

```
$ time vips copy wtc.webp x.v
memory: high-water mark 271.94 MB
real	0m1.856s
user	0m2.284s
sys	0m0.604s
```

Yes, I think we're done here, let's close, we need a better libwebp to go much further.

**Comment by lovell** [comment]
Great work on this. I've created https://github.com/lovell/sharp/issues/369 to track all the new features that will be in 8.3.
