### ISSUE TITLE
Exif as xml

### ISSUE THREAD

**Issue by Nadot** [jcupitt/libvips#399]
Bonjour

With libvips, it is possible to get the exif data from jpeg as a xmlDoc ?

I see the function 
`static xmlDoc * get_xml( VipsImage *im ) { ... }`
in [https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/vips.c](url)
but it seems to be only internal.

Merci

**Comment by jcupitt** [comment]
Hi, there's some code to wrap up all image metadata as an xml doc here:

https://github.com/jcupitt/libvips/blob/master/libvips/foreign/dzsave.c#L148

down to line 278. That's the thing dzsave and tiffsave use to write out image metadata. I would copy-paste that code somewhere.

Perhaps it should be a standard bit of vips? Something like:

```C
char *vips_image_get_xml(VipsImage *image);
```

**Comment by jcupitt** [comment]
I think it probably shouldn't be exposed as an `xmlDoc` since that would tie the vips API to libxml2. If you need an `xmlDoc` it's probably best to write that code yourself.

**Comment by jcupitt** [comment]
Did this resolve your issue @Nadot? Please repoen if it didn't.

**Comment by Nadot** [comment]
It is OK for me.

Merci
