### ISSUE TITLE
Create a best practices guide for photograph processing

### ISSUE THREAD

**Issue by nathanaeljones** [jcupitt/libvips#400]
Many new users of libvips are using it for real-time photograph manipulation on the internet. A small "Best practices" guide on downsampling and cropping images would be helpful. 

Likely topcis would include:
* Usage of linear light (to avoid deleting highlights/expanding shadows) Good test image: https://unsplash.com/photos/UyUvM0xcqMA
* Premultiplication of alpha component when downscaling transparent PNGs.
* How to ensure edge pixels are not dropped, under-weighted, or over-weighted (Don't have test images here, easy to generate though).
* Application of color profile / normalization to sRGB at the optimal point.
* Keeping operations fast - I.e, if you're going to benchmark resizing a jpeg (while doing it the 'right' way), what commands would you use?

Many users expect "Adobe Lightroom" quality photograph manipulation, and libvips can certainly help them achieve that if they use it correctly.

**Comment by jcupitt** [comment]
Good idea. `vipsthumbnail` does all these things, but I agree it would be useful to have it spelt out. 

There's the "Tips and tricks" post. It could maybe be worked up into a page on the vips wiki. Blog posts aren't the best places to keep documentation :-( 

http://libvips.blogspot.co.uk/2013/11/tips-and-tricks-for-vipsthumbnail.html

**Comment by jcupitt** [comment]
The `vipsthumbnail` sources:

https://github.com/jcupitt/libvips/blob/master/tools/vipsthumbnail.c

It should be easy to read, I hope.

**Comment by jcupitt** [comment]
I had a quick go here:

https://github.com/jcupitt/libvips/wiki/HOWTO----Image-shrinking

All suggestions/edits very welcome.

**Comment by nathanaeljones** [comment]
Awesome! It's not immediately obvious what the command-line equivalents (via vipsthumbnail) would be, but otherwise it's clear and very helpful!

**Comment by nathanaeljones** [comment]
This is a tangent, but what kind of aliasing do you get with shrink-on-load jpeg (since I'm working on a new version of that)?  There are partial edge  blocks to deal with post-decode and it was scaling in the wrong luminance space, but I wasn't aware of any aliasing specifically.

**Comment by jcupitt** [comment]
The nxn box filter has very hard edges (of course) and that can produce nasty artifacts. For example, compare these two:

http://www.rollthepotato.net/~john/kevill/IM-400x300.png
http://www.rollthepotato.net/~john/kevill/vips-400x300.png

The IM one is loading the original 800x600 jpeg at full res and then doing a lanczos3 downsize by x2. The vips one is attempting to save some time by using doing a x2 shrink-on-load, but as you can see there's horrible aliasing on the roof. 

The current vipsthumbnail does shrink-on-load to a x2 above the target. Compare these two:

http://www.rollthepotato.net/~john/kevill6/200x150-im.png
http://www.rollthepotato.net/~john/kevill6/200x150-vips.png

The IM one is loading the full-res image and doing a x4 downsample with lanczos3, the vips one is doing x2 shrink-on-load and x2 lanczos3. There's still a bit of aliasing, but it's not too bad. 

It should probably do a very light blur after the box filter and before the lanczos3.

**Comment by jcupitt** [comment]
I've updated the page, hopefully it's a bit better. 

* links to the docs
* more chat
* some notes and examples on aliasing from block shrink

**Comment by jcupitt** [comment]
@lovell, can you think of any other points to cover? I know sharp does something very like this.

**Comment by lovell** [comment]
@jcupitt Your write-up of this is great, thank you. sharp currently does almost all these things, the difference being a lanczos2-ish blur+affine rather than a lanczos3 reduce. I plan to move sharp to use either vips_resize or vips_reduce with https://github.com/lovell/sharp/issues/310

**Comment by jcupitt** [comment]
I'll close, I think this is done.
