### ISSUE TITLE
tune new downsizer for libvips 8.3

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#404]
There's a new version of `vips_resize()` in this branch, it now does a pretty straight lanczos3:

https://github.com/jcupitt/libvips/tree/add-lanczos3

I'm hoping to move libvips 8.3 to this new code. It's faster, uses less memory, and quality should be up too. 

I've uploaded some samples with the new resampler here:

http://www.rollthepotato.net/~john/skin2
http://www.rollthepotato.net/~john/ghibli

Previous best is here:

http://www.rollthepotato.net/~john/skin

Any help tuning it up would be great.

**Comment by jcupitt** [comment]
This branch is doing:

1. vertical 1D box shrink
2. horizontal 1D box shrink
3. anti-alias, sigma = ((1.0 / residual) - 0.5) / 2.5, only blur if residual < 0.9 && sigma > 0.5
4. vertical 1D lanczos3
5. horizontal 1D lanczos3

1 and 3 vectorise well, 2, 4, and 5 do not :( But performance is nicely up from the previous best thanks to no longer needing a line cache.

vips 8.2 with a 10k x 10k RGB jpg:

```
$ time vipsthumbnail wtc.jpg -s 2000
peak rss: 52m
real    0m0.698s
user    0m1.536s
sys    0m0.044s
```

And with this branch:

```
$ time vipsthumbnail wtc.jpg -s 2000
peak rss: 40m
real    0m0.450s
user    0m0.792s
sys    0m0.020s
```

**Comment by jcupitt** [comment]
Some interesting test images from @ScottKevill:

http://www.rollthepotato.net/~john/kevill/

Looks like vips needs the anti-alias filter turned up slightly.

**Comment by jcupitt** [comment]
There's some discussion on this new code on https://github.com/lovell/sharp/issues/310 as well.

**Comment by jcupitt** [comment]
Looks a bit better:

http://www.rollthepotato.net/~john/kevill2/
http://www.rollthepotato.net/~john/ghibli2/

Though the ghibli now seems a little soft. 

Looking closely at the result, it seems IM is doing more anti-alias, plus a post-lanczos sharpen, they have some haloing around the text.

**Comment by jcupitt** [comment]
With a very mild post-shrink sharpen back again, and a little more anti-alias:

http://www.rollthepotato.net/~john/kevill3/
http://www.rollthepotato.net/~john/ghibli3/

There are still slight rounding issues on resize, but that's a separate issue.

**Comment by jcupitt** [comment]
I fixed a few rounding problems, added a set of tests and merged to master.

**Comment by ScottKevill** [comment]
Thanks and appreciate the fast response. Tried using vipsthumbnail again on the same image with the new master, and it's not much better.. the roof still looks pretty bad compared with the IM version.

**Comment by jcupitt** [comment]
That's strange, did you see the samples here?

http://www.rollthepotato.net/~john/kevill3/

Does your `vipsthumbnail` output look like that? IM and vips look rather close now (to me).

**Comment by ScottKevill** [comment]
400x300 and 300x225 seem to be the most noticeable. IM versions have no sign of the swirl/ripple in the roof at all, but it's quite clear in the VIPS versions in your kevill3 samples.

This is what I'm seeing with vipsthumbnail master (different from kevill3): [400x300](http://kevill.com/test/test_400x300_2_vips.png) and [300x225](http://kevill.com/test/test_300x225_2_vips.png).

The offset/translation issue is fixed but the aliasing in the roof is worse than kevill3 and is similar to the aliasing in the original 8.2.2.

**Comment by jcupitt** [comment]
I agree, the anti-alias filter on my samples need to be turned up a bit for 400 and 300, I'll tweak it a bit more. 

Your 400x300 does not look right, I think you might have somehow picked up an old version of the code. Try it next to mine:

http://kevill.com/test/test_400x300_2_vips.png
http://www.rollthepotato.net/~john/kevill3/vips-400x300.png

Put them in two taps and try flipping between them, yours has a displacement error that's been fixed in master.

**Comment by ScottKevill** [comment]
Are you sure about that? :) kevill, kevill2 and kevill3 have the displacement error:
http://www.rollthepotato.net/~john/kevill3/IM-400x300.png
http://www.rollthepotato.net/~john/kevill/vips-400x300.png
http://www.rollthepotato.net/~john/kevill2/vips-400x300.png
http://www.rollthepotato.net/~john/kevill3/vips-400x300.png
http://kevill.com/test/test_400x300_2_vips.png
Compare the first IM one with the last VIPS one.

**Comment by jcupitt** [comment]
Maybe it's a strange cache thing? I did make an update to kevill3 after a cock-up, you might be seeing an old version. 

These two do not look the same here:

http://kevill.com/test/test_400x300_2_vips.png
http://www.rollthepotato.net/~john/kevill3/vips-400x300.png

Yours has a displacement error and a lot more aliasing. I'll tune the anti-alias a bit more and upload some fresh ones.

**Comment by ScottKevill** [comment]
Correct, they aren't the same, but that's because kevill3 there has the same displacement error as kevill and kevill2, but my new one has no displacement error. My new one is the only one that matches IM's displacement. To clarify:

Displacement error: (all displacements match each other, but not IM's)
http://www.rollthepotato.net/~john/kevill/vips-400x300.png
http://www.rollthepotato.net/~john/kevill2/vips-400x300.png
http://www.rollthepotato.net/~john/kevill3/vips-400x300.png

No displacement error:
http://www.rollthepotato.net/~john/kevill/IM-400x300.png
http://kevill.com/test/test_400x300_2_vips.png

**Comment by jcupitt** [comment]
Oh dear I'm getting confused. I uploaded some fresh ones:

http://www.rollthepotato.net/~john/kevill4/

No changes from kevill3. Do you see a better match now? I see no displacement differences between IM and vips, a nice result for 600 and 200, a poor result for 400 and a not great result for 300.

The bad aliasing in 400 is caused by jpeg shrink-on-load. vipsthumbnail is loading your source image at half-resolution, seeing that's it's already the right size, and then doing nothing. But the half-res load has actually introduced a lot of extra sharpening over the original, so really it should do a light blur and sharpen, rather than nothing. The problems in 300 are the same, except that the degree of blur that's appropriate for the original is no longer right once the extra sharpening from the shrink-on-load has been added.

I'll add something to fix this.

**Comment by ScottKevill** [comment]
Okay, yes, kevill4 is definitely different from kevill3 for me, so I think there's something funny going on at your end. :) Maybe you are behind a transparent web proxy?

I just downloaded http://www.rollthepotato.net/~john/kevill3/vips-400x300.png from two different sources (to rule out any sneaky ISP proxy at my end), both were identical (len=236670 bytes, md5=9b69fc9cc232eb42743f1a600454bb49) and both had the displacement error.

Repeated with http://www.rollthepotato.net/~john/kevill4/vips-400x300.png from two different sources (len=227539,md5=748606e0589b3a4b22dd976e5deb061f) no displacement error.

Regarding the aliasing, for half-resolution at 400x300, is the shrink-on-load even needed? In this situation if I understand correctly, shrink-on-load is used while the affine is skipped. Would skipping the shrink-on-load and doing affine + interpolation produce better results for this 50% reduction?

**Comment by jcupitt** [comment]
I've tuned it a bit more. It now uses the block shrink and shrink on load a bit less, so it smooths out aliasing on transitions. 

http://www.rollthepotato.net/~john/kevill5/
http://www.rollthepotato.net/~john/ghibli5/

Perhaps vips is a little too sharp?

**Comment by jcupitt** [comment]
I think this really is it, here's git master now:

http://www.rollthepotato.net/~john/kevill6
http://www.rollthepotato.net/~john/ghibli6

I've changed direction, this is now shrink-on-load, then block shrink, then lanczos3 reduce for the final 2x - 3x reduction, with the size of the lanczos kernel set by the reduction factor. Phew.

I'll look at vectorizing the inner loops a bit more.

**Comment by ScottKevill** [comment]
Wow, it's looking fantastic now.

Looking closely:
- 200x150 is now the only one showing aliasing swirls. This might have been ignored at first because it was the best of the original bunch.
- All VIPS sizes seem to have a displacement error (or at least a displacement difference) from the IM versions. Hard to tell, but it's only very slight.. half a pixel perhaps?
- 356x267: the VIPS image is actually 355x266. A rounding error related to the displacement perhaps?

**Comment by jcupitt** [comment]
I'm inclined to leave the aliasing on 200x150, it doesn't seem too bad to me, what do you think?

For this one, vipsthumbnail is using shrink-on-load to get to 400x300, then doing a x2 downsize with a large lanczos3 kernel. We'd need to do a lot less shrink-on-loading and a lot more lanczos and it would hurt performance. 

Yes, there are small rounding differences. The 356x267 one is bad, it shouldn't miss on both axies, I'll look into that.

**Comment by puzrin** [comment]
Samples from 6 looks very close, except small shift.

Having at least 2x reserve for lanczos3 should help (compared to previous version you descrubed in `sharp` tracker), but IMHO the best way is to ask Nicolas.

**Comment by jcupitt** [comment]
I've been chatting to Nicolas about this a bit, though he's very busy job hunting at the moment, so I don't want to ask him too much.

**Comment by ScottKevill** [comment]
The 200x150 isn't terrible, but it would be nice to match IM here. I completely understand that performance is a major goal of VIPS, and that you'd want that default for vipsthumbnail / vips_resize. If I can get the desired quality slower by manually doing separate ops with the C API, I would be happy with that as it would probably still be faster than IM.

**Comment by jcupitt** [comment]
I've had a go at a vectorized path for vertical reduce here:

https://github.com/jcupitt/libvips/tree/orc-reduce

It's still not quite right, there's some banding, but it's good enough to benchmark. With vectors turned off:

```
$ time vips reducev wtc.v x.v 1.2 --vips-novector
real	0m1.698s
user	0m4.872s
sys	0m0.304s
```

And with the vector path:

```
$ time vips reducev wtc.v x.v 1.2
real	0m0.784s
user	0m1.432s
sys	0m0.288s
```

A bit more than twice as fast. I'll try and fix the banding.

**Comment by puzrin** [comment]
> I've been chatting to Nicolas about this a bit, though he's very busy job hunting at the moment, so I don't want to ask him too much.

I understand. Asked him for help too, but about pica (it has additional restrictions). Will share everything, if that can help. If you know someone else who can be asked about math - let me know. I'm very far from image processing. Pica was written for fun, because i learned how to write fast math in JS.

**Comment by jcupitt** [comment]
OK, vector vertical resize seems to work fine now, I'll merge to master. I've sped it up a bit more:

```
$ time vips reducev wtc.v x.v 1.2
real	0m0.425s
user	0m1.124s
sys	0m0.268s

```

**Comment by jcupitt** [comment]
@ScottKevill I did a quick blog post about the new resampler. I used your photo and put your name in. Please tell me if this is not OK and I'll remove it.

http://libvips.blogspot.co.uk/2016/03/faster-and-better-image-shrinking.html

If anyone is curious, I put up another set of results with the final code. The sizing and rounding has improved slightly. 

http://www.rollthepotato.net/~john/kevill7/

And there's a page on the vips wiki about best practice for downsizing:

https://github.com/jcupitt/libvips/wiki/HOWTO----Image-shrinking

**Comment by ScottKevill** [comment]
That's fine, it's all here in this thread anyway. :)

Blog post looks good. http://www.rollthepotato.net/~john/kevill/vips-400x300.png as the "before" image doesn't look as bad as the original "before" image: http://www.rollthepotato.net/~john/kevill7/400x300-vips-8.1.png

(The original VIPS image was 8.2.2, not 8.1)

**Comment by jcupitt** [comment]
There have been some more small changes, we now have:

http://www.rollthepotato.net/~john/kevill8/

The remaining aliasing in the 200-pixel-wide version should have gone.

**Comment by ScottKevill** [comment]
Great work, they look amazing, but there does appear to be a displacement that has crept in for the kevill8 samples. Visible at all sizes except 600x450 (or 600x450 may have been too slight to notice). If you tab back & forth between IM and VIPS versions at each size, you'll see it.

**Comment by jcupitt** [comment]
Yes, there's about a 0.5 pixel offset. They just differ slightly in the way they handle coordinate rounding, I think I'll leave it.

**Comment by jardakotesovec** [comment]
@jcupitt Thanks for amazing library! We have use case where I show lower resolution image (scaled) before high resolution gets fetched and transition from lower to higher feels bit jumpy. It sound like what has been described here (maybe around 0.5px).  

I tried to do the resize in affinity photo also with Lanczos 3 and result was very similar, but not jumpy.

Is there any chance that this could be eliminated?

**Comment by jcupitt** [comment]
I hadn't thought of that, you're right, that's a good argument for changing this. I'll make a new issue and tag it as 8.4 milestone.

**Comment by jcupitt** [comment]
The 0.5 seems to be down to corner vs. centre convention on downsize. I've added an option to `resize` to use centre and made vipsthumbnail use it. I now see:

http://www.rollthepotato.net/~john/kevill9/

They seem pretty close now.
