### ISSUE TITLE
Bug: mrxs files are not tiled correctly (Win)

### ISSUE THREAD

**Issue by martinweihrauch** [jcupitt/libvips#406]
Compared with vips 7.4, the version 8.2 for Windows only tiles a very small image of a MRXS (Mirax/3D-Histech file).
This maybe due to the newly added OpenSlide version? Is it possible that VIPS currently neglects the whole MRXS-pyramid-folder that accompanies every mrxs-file?

**Comment by jcupitt** [comment]
I think I've found the problem: MRXS images are also JPEG images, so vips needs to try to open with openslide before it tries libjpeg.

This fix will be in the next 8.3 beta. Thanks for the report!
