### ISSUE TITLE
Compile failure using VImage8.h

### ISSUE THREAD

**Issue by DFKSingleton** [jcupitt/libvips#409]
The bug is, I must say, fairly obscure and is unlikely to affect most users. It does however mean that particular operators in VIPS cannot be used as function variables. I will take the operator | as an example, but the problem applies to most (if not all) similar operators.

In VImage8.h there are five different operator | declared, with different calling parameters. They are all declared within the VImage class as friend operators and their bodies are also declared (and this is the problem) within the VIMage class. The GCC compiler accepts this and one can write, compile and run code such as:

`image1 = image2 | image3;`

without problem.

However, if one writes code such as:

```
typedef VImage (*fn_t) (Vimage a, VImageb);
fn_t myFn = operator |;
```

one gets the error message:
error: no matches converting function 'operator| ..... followed by a list of candidate operator|'s

I have investigated the problem and have written a small test class and function with a macro definition that demonstrates the problem and the solution: 

```
// testOverload.cpp

// Comment to demonstrate the problem
#define DEFINE_OUTSIDE_CLASS

class mytest {
public:
   mytest () {}
   mytest (const mytest & rObj) {

   }
#ifndef DEFINE_OUTSIDE_CLASS
   friend mytest operator |(mytest a, mytest b){
      return a;
   }

   friend mytest operator |(mytest a, int b){
      return a;
   }
#else
   friend mytest operator |(mytest a, mytest b);
   friend mytest operator |(mytest a, int b);
#endif

   mytest operator =(mytest a) {
      return a;
   }
};

#ifdef DEFINE_OUTSIDE_CLASS
mytest operator |(mytest a, mytest b){
   return a;
}

mytest operator | (mytest a, int b) {
   return a;
}
#endif

void dummy() {
   mytest test1, test2, test3;
   test3 = test1 | test2;
   typedef mytest (*fn_t) (mytest a, mytest b);
   fn_t myFn = operator |;
   test3 = myFn (test1, test2);
}

```
By commenting/ uncommenting the line **#define DEFINE_OUTSIDE_CLASS**, the problem and the solution can be demonstrated.

If it would help you, I offer to correct VImage8.h and send you the corrected copy.

You may of course ask, why would anyone want a function pointer to one of the operators. I can only say that I needed one, because I wanted to pass one of the operators to a function that I was writing, so that the function could use the specified operator while the rest of the code in the function remained the same. I was able to solve my immediate problem using the VImage::boolean() function and passing an enum of type VipsOperationBoolean into my function.

**Comment by jcupitt** [comment]
Hi @DFKSingleton. I've never wanted to take the address of an operator myself, but I guess I can see it might be useful. 

I'll move the overload bodies out of the header.

**Comment by jcupitt** [comment]
OK, change in git master, it'll be in 8.3.

Thank you for the idea, @DFKSingleton.
