### ISSUE TITLE
vips_webpsave_buffer() ignores lossless flag

### ISSUE THREAD

**Issue by aaron42net** [jcupitt/libvips#410]
The lossless flag is passed to vips__webp_write_buffer(), which doesn't use it.  It probably needs some logic copied from vips__webp_write_file() to use the WebPEncodeLosslessRGB or WebPEncodeLosslessRGBA encoders.

See: https://github.com/jcupitt/libvips/blob/master/libvips/foreign/vips2webp.c#L131

**Comment by jcupitt** [comment]
Ooop! Oh dear, that's dumb. Thank you very much for spotting this @aaron42net.

**Comment by aaron42net** [comment]
No worries.  Thanks for the fast turnaround!
