### ISSUE TITLE
Second call to VImage::black() produces unexpected results!

### ISSUE THREAD

**Issue by DFKSingleton** [jcupitt/libvips#411]
My problem is shown in the small program listed below. I create a black image using VImage::black().. I than draw a circle in the image (that I want to use as a filter), using VImage::draw_circle(). I then call VImage::black() again because I want another black image of the same size. Surprisingly, the second image is not all black! It also contains the circle that I drew on the first image! (see the two attached files). The workaround for the problem is simple. Before I draw my circle, I take a copy of the first image, using VImage::copy(). The second call to black() then deligers the expected result!

I am not sure whether what I have seen is a feature or a bug! If it is a feature, then it would be helpful if the documentation for vips_black() was extended to warn of the dangers of operating directly on a black image with functions such as draw_circle().

![image1](https://cloud.githubusercontent.com/assets/18052758/14280017/721c9ece-fb30-11e5-8be0-08a24915abeb.jpg)
![image2](https://cloud.githubusercontent.com/assets/18052758/14280032/7f38e130-fb30-11e5-929c-fe6b495b47ea.jpg)

'
/*
 * vipsblacktest_main.cpp
 *
 *  Created on: 03.04.2016
 *      Author: David Singleton
 */
#include <stdio.h>
#include <vips/vips8>
using namespace vips;
#define RC_OK 0
int main(int argv, char ** argc) {
   int iRc = vips_init(argc[0]);
   if (RC_OK != iRc) {
      vips_error_exit("unable to start VIPS");
   }
   vips_leak_set(TRUE);

   {  // In a block, so that the destructors are called before vips_shutdown
      VOption * pOption = new VOption();
      pOption->set("bands", 1);
      VImage image1 = VImage::black(200, 200, pOption);
      std::vector<double> ink;
      ink.push_back(255.0);
      pOption = new VOption();
      pOption->set("fill", TRUE);
      image1.draw_circle(ink, 100, 100, 50, pOption);
      image1.write_to_file("image1.jpg");

      pOption = new VOption();
      pOption->set("bands", 1);
      VImage image2 = VImage::black(200, 200, pOption);
      image2.write_to_file("image2.jpg");
   }

   vips_shutdown();
   printf("vipsblacktest successfully ended\n");
   return 0;
}
`

**Comment by DFKSingleton** [comment]
I would add that the problem only occurs when the the second call to VImage::black() uses exactly the same height and width. When these are different from the first call, then the second black image is as expected - all black!

**Comment by jcupitt** [comment]
That's right, the `draw_` operations destroy the image you run them on, you can't really mix them with the regular vips operations, it messes up all the caching. You need to use `copy` to make a private image, then draw on that (as you found).

It's sort-of mentioned in the docs, but not very explicitly, I suppose:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-draw.html#libvips-draw.description

The python and ruby interfaces add these extra copy operations automatically, but the C++ interface doesn't. The extra copy operations can be expensive if you don't get them in the right place, and C++ programmers are used to crashes and misbehaviour (I think that was my reasoning anyway).

I'll expand the warning on draw operations.

**Comment by jcupitt** [comment]
I added some notes, does that look better? New draw intro is:

```
 * These operations directly modify the image. They do not thread, on 32-bit
 * machines they will be limited to 2GB images, and a little care needs to be
 * taken if you use them as part of an image pipeline. 
 * They are mostly supposed to be useful for paintbox-style programs.
 *
 * libvips operations are all functional: they take zero or more existing input 
 * images and generate zero or more new output images. Images are
 * never altered, you always create new images. This means libvips can cache
 * and thread very agressively.
 *
 * The downside is that creating entirely fresh images each time can be very
 * slow. libvips has a range of tricks to avoid these problems, but there are
 * still times when you really have to be able to modify an image. An example
 * might be drawing a curved line from a set of straight line segments: if you
 * need to draw 1,000 straight lines, a 1,000 operation-deep pipeline is going
 * to be a slow way to do it. This is where the draw operations come in.
 *
 * To use these operations, take a copy of the image you want to modify, to
 * ensure that no one else is using it, then call a series of draw operations.
 * Once you are done drawing, return to normal use of vips operations. Any time
 * you want to start drawing again, you'll need to copy again. 
```

**Comment by DFKSingleton** [comment]
Hello Mr Cupitt,

 

I suggest the following additions to the last paragraphs:

 

 * To use these operations, take a copy (using the vips_copy() function) of the image you want to
modify, to
 * ensure that no one else is using it, then call a series of draw
operations.
 * Once you are done drawing, return to normal use of vips
operations. Any time
 * you want to start drawing again, you'll need to copy again. 

Best wishes

 

David Singleton

 

 

-----Original-Nachricht-----

Betreff: Re: [jcupitt/libvips] Second call to VImage::black() produces 
unexpected results! (#411)

Datum: 2016-04-06T11:28:54+0200

Von: "John Cupitt" <notifications@github.com>

An: "jcupitt/libvips" <libvips@noreply.github.com>

 

 

 

I added some notes, does that look better? New draw intro is:

 * These operations directly modify the image. They do not thread, on 32-bit * machines they will be limited to 2GB images, and a little care needs to be * taken if you use them as part of an image pipeline. * They are mostly supposed to be useful for paintbox-style programs. * * libvips operations are all functional: they take zero or more existing input * images and generate zero or more new output images. Images are * never altered, you always create new images. This means libvips can cache * and thread very agressively. * * The downside is that creating entirely fresh images each time can be very * slow. libvips has a range of tricks to avoid these problems, but there are * still times when you really have to be able to modify an image. An example * might be drawing a curved line from a set of straight line segments: if you * need to draw 1,000 straight lines, a 1,000 operation-deep pipeline is going * to be a slow way to do it. This is where the draw operations come in. * * To use these operations, take a copy of the image you want to modify, to * ensure that no one else is using it, then call a series of draw operations. * Once you are done drawing, return to normal use of vips operations. Any time * you want to start drawing again, you'll need to copy again. 

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/jcupitt/libvips/issues/411#issuecomment-206256627>

**Comment by jcupitt** [comment]
Hi David, OK, added the ref to `vips_copy()`.

By the way, did you see the `vips_mask_ideal()` funtions? They will make a circle on a black background for you, if you are doing Fourier-space filtering. 

```
vips mask_ideal x.png 128 128 0.5 --uchar --reject --optical
```

See http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-create.html#vips-mask-ideal

**Comment by DFKSingleton** [comment]
Hallo John,
 
Thanks for the information. I just wanted to look at details in the centre 
of the image, so vips_mask_ideal () would not help me in this case.
 
Best wishes
 
David Singleton
 
 
 
-----Original-Nachricht--- --
Betreff: Re: [jcupitt/libvips] Second call to VImage::black() produces 
unexpected results! (#411)
Datum: 2016-04-06T16:15:55+0200
Von: "John Cupitt" <notifications@github.com>
An: "jcupitt/libvips" <libvips@noreply.github.com>
 
 
 
Hi David, OK, added the ref to vips_copy().
By the way, did you see the vips_mask_ideal() funtions? They will make a 
circle on a black background for you, if you are doing Fourier-space 
filtering.

vips mask_ideal x.png 128 128 0.5 --uchar --reject --optical 

See 
http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-create.html#vips-mask-ideal
<http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-create.html#vips-mask-ideal>
—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/jcupitt/libvips/issues/411#issuecomment-206391609>
 
﻿

**Comment by jcupitt** [comment]
I'll close. Thanks for the nudge on the docs, @DFKSingleton.
