### ISSUE TITLE
vipsthumbnail auto rotate not working

### ISSUE THREAD

**Issue by marksamman** [jcupitt/libvips#413]
```bash
$ vipsheader -a Landscape_4.jpg | grep -i orien
exif-ifd0-Orientation: 4 (Bottom-left, Short, 1 components, 2 bytes)
$ vipsthumbnail --rotate Landscape_4.jpg --output Landscape_4_out.jpg
$ vipsheader -a Landscape_4_out.jpg | grep -i orien
exif-ifd0-Orientation: 4 (Bottom-left, Short, 1 components, 2 bytes)
```

libexif seems to be installed, but I'm not sure vips was built with it, but I'm assuming it was because vipsthumbnail didn't output any warning:
```
$ brew info vips
homebrew/science/vips: stable 8.2.3 (bottled)
Image processing library
http://www.vips.ecs.soton.ac.uk/
/usr/local/Cellar/vips/8.2.3 (180 files, 12.1M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew-science/blob/master/vips.rb
==> Dependencies
Build: pkg-config ✔
Required: fontconfig ✔, gettext ✔, glib ✔
Recommended: libpng ✔, jpeg ✔, orc ✔, libgsf ✔, libtiff ✔, fftw ✔, little-cms2 ✔, pango ✔, libexif ✔, gobject-introspection ✔, pygobject3 ✔, python ✔
Optional: openslide ✘, imagemagick ✔, graphicsmagick ✘, openexr ✘, cfitsio ✘, webp ✔, python3 ✔, libmatio ✘, mozjpeg ✘, jpeg-turbo ✘
```

Landscape_4.jpg was taken from https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_4.jpg

**Comment by jcupitt** [comment]
Hi @marksamman,

libvips just implements the rotation part of exif orientation, it doesn't do the mirroring. Try:

  https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_6.jpg

And it should work. 

The reasoning was that all cameras just do upright / 90 degrees left / 90 degrees right / upside down, and none (as far as I know?) produce images with the left-right and top-bottom flip options which the spec allows. Without a real test case produced by a real device there didn't seem much point adding the feature.

**Comment by marksamman** [comment]
Fair enough. I don't actually need this specific kind of rotation, I had a bug in my code where I accidentally stripped out EXIF before running vipsthumbnail and when I was going to test vipsthumbnail I just ended up finding that image which didn't work and thought the feature was completely broken because it worked with ImageMagick's convert using -auto-orient. You can close this issue if you don't see any reason to support this rotation.

**Comment by jcupitt** [comment]
OK, please reopen if you hit a problem with the four simple rotations.

**Comment by wilg** [comment]
iOS devices produce images with the flipped rotations (such as 8) if "Mirror Front Camera" is enabled in the settings

**Comment by jcupitt** [comment]
Oh, interesting to know @wilg.

libvips 8.10 handles all orientation cases, so this issue is out of date.
