### ISSUE TITLE
No ./configure?

### ISSUE THREAD

**Issue by binarykitchen** [jcupitt/libvips#414]
Early in the readme you mention of a `./configure` but I can't locate it anywhere? Outdated maybe?

**Comment by jcupitt** [comment]
Hi @binarykitchen, `configure` is not in git, you need to generate it. Run `./bootstrap.sh` to create the configure system.

It needs quite a bit of stuff installed. If you build from a tarball instead, `configure` is there and ready to go. The latest stable tarballs are here:

http://www.vips.ecs.soton.ac.uk/supported/current/

**Comment by binarykitchen** [comment]
thanks, it worked. maybe you want to add that in the readme at top?

**Comment by jcupitt** [comment]
It's in there under `Build from git`:

https://github.com/jcupitt/libvips#building-libvips-from-git

Most people build from the pre-baked tarballs, so I put that first. Or they used to, perhaps that's changed now?

**Comment by jcupitt** [comment]
I rephrased the README slightly, does that seem clearer?

**Comment by binarykitchen** [comment]
Yes, better now :) U know, usability is a matter of perspective ...

**Comment by jcupitt** [comment]
OK, I'll close.
