### ISSUE TITLE
Vips dzsave_buffer support

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#415]
It would be great, if Vips supported dzsave_buffer, provided that a ZIP container is used.

That way zoom images could be generated completely in memory.

**Comment by jcupitt** [comment]
Looks like it should be a one-line change. vips currently calls gsf_output_stdio_new() to create the object to write to:

https://github.com/jcupitt/libvips/blob/master/libvips/foreign/dzsave.c#L1780

Looks like we'd just need to swap that for gsf_output_memory_new():

https://developer.gnome.org/gsf/stable/gsf-memory.html#gsf-output-memory-new

It would need a fair amount of memory, of course, I'd imagine at least double the size of the output zip, so a 2gb zip file would need more than 4gb of ram to generate.

**Comment by felixbuenemann** [comment]
For moderately sized input images, eg. 20 MP, the zip is just a couple megabytes. I agree that in memory is a bad choice for huge sources.

**Comment by felixbuenemann** [comment]
I looked at the codebase, to see if I can implement this my self, but figuring out the whole mapping between the C functions and the object model layered on top of it is giving me major headaches.

I really prefer to contribute code instead of asking for features, but this is currently out of my league.

**Comment by jcupitt** [comment]
Yes, you need to learn GObject before you can really do this, unfortunately :-( it's not hard, but also maybe not very useful knowledge outside the Gnome world.

The steps would be:

- split dzsave into an abstract base class plus a save-to-file class, with just the filename as the argument in save-to-file 
- the _build function would need to be split too
- add a new subclass for buffer save
- add a new C wrapper for vips_dzsave_buffer

webpsave.c has this structure and it's only 190 lines of code, it might make it clearer. I'll have a go at this myself for 8.4, I'm focusing on getting 8.3 done at the moment.

**Comment by jcupitt** [comment]
OK, done! Zip only. It was a bit harder than I thought :(

**Comment by felixbuenemann** [comment]
Is the `basename` stuff required because of the restriction in older libgsf versions that cannot directly write to the root of a zip (as discussed in #465)?

**Comment by felixbuenemann** [comment]
Forget my question, I re-read the code and can see that `basename` is used, because it cannot be derived from `filename`, which wouldn't make sense in a buffer context.

**Comment by jcupitt** [comment]
Exactly, it's the name of the directory that the zip will make when unzipped.
