### ISSUE TITLE
vipsthumbnail produces offset results?

### ISSUE THREAD

**Issue by nathanaeljones** [jcupitt/libvips#416]
I was comparing libvips and imageflow to check imageflow's accuracy, and noticed a lot of differences. I then tried imagemagick, and found that DSSIM was lower between it and imageflow than it and vipsthumbnail --linear.

In this image, the image seems shifted down and to the right. 
First image of each pair is from imagemagick, and the second is from vipsthumbnail
![imagemagick_u1_128x128](https://cloud.githubusercontent.com/assets/107935/14370697/c297ea8e-fced-11e5-8a32-79302e9fe4ed.png)
![vips_u1_1](https://cloud.githubusercontent.com/assets/107935/14370702/cb7bc77e-fced-11e5-9b33-c198c2d54703.png)

Here, strange things are happening with colors
![imagemagick_dalai_lama_128x128](https://cloud.githubusercontent.com/assets/107935/14370703/cfcadbc6-fced-11e5-9c28-9f4897c6197f.png)
![vips_gamma_dalai_lama_gray_1](https://cloud.githubusercontent.com/assets/107935/14370704/d1ab9f2a-fced-11e5-8aaa-363afeaddfcb.png)

## Imagemagick commands  used:

`convert u1.jpg -set colorspace sRGB -colorspace RGB -filter Mitchell -distort Resize 128x128 -colorspace sRGB imagemagick_u1_128x128.png`

`convert gamma_dalai_lama_gray.jpg -set colorspace sRGB -colorspace RGB -filter Mitchell -distort Resize 128x128 -colorspace sRGB imagemagick_dalai_lama_128x128.png`

##Version

`vipsthumbnail --vips-version
libvips 8.2.2-Wed Mar  2 13:25:42 MST 2016`

## Originals
https://s3-us-west-2.amazonaws.com/imageflow-resources/test_inputs/gamma_dalai_lama_gray.jpg
https://s3-us-west-2.amazonaws.com/imageflow-resources/test_inputs/u1.jpg

**Comment by jcupitt** [comment]
Try vips master, vips 8.3 is due out in a few days and it has a completely rewritten downsizer. It should be almost identical to IM now.

Samples:

http://www.rollthepotato.net/~john/kevill8/

There was a blog post about the new downsizer:

http://libvips.blogspot.co.uk/2016/03/faster-and-better-image-shrinking.html

**Comment by jcupitt** [comment]
And you're right, linear mode is not working well, it needs revising.

**Comment by nathanaeljones** [comment]
I'll probably wait for official 8.3 :) -> https://github.com/jcupitt/libvips/issues/418

I'm on Ubuntu 14.04; will there be a binary release?

**Comment by nathanaeljones** [comment]
I've been trying to set up a benchmark between imageflow, libvips, and imagemagick to measure throughput, i.e, how many (say 16MP jpegs) can they resize in high quality per second (while configured such that the results have very low DSSIM values). I've been using vipsthumbnail (I assume it's the fastest?), but would like to know if there is an optimal scheduling/threading model to use when testing libvips.

**Comment by nathanaeljones** [comment]
`convert -version` takes < 7 ms, but `vipsthumbnail --vips-version` takes ~24ms. I'm concerned about this skewing the benchmark. Are there ways to mitigate this? (like a ruby equivalent of vipsthumbnail that can keep the library in memory between runs)?
```

time vipsthumbnail --vips-version
libvips 8.2.2-Wed Mar  2 13:25:42 MST 2016

real	0m0.024s
user	0m0.016s
sys	0m0.004s

```

**Comment by jcupitt** [comment]
No, it should work well in just the default mode, I hope. It'll be slightly quicker if you get it to do the looping, ie.:

```
vipsthumbnail *.jpg
```

rather than:

```
for i in *.jpg; do vipsthumbnail $i; done
```

But I doubt if the difference will be large. It'll mostly be stuck in libjpeg, so threading doesn't help much. Something like GNU parallel is a better way to get parallelism. 

The new resampler in 8.3 is designed for the gcc auto-vectorizer, so you'll see a good speedup if you build with `-O3`. It also uses orc for the lanczos3, so build with orc for another speedup.

vipsthumbnail uses shrink-on-load to get to a size x2 above the target. For a comparable IM command, you'll need to use x2 above the target for the shrink-on-load setting there, so:

```
convert -define jpeg:size=4000x4000 wtc.jpg -resize 2000 out.jpg
```

is equivalent to:

```
vipsthumbnail wtc.jpg --size 2000 -o out.jpg
```

You could consider testing tiff as well as jpg, and large as well as small image output sizes. 

That blog post has some timings and command-lines I've used for testing, it might be helpful. 

It'd be interesting to look at memory use as well as CPU use, but that's much harder.

**Comment by nathanaeljones** [comment]
> But I doubt if the difference will be large. It'll mostly be stuck in libjpeg, so threading doesn't help much. Something like GNU parallel is a better way to get parallelism. 

I meant actually spawning threads and running multiple vipsthumbnail processes in parallel (similar to GNU parallel, which claims a 10ms overhead). I like to spin up threads outside of the benchmark code to avoid that overhead.

Shrink-on-load and other block-shrinking techniques are a bit tricky regarding how much to downscale first. In previous products I've seen quality loss if less less than the last 310% of scaling is done with actual interpolation, but 210+%  works for most images pretty well. With strict power-of-two sized images, 200% can result is visible artefacts, since the over-sharpened block edges align perfectly with the negatively weighted interpolation kernel, and that ends badly. 

Have you done any DSSIM testing around what percentages guarantee the best quality in libvips? Your pipeline is so different this might not be an issue in < version 8.3.  

I've found that blurring the block edges ("sharpening" -7 to -20%) can really lower the DSSIM compared to a fully interpolated image. It kind of fills in the blurring where the block kernel missed. https://github.com/imazen/imageflow/blob/03caf90b383a80a5c3e65ca999dfa7016712cff3/lib/convolution.c#L446-L540

**Comment by lovell** [comment]
> "convert -version takes < 7 ms, but vipsthumbnail --vips-version takes ~24ms. I'm concerned about this skewing the benchmark. Are there ways to mitigate this?"

libvips 8.3 will include https://github.com/jcupitt/libvips/pull/402

**Comment by nathanaeljones** [comment]
Perfect!

**Comment by nathanaeljones** [comment]
Is there any way to control shrink-on-load under vipsthumbnail? I can't do apples-to-apples under linear (since only imageflow supports linear shrink-on-load for the moment), but for srgb scaling I'd like to measure the same shrink-on-load factor for everyone. Also, shrink-on-load is supported for 1/8..7/8, but some implementations only use 1/8, 1/4, 1/2, so I'd try to pick sizes that work for those 3 vs the full 7.

**Comment by nathanaeljones** [comment]
> You could consider testing tiff as well as jpg, and large as well as small image output sizes. 

I don't have any plans to integrate libtiff. Is there another simple/low-overhead format you would suggest for comparison, @jcupitt? PPM seems to be popular. I'm OK with adding exactly 1 simple codec to imageflow (whether BMP or PPM or ?) for benchmarking purposes, as long as the attack surface is very minimal and a codec can be written in a few pages of code.

**Comment by jcupitt** [comment]
Yes, PPM is a good choice for a fast, minimal file format. The binary versions are just a header line with width and height, then a dump of the RGB pixels values.

**Comment by jcupitt** [comment]
No, vipsthumbnail has no shrink-on-load controls. It used to have more knobs, but they tended to get in the way: it was hard to improve vipsthumbnail and also support the old flag meanings. I think they've almost all been deprecated now and have no effect. 

The current "philosophy" is that it should do the fastest, best-quality resize it can, and not offer any controls. This way, if the next version has yet another improvement, everyone gets the fixed version immediately and no one has to adapt their code. 

I think you'll have to write your own tiny thumbnailer if you want to control details of the process.

**Comment by jcupitt** [comment]
You're right, some study of what proportion should be block and what lanczos would be useful. I've not done it, except by eye.

vips uses lanczos3 for the final 200%+, which is not quite enough in a few awful cases (like those roof tiles in the picture of the house). 

I've been meaning to test lanczos2 vs. 3 as well, the difference seems extremely small, looking at the masks.

**Comment by nathanaeljones** [comment]
Are you using orthogonal or EWA resizing with the lanczos kernel?

**Comment by jcupitt** [comment]
It's orthogonal.

**Comment by nathanaeljones** [comment]
Lanczos is fantastic for EWA, but less ideal for orthogonal. Robidoux or Mitchell are popular choices there. For upscaling orthogonally, Ginseng (lanczos family) is great. However, the differences between filters are outshadowed by rounding errors or any sharpening you apply. I often calculate the area under the axis for a given filter, then determine the desired volume (I.e, sharpening goal), and use that ratio to multiply against weights < 0. 

Are you using ORC to generate per-scanline kernels? The nature of windowing, where a pixel has a variable number of inputs, has been a challenge for me to optimize, but runtime instruction generation would offer some ideal unrolling/vectorization.

**Comment by nathanaeljones** [comment]
For now I'm going to stick with comparing post-scaling of 200% or more, and use vipsthumbnail. Can't wait to run these benchmarks again against 8.3 and get meaningful DSSIM values.

https://gist.github.com/nathanaeljones/58ed26f967ff10b5bf3b37987c9dcbfe

https://gist.github.com/nathanaeljones/efdb075502c3ab99e0d7f77ed8d4c4b5

https://gist.github.com/nathanaeljones/60aeb33268e132da6e0d6a377a5ecf21

https://gist.github.com/nathanaeljones/c9ad16b9d6c1d4709efb54773772cf3f

**Comment by jcupitt** [comment]
It's like IM I think, where `-resize` is orthogonal lanczos3, `-distort` is EWA. 

Yes, I spent some time fighting the gcc auto-vectorizer, but I couldn't get a good result with lanczos -- it now uses ORC for the vertical component. You can turn orc on and off with `--vips-novector`. For a 10k x 10k RGB on this laptop I see:

```
$ time vips reducev wtc.ppm x.ppm 3 --vips-novector
real	0m1.261s
user	0m4.648s
sys	0m0.152s
$ time vips reducev wtc.ppm x.ppm 3
real	0m0.325s
user	0m0.964s
sys	0m0.148s
```

So about a 4x speedup.

**Comment by jcupitt** [comment]
Interesting numbers! Yes, 8.3 should look better, I hope.

**Comment by nathanaeljones** [comment]
So ORC is good at optimizing gather and prefetching? I take the horizontal,
transpose, horizontal, transpose approach, but I'm wondering if there is a
faster way.

**Comment by jcupitt** [comment]
For the vertical reduce, you can use the same mask coefficients for every pixel in an output scanline and you don't need to loop over band elements. I generate code something like this:

```
unsigned char *s0 = pointer to first pixel in scanline 0
unsigned char *s1 = ...
const int c0 = first mask coeff
const int c1 = ...
unsigned char *out = pointer to first pixel in output scanline
const int n = number of bits of precision in accumulator
for( int x = 0; x < width; x++ ) {
    int sum = s0[x] * c0 + s1[x] * c1 + ...
    out[x] = (sum + ((1 << n / 2)) >> n
}
```

It's using 6 bits of precision at the moment, which lets you fit the accumulator in 16 bits.

**Comment by nathanaeljones** [comment]
How do you get the same input coefficient s for each output pixel unless you are doing a 1/X reduction?

**Comment by nathanaeljones** [comment]
Is there a way to compensate in the frequency space? I'm clueless about frequency space math and have no real formal math education.

**Comment by jcupitt** [comment]
Yes, `reducev` has a times-reduction argument, so that's for scaling by 1/3.

Sorry, compensate for what in frequency space? I've lost track a bit, I wish github comments were threaded rather than just being a big list.

**Comment by nathanaeljones** [comment]
I was talking about the final resample pass, not the original block scaling. I assume reducev is the block-scaling?

**Comment by jcupitt** [comment]
The block scaling is `vips_shrink()`, the final resample pass is `vips_reduce()`. 

The thing that generates the orc code is here, if you're curious:

https://github.com/jcupitt/libvips/blob/master/libvips/resample/reducev.cpp#L159

**Comment by nathanaeljones** [comment]
So, my brain transposed something you said: 

> For the vertical reduce, you can use the same mask coefficients for every pixel in an output scanline and you don't need to loop over band elements. 

Each input scanline in the vertical reduce gets a different coefficient, right?

**Comment by jcupitt** [comment]
Exactly, and that set of coeffs is fixed for each output scanline. It's

```
output_pixel = input1 * c1 + input2 * c2 ...
```

with c1 - cn fixed for that output line. `reducev` gives orc pointers to the output scanline plus all the input scanlines plus a set of cn, and orc then generates an entire output line.

**Comment by nathanaeljones** [comment]
Makes sense. I've seen that approach before. So orc generates a different instruction set for each output scanline, right? 

Is horizontal reduction still faster than vertical?

**Comment by jcupitt** [comment]
Oh no, vertical is MUCH faster. I do vertical first, so there are fewer horizontals to do.

```
$ time vips reduceh wtc.ppm x.ppm 2.3 
real	0m1.484s
user	0m4.228s
sys	0m0.204s
$ time vips reducev wtc.ppm x.ppm 2.3 
real	0m0.593s
user	0m0.892s
sys	0m0.260s
```

**Comment by nathanaeljones** [comment]
Interesting. I assume you've tried using vertical exclusively via transposes?

**Comment by jcupitt** [comment]
I thought about it, but no, not tried it yet. I'm not certain there would be much of a gain.

**Comment by nathanaeljones** [comment]
Writes can be asynchronous, and there are intrinsics for SIMD scatter/gather, but I haven't implemented an optimized transpose myself (since I currently distribute the writes with slower operations, avoiding that bottleneck).

**Comment by jcupitt** [comment]
I'll close, I think this is mostly resolved.

**Comment by nathanaeljones** [comment]
8.3.1 still has 1px image offsets (or - different image dimensions from 8.2.2, preventing comparison)

https://gist.github.com/nathanaeljones/7808d4ba10b8a6f8d3d30e5c8e14b47a

**Comment by jcupitt** [comment]
I think the offset is just vips and IM handling rounding slightly differently, so I plan to leave it as it is.
