### ISSUE TITLE
Vips tiffsave_buffer support

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#417]
It's currently not possible in to write tiff files to an in memory buffer, because libvips does not implement `tiffsave_buffer` required to do so.

According to the following StackOverflow article, it should be possible to write to memory using libtiff:

[C++ LibTiff - Read and Save file from and to Memory](http://stackoverflow.com/questions/4624144/c-libtiff-read-and-save-file-from-and-to-memory)

Writing to memory would be useful for scenarios where writing to the filesystem is either denied or too slow or would interfere with reads from the same volume.

**Comment by jcupitt** [comment]
OK, marking as an enhancement.

**Comment by jcupitt** [comment]
OK, in git master. Thanks for the suggestion!

**Comment by felixbuenemann** [comment]
Thanks, John!
