### ISSUE TITLE
[master] Fails to link against ImageMagick 6.9.3-7 Q16 x86_64 2016-04-06

### ISSUE THREAD

**Issue by nathanaeljones** [jcupitt/libvips#418]
/bin/bash ../libtool  --tag=CC   --mode=link /usr/bin/gcc -std=gnu99  -O3   -o vips vips.o -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -fopenmp -I/usr/local/include/ImageMagick-6 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/x86_64-linux-gnu -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libxml2 -I/usr/include/librsvg-2.0 -I/usr/include/libpng12 -I/usr/include/libgsf-1 -I/usr/include/libexif -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/OpenEXR -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 ../libvips/libvips.la -L/usr/local/lib -lMagickWand-6.Q16HDRI -lMagickCore-6.Q16HDRI   -lpng12   -ltiff   -lz -ljpeg  -Wl,--export-dynamic -pthread -lgmodule-2.0 -lxml2 -lgobject-2.0 -lglib-2.0   -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lgsf-1 -lgobject-2.0 -lxml2 -lglib-2.0     -llcms2    -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lcairo    -pthread -lIlmImf -lz -lImath -lHalf -lIex -lIlmThread     -lwebp    -lexif   -lm 
libtool: link: /usr/bin/gcc -std=gnu99 -O3 -o .libs/vips vips.o -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -fopenmp -I/usr/local/include/ImageMagick-6 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/x86_64-linux-gnu -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/libxml2 -I/usr/include/librsvg-2.0 -I/usr/include/libpng12 -I/usr/include/libgsf-1 -I/usr/include/libexif -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/OpenEXR -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 -Wl,--export-dynamic -pthread -pthread  ../libvips/.libs/libvips.so -L/usr/local/lib /usr/local/lib/libMagickWand-6.Q16HDRI.so /usr/local/lib/libMagickCore-6.Q16HDRI.so -lpng12 /usr/lib/x86_64-linux-gnu/libtiff.so -ljpeg -lgmodule-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig /usr/lib/x86_64-linux-gnu/libfreetype.so -lgsf-1 -lxml2 -llcms2 -lrsvg-2 -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 /usr/lib/x86_64-linux-gnu/libcairo.so /usr/lib/x86_64-linux-gnu/libIlmImf.so -lz -lImath -lHalf -lIex -lIlmThread -lwebp -lexif -lm -fopenmp -pthread -Wl,-rpath -Wl,/home/n/vips/lib
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DestroyPixelWand'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `PixelSetColor'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetStrokeWidth'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawRectangle'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPushPattern'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetStrokeColor'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPathLineToAbsolute'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawRoundRectangle'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawAnnotation'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPathStart'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetClipPath'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPathClose'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetViewbox'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `PixelSetRedQuantum'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPopClipPath'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetStrokeAntialias'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DestroyMagickWand'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DestroyDrawingWand'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawColor'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `NewMagickWandFromImage'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawScale'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawLine'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `PixelSetOpacityQuantum'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawRender'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetStrokePatternURL'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetFillPatternURL'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPushDefs'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawComment'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `PixelSetBlueQuantum'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetFontSize'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetStrokeDashArray'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPathMoveToAbsolute'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPushClipPath'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPopPattern'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPathFinish'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetTextUnderColor'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetFillColor'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetFont'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `NewPixelWand'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawArc'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawRotate'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `PopDrawingWand'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `PixelSetGreenQuantum'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawTranslate'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetClipRule'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawComposite'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPathEllipticArcAbsolute'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetStrokeLineJoin'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawPopDefs'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `PushDrawingWand'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawSetStrokeLineCap'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `PixelSetQuantumColor'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `DrawEllipse'
/usr/local/lib/libMagickCore-6.Q16HDRI.so: undefined reference to `AcquireDrawingWand'
collect2: error: ld returned 1 exit status
make[2]: *** [vips] Error 1
make[2]: Leaving directory `/home/n/Documents/github/libvips/tools'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/n/Documents/github/libvips'
make: *** [all] Error 2

**Comment by jcupitt** [comment]
This is actually an imagemagick bug (in my opinion). 

ImageMagick comes in two main parts, core and wand. Core is the low-level part, wand is a higher API on top of wand. libvips uses the core API, since it needs some functions which wand does not supply.

In about IM 6.9.0 they added a new decoder for WMF files. Decoders sit inside core, since they are rather low-level. However, the people who wrote the new wmf decoder used some wand functions (like `DrawSetStrokeLineJoin`) to render WMF files.

This has unfortunately broken their structure. We have bits of core which depend on wand functions, and of course wand depends on core. As a result, every library which linked against core (like libvips) no longer works. 

The simplest solution is probably to build imagemagick with the `--with-modules` options. This puts all the loaders into separate modules, which is a bit slower, but does mean their circular dependency is hidden and programs which use imagemagick can link again. 

I don't know how much pain this is going to cause IM packagers, perhaps they all already use `--with-modules`.

http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=28634

They don't seem very concerned about having introduced this circular dependency, which puzzles me a little. Perhaps it's not as big a deal as I'm making out.

**Comment by nathanaeljones** [comment]
> The simplest solution is probably to build imagemagick with the --with-modules option. This puts all the loaders into separate modules, which is a bit slower, but does mean their circular dependency is hidden and programs which use imagemagick can link again. 

Thanks! Perhaps a note in the readme would help until they figure it out?

**Comment by jcupitt** [comment]
OK, added a note.
