### ISSUE TITLE
resize just one section of an image?

### ISSUE THREAD

**Issue by mikesmith20** [jcupitt/libvips#425]
I'd like to resize a small part of an image, but use the pixels around the edge (that will be cropped out) as context for the resize. Is there a way to do this? I imagine it has something to do with VipsRegion and its "valid" VipsRect.

**Comment by mikesmith20** [comment]
It looks like vips_affine has an oarea argument that does this. My question is whether the lanczos3 interpolator will read past the oarea bounds when calculating the edge pixels.

**Comment by jcupitt** [comment]
You could just crop after resize, would that work? If you do:

```python
a = Vips.Image.new_from_file("huge.tif", access = Vips.Access.SEQUENTIAL)
a = a.resize(2.2)
a = a.crop(10, 10, 100, 100)
a.write_to_file("out.tif")
```

Now only a 100 x 100 pixel area will be calculated, it won't resize the whole image. And it won't read the whole of the input, only enough to generate the output.

**Comment by mikesmith20** [comment]
That's a good solution for a large file on disk, but not if the large file is streaming over the network. I want to do something like new_from_buffer, without waiting for the entire compressed file to download.

There's another related use case, where I want to run GPU processing algorithms while retaining the nice incremental processing of vips.

**Comment by jcupitt** [comment]
There was an experimental branch of libvips a few years ago that added true streaming support. You could connect libvips to a pair of network sockets (for example) and write:

```C
VipsStreamInput *in_stream = ...;
VipsStreamOutput *out_stream = ...;

while( !vips_stream_input_eof( in_stream ) ) {
  VipsImage *x;
  VipsImage *y;

  if( !(x = vips_image_new_from_stream( in_stream, "", NULL )) ||
    vips_invert( x, &y, NULL ) ||
    vips_image_write_to_stream( y, ".jpg", out_stream, NULL ) )
    vips_error_exit( NULL );

  g_object_unref( x );
  g_object_unref( y );
}
```

Though it was never quite finished and has probably drifted too far from master now to be very useful. There was a long discussion about this in sharp:

https://github.com/lovell/sharp/issues/30

If you want to operate on pixels yourself (perhaps with a GPU) and keep streaming, you'd need to dive down into the C internals of vips and write your own operator. There's an example here:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/extending.html

You probably saw.
