### ISSUE TITLE
Strange artifacts after resizing.

### ISSUE THREAD

**Issue by skunkworker** [jcupitt/libvips#426]
I was resizing a stock photo with carrierwave-vips and it was creating some weird artifacts.
I'm using `ruby vips (0.3.14)` and `vips 8.2.3` from Homebrew.

This is what the image should look like:
![correct](http://i.imgur.com/HmTQoez.jpg)

One artifact
![artifact1](http://i.imgur.com/5rHsIVB.jpg)

Another
![artifact2](http://i.imgur.com/iaVsiKG.jpg)

I'll try to track down exactly what commands its calling, but so far this is the only image in the last year that I've seen had artifacts.

**Comment by jcupitt** [comment]
Hi @skunkworker, could you try with 8.3? It hit homebrew a couple of days ago, it has a new resizer which should be faster and better quality.

I tried your image here with:

```
$ vipsthumbnail 687474703a2f2f692e696d6775722e636f6d2f486d54516f657a2e6a7067.jpg -s 703 -o x.jpg 
```

And it worked, but of course that won't be exactly the thing carrierwave is using.

**Comment by skunkworker** [comment]
@jcupitt I actually thought about that in the meantime and updated to vips-8.3 on brew. There was no change to the two thumbnails so at least we know that it somehow affects both versions.

I'll see what carrierwave is using.

Here is a link to the raw image, its about 19MB https://mega.nz/#!2x8mCDaK!QQ2JZxvl0R_XqCwHXni2bAa1GdPIWXMxAk8Rtre9Gb8

**Comment by jcupitt** [comment]
Woah, that's huge. It's working here with `vipsthumbnail`, I'll have a look at CW too.

**Comment by skunkworker** [comment]
@jcupitt here's a gist that I extracted out of carrierwave vips . It only depends on ruby vips. https://gist.github.com/skunkworker/919a6b2574913b36bcbedccaf674e360
It assumes that you are running it in a folder with the `original.jpg` file I linked to earlier. And it produces the same artifacting on the top of the image.

**Comment by jcupitt** [comment]
carrierwave-vips is using this code:

https://github.com/eltiare/carrierwave-vips/blob/master/lib/carrierwave/vips.rb#L247

Which is a rubyization of what `vipsthumbnail` did a few years ago. I'd guess the problem is the line:

```ruby
          image = image.tile_cache(image.x_size, 1, 30)
```

Try changing the 30 to 130, it might help.

A better fix would be to get carrierwave to use the new `resize` operator. This new vips operator does what that method does, but faster, with better quality and in less memory. 

Probably the simplest way to fix this would be to move carrierwave-vips to ruby-vips8. This has all this new stuff built in. It shouldn't be a large amount of work, carrierwave-vips is only a couple of hundred lines. 

Would you have the time to try this? I'll have a quick go if you're busy.

**Comment by jcupitt** [comment]
Hey, that's a great test program! Thanks @skunkworker, I see black squares here too.

Yes, the 130 change fixes it for me, so (in my opinion) it looks like a carrierwave-vips issue.

**Comment by skunkworker** [comment]
@jcupitt strange, I'm still getting the black squares on the 130 fix inside the `def resize_image` method.

**Comment by jcupitt** [comment]
Oh, you're right, it seems rather random. If I run your gist like this I see:

```bash
$ for i in {1..100}; do ./try232.rb; vips avg out-test.png; done
94.320581
85.558365
94.320581
94.320581
94.320581
94.320581
94.320581
94.320581
94.320581
94.320581
86.053840
94.320581
94.320581
94.320581
94.320581
94.320581
94.320581
94.320581
93.871133
94.320581
94.320581
94.320581
94.320581
94.320581
94.320581
94.320581
90.434956
94.320581
90.434956
94.320581
90.638547
94.320581
94.320581
94.320581
86.053840
94.320581
94.320581...
```

So it's failing one time in 5 or 10. I'll look into it a bit more.

**Comment by skunkworker** [comment]
@jcupitt interesting. Though I do have an interest in moving carrierwave vips over to vips8 and also working on getting around to forking refile's external image modification tools to use vips as well.

**Comment by jcupitt** [comment]
You could get carrierwave-vips going a lot quicker. I notice it's not using libjpeg shrink-on-load, that would be good for at least a x4 speedup on a large image like this.

**Comment by skunkworker** [comment]
@jcupitt I'll work on that first. Does vips have some sort of image based testing to detect black boxes or other artifacts from resizing images? It would be interesting to get [American fuzzy lop](http://lcamtuf.coredump.cx/afl/) running on it.

**Comment by jcupitt** [comment]
The vips test suite uses `project` to look for black horizontal or vertical lines in resized images. 

You could use `rank`: it runs a M x N window over the image, puts all pixels within that window into an array, sorts it, and then picks element P from the array to be the output. It's the primitive used to implement median filtering.

To spot 50 x 50 (or larger) black boxes, do:

```ruby
    if image.rank(50, 50, 0).min() == 0 
        puts "50 x 50 black area in image"
    end
```

**Comment by jcupitt** [comment]
Hello again, here's your test program adapted for vips8. I've made the smallest changes I can:

https://gist.github.com/jcupitt/f00e7f4f280aceaeb7c8d298a9ebd481

I changed the cache sizing rules: it now sizes the cache to be large enough to hold two lines of tiles, plus a little bit. It seems stable for me.

vips8 has a new `resize` operator which can replace most of the `resize_image` def. I would change it to be:

```ruby
def resize_image(image, width, height, min_or_max = :min)
 ratio = get_ratio image, width, height, min_or_max
 image.resize ratio, :centre => TRUE
end
```

It does a high-quality lanczos3 resize with centre sampling, so it's a very close match for imagemagick. You can remove the sharpening stage.

**Comment by jcupitt** [comment]
I meant to say, vips 8.5 will have a new `thumbnail` operator which does things like JPEG shrink-on-load and proper handling of alpha. It should produce a very worthwhile speed improvement. 

Please reopen if it's still broken for you.

**Comment by skunkworker** [comment]
@jcupitt awesome. I'm looking forward to it.
