### ISSUE TITLE
Supported file formats

### ISSUE THREAD

**Issue by MarkSetchell** [jcupitt/libvips#429]
On this page [Using vips from the commandline](http://www.vips.ecs.soton.ac.uk/supported/8.2/doc/html/libvips/using-cli.html) it says I can see a list of supported file formats by typing `vips -l foreign` but that doesn't work. Could you maybe update that page with the correct command please?

**Comment by jcupitt** [comment]
Hi @MarkSetchell, oops, I'll fix it, thanks.

You can just do `vips -l` and look through the output for the file load/save operations. On *nix, maybe:

```
$ vips -l | grep -i foreign
```

**Comment by jcupitt** [comment]
OK, fixed in git master, there was a typo in the declaration of `VipsForeign`. Thanks!

**Comment by MarkSetchell** [comment]
Many thanks, John.

**Comment by jcupitt** [comment]
The fix is in 8.3, I'll close.
