### ISSUE TITLE
gifload is broken on many platforms

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#437]
giflib5 still has serious issues. This is a nasty one:

https://sourceforge.net/p/giflib/bugs/94/

This causes the vips test suite to fail on gif loading when compiled with giflib 5.1.2, the version in Ubuntu 16.04. Probably many other platforms which have switched to giflib5 also have this unfixed.

Unfortunately you can't really have giflib4 and giflib5 installed at the same time, since they didn't change the include name or the library prefix, so there's no giflib4 on Ubuntu 16.04. Therefore the vips `gifload` operation simply can't work on 16.04, unless you build your own giflib4 and install to a private prefix.

I don't think there's anything vips can do, we just have to wait for the giflib fixes to filter down.

@lovell, @felixbuenemann I guess this could be a problem for sharp?

**Comment by lovell** [comment]
It looks like giflib [commit cb88511](https://sourceforge.net/p/giflib/code/ci/cb88511b50621233ae93858ba38f004726d1bc5d/tree/lib/dgif_lib.c?diff=e6d243873d3a9d51f875ae747a7baf70b54c54ee) fixed this as part of v5.1.4.

My Ubuntu 14.04 [trusty-backport-giflib](https://launchpad.net/~lovell/+archive/ubuntu/trusty-backport-giflib/) PPA provides v5.1.4 and I'd be happy to create a 16.04 PPA if it helps.

**Comment by felixbuenemann** [comment]
I ran the Python test suite against 4.2.3 and master and both completed without errors. If the version that ships with Xenial is broken, then adding a bug report for the package on launchpad.net would be the right way to get it fixed.

**Comment by felixbuenemann** [comment]
I have backported the Yakkety Yak package to Xenial Xerus in [ppa:louisinternet/giflib](https://launchpad.net/~louisinternet/+archive/ubuntu/giflib) and if fixes the problems with loading gifs in both gifload ang magickload.

I have opened [Bug #1580376](https://bugs.launchpad.net/ubuntu/+source/giflib/+bug/1580376) on Launchpad, to get the fixed version into Xenial.

**Comment by felixbuenemann** [comment]
**Good News:** There has been some progress on [Bug #1580376](https://bugs.launchpad.net/ubuntu/+source/giflib/+bug/1580376) to get the fixed version into Ubuntu Xenial. The fixed package version 5.1.4-0.3 is now in the xenial-proposed repository.

You can help by testing that version (see [instructions](https://bugs.launchpad.net/ubuntu/+source/giflib/+bug/1580376/comments/6)) and leaving a comment on the launchpad tracker.

**Comment by felixbuenemann** [comment]
> The verification of the Stable Release Update for giflib has completed successfully and the package has now been released to -updates.

Do we know of other distributions that ship problematic giflib versions?
Otherwise I think this issue can be closed.

**Comment by jcupitt** [comment]
This fix has just arrived on my desktop! Nice!

Sure, let's close.

**Comment by felixbuenemann** [comment]
Great — and sorry for not tending to my open PRs, I'm just to busy working on other stuff right now and will get back to them as soon as I find some time.
