### ISSUE TITLE
libwebp not detected on Ubuntu Precise

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#440]
The detection of libwebp on Ubuntu 12.04 Precise is currently not working, because the packages are missing pkg-config configuration files.

This is currently not showing up on Teavis CI, because a newer webp package from the lyrasis/precise-backports ppa is used.

If we want to support the systems webp packages on precise, we should fallback to a classic include/link check, if the pkg_config check fails.

It probably makes sense to drop the backports ppa on Travis CI. It would cause the webp lossless check in test_formats.sh to fail, but that could be worked around by setting the quality to 90 instead of 0, which would turn the error into a warning. Dropping the ppa will also be required for #438.

**Comment by jcupitt** [comment]
We'd need something like `FIND_WEBP` in `acinclude.m4` I guess. I'll have a go.

**Comment by jcupitt** [comment]
OK, added a fallback.

I tested by removing my `libwebp.pc` and configure still found webp. I looked through config.log and it all seemed sensible. Hopefully it'll work on travis too.

**Comment by felixbuenemann** [comment]
Working fine now, see #442.
