### ISSUE TITLE
Resize rounding changed in 8.3

### ISSUE THREAD

**Issue by mikesmith20** [jcupitt/libvips#444]
I had some regression tests break because of what looks like a change in vips_resize rounding.

If I pass a shrink of 1.0 / 10.2298, with an original size of 1024x683.

8.2: 100x67
8.3: 100x66

683 x (1.0 / 10.2298) is about 66.766.

**Comment by jcupitt** [comment]
Oh dear, I'm sorry it broke your tests. 

8.3 has a new image downsizer which should be noticeably faster and better quality. The rounding changed too, to be more in line with ImageMagick. It strictly rounds down now, so the calculation is

```
floor(683.0 * (1.0 / 10.2298))
```

which is 66.
