### ISSUE TITLE
vipsthumbnail premultiply breaks tiff output

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#447]
Due to issue #291 `vipsthumbnail` does premultiply / resize / unpremultiply, if the source image contains an alpha channel.

This does not work correctly, when the input image has an alpha channel (like png, tiff) and the output image is tiff.

**Example Command:** `vipsthumbnail -s 300 -f 'tn_%s.tif' alpha.png`

Instead of the correct result, the opaque areas of the image are displayed in solid white with coloured fringes around the edges.

I tested the same code using pyvips8 and I get the same problem.

If I remove the premultiply / unpremultiply steps, the resulting TIFF is fine.

The output image also looks wrong (solid white areas), if only multiply without unpremultiply is applied.

**Comment by felixbuenemann** [comment]
**Minimal Python Example:**

```python
from gi.repository import Vips

im = Vips.Image.new_from_file('alpha.png')
im = im.premultiply(max_alpha=255)
im = im.unpremultiply(max_alpha=255)
im.write_to_file('out.tif')
```

I noticed that the resulting image now has band format float instead of uchar.

**Comment by jcupitt** [comment]
Ooop oh dear:

```
$ vipsheader Opera-icon-high-res.png 
Opera-icon-high-res.png: 3056x3325 uchar, 4 bands, srgb, pngload
$ vipsthumbnail Opera-icon-high-res.png -o x.tif
$ vipsheader x.tif 
x.tif: 117x128 float, 4 bands, scrgb, tiffload
```

`vipsthumbnail` should clearly convert back to the input format and not rely on the savers to do this.

**Comment by felixbuenemann** [comment]
Jepp, `im = im.cast(Vips.BandFormat.UCHAR)` fixes things.

**Comment by jcupitt** [comment]
Seems to fix vipsthumbnail for me. But it looks like there might be a rounding problem in unpremultiply, I'll have a look.

**Comment by felixbuenemann** [comment]
It also seems to change colourspace from srgb to scrgb, should I open another issue for that?

**Comment by felixbuenemann** [comment]
Sorry, forgot `make install`. It's fine now.
