### ISSUE TITLE
Convert 16-bit to 8-bit C API

### ISSUE THREAD

**Issue by ismikhail** [jcupitt/libvips#449]
Hi,

I'm using the C API to read, resize and write and image. Everything works great until I try to convert 16-bit PNG into a 8-bit JPEG using vips_jpegsave_buffer() function. According to the docs I need to use vips_copy() to convert 16-bit image to 8-bit. I tried the following code without any luck.

```
// t[0]->Type = VIPS_INTERPRETATION_RGB16
// t[0]->Bbits = 16
// t[0]->Bands = 4

vips_copy( t[0], &t[1],
		"bands", t[0]->Bands,
        "interpretation", VIPS_INTERPRETATION_sRGB,
        NULL );
```

Is there a parameter I'm missing here?

**Comment by jcupitt** [comment]
Hi @ismikhail, you don't need to convert, the jpeg save will do it for you automatically.

If you want to convert 16->8 yourself, use `vips_colourspace()`:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-colour.html#vips-colourspace

eg.:

```
vips_colourspace( in, &out, VIPS_INTERPRETATION_sRGB, NULL );
```

`vips_copy()` lets you change header fields without changing data, so if an image is tagged as RGB16 but you happen to know it's really sRGB, you can change the tag.

**Comment by ismikhail** [comment]
Hi John,

Thanks for replying to my post! After further testing I found out that the image comes out wrong after i use vips_flatten. If i do not flatten vips_savejpeg uses black background by default and the resulting image comes out a little darker. Here is the input and output images. 
in.png
![in](https://cloud.githubusercontent.com/assets/2288662/15455766/14552556-2013-11e6-9f32-7c63e22041fe.png)
out.jpg
![out](https://cloud.githubusercontent.com/assets/2288662/15455767/1b606360-2013-11e6-8c49-f3c1d6edf3d0.jpg)
without vips_flatten
![out](https://cloud.githubusercontent.com/assets/2288662/15455797/b3a64626-2013-11e6-8d51-203e9bce4dc8.jpg)


And here is the source code:

```
#include <vips/vips.h>

int main(int argc, char *argv[])
{
    double scale = .9;
	VipsImage *global;
    VipsImage **t;

    global = vips_image_new();
    t = (VipsImage **) vips_object_local_array(VIPS_OBJECT(global), 3);

    if (!(t[0] = vips_image_new_from_file(argv[1], NULL))) {
        g_object_unref(global);
        vips_error_exit("unable to read %s", argv[1]);
    }

    if (vips_resize(t[0], &t[1], scale, NULL)) {
        g_object_unref(global);
        vips_error_exit("unable to resize %s", argv[0]);
    }

    VipsArrayDouble *array = vips_array_double_newv(3, 255.0, 255.0, 255.0);
    if (vips_flatten(t[1], &t[2], "background", array, NULL)) {
		g_object_unref(global);
        vips_error_exit("unable to flatten %s", argv[0]);
    }

    vips_jpegsave(t[2], argv[2], "Q", 90, NULL);

    g_object_unref(global);

    return 0;
}
```

**Comment by jcupitt** [comment]
Argh! Oh dear, yes, it seems `vips_flatten()` does not work on 16-bit images. For example:

```
vips flatten in.png x.png
```
Makes a crazy image. I'll have a look.

**Comment by jcupitt** [comment]
Oh ahem, I forgot, you need to tell it the maximum alpha value. Try:

```
$ vips flatten in.png x.png --max-alpha 65535
```

Perhaps it should default to the correct max-alpha for your image type, rather than just 255.

**Comment by jcupitt** [comment]
For your code, just remove the flatten, `jpegsave` will do it automatically. You can pass the background to the jpegsave instead, for example:

https://gist.github.com/jcupitt/abb06129c1f7d40597e98e45eaa732c9

**Comment by jcupitt** [comment]
I though of one more thing: you can use a one-element background, for example:

```
    VipsArrayDouble *array = vips_array_double_newv(1, 255.0);
```

It'll be expanded to match the image. This way your code will work for grey + alpha as well.

**Comment by jcupitt** [comment]
I changed flatten/premultiply/unpremultiply to default to 65535 for RGB16/GREY16 images, so this should be simpler in vips 8.4. Thanks!

**Comment by ismikhail** [comment]
Thanks a lot John, I'll try all of your suggestions.

**Comment by ismikhail** [comment]
I ended up using vips_colourspace to convert to VIPS_INTERPRETATION_sRGB and it worked. Thanks!

**Comment by jcupitt** [comment]
Good, glad it's working, I'll have a look at this in a bit, I'm still fixing up tiff orientation.

I didn't see your update. github only sends notifications for new posts.

**Comment by jcupitt** [comment]
I think it's fixed now, git master now knows that if jpg compression is on, tiffsave should convert. Yuo can now run:

```
$ vips copy rope.dng x.tif[compression=jpeg]
```

for example.

Of course that image will look pretty bad: jpg compression will not work well on a DNG, you really need to demosaic first.

**Comment by jcupitt** [comment]
I think we're done, I'll close.

**Comment by ismikhail** [comment]
Thanks a lot, appreciate your help!
