### ISSUE TITLE
im_vips2tiff rotates dng images 90 degrees on conversion to ptif

### ISSUE THREAD

**Issue by nikolaykolev** [jcupitt/libvips#454]
Hello, first if there is such issue I'm sorry I couldn't find it.
So ... I am converting some dng files to ptif files using im_vips2tiff, but some of them are being rotated on 90 degrees, and some are ok after the conversion. I am using this command:

vips im_vips2tiff image.dng image.ptif:jpeg:90,tile:512x512,pyramid

I'm attaching a file that is rotated after the conversion(1.dng) and one that is not(2.dng). If you have any idea how to prevent this or how to recognize the images that are going to rotate it will be ok in both ways.
[images.zip](https://github.com/jcupitt/libvips/files/283968/images.zip)

**Comment by jcupitt** [comment]
Hi @nikolaykolev,

vips does not support the orientation tag in tiff files (your .dng camera files are tiffs under the hood). One of your photos was taken with the camera rotated, and this rotation is not being undone.

I'll add a note about supporting tiff orientation to the vips todo list. I'm not sure what your best short-term fix is. You can detect rotation like this:

```
$ tiffinfo 1.dng | grep Orientation 
  Orientation: row 0 rhs, col 0 top
```

You'd need to parse that and apply a `rot90` or `rot270` before building the pyramid.

You're also using the old vips7 syntax, the new vips8 command would be:

```
vips tiffsave 2.dng 2.ptif --compression jpeg --Q 90 --tile --tile-width 512 --tile-height 512 --pyramid
```

It'll be quicker and use less memory, especially on large images. You can see all of the options if you run `tiffsave` with no arguments.

**Comment by jcupitt** [comment]
Related issue: https://github.com/jcupitt/libvips/issues/243

**Comment by nikolaykolev** [comment]
Thanks for the quick reply. I think this will do the trick. 
Thank you very much!

**Comment by jcupitt** [comment]
I've just merged a new orientation system to master, vips 8.4 should handle this automatically. Thanks for suggesting this useful feature .

**Comment by abubelinha** [comment]
> You're also using the old vips7 syntax, the new vips8 command would be:
> 
> ```
> vips tiffsave 2.dng 2.ptif --compression jpeg --Q 90 --tile --tile-width 512 --tile-height 512 --pyramid
> ```
> 
> It'll be quicker and use less memory, especially on large images. You can see all of the options if you run `tiffsave` with no arguments.

Sorry to use this old thread @jcupitt  
I arrived here googling for vips documentation on the usage of functions like im_vips2jpeg or im_vips2tiff
They are present in a 10 years old script present in my old WinXP machine.

Looks like many of those functions will be now deprecated. Can you point me to any documents dated on the moment of that change, so I can easily find out how to translate the old funcions to the new ones?

Thanks a lot

**Comment by jcupitt** [comment]
Hello @abubelinha,

There's a chapter in the docs on the CLI:

https://libvips.github.io/libvips/API/current/using-cli.html

It should be simple to translate: just type eg. `vips vips2tiff` at the command prompt and it'll tell you all the arguments and flags.

**Comment by abubelinha** [comment]
> It should be simple to translate: just type eg. `vips vips2tiff` at the command prompt and it'll tell you all the arguments and flags.

OK, but you mean `vips tiffsave`, don't you? 
(or the old version, `vips im_vips2tiff`)
Because:

```
$  vips -v
vips-8.4.5-Wed Jan 18 12:36:44 UTC 2017
$ vips vips2tiff
vips: unknown action "vips2tiff"
```

Thanks a lot for your prompt answer and the CLI docs link!

**Comment by jcupitt** [comment]
Ooop, you're right. Not paying attention.
