### ISSUE TITLE
Vips dzsave google layout unexpected padding

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#459]
I noticed that the vips dzsave google layout uses an unexpected padding that leads to unwanted behavior when used with the openseadragon viewer and when using wrap-around mode.

I'm testing with a 86400x43200 TIFF image and the default settings using vips master.

In the smallest tile the image does not stretch over the full width of the tile, but instead is aligned to the left top with padding to the right and bottom:

![0](https://cloud.githubusercontent.com/assets/909587/15765891/1067c2de-293a-11e6-953e-4f28fbcce31c.jpg)

I would have expected this:

![tile_0_nw](https://cloud.githubusercontent.com/assets/909587/15766080/7af9ccd6-293b-11e6-9bf6-c5647a920d7e.jpg)

I also tried `--centre` option which also adds padding. The source image is auto-extended from 86400x43200 to 131072x131072 by vips and this is the smallest tile:

![0](https://cloud.githubusercontent.com/assets/909587/15766144/df35b890-293b-11e6-9513-965eb01cb503.jpg)

I would have expected the images to be extended to 86400x86400 and the smallest tile to look like:

![tile_0_c](https://cloud.githubusercontent.com/assets/909587/15766207/4a4e76da-293c-11e6-9929-460f1026e776.jpg)

I also tried with tile sizes which were evenly divisible like 192 or 450, but I always ended up with padding in the lowest zoom level.

So why isn't vips scaling the image to perfectly fit the tiles for each zoom level?

**Comment by jcupitt** [comment]
I copied the google maps layout and behaviour from the NYU path SlideTiler. Unfortunately they had their code on google code and it's all vanished :( I can't find the current version.

I can see that upsizing could be an alternative to padding. Perhaps we need another option? It would be a simple thing to add.

**Comment by jcupitt** [comment]
I suppose the counter argument would be that if you upsize, the highest res tileset could be enlarged by up to x2, and would probably look slightly fuzzy. 

If you pad instead of upsizing, you are guaranteed to have a sharp image, and it'll be smaller too, since dzsave won't save the padding tiles, it'll rely on the viewer to replace them with `blank.png`.

Google probably avoids this problem by simply rendering their images at the correct size to avoid half-tiles. That's not really possible for openslide.

**Comment by felixbuenemann** [comment]
In the PDF from microimages describing the google maps layout all their zoom levels were perfect multiples so they had no problem with wrapping around the edges. I'll have to think about a good solution.

**Comment by jcupitt** [comment]
I think this is done, I'll close.
