### ISSUE TITLE
free non-worker buffers

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#466]
We free buffers on `vips__buffer_shutdown()`, called during thread shutdown, but this won't happen for the main thread until program exit! Therefore any buffers allocated on the main thread will never leave cache,
and will eventually fill it with junk, forcing all operations out.

We need to free buffers on image close, not thread exit.

Branch with experimental fixes for this issue:

https://github.com/jcupitt/libvips/tree/free-non-worker-buffers

This patch had a simple fix:

https://github.com/jcupitt/libvips/commit/2a77301033146dfbaf8e8a9fa1fb8fb6a567162b

But that broke sharp, since it assumed a single main thread, whereas sharp can use many main threads.

**Comment by lovell** [comment]
Meanwhile, I'll investigate using node's [AtExit](https://nodejs.org/dist/latest-v6.x/docs/api/addons.html#addons_atexit_hooks) to explicitly call `vips_shutdown` on what I hope will be its main main thread.

**Comment by jcupitt** [comment]
Phew, I think I've found a better solution. Hopefully you won't see a crash on exit with node.

**Comment by lovell** [comment]
I can confirm there's no segfault on exit with commit b90145c :tada:

**Comment by jcupitt** [comment]
Here's a tiny program to show the difference this patch makes:

```python
#!/usr/bin/python

import sys
import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

for name in sys.argv[1:]:
    print name, "cache =", Vips.cache_get_size(), "mem =", Vips.tracked_get_mem()
    image = Vips.Image.new_from_file(name, access = Vips.Access.SEQUENTIAL)
    image = image.resize(100.0 / image.width)
    image.write_to_file("tn_" + name)
```

If I make 10000 test images (`k2.jpg` is a 1450x2048 pixel RGB jpg) and run it without the patch I see:

```
$ time for i in {1..10000}; do cp ~/pics/k2.jpg $i.jpg; done
$ time ../process.py *
10000.jpg cache = 0 mem = 0
1000.jpg cache = 17 mem = 677493
1001.jpg cache = 33 mem = 1354948
1002.jpg cache = 49 mem = 2032403
1003.jpg cache = 65 mem = 2709858
1004.jpg cache = 81 mem = 3387313
1005.jpg cache = 97 mem = 4064768
...
1162.jpg cache = 1000 mem = 103729113
1163.jpg cache = 1000 mem = 104165801
1164.jpg cache = 0 mem = 104602489
1165.jpg cache = 0 mem = 104687631
1166.jpg cache = 0 mem = 104864927
1167.jpg cache = 0 mem = 104991374
1168.jpg cache = 0 mem = 105038044
1169.jpg cache = 0 mem = 105080360
116.jpg cache = 0 mem = 105080360
1170.jpg cache = 0 mem = 105122676
1171.jpg cache = 0 mem = 105164973
1172.jpg cache = 0 mem = 105172473
1173.jpg cache = 0 mem = 105214789
1174.jpg cache = 0 mem = 105214789
....
9998.jpg cache = 0 mem = 105214789
9999.jpg cache = 0 mem = 105214789
999.jpg cache = 0 mem = 105214789
99.jpg cache = 0 mem = 105214789
9.jpg cache = 0 mem = 105214789
real	6m50.016s
user	6m19.244s
sys	0m17.384s
```

At 1163, the operation cache has filled. Soon after, junk left on the main thread fills the pool of tracked memory. vips tries to free some memory by dropping operations from cache, but it can't free the main thread stuff this way and the whole cache empties. By 1174, memory use stabilises, some way above 100mb.

Here's the same thing with this patch:

```
$ time ../process.py * 
10000.jpg cache = 0 mem = 0
1000.jpg cache = 17 mem = 677493
1001.jpg cache = 33 mem = 1354948
...
1054.jpg cache = 961 mem = 40647338
1055.jpg cache = 977 mem = 41324793
1056.jpg cache = 993 mem = 42002248
1057.jpg cache = 1000 mem = 42679609
1058.jpg cache = 1000 mem = 42679609
1059.jpg cache = 1000 mem = 42679609
...
9998.jpg cache = 1000 mem = 42679609
9999.jpg cache = 1000 mem = 42679609
999.jpg cache = 1000 mem = 42679609
99.jpg cache = 1000 mem = 42679609
9.jpg cache = 1000 mem = 42679609
real	6m43.047s
user	6m15.428s
sys	0m12.360s
```

So by 1059, we have 1000 operations in cache and 42mb of memory allocated. Everything is stable from that point on, for about a 60mb saving.

**Comment by felixbuenemann** [comment]
@jcupitt I saw the following sporadic error on shutdown using ruby-vips8 yesterday:

```ruby
./tiff2hashed_intermediates.rb: line 0
   GLib-CRITICAL **:g_hash_table_remove_internal: assertion 'hash_table != NULL' failed
./tiff2hashed_intermediates.rb: line 0
   GLib-CRITICAL **:g_hash_table_remove_internal: assertion 'hash_table != NULL' failed
./tiff2hashed_intermediates.rb: line 0
   GLib-CRITICAL **:g_hash_table_remove_internal: assertion 'hash_table != NULL' failed
./tiff2hashed_intermediates.rb: line 0
   GLib-CRITICAL **:g_hash_table_remove_internal: assertion 'hash_table != NULL' failed
./tiff2hashed_intermediates.rb: line 0
   GLib-CRITICAL **:g_hash_table_remove_internal: assertion 'hash_table != NULL' failed
./tiff2hashed_intermediates.rb: line 0
   GLib-CRITICAL **:g_hash_table_remove_internal: assertion 'hash_table != NULL' failed
```

Could this be caused by 2a77301033146dfbaf8e8a9fa1fb8fb6a567162b which has since been reverted?

**Comment by jcupitt** [comment]
@felixbuenemann I guess it's possible. The new stuff in `free-non-worker-buffers` should be safer, so it could help.

**Comment by jcupitt** [comment]
OK, merged to master. Thanks everyone!
