### ISSUE TITLE
How to get image size (width & height) from CLI

### ISSUE THREAD

**Issue by yurykovshov** [jcupitt/libvips#467]
Hi John,

I went through all vips functions and, looks like, there is no possibility to get an image size from the command-line interface. 
Or may be I'm looking in a wrong direction? Could you please give me a clue where to look for?

Many thanks,
Yury

**Comment by jcupitt** [comment]
Hi Yury, try:

```
$ vipsheader -f width k2.jpg
1450
```

You can get any header field, try `vipsheader -a` to see them all.

**Comment by yurykovshov** [comment]
Thank you!

**Comment by sergeevabc** [comment]
``` console
$ magick identify -format %G in.jpg
4000x2672

$ magick identify -format "%f, %[width]x%[height], %B bytes" in.jpg
in.jpg, 4000x2672, 6316473 bytes
```

`vipsheader` seems to be unable to output multiple format fields at once, aggrrrhh.

**Comment by sergeevabc** [comment]
John, I try to reduce the number of disk operations to extend the life of the disk. For example, Tor configuration file 'torrc' even has a dedicated option called 'AvoidDiskWrites 1'. In this case, I found the following one-call way that @yurykovshov might find useful.

The contents of getSize.cmd

``` console
@echo off

for /f "tokens=2 delims=:," %%a in ('vipsheader "%~1"') do for /f "tokens=1" %%b in ("%%a") do set "_size=%%b"

echo %_size%
```

Then we call it as follows

``` console
$ getSize.cmd "example photo.jpg"

4000x2672
```

**Comment by jcupitt** [comment]
Oh, that's nice.

I agree that something like:

```
$ vipsheader -f width -f height k2.jpg
1450
2048
```

Would be useful. Unfortunately the CLI arg parser libvips uses makes supporting repeated flags awkward, so it's not a trivial change.

**Comment by jcupitt** [comment]
Ah maybe it is easy, I'll make a PR.

**Comment by jcupitt** [comment]
I made quick PR for this feature. I can now do:

```
$ vipsheader -f width -f height k2.jpg
1450
2048
```

Thanks for the suggestion!
