### ISSUE TITLE
Building 'master' under cygwin fails

### ISSUE THREAD

**Issue by DFKSingleton** [jcupitt/libvips#470]
Sorry to report another small problem!

I have tried to build the GIT master under cygwin, using the instructions "Building libvips from git". the "brew" command does not seem to be available under cygwin (or I could not find a package to install it). Never mind, it was possible to install the dependancies without problem. I then called ./bootstrap.sh, as advised. Automake complained about several of the Makefile.am's. A typical complaint was the following:

cplusplus/Makefile.am:9: error: Libtool library used but 'LIBTOOL' is undefined
cplusplus/Makefile.am:9:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
cplusplus/Makefile.am:9:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
cplusplus/Makefile.am:9:   If 'LT_INIT' is in 'configure.ac', make sure
cplusplus/Makefile.am:9:   its definition is in aclocal's search path.

I will google to see if I can find any more useful information.

Naturally, the problem does not arise with the distributions, because ./configure has already been created (probably on a linux system). 

Best wishes

David singleton

**Comment by DFKSingleton** [comment]
bootstrap.sh produced the following error message:

./bootstrap.sh: Zeile 62: libtoolize: Kommando nicht gefunden.
(Sorry my cygwin uses the German locale, but I think the meaining is clear!)

After googling for causes and then installing the libtool package, ./configure now seems to work. 

I think that we can regard this issue as closed

**Comment by jcupitt** [comment]
I've never tried under cygwin myself, good to know it's working.

**Comment by jcupitt** [comment]
Of course that'll make a cygwin binary. If you want to make something that links under VS, you'll need a native win binary. I make them with this thing:

https://github.com/jcupitt/build-win64

It'll need a linux VM, but it's pretty simple, just two commands to make the binary.
