### ISSUE TITLE
Getting "arrayjoin: too many arguments" with commandline vips

### ISSUE THREAD

**Issue by peterLaurence** [jcupitt/libvips#471]
Hi,

I wrote a script that assembles many small tiles into one big file. It works fine until some limit in number of arguments is reached.
I am using vips arrayjoin like this in my bash script :

```
#!/bin/bash
dirlist=(`find $directory -type d`)
imagelist=(`ls ${dirlist[1]}`)
allimages=()
for image in ${imagelist[*]}
do
  sublist=(`find $directory -type f -name $image | sort -n`)
  #echo ${sublist[*]}
  allimages+=("${sublist[@]}")
done
#echo ${allimages[*]}

xwide=$((${#dirlist[@]} - 1))
echo ${#allimages[@]}
vips arrayjoin "${allimages[@]}" out.png --across $xwide --vips-progress
```

I am getting the error "arrayjoin: too many arguments" with the size of my input array of image being 24564. How could i get around this?
Thanks.

**Comment by jcupitt** [comment]
Holy Moley that's a lot of images!

Looking at arrayjoin I don't see an obvious limit there. The message is actually generated by the thing that calls arrayjoin when there are more arguments supplied than the operation needs. That suggests you've broken bash: perhaps the closing `"` from your array argument has been truncated?

Bash has a limit on command-line length (I think). What happens if you use shorter filenames? Can you join more files up before hitting the limit?

You could also consider rewriting your bash script in Python. It should be able to do arrays of any size.

**Comment by peterLaurence** [comment]
Yes that's a lot of images :D

Indeed, i may have broken bash args limit here. I haven't tried to use shorter filenames, but with (much) fewer images it works. I am trying to write this in C++ right now, to get rid of that limit.

**Comment by jcupitt** [comment]
I'm just testing a py version now, wait a sec.

**Comment by peterLaurence** [comment]
Thanks!

**Comment by peterLaurence** [comment]
Also, as a side question, if i make a program in C++ equivalent to the script, is libvips required to be installed on the system for the program to execute, or the program self-contains everything?

**Comment by jcupitt** [comment]
This works for me:

```python
#!/usr/bin/env python

import os
import sys

import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

Vips.progress_set(True)

images = []
for dirname in sys.argv[2:]:
    for filename in os.listdir(dirname):
        images.append(Vips.Image.new_from_file(dirname + "/" + filename,
                                               access = Vips.Access.SEQUENTIAL))

join = Vips.Image.arrayjoin(images, across = 100)
join.write_to_file(sys.argv[1])
```

You'll need a lot of RAM. My laptop has 6gb and can join 30,000 100x100 pixel jpg images OK, but falls over doing 30,000 1024x768 jpgs. You'll need to raise the number of files with `ulimit -n 40000`, of course.

**Comment by peterLaurence** [comment]
Thanks, i will test this approach and give feedback.

**Comment by jcupitt** [comment]
You can make a static binary, but it's not easy and doesn't work very well.

I would make a directory and put the program plus the libs in that, plus a small wrapper script to set the various environment variables. 

You could use a container, like docker, as well. That might be simplest.

**Comment by peterLaurence** [comment]
Ok so that's not that simple, good to know.

**Comment by peterLaurence** [comment]
Before testing the python method, i am finishing my first attempt with C++, but I am having a hard time using vips_arrayjoin, especially with the out parameter which needs to be a `VipsImage **out`, while i only need it to be "out.png" for instance (this is my first time with libvips..).
Could you provide a little sample of vips_arrayjoin in C/C++, that would help a lot.
Thanks again.

**Comment by peterLaurence** [comment]
Do you think that joining many tiles like this could use "little" amount of RAM? Obviously in the python script we store all tiles before joining them. Could it be done in a more efficient way?
As i still haven't got a working C++ program equivalent to my bash script, i am thinking of giving up and go for the python solution (i have much more experience with that language so it won't be a problem).

**Comment by peterLaurence** [comment]
I successfully wrote a python script. But i have only 6GB RAM and my computer falls down at 75% of the task. I noticed that it uses the swap partition when no more RAM is available. Will try to increase the swap.

**Comment by jcupitt** [comment]
We can probably tune it a bit. How large are the images you are joining, what is their filetype, are they all the same size? 

libvips has about five different ways of opening images, I don't know if you've seen:

http://libvips.blogspot.co.uk/2012/06/how-libvips-opens-file.html

Dropping or changing the access hint might help, or maybe changing the file format.

**Comment by peterLaurence** [comment]
They are all 256x256 png images.
Right now after the swap increase i have a result 35328 x 45568 png, but there is something wrong with  the produced image. I may have done something wrong in my script (i'm checking right now).

**Comment by jcupitt** [comment]
I experimented a bit, and with 30,000 256x256 pngs this runs in the smallest amount of memory for me:

```python
#!/usr/bin/env python

import os
import sys

import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

#Vips.leak_set(True)
#Vips.progress_set(True)

images = []
for dirname in sys.argv[2:]:
    for filename in os.listdir(dirname):
        images.append(Vips.Image.new_from_file(dirname + "/" + filename,
                                               access = Vips.Access.SEQUENTIAL_UNBUFFERED))

join = Vips.Image.arrayjoin(images, across = 170)
join.write_to_file(sys.argv[1])
```

About 5gb peak RSS, takes about two minutes to run. Keep leak tracking off, it needs quite a bit more memory. That's with RGB PNG, RGBA will need a bit more. 

The image seems fine, but you'll find a lot of image viewers will barf on a 45k x 45k PNG image. nip2 will view it OK, fwiw, though it takes a while to open it. How are you going to present the image? Deepzoom might be a better choice.

**Comment by peterLaurence** [comment]
Yeess!!
The produced image is fine, it was my image viewer (shotwell on ubuntu) that was completely messed up. Apparently, when he has to swap for image preview, something is going really wrong.
I know the produced image is actually good thanks to vipsthumbnail.

Hah i just see your new post. Thanks. I am testing this asap.

**Comment by peterLaurence** [comment]
Confirmed that with using `Vips.Access.SEQUENTIAL_UNBUFFERED`, it needs much less memory (i almost didn't have to swap).

Indeed i am going to use deepzoom to present the image. I have already written an Android app able to present tiled images produced by libvips dzsave. FWIW, here's the link : https://github.com/peterLaurence/TrekAdvisor

**Comment by jcupitt** [comment]
Here's a C++ version, fwiw. It's almost the same as the Python one.

```C++
/* compile with
 *      g++ -g -Wall arrayjoin.cpp `pkg-config vips-cpp --cflags --libs`
 */

#include <stdlib.h>
#include <vips/vips8>

using namespace vips; 

int
main( int argc, char **argv )
{
        if( VIPS_INIT( argv[0] ) )
                vips_error_exit( NULL );

        std::vector<VImage> images;

        for( int i = 2; i < argc; i++ ) 
                images.push_back( VImage::new_from_file( argv[i],
                        VImage::option()->set( "access",
                                VIPS_ACCESS_SEQUENTIAL_UNBUFFERED ) ) );

        VImage join = VImage::arrayjoin( images,
                VImage::option()->set( "across", 170 ) );

        join.write_to_file( argv[1] );

        return( 0 );
}
```

**Comment by peterLaurence** [comment]
Nice. Does the C++ version use less memory on your tests?

**Comment by jcupitt** [comment]
They build the same vips pipeline, so speed and memory is almost identical. It's a few seconds faster.

**Comment by peterLaurence** [comment]
Ok so i'm fine with my python script. But the C++ version might be interesting if one day i have the courage to use Docker and make a portable executable.
I have everything i need, thanks for your help!

**Comment by jcupitt** [comment]
You can write deepzoom directly, I guess you know. Try that python script with:

```
$ time ./arrayjoin.py x.dz x
real	2m23.483s
user	4m45.632s
sys	0m48.564s
```

So no slower than png write, and much more work done. It'll write `x.dzi` and `x_files`.

PNG really is an awful format :( it's excruciatingly slow and no one knows why. And the images are huge.

**Comment by peterLaurence** [comment]
I usually create a deepzoom from an existing image. But this time i only had tiles obtained from openstreetmap servers, which only serves [png file](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames).
I didn't know i could produce the deepzoom directly. Good to know.
