### ISSUE TITLE
svgload does not detect svgz files

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#473]
Currently svgload is not used for `.svgz` files, which is the file extension used for gzip-compressed svg files.

Most major svg programs can generate `.svgz` in addition to `.svg`, so it would be nice if this format was supported by svgload as well. I'm pretty sure, this is only an issue with the format detection code, because `rsvg-convert` from librsvg 2.4 handles `.svgz` files just fine.

I'm not sure what's the best solution to the problem, because the current detection code bypasses librsvg and does some plain text sniffing, which would mean it would have to also detect gzip, uncompress a couple of bytes and then search on the result…

If you also have magickload enabled, it will eventually load the svgz, but magickload is slow and its svg support is worse then librsvg's.

**Comment by jcupitt** [comment]
I suppose we could add a `svgzload` operation which just looked at the filename suffix. If there's no file sniffer, it'll fall back to just testing the filename suffix:

https://github.com/jcupitt/libvips/blob/master/libvips/foreign/foreign.c#L471

It wouldn't work for memory buffers. Perhaps users could just call `svgzload_buffer` by hand if they wanted that.

**Comment by felixbuenemann** [comment]
Hmm, don't you think it's a bit confusing to have two different loaders, that end up calling the exact same code after the detection stage?

**Comment by jcupitt** [comment]
Well, that's true. The alternative is to look for the gz magic number and if we see it, decompress the first few hundred bytes. I've not looked into libz, I don't know how easy that is.

**Comment by felixbuenemann** [comment]
I looked at the [zlib manual](http://www.zlib.net/manual.html) and I think you could use the `uncompress` function with a fixed size destination buffer, that's big enough to hold as much uncompressed xml as is required to run the detection code. The call to `uncompress` should return `Z_BUF_ERROR`, but you should still be able to read the output buffer.

**Comment by felixbuenemann** [comment]
OK, it's not actually that easy. I tried it with a small sample program and it returned a stream error, so I guess uncompress is for raw deflate streams. I'll try to come up with a short example using the advanced zlib api.

**Comment by felixbuenemann** [comment]
Here's a small sample program that decodes up to `OSIZE` bytes from the input buffer:

```c
#include <stdio.h>
#include <zlib.h>

#define BLANKPAGE_SVGZ {31, 139, 8, 0, 0, 0, 0, 0, 2, 3, 53, 76, 53, 186, 194, 96, 16, 172, 249, 79, 177, 223, 82, 199, 221, 165, 121, 232, 29, 208, 184, 123, 114, 121, 228, 1, 213, 248, 152, 237, 16, 194, 112, 111, 218, 184, 44, 44, 228, 16, 166, 60, 43, 90, 11, 163, 174, 171, 116, 134, 25, 199, 145, 30, 5, 186, 108, 66, 134, 103, 89, 150, 121, 181, 17, 134, 248, 62, 250, 229, 100, 33, 11, 44, 72, 154, 4, 170, 200, 163, 77, 86, 102, 117, 238, 34, 104, 187, 166, 76, 239, 22, 174, 131, 32, 64, 8, 226, 44, 251, 241, 155, 133, 199, 215, 36, 122, 77, 134, 215, 100, 195, 46, 200, 216, 196, 124, 159, 218, 228, 9, 215, 155, 22, 227, 137, 0, 0, 0}

#define OSIZE 224

#define WINDOW_BITS 15
#define GZIP 32

int main(void) {
  z_stream zs = {0};
  unsigned char ibuf[] = BLANKPAGE_SVGZ;
  unsigned char obuf[OSIZE];
  size_t ilen = sizeof(ibuf);
  size_t opos = 0;
  int ret;

  zs.zalloc = Z_NULL;
  zs.zfree = Z_NULL;
  zs.opaque = Z_NULL;
  zs.next_in = ibuf;
  zs.avail_in = ilen;

  ret = inflateInit2(&zs, WINDOW_BITS | GZIP);
  if (ret != Z_OK) {
    fprintf(stderr, "Zlib init failed: %d\n", ret);
    return 1;
  }

  do {
    zs.avail_out = OSIZE - opos;
    zs.next_out = obuf + opos;
    ret = inflate(&zs, Z_NO_FLUSH);
    if (ret < Z_OK) {
      fprintf(stderr, "Zlib inflate failed: %d\n", ret);
      return 1;
    }
    opos = OSIZE - zs.avail_out;
  } while (opos < OSIZE && zs.avail_out == 0);

  inflateEnd(&zs);

  fwrite(obuf, opos, 1, stdout);

  return 0;
}
```

Note that the uncompressed input could be smaller than `OSIZE`, so `opos` should be checked to get the actual decoded length. For example the embedded SVGZ is only 137 bytes uncompressed.

I've simplified the code to use a fixed size buffer, because that's what `vips_foreign_load_svg_is_a_buffer` is currently using. For streams another loop would be needed to update the input buffer.

**Comment by felixbuenemann** [comment]
@jcupitt I'll have a go at integrating the above code myself and adding a test. I'll probably need some help with adding the zlib check to configure.

**Comment by jcupitt** [comment]
I have some time this afternoon Felix, shall I have a quick try at this?

**Comment by felixbuenemann** [comment]
@jcupitt I already have a working PR for this #476, you could look at the comments.

There were two todos:

* Add a configure check for a string function 
* Add support for double extensions (.svg.gz) in vips 

Feel free to take my PR and add those missing pieces.

**Comment by felixbuenemann** [comment]
All done.
