### ISSUE TITLE
rotating 45 degrees, white background?

### ISSUE THREAD

**Issue by willsand** [jcupitt/libvips#475]
I am using the libvips python binding to rotate 45 degrees with affine() and the standard rotation matrix.
But the added pixels are in black. Is there a possibility to make them white?

I saw that there is a type VipsExtend which also references affine() , but i cannot seem to pass extend or background as an argument. (http://www.vips.ecs.soton.ac.uk/supported/7.40/doc/html/libvips/libvips-conversion.html#VipsExtend)
The images i am using are in .svs Aperio format.

It would be great if someone could help me.

kind regards,
Lorenz

**Comment by willsand** [comment]
as mentionend here: https://github.com/jcupitt/libvips/issues/188
I used a sample jpg as the svs also only have 3 bands and added an extra band. 
im = im.bandjoin(255)
im = im.affine([0.7071,-0.7071,0.7071,0.7071])
im = im.flatten(background = 1) // or i used the background argument in save_to_file

But the added pixels are still black.
What am i doing wrong? :-)

**Comment by jcupitt** [comment]
Hi, yes, I think I'd add an alpha, rotate and flatten. 

svs files have an alpha, though the alpha will almost always be 255, I think. It's there for historic reasons. 

I'll make you a sample program, hang on.

**Comment by jcupitt** [comment]
This works for me:

```python
#!/usr/bin/python

import sys

import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

im = Vips.Image.new_from_file(sys.argv[1])

im = im.extract_band(0, n = 3)
im = im.bandjoin(255)
im = im.similarity(angle = 45)
im = im.flatten(background = 255)

im.write_to_file(sys.argv[2])
```

If I run with:

```
 $ ./45degree.py ~/pics/openslide/CMU-1.svs[level=2] x.dz
```

and look at `x_files/12/0_0.jpeg` I see a while square, so I think I have a white background on the rotated svs.

**Comment by willsand** [comment]
That works! 
Thanks a lot for the quick answer and maintaining this great software!

**Comment by jcupitt** [comment]
Good! I'll close.

**Comment by willsand** [comment]
in the documents http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-resample.html#vips-similarity
it is stated that angle in similarity is anticlockwise, thats wrong though?

**Comment by jcupitt** [comment]
Ooop! Thanks! Fixed in master in the commit above.
