### ISSUE TITLE
TavisCI: MacOS X build broken

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#477]
The MacOS X build on TravisCI for the current master fails to detect most dependencies and fails during the PNG tests.

I'll try to investigate what's going on. Doing a `cat config.log` will probably give insights.

**Comment by jcupitt** [comment]
I had a quick look: git master fails on OS X because it can't find libpng, which triggers a slew of failures in the test suite.

It correctly installs libpng-1.6.28 with brew, and on linux at least libvips seems to work fine with libpng 1.6.28. Perhaps the .pc file is installed somewhere strange on OS X, I'll check that tonight.

**Comment by felixbuenemann** [comment]
On my system there's a `/usr/local/lib/pkgconfig/libpng.pc` and `/usr/local/lib/pkgconfig/libpng16.pc`. Have you tried looking at the config.log?

**Comment by jcupitt** [comment]
Yes, I have those two as well, but everything seems to work fine on my mac. Very odd. 

I added a `cat config.log` to `.travis.yml` (is that what you meant?) hopefully something will appear here:

https://travis-ci.org/jcupitt/libvips/jobs/193097479

Happy New Year, by the way!

**Comment by felixbuenemann** [comment]
Thanks, Happy New Year to you John!

Looks like you already figured out that it's related to `PKG_CONFIG_PATH`. I faintly remember needing to set the PKG_CONFIG_PATH for libffi for the ruby and the python vips8 bindings, but looks like that's no longer needed.

I think you can remove the extra debug output in the `before_script` and then this issue can be closed.

**Comment by jcupitt** [comment]
Yes, brew has shifted quite a bit under our feet, I think. One  of the issues was `brew resinstall` vs. `brew install`. It seems the `.pc` files are often only made during install. 

Anyway, I've cleaned it up a bit and OS X is no longer an allowed failure. Phew!

**Comment by jcupitt** [comment]
Also, thanks for pushing on this issue, it's good to have it done.
