### ISSUE TITLE
vips_tiffsave() in version 7.42 and 8.2

### ISSUE THREAD

**Issue by iwbh15** [jcupitt/libvips#479]
Could it be that there is a difference in the vips_tiffsave() function between version 7.42 and 8.2?

I use nip2 to create a 6 channel (8bit) image and save is as uncompressed, tiled, pyramid tiff.

In nip2 7.42 a get a 6 channel image with reduced resolution layers as expected. In an Exif Viewer all IDFx entries for the different resolution layers show identical information (except of course for the resolution specific informati

In nip2 8.2 the identical procedure creates a similar image but with two additional entries in the IDF0 section. The additional information is
Extra Samples:		Unknown(1 1 1)
Sample Format: 	Unsigned; Unsigned; Unsigned; Unsigned; 1; 1

Does this means that the last 2 channels are 1bit information instead of 8bit unsigned?

I plan to use the vips_tiffsave() directly from vips_dev.
Is there a change in the vips_tiffsave() function between version 7.42/7.43 and 8.2/8.3?

And ( as a side question), is it possible to display somehow the command string which is used when an image is save in nip2?

Regards,
Peter

**Comment by jcupitt** [comment]
Hi, the pixels should be the same, but the metadata handling has been improved. I see:

```
john@kiwi:~/pics$ vips bandjoin "k2.jpg k2.jpg" x.v
john@kiwi:~/pics$ vipsheader x.v
x.v: 1450x2048 uchar, 6 bands, srgb, jpegload
john@kiwi:~/pics$ vips tiffsave x.v x.tif
john@kiwi:~/pics$ tiffinfo x.tif 
TIFF Directory at offset 0x10fe008 (17817608)
  Image Width: 1450 Image Length: 2048
  Resolution: 28.3465, 28.3465 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Extra Samples: 3<assoc-alpha, assoc-alpha, assoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 6
  Rows/Strip: 128
  Planar Configuration: single image plane
  RichTIFFIPTC Data: <present>, 332 bytes
```

vips has the image tagged as "6 band srgb" (since it came from an rgb source), so it saves it as RGB with three extra alpha channels. 

Could you save your 6 band image in vips format and see what `vipsheader` says, then try `tiffsave` and `tiffinfo` and copy/paste that too?

**Comment by iwbh15** [comment]
Thanks, it seems to be ok.

From a 6 channel(bw 8bit) bandjoined in nip2 and saved as x.v I got
 
vipsheader x.v
x.v: 400x400 uchar, 6 bands, b-w

vips tiffsave x.v x.tif --tile
tiffinfo x.tif
TIFF Directory at offset 0xea608 (960008)
  Image Width: 400 Image Length: 400
  Resolution: 10, 10 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Extra Samples: 3<assoc-alpha, assoc-alpha, assoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 6
  Rows/Strip: 128
  Planar Configuration: single image plane

TIFF Directory at offset 0x180008 (1572872)
  Image Width: 400 Image Length: 400
  Tile Width: 128 Tile Length: 128
  Resolution: 10, 10 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Extra Samples: 3<assoc-alpha, assoc-alpha, assoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 6
  Planar Configuration: single image plane

**Comment by jcupitt** [comment]
OK, it looks sensible to me. Please close if you think this is done.
