### ISSUE TITLE
support ImageMagick 7+

### ISSUE THREAD

**Issue by sachinwalia2k8** [jcupitt/libvips#480]
In ImageMagick 7.0+ magick/api.h has been removed. Because of this building libvips 8.3.1 fails with following error:

magick2vips.c:101:24: fatal error: magick/api.h: No such file or directory

**Comment by jcupitt** [comment]
Thank you for the report! I'll have a look.

**Comment by jcupitt** [comment]
The changes for imagemagick7 are quite large:

http://www.imagemagick.org/script/porting.php

I think we'll need a new `magickload` operation in vips, and then pick either the magick6 or magick7 loaders at configure time. 

Let's use this issue to track progress. I'll change it into an enhancement.

**Comment by jcupitt** [comment]
The changes for imagemagick7 are quite large:

http://www.imagemagick.org/script/porting.php

I think we'll need a new `magickload` operation in vips, and then pick either the magick6 or magick7 loaders at configure time. 

Let's use this issue to track progress. I'll change it into an enhancement.

**Comment by jcupitt** [comment]
I've made a branch for magick7 support.

**Comment by sachinwalia2k8** [comment]
@jcupitt - If I've both ImageMagick 7.0.2 as well as GraphicsMagick 1.3.24 in the path then if I want to build libvips with GraphicsMagick instead will that fail too? I've noticed that to be the case and wondering if there is anything wrong with what I am doing.

**Comment by jcupitt** [comment]
It picks IM by default, you need to tell it to use GM. Try:

```
./configure --with-magickpackage=GraphicsMagick
```

And it should build against GM instead.

**Comment by jcupitt** [comment]
I've pushed some more code to the https://github.com/jcupitt/libvips/tree/add-magick7 branch and it seems to work, at least at a basic level.

It is much slower though. They have switched to using `double` for pixel values and it's added a lot of overhead. Before I saw:

```
$ time vips magickload IMG_1867.JPG x.v
real	0m0.207s
user	0m0.284s
```

But with IM7 it's:

```
$ time vips magickload IMG_1867.JPG x.v
real	0m0.562s
user	0m1.292s
```

CPU load is about 4x higher. Perhaps there's some tuning I can do.

**Comment by sachinwalia2k8** [comment]
@jcupitt - thanks for the info. IM 7+ seems to be a bad news in that case. Is there a table I can refer to that can tell me the performance of VIPS with shared open source library such as GraphicsMagick, ImageMagick etc. Moreover are there any other libraries that VIPS can make use of?

**Comment by jcupitt** [comment]
vips only uses imagemagick / graphicsmagick to load less-used formats like TGA or DICOM. If you don't need to load those images, you don't need them. In fact, for most people it's better not to use them. 

What are you planning to use vips for?

**Comment by sachinwalia2k8** [comment]
@jcupitt primarily for resizing standard formats - jpg, png, webp etc. Can vips also help in converting from different formats. for example from tiff to jpg?

**Comment by jcupitt** [comment]
Oh sure. Just:

```
vips copy fred.tif jim.jpg
```

It doesn't sound like you need ImageMagick. Try:

```
$ vips -l foreign
```

To see all the supported file load / save operations.

**Comment by sachinwalia2k8** [comment]
Thanks. how do I build vips without graphicsmagick or imagemagick?

**Comment by jcupitt** [comment]
Use `--without-magick` to `configure`. Try `./configure --help`, it lists all the options.

**Comment by jcupitt** [comment]
On benchmarks, I guess you've seen:

http://www.vips.ecs.soton.ac.uk/index.php?title=Speed_and_Memory_Use

libvips has it's own image processing "engine", so the libraries you use it with shouldn't affect the speed. Things like libjpeg vs. libjpeg-turbo will make a difference, of course.

**Comment by sachinwalia2k8** [comment]
Thanks @jcupitt. My use case would involve launching vips on a commandline from Java as a separate process instance every time a request to resize/conversion comes from the web interface. Since there are no native Java bindings so the web application to fork a new process for every such request. From the benchmark it seems commandline would be a better option. Can you please share any info that you may have about limitations if any for launching multiple instances of vips in a highly concurrent environment. Thanks in advance.

**Comment by jcupitt** [comment]
Yes, I'd just shell out to `vipsthumbnail`. It can do most resizing and format conversion tasks, and it's very quick. There's a blog post about it here:

http://libvips.blogspot.co.uk/2013/11/tips-and-tricks-for-vipsthumbnail.html

You can set the environment variable `VIPS_CONCURRENCY` to control how large a threadpool vips should make. Set it to 1 to keep resource use down.

Yes, in a web environment I'd certainly turn IM/GM off. There are lots of other things you can turn off too --- you probably don't need support for FITS images, for example.

I would have a separate thing for resize requests. Have a DB table for resize jobs, and a separate, low-privilege process running as a different user which takes jobs from the table and runs them one at a time. Perhaps that's a feature for a later version.

**Comment by sachinwalia2k8** [comment]
@jcupitt thanks those are really helpful tips.

**Comment by jcupitt** [comment]
Status update: it's almost there, it's currently stuck on dicom read.

http://www.imagemagick.org/discourse-server/viewtopic.php?f=2&t=30191

**Comment by felixbuenemann** [comment]
@jcupitt Have you done any comparisons when both im6 and im7 have been compiled with the same quantum depth?

By default im6 uses a quantum-depth of 16 bits, although if you don't work with 16 bit images using a quantum depth of 8 bit should be fine. If im7 uses doubles by default it's probably using a quantum depth of 32 bits.

**Comment by jcupitt** [comment]
I've benchmarked IM6 and IM7 both with the default quantum depth. On my two-core laptop, the vips-bench benchmark time went from 1.3s to 2.7s, so im6 is a bit more than double the speed. vips is 0.4s. Yes, `sizeof(Quantum)` is 4 in im7 default, which sounds like float rather than double. 

IM7 also adds quite a it of overhead to pixel manipulation. They have a read mask, so every pixel can be turned on or off, they have channel traits, so channels can be set to update / blend / don't-touch, and they have channel tags, so they don't have the red channel fixed at index 0, instead operations must search and find the channel that's got the red tag set on it. They've moved the index channel into the regular channel set too, so if you load a GIF, for example, you actually see five channels: RGB, alpha and index. 

The im7 magickload in vips only looks at the tags to drop the index channel. For speed it assumes that RGBA are in the usual order and that the read mask and traits are set all on. I hope this is correct. 

I tried loading a 10k x 10k pixel RGB 8-bit TIFF. With IM7 I see:

```
$ time vips magickload wtc.tif x.v
real	0m2.535s
user	0m1.532s
sys	0m0.600s
```

With IM6:

```
$ time vips magickload wtc.tif x.v
real	0m2.020s
user	0m0.856s
sys	0m0.552s
```

And with vips:

```
$ time vips copy wtc.tif x.v
real	0m1.603s
user	0m0.160s
sys	0m0.472s
```

The drop in user time is probably the best indicator of the change in complexity, it's spending a lot of time stuck in IO.

**Comment by jcupitt** [comment]
OK, all done and merged to master.

**Comment by sergeevabc** [comment]
I have downloaded [vips-dev-w64-all-8.11.0-rc1.zip][1] for Windows 7 and vips.exe works as expected, but how do I use functions of included libMagickCore-6.Q16-7.dll (I see nothing special in `vips -l | rg magick` output) and why there is no IM7 specific dll?

[1]: https://github.com/libvips/build-win64-mxe/releases

**Comment by jcupitt** [comment]
Hi @sergeevabc,

libvips uses *magick to load and save file formats which it doesn't support itself. For example, BMP load and save will be routed via *magick:

```
vips copy x.bmp y.bmp
```

You can build libvips against IM6, IM7 and GM. libvips does not try to expose any other *magick functionality.
