### ISSUE TITLE
Gray Lama

### ISSUE THREAD

**Issue by escholtz** [jcupitt/libvips#482]
Was using the Dalai Lama test image (from http://www.4p8.com/eric.brasseur/gamma.html) and found an unexpected result when the output size is the same as the input size.

This is the command I'm running using libvips 8.3.1:
```
vipsthumbnail gamma_dalai_lama_gray.jpg --linear --size=258x222 -o lama_optimized.jpg[Q=100]
```

This is the input:
![gamma_dalai_lama_gray](https://cloud.githubusercontent.com/assets/897417/16706026/c617e3e2-4551-11e6-8ce2-46e43d380c52.jpg)

And this is the output:
![lama_optimized](https://cloud.githubusercontent.com/assets/897417/16706027/cde7e734-4551-11e6-8423-1a8431d99385.jpg)

Is this expected? I know vipsthumbnail is intended for thumbnails (hence the name) but was hoping it would also work for passthrough (same size output but exif striping and jpeg optimization).

Otherwise the library is working great. Thanks for creating it!

**Comment by jcupitt** [comment]
Hi @escholtz, you're just seeing the effects of JPG compression, I think. Try:

```
$ vipsthumbnail gamma_dalai_lama_gray.jpg --linear --size=258x222 -o lama_optimized.png
```

ie. output to a PNG file, and it'll look OK. 

You can also turn off chroma subsample, which will fix it too:

```
$ vipsthumbnail gamma_dalai_lama_gray.jpg --linear --size=258x222 -o lama_optimized.jpg[Q=100,no-subsample]
```

If you use the `--vips-info` flag to `vipsthumbnail` it shows all the processing steps, handy for tracking down problems.

**Comment by jcupitt** [comment]
Oh, and the reason this only shows up when output size == input size is that the image has the picture info only in the chroma, and uses pairs of contrasting lines. JPEG uses a 2x2 chroma subsample, so in this case each 2x2 block exactly cancels out. 

I'm not sure `--linear` is worth the pain, myself. It can be more than 10x slower (since it means you can't use shrink-on-load) and the differences are minimal for almost all images. 

```
$ time vipsthumbnail wtc.jpg 
memory: high-water mark 4.73 MB
real	0m0.298s
user	0m0.292s
sys	0m0.004s
$ time vipsthumbnail --linear wtc.jpg 
memory: high-water mark 32.61 MB
real	0m4.988s
user	0m4.976s
sys	0m0.008s
```

**Comment by escholtz** [comment]
Thanks for the quick and detailed response. `--vips-info` will be very useful for exploring and learning more.

Do you have specific guidance on when to turn off chroma subsample? (I see in this post it mentions at high Q values: http://libvips.blogspot.com/2013/11/tips-and-tricks-for-vipsthumbnail.html)

**Comment by jcupitt** [comment]
I think IM turns off chroma-subsample for Q>90. I though vips did as well but it obviously isn't. I'll have a look.

**Comment by jcupitt** [comment]
Looks like it's something I intended to add but never got around to. I'll add a note to the TODO on this. Thanks for pointing the problem out!

**Comment by felixbuenemann** [comment]
Btw. I've got a todo to implement proper subsampling control for jpeg via hsample, vsample options that take an array of integers for each plane. In my experience 4:4:4 subsampling works well for small to medium sized images, where high detail clarity is needed. But for high-res retina resolution photographic images where compression is a big issue, progressive mode with 4:0:0 (1/4th of chroma in h/v direction works really well).
