### ISSUE TITLE
Optional Argument "interpolate" Possibilities Undocumented for vips_affine

### ISSUE THREAD

**Issue by imfranklin** [jcupitt/libvips#483]
The links to "VipsInterpolate" throughout the docs - http://www.vips.ecs.soton.ac.uk/usr/share/gtk-doc/html/libvips/VipsInterpolate.html - are dead. What are the possible interpolate values?

**Comment by jcupitt** [comment]
Oh dear, I'll try to fix the docs, thanks for letting me know.

You can see the interpolators your vips has with:

```
$ vips -l interpolate
  VipsInterpolate (interpolate), VIPS interpolators
    VipsInterpolateNearest (nearest), nearest-neighbour interpolation
    VipsInterpolateBilinear (bilinear), bilinear interpolation
    VipsInterpolateBicubic (bicubic), bicubic interpolation (Catmull-Rom)
    VipsInterpolateLbb (lbb), reduced halo bicubic
    VipsInterpolateNohalo (nohalo), edge sharpening resampler with halo reduction
    VipsInterpolateVsqbs (vsqbs), B-Splines with antialiasing smoothing
```

The you give the nickname to [`vips_interpolate_new()`](http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-VipsInterpolate.html#vips-interpolate-new).

**Comment by jcupitt** [comment]
I think I found the problem: the doc tool had changed the rules it used to recognise classes.

I've regenerated the docs, it should be all there now.

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-resample.html#vips-affine

**Comment by imfranklin** [comment]
Thanks for the quick doc fix and interpolators list!
