### ISSUE TITLE
Help understanding bandjoin

### ISSUE THREAD

**Issue by mhirsch** [jcupitt/libvips#484]
I hope someone can help me understand the bandjoin operation in the vips c++ API, since it seems to behave in a way that is not intuitive, and I can't find an explanation in the docs. I've written the following test programs in c++. I have two basic questions. First, `bandjoin()` accepts a `std::vector<VImage>` or a `VImage`. When the `VImage` is passed it seems to operate properly, adding the passed image as a channel to the existing image. However, when a vector is passed, it seems to entirely replace the image with the images in the vector.

```c++
#include <vips/vips8>
#include <iostream>

// g++ t.cc -o t `pkg-config vips-cpp --libs --cflags`

using vips::VImage;

int main(int argc, char **argv ) {

  if( VIPS_INIT( "test" ) )
    vips_error_exit(NULL);

  VImage image;

  image = VImage::new_from_file("test/fixtures/50020484-00001.png");
  
  std::cout << "load: " << image.bands() << std::endl;

  std::vector<VImage> joinImages;

  joinImages.push_back(VImage::new_from_file("test/fixtures/testJoinChannel.png"));
  joinImages.push_back(VImage::new_from_file("test/fixtures/stripesH.png"));

  std::cout << "join image 1: " << joinImages[0].bands() << std::endl;
  std::cout << "join image 2: " << joinImages[1].bands() << std::endl;

  image = image.bandjoin(joinImages);

  std::cout << "image has " << image.bands() << " bands.\n";

  image = image.colourspace(VIPS_INTERPRETATION_sRGB);

  std::cout << "after colourspace, image has " << image.bands() << " bands.\n";

  image = image.bandjoin(joinImages);

  std::cout << "image has " << image.bands() << " bands.\n";

  vips_shutdown();

  return 0;
}
```

Program output:
```
$ ./t
load: 1
join image 1: 1
join image 2: 1
image has 2 bands.
after colourspace, image has 4 bands.
image has 2 bands.
```

Also, after adding additional channels to my single channel image, I would like vips to interpret it as an sRGB image. However, running `colourspace(VIPS_INTERPRETATION_sRGB)` yields a 5 channel image -- two additional channels are added to the image. What's the right way to merge three single channel images into one three channel image?

```c++
#include <vips/vips8>
#include <iostream>

// g++ t.cc -o t `pkg-config vips-cpp --libs --cflags`

using vips::VImage;

int main(int argc, char **argv ) {

  if( VIPS_INIT( "test" ) )
    vips_error_exit(NULL);

  VImage image;

  image = VImage::new_from_file("test/fixtures/50020484-00001.png");
  
  std::cout << "load: " << image.bands() << std::endl;

  std::vector<VImage> joinImages;

  joinImages.push_back(VImage::new_from_file("test/fixtures/testJoinChannel.png"));
  joinImages.push_back(VImage::new_from_file("test/fixtures/stripesH.png"));

  std::cout << "join image 1: " << joinImages[0].bands() << std::endl;
  std::cout << "join image 2: " << joinImages[1].bands() << std::endl;

  image = image.bandjoin(joinImages[0]);
  image = image.bandjoin(joinImages[1]);

  std::cout << "image has " << image.bands() << " bands.\n";

  image = image.colourspace(VIPS_INTERPRETATION_sRGB);

  std::cout << "after colourspace, image has " << image.bands() << " bands.\n";

  vips_shutdown();

  return 0;
}
```

Program output:
``` 
$ ./t
load: 1
join image 1: 1
join image 2: 1
image has 3 bands.
after colourspace, image has 5 bands.
```

**Comment by mhirsch** [comment]
Ok, I understand that `image.colourspace()` is attempting to convert the image from the stored interpretation, ignoring the fact that it has extra channels. Is it safe to do something like this to the image after the bands have been added?

```c++
image.get_image()->Type = VIPS_INTERPRETATION_sRGB;
```

I would still like to know what's going on with `std::vector<VImage>` arguments.

**Comment by jcupitt** [comment]
Hi @mhirsch, there's no `VImage` method for `image.bandjoin(std::vector<Vimage> images)`, it looks like C++ is deciding to call the static class method in this case and discarding `this`. I'll add something, thanks for pointing this out.

It's not really safe to write to `Type`, you don't know if the `VipsImage` is shared or not, you could be messing up someone else's image. The safe way to set fields is to use `copy`, something like:

```C++
        image = image.copy(VImage::option()->set( "interpretation", VIPS_INTERPRETATION_sRGB));
```

If you load a mono image, it gets tagged as `B_W`. Join three of them together and you'll still have a `B_W` image, vips will regard the extra bands as alphas. If you now convert to RGB, it'll expand the first band to three, then reattach the final two, producing a five band image.

**Comment by jcupitt** [comment]
Oh I remember now, I looked at this before. C++ doesn't let you have a static class member with the same signature as a method. `VImage` has a static class member `bandjoin` declared like this:

```C++
static VImage bandjoin( std::vector<VImage> in , VOption *options = 0 );
```

This joins a vector of images up, it's an automatically-generated wrapper for `vips_bandjoin()`, you use it something like:

```C++
VImage rgb = VImage::bandjoin(std::vector<VImage> vec({r, g, b});
```

Instances of `VImage` have a `bandjoin` method declared like this:

```C++
VImage bandjoin( VImage other, VOption *options );
```

Which you use as:

```C++
rgb = r.bandjoin(g).bandjoin(b);
```

And there's no ambiguity, but if you declare a vector version of the instance member:

```C++
VImage bandjoin( std::vector<VImage> other, VOption *options );
```

Now that clashes with the class member and you'll get an error from the compiler. 

I don't know what the best solution is. Python has a similar problem (you can't have an instance and a class method with the same name), and there we decided (eventually) to get rid of the class member and just have the instance. Perhaps C++ should do the same.

**Comment by jcupitt** [comment]
Here's a sample program to join a set of images to make an RGB:

```C++
// g++ -g -Wall try238.cpp `pkg-config vips-cpp --libs --cflags`

#include <vips/vips8>
#include <iostream>

using vips::VImage;

int
main(int argc, char **argv) 
{
  if (VIPS_INIT("test"))
    vips_error_exit(NULL);

  std::vector<VImage> images;

  for (int i = 2; i < argc; i++) {
    VImage x = VImage::new_from_file(argv[i]);
    std::cout << "join image: " << argv[i] << ": " << x.bands() << std::endl;
    images.push_back(x);
  }     

  VImage image = VImage::bandjoin(images);
  image = image.copy(VImage::option()-> 
    set("interpretation", VIPS_INTERPRETATION_sRGB));

  image.write_to_file(argv[1]);

  return(0);
}   
```

**Comment by mhirsch** [comment]
Thank you very much for your comments! This is exactly what I was looking for.
