### ISSUE TITLE
Possible missing libxml2 depends_on clause in vips.rb homebrew recipe

### ISSUE THREAD

**Issue by lovell** [jcupitt/libvips#485]
Hi John,

A Travis-based OS X 10.9 build is failing to install libvips (from source) via the simple homebrew command:
```sh
brew update
brew install homebrew/science/vips --with-webp --without-fftw --without-poppler
```
The salient error is:
```
configure: error: Package requirements (glib-2.0 >= 2.6 gmodule-2.0 libxml-2.0 gobject-2.0) were not met:
No package 'libxml-2.0' found
```
The Travis config file is at https://github.com/lovell/package-libvips-darwin/blob/master/.travis.yml

The build log is at https://travis-ci.org/lovell/package-libvips-darwin/builds/145192835

It looks like this has occurred previously at https://github.com/Homebrew/homebrew-science/issues/1024 but there's no confirmation the problem went away.

Do you think we might need to add something like a `depends_on: "libxml2"` clause to [vips.rb](https://github.com/Homebrew/homebrew-science/blob/master/vips.rb) (or perhaps one of vips' dependencies is missing a `depends_on`)?

**Comment by jcupitt** [comment]
Oh argh, stupid brew, I wish they had a set policy on these extra libs and stuck to it. Or maybe it's apple's fault? Why don't they ship the pkg-config files for the libraries they distribute. 

I should be able to have a look later.

**Comment by jcupitt** [comment]
So I think the situation is:

* In OS X 10.11.5 (el cap), Apple provide /usr/lib/libxml2.2.dylib, but no header files and no .pc file
* Apple do have headers in the SDK, look in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.‌platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2` ... for 10.11 this is version 2.9.2
* Apple however carefully remove all the .pc files, goodness knows why
* brew include a .pc file which will trick vips into building against the system libxml2 ... when brew builds vips it'll prepend it's special `libxml-2.0.pc` directory to `PKG_CONFIG_PATH`
* If you include libxml2 as a `depends_on`, vips will build against brew's more recent libxml2 and not the system one

I've probably messed up some details, argh :( 

So I think I would guess that this is a homebrew bug. Somehow the fake .pc file that lets formula find the system libxml2 is not being passed to vips.

**Comment by lovell** [comment]
Thanks John, looking at recent `brew` commits it appears https://github.com/Homebrew/brew/pull/507 broke it and https://github.com/Homebrew/brew/pull/530 fixed it, so all good again when I tried this morning.
