### ISSUE TITLE
Replace libxml2 with expat

### ISSUE THREAD

**Issue by nwmcsween** [jcupitt/libvips#486]
Libxml2 is [https://dev.yorhel.nl/yxml](slow and bloated) and full of UB and CVE issues and actively will not fix the UB issues. Consider [yxml](https://dev.yorhel.nl/yxml)

**Comment by jcupitt** [comment]
Good idea. We picked libxml2 a very, very long time ago, and things have moved on.

Another possibility would be expat: glib pulls this in, so we'd get it for free, and it's faster and better-supported than libxml2.

**Comment by nwmcsween** [comment]
What does vips use glib for? glib is also in my opinion a mess.

**Comment by jcupitt** [comment]
It uses a lot of glib. Most of the main objects are subclasses of gobject, it uses the gobject signal/slot system, the bindings are (mostly) done with gobject-introspection, it uses a lot of the glib data structures, the documentation is generated with gtk-doc, and it uses the glib Windows portability layer.

Way back libvips had its own portability layer, data structures and introspection system, but I got fed up with maintaining it, and glib seemed a reasonable fit. Plus I knew it fairly well from having done some gtk.

**Comment by nwmcsween** [comment]
I understand the need for a portability layer, maybe [http://midipix.org/](midipix) could be used instead of glib, then direct posix functionality could be used.

**Comment by jcupitt** [comment]
midipix looks very nice, but we'd still need glib for gobject, so I don't think there would be much saving.

**Comment by lovell** [comment]
If `expat` is an option here then +1 for that as it has proved itself to be both fast and stable in my (many years) experience of using it.

**Comment by jcupitt** [comment]
Let's try an experimental expat branch. I'll have a quick hack.

**Comment by jcupitt** [comment]
Here's a libxml-free branch:

https://github.com/jcupitt/libvips/tree/try-expat

Still needs a bit of polishing, but it does seem to work.

**Comment by jcupitt** [comment]
OK, all fixed up and merged to master. Thanks for suggesting this, expat is pretty nice. 

If you ldd on a vips executable you'll still see libxml2 in there, but that's because various things that libvips uses use libxml2.
