### ISSUE TITLE
Unable to align text in vips_text

### ISSUE THREAD

**Issue by gargsms** [jcupitt/libvips#493]
This is my current C code: 
```
vips_text( &out, as,
      "width", 400,
      "spacing", 2,
      "alignment", 1,
      "font", "Century Gothic 32", NULL );
```
`out` is a VipsImage, and `as` is a string.

This function works with all other options described at http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-create.html#vips-text except `alignment`

I haven't been able to figure out what is the required value for the option. In the definition and even in the source it expects an integer (0, 1, 2) but somehow it is not working with any input.

**Comment by jcupitt** [comment]
I added some type annotations for the optional arguments https://github.com/jcupitt/libvips/commit/54aea13a8c350c01affa2cd74f56d5fcfead1611 thanks for pointing this out.

`alignment` is a `VipsAlign`:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#VipsAlign

So use `VIPS_ALIGN_CENTRE` or whatever.

It will only affect alignment for multi-line text, so you need to set `width` small enough that your text will wrap. Try this at the command-line:

```
vips text x.png "Hello world!" --dpi 300 --align centre
```

You'll see a single line of text. But set the width down:

```
vips text x.png "Hello world!" --dpi 300 --align centre --width 100
```

And you should see two lines of text centred above each other.

**Comment by gargsms** [comment]
Well, I should have tried this earlier.
The real issue here is not the enum reference, but the option name. It is not `alignment` as is listed in the docs, but is `align`. The enum is ultimately resolved to an `int` anyway. Using either of `0, 1, 2` or `VIPS_ALIGN_`XX works with the option as `align`

**Comment by gargsms** [comment]
And the API is inconsistent in C and C++ with them using `align` and `alignment` respectively.

**Comment by jcupitt** [comment]
Oh argh, thank you very much for pointing this out. Sorry about that. I've fixed the docs. 

It's `align` everywhere I think. The docs were wrong, but the API was consistent. 

You can also use a string in C++, if you want. Something like:

```
VImage::option()->set( "align", "centre" )
```

**Comment by zhaohuxing** [comment]
@jcupitt Please, Where is VipsAlign docs?

**Comment by jcupitt** [comment]
@zhaohuxing please open new discussions for new questions.

The `text` docs are here:

https://www.libvips.org/API/current/libvips-create.html#vips-text

And that links to VipsAlign here:

https://www.libvips.org/API/current/libvips-conversion.html#VipsAlign
