### ISSUE TITLE
Using vips_ifthenelse for multiple channel images

### ISSUE THREAD

**Issue by gargsms** [jcupitt/libvips#495]
My use case involves writing text over an image where the text can be of any color.
So I generate text using `vips_text()` and then change the interpolation to RGB using `vips_copy()`. Then I can apply the color using `vips_linear()`
Let's assume I want to use pure blue color. I use `vips_linear` co-efficients `a` as `{0, 0, 255}` and keep `b` to `{0, 0, 0}`
The only issue with this approach is overlaying the text using `vips_ifthenelse()` will leave the other channels of the image intact, which is not my requirement.
I tried using `a` as `{ 1/(255.0), 1/(255.0), 255 }` which works, but the text becomes horrible and does not remain smooth at all. Setting `blend` as `FALSE` in `ifthenelse` does not help either.
Of course, this issue only exists for pure R, G, or B colors and not any intermediary.

**Comment by jcupitt** [comment]
Hi, use a mono text image, and colour images for then and else parts. In Python:

```python
im = Vips.Image.new_from_file("somefile.jpg")
txt = Vips.Image.text("hello world!", width = 500, dpi = 300)
im = txt.ifthenelse([0, 0, 255], im)
im.write_to_file("someotherfile.jpg")
```

**Comment by jcupitt** [comment]
In C, you need to make the blue image yourself. Make a 1x1 pixel black image, add the blue to it, cast down to uchar, then expand up to whatever size you need with `vips_embed()`.

**Comment by gargsms** [comment]
This is the code I have been using to extend [lovell/sharp](https://github.com/lovell/sharp/issues/512)
```c++
VImage Text(VImage image, std::string text, std::string align, int *colors,
    int *pos, int const width, std::string font,
    int const spacing) {

    std::vector<double> color(colors, colors + 3);
    std::vector<double> zero(3);

    VImage pixel = image.embed(0, 0, 1, 1);
    pixel = pixel.linear(zero, color);
    pixel = pixel.replicate(image.width(), image.height());

    VImage overlay = VImage::new_memory();
    overlay = overlay.text(&text[0u],
      VImage::option()
        ->set("font", &font[0u])
        ->set("width", width)
        ->set("align", &align[0u])
        ->set("spacing", spacing)
        ->set("dpi", 300));

    overlay = overlay.embed(pos[0], pos[1], image.width(), image.height());

    image = overlay.ifthenelse(pixel, image);

    return image;
  }
```
The only issue I have here is the text being quite sharp, and at a very low resolution. Is there a way to increase the resolution of the text(or the `overlay` and `pixel`, for that matter)?

Sorry for continuing in the same thread. Ideally it should have been an issue in itself. But it is the next step for this issue.

**Comment by jcupitt** [comment]
Hi @gargsms, I think you should turn on blending, you're missing the anti-aliasing. 

`C.ifthenelse(T, E)` picks pixels from T if C is non-zero, and from E otherwise. If you turn on blending, it'll scale the value in C to 0 - 1 and use that to blend smoothly between T and E.

You can make the code that builds `pixel`, your constant image, a bit faster. Something like (untested):

```C++
VImage pixel = (VImage::black(1, 1) + color).cast(image.format());
pixel = pixel.embed( 0, 0, image.width(), image.height(),
                VImage::option()->set( "extend", VIPS_EXTEND_COPY ) );
```

The two improvements are:

* casting to the target format before enlarging will probably make the constant image quite a bit smaller: the output of the `+` will be a float and you'll often just need `uchar`
* using `.embed()` to enlarge the image is quicker than replicate

**Comment by jcupitt** [comment]
There's actually a convenience function for making constant images in C++:

```C++
VImage
VImage::new_from_image( std::vector<double> pixel )
```

Something like:

```C++
pixel = image.new_from_image(color);
```

Makes a new image that matches `image` in every way, except that all pixels have the value `color`.

**Comment by gargsms** [comment]
Thanks @jcupitt. Anti-aliasing, or `blend` seems to do the trick. The text is quite smooth now.
Earlier I was trying for a single channel pixel (the issue relates to that) and hence the channels of the base image were also added to the text, making it look of different color based on the background. Zero-ing out the other channels makes it disappear with advantage of blend quite prominent.

About using embed as replicate, I didn't quite realize it was possible (didn't read the docs enough.)
Also, the other function `VImage::new_from_image` is very handy. I guess it is not documented anywhere.

Closing this now.
Thanks a lot.
