### ISSUE TITLE
Question: simultaneously adjust roll, pitch, yaw and shift with vips operations, how to?

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#496]
I am currently working on an interface to the align_image_stack image alignment tool. This interface should read the image alignment parameters returned by align_image_stack and apply them on-the-fly using VIPS operations.

align_image_stack gives the relative alignment between two images in terms of roll, pitch, yaw and x,y shifts (so 5 parameters in total).

Is there a simple way to build a distortion matrix in VIPS that applies all 5 corrections simultaneously? If not, a chain of two or three operations would also be OK...

Maybe vips_affine() is the way to go? But I cannot figure out myself how I should translate the roll, pitch, yaw and shift parameters into the a,b,c,d values for the affine transform...

Thanks for the help!

**Comment by jcupitt** [comment]
Hi Andrea, do you need a perspective transform in there? Affine can't do that, unfortunately .

**Comment by aferrero2707** [comment]
Hummm... yes, I think that adjusting pitch and yaw is basically equivalent to a perspective transform.

I found an interesting thread that shows a matlab example where the 3D roll/pitch/yaw transform is projected onto the image plane and converted into a 2D affine transform, if I understand correctly: http://stackoverflow.com/questions/20445147/transform-image-using-roll-pitch-yaw-angles-image-rectification

I think the OP confuses "yaw" and "roll" in his example, because "roll" and not "yaw" is what corresponds to "image rotation". Parts from this detail, could this be useful?

**Comment by jcupitt** [comment]
An affine transform just can't do perspective. It's:

```
x' = a x + b y + e
y' = c x + d y + f
```

ie. a linear recombination of x and y. All parallel lines in the input will remain parallel in the output, so no perspective.

You need to add another term for a perspective transform:

```
x' = a x y + b x + c y + d
```

etc. for y.

**Comment by aferrero2707** [comment]
In this case, I think I will start by discarding the yaw and pitch parameters. The goal is mostly to align handheld bracketed shots that will be composed into an HDR image, therefore the mis-alignment is mostly due to rotation and translation of the camera. I expect the effect of tilting to be of second order.

Thanks anyhow for your quick answers!

**Comment by jcupitt** [comment]
Of course you should probably consider lens distortion too, unfortunately. Pincushioning and barrelling due to zoom lenses will stop a simple perspective warp from working very well. I used to use a quadratic to model lens distortion, ie.:

```
x' = a x ^ 2 + b y ^ 2 + c x y + d x + e y + f
```

but honestly it doesn't work very well. You really need something a bit fancier.

**Comment by aferrero2707** [comment]
I will most likely use images that are already corrected from distortion using lensfun or some other lens correction library (like Adobe LCP profiles). Otherwise I agree that the matching by perspecive wrap would not be accurate.
