### ISSUE TITLE
vipsthumbnail.exe and unicode paths

### ISSUE THREAD

**Issue by sleman** [jcupitt/libvips#501]
Running vipsthumbnail on a unicode path fails.

`vips__file_open_write: unable to open file "C:\Users\P+ómela 01-07-2015\AppData\Roaming\test\IMG_0002.JPG" for writing`

`windows error: The system cannot find the file specified.`

**Comment by jcupitt** [comment]
Sorry, this is a known problem: https://github.com/jcupitt/libvips/issues/294

libvips assumes utf-8 everywhere, but Windows has a special filename encoding. So you need to insert calls to `g_filename_to_utf8 ()` etc. at the right points as filenames are turned to strings and back.  

https://developer.gnome.org/glib/stable/glib-Character-Set-Conversion.html

Unfortunately, I don't have easy access to a Windows machine to test this :(

**Comment by jcupitt** [comment]
Do you mind if I close this? It would be good to keep #294 as the issue for this bug.
