### ISSUE TITLE
Problem to convert gif with transparent background to png

### ISSUE THREAD

**Issue by diegocsandrim** [jcupitt/libvips#502]
Hi!
I was trying to convert a gif with transparent background to png, and expecting it to retained the transparency, but it was removed.

Source Image (Gif with transparence)
![image](https://cloud.githubusercontent.com/assets/4148815/17782284/2406693a-6549-11e6-9b86-77c554476fea.gif)
**Reproduce**: use the command in a Windoes machine (I guess this command use the giflib):
`./vips.exe copy image.gif copy-image.png`

**Expected result**: a PNG image with transparency.

**Actual result**: a PNG without transparency, the transparence was converted into the color that was defined as tranparent in that GIF image .
![copy-image](https://cloud.githubusercontent.com/assets/4148815/17782332/5d16e88a-6549-11e6-81ae-58f351b34b3d.png)

**Additional Info:**
I also tryed with the command (I guess this use the ImageMagick):
Using the command
`./vips.exe magickload image.gif magick-image.png`
The transparence was retained (as expected)
![magick-image](https://cloud.githubusercontent.com/assets/4148815/17782336/601dd52a-6549-11e6-99d2-21fe71ff32e5.png)

I would appreciate that you confirm some things:
- Does the command `copy` use giflib?
- Does the command `magickload` use the ImageMagick?
- Is there a way to tell `copy` command to retain the transpacency?
- Is that a bug?

**Comment by jcupitt** [comment]
Hi @diegocsandrim, right on all counts, and it does look like a bug. I'll investigate. Thanks for reporting this!

**Comment by jcupitt** [comment]
I think I've found it, your `homer.gif` has some extra bits set in the graphics extension block, and this was confusing the test for transparency.

If you build from the head of the 8.3 branch, or from git master, you should get the fix.

**Comment by diegocsandrim** [comment]
Thank you very much!

**Comment by jcupitt** [comment]
I'll close, I think we're done. Thanks again for the report!

**Comment by diegocsandrim** [comment]
Thank you @jcupitt! Are you planning to release this 8.3.4, or another version with this fix? I have tried to build this on my own, but i couldn't.
