### ISSUE TITLE
Enhanced geometry strings for vipsthumbnail

### ISSUE THREAD

**Issue by tomasc** [jcupitt/libvips#503]
It would be very nice to have some of the image magick's geometry behaviour implemented in the `vipsthumbnail` – for example the ability to specify width or height only (`NNx` and `xNN`) and no resize when source is larger or smaller (`NNxNN>` and `NNxNN<`) – see http://www.imagemagick.org/script/command-line-processing.php#geometry

Would you be open for adding these? I wrote the necessary calculations here in Ruby https://github.com/tomasc/dragonfly_libvips/blob/master/lib/dragonfly_libvips/dimensions.rb and would be available to help in getting them included in `vipsthumbnail` as these seem to be frequently used (or at least I do use these often) when generating image thumbnails.

**Comment by jcupitt** [comment]
Hi again, here's a branch with this added:

https://github.com/jcupitt/libvips/tree/add-thumbnail-geometry

You can use sizes like `100x200<`, or `x200>`, it seems to match `convert` in behaviour for me.

One difference is if you skip the `x`. It uses plain `200` to mean "bounding box of 200 x 200", whereas `convert` uses it to mean "width of 200". I don't think this will be easy to change without breaking a lot of existing `vipsthumbnail` scripts, unfortunately :(

**Comment by tomasc** [comment]
Hi John, thanks a million for implementing this!

I do think it is fine not to mirror the convert syntax 100%. I would even consider making the `x` mandatory so that it is clear `vipsthumbnail` is enforcing certain syntax of the dimensions string?

**Comment by jcupitt** [comment]
I think requiring the x would break to many exisiting `vipsthumbnail` uses, unfortunately. 

OK, merged to master! Thank you for proposing this nice improvement.

**Comment by tomasc** [comment]
Thanks @jcupitt I look forward to 8.5!
