### ISSUE TITLE
slight offset on resize()

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#504]
Compared to imagemagick, vipsthumbnail has a slight offset, perhaps 0.5 pixel. This can cause visible "jumping" when you switch from a low-res to a high-res image. 

See https://github.com/jcupitt/libvips/issues/404#issuecomment-241717882

**Comment by jcupitt** [comment]
I did some digging and the problem seems to be that IM uses centre convention and vips uses corner. If I add 0.5 to x and y in the vips reducer, the offset almost vanishes.

Probably the best solution is to add a "use centre" flag to reduce. I don't want to switch vips over to corner wholesale, since corner has a number of disadvantages and changing would involve touching a huge amount of code.

**Comment by jcupitt** [comment]
The add-centre-sampling branch seems to have working code for this:

https://github.com/jcupitt/libvips/compare/add-centre-sampling

I now see:

http://www.rollthepotato.net/~john/kevill9/

vips is very close to IM now.

**Comment by jcupitt** [comment]
@lovell this might be useful for you, perhaps? tldr: turn on the `centre` option to `vips_resize()` to remove the 0.5 pixel offset. What do you think?

**Comment by lovell** [comment]
Great, thanks @jcupitt, https://github.com/lovell/sharp/issues/568 created to track this.

**Comment by jcupitt** [comment]
OK, merged to master.

**Comment by jardakotesovec** [comment]
Seems that with centre option it produces different results, but still somewhat shifted - I was investigating why some of our small thumbnails looks shifted. Here is example with centered artwork. And results using centre option on, off and image magick. Result from vips are both bit shifted, just differently, only image magick has precisely centered result. Unfortunately with some artworks and small thumbnails it makes quite difference and result looks shifted (between 0.5-1px).

Any idea/suggestion how this could be improved?

![vipscentrefalse](https://user-images.githubusercontent.com/1590681/27187022-5b1f8cc4-51ea-11e7-9156-0d2e43c83739.png)
![vipscentretrue](https://user-images.githubusercontent.com/1590681/27187023-5b1fe70a-51ea-11e7-8e65-ce93f857ae50.png)
![im](https://user-images.githubusercontent.com/1590681/27187028-5dd17356-51ea-11e7-8ae3-9ed03cb46e06.png)
![source](https://user-images.githubusercontent.com/1590681/27187033-609107dc-51ea-11e7-914f-3e99dfebe776.jpeg)

**Comment by jcupitt** [comment]
Hello @jardakotesovec, could you open a new issue please? It makes it easier to find things if each change to vips has a separate issue linked to it. 

You test image has given me a terrible headache hehe.

**Comment by jcupitt** [comment]
I tried quickly here:

http://www.rollthepotato.net/~john/horror/

Put the images into two tabs and try flipping. I made the images with:

```
convert horror.jpg -resize 128x128 convert_horror.jpg
vipsthumbnail horror.jpg  -o vips_horror.jpg
```

And they seem almost identical to me, I don't really see a shift.

**Comment by jardakotesovec** [comment]
@jcupitt I apologize for the headache I should have done testing directly with vips cmd from the beginning. My results were created via sharp wrapper and it seems that the issue is somewhat how I use the sharp or how the sharp use the vips maybe (https://github.com/lovell/sharp/issues/848). 

Bottom line is that I was able to get the nicely centered result directly with vips, so there is good chance that I don't bring this up again :-).

Thanks for your feedback.
