### ISSUE TITLE
How to sharpen sawtooth effect when resizing?

### ISSUE THREAD

**Issue by jackliu97** [jcupitt/libvips#505]
I'm seeing this when resizing jpegs with crisp sloped edges. Which commands should I be using to offset this effect?

examples...

(resized)
<img width="64" alt="screen shot 2016-08-24 at 1 54 47 pm" src="https://cloud.githubusercontent.com/assets/1696071/17941684/6671a89e-6a02-11e6-92a0-d96f14031dc7.png">

vs

(original)
<img width="91" alt="screen shot 2016-08-24 at 1 55 01 pm" src="https://cloud.githubusercontent.com/assets/1696071/17941688/686a46c4-6a02-11e6-9a12-31de4da7517a.png">

**Comment by jcupitt** [comment]
Hi @jackliu97, what version and what command are you using now? 8.3 added a fast lanczos3  downsizer, and if you use `resize` with the default settings you should see good results.

If I run:

```
$ vipsthumbnail sample.png -o x.png -s 298
```

On your original image I see:

<img width="69" alt="x" src="https://cloud.githubusercontent.com/assets/580843/17950031/72d3af1c-6a50-11e6-919d-0d109974405d.png">

**Comment by jackliu97** [comment]
Hey thanks for replying. I'm currently using `vips-8.0.2-Sat May 16 05:56:01 PDT 2015`.

I wrote my own go service, using github.com/h2non/bimg as a wrapper. This was actually a 2000x1000 jpeg that I shrunk to 1000x500 using `bimg.Resize` with `opt.Force=True`

When I tried it with your same exact command:

```
vipsthumbnail test_resize.jpg -o result_resize.jpg -s 1000x500
```

The image comes out without any visible deterioration at all.

Maybe this is something I should be asking the author, or simply just use cmd calls. Thanks!

**Comment by jcupitt** [comment]
I'd try a more recent libvips, the resizing code has been rewritten since 8.0.2, it's much nicer now. 

You could mention this to the bimg maintainer too, I'm sure he'd be interested.

**Comment by jackliu97** [comment]
Thanks! I will try the latest version of vips, and also post an issue to the bimg maintainer.

**Comment by jackliu97** [comment]
Turns out, bimg have bicubic as the default interpolation. I just need to set it to bilinear.

**Comment by jcupitt** [comment]
I wouldn't use bilinear, it's very low quality. The default for `vipsthumbnail` is lanczos3, which is very nice. 

Bicubic should be better than bilinear, I'm not sure where the sawtooth is coming from.
