### ISSUE TITLE
Possible to dzsave and resize at the same time?

### ISSUE THREAD

**Issue by allanw1** [jcupitt/libvips#506]
I want to generate a deepzoom file but I'd also like to resize the image at the same time. Is it possible from the command line in one step? Or should I write it to a temp file first? I want to avoid that since it's a large image and I don't want to JPEG compress multiple times.

**Comment by jcupitt** [comment]
Hi @allanw1, yes, you can use `.dz` as an output file suffix to mean "write to deepzoom".

When vips writes the output from an operation, for example:

```
$ vips invert file1.jpg file2.tif
```

It uses the suffix on the output file name to pick a save operation to use. Here `.tif` will pick `tiffsave`. You can see all the registered suffixes with `vips -l`:

```
$ vips -l  | grep VipsForeignSave
...
        VipsForeignSaveDz (dzsave), save image to deep zoom format (.dz), priority=0, any
        VipsForeignSaveTiff (tiffsave), save image to tiff file (.tif, .tiff), priority=0, any
```

vips then runs that save operation to save the output file, using any options in `[]` at the end of the filename to set options on the save operation. So these two are equivalent:

```
$ vips jpegsave somefile x.jpg --Q 90
$ vips copy somefile x.jpg[Q=90]
```

That's using `copy` as the operation, but you can use anything, of course. 

You can therefore solve your problem like this:

```
$ vips resize somefile output.dz[tile_size=512] 0.2
```

And it'll shrink by a factor of five before saving. 

`resize` might not be the best thing to use, what are you shrinking and by how much?

**Comment by allanw1** [comment]
Thanks. It's a bit strange that there's a dedicated dzsave option when you can use the .dz format directly.

Currently I'm using the options "--tile-size=510 --angle=d90 --properties"
Seems like I can use all three options in the dz save options then.

I'm resizing some 50000x50000 images to 25000x25000 from slide formats like .svs or .mrxs

**Comment by jcupitt** [comment]
The `dsave` command is the main one, it's just that you can also invoke it implicitly.

You can pull layers out of slides and then just dzsave them, it can be a lot quicker. For example:

```
$ vipsheader -a mrxs/CMU-1.mrxs 
... a lot of stuff ...
openslide.level[0].downsample: 1
openslide.level[0].height: 220696
openslide.level[0].width: 109240
openslide.level[1].downsample: 2
openslide.level[1].height: 110348
openslide.level[1].width: 54620
...
```

It lists all the levels and you can pick out the one you need. So:

```
$ vips dzsave mrxs/CMU-1.mrxs[level=1] x
```

Will pull out level 1 (110k x 55k pixels) and build a pyramid from that. It'll be much, much faster than decoding the whole image and shrinking it.

**Comment by allanw1** [comment]
Thanks, that was very helpful. Could be useful to document the use of [level=n] in dzsave

**Comment by jcupitt** [comment]
OK, I added a note to the dzsave blog post.
