### ISSUE TITLE
Add function to check for embedded icc profile's presence

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#511]
If one write's code that needs to work with images with embedded icc profiles as well as images without profile, it's often required to check if an embedded profile is present and then used different behaviour depending on the result.

For example when doing linear light resizing, with an embedded profile one would do:

```ruby
im = Vips:Image.new_from_file("image_with_icc.png")
im = im.icc_import(pcs: :xyz)
im = im.resize(0.5)
im = im.icc_export(pcs: :xyz)
im.write_to_file("image_with_icc_resized.png")
```

For doing resize without embedded profile:

```ruby
im = Vips:Image.new_from_file("image_no_icc.png")
im = im.colouspace(:xyz)
im = im.resize(0.5)
im = im.colourspace(:srgb)
im.write_to_file("image_noicc_resized.png")
```

It would be great if the was a function like `vips_icc_has_embedded_profile()` which would return a boolean value, so the above example could switch on `im.icc_has_embedded_profile()`.

Currently I'm handling this problem by catching `Vips::Error` and checking for the exception error message to match `"icc_import: no input profile\n"`, but using exception handling for control flow is highly discouraged in ruby.

**Comment by jcupitt** [comment]
Hi @felixbuenemann, I agree, that's very ugly.

You can check for the `icc-profile-data` field. If it's present, there's an ICC profile on the image. 

In Ruby, it's something like:

```ruby
image = ...
if image.get_typeof("icc-profile-data") != 0 
    image.icc_import(...)
end
```

Would that fix your problem?

**Comment by jcupitt** [comment]
... of course, anything can attach any item of data under the name `icc-profile-data`, so I suppose that's not foolproof. You'll also find that sometimes RGB images have CMYK profiles attached (or vice versa) and that'll make `#icc_import` fail.

It would be more robust to first try `#icc_import`, then if that fails, fall back to `#colourspace`.

**Comment by felixbuenemann** [comment]
Well if an RGB image has a CMYK profile that really is an error and should fail.

Your proposed solution works for me, although the check needs to be for `nil` as 0 is not falsy in ruby.

**Comment by felixbuenemann** [comment]
Btw. I amended the wiki article on linear light resize to use `vips_icc_export()` if `vips_icc_import()` was used. Otherwise I got completely wrong coulours (if using icc_import / resize / colourspace).

**Comment by felixbuenemann** [comment]
@jcupitt Should I keep the issue open as a possible enhancement? The above fix works for me, but it's not easy to find.

**Comment by jcupitt** [comment]
Maybe we should add a note to the `vips_icc_import()` docs? I'll have a look.

Strange, you'd think `colourspace(:srgb)` would give roughly the same results as `icc_export()` with an sRGB profile. Could it be a difference in rendering intent?

**Comment by felixbuenemann** [comment]
The output image looked like it was still xyz. I'll retry, maybe I did something wrong, but I remember trying it at least twice.

**Comment by felixbuenemann** [comment]
And yeah adding a note to `vips_icc_import()` and `vips_icc_transform()` docs should be ok.

**Comment by felixbuenemann** [comment]
@jcupitt Just retried icc_import / resize / colourspace srgb and it was fine.

Still icc_export should be preferred, if for example an sRGB file like PNG is used with a non-sRGB ICC profile like AdobeRGB, right?

**Comment by felixbuenemann** [comment]
Btw. it's strange that `im.get_typeof("icc-profile-data")` returns `nil` in Ruby, but `<GType invalid (0)>` in Python. So in Python the check needs to be `im.get_typeof("icc-profile-data").name != "invalid"`.
I would have expected the Python code to return `None`.

**Comment by jcupitt** [comment]
`colourspace(:srgb)` will be a lot faster (2x faster? I forget), and will be more accurate too. It's less flexible though --- srgb relative only. I'd use a matching `icc_export`anyway, for symmetry. 

The pyvips test for invalid is annoying, I agree, it comes down to differences in the way that gobject-introspection wraps GType in ruby-gnome2 vs. pygobject. You can do `im.get_typeof("icc-profile-data") != GObject.TYPE_INVALID`, which is slightly neater.

**Comment by jcupitt** [comment]
OK, I added a note to the docs too. I found a problem with very large profiles too, so ... useful!

**Comment by felixbuenemann** [comment]
Thanks you John!
