### ISSUE TITLE
overlap in dzsave with google layout is still broken

### ISSUE THREAD

**Issue by unusual-thoughts** [jcupitt/libvips#512]
Hi, I still have an issue with dzsave in Google layout on latest git on linux.
On this source image:
![crowd1](https://cloud.githubusercontent.com/assets/8385247/18233402/dee8443a-72e6-11e6-8519-1f45cea0be9f.jpg)
`vips dzsave crowd.png output --layout google --tile-size 256 --overlap 192` produces:
![all](https://cloud.githubusercontent.com/assets/8385247/18233397/d79d6692-72e6-11e6-8ebf-d24a3c275074.jpg)

As you can see, only the first row and column actually overlap with the second row/column.
Also, it is missing the last row (that should be padded with white)

While `vips dzsave crowd.png output --layout dz --tile-size 256 --overlap 192` produces:
![all3](https://cloud.githubusercontent.com/assets/8385247/18233413/1faf6908-72e7-11e6-938d-ca010058cd2f.jpeg)
Which looks fine to me (the non-border tiles are 640 pixels across = 256+192+192)

I was expecting the google layout tiles to still be 256x256, but with 3/4 overlap as well.

**Comment by jcupitt** [comment]
Oh dear, that looks bad, I'll investigate. Thanks!

**Comment by jcupitt** [comment]
I made a pair of tiny untiler programs:

https://gist.github.com/jcupitt/e1a9cec351dac91c4a9d4055a21f41b3

https://gist.github.com/jcupitt/c179028f51b94d1d4163593011215938

And yes google maps layout is broken here too.

**Comment by unusual-thoughts** [comment]
Nice! I was using `montage` from imagemagick to figure out what was going on

**Comment by jcupitt** [comment]
Do you know how google maps expects overlaps to work? I've not found any documentation :(

deepzoom makes the centre tiles larger by 2* overlap and steps across the image by tilesize. I have the impression that gmaps expects every tile to be tilesize pixels across and to step centre tiles by tilesize - 2*overlap, but I can't find any confirmation.

**Comment by unusual-thoughts** [comment]
Honestly, I don't know that google maps even supports overlaps. The way I expected it to work is to keep all tiles at tilesize no matter what, and to step center tiles by tilesize-overlap (not tilesize-2*overlap)

**Comment by jcupitt** [comment]
Yes, I've only seen overlap 0 for gmaps, I think. I've downloaded maptiler (the commercial google maps builder) I'll see if they have an overlap option.

**Comment by jcupitt** [comment]
maptiler always does 0 overlap and there's no option to change it I could find. 

https://www.maptiler.com

It's also extremely slow, which is gratifying :) It's about 45s for a 10k x 10k pixel image, whereas `dzsave` is under 2s. Of course it can do a range of projections, such as Mercator, which dzsave absolutely cannot.

**Comment by unusual-thoughts** [comment]
The effort you put into libvips' backend really shows!

Regarding overlap, even though it's not an actual google maps feature it would still be nice to have it for other uses (I'm not actually using the google maps javascript client).

Also, do you have any idea why the last row is missing?

**Comment by jcupitt** [comment]
I made a branch with an experimental new overlap system, it's better but not quite done. 

https://github.com/jcupitt/libvips/tree/new-dzsave-overlaps

I retagged as an enhancement rather than a bug, since I'm not sure GM with overlap != 0 was ever really supported.

**Comment by jcupitt** [comment]
It seems to work now. I see:

```
$ vips dzsave crowd.jpg x --overlap 192 --depth one --layout google
$ ~/try/untile-gm.py x/0 x.jpg
```

![x](https://cloud.githubusercontent.com/assets/580843/18306636/9badf0ca-74e4-11e6-91c2-995c2fbd2044.jpg)

Would you be able to test as well? I'll add something to the test suite too.

**Comment by unusual-thoughts** [comment]
It looks right on my end as well. Both the last row bug and tile_step bug are fixed.
You mentioned the fix wasn't quite done?

**Comment by jcupitt** [comment]
That's great! 

I just meant it needs some tests, and I ought to verify that the number of tiles is correct if the image width is exactly right and it doesn't try to round up or down unexpectedly.

**Comment by unusual-thoughts** [comment]
Also, just a tiny fix: vips was stripping any suffix after the last dot in the output directory name (even though it wasn't a known extension like `.zip`)
https://github.com/jcupitt/libvips/pull/519

**Comment by jcupitt** [comment]
OK, added some tests, it all seems to work, and pushed to master.
