### ISSUE TITLE
Question: Rotate an image by arbitrary angles

### ISSUE THREAD

**Issue by gargsms** [jcupitt/libvips#514]
Is it possible to rotate an image by arbitrary angle?
In the docs, I could only find possible rotations as whole multiples of 45 degrees.

**Comment by jcupitt** [comment]
You probably want `similarity`:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-resample.html#vips-similarity

**Comment by gargsms** [comment]
This works. Thanks

**Comment by s-sajid-ali** [comment]
What's the convention for the center of the rotation ? 

Is there an equivalent of the [['center'](http://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.rotate)] argument for skimage.transform.rotate? 
(The skimage implements the rotate as a sum of three similarity transform but I was not able to get the same behavior by applying three similarity transforms using vips.)
