### ISSUE TITLE
Xres and Yres can sometimes be invalid for jpeg with exif

### ISSUE THREAD

**Issue by UlysseM** [jcupitt/libvips#516]
Hi,

I had an image who had the following metadata resolution:
- x from jpeg frame: 350
- y from jpeg frame: 350
- y from exif tag: 350

The VipsImage picked up a resolution of 72x350.

Digging up a bit, Vips is importing exif info with **exif_data_new_from_data** from libexif, which will set the flag EXIF_DATA_OPTION_FOLLOW_SPECIFICATION and call exif_data_load_data, which will basically end up calling exif_content_fix, since the flag mentioned above was set.

This last function will basically make sure we have the right type (rational / byte / ...) for the right tag, and will also add a default value of 72 for the X_RESOLUTION and Y_RESOLUTION tag whenever it is not provided.

This basically mean that, when we are calling **exif_data_new_from_data**, X_RESOLUTION and Y_RESOLUTION will be set to 72 if they are not in the metadata. Which mean, back to the vips code, **res_from_exif** will always pick up the resolutions tags from the exif.

I don't really know what's the best approach for this:
- We could try importing the exif data without exif_data_new_from_data, to avoid calling exif_content_fix. If exif_content_fix is really that important for vips, we can check for the presence of the X_RESOLUTION and Y_RESOLUTION tags before calling exif_content_fix manually, and use that resolution later on if both field were set at this point.
- We could ignore the exif resolution, and pick the one from the jpeg frame
- We could ignore the exif resolution if it has a value of 72 and the jpeg frame has a value != 72 or 0.

I don't mind patching this, I'd just want to know if any of these approach would eventually make it into master.

**Comment by jcupitt** [comment]
Hi @UlysseM, sure, I'm happy to see improvements to master. A sample image would help me to understand the issues. 

Could you upload a JPG somewhere which shows this problem? It sounds like it might be a good addition to the test suite.

**Comment by UlysseM** [comment]
http://umw.fr/res.jpg
Since I'm using the VipsImage Xres and Yres to squarify the image, I'm getting a really weird look for this image.

**Comment by jcupitt** [comment]
I agree, this looks tricky to fix. I tried in several exif viewers and they all complained. `exiv2` was interesring:

```
$ exiv2 -v bad-exif-res.jpg 
File 1/1: bad-exif-res.jpg
Warning: Directory Image, entry 0x0001 has unknown Exif (TIFF) type 0; setting type size 1.
Error: Offset of directory Sony1, entry 0x2001 is out of bounds: Offset = 0x005fe076; truncating the entry
File name       : bad-exif-res.jpg
File size       : 263267 Bytes
```

And it fails to list any resolution tags. 

The libexif-based viewers all gave the same result (of course), with yres 350, xres 72. 

```
$ vipsheader -a bad-exif-res.jpg | grep -i resol
exif-ifd0-YResolution: 350/1 (350, Rational, 1 components, 8 bytes)
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd0-XResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-XResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-YResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
resolution-unit: in
$ exiftool bad-exif-res.jpg | grep -i resol
Y Resolution                    : 350
Resolution Unit                 : inches
X Resolution                    : 72
```

The `jpegsave` operation has a two-stage strategy for fixing and writing exif. It creates an exif block with required fields al set to their default values, then merges that with the tags from the header. Perhaps we could do something similar for load?

* create empty exif block with just the required fields all at their default value
* loop over the exif in the jpeg file, setting fields
* have a special case: if one of xres or yres is set but not both, set both

So you'd see 350/350 for your file. Does that sound reasonable?

**Comment by UlysseM** [comment]
I'm not sure I understand your plan.

1/ if we create an empty exif block, the value for x/y res will be set to 72.
2/ in order to copy the field, we need to load them first. If we use exif_data_new_from_data to do so, we end up with the same issue (we won't be able to detect if it was set by default, or if it was in the original exif).
3/ You mean, by removing the x/y res from the exif block we created? So that we fallback to the resolution available in the jpeg header format later on?

----

Currently, my plan goes as follow:

Instead of calling exif_data_new_from_data, we can call a new function we'd host in the vips code:
```
ExifData * load_exif_data_without_fix(const unsigned char* data, unsigned int size) {
  ExifData *edata = exif_data_new();
  if (!edata) {
     return NULL;
  }
  exif_data_unset_option(edata, EXIF_DATA_OPTION_FOLLOW_SPECIFICATION);
  exif_data_load_data (edata, data, size);
  return edata;
}
```
Which will have the same effect, as exif_data_new_from_data(data, size), except we will not have "exif_content_fix" being called, and the values set by default.

I don't know exactly how not having the edata "fixed" will impact the vips code (I have not read it all), but I expect it should behave as expected in res_from_exif.
the get_entry_double will return -1 since the field will be missing, or vips_exif_get_double will return -1 if the field doesn't have the expected type (not rational).

If you feel a bit scared about having potentially missing fields, we can move the "res_from_exif" a couple of lines up (before exif_data_foreach_content), and call exif_content_fix right after.

**Comment by jcupitt** [comment]
Yes, I think we have the same idea. We make an "empty" exif block with all required fields at their default values, load without defaulting (your `load_exif_data_without_fix()` function), then merge the two blocks to make the exif we attach to the vips image. 

I'll make a branch for experimenting.

**Comment by UlysseM** [comment]
https://github.com/UlysseM/libvips/commit/4451f4d8393c4e75070a7020dc1ba47d8fd96431

(note: I let an extra printf to debug the value of xres and yres)

I got the following:
```
tools/vipsheader -a es.jpg  | grep -i resol
vips warning: VipsJpeg: error reading resolution
Resolution is 13.779528 13.779528
exif-ifd0-YResolution: 350/1 (350, Rational, 1 components, 8 bytes)
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd0-XResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-XResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-YResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
```
The resolution is 13.77, which multiplied by 25.4 gives me the 350 I expected. Overall, I'm pretty happy with this result.
The downside here is that the vipsheader will print out bad information.

**Comment by jcupitt** [comment]
Ah I see what you mean now I look at the code, yes, no need to merge two blocks ourselves, we can just fix before attaching the vips metadata. 

It seems to work OK for me, I now see:

```
$ vipsheader -a bad-exif-res.jpg
bad-exif-res.jpg: 1024x683 uchar, 3 bands, srgb, jpegload
width: 1024
height: 683
bands: 3
format: 0 - uchar
coding: 0 - none
interpretation: 22 - srgb
xoffset: 0
yoffset: 0
xres: 13.779528
yres: 13.779528
filename: "bad-exif-res.jpg"
vips-loader: jpegload
jpeg-multiscan: 0
...
```

It probably needs some more testing.

**Comment by UlysseM** [comment]
I just removed the "fix" line, and I got:
```
tools/vipsheader -a /Users/ulysse/Downloads/res.jpg  | grep -i resol
vips warning: VipsJpeg: error reading resolution
Resolution is 13.779528 13.779528
exif-ifd0-YResolution: 350/1 (350, Rational, 1 components, 8 bytes)
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd1-XResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-YResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)

```
Which looks more valid to me (for the header part).

**Comment by jcupitt** [comment]
I think we need to keep the exif data on the vips header to spec, I'd like to keep the fix line.

How about when we spot the missing tags, we add exif ourselves for the corrected value? Then the fix won't add the incorrect 72dpi tags.

**Comment by UlysseM** [comment]
You mean write the dpi info from the Xres value? this would be pretty neat, I'll edit my commit.

**Comment by jcupitt** [comment]
There's `set_exif_resolution()` in the jpeg writer to set exif tags from the vips xres/yres, I tried just calling that to update the exif:

```
$ vipsheader -a bad-exif-res.jpg
xres: 13.779528
yres: 13.779528
exif-ifd0-YResolution: 350/1 (350, Rational, 1 components, 8 bytes)
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd0-XResolution: 4294966200/12271332 (350.00000000, Rational, 1 components, 8 bytes)
```

Which is pretty funny, sigh. It might be necessary to keep it a rational if we copy the field.

**Comment by jcupitt** [comment]
Anyway, make a PR with your commit in and I'm very happy to merge to master.

**Comment by UlysseM** [comment]
With my most recent commit, I have:
```
tools/vipsheader -a res.jpg  | grep -i resol
vips warning: VipsJpeg: error reading resolution
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd0-XResolution: 13779/1000 (13.779, Rational, 1 components, 8 bytes)
exif-ifd0-YResolution: 13779/1000 (13.779, Rational, 1 components, 8 bytes)
exif-ifd1-XResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-YResolution: 72/1 (72, Rational, 1 components, 8 bytes)
exif-ifd1-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
```

**Comment by UlysseM** [comment]
Oh well, I had no idea write_tag existed. Do you want both commit in the PR or just the first ?

**Comment by jcupitt** [comment]
Could you put everything in there?

**Comment by jcupitt** [comment]
OK, all done! Thanks @UlysseM.
