### ISSUE TITLE
vips_resize() uses bicubic for upsizing and Lanczos for downsizing?

### ISSUE THREAD

**Issue by aarti** [jcupitt/libvips#517]
Looking at this chunk of code in vips_resize() it appears that bicubic would be used for upsizing and Lanczos for downsizing. Could you please confirm.

https://github.com/jcupitt/libvips/blob/master/libvips/resample/resize.c#L270-L310

**Comment by jcupitt** [comment]
Yes, I think you're correct.

**Comment by aarti** [comment]
Is it intentional? or would be a matter of updating the function `vips_resize_interpolate`

**Comment by jcupitt** [comment]
Bicubic seemed a reasonable default. It could be swapped for one of the Roubidoux ones I guess. Yes, it would be just a matter of changing `vips_resize_interpolate()`.

By the way, you can see what operations vips is performing with `--vips-cache-trace`. For example:

```
$ vips resize k2.jpg x.jpg 2 --vips-cache-trace
...
vips cache+: affine in=((VipsImage*) 0x262e020) interpolate=((VipsInterpolateBicubic*) 0x2629050) out=((VipsImage*) 0x262e340) matrix=2 0 0 2  -
...
```

**Comment by jcupitt** [comment]
I'll close, I think we're done.
