### ISSUE TITLE
Question: dzsave depth

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#520]
I notice that if I use `--depth=onetile` OpenSeaDragon gets awfully confused -- presumably because the structure no longer matches the expected naming conventions?

However the default (`onepixel`) seems counter-intuitive -- zooming out beyond `tile-size` doesn't seem particularly useful -- and in my use case utilises additional CPU and disk space in creating them.

Perhaps I need to set it to `onetile` and work out how to "de-confuse" OpenSeaDragon?

Any thoughts?

**Comment by jcupitt** [comment]
Yes, `onetile` is for the google maps and zoomify mode, no deepzoom viewer will work with that. 

You'd need to switch viewer I think.

**Comment by harukizaemon** [comment]
Ahh that's OK.  I can live with the extra files.  It just seemed odd to have them all the way down to a single pixel when.  Thanks!

**Comment by jcupitt** [comment]
It's part of the deepzoom format. They allow images to be nested, so a single pixel in one image can expand into an entirely new image if you zoom far enough. To make this possible, you need to be able to zoom out to a single pixel.

**Comment by harukizaemon** [comment]
Ahh!  I hadn't considered the nesting aspect.  Right.  I'll stick with it as is - I don't think OSD supports either of the other formats - and the additional data is in the hundreds of K which in comparison to the stuff I'm processing, is peanuts.
