### ISSUE TITLE
vips_text align does not work when the text can fit in a single line

### ISSUE THREAD

**Issue by gargsms** [jcupitt/libvips#521]
It does work when the text overflows the width, but not when it can be contained in the width. In that case it is always left aligned no matter what.

**Comment by jcupitt** [comment]
That's correct, `align` only affects multi-line text. `width` is not the width of the output image, it's the point at which the text will be line wrapped.

Maybe 'wrap-width` would be a better name? 

```
john@kiwi:~/pics$ vips text x.png banana
john@kiwi:~/pics$ vipsheader x.png
x.png: 45x14 uchar, 1 band, b-w, pngload
john@kiwi:~/pics$ vips text x.png banana --width 1000
john@kiwi:~/pics$ vipsheader x.png
x.png: 45x14 uchar, 1 band, b-w, pngload
```

If you want to centre a single line of text, use `embed`. In Ruby:

```
txt = Vips::Image.text "hello"
txt = txt.embed (1000 - txt.width / 2), 0, 1000, txt.height
```

**Comment by gargsms** [comment]
Makes sense. I would try and use embed then.

**Comment by jcupitt** [comment]
I tried to make the docs clearer. Thanks!
