### ISSUE TITLE
Convert 16-bit png to jpeg not working as expected?

### ISSUE THREAD

**Issue by nvartolomei** [jcupitt/libvips#522]
Hello,

I'm converting transparent pngs to jpegs, however I'm using go bindings provided by [bimg](https://github.com/h2non/bimg) which uses [`vips_flatten`](https://github.com/h2non/bimg/blob/master/vips.h#L248).

When building with current libvips I got the same issue as https://github.com/h2non/bimg/issues/103 which, as I see, is fixed in master.

Tried to build with libvips:master, now the output isn't strange, but instead of white background (which is passed to vips_flatten) in place of transparency it is black.

The image I'm testing is https://dl.dropboxusercontent.com/u/98262/3.png

**Comment by jcupitt** [comment]
Hi @nvartolomei, it seems to work for me with git master. If I run:

```
$ vips copy 3.png x.jpg[background=255]
```

I see a white background. Do you know what operations  bimg is running? If you can turn on vips tracing you should be able to get a list of what it's doing.

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/VipsOperation.html#vips-cache-set-trace

**Comment by jcupitt** [comment]
I added a thing to master so that setting the env var `VIPS_TRACE` will also trace vips operations, it might help.

**Comment by nvartolomei** [comment]
Does this use flatten call? Looks like in case of 16 bit image I need to pass [255*256, 255*256, 255*256] as background instead of [255, 255, 255]. Just assuming this, haven't tested yet.

**Comment by nvartolomei** [comment]
Tested, above assumption is true.

**Comment by jcupitt** [comment]
Yes, `jpegsave` automatically converts to a format that the jpeg writer can handle, so 1, 3 or 4 bands, no alpha, 8 bits. The alpha removal happens after conversion to 8 bits, so 255 is fine. 

You're right, if you flatten a 16-bit RGBA image to 16-bit RGB, you'll need to use (2^16 - 1) as white, or 65535. 

```
$ vips flatten 3.png x.png --background 65535
```

You can use 65535 as white for 8-bit images too, if that simplifies things at all.

**Comment by nvartolomei** [comment]
Oh, then looks like this is incorrect call from bimg side.

Thank you for explanations!
