### ISSUE TITLE
vips embed puts white in the transparent area of original png

### ISSUE THREAD

**Issue by aarti** [jcupitt/libvips#524]
How can I get same background color for transparent area?

`vips embed  fixtures/1.png ~/Desktop/test1.png 100 300 600 600 --extend=background --background="255 0 0 255"`

![1](https://cloud.githubusercontent.com/assets/318049/18525797/db941faa-7a72-11e6-8690-99fb36f84ba4.png)
![test1](https://cloud.githubusercontent.com/assets/318049/18525807/e13795c2-7a72-11e6-8b44-e5aa3ac4d374.png)

**Comment by jcupitt** [comment]
I think the easiest way would be to flatten the alpha out of the rose picture first:

```
$ vips flatten rose.png x.png --background "255 0 0"
```

Then put it inside the red square:

```
$ vips embed x.png out.png 100 300 600 600 --background "255 0 0"
```

Would that work?

**Comment by aarti** [comment]
Thank you!!!
