### ISSUE TITLE
Question: Install VIPS on Centos 7

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#528]
My apologies for what is likely a totally newbie question.

I am trying to workout how to install VIPS on a fresh Centos 7 box and thus far, have failed dismally.

Can anyone point me in the right direction?

Thanks you,

Simon

**Comment by jcupitt** [comment]
Hi, vips is part of Centos 7, so you can just install with yum, I think.

If you wan t to build the latest version from source, it's like any package: download the tarball, `./configure`, add packages until you get an all clear, then `make` and `make install`.

Latest stable tarballs are here:

http://www.vips.ecs.soton.ac.uk/supported/current/

**Comment by harukizaemon** [comment]
@jcupitt AFAICT VIPS isn't in any Centos repositories. I'll have to try and build from source but I suspect Centos 7 is missing some of the dependencies as well. I'll give it a go. Thank you, as always.

**Comment by jcupitt** [comment]
Oh, you're right, funny, it's been in Fedora for many years, I would have thought it had made its way to Centos by now. 

It's very easy to build from source, try:

http://astonj.com/tech/how-to-install-vips-on-centos-libvips/

**Comment by harukizaemon** [comment]
Thanks! I'll give it a try now.

**Comment by jcupitt** [comment]
... obviously don't install 7.30, as Aston does, you want 8.3.3.

**Comment by harukizaemon** [comment]
Haha yes. Just trying on 8.33 now and getting lib version issues:

```
configure: error: Package requirements (glib-2.0 >= 2.6 gmodule-2.0 libxml-2.0 gobject-2.0) were not met:

No package 'glib-2.0' found
No package 'gmodule-2.0' found
No package 'libxml-2.0' found
No package 'gobject-2.0' found
```

But e.g. when I go to install glib2:

```
# yum -y install glib2
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.eboundhost.com
 * epel: mirror.steadfast.net
 * extras: mirrors.tummy.com
 * updates: mirror.us.oneandone.net
Package glib2-2.42.2-5.el7.x86_64 already installed and latest version
Nothing to do
```

**Comment by harukizaemon** [comment]
Ahh I didn't have the `-devel` versions installed.  I'm an idiot!

**Comment by harukizaemon** [comment]
```
[root@centos7 vips-8.3.3]# vips --version
vips-8.3.3-Sun Sep 18 05:17:37 UTC 2016
```

Brilliant.  Thank you!

**Comment by jcupitt** [comment]
Good! You can `make check` to test your build as well. If you get the Python binding working, there's a fairly complete test suite you can run.

**Comment by jcupitt** [comment]
Oh, I'd check things like jpg and png support. Look at the summary at the end of `./configure` and make sure you have `yes` next to the various file formats you want to be able to handle. You'll need packages like `libjpeg-turbo-dev`, for example.

**Comment by ricochet2200** [comment]
For any future readers trying to figure out all of the packages needed to support a bunch of file formats, I run this:

> yum install giflib-devel openslide-devel OpenEXR-devel fftw-devel cfitsio-devel ImageMagick-devel orc-devel lcms2-devel matio-devel libwebp-devel libgsf-devel pango-devel poppler-glib-devel gcc-c++ libxml2-devel glib2-devel libpng-devel libjpeg-devel libtiff-devel gcc intltool libxml2-devel glib2-devel libexif-devel poppler-glib-devel libexif-devel pygobject3-devel pygobject2-devel epel-release

YMMV

**Comment by tdiprima** [comment]
When I configure, it says `image pyramid export: no (requires libgsf-1 1.14.27 or later)`.  I need image pyramid support, so when I do `yum install libgsf` it says `Package libgsf-1.14.26-7.el7.x86_64 already installed and latest version`.  Hm... that's **libgsf-1.14.26**, it's supposedly already the latest, but I need **libgsf-1 1.14.27**?  :\  I tried the `-devel` thing, but it also says `libgsf-devel-1.14.26-7.el7.x86_64 already installed and latest version`.  Any help would be greatly appreciated.

**Comment by jcupitt** [comment]
Hi @tdiprima , centos is lagging a bit here, 1.14.27 is from 2013.

Looking at the changelog, 1.14.21 was very crashy, 1.14.27 is known to work well, and I'm uncertain of the status of 22 - 26. I'll test 1.14.26 for you.

**Comment by jcupitt** [comment]
You could also consider building 1.14.27 yourself. Download from here:

https://ftp.gnome.org/pub/gnome/sources/libgsf/1.14/

Then `./configure`, `make` etc. as with vips.

**Comment by jcupitt** [comment]
OK, 1.14.26 seems to work on my smaller test images, I'll do a new vips with the min version set to .26. 

It won't do large zip output, would that be a problem? zip64 output was added in 1.14.31.

**Comment by tdiprima** [comment]
Got a compilation error.  `relocation R_X86_64_32 against '.bss' can not be used when making a shared object; recompile with -fPIC`  So according to this http://stackoverflow.com/questions/13812185/how-to-recompile-with-fpic, I had to do `./configure --enable-shared`.  Thanks for your help, but I'm abandoning doing this on CentOS.  I was able to install it on Ubuntu, thanks to `apt-get`.

**Comment by jcupitt** [comment]
I put a 8.4.5 up for you:

http://www.vips.ecs.soton.ac.uk/supported/current/

It should work with the libgsf on centos.

**Comment by tdiprima** [comment]
Wow.  Thank you.  And it works.  Thanks very much!

**Comment by ricochet2200** [comment]
@tdiprima Maybe you already have this figured out, but I'll respond anyway.

Yes, on EL7 libgfs is a micro version short of the minimum requirements for vips, so you will need to build it.  You should be able to follow the instructions [here](http://chrishewett.com/blog/vips-dzsave-build-from-source-on-centos-7-0/) to get it to work.

**Comment by ondrej-111** [comment]
Easy way using package manager yum: https://tufora.com/tutorials/linux/general/install-vips-vips-tools-and-vips-devel-libvips-on-centos-7
