### ISSUE TITLE
pdfload: no optional argument 'n' in libvips 8.3

### ISSUE THREAD

**Issue by joao** [jcupitt/libvips#529]
According to the libvips 8.3 [documentation](http://www.vips.ecs.soton.ac.uk/supported/8.3/doc/html/libvips/VipsForeignSave.html#vips-pdfload) there should be an 'n' optional argument available for pdfload.
For example:
`time vips copy file.pdf[n=-1] a.tif`

But when running it it states:
`pdfload: no property named`n'`

I found issue #445 that states that the 'n' optional argument will be only be added in 8.4.
Is the issue correct and the documentation wrong?

**Comment by jcupitt** [comment]
Hi @joao, yes, it's an 8.4 feature. 

It's very unfortunate. The 8.3 docs had some very serious problems: sections were missing, cross-linking was not working well, part of the introspection system that generates them was not working. I spent ages fixing up the docs for 8.4.

The poor state of the 8.3 docs was causing confusion and people were unable to find things. I thought it would be better to overwrite them with the 8.4 docs than to leave the badly broken ones up. There would be a small number of features in the docs which were not there in the library, but on the plus side, at least the docs would basically work.

Sorry for the confusion. 8.4 will be officially done by the end of the week, so hopefully this embarassing problem will vanish. The almost-final-beta is here, if you're curious:

http://www.vips.ecs.soton.ac.uk/development/8.4/

**Comment by joao** [comment]
Thank you for the fast reply!
Was also confused by #284, but will try it for now.

I'm using vips dzsave to generate tiles of horizontally appended images, from PDF pages.
Currently using ImageMagick 'convert' to extract them and append, but would like to use something more speedier like libvips. BTW, dzsave is really well made, thank you for all the work on it!

**Comment by jcupitt** [comment]
Ah OK. Yes, I think you'll need 8.4, sorry.

**Comment by jcupitt** [comment]
I think we're done, I'll close. Please open a new issue if you still have problems.
