### ISSUE TITLE
Check if SVG and PDF formats are supported by libvips

### ISSUE THREAD

**Issue by h2non** [jcupitt/libvips#531]
What's the consistent way to check if `libvips` has been linked against `libpoppler` or `librsvg`, in order to behave accordingly if those libraries, and therefore those image formats, are available. 
I'm using the C API.

I'm currently checking the contract macro via `#ifdef  HAVE_POPPLER`, but that doesn't appears to work.

Thank you!

**Comment by jcupitt** [comment]
Hi, just look up the `svgload` or `pdfload` operations. They only exist if libpoppler or librsvg have been configured. 

From C, you can do:

```
    if (vips_type_find("VipsOperation", "pdfload")) 
        have_pdfload();
```

meaning, search the type hierarchy below `VipsOperation` for a class whose nickname is `pdfload`.

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/VipsObject.html#vips-type-find

**Comment by h2non** [comment]
Fair enough! Thanks a lot!
