### ISSUE TITLE
move vipsthumbnail into libvips core

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#532]
`vipsthumbnail.c` now has quite a bit of logic in, and this has to be reimplemented in every language binding. At least sharp and bimg have something like this.

It would be helpful to move almost all of vipsthumbnail into the libvips core, perhaps as:

```
int vips_thumbnail( const char *filename, VipsImage **out, int target_width, int target_height, NULL );
```

With options for the various `--flags`, such as linear. There should be a `vips_thumbnail_buffer()` as well for memory sources.

**Comment by jcupitt** [comment]
OK, now in master, see:

https://github.com/jcupitt/libvips/blob/master/libvips/resample/thumbnail.c#L647

**Comment by hey-red** [comment]
@jcupitt vips_thumbnail will be available since 8.5 release? How soon?

**Comment by jcupitt** [comment]
Hi, there's usually a new release every six months, so I'd guess March 2017 for an official 8.5.

You can use git master before then if you like, of course.

**Comment by hey-red** [comment]
@jcupitt How to build https://github.com/jcupitt/build-win64 without version, directly from master?

**Comment by jcupitt** [comment]
It's not directly supported, you'd need to do a little hacking. I'd make a vips 8.5 tarball from git master, then adjust `vips.modules` and `variables.sh` to reference your tarball instead of the official one. It's not easy on Windows, unfortunately.
