### ISSUE TITLE
Question: How to correctly load/convert/interpret 32-bit float encoded raw files

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#534]
I have a raw image encoded as 32-bit float. I first raw-load it as 4 bands of 1-byte pixels. Then `copy` it with 1 band, a format of `FLOAT` and interpretation of `B_W`. This _seems_ to work just fine when I convert it to PNG.

I also have a raw image encoded as 16-bit unsigned. I first raw-load it as 2 bands of 1-byte pixels. Then `copy` it with 1 band, a format of `USHORT` and interpretation of `GREY16`. This also seems to work just fine when I convert it to PNG.

Now I need to use `cast` to convert the U16 to F32 so it can be processed by some other piece of software on a GPU. If I maintain the interpretation as `GREY16` all works just fine when I convert it to PNG. However, when values come back from the other software, I can't guarantee that they will be integer values that fit within 16-bits.

So, I tried to `copy` it and specify the interpretation as `B_W` but that no longer generates a usable image when I convert it to PNG, seemingly treating it as an 8-bit value?

So my question is, what interpretation am I supposed to use in order to have everything correctly interpret all all 32-bits of the float values?

Thanks,

Simon

**Comment by jcupitt** [comment]
Hi Simon,

`interpretation` and `format` are two different things. `format` is a real description of what's in the image: pixels really are ushort or float. `interpretation` is a hint saying how those pixels should be interpreted. For example, `B_W` means a mono image with 0 - 255 as black - white (the name is historical and not very intuitive).

Mostly `interpretation` is just a hint and doesn't affect how pixels are processed. The exception is the save and colour operations. They will look at `interpretation` and try to cleverly convert the image down to the format the operation needs as input. For example, if `pngsave` sees a float image tagged as `RGB16`, it will be assumed to be RGB with 0 - 65535 as black to white, and will be converted to u16 for libpng to write to the output. 

I don't know if that makes it any clearer. Can you describe a specific example which is not behaving correctly?

**Comment by harukizaemon** [comment]
Hi John,

Yes, that makes sense and is how I had come to understand it.

So the images are greyscale with either unsigned 8/16-bit integer, or 32-bit floating point intensity values.

When I output to PNG what should I be setting interpretation for each of these scenarios?

I can upload some scenarios if that would help?

**Comment by harukizaemon** [comment]
Hi John,

I have a ZIP file with an example in it. Is there a way I can get it to you without linking to it directly?

**Comment by jcupitt** [comment]
Looking at the source, it seems I was wrong, sorry! Float images will always be saved as 8-bit PNG. You need one of the larger int formats to get 16-bit PNG.

So use `cast()` to convert to u8 or u16 before saving if you want to be sure.

**Comment by harukizaemon** [comment]
Ahh! That perfectly explains my observation, then.

So now to test this out I did:

1. rawload with appropriate dimensions and bands
1. copy with 1 band and appropriate format (uchar, ushort, float)
1. cast to float
1. cast to uint
1. pngsave

Results:

1. Images originally stored as ushort (u16) come out perfectly
1. Images original stored as uchar (u8) or float (f32) come out entirely black

So now I'm thinking is where I need to mix in some `interpretation` magic?

So sorry to be a pain about this. I'm sure you have much better things to do with your life :/

**Comment by harukizaemon** [comment]
[Here is the output](https://github.com/jcupitt/libvips/files/515369/lena.zip) from the running the following commands on an 8-bit image that ends up black:

```
vips rawload lena-512x512x1-u8.raw lena-512x512x1-u8.vips 512 512 1
vips cast lena-512x512x1-u8.vips lena-512x512x1-u8-f32.vips float
vips cast lena-512x512x1-u8-f32.vips lena-512x512x1-u8-f32-ushort.vips ushort
vips pngsave lena-512x512x1-u8-f32-ushort.vips lena-512x512x1-u8-f32-ushort.png
```

**Comment by harukizaemon** [comment]
[Here is the output](https://github.com/jcupitt/libvips/files/515407/lena.zip) from the running the following commands on an float image that ends up black:

```
vips rawload lena-512x512x1-f32.raw lena-512x512x1-4xu8.vips 512 512 4
vips copy lena-512x512x1-4xu8.vips lena-512x512x1-f32.vips --bands=1 --format=float
vips cast lena-512x512x1-f32.vips lena-512x512x1-f32-ushort.vips ushort
vips pngsave lena-512x512x1-f32-ushort.vips lena-512x512x1-f32-ushort.png
```

**Comment by harukizaemon** [comment]
Turns out, performing a `byteswap` after casting worked in both cases. For example:

```
vips rawload lena-512x512x1-u8.raw lena-512x512x1-u8.vips 512 512 1
vips cast lena-512x512x1-u8.vips lena-512x512x1-u8-f32.vips float
vips cast lena-512x512x1-u8-f32.vips lena-512x512x1-u8-f32-ushort.vips ushort
vips byteswap lena-512x512x1-u8-f32-ushort.vips lena-512x512x1-u8-f32-ushort-byteswap.vips
vips pngsave lena-512x512x1-u8-f32-ushort-byteswap.vips lena-512x512x1-u8-f32-ushort-byteswap.png
```

So I have a solution, but I don't really understand why :)

**Comment by jcupitt** [comment]
Yes, that'll sort-of work. Your problem is caused by the range difference. For example:

```
$ vips black x.v 100 100 
$ vips linear x.v x2.v 0 255
$ vips max x2.v
255.000000
$ vipsheader x2.v
x2.v: 100x100 float, 1 band, b-w
```

So x2.v is 100x100 pixels of float data, each pixel has the value 255, and it's tagged as `B_W`. Now cast to ushort:

```
$ vips cast x2.v x3.v ushort
$ vips max x3.v
255.000000
$ vipsheader x3.v
x3.v: 100x100 ushort, 1 band, b-w
```

Pixel values haven't changed (still 255 everywhere), the values are just in a ushort container now. If I save as PNG:

```
$ vips copy x3.v x.png
$ vipsheader x.png
x.png: 100x100 ushort, 1 band, grey16, pngload
$ vips max x.png
255.000000
```

It's saved as 16-bit PNG, still with 255 in. But 16-bit PNG has 65535 as white, not 255, so when you view the image it'll look black.

The solution is to multiply by 256, or shift left 8 places, before saving. For example:

```
$ vips boolean_const x3.v x4.v lshift 8
$ vips copy x4.v x.png
$ vips max x.png
65280.000000
```

Now it'll look white. Your byteswap was doing more or less this by swapping the top and bottom bytes in each pixel, but *256 is better.

vips will do this for you automatically under some circumstances. For example, if you have a ushort image tagged as `RGB16` and you save as JPG (which is 8-bit only), it'll automatically shift down 8 bits for you. It can't always do this though: if you are changing formats and interpretations, you will need to keep the black - white range in mind. 

You can use `colourspace` to do this automatically. It looks at the current image interpretation and the destination interpretation you give and picks a series of transforms for you to move over. For example:

```
$ vips black x.v 100 100 
$ vips linear x.v x2.v 0 255
$ vips max x2.v
255.000000
$ vipsheader x2.v
x2.v: 100x100 float, 1 band, b-w
```

So a 100x100 pixel image, float, B_W, 0 - 255, as before, then:

```
$ vips colourspace x2.v x3.v grey16
$ vipsheader x3.v
x3.v: 100x100 ushort, 1 band, grey16
$ vips max x3.v
65535.000000
```

So it's changed the format, the interpretation and the range of values. 

I suppose the other issue is the gamma. Do your pixels have one? Do you need one?

**Comment by harukizaemon** [comment]
Aha! OK now it makes sense. Thank you!

That's a great question re gamma. I'll have to ask. As it happens the range of some of these images IS too great to fit in u16 so I'm going to need to perform some kind of scaling back to u16.

**Comment by jcupitt** [comment]
If they are linear, a gamma is a good way to get the bits down. The rule of thumb I remember is that a linear 10 bit image is roughly equivalent to an 8 bit image with a gamma. I'd think you could put 20 bits linear into a 16-bit image with a gamma.

You have pretty amazing SN if you have an image sensor with 20 bits of linear precision, of course! Or are these things synthetic?

**Comment by harukizaemon** [comment]
The originals are CT scans. Thereafter some processing occurs which should in theory bring down the range even further.

**Comment by harukizaemon** [comment]
Actually, I totally forgot (I have so much going on!) that I had discussed this today with the backend GPU guys and I think we're just going to get the their routines to normalise the range back into u16 before writing the resulting file.

I see vips has `scale` but that only supports `u8` so given they'll have all the data on the actual range from having done the processing, they can do a conversion fairly easily.

**Comment by jcupitt** [comment]
I think we're done, I'll close. Please open a new issue if you still have problems.
