### ISSUE TITLE
Banding along sharp edges with vips_resize()

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#536]
Using the 8.3.x version of vips_resize() with default arguments, a user on [the pixls.us forums](https://discuss.pixls.us/t/when-life-gives-you-blind-kittens-do-blind-kittens-lemonade/2390/11?u=carmelo_drraw) has noticed some visible horizontal banding along sharp edges.

The link provides an example of such banding, and in the same thread one can find a link to the original high-res image.

The downscaled output was obtained with photoflow, but the code directly calls vips_resize() without further intervention in the downscaling process.

Maybe there is still some margin for improving the already really excellent VIPS downscaling algorithm? (the same user concludes that VIPS is much better than PS bicubic - not surprising - and also better than GIMP no-halo/low-halo methods)

Thanks for all the efforts in providing such great tools to play with!

**Comment by aferrero2707** [comment]
This finally seems to be an artefact of Jpeg compression, so please forget about this issue for the moment...

Sorry for the noise.

**Comment by jcupitt** [comment]
Hi Andrea, vips is a pretty straight lanczos3 by default, so you shouldn't get much ringing. 

If there's transparency, you need to pre-multiply before resize or you'll get fringing on edges in the alpha mask, I don't know if that could be an issue. 

Yes, jpg can cause lots of artifacts on edges.
