### ISSUE TITLE
Does libvips support Camera RAW format such as CRW/CR2/NEF

### ISSUE THREAD

**Issue by sachinwalia2k8** [jcupitt/libvips#537]
I am using dcraw in my workflow to decompress RAW to PPM and then to PNG and so forth. I am wondering if libvips support decompressing RAW formats such as CRW/CR2/NEF etc and then eventual conversion to JPEG

thanks.

**Comment by jcupitt** [comment]
libvips has an imagemagick loader, so if you configure IM to support cr2 (I think it uses `ufraw`?), you should be able to load raw files. 

I generally use rawtherapee to convert CR2 -> TIF. It has a nice command-line mode, and you can create parameter files to get a lot of control over the process.

**Comment by sachinwalia2k8** [comment]
Thanks this information is helpful.
