### ISSUE TITLE
Give exact pixel dimensions as arguments to CLI

### ISSUE THREAD

**Issue by Meekohi** [jcupitt/libvips#539]
It would be nice to have the ability to pass exact pixel dimensions to the CLI when resizing (and presumably other operations too). Right now if you know the end result you want, you first have to get the current image dimensions via some other means and compute (new_width / orig_width), and also take into account the rounding behavior (#491) to get the exact scale factor.

**Comment by jcupitt** [comment]
Could you use `vipsthumbnail`? I think it would do what you want, for resizing at least.

There's also https://github.com/jcupitt/libvips/issues/532 "move vipsthumbnail into libvips core". The idea would be to make a `vips_thumbnail()` operation which did almost all the stuff that `vipsthumbnail.c` does, but inside libvips. You could then easily thumbnail from anything that can call libvips.

**Comment by Meekohi** [comment]
Hrm possibly, although I think it might be a better more principled change to just edit the way the CLI takes parameters (maybe on the command line allow for both "20.0" parsed as a float to be 20x scale factor, but "20" or "20px" to be pixel amount)

**Comment by jcupitt** [comment]
The CLI is auto-generated from the libvips classes, you can't really add special cases like that, unfortunately. You'd have to add a new resize operator that took a target pixel size rather than a scale.

**Comment by jcupitt** [comment]
git master libvips now has a `thumbnail` operation which takes image size in pixels as the sizing argument. Docs here:

https://github.com/jcupitt/libvips/blob/master/libvips/resample/thumbnail.c#L647

Use on the command-line as:

```
$ vips thumbnail
generate thumbnail from file
usage:
   thumbnail filename out width
where:
   filename     - Filename to read from, input gchararray
   out          - Output image, output VipsImage
   width        - Size to this width, input gint
			default: 1
			min: 1, max: 10000000
optional arguments:
   height       - Size to this height, input gint
			default: 1
			min: 1, max: 10000000
   auto-rotate  - Use orientation tags to rotate image upright, input gboolean
			default: true
   crop         - Reduce to fill target rectangle, then crop, input gboolean
			default: false
   linear       - Reduce in linear light, input gboolean
			default: false
   import-profile - Fallback import profile, input gchararray
   export-profile - Fallback export profile, input gchararray
```

It should be a convenient way to resize images.
