### ISSUE TITLE
Memory issues when using vips_draw_image (Python)

### ISSUE THREAD

**Issue by Jondeen** [jcupitt/libvips#545]
Hi,

Is draw_image a very memory intensive operation?
It seems to expend increasing amounts of memory for every draw operation I perform, however it only seems to become a problem with excessively large images (4,889,045,400 pixels).

I use the method to combine including/excluding masks ahead of quantitation. Maybe there is a better alternative for doing this? The "including" mask should limit the size of image data to ~10th of the original size (via a trim operation at first step), not sure of this matters in the bigger context.

Thanks
Jonas

**Comment by jcupitt** [comment]
Hi, yes, the `draw_*` operations are all very memory-heavy, though it depends how you call them and which language you are using. They all do something like:

```
def draw_something(image)
  if image is not a large memory array
    allocate huge area of memory
    render image into memory area
    remake image into a reference to the huge memory area
  end

  draw pixels to memory area
end
```

This means that they have side-effects: if you do two draw operations in a row, the second will modify the result of the first. This completely destroys libvips caching and threading system, so the python/ruby/php/node bindings make a copy of each image before calling the draw operation. They try to free the previous image quickly if they can detect that there's no sharing, but it's not always possible.

If you use C or C++, you can control the sharing yourself and avoid the copy operations. 

Could you post some example code? I might be able to suggest another solution. For example, `insert` might do what you need efficiently.

**Comment by jcupitt** [comment]
Oh, I didn't see the (Python) in the title. Yes, it's very expensive, especially for large images. Post an example of what you're doing.

**Comment by Jondeen** [comment]
Thanks! I'll check out `insert` and report back. I'll see if I can find some intelligible code to share as well ;-)

**Comment by Jondeen** [comment]
UPDATE;
When using `draw_image`, memory usage peaked at 22GB before the process was killed by resource management. By using `insert` it was reduced to 2GB.

Below is the script responsible for cutting out artifacts in image, repeated for each artifact ROI embedded (sometimes more than 10 individual artifact ROIs could be supplied).

```python
def cut_image_artifacts(im,json_data,artifact_roi_json_datas):
    # (Original) Image Dimensions
    im_dimensions=[im.Xsize,im.Ysize]

    artifact_coords=[data['path'] for data in artifact_roi_json_datas]
    artifact_extremas = [None for _ in artifact_coords]
    for i,a_coords in enumerate(artifact_coords):
        artifact_coords[i],artifact_extremas[i]=sanitizeCoords(a_coords, im_dimensions)


    # Init 2D-coordinate filled image
    xyz=Image.xyz(im_dimensions[x],im_dimensions[y])

    if json_data != None:
        # Coordinates are stored in json format as list of x/y-coords [[x0,y0],[x1,y1],...,[xn,yn]]
        coords=json_data['path']
        coords,extremas = sanitizeCoords(coords, im_dimensions)
        min,max = extremas

        # New dimensions:
        w=(max[x]-min[x])
        h=(max[y]-min[y])

        logic = ~Image.black(im_dimensions[x],im_dimensions[y],bands=1)
        logic_roi = testCoords(coords, xyz.crop(min[x],min[y],w,h))
        logic=logic.insert(logic_roi,min[x],min[y])
    else:
        min = [0, 0]
        max = im_dimensions
        w,h= im_dimensions[x],im_dimensions[y]
        logic = Image.black(w,h,bands=1)
        logic=logic.invert()
        xyz=Image.xyz(w,h)

    for i,a_coord in enumerate(artifact_coords):
        a_min,a_max = artifact_extremas[i]
        a_w,a_h = a_max[x]-a_min[x],a_max[y]-a_min[y]
        a_xyz = xyz.crop(a_min[x],a_min[y],a_w,a_h)
        a_logic = ~testCoords(a_coord, a_xyz)
        crop_logic = logic.crop(a_min[x],a_min[y],a_w,a_h) & a_logic
        logic=logic.insert(crop_logic,a_min[x],a_min[y])

    # Apply logics, return with outside blanked (filled with white)
    im=((logic&im)|~logic)
    # Remove redundant imagery
    im =im.crop(min[x],min[y],w,h)
    return im
```

**Comment by jcupitt** [comment]
That's a useful drop in memuse!

How is speed? You'll find insert becomes slow if you are combining several thousand images. 

Another alternative is to use destructive operations, but you have to be extremely careful, it's easy to make Python segv if you make a mistake.

**Comment by Jondeen** [comment]
Speed is improved from using `draw_image`. My main goal is to make these analyses doable on low-mem systems so latency of doing the analyses is not important (as long as it doesn't take days to complete). As mentioned Only a dozen or so of these operations are performed. What would be the destructive alternative to `insert`?

**Comment by jcupitt** [comment]
`insert` should be fine for a few dozen images. It'll bog down for many thousands. 

For the destructive version, you make a copy of the image in memory, then write to that repeatedly with a series of direct calls to `draw_image`. If you have 4gb images, even one copy in memory is a lot, so I expect plain `insert` will be preferable.
