### ISSUE TITLE
Compile error: threadpool.c:191: error: lvalue required as left operand of assignment

### ISSUE THREAD

**Issue by KarlAustin** [jcupitt/libvips#548]
I'm trying to compile 8.4 to update an app from 8.3 and am running in to an issue when building:

```
threadpool.c: In function ‘vips_thread_run’:
threadpool.c:191: error: lvalue required as left operand of assignment
```

Line 191 is:

`g_private_set( &vips_threadpool_is_worker_private, data );`

Now I'm not much of a C person, but to my mind there's no assignment there!

gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) on CentOS6

**Comment by jcupitt** [comment]
Hi Karl, my guess would be that `g_private_set()` is a macro and it's been expanded to something that includes an assignment.

Do you know what glib version you are using? I'm:

```
$ pkg-config glib-2.0 --modversion
2.48.1
```

**Comment by KarlAustin** [comment]
2.28.8

So quite old, but that's RHEL/CentOS for you :/

**Comment by jcupitt** [comment]
Ah OK, that's before the big changes to the threading system in 2.32. I'll see if I can get vips working with your glib.

**Comment by jcupitt** [comment]
I think I have it working, could you test the head of the 8.4 branch? 

https://github.com/jcupitt/libvips/tree/8.4

though there's still an annoying warning from the test suite, I'll fix that too.

**Comment by jcupitt** [comment]
The test suite warning was just a silly thing. 

I've applied the fix to master as well. Thanks very much for reporting this issue, @KarlAustin !

**Comment by KarlAustin** [comment]
Perfect, compiles and runs.   Seeing about 4-5% improvement in speed as well on the app it's used in.

Thanks.

**Comment by jcupitt** [comment]
Good, glad it's working. You might see a drop in memory use too, especially on long-running server processes.
