### ISSUE TITLE
add ICC profile read to loadwebp

### ISSUE THREAD

**Issue by rnanwani** [jcupitt/libvips#550]
` cwebp -metadata icc <input.jpg> -o <output.webp>`

The above command maintains the color profile in the output. How can I achieve the same (or even get the entire metadata for the image) in the output using libvips. The color profile is getting stripped by default when I use

`vips webpsave <input.jpg> <output.jpg>`

**Comment by jcupitt** [comment]
The libvips webp reader does not look for ICC profiles on the input file. This would be a useful feature to add. Obviously the webp writer should be able to attach profiles as well. 

libvips knows about ICC profiles in PNG, TIFF and JPG, so this is just a problem for webp.

**Comment by jcupitt** [comment]
Here's a branch for this feature:

https://github.com/jcupitt/libvips/tree/add-webp-metadata

It seems to work, though all it does at the moment is print a message about the ICC / EXIF and XMP metadata. 

I can't find any test webp images with embedded profiles, I don't suppose you have one handy?

**Comment by rnanwani** [comment]
Can you check this image
https://drive.google.com/open?id=0BznBgV252hG1cnlGQ21FSW9BQXM

**Comment by jcupitt** [comment]
That's a great test image, thanks!

I see:

```
$ vipsheader -a webp_with_profile.webp 
vips warning: exif: error reading resolution
webp_with_profile.webp: 367x550 uchar, 3 bands, srgb, webpload
width: 367
height: 550
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: webp_with_profile.webp
vips-loader: webpload
icc-profile-data: 560 bytes of binary data
xmp-data: 3652 bytes of binary data
exif-data: 9239 bytes of binary data
exif-ifd0-XResolution: 25400/1000 (25.400, Rational, 1 components, 8 bytes)
exif-ifd0-YResolution: 25400/1000 (25.400, Rational, 1 components, 8 bytes)
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd2-ExifVersion: Exif Version 2.1 (Exif Version 2.1, Undefined, 4 components, 4 bytes)
exif-ifd2-FlashPixVersion: FlashPix Version 1.0 (FlashPix Version 1.0, Undefined, 4 components, 4 bytes)
exif-ifd2-ColorSpace: 65535 (Internal error (unknown value 65535), Short, 1 components, 2 bytes)
```

So:

* There's no resolution information on your exif, which I think is required by the standard, hence the warning message.
* Does that look roughly correct? There seems to be too much exif, I don't know what's in the 9200 bytes. 
* Is the size of the ICC profile and the XMP data correct? 
* I'm not sure what colorspace -1 means.

**Comment by rnanwani** [comment]
The original JPEG - https://drive.google.com/open?id=0BznBgV252hG1czM3S0phNGUtNGM
I used `cwebp -metadata all <input> -o <output>`

The input JPEG has this additional data which is the reason for 9200 bytes i guess
exif:UserComment: 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0....<many more zeroes after this>
    unknown: 28, 234, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, <even more zeroes after this>

**Comment by jcupitt** [comment]
It seems to work, would you be able to test?

https://github.com/jcupitt/libvips/tree/add-webp-metadata

I still need to check against libwebp 0.3 and check for memleaks with valgrind, but otherwise it all seems to be complete and working.

**Comment by jcupitt** [comment]
OK, valgrind and 0.3 testing done, all ready for merge.

**Comment by jcupitt** [comment]
Merged to master. Thanks!
