### ISSUE TITLE
Example of resizing a high density image (retina screenshot) to 72ppi jpeg

### ISSUE THREAD

**Issue by nvartolomei** [jcupitt/libvips#552]
Can anyone provide an example of resizing a high density image to standard 72ppi jpeg without losing too much quality? Tried with h2non/bimg and sharp and the results are far from acceptable.

At 100% quality:

1440px
![hello](https://cloud.githubusercontent.com/assets/543193/20144462/5fdbb666-a6a5-11e6-86f6-3ca516062440.jpeg)

700px
![hello](https://cloud.githubusercontent.com/assets/543193/20144514/860398ae-a6a5-11e6-9542-6000c3b9d022.jpeg)

orignal
<img width="1393" alt="sh" src="https://cloud.githubusercontent.com/assets/543193/20144464/6005f840-a6a5-11e6-809d-60a4c3817410.png">

**Comment by jcupitt** [comment]
Hi, you could try the kernel option. sharp uses lanczos3 by default, but cubic might produce harder edges. 

http://sharp.dimens.io/en/v0.16.2/api/#resizewidth-height-options

Disabling chroma subsample on jpegsave will make blue text look much better. If you use png for the output, it'll look better again.

**Comment by lovell** [comment]
Cross-posted at https://github.com/h2non/imaginary/issues/109

**Comment by jcupitt** [comment]
@nvartolomei please don't cross-post questions, it creates extra, unnecessary support work.

**Comment by jcupitt** [comment]
I tried just turning jpeg quality up. Like imagemagick, above Q90, libvips disables chroma subsample.

```
$ vipsthumbnail screenshot.png -s 700 -o thumb.jpg[Q=90]
```

It makes the blue text much less blurry. 

![thumb](https://cloud.githubusercontent.com/assets/580843/21652271/f238245c-d2a3-11e6-9923-6606e94b081e.jpg)

You can also disable chroma subsample but leave Q at the default 75:

```
vipsthumbnail screenshot.png -s 700 -o thumb.jpg[no-subsample]
```

Which might be good enough, and is smaller.

![thumb](https://cloud.githubusercontent.com/assets/580843/21652395/6167a32a-d2a4-11e6-9e83-4f458f503ae5.jpg)
