### ISSUE TITLE
dzsave crashing in 8.4.x on Windows

### ISSUE THREAD

**Issue by yurykovshov** [jcupitt/libvips#553]
Hi!

I have a successful CLI call of dzsave command in 8.3 version:
`vips.exe dzsave "Colon.svs" "Colon" --overlap=0 --suffix=".jpg[Q=85]" --tile-width=256 --tile-height=256 --properties --vips-concurrency=1 --vips-progress`

But in 8.4.1 with the same line I have a vips.exe crushing. And it works only if I leave:
`vips.exe dzsave "Colon.svs" "Colon" --vips-progress`

But looks like it stops crushing as soon as I remove "suffix" argument. I've checked the vips source code and looks like I'm using it in a right way.

// Windows 8

> Faulting application name: vips.exe, version: 0.0.0.0, time stamp: 0x00020501
Faulting module name: vips.exe, version: 0.0.0.0, time stamp: 0x00020501
Exception code: 0xc0000005
Fault offset: 0x0000000000001acc
Faulting process id: 0x709c
Faulting application start time: 0x01d23b48972e415f
Faulting application path: C:\vips-dev-8.4\bin\vips.exe
Faulting module path: C:\vips-dev-8.4\bin\vips.exe
Report Id: d4efc3ff-a73b-11e6-82b1-50e549daa4bf
Faulting package full name: 
Faulting package-relative application ID: 

[Report.zip](https://github.com/jcupitt/libvips/files/583260/Report.zip)

**Comment by jcupitt** [comment]
Hi @yurykovshov, have you tried 8.4.2?

**Comment by jcupitt** [comment]
OK, seeing a crash here too in Wine, I'll investigate. Thanks for reporting this Yury.

**Comment by jcupitt** [comment]
I found it, thanks for reporting this Yury. I'll put up 8.4.4 later today.

**Comment by jcupitt** [comment]
OK, 8.4.4 is up with the fix:

http://www.vips.ecs.soton.ac.uk/supported/current/win32/

You want the `all` zip, of course.

**Comment by yurykovshov** [comment]
Ok, it is fixed. Thanks, John!

**Comment by yurykovshov** [comment]
Noticed that during dzsave of MRXS file to ZIP container, VIPS or openslide (?) outputs a lot of warnings: 
![image](https://cloud.githubusercontent.com/assets/7525042/20313960/ebc01246-ab58-11e6-81fd-8dd6adc17b03.png)

If it's a problem, then it's better to create a new issue. The current one I'll close. Thanks

**Comment by bgilbert** [comment]
@yurykovshov That's a libjpeg error raised by OpenSlide, and your Deep Zoom image will be partially blank as a result.  If you're only seeing this with one slide file, the slide might be corrupt.  If you're seeing it with more than one slide, please [file an OpenSlide bug](https://github.com/openslide/openslide/issues/new).
