### ISSUE TITLE
Repeated operations and memory

### ISSUE THREAD

**Issue by mhirsch** [jcupitt/libvips#556]
I may be abusing vips with this application, so I apologize if this sounds a little odd. What I would like to do is create a vips pipeline that implements an iterative image processing algorithm, where a number of operations are executed repeatedly on the same image buffer. The problem I'm facing is that under some conditions the amount of memory used by vips explodes. I'd like to understand if this kind of thing is possible entirely within the vips pipeline or whether I have to run each iteration of the algorithm as a separate vips pipeline (e.g. write to a buffer inside the loop, below).

The algorithm itself is a little more complicated that what I'm showing here but this illustrates the problem I'm having. I'm using the C++ API.

In this example, an image is read in and repeated convolution is performed. Vips handles this very nicely and I get the expected result:

```
VImage in = VImage::new_from_file(input,VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );

in = in.cast(VIPS_FORMAT_FLOAT);

for(int i=0;i<50;i++) {
  in = in.conv(kernel);
}

in.pngsave("out.png");
```

In this example the memory usage increases until the processes is killed:

```
VImage in = VImage::new_from_file(input,VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );

in = in.cast(VIPS_FORMAT_FLOAT);

for(int i=0;i<50;i++) {
  in = in - in.conv(kernel);
}

in.pngsave("out.png");
```

**Comment by jcupitt** [comment]
Hi Matt, no, that's fine, vips is supposed to be used like this, there's no abuse.

Try swapping your `in - in.conv(kernel)` for `-conv(kernel) + in`. Magic!

It's to do with the way vips caches and reuses results. When it evaluates `subtract` it first builds the left-hand side, then the right-hand side, then does the subtract. In this case, the left side is the whole of the pipeline and the right side is also the whole of the pipeline, but with an extra convolution added to the end..

Suppose it's computing 100x100 pixels in the centre somewhere. First it'll calculate a 100x100 pixel area of the whole of the pipeline, then it'll ask `conv` for that same 100x100 pixel area. The convolution operator will need 102 x 102 pixels (assuming a 3x3 kernel), vips will look at the last few areas it calculated, see the 100x100 pixel region, but that's no good, it needs 102x102, so it'll calculate the entire pipeline again, but slightly larger. Because it ends up calculating twice for each node, your `x - conv(x)` will be O(2**n), where n is pipeline length. 

If you swap the order of the args to `subtract`, now it's doing the larger area first, so when it comes to calculate the RHS of the subtract, it already has the pixels ready, it won't need to calculate again. Now your complexity is O(n).

We're toying with something to make operators automatically choose the 'larger' side first, but it's not nailed down yet. Maybe 8.5 will do this kind of optimisation automatically.

I expect you know, but you can implement `x - conv(x)` with a single convolution if you adjust your kernel. I guess you did it this way to illustrate the problem.

**Comment by mhirsch** [comment]
Thanks very much for your comments. By ensuring that the larger image is always on the left side of binary operators I was able to get my iteration to run with finite memory! However, I suspect I am still doing some redundant calculation. In the case where I write the image out to a buffer after each iteration processing takes ~3m. When I run the entire pipeline at once it takes upwards of 10m. Is there some mechanism for understanding performance consequences? I've been playing with setting `VIPS_PROGRESS=1` but that only gives me limited insight.

During a convolution is there a way to tell vips that I only care about the central part of the image (for e.g. like passing `'same'` into `conv2()` in octave) so that it doesn't have to propagate the contribution of the edges through the entire iteration?

How expensive are `cast()` operations? I would love a way to run `linear()` and get an integer type back that's larger than `UCHAR`, and to be able to clamp an image to a range (e.g. values large than 255 set to 255) without casting to `UCHAR`.

I really appreciate this project -- this is such a powerful tool! Thank you.

**Comment by jcupitt** [comment]
Yes, vips doesn't cache much automatically. In batch processing it usually burns memory to no purpose. You can add explicit cache operators if you know you will be reusing a result a lot. 

For example, in Python your program could be:

```python
#!/usr/bin/env python

import sys
import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

Vips.leak_set(True)

kernel = Vips.Image.new_from_array([[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]])
im = Vips.Image.new_from_file(sys.argv[1], access = Vips.Access.SEQUENTIAL)
im = im.cast(Vips.BandFormat.FLOAT)

for i in range(1,int(sys.argv[3])):
    im = -im.conv(kernel) + im
    
im.write_to_file(sys.argv[2])
```

With a 5 stage pipeline I see:

```
$ time ./try252.py ~/pics/k2.jpg x.jpg 5
memory: high-water mark 41.64 MB
real	0m1.038s
user	0m3.640s
sys	0m0.032s
```

Which is pretty good, but if I try 50 stages, it's not so great:

```
$ time ./try252.py ~/pics/k2.jpg x.jpg 50
memory: high-water mark 730.82 MB
real	0m19.300s
user	1m10.772s
sys	0m0.324s
```

There's quite a bit of overcomputation now on edges, and all those intermediate buffers are beginning to add up. If I change the inner loop:


```python
for i in range(1,int(sys.argv[3])):
    im = -im.conv(kernel) + im

    new_image = Vips.Image.new_memory()
    im.write(new_image)
    im = new_image
```

So at each stage I write to a memory image and the pipeline is just invert/embed/conv/add, I see:

```
$ time ./try252.py ~/pics/k2.jpg x.jpg 5
memory: high-water mark 108.75 MB
real	0m1.075s
user	0m3.548s
sys	0m0.088s
```

About the same speed, but higher mem use. At 50 stages though:

```
$ time ./try252.py ~/pics/k2.jpg x.jpg 50
memory: high-water mark 108.75 MB
real	0m11.237s
user	0m39.312s
sys	0m0.912s
```

Memuse is constant, and now there's no recomputation on tile edges, so speed is up.

The downside of course if that you can no longer process very large images. 

`cast` is cheap, and `float` is hardly slower than `uchar` on modern machines. The only time you'll notice a large difference is with some operators like `conv` which have a special path for `uchar` images that's much, much faster.

```
$ more blur.con
3 3 9 1
1 1 1
1 1 1
1 1 1
$ time vips conv wtc.jpg x.jpg blur.con --vips-info
info: convi: using vector path
real	0m1.154s
user	0m2.532s
sys	0m0.076s
$ vips cast wtc.jpg x.v float
$ time vips conv x.v x2.v blur.con --vips-info
info: convi: using C path
real	0m6.062s
user	0m20.368s
sys	0m1.260s
```

Just do `linear` then `cast`, it should be quick. The `uchar` mode in `linear` is just there for screen output where you really do care about shaving every ms.

**Comment by mhirsch** [comment]
Just wanted to say thanks again for all your help with this. 

For my problem, the iteration involves a number of convolutions with intermediate operations, and thinking about this further, the tile-based dependency graph of vips is poorly suited to this type of problem. The redundant calculations caused by the convolution operation's spreading dependence on neighboring regions, over a reasonable number of iterations, will far outweigh the advantage of cache coherency in keeping processing local. In this case, it's probably better to write to intermediate temporary files if the problem exceeds the in-core size of the system rather than do the extra calculation. Lucky for me vips really is eminently flexible. Thanks again for this wonderful project and your really quick responses!

**Comment by jcupitt** [comment]
I'm blushing, thanks for your kind words. 

Yes, streaming isn't always the best solution. Long chains of non-local operations are a nightmare for all image processing systems :(

**Comment by jcupitt** [comment]
Hi again, automatic reordering has just landed:

https://libvips.blogspot.co.uk/2017/01/automatic-computation-reordering.html

The blog post uses your example, I hope that's OK. Thanks!

**Comment by mhirsch** [comment]
Very cool! Great feature and nice write-up! Thanks for letting me know.
