### ISSUE TITLE
Supported types

### ISSUE THREAD

**Issue by hey-red** [jcupitt/libvips#557]
It is possible to get a list of all supported types?

**Comment by jcupitt** [comment]
libvips uses GObject, so you use the GObject type system for introspection. The main docs are here:

https://developer.gnome.org/gobject/stable/index.html

It's simplest from Python. For example, this generates the C++ bodies for all vips operations:

https://github.com/jcupitt/libvips/blob/master/cplusplus/gen-operators.py

Or in Ruby, this finds all enums:

https://github.com/jcupitt/php-vips/blob/master/examples/generate_phpdoc.rb#L33

**Comment by hey-red** [comment]
@jcupitt This question about supported image formats 😋

**Comment by jcupitt** [comment]
Oh heh. You can do it at the command line if that works for you:

```
$ vips -l foreign
    VipsForeign (foreign), load and save image files, priority=0
      VipsForeignLoad (fileload), file loaders, priority=0
        VipsForeignLoadCsv (csvload), load csv from file (.csv), priority=-50, get_flags, get_flags_filename, header, load
....
```

`-l foreign` means list all classes below `foreign` in the class hierarchy. You can do it from C as well: 

https://github.com/jcupitt/libvips/blob/master/tools/vips.c#L160
