### ISSUE TITLE
Optional arguments

### ISSUE THREAD

**Issue by hey-red** [jcupitt/libvips#558]
What arguments supports vips_image_write_to_*()?
Any for vips_jpegsave/vips_pngsave... etc?

**Comment by jcupitt** [comment]
Exactly, `vips_image_write_to_file()` looks at the suffix, then picks a saver for you from the `VipsForeignSave` hierarchy. Any extra arguments are passed along to the saver.

**Comment by hey-red** [comment]
@jcupitt I'm trying to set thats arguments from C#, but get error on write function. 
How to get last error from error buffer?

**Comment by jcupitt** [comment]
`vips_error_buffer()` gets the whole error buffer, `vips_error_clear()` empties it.

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-error.html

**Comment by hey-red** [comment]
Oh, I'm used this function but miss what that char is a pointer 😌

**Comment by hey-red** [comment]
@jcupitt When i call vips_image_write_to_file(_image, path, "strip", true, "Q", 95, null) gets error: 
`jpegsave: no property named '`
This is correct arguments?

**Comment by jcupitt** [comment]
Yes, that's right. What are `true` and `null`? Usually you'd use `TRUE` and `NULL`.

**Comment by jcupitt** [comment]
Sample code:

```C
/* compile with:
 *      gcc -g -Wall diuming8.c `pkg-config vips --cflags --libs`
 */

#include <vips/vips.h>

int
main( int argc, char **argv )
{
        if( VIPS_INIT( argv[0] ) )
                vips_error_exit( NULL );

        VipsImage *im;

        if( vips_black( &im, 1000, 1000, NULL ) )
                vips_error_exit( NULL );
        im->Xres = im->Yres = 720.0 / 25.4;
        if( vips_image_write_to_file( im, "image.tif",
                "compression", VIPS_FOREIGN_TIFF_COMPRESSION_LZW,
                "tile", TRUE,
                "squash", TRUE,
                "resunit", VIPS_FOREIGN_TIFF_RESUNIT_INCH,
                NULL ) ) {
                g_object_unref( im );
                vips_error_exit( NULL );
        }

        g_object_unref( im );

        return( 0 );
}
```

**Comment by jcupitt** [comment]
The varargs stuff is painful from other languages. I would do what the C++ interface does:

https://github.com/jcupitt/libvips/blob/master/cplusplus/VImage.cpp#L520

It uses `vips_foreign_find_load()` to find the load operation for the file, then executes that operation, passing the optional arguments in. No varargs needed!

`call_option_string()` makes the operation, sets any args codes as strings, then sets all of the supplied arguments.

https://github.com/jcupitt/libvips/blob/master/cplusplus/VImage.cpp#L459

The cpp interface has that ugly `VOption` thing, but that's just because it has to work with pre-C++11. You can make it much prettier with a modern C++ compiler. I'm sure C# would be better too.

**Comment by hey-red** [comment]
>What are true and null? Usually you'd use TRUE and NULL.
I'm using it from C#.
@jcupitt I can only call functions from dll. To use C ++ needs to write a wrapper. I think so.

**Comment by jcupitt** [comment]
Don't call C++, it won't work from C#, but you can call the C functions that the C++ is calling. Just rewrite the C++ in C#.

**Comment by hey-red** [comment]
Oh, it's really hard to implement. There is nothing difficult in creating operation, but set_property really
hard to implement.
There are no function like 
`int vips_image_write_to_file (VipsImage *image, const char *name, ...);`
but with this signature
`int vips_image_write_to_file (VipsImage *image, const char *name, const char *option_string);`
?

**Comment by jcupitt** [comment]
I'll see if I can make a simple example.

**Comment by jcupitt** [comment]
I found this old example program from years ago:

https://gist.github.com/jcupitt/6d5919e6adc540cef566a97cef05bdac

It walks the arguments of any vips operation. For example:

```
$ gcc -g -Wall introspect.c `pkg-config vips --cflags --libs`
$ ./a.out jpegload
jpegload:
required input arguments:
	filename
		Filename
		Filename to load from
		string - default = (null)
optional input arguments:
	disc
		Disc
		Open to disc
		bool - default = 1
	access
		Access
		Required access pattern for this file
		enum - values:
			0 - random (VIPS_ACCESS_RANDOM)
			1 - sequential (VIPS_ACCESS_SEQUENTIAL)
			2 - sequential-unbuffered (VIPS_ACCESS_SEQUENTIAL_UNBUFFERED)
		default = 0
	shrink
		Shrink
		Shrink factor on load
		int - min = 1, max = 16, default = 1
	fail
		Fail
		Fail on first warning
		bool - default = 0
	autorotate
		Autorotate
		Rotate image using exif orientation
		bool - default = 0
```

I'll make another example that calls `jpegload` from C.

**Comment by jcupitt** [comment]
Here's a simple example calling `jpegload`:

```C
/* compile with
 * gcc -g -Wall callvips.c `pkg-config vips --cflags --libs`
 */

#include <vips/vips.h>

int
main( int argc, char **argv )
{
	VipsOperation *op;
	GValue gvalue = { 0 };
	VipsImage *image;

	if( VIPS_INIT( argv[0] ) ) 
		/* This shows the vips error buffer and quits with a fail exit
		 * code.
		 */
		vips_error_exit( NULL ); 

	/* This will print a table of any ref leaks on exit, very handy for
	 * development.
	 */
	vips_leak_set( TRUE );

	if( argc != 3 )
		vips_error_exit( "usage: %s filename options", argv[0] );

	op = vips_operation_new( "jpegload" );

	/* Set arguments from an option string. The string has a syntax like:
	 *
	 * 	fail=true
	 * 	fail
	 * 	filename=banana.jpg
	 * 	access=sequential,fail
	 *
	 * optionally enclosed in square brackets. This is used by vips to
	 * implement the trailing arguments on filenames feature.
	 */
	if( vips_object_set_from_string( VIPS_OBJECT( op ), argv[2] ) ) {
		/* You need to call this before unreffing op!
		 */
		vips_object_unref_outputs( VIPS_OBJECT( op ) );

		g_object_unref( op ); 
		vips_error_exit( NULL ); 
	}

	/* Set the only required argument: the input filename.
	 */
	g_value_init( &gvalue, G_TYPE_STRING );
	g_value_set_string( &gvalue, argv[1] );
	g_object_set_property( G_OBJECT( op ), "filename", &gvalue );
	g_value_unset( &gvalue );

	/* Set an optional argument: the boolean "fail".
	 */
	g_value_init( &gvalue, G_TYPE_BOOLEAN );
	g_value_set_boolean( &gvalue, TRUE );
	g_object_set_property( G_OBJECT( op ), "fail", &gvalue );
	g_value_unset( &gvalue );

	/* Call the operation. This will look up the operation+args in the vips
	 * operation cache and either return a previous operation, or build
	 * this one.
	 */
	if( vips_cache_operation_buildp( &op ) ) {
		vips_object_unref_outputs( VIPS_OBJECT( op ) );
		g_object_unref( op );
		vips_error_exit( NULL ); 
	}

	/* Now get the result from op.
	 */
	g_value_init( &gvalue, VIPS_TYPE_IMAGE );
	g_object_get_property( G_OBJECT( op ), "out", &gvalue );
	image = VIPS_IMAGE( g_value_get_object( &gvalue ) );
	g_value_unset( &gvalue );

	g_object_unref( op );

	printf( "generated image %p\n", image );
	printf( "width = %d\n", image->Xsize );
	printf( "height = %d\n", image->Ysize );

	g_object_unref( image );

	return( 0 ); 
}
```

Run like this:

```
$ gcc -g -Wall callvips.c `pkg-config vips --cflags --libs`
$ ./a.out ~/pics/k2.jpg "fail"
generated image 0x563babb08020
width = 1450
height = 2048
```

**Comment by almosnow** [comment]
@jcupitt Dude! Thanks for the awesome library.

You need to put this bizarre (I know it's not your fault) way of adding optional arguments, **somewhere visible in the docs**!

I just spent 2+ hours trying to find the correct way to call vips_hough_line only to find (thanks to your example code) that it must be ("NAME", VALUE, ...)

Believe me, I even looked at libvips' source code and couldn't infer that was how it was suppossed to work.

**Comment by jcupitt** [comment]
Hi @almosnow, the optional args are supposed to be explained here:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/using-from-c.html

It runs through how the C API works. The "VIPS Operations" section covers optional arguments (and other things). Do you think it should be expanded? 

There's a little more detail here:

www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/VipsOperation.html#VipsOperation.description

**Comment by almosnow** [comment]
@jcupitt You're right, it **is** there.

I just kind of skimmed over it. And tried searching with Ctrl+F and "arguments" and found only an unrelated match, so I assumed it wasn't there.

Perhaps a little trivial change from:

>Operations can take options. You give these as a set of NULL-terminated ...

to

>Operations can take optional arguments. You give these as a set of NULL-terminated ...

would help people like me to find it with more ease.

Aside from that, I think the C walkthrough is particularly great, it's actually what I used to get started.

**Comment by jcupitt** [comment]
OK, looks like a useful change. Thanks!

**Comment by cr-solutions** [comment]
I have a similar problem with "vips_image_write_to_file"
I like to implement libvips via FFI in PHP

reading an image and resize ....
looks good, but after I like to save the resized image via "vips_image_write_to_file"
I get the following error from "vips_error_buffer"

`jpegsave: no property named `'`

what this error mean?

**Comment by jcupitt** [comment]
Hello @cr-solutions,

Could you open a new issue, please? Include some sample code to show what you are executing to get this error.

I would look at ruby-vips, pyvips or lua-vips to get ideas on the best way to call libvips from FFI. There's also a chapter in the docs, perhaps you saw:

https://libvips.github.io/libvips/API/current/binding.md.html
