### ISSUE TITLE
Question: Generation time of DZI vs Zoomify

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#559]
Intuitively, I'd say zoomify would be faster to generate as it stops at a single tile rather than a single pixel for DZI. Is that actually going to be true given the code? Is there something inherently faster about either method?

**Comment by jcupitt** [comment]
The last few layers of DZI are extremely small, so I don't think they take any significant amount of time. 

Zoomify uses and old and strange directory layout dating back to when it was very slow to have more than 256 files in a directory on Windows. DZI is more modern and simpler to work with. Google maps layout is simpler and more modern again.

**Comment by harukizaemon** [comment]
Yeah right. I just switched to using Zoomify from DZI - because with DZI on some of the images I'm displaying (eg 200,000 x 200,000) anything smaller than a tile size is never used and takes hours to generate. I had to write my won OpenSeadragon plugin to support Zoomify anyway - so I guess I should look at the Google format and write a plugin for that instead.

**Comment by harukizaemon** [comment]
Do you have a link to the format? I couldn't find anything particularly helpful. I used VIPS to generate a layout and AFAICT it's basically `z/x/y.suffix`?

**Comment by jcupitt** [comment]
Yes, it's very simple. The only wrinkle is that tiles can be missing: if the viewer can't find `thing/z/y/x.jpg` it should display `thing/blank.png` instead. It works well for microscopy slides where you often have large white areas. 

Oh dear, 200,000 x 200,000 shouldn't take hours to generate. Are these jp2k compressed images? That might be your bottleneck. If you're running on Windows, filesystem output is very slow and you should use zip instead.

**Comment by jcupitt** [comment]
Or rather, the viewer should always display `blank.png` everywhere, and layer real tiles on top as they come in.

**Comment by harukizaemon** [comment]
It's running on CentOS 7 but it's shared hardware. I'm waiting to get some new dedicated hardware so I'll see how long it takes on that. At any rate, just using Zoomify saved me considerable disk space so it was worth it for that. I'll trying switching to the Google Maps layout using `blank.png` as you suggest. Thanks!

**Comment by jcupitt** [comment]
You'll find zip output can save space on *nix as well. Tiles are typically ~2kb, so if each one is in a separate disk block, you're actually using 4kb per tile. An uncompressed zip is just all the tiles run together in a single file, so you can write a little JS as part of your viewer to scan the index off the end of the file, then use http RANGE to pull out sections of the zip for each tile. zips are also slightly easier to manage than massive trees of tiles. 

I think some file systems will put small files together into the space at the end of blocks, though I don't know if ext does this.

**Comment by harukizaemon** [comment]
Nice! Good idea. So would you suggest NOT using Google Maps layout?

Also, I've been using an overlap of `0`. I couldn't think of any reason to have an overlap :/

**Comment by jcupitt** [comment]
I think the overlap can be handy if you are doing fractional zooming, and deepzoom requires it, but I've never needed it myself. 

I like the GM layout, and the blank thing can be a good space-saver, but I doubt if it'll make much difference to performance or to generation time. Generating a GM layout will be slightly slower since vips has to test every tile to see if it's blank.

**Comment by harukizaemon** [comment]
Ahh, right! Hmm. Sounds like I might end up going back to DZI after all LOL. Guess I should wait to see how it performs on real hardware.

**Comment by jcupitt** [comment]
I tried on my desktop and the differences don't seem huge. This is for a 120k x 100k jp2k-compressed image:

```
$ time vips dzsave 2013_09_20_29.ndpi x --vips-progress
real	5m55.519s
user	27m45.992s
sys	10m36.628s
$ time vips dzsave 2013_09_20_29.ndpi x --vips-progress --layout zoomify
real	5m53.820s
user	27m55.384s
sys	10m39.632s
$ time vips dzsave 2013_09_20_29.ndpi x --layout google
real	6m19.164s
user	30m29.580s
sys	12m43.128s
```

**Comment by jcupitt** [comment]
My desktop is a fairly old 6-core (12 thread) i7.

**Comment by harukizaemon** [comment]
Right. I guess it might just be the shared infrastructure that's killing it. I also have it throttled to a single thread - again because of the shared infrastructure. Once I get some real hardware I'll try it again.

**Comment by harukizaemon** [comment]
I like the Google layout as well - now that I've looked at it. The Zoomify is whacky given the 256 file limit but it seems to work ok and I like that it doesn't generate all those extra layers. But the Google seems the simplest. The real hardware will be minimum dual-cpu 20-core.

**Comment by harukizaemon** [comment]
> I think the overlap can be handy if you are doing fractional zooming, and deepzoom requires it, but I've never needed it myself.

What did you mean by "fractional zooming"?

**Comment by harukizaemon** [comment]
> Or rather, the viewer should always display blank.png everywhere, and layer real tiles on top as they come in.

So my OSD plugin probably needs to therefore ensure `404 Not Found` is handled gracefully?

**Comment by jcupitt** [comment]
In the viewers I've written, you load tiles with something like:

```javascript
    var img = new Image();
    img.src = url;
    img.onload = function () {
...
    };
```

So in `onload()` you just need to test for an error before attaching it to the canvas. If there's an error, do nothing.

**Comment by harukizaemon** [comment]
Don't think there's any reason to keep this open. As usual, thanks for your time! I will have more questions, I'm sure.

**Comment by harukizaemon** [comment]
Haha, so having just closed it I did have another question. I looks as though the Google Maps tiles are always the full tile-size - unlike eg DZI and Zoomify which clip partial tiles?

**Comment by jcupitt** [comment]
Yes, gmap tiles are always full size. dzsave has an option to centre the image, which can look a bit nicer.

**Comment by harukizaemon** [comment]
Thanks. I'll try the centre options however I think it'll also need some way to hook in to OpenSeaDragon to change the way it renders the tiles (see https://github.com/openseadragon/openseadragon/issues/1083).

Out of curiosity, did you roll your own rendering? OSD is handy but more and more I'm finding I want/need to do things "my way" :)

**Comment by jcupitt** [comment]
Couldn't you just tell OSD that your image is 512x512, even though it's really a centred 300x300?

I made a viewer for ptm pyramids:

https://github.com/jcupitt/iipmooviewer

Try dragging the lightbulb in the demo. But I've generally used openseadragon.

**Comment by harukizaemon** [comment]
You, sir, are a genius and that'll teach me to do stuff late at night!
