### ISSUE TITLE
vips magick temporary file 

### ISSUE THREAD

**Issue by juyunsang** [jcupitt/libvips#563]
Hi
When I Use Libvips , I Saw big size magick-xxx file ex) (/tmp/magick-ZiQ4bHzr, /tmp/magick-kbxeTn8C)
I heard that Libvips use Magick++ 
I want to store Magick++ temporary File in specific directory.

Vips use environment variable TMPDIR as temporary directory 
If is set environment variable TEMPDIR -> /home/juyunsang , big size magick file store in /home/juyunsang?

Please Reply

**Comment by jcupitt** [comment]
Sorry, I don't know. You will need to look at the imagemagick documentation to find out how to control the imagemagick temporary file. 

What kind of file are you trying to load? Perhaps there is another way to load it?

**Comment by juyunsang** [comment]
Thank you for reply
No I want to store temporary magick file another path.
when imagemagick using vips make very big size(2~3Gb) magick-xxxx file in /tmp
io of disk mounted /tmp hit 100% , so system couldn't write /tmp, instance will be down.
imagemagick executable file `convert` has this option link registry:temporary-path=/home/juyunsang.
i'm not using vipsthumbnail , i write my vips executable file using vips c library.
how to fix temporary path using vips c library like registry:temporary-path=/home/juyunsang.

**Comment by jcupitt** [comment]
This suggests `MAGICK_TEMPORARY_PATH`, does that work?

http://stackoverflow.com/questions/27458437/make-imagemagick-use-external-hdd-for-temporary-files

What kind of file are you loading?

**Comment by jcupitt** [comment]
I'll close. Please reopen if this problem is not resolved.
