### ISSUE TITLE
Access violation in vips_image_write_to_file, am I freeing the resources correctly?

### ISSUE THREAD

**Issue by izhbq412** [jcupitt/libvips#565]
I'm trying to make mipmap images for moderately large (10k x 10k) TIFF images. I'm doing it in a pretty simple (and maybe naive) way, somewhat like this:

```
shared_ptr<VipsImage> m_pImage( vips_image_new_from_file( filePath, NULL ), FreeGObject() );

   shared_ptr<VipsImage> pDestImg( vips_image_new(), FreeGObject() );
   if( !pDestImg )
      RaiseVipsError();

   if( vips_image_write( m_pImage.get(), pDestImg.get() ) )
      RaiseVipsError();

   int level = 0;
   VipsImage* temp;
   shared_ptr<VipsImage> mipLevel;

   do
   {
      // ... some code to calculate xOffset, yOffset

      if( vips_resize( m_pImage.get(), &temp, 1.0 / (1 << level), NULL ) )
         RaiseVipsError();
      mipLevel.reset( temp, FreeGObject() );

      if( vips_insert( pDestImg.get(), mipLevel.get(), &temp, xOffset, yOffset,
                            "expand", TRUE, NULL ) )
         RaiseVipsError();
      pDestImg.reset( temp, FreeGObject() );

      // some more code... calc next width, height, level...
   }
   while (width >= 1 && height >= 1);

   if( vips_image_write_to_file( pDestImg.get(), destination, NULL ) )
      RaiseVipsError();
```

`FreeGObject()` is a simple functor that calls `g_object_unref` of the pointer if it's not NULL.

I get an access violation in libvips-42.dll  - appears to be inside vips_tracked_free, during the call to vips_image_write_to_file.

The algorithm above is supposed to vips_insert smaller (`vips_resize`-ed) images based on the original image (m_pImage) in a specific location inside pDestImg, expanding it as needed. Now, as far as I understood, vips_insert gives me a new image every time I call vips_insert, so I free the old pDestImg with g_object_unref and replace it with the one I got from vips_insert. Is this correct? Same question regarding vips_resize.

I tried commenting out the calls to g_object_unref, because I thought that maybe I'm freeing an object that's still required, but I still get this error.

This code runs in a loop for different images. The access violation happens during the second iteration - the first time everything is ok.

Any idea what's going on?

I'm using version 8.1.1-1, 32-bit.

PS: Both the input and output files are TIFFs.
PPS: Looking at the decompiled assembly, vips_tracked_free receives a NULL pointer and crashes when it attempts to subtract 0x10 from it.

**Comment by jcupitt** [comment]
Hello, sorry for the delay in responding.

Sorry, I'm not sure what's going on in your code. Could you post a complete example I could try running? My guess would be you have too many unrefs. 

Yes, `tracked_malloc()` and `tracked_free()` save the size of the malloc in the previous 16 bytes. libvips uses this to estimate resource use, so it knows when to start dropping cache entries. You can see the code here:

https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/memory.c#L227

It's only used internally by vips, and only for "large" objects, so the 16 bytes overhead doesn't matter.  

libvips has a C++ API here, you probably saw:

https://github.com/jcupitt/libvips/tree/master/cplusplus

I think I would build that for Windows, then use that interface. This is how the node.js libvips binding works on Windows. 

Alternatively, it has a simple thing to do all the ref/unref stuff for you:

https://github.com/jcupitt/libvips/blob/master/cplusplus/include/vips/VImage8.h#L52

You're very welcome to copy-paste that class into your code if you like.

**Comment by jcupitt** [comment]
I'll close. Please reopen if this problem is not resolved.
