### ISSUE TITLE
Segmentation fault, very large tiff

### ISSUE THREAD

**Issue by PeterJackNaylor** [jcupitt/libvips#566]
Hi,

I have a problem that I don't seem to understand how to fix...
My goal is to take a very large tiff, and overlay a given segmentation on it. To do this, I perform three step:
- cutting up the large tiff into smaller tiff images (224 x 224) (about 8024 images) with openslide
- overlay my segmentation on these small tiff images with different software. 
(NB: for the code part, each image is saved under this format: "x_y.tiff" where x and y are the positions in the original tiff, and are stored in our folder called ./small_tiff/)
- I reconstruct the image via vips.

The reconstruction parts doesn't work, it fails when I ask for more than 1000 images. For less then a 1000 the process runs and gives me satisfactory results. However, I would like to do this with the 8000 images.

I get two types of errors:
Segmentation fault (core dumped) 

Or :
```

  TIFFOpen: small_tiff/13280_11744.tiff: Too many open files
tiff: unable to open "small_tiff/13280_11744.tiff" for input
tiff2vips: unable to open "small_tiff/13280_11744.tiff" for input
TIFFOpen: small_tiff/13056_11744.tiff: Too many open files
tiff: unable to open "small_tiff/13056_11744.tiff" for input
tiff2vips: unable to open "small_tiff/13056_11744.tiff" for input
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
TIFFOpen: small_tiff/13504_11744.tiff: Too many open files
tiff: unable to open "small_tiff/13504_11744.tiff" for input
tiff2vips: unable to open "small_tiff/13504_11744.tiff" for input
VipsRegion: valid clipped to nothing

```

Is this a problem with the number of opened images that happens in the background of vips? I have tried several things that I found here to increase this limit: https://easyengine.io/tutorials/linux/increase-open-files-limit/ 

I have also tried playing around with different compression formats thinking that it may be due to memory reasons but unsuccessfully.

Here is the code I use, it is quiet straightforward and  is based on the code given by jcupit in https://github.com/jcupitt/libvips/issues/354.

Here is the code:

``` python


import sys
import openslide
from gi.repository import Vips

if len(sys.argv) < 3:
    print "usage: %s n image-out image1 image2 ..." % sys.argv[0]
    print "   make an n x n grid of images"
    sys.exit(1)

slide_name = "/home/pnaylor/Documents/temp_image/576041.tiff"
size_x, size_y = openslide.open_slide(slide_name).dimensions

outfile = sys.argv[1]

img = Vips.Image.black(size_x, size_y)

i = 2
val = min(len(sys.argv), 1020)
for i in range(2, val):
	if i % 1000 == 0:
		print "{} / {}".format(i, len(sys.argv))
	tile = Vips.Image.new_from_file(sys.argv[i], 
	                                access = Vips.Access.SEQUENTIAL_UNBUFFERED)
	_x, _y = sys.argv[i].split('.')[0].split('/')[-1].split('_')
	img = img.insert(tile, int(_x), int(_y))

img.tiffsave(outfile, tile=True, pyramid=True, bigtiff = True)
```

Here our also my configuration for vips under ubuntu 16.04:

``` bash

native win32:				no
native OS X:				no
open files in binary mode: 		no
enable debug:				no
build deprecated components:		yes
build docs with gtkdoc:			no
gobject introspection: 			yes
build vips7 Python binding:		yes
install vips8 Python overrides:		yes
  (requires pygobject-3.12.0 or later)
build radiance support: 		yes
build analyze support: 			yes
build PPM support: 			yes

* optional dependencies
use fftw3 for FFT: 			yes
Magick package: 			MagickCore
file import with libMagick: 		yes (magick6)
accelerate loops with orc: 		no
  (requires orc-0.4.11 or later)
ICC profile support with lcms: 		yes (lcms2)
file import with OpenEXR: 		yes
file import with OpenSlide:		yes
  (requires openslide-3.3.0 or later)
file import with matio: 		no
PDF import with poppler-glib: 		no
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0: 		yes
  (requires librsvg-2.0 2.34.0 or later)
zlib: 					yes
file import with cfitsio: 		no
file import/export with libwebp:	no
  (requires libwebp-0.1.3 or later)
text rendering with pangoft2: 		yes
file import/export with libpng: 	yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
file import/export with libtiff:	yes (pkg-config libtiff-4)
file import/export with giflib:		no
file import/export with libjpeg:	yes
image pyramid export:			yes
  (requires libgsf-1 1.14.27 or later)
use libexif to load/save JPEG metadata: ye

```

the code here doesn't work when val is equal or more to 1200 but works when val is under 1100?
Any help would be really appreciated! 

Thanks,

Peter

**Comment by PeterJackNaylor** [comment]
Hi,
I fixed this, it was the file limit, https://coderwall.com/p/ptq7rw/increase-open-files-limit-and-drop-privileges-in-python . Sorry for the lonely comments.
Peter

**Comment by jcupitt** [comment]
Hi Peter, glad it's working. 

If your images are in a regular grid, I'd use `arrayjoin`:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-arrayjoin

Open all of your input images into a Python array, then call `arrayjoin` giving the number of tiles across. It can join any number of images and needs much less memory than many nested `insert` calls.

You can use vips to quickly chop an image into tiles too. `dzsave` has an option to set the pyramid depth. Set it to 1 and it'll just slice your image into a single layer of tiles. It's very fast.

**Comment by PeterJackNaylor** [comment]
Hi,
Thank you for the advice and I have checked them out but not all of it suits my needs (but maybe?).
I wanted to do some chop into overlapping tiles (which I found in dzsave) but however we cannot merge with a specific condition while the overlapping? (like averaging the overlapping tiles, or taking the max).

I have also had another problem with very larges tiffs, here I was trying to stick together more then 70000 224x224 images and this results in a segmentation error. (but if I force the merge to only do half it works!). So my questions is, how does vips forecast the space/cpu usage before joining? (as it seems not to even try to merge them)..

Thanks again,

Peter

**Comment by jcupitt** [comment]
You'd need to make your own merge id you need some kind of custom join. It's not too hard: extract the overlap in both, perform some calc, join them all up with `insert`. It'd just be a few lines of Python or whatever.

vips has a built-in thing to do a feathered join, would that be useful? 

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-mosaicing.html#vips-merge

It just joins two images, so you'd do repeated left-right joins to make a row, then repeated top-bottom joins to assemble the rows. It's fine for up to 1,000 or so images, it gets a bit slow beyond that. It can handle transparency and irregular image mosaics.

**Comment by jcupitt** [comment]
Ooop, I missed part 2.

Wow, 70,000 images is a lot. Yes, I'd expect you to have to assemble that in sections. Use vips format for intermediate images, it's fast and will keep all the state and metadata.

Yes, vips works in quite a few layers and passes. When you call `image.join()` or whatever, it's not doing any processing, it's just building a large graph. When you write to the output, it walks the graph and constructs a lower-level lightweight tree representation, one for each thread of execution. When evaluation proper starts, a third layer is built, this time a graph again, and it's this layer that does memory allocation. It takes a few tiles for everything to settle down, but after that the whole thing should run with no more mallocing.
