### ISSUE TITLE
Problems with VIPS objects un-referencing in 8.4.2

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#568]
I am observing issues related to objects reference counting with VIPS 8.4.2 in my PhotoFlow application.

All works fine with 8.4.1, while the same code consistently crashes with 8.4.2. However, as PhotoFlow creates a quite large number of operations even for relatively simple processing configurations, it is quite hard for me to debug the problem and locate the exact origin of the problem...

Do you have any suggestion for debugging the reference counting? Has something been changed in the way VIPS raises/lowers the reference counting of operations and other objects? 

Thanks!

**Comment by jcupitt** [comment]
Hi @aferrero2707, the big 8.4.2 change was this one:

https://github.com/jcupitt/libvips/issues/535

It was a complicated race condition in thread shutdown. Could that be related to the crashes you are seeing?

8.5 (git master libvips) has this bit of hairy code rewritten and it should be simpler and safer. Could you test photoflow against git master? If it works with that, I think we can probably conclude that this thread shutdown issue behind your crashes too. 

I think that would mean we'd have to backport the new buffer code to 8.4 and do a 8.4.6 with the fix :( but let's cross that bridge when we reach it.

Reference counting bugs are the worst. My approach has been:

1. Make the smallest test case I can.

2. Use `vips_object_print_all()` to dump a summary of all objects and their counts to a file at a point where I know counts are sane.

3. Step to the point where I know counts have gone bad, and dump again.

4. `diff` the two dumps and try to relate count changes there to things I think the program should or should not have done.

5. Adjust points 2. and 3. and try again, homing in on the bad count change.

The best solution of course is simply to never touch reference counts. Do all that stuff in a small, easily testable layer somewhere (like VObject in the C++ bindings), and never change counts in your main code.

**Comment by aferrero2707** [comment]
My code seems to work fine with latest git master from today... I still do not have any idea what was causing the crashes with 8.4.2... I will eventually run some more tests when I will have some spare time.

Incidentally, I also noticed a bunch of error messages from ```vips_shutdown()```, that I do not remember having seen in the past:

    error buffer: vips_sink: stop function failed for image "temp-360"
    vips_sink: stop function failed for image "temp-360"
    vips_sink: stop function failed for image "temp-360"
    vips_sink: stop function failed for image "temp-360"
    vips_sink: stop function failed for image "temp-441"
    vips_sink: stop function failed for image "temp-441"
    vips_sink: stop function failed for image "temp-441"
    vips_sink: stop function failed for image "temp-441"
    threads: 1 still active
    PhotoFlow::close(): vips shutdown done

Any idea of what I could be doing wrong, or if this is harmless?

Thanks!

**Comment by jcupitt** [comment]
`vips_shutdown()` now displays checks the error buffer and displays any messages in there. I found I'd never noticed a few errors. 

Sorry, I don't know exactly what the problem could be. The `stop function failed` means that the image processing operations that generated `temp-360` is returning non-zero from sequence stop, but I guess not setting an error. It's probably harmless, but I'd look into it. 

`threads: 1 still active` looks worse. It counts vips threads created versus vips threads joined, and it sounds like a join hasn't happened. Are you using `vips_sink_screen()`? That makes some extra background threads.

**Comment by aferrero2707** [comment]
Indeed, PhotoFlow's image preview is entirely based on ```vips_sink_screen()```... is there something special I should do to stop it properly, apart from de-referencing all VipsImage objects?

**Comment by jcupitt** [comment]
Just unreffing the images will be enough. I was only trying to think of operations which made extra threads.

**Comment by aferrero2707** [comment]
But then I do not understand why ```vips_shutdown()``` does not report any images/operation still alive, and at the same time it reports one thread that is still active... probably a minor issue, but I just want to make sure I am not messing with reference counting somewhere...

Thanks!

**Comment by jcupitt** [comment]
Yes, I'm puzzled too. Maybe try adding `sleep(10)` just before `vips_shutdown()`. If the message goes away, you've probably found a race condition :(

**Comment by aferrero2707** [comment]
Some progress on this: the ```stop function failed for image``` messages were due to an error from my side, I was basically using the wrong return value for the stop functions in my code... so we can consider this solved.

Concerning the thread that is reported as being still active, adding some extra sleep before ```vips_shutdown()``` does not solve the problem. I am trying to figure out if the problem comes from my own code, before we start checking the VIPS side... I'll drop a message here as soon as I have some conclusive result.
