### ISSUE TITLE
Split multiframe tiff into seperate files 

### ISSUE THREAD

**Issue by freddy31** [jcupitt/libvips#569]
Is it possible to split a tiff file into seperate image files from the command line?

**Comment by jcupitt** [comment]
Hi @freddy31, you can pull out single pages with:

```
$ vips copy manypage.tif[page=12] x.jpg
```

You can obviously make a loop if you need all pages. 

libvips master has a new feature: it supports "toilet roll" images. You can read out many pages as a long strip, provided they are all the same size:

```
$ vips copy manypage.tiff[page=2,n=5] x.jpg
```

Will read 5 pages, starting at page 12. It works for gif and pdf too, and for many-page tiff write.

**Comment by freddy31** [comment]
Hi, thanks for the reply.

If i were to make a loop, how would i be able to find out how many frames the file has?

**Comment by jcupitt** [comment]
You can test the exit status of the command: it'll fail when a page does not exist. In bash, for example:

```
$ i=0
$ while vips copy x.tif[page=$i] y$i.tif; do ((i++)); done
tiff2vips: TIFF does not contain page 5
$ ls
x.tif  y0.tif  y1.tif  y2.tif  y3.tif  y4.tif
```

**Comment by jcupitt** [comment]
I'll close. Please reopen if this problem is not resolved.

**Comment by urmilas239** [comment]
Hi, A related Question. How can I find out in vips the number of level in a multipage tiff? I am looking forimagemagick's "identify -verbose '%n' imagename.tiff" would return , using vips. Thanks.

**Comment by jcupitt** [comment]
See https://github.com/jcupitt/libvips/issues/779
