### ISSUE TITLE
libvips load average issue

### ISSUE THREAD

**Issue by juyunsang** [jcupitt/libvips#572]
Good morning
I have an anomaly while using libvips.
I use the libvips c library to create a jpeg thumbnail with my executable file, while the cpu usage drops during the thumbnail creation and the load average suddenly increases so the instance becomes inoperable
I will email you my code if you wish.
please reply

**Comment by jcupitt** [comment]
Hello @juyunsang,

libvips tries to create many threads to speed operation, but this can be a problem in some machines. Try limiting libvips to a single thread. Add:

```C
vips_concurrency_set(1);
```

Somewhere near the start of your program.

**Comment by jcupitt** [comment]
Hi again, did you make any progress with this. I'd be happy to have a look at your code if you like.

**Comment by juyunsang** [comment]
Limiting the number of concurrent threads has been fixed.
Thank you.
What is the default thread creation limit within libvips?

**Comment by jcupitt** [comment]
It starts one thread for each hardware thread you have.

**Comment by juyunsang** [comment]
Fixed issue with limiting to one vips thread.
Thank you for answer.
