### ISSUE TITLE
Create 3 bands 'main' VipsImage as a container for 'sub' VipsImages objects

### ISSUE THREAD

**Issue by alonit** [jcupitt/libvips#575]
Hi,

At run-time I do a mosaic of 3 bands (RGB model) images into VipsImage object so that at the end of the mosaic process I have numerous 3 bands VipsImage objects at hand each represent different map region. In this phase I want to insert these map regions (mosaic VipsImage objects) into a single global VipsImage which contain the regions, where each region located at its (x,y) position in the global VipsImage.

I found that:

```
vips_insert (VipsImage *main,
             VipsImage *sub,
             VipsImage **out,
             int x,
             int y,
             ...);
``` 

could fit, but I first need to create `main` image as a 3 bands image with a specific background color (black would not fit for me for all use cases) so that the main image can hold the 3 bands `sub` images ?

What is the best/recommended way (in terms of performance) of doing insertion of sub images (3 bands in my case) to a single global image? and How to set the required background color for the `main `image

Thanks a lot in advanced.

**Comment by jcupitt** [comment]
Hi, to make your huge image, make a single pixel of the colour you need, then use `embed` to blow it up to the size you want. In Python:

```python
pixel = (Vips.Image.black(1, 1) + [2, 3, 4]).cast("uchar")
image = pixel.embed(0, 0, 100000, 100000, extend = Vips.Extend.COPY)
```

Will make a 100,000 x 100,000 pixel 8-bit RGB image where each pixel has the value (2, 3, 4).

Just use `insert` to paste your sub-images into that.

**Comment by alonit** [comment]
Oh, Thanks.

Is the `+` operator you used in the example above is supported in Vips C API?
It will be appreciated if you please set an example such as above in C, as I'm using the Vips C API. 

Thanks again.

**Comment by jcupitt** [comment]
Here's a gist that should answer your question:

https://gist.github.com/jcupitt/0905c5a2178f6c62b373f40703b39d34
