### ISSUE TITLE
How to set the background color of a mosaic ?

### ISSUE THREAD

**Issue by alonit** [jcupitt/libvips#576]
Hi,

I am using `vips_mosaic` to mosaic given images. Due to camera alignment and probably other factors, the resulted mosaic image outer frame has a black color strip. for example:

The by-product black background of a mosaic (in red circle):

![mosaic_alignment](https://cloud.githubusercontent.com/assets/21310386/21470572/94e650a8-ca97-11e6-95ac-77ba52fd39ec.png)

Is there a way to set desired background color for a mosaic - this will help smooth the real mosaic image data from the by-product alignment and from other mosaic missing's?

Thanks!

**Comment by jcupitt** [comment]
Hi again, `mosaic` uses pixel value 0 to mean transparent. I would add one to all my source images (or maybe OR with 1?) to make sure they have no accidental transparent areas, then after mosaicing, use `== 0` to find the transparent parts and swap them for whatever you want. 

In Python, something like (untested):

```python
# OR with 1 to make sure there are no zeros
left = Vips.Image.new_from_file("left.tif") | 1
right = Vips.Image.new_from_file("right.tif") | 1

joined = left.mosaic(right, "horizontal", 0, 0, 200, 0)

# find transparent pixels ... we want all bands == 0, so AND the mask
# bands
mask = (joined == 0).bandand()

# use the mask to pick images from the background or the mosaic
out = mask.ifthenelse(bg_image, joined)
```

**Comment by alonit** [comment]
Thanks for the fast reply. 

Sorry but I forgot to tell you that I'm using the Vips C API. Can you please show an example in Vips C API as I'm not sure about the C version of your Pyton example.

Thanks again.

**Comment by jcupitt** [comment]
I made a gist for you:

https://gist.github.com/jcupitt/0905c5a2178f6c62b373f40703b39d34

It should answer your other issue too.

**Comment by alonit** [comment]
Thanks. I tried your gist on my machine (Vips 8.4 C API on Windows 7) and encounter the followings:
1. `const_image` method works fine 
2. `join` : all goes well until calling the `vips_ifthenelse( t[7], t[5], t[4], &t[8], NULL )` line in which return error (-1) with `cError = 0x0000000069fc4840 "ifthenelse: no property named `¸Uãëþ\a'\n"`

Parameters status before calling to `vips_ifthenelse`

t[7]: 
![image](https://cloud.githubusercontent.com/assets/21310386/21520464/20519550-ccfd-11e6-992d-e5a925431e3a.png)

t[5]:
![image](https://cloud.githubusercontent.com/assets/21310386/21520484/44c406e8-ccfd-11e6-8d22-ca34b9171f19.png)

t[4]:
![image](https://cloud.githubusercontent.com/assets/21310386/21520512/709bea06-ccfd-11e6-84f1-2af26692e546.png)

t[8]:
![image](https://cloud.githubusercontent.com/assets/21310386/21520535/a7e0fb1e-ccfd-11e6-97dd-e697cb4163f3.png)


Do you have idea about what could go wrong with this ?

Many thanks.

**Comment by alonit** [comment]
Oh, sorry, I forgot to insert NULL at the end of parameter chain when calling to `vips_ifthenelse` - this cause the failure I described above.

So, your gist works well on my machine. Thanks a lot :+1: 

I wonder if I can remove the by-product mosaic background without changing the overall original mosaic image values. I have to process the resulted stitched image without doing any modification on it, as any modification (such as changing pixel from zeros to ones) have the potential of changing image processing algorithm results hence consistency is not preserved as desired.

Thanks in advanced.

**Comment by jcupitt** [comment]
Glad it works!

Is there a compiler flag to warn about missing NULLs? gcc has one anyway. 

You could add one, do the mosaic, then subtract one again, that would be a simple way to avoid any modification.
