### ISSUE TITLE
Webp lossless vs lossy compression on an indexed color PNG image

### ISSUE THREAD

**Issue by rnanwani** [jcupitt/libvips#578]
This might not be the right medium to ask as the question is more related to webp than to vips. But understanding the webp part would help understand the part of functionality in vips.

![fast-delivery](https://cloud.githubusercontent.com/assets/4739557/21758105/22272f74-d65e-11e6-8732-3e7b787750de.png)
Link - https://drive.google.com/open?id=0B3CnCQhw6PquaGYxNHF4ZC1aczA

This image is compressed using TinyPNG and uses an indexed colour palette in PNG and is about 21.4KB in size. If I use `vips copy` or `cwebp` to convert from PNG to WebP, the output size is 34KB. 

However, if I use `cwebp -lossless` to convert the PNG to WebP, then the output size is almost equal to that of the original PNG (slightly more at 21.5KB). How is the lossless conversion able to provide more compression than lossy mode? Is it because WebP lossless uses indexed color palette while lossy mode doesn't as indicated here https://developers.google.com/speed/webp/docs/compression#color_indexing_palettes_transform.

Here is the output from the two `cwebp` commands

```
cwebp origina.png -o origina_cwebp.webp
Saving file 'origina_cwebp.webp'
File:      origina.png
Dimension: 1263 x 1020 (with alpha)
Output:    34916 bytes Y-U-V-All-PSNR 47.53 45.09 45.20   46.58 dB
block count:  intra4: 880
              intra16: 4176  (-> 82.59%)
              skipped block: 3964 (78.40%)
bytes used:  header:            368  (1.1%)
             mode-partition:   4859  (13.9%)
             transparency:     5276 (99.0 dB)
 Residuals bytes  |segment 1|segment 2|segment 3|segment 4|  total
    macroblocks:  |       1%|      10%|       7%|      80%|    5056
      quantizer:  |      36 |      36 |      32 |      23 |
   filter level:  |      11 |       9 |       6 |       3 |
Lossless-alpha compressed size: 5275 bytes
  * Header size: 54 bytes, image data size: 5221
  * Lossless features used: PALETTE
  * Precision Bits: histogram=5 transform=5 cache=0
  * Palette size:   21

```

```
cwebp -lossless origina.png -o origina_cwebp_lossless.webp
Saving file 'origina_cwebp_lossless.webp'
File:      origina.png
Dimension: 1263 x 1020
Output:    21518 bytes
Lossless-ARGB compressed size: 21518 bytes
  * Header size: 510 bytes, image data size: 20983
  * Lossless features used: PALETTE
  * Precision Bits: histogram=5 transform=5 cache=1
  * Palette size:   70
```

**Comment by jcupitt** [comment]
Hi @rnanwani,

I don't know much about webp, but yes, for some image content, especially where there are large areas of flat colour, a losslessly-compressed image will be smaller than a lossilly-compressed image. For example, using your test image:

```
john@kiwi:~/pics$ vips copy tiny.png x.jpg
john@kiwi:~/pics$ vips copy tiny.png x.png
john@kiwi:~/pics$ ls -l x*
-rw-r--r-- 1 john john 66772 Jan 10 10:07 x.jpg
-rw-r--r-- 1 john john 63263 Jan 10 10:07 x.png
```

And that's without palette-ization. Obviously for a photographic source, the situation will reverse.

I see slightly better webp numbers than you, interestingly:

```
$ cwebp -lossless tiny.png -o tiny.webp
Saving file 'tiny.webp'
File:      tiny.png
Dimension: 1263 x 1020
Output:    19184 bytes
Lossless-ARGB compressed size: 19184 bytes
  * Header size: 407 bytes, image data size: 18752
  * Lossless features used: PALETTE
  * Precision Bits: histogram=5 transform=5 cache=0
  * Palette size:   70
```

I have webp 0.5.1.

**Comment by rnanwani** [comment]
Yes. I was using webp 0.5.0 and after upgrading I too got the same size.
I guess lossless and near-lossless flags were added in libvips in 8.4? If that's the case, then what is the behavior of `vips copy`. Would it (or rather should it) consider both lossy and lossless methods before delivering the final image which would then be the smallest of the two?

**Comment by jcupitt** [comment]
You can give args to `vips copy`, for example:

```
john@kiwi:~/pics$ vips copy tiny.png x.webp
john@kiwi:~/pics$ vips copy tiny.png x2.webp[lossless]
john@kiwi:~/pics$ ls -l x* 
-rw-r--r-- 1 john john 19184 Jan 10 17:05 x2.webp
-rw-r--r-- 1 john john 34916 Jan 10 17:05 x.webp
```

With no arguments you get the default behaviour. 

My feeling is that vips shouldn't try different options for you. Finding the best settings quickly is not easy and can need deep knowledge of the file format. I think I'd leave that to specialist tools.

**Comment by rnanwani** [comment]
Can you confirm if this is the right command to test vips near lossless flag

`vips copy test/fixtures/alpha-premultiply-1024x768-paper.png /tmp/webp-near-lossless-20.webp[near_lossless,Q=20]`

**Comment by jcupitt** [comment]
Yes, looks right, I think.

**Comment by rnanwani** [comment]
Then in that case, the output size obtained using varied Q levels with `near_lossless` using vips doesn't follow a trend like it does when we use `cwebp` for the same.

![image](https://cloud.githubusercontent.com/assets/4739557/21919596/8340bab6-d981-11e6-91a8-e8e63d0b948c.png)

As it can be seen in the above screenshot, the first set of files, generated using `cwebp` follow a trend where the size increases with increase in quality (or `near_lossless` approaching 100).
The command used is 
`cwebp -near_lossless 70 test/fixtures/alpha-premultiply-1024x768-paper.png -o /tmp/cwebp-near-lossless-70.webp`

However, with `vips` the same trend could not be observed, with Q=30 being significantly smaller than both Q=20 and Q=40. Likewise for other quality values. 
The command used is
`vips copy test/fixtures/alpha-premultiply-1024x768-paper.png /tmp/webp-near-lossless-20.webp[near_lossless,Q=20]`

**Comment by jcupitt** [comment]
I reread `cwebp.c` and it seems they only use the presets for lossy compression. I changed `vips2webp.c` to match and I now see the same behaviour as cwebp.

```bash
#!/bin/bash

im=~/pics/k2.jpg

for q in {0..100..20}; do
	vips copy $im x.webp[near_lossless,Q=$q]
	echo -n "vips Q = $q "
	ls -l x.webp
done

for q in {0..100..20}; do
	cwebp -quiet -near_lossless $q $im -o x.webp
	echo -n "cwebp Q = $q "
	ls -l x.webp
done
```

With a photographic image I see:

```
john@kiwi:~/pics$ ./nearlossless.sh 
vips Q = 0 -rw-r--r-- 1 john john 1820718 Jan 13 12:33 x.webp
vips Q = 20 -rw-r--r-- 1 john john 1817984 Jan 13 12:33 x.webp
vips Q = 40 -rw-r--r-- 1 john john 1811428 Jan 13 12:33 x.webp
vips Q = 60 -rw-r--r-- 1 john john 1800202 Jan 13 12:34 x.webp
vips Q = 80 -rw-r--r-- 1 john john 1948352 Jan 13 12:34 x.webp
vips Q = 100 -rw-r--r-- 1 john john 2249190 Jan 13 12:34 x.webp
cwebp Q = 0 -rw-r--r-- 1 john john 1820566 Jan 13 12:34 x.webp
cwebp Q = 20 -rw-r--r-- 1 john john 1817832 Jan 13 12:35 x.webp
cwebp Q = 40 -rw-r--r-- 1 john john 1811276 Jan 13 12:35 x.webp
cwebp Q = 60 -rw-r--r-- 1 john john 1800050 Jan 13 12:35 x.webp
cwebp Q = 80 -rw-r--r-- 1 john john 1948200 Jan 13 12:35 x.webp
cwebp Q = 100 -rw-r--r-- 1 john john 2249038 Jan 13 12:36 x.webp
```

Thanks for finding this. libwebp is rather unfinished :(

**Comment by jcupitt** [comment]
I think we're done, I'll close.
