### ISSUE TITLE
./configure says ok, make crashes

### ISSUE THREAD

**Issue by mezod** [jcupitt/libvips#579]
I am trying to manually install libvips on a debian 6 (yeah, sorry :face_with_head_bandage: ) and I managed to manually install all the needed packages, ./configure says ok, but when I run make I get:

```
In file included from vips2jpeg.c:148:
jpeg.h:80: error: expected ')' before '*' token
make[2]: *** [vips2jpeg.lo] Error 1
make[2]: Leaving directory `/home/joan/vips-8.4.1/libvips/foreign'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/joan/vips-8.4.1/libvips'
make: *** [install-recursive] Error 1
```

I am pretty much out of my comfort zone here, so if anyone has an idea of what's wrong i'd highly appreciate it! Thanks!

**Comment by jcupitt** [comment]
Hi @mezod, I think you are missing libexif. Try installing that and configuring again. 

It actually looks like a libvips bug: it should compile even if libexif is missing. I'll try to fix it.

**Comment by jcupitt** [comment]
I fixed the libvips bug:

https://github.com/jcupitt/libvips/commit/6542885d074223aa4cae22152d57aecba3b5650e

Thank you for reporting this error!

What do you plan to use the library for? If it's for image resizing, you probably need libexif anyway.

**Comment by mezod** [comment]
hey @jcupitt thanks for your prompt response. I'm frankly surprised I found a bug. I hardly know what I'm doing here! Glad to have helped you somehow though!

Installing libexif solved the problem and make seems to work. I could also sudo make install without apparently any problems. However, I'm still running into the same problem with node-gyp / sharp... which is what brought me here.

I am trying to install https://github.com/lovell/sharp which as you guessed is for image resizing with Node.js.

I am stuck at the moment, do you have any ideas on how do I check if libvips was properly installed? I had to install it manually following https://github.com/jcupitt/libvips#building-libvips-from-a-source-tarball . `dpkg -l | grep libvips` doesn't show anything. Any ideas are welcome! sysadmin is obviously not my thing hehe :-)

**Comment by lovell** [comment]
@mezod You'll [need gcc v4.8 or later](http://sharp.dimens.io/en/stable/install/#prerequisites) for C++11 support but Debian 6 ships with (I think) only v4.4.

**Comment by mezod** [comment]
thanks @lovell , looks like installing gcc 4.8 in a debian 6 is not a very good idea, I'll see how I proceed, thanks for your time guys!

**Comment by jcupitt** [comment]
Glad it compiled. `dpkg` only lists things installed by the `apt` package manager, it won't list things you built yourself.

To test if libvips is ready to build against, use `pkg-config`. For example, I see:

```
$ pkg-config vips --modversion
8.5.0
```

You'll probably see an error though.

`apt` installs to `/usr`, but by default stuff you build installs to `/usr/local`. You need to set up your environment so that programs which you run also look in `/usr/local` for stuff. You'll need to set at least `PATH`, `LD_LIBRARY_PATH` and `PKG_CONFIG_PATH`, and you'll have to run node as you.

**Comment by jcupitt** [comment]
Thanks @lovell, that sounds like it might be a blocker.

**Comment by mezod** [comment]
yep 8.4.1 seems to be properly installed... just need to figure out what I do with gcc now... thanks again! you can close this issue if you feel like it :)

**Comment by jcupitt** [comment]
Ok, done!

**Comment by helloqhx** [comment]
@mezod I have the same issue with you and fix it with installed the libexif, but when i `npm install sharp`, it output `ERROR: glibc version 2.12 requires manual installation`
Can you tell me how to install sharp at Centos 6.5 completely?
Thanks very muck.

**Comment by mezod** [comment]
Well, it looks like you are missing the glibc library

try `pkg-config glibc` to check if you have glibc installed and if its 2.12^. Otherwise use apt-get to install it or find the pkg and install it manually (wget + dpkg -i)

**Comment by lovell** [comment]
@helloqhx Please don't [cross-post](https://github.com/lovell/sharp/issues/342#issuecomment-272820696).
