### ISSUE TITLE
Build from source error at Centos 6.5

### ISSUE THREAD

**Issue by helloqhx** [jcupitt/libvips#581]
> In file included from vips2jpeg.c:148:0:
jpeg.h:80:32: error: unknown type name ‘ExifData’
 int vips__set_exif_resolution( ExifData *ed, VipsImage *im );
                                ^
make[3]: *** [vips2jpeg.lo] Error 1
make[3]: Leaving directory `/data/software/vips/libvips/foreign'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/data/software/vips/libvips'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/software/vips'
make: *** [all] Error 2

I want install libvips on centos 6.5, but it stuck at make, and output the error above.
Can anyone help?

**Comment by jcupitt** [comment]
Hello @helloqhx, this came up a couple of days ago: https://github.com/jcupitt/libvips/issues/579

You need to install the libexif headers, or build from the head of the 8.4 branch on github. What do you plan to use vips for? If it's image resizing, you probably need libexif.

**Comment by helloqhx** [comment]
Thanks very muck for your quick answer.
Installed `libexif-devel` fix it.

**Comment by jcupitt** [comment]
Glad it's working, I'll close.
