### ISSUE TITLE
3D histogram

### ISSUE THREAD

**Issue by Jondeen** [jcupitt/libvips#582]
Hi,

Are there any easy-ish ways of generating a 3D histogram of an image, i.e. count of individual triplet pixel values for any 3-band colourspace?

**Comment by jcupitt** [comment]
Hi, yes, you need `vips_hist_find_ndim()`:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-arithmetic.html#vips-hist-find-ndim

**Comment by Jondeen** [comment]
Wow, libvips has it all - somehow I missed it when looking for it myself. Thanks for speedy reply. Speedy like libvips is itself!

**Comment by jcupitt** [comment]
It's classified as an arithmetic operator, confusingly, because it's based on the statistics base class :( I'll add a note to the histogram section saying to check in arithmetic as well.
