### ISSUE TITLE
VIPS_INIT call policy

### ISSUE THREAD

**Issue by alonit** [jcupitt/libvips#588]
Hi,

Using vips 8.4.4, is it a must to call manually `VIPS_INIT()` from my code (e.g. from my main() function) ? or Is the vips system call `VIPS_INIT()` for me when first calling some vips operations? If it called automatically by vips , what is the difference between manually calling it from my code vs automatically called by the vips system.

Thanks

**Comment by jcupitt** [comment]
It's best to call it yourself if you can. It checks API compatibility, for example, and if you call it yourself, you can be certain you can call any vips function after that. Only the most commonly-used vips API functions will do `vips_init()` for you, so if you call one of the more obscure ones first, you can crash.

There's also threading. `VIPS_INIT()` can be run from any thread, but it must not be called from more than one thread at once or you'll see crashes. This is much easier to guarantee if you have a separate init phase for your program. 

I'll add some more notes to the docs.

**Comment by jcupitt** [comment]
I'll close, I think this is resolved.
