### ISSUE TITLE
Generated thumbnail is "more colourful" than the source image

### ISSUE THREAD

**Issue by laszbalo** [jcupitt/libvips#589]
Hi!

I resized a photo by issuing the following command:
```shell
vipsthumbnail input.jpg -o out.jpg[Q=97,optimize-coding,strip=true] --eprofile /usr/share/color/icc/ghostscript/srgb.icc --delete -s 400
```

You can see the result of the above command in the first photo. The second photo, which was obtained by resizing the original image differently, preserves the colours of the original photo correctly.

![out2](https://cloud.githubusercontent.com/assets/1551034/22337564/2a61444a-e3dd-11e6-8902-419dbb2da999.jpg) ![out1](https://cloud.githubusercontent.com/assets/1551034/22337610/4d4f1aa4-e3dd-11e6-9832-c36eaf0354bf.jpg)

Can anybody explain why is this happening and how can I fix it?
Using vesion 8.4.5.
With thanks,
Laszlo

EDIT:

I forgot to tell, that when I run the above command but save it in ppm format by using ```-o out.ppm[strip=true]```, then I get the exact same looking picture than the second one.

**Comment by jcupitt** [comment]
Hi, could you upload the original somewhere? My guess would be it's adobe98 and you've been viewing it in an image viewer which does not support ICC profiles.

**Comment by laszbalo** [comment]
[Link](http://assets.vogue.com/photos/56d0a990de114fd342ed1fb2/master/pass/_VER0037.jpg) to the original image. Using ristretto (default on Xubuntu) as image viewer. But looking at the two photos side by side in Chrome, I can still see the difference.

**Comment by laszbalo** [comment]
Not sure if it makes any difference, but I am using a different file in --eprofile.
In my system this is the structure of /usr/share/color/icc/:
```
/usr/share/color/icc/
├── colord
│   ├── AdobeRGB1998.icc
│   ├── AppleRGB.icc
│   ├── BestRGB.icc
│   ├── BetaRGB.icc
│   ├── Bluish.icc
│   ├── BruceRGB.icc
│   ├── CIE-RGB.icc
│   ├── ColorMatchRGB.icc
│   ├── Crayons.icc
│   ├── DonRGB4.icc
│   ├── ECI-RGBv1.icc
│   ├── ECI-RGBv2.icc
│   ├── EktaSpacePS5.icc
│   ├── FOGRA27L_coated.icc
│   ├── FOGRA28L_webcoated.icc
│   ├── FOGRA29L_uncoated.icc
│   ├── FOGRA30L_uncoated_yellowish.icc
│   ├── FOGRA39L_coated.icc
│   ├── FOGRA40L_SC_paper.icc
│   ├── FOGRA45L_lwc.icc
│   ├── FOGRA47L_uncoated.icc
│   ├── Gamma5000K.icc
│   ├── Gamma5500K.icc
│   ├── Gamma6500K.icc
│   ├── GRACoL_TR006_coated.icc
│   ├── IFRA26S_2004_newsprint.icc
│   ├── NTSC-RGB.icc
│   ├── PAL-RGB.icc
│   ├── ProPhotoRGB.icc
│   ├── SMPTE-C-RGB.icc
│   ├── SNAP_TR002_newsprint.icc
│   ├── sRGB.icc
│   ├── SwappedRedAndGreen.icc
│   ├── SWOP_TR003_coated_3.icc
│   ├── SWOP_TR005_coated_5.icc
│   ├── WideGamutRGB.icc
│   └── x11-colors.icc
└── ghostscript
    ├── default_cmyk.icc
    ├── default_gray.icc
    ├── default_rgb.icc
    ├── gray_to_k.icc
    ├── lab.icc
    ├── ps_cmyk.icc
    ├── ps_gray.icc
    ├── ps_rgb.icc
    ├── sgray.icc
    └── srgb.icc

```

I tried using both /usr/share/color/icc/ghostscript/srgb.icc and /usr/share/color/icc/colord/sRGB.icc, bot got the same looking photo. If I omit --eprfile altogether, then I get the correct image, though.

**Comment by jcupitt** [comment]
Hi, I'm not sure that's the original image, it doesn't have a colour profile embedded in it. If I do this:

```
john@kiwi:~/pics$ vipsthumbnail VER0037.jpg -o vt.jpg[Q=97,optimize-coding,strip=true] --eprofile /usr/share/color/icc/ghostscript/srgb.icc --delete -s 400
john@kiwi:~/pics$ vipsthumbnail VER0037.jpg -o vt2.jpg[Q=97,optimize-coding,strip=true] --delete -s 400
john@kiwi:~/pics$ vips subtract vt.jpg vt2.jpg x.v
john@kiwi:~/pics$ vips abs x.v x2.v
john@kiwi:~/pics$ vips max x2.v
0.000000
```

ie. I see the same result with or without `--eprofile`.

**Comment by laszbalo** [comment]
Sorry, but I have linked the wrong file. Please find the exact one I used as the source for the above two files [here](https://dl.dropboxusercontent.com/u/72817558/2.jpg). Following the steps above, I got 42.000.

**Comment by jcupitt** [comment]
Thanks! I should be able to take a look on Sunday.

**Comment by jcupitt** [comment]
Hi, again, I had some time.

Yes, your original image is in Adobe98 colourspace, which has a wider gamut than sRGB. If you view it using a program which does not support ICC profile, or it you delete the profile, it will look desaturated. 

Try:

```
$ vipsthumbnail sample.jpg --eprofile /usr/share/color/icc/ghostscript/srgb.icc -s 400 -o x.jpg[strip]
$ vipsthumbnail sample.jpg -s 400 -o x2.jpg[strip]
```

That'll make `x.jpg` which has no profile and is just the pixels from your original, but shrunk down. It'll look desaturated. `x2.jpg` also has no profile, but it has been converted from Adobe98 to sRGB, so the colour will look correct.

If I look at the original `sample.jpg`, `x.jpg` and `x2.jpg` in ristretto on Ubuntu 16.10, then `sample` and `x` match, `x2` looks different and desaturated. 

Perhaps you are using an older ristretto that does not support ICC profiles? Older version of Chrome also do not support profiles. You could also try Firefox or `eog`.

**Comment by jcupitt** [comment]
... so as far as I can see, `vipsthumbnail` is correct and your second version of the image is wrong. 

Here's another way of doing it:

```
$ convert sample.jpg -resize x400 -profile /usr/share/color/icc/ghostscript/srgb.icc x3.jpg
```

Which will resize and convert to sRGB with imagemagick. It will match the colourful output of vipsthumbnail.

**Comment by laszbalo** [comment]
Thank you for your detailed reply. It was very helpful, as always. 
Both Firefox and eog renders the original photo nicely saturated/coloured, unlike Risetto, which on my Xubuntu 16.10, renders the photo desaturated. At the weekend also tried viewnoir, but based on what you just explained, it also lacks the ICC profile support. Sorry for spamming the issue tracker.

> That'll make x.jpg which has no profile and is just the pixels from your original, but shrunk down. It'll look desaturated. x2.jpg also has no profile, but it has been converted from Adobe98 to sRGB, so the colour will look correct.

I think when you were talking about x.jpg, you really meant x2.jpg and vice versa.
