### ISSUE TITLE
Set bigtiff automatically when tiff exceeds the 4gb limit ( tiffsave )

### ISSUE THREAD

**Issue by AndreasSchmid1** [jcupitt/libvips#591]
I generate generic tiled tiffs from svs files with libvips (btw a amazing tool!)
(tiffsave source.svs target.tiff --compression jpeg --Q 75 --tile --tile-width 256 --tile-height 256 --pyramid)

I also have the demand that bigtiff (--bigtiff) files are only created if the target tiff exceeds the limit for a normal tiff file.

Is it possible to change a bigtiff file to a normal tiff file after checking the filesize?
Or is it possible to let the tool decide when it is necessary to create a bigtiff file?

Thank you very much for help in advance

**Comment by jcupitt** [comment]
Hi @AndreasSchmid1, sorry, this is not possible to do automatically. 

You must use bigtiff if the output tiff size is over 4gb (actually 2gb for some versions of libtiff), but it's impossible to tell in advance how large the final file will be. For example, the degree of compression you get can change a lot depending on the image contents.

You cannot change bigtiff to regular tiff, except by reading the whole file, modifying all the sizes, and writing back again. You can use the `tiffcp` program to do this, but it is slow.

The simplest solution would be to write as a regular tiff file, then if that fails, try again as bigtiff. This will also be slow, unfortunately.

**Comment by AndreasSchmid1** [comment]
Hi @jcupitt . Thank you very much for your fast answer. Yes, I think I will go for the "try create regular tiff approach")
I lately used Bitmiracle Libtiff.net (a .net implementation of libtiff), which magically autogenerates bigtiff files when it exceeds the regular tiff limit. 
Link for the stackoverflow discussion
http://stackoverflow.com/questions/28676738/create-a-bigtiff-4gb-file-with-bitmiracle-libtiff-net 
I also tried to understand what they did without big success^^.
https://github.com/Milster/libtiff.net/commit/1f56e41fc956f9d1d0970d8422343969875ec200

**Comment by jcupitt** [comment]
I found some discussion here:

https://trac.openmicroscopy.org/ome/ticket/6589

All they do is check if compression is off, and just in that case, try to predict the file size and enable bigtiff if necessary.

I guess vips could do this too, though I wonder how useful it is. It would be very annoying to have bigtiff turned on automatically when it wasn't needed.

**Comment by AndreasSchmid1** [comment]
Yes, I think you are right.

Actually my initial approach was to generate bigtiff files in general. 
Unfortunately I was not able to generate valid files for openslide then.
For example a generic tiled tiff with bigtiff flag set + filesize below 4gb cannot be opened.

But I will review this with a colleague who has a deeper understanding of this to make sure that I did not make a mistake there. And if not, to detect if this is maybe an issue on the openslide side.

**Comment by jcupitt** [comment]
bigtiff should always work i think. For example, I see:

```
$ vips copy CMU-1-Small-Region.svs x.tif[bigtiff,tile]
$ tiffinfo x.tif
TIFF Directory at offset 0x1b00010 (28311568)
  Image Width: 2220 Image Length: 2967
  Tile Width: 128 Tile Length: 128
  Resolution: 10, 10 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Extra Samples: 1<unassoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 4
  Planar Configuration: single image plane
$ file x.tif 
x.tif: Big TIFF image data, little-endian
```

And I can view `x.tif` with `eog`. Many viewers do not support bigtiff, unfortunately.

**Comment by AndreasSchmid1** [comment]
@jcupitt thank you. I tested it with the same file and it worked for me aswell. On monday i will review if my source files are already corrupted.

**Comment by jcupitt** [comment]
OK, I added a thing to git master libvips to enable bigtiff if compression is off and if the pixel data is >4gb. This won't always work, but it will help in some cases.

**Comment by jcupitt** [comment]
... I'm afraid it won't help your case, for example, since you are using JPEG compression and it won't be possible to predict the file size in advance. Anyway, this might help someone.

**Comment by AndreasSchmid1** [comment]
Thank you very much @jcupitt .

I did some tests this morning.
I was able to produce a valid bigtiff tif file with the sample file you also used.

`vips tiffsave CMU-1-Small-Region.svs result.tiff --compression jpeg --Q 75 --bigtiff --tile --tile-width 256 --tile-height 256 --pyramid`

But I was not able to produce a valid bigtiff tif file with another source file. (At least I could not open it via nip2)

`vips tiffsave source.tif result.tiff --compression jpeg --Q 75 --bigtiff --tile --tile-width 256 --tile-height 256 --pyramid`

I attached the source.tif

**Comment by jcupitt** [comment]
Hi again Andreas, thanks for the sample image. 

It works here, strange. I was able to view `result.tiff` in both nip2 and eog. 

Do you see any error messages? Are you cable to process `result.tiff` using any of the vips tools? For example, does:

```
$ vips copy result.tiff x.jpg
```

make an image you can view?

**Comment by AndreasSchmid1** [comment]
Thank you @jcupitt 

When I use "$ vips copy result.tiff x.jpg" on the currupted result.tiff I get the errormessage "Not a TIFF file, bad BigTIFF offsetsize 0 (0x0)".

Download of the currupted tif file:
imaging.precipoint.com/sampleSlides/failed.tiff

But I do not want to waste your time. Maybe I did something wrong or use an old version of the libvips library. When I find time the next days I will download the latest stable windows libvips binaries and review this issue with a collegue. When it is working on your side it is likely an issue on my side^^.

**Comment by jcupitt** [comment]
Oh, I didn't realize you were on Windows. I tried with 8.4.4 and it seems to work for me:

```
$ ~/Desktop/vips-dev-8.4/bin/vips.exe tiffsave source.tif result.tiff --compression jpeg --Q 75 --bigtiff --tile --tile-width 256 --tile-height 256 --pyramid
$ tiffinfo result.tiff 
TIFF Directory at offset 0x69beee (6930158)
  Image Width: 7936 Image Length: 7936
  Tile Width: 256 Tile Length: 256
  Resolution: 2.82828, 2.82828 pixels/inch
  Bits/Sample: 8
  Sample Format: unsigned integer
....
```

**Comment by AndreasSchmid1** [comment]
Ok, I found the bug which was clearly on our side. Thank you very much for your "premium support" and for this great library.

**Comment by jcupitt** [comment]
OK, glad it's working.
