### ISSUE TITLE
Question: How to create tiles for multiple jpegs via "vips dzsave" and CLI in one go?

### ISSUE THREAD

**Issue by comrade2sun** [jcupitt/libvips#593]
Hi
Since this command on CLI

> vips dzsave P:\images\fred.jpg D:\data\fred

creates the desired tiles lightning fast, even faster than I can type the command itself, I would like to know, how I could create the tiles for all the other jpegs in the same folder in one go. As you can imagine, Fred has many many friends and I am a bit slow (and lazy) :innocent: to type this command over and over again.
I am not a regular command-line user at all and if it comes to a more complex task, I am absolutly lost and therefore any help would be much appreciated

I am on a Win10 machine, using `vips-dev-8.4` and start CLI in the bin folder.
The image format is .jpg and the  average height and width less than 10 000 px.
I would like to keep the jpegs filename for the main tile-source folder, par example '`fred_files`'. But I also could go ahead with numbers like `'000_ files'`, `'001_files'` ... and so on.
Optional arguments I may will use `overlap` and `tile-size` in the future, but for a start the default will be sufficient.
The tiles are displayed with the OpenSeadragon viewer.

Any suggestions and help would be great to make my humble tasks a bit faster.

Thank You

**Comment by jcupitt** [comment]
Hi, you need to write a little script. On Windows, you should probably look into powershell, it can do this kind of thing very simply. Unfortunately I don't use Windows much and can't really help directly.

On linux it would be something like:

```bash
for filename in image/*.jpg; do
   vips dzsave $filename outputdir/$(basename $filename)
done
```

**Comment by comrade2sun** [comment]
Hi jcupitt

Thanks for your quick reply and your suggestion.

I dit try something like this
``` 
for filename in P:\images\*.jpg; do
   vips dzsave $filename D:\data\$(basename $filename)
```
  
on  Windows PowerShell as well with Windows cmd.exe with so far no decent result.

That means, I am stuck somewhere between my heroic try&error method with results like

> "filename" can not be processed syntactically at this point

and "Windows Powershell for Beginners" with results like this:

> VipsForeignLoad: file Â»$filenameÂ« not found

Anyway, the latter gives some hope, I may ask in some last desperate attempt Cortana :gun: ...

But I am still optimistic to find the magic command one day. :sparkles:

**Comment by jcupitt** [comment]
Good luck! I'd read some sort of "powershell for beginners" tutorial, though I couldn't recommend a particular one.
