### ISSUE TITLE
Loading Python Vips GObject-Introspection breaks scikit-learn non-negative matrix factorization

### ISSUE THREAD

**Issue by ro-joshi** [jcupitt/libvips#594]
Hi,

I'm trying to use Vips to read a portion of a massive image into python, and then feed the image into a machine learning algorithm (non-negative matrix factorization or NMF). However, loading the Vips library results in erroneous NMF results.

These are steps that reproduce on my computer:

```python
import numpy as np
from matplotlib import pyplot as plt
from sklearn.decomposition import NMF
from gi.repository import Vips

img = Vips.Image.new_from_file('train_10.bmp') #3 channel RGB image
tmp = img.extract_area(0, 0, 500, 500)
mem_img = tmp.write_to_memory()
np_3d = np.fromstring(mem_img, dtype=np.uint8)
np_3d = np_3d.reshape((500, 500, 3))
A = np.log(255 / np_3d)
nmf = NMF(n_components=2, init='nndsvd', random_state=0, alpha=.1, l1_ratio=1, verbose=10)
nmf_tfm = nmf.fit_transform(A.reshape(-1, 3))
nmf_tfm = nmf_tfm.reshape((500, 500, 2))
plt.figure()
plt.imshow(nmf_tfm[:, :, 0])
plt.figure()
plt.imshow(nmf_tfm[:, :, 1])
```

nmf_tfm should now be a 500x500 2 channel image, with the first channel containing one dominant color in the image, and the second channel containing the other dominant color in the image.  However, NMF does not converge properly with Vips loaded and the second channel is filled with zeros or a degraded image as a result.

This is also reproducible by simply loading the library and not using Vips for anything:

```python
#### Doesn't work
import numpy as np
from matplotlib import pyplot as plt
import cv2 #use opencv to load the image
from sklearn.decomposition import NMF
from gi.repository import Vips

img = cv2.imread('train_10.bmp') #use opencv to load image instead
A = np.log(255 / img)
nmf = NMF(n_components=2, init='nndsvd', random_state=0, alpha=.1, l1_ratio=1, verbose=10)
nmf_tfm = nmf.fit_transform(A.reshape(-1, 3))
nmf_tfm = nmf_tfm.reshape((img.shape[0], img.shape[1], 2))
plt.figure()
plt.imshow(nmf_tfm[:, :, 0])
plt.figure()
plt.imshow(nmf_tfm[:, :, 1])
```

```python
#### works
import numpy as np
from matplotlib import pyplot as plt
import cv2 #use opencv to load the image
from sklearn.decomposition import NMF

img = cv2.imread('train_10.bmp') #use opencv to load image instead
A = np.log(255 / img)
nmf = NMF(n_components=2, init='nndsvd', random_state=0, alpha=.1, l1_ratio=1, verbose=10)
nmf_tfm = nmf.fit_transform(A.reshape(-1, 3))
nmf_tfm = nmf_tfm.reshape((img.shape[0], img.shape[1], 2))
plt.figure()
plt.imshow(nmf_tfm[:, :, 0])
plt.figure()
plt.imshow(nmf_tfm[:, :, 1])
```

Example image file: [train_10.bmp.zip](https://github.com/jcupitt/libvips/files/737752/train_10.bmp.zip)

**Comment by jcupitt** [comment]
Hi @ro-joshi, I tried your program here but it fails to run for me. In your final example, are you sure the line:

```python
A = np.log(255 / img)
```

is correct? I see:

```
$ ./ro.py ~/pics/k2.tif
./ro.py:10: RuntimeWarning: divide by zero encountered in divide
  A = np.log(255 / img)
```

**Comment by ro-joshi** [comment]
@jcupitt My apologies, there were a lot of problems with that code.  I've uploaded a sample image and fixed the top code block.  The bottom two code blocks should work as in the original post.  Please let me know if it still doesn't run.

**Comment by jcupitt** [comment]
Hi, I tried your doesn't-work example:

```python
#!/usr/bin/env python2

import numpy as np
from matplotlib import pyplot as plt
import cv2 #use opencv to load the image
from sklearn.decomposition import NMF

import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

img = cv2.imread("train_10.bmp")
A = np.log(255 / img)
nmf = NMF(n_components=2, init='nndsvd', random_state=0, alpha=.1, l1_ratio=1,
        verbose=10)
nmf_tfm = nmf.fit_transform(A.reshape(-1, 3))
nmf_tfm = nmf_tfm.reshape((img.shape[0], img.shape[1], 2))
plt.figure()
plt.imshow(nmf_tfm[:, :, 0])
plt.figure()
plt.imshow(nmf_tfm[:, :, 1])
plt.show()
```

And when I run:

```
john@kiwi:~/try$ ./ro.py
('violation:', 1.0)
('violation:', 0.7614253535559332)
('violation:', 0.31490954214348166)
...
('violation:', 0.25589996653726654)
('violation:', 0.25588435337134)
```

It seems to converge OK and I see two different images on the screen. This is Ubuntu 16.10. I had to use py2, there doesn't seem to be a bundled opencv for py3.

**Comment by jcupitt** [comment]
I tried your load via vips example, and that seems to work as well. 

```python
#!/usr/bin/env python3

import numpy as np
from matplotlib import pyplot as plt
from sklearn.decomposition import NMF

import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

img = Vips.Image.new_from_file('train_10.bmp') #3 channel RGB image
tmp = img.extract_area(0, 0, 500, 500)
mem_img = tmp.write_to_memory()
np_3d = np.fromstring(mem_img, dtype=np.uint8)
np_3d = np_3d.reshape((500, 500, 3))
A = np.log(255 / np_3d)
nmf = NMF(n_components=2, init='nndsvd', random_state=0, alpha=.1, l1_ratio=1,
        verbose=10)
nmf_tfm = nmf.fit_transform(A.reshape(-1, 3))
nmf_tfm = nmf_tfm.reshape((500, 500, 2))
plt.figure()
plt.imshow(nmf_tfm[:, :, 0])
plt.figure()
plt.imshow(nmf_tfm[:, :, 1])
plt.show()
```

I see:

```
john@kiwi:~/try$ ./ro2.py 
violation: 1.0
violation: 0.7541385337013335
violation: 0.6983244808948235
violation: 0.5773739808804418
violation: 0.5172862398522606
...
violation: 0.2849086137826081
violation: 0.28485022932655246
```

It seems to take longer to converge, but I get two different images, and no zeros.

**Comment by ro-joshi** [comment]
@jcupitt Thanks for checking this out.  Is the result you are getting reproducible when run several times? I get varying results, sometimes zeros, sometimes degraded images, and sometimes what looks ok - but never the consistent results I get without loading Vips.  I see convergence after 2 loops sometimes and longer at other times. Please see attached for example results I see after loading the Vips library
[Archive.zip](https://github.com/jcupitt/libvips/files/737794/Archive.zip)
.

If this is specific to my system, any ideas on how I can debug this? Thank you.

**Comment by jcupitt** [comment]
I tried adding a loop:

```python
#!/usr/bin/env python3

import numpy as np
from matplotlib import pyplot as plt
from sklearn.decomposition import NMF

import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

img = Vips.Image.new_from_file('train_10.bmp') #3 channel RGB image
tmp = img.extract_area(0, 0, 500, 500)
mem_img = tmp.write_to_memory()
np_3d = np.fromstring(mem_img, dtype=np.uint8)
np_3d = np_3d.reshape((500, 500, 3))

for i in range(1,10):
    A = np.log(255 / np_3d)
    nmf = NMF(n_components=2, init='nndsvd', random_state=0, alpha=.1, 
            l1_ratio=1, verbose=10)
    nmf_tfm = nmf.fit_transform(A.reshape(-1, 3))
    nmf_tfm = nmf_tfm.reshape((500, 500, 2))
    plt.figure()
    plt.imshow(nmf_tfm[:, :, 0])
    plt.figure()
    plt.imshow(nmf_tfm[:, :, 1])
    plt.show()
```

And I get the same result on each loop. 

I guess you're running in ipython, is that right? What if you try running at the command-line?

What platform are you using? I'm Ubuntu 16.10 with all the packages as bundled. 

I'm using git master vips, I'll try 8.4.

**Comment by jcupitt** [comment]
It seems to work with 8.4 as well.

**Comment by ro-joshi** [comment]
Thanks for the code - I think I'm getting closer to the problem.

I'm on Gentoo and running Python 3.4, Vips 8.4, numpy 1.11.2, scipy 0.18.1, scikit-learn 0.18.1

I set up a virtual environment running pip/local versions of numpy and scipy, which are not linked to my system BLAS library (use openblas it looks like), along with the system versions of scikit-learn and Vips 8.4.  When I ran your code, I got reproducible results, just like you.

> In [2]: np.__config__.show()
> openblas_info:
>     define_macros = [('HAVE_CBLAS', None)]
>     library_dirs = ['/usr/local/lib']
>     libraries = ['openblas', 'openblas']
>     language = c
> blas_mkl_info:
>   NOT AVAILABLE
> lapack_opt_info:
>     define_macros = [('HAVE_CBLAS', None)]
>     library_dirs = ['/usr/local/lib']
>     libraries = ['openblas', 'openblas']
>     language = c
> blis_info:
>   NOT AVAILABLE
> lapack_mkl_info:
>   NOT AVAILABLE
> openblas_lapack_info:
>     define_macros = [('HAVE_CBLAS', None)]
>     library_dirs = ['/usr/local/lib']
>     libraries = ['openblas', 'openblas']
>     language = c
> blas_opt_info:
>     define_macros = [('HAVE_CBLAS', None)]
>     library_dirs = ['/usr/local/lib']
>     libraries = ['openblas', 'openblas']
>     language = c

When I run my code with my system versions of numpy and scipy, which are linked to an MKL/intel BLAS library, along with system versions of scikit-learn and Vips 8.4, I get the problems.

> >>> np.__config__.show()
> lapack_info:
>     libraries = ['mkl_rt', 'iomp5', 'm']
>     language = f77
>     library_dirs = ['/opt/intel/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64', '/opt/intel/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64', '/usr/lib64']
> lapack_opt_info:
>     libraries = ['mkl_rt', 'iomp5', 'm', 'mkl_rt', 'iomp5', 'm']
>     language = c
>     define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
>     library_dirs = ['/opt/intel/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64', '/opt/intel/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64', '/usr/lib64']
> blas_info:
>     libraries = ['mkl_rt', 'iomp5', 'm']
>     language = c
>     library_dirs = ['/opt/intel/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64', '/opt/intel/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64', '/usr/lib64']
>     define_macros = [('HAVE_CBLAS', None)]
> blas_opt_info:
>     libraries = ['mkl_rt', 'iomp5', 'm']
>     language = c
>     define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
>     library_dirs = ['/opt/intel/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64', '/opt/intel/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64', '/usr/lib64']
> system_info:
>   NOT AVAILABLE

Maybe Vips is somehow interfering with the MKL backend on Gentoo? What backend is your numpy/scipy using?

Thank you.

**Comment by ro-joshi** [comment]
I narrowed it down a bit further...

It seems to be localized to scipy. Local vs. system version of numpy didn't matter.

With the pip version of scipy 0.18.1, I get no problems:

> openblas_info:
>     libraries = ['openblas']
>     language = f77
>     library_dirs = ['/usr/local/lib']
> blas_opt_info:
>     libraries = ['openblas']
>     language = f77
>     library_dirs = ['/usr/local/lib']
> lapack_opt_info:
>     libraries = ['openblas']
>     language = f77
>     library_dirs = ['/usr/local/lib']

With my installed version of scipy with MKL backend, I get the problems:

> blas_info:
>     language = c
>     libraries = ['mkl_rt', 'iomp5', 'm']
>     define_macros = [('HAVE_CBLAS', None)]
>     library_dirs = ['/opt/intel/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64', '/opt/intel/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64', '/usr/lib64']
> blas_opt_info:
>     language = c
>     libraries = ['mkl_rt', 'iomp5', 'm']
>     define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
>     library_dirs = ['/opt/intel/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64', '/opt/intel/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64', '/usr/lib64']
> lapack_opt_info:
>     language = c
>     libraries = ['mkl_rt', 'iomp5', 'm', 'mkl_rt', 'iomp5', 'm']
>     define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
>     library_dirs = ['/opt/intel/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64', '/opt/intel/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64', '/usr/lib64']
> lapack_info:
>     language = f77
>     libraries = ['mkl_rt', 'iomp5', 'm']
>     library_dirs = ['/opt/intel/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64', '/opt/intel/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64', '/usr/lib64']
> system_info:
>   NOT AVAILABLE

I think Vips is somehow interfering with the linear algebra library.

**Comment by jcupitt** [comment]
I think my guess would be that vips and something like blas both have a dependency on the same library, but that they have been linked to different versions and those versions are not binary-compatible.

 You are running vips first, so it will dlload() the various libraries that vips needs to run. When it tries to dlload() the libraries for numpy later, it sees that a version of this third library has already been linked, so it does not link it again, but hooks numpy up to the incompatible version.

Now when numpy runs, it ends up calling into a library it is not expecting and disaster follows.

I think I would try rebuilding the whole stack.

**Comment by ro-joshi** [comment]
I tried rebuilding the stack, including numpy, scipy, vips, pygobject, and scikit-learn, but it didn't work.

Downgrading to Vips 7.38 and using the VipsCC interface works.  However, I really need python3 for other libraries.

It might be something with the Vips gobject-introspection interface, but I don't really know where to go from here.

**Comment by ro-joshi** [comment]
This workaround fixes the problem for me.  My guess is that if Vips is loaded before a SciPy BLAS function is called, the BLAS library is not loaded/linked properly (possible Vips changing an environment variable??).  If a SciPy BLAS function is called before loading Vips, the BLAS library gets properly linked and loaded.  Any thoughts would be appreciated, though this workaround is fine for now.

```
from scipy import linalg
import numpy as np
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
a = linalg.inv(A)

from matplotlib import pyplot as plt
from sklearn.decomposition import NMF

import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

img = Vips.Image.new_from_file('train_10.bmp') #3 channel RGB image
tmp = img.extract_area(0, 0, 500, 500)
mem_img = tmp.write_to_memory()
np_3d = np.fromstring(mem_img, dtype=np.uint8)
np_3d = np_3d.reshape((500, 500, 3))

for i in range(1,10):
    A = np.log(255 / np_3d)
    nmf = NMF(n_components=2, init='nndsvd', random_state=0, alpha=.1, 
            l1_ratio=1, verbose=10)
    nmf_tfm = nmf.fit_transform(A.reshape(-1, 3))
    nmf_tfm = nmf_tfm.reshape((500, 500, 2))
    plt.figure()
    plt.imshow(nmf_tfm[:, :, 0])
    plt.figure()
    plt.imshow(nmf_tfm[:, :, 1])
    plt.show()
```

**Comment by jcupitt** [comment]
libvips sets the env var `VIPSHOME`, but that's all, I doubt if that's the problem. I think you said the older `vipsCC` Python binding was working, so perhaps the problem is in gobject-introspection? What happens if you just do `import gi` before numpy?

These linking and init problems can get very nasty. The worst one I had was with C++ static init. I was getting a segv when some C++ inside libvips tried to throw an exception when libvips was loaded as a plugin inside mysql. I traced it to a compiler flag that mysql uses to speed up plugin linking, but which breaks the path C++ uses to link code in static init :( that took weeks to find.

**Comment by ro-joshi** [comment]
`import gi` or `from gi.repository import Pango` works fine.  I've also replicated the problem with a reference BLAS library in addition to MKL.  The problems start once `Vips.init(sys.argv[0])` is called in Vips.py.

Like you said, I think this is some complicated thing (maybe PyGI setup?).  If I run Vips, MKL, Scipy, PyGI linked to system gobject-introspection in an anaconda environment everything works fine.  The workaround is simple enough though, so I'm going to table this for now.  Appreciate all the help.

**Comment by jcupitt** [comment]
There's a new libvips binding for Python:

https://pypi.python.org/pypi/pyvips

This one uses cffi instead of gobject-introspection, so it's much, much simpler to install. All you need to do is get the libvips shared library on your system somehow, then `pip install pyvips` and that's it. 

The API is the same, you just need to put `import pyvips` at the top and everything should work. The docs are much better too:

https://jcupitt.github.io/pyvips/
