### ISSUE TITLE
How to force VIPS to use more than 4 CPU efficiently?

### ISSUE THREAD

**Issue by maciej-zabielski** [jcupitt/libvips#595]
Hi,

I'am using vips on system with 12 cpu. Vips is compiled from master, with all latest changes.
When saving tiff to dz format, I've found than vips does not use all available cpu on this system.
To test it I’ve convert one big tiff image and spawn vips several times using different --vips-concurrency values. Source tiff file and destination are located on ram disk, tmpfs type storage so processing should not be limited by HDD latency.

Processing time will be reduced for each additional core, but only up to 4. Going further from there will not give any gain - the processing time will remain the same (see processing times vs number of cores below)

Test mage used has dimensions of 9000x13736, 72dpi, 24bit

```
$ for i in {1..12}; do echo "Proc=$i"; time vips dzsave test.tif test.zip --suffix=.png --vips-concurrency=$i ; done

Proc=1
real    0m24.327s
user    0m24.811s
sys     0m1.369s

Proc=2
real    0m14.921s
user    0m25.885s
sys     0m2.238s

Proc=3
real    0m12.126s
user    0m26.503s
sys     0m2.689s

Proc=4
real    0m11.083s
user    0m27.458s
sys     0m3.425s

Proc=5
real    0m10.995s
user    0m28.819s
sys     0m4.004s

Proc=6
real    0m11.129s
user    0m29.913s
sys     0m4.771s

Proc=7
real    0m11.283s
user    0m30.461s
sys     0m5.338s

Proc=8
real    0m11.657s
user    0m30.767s
sys     0m5.965s

Proc=9
real    0m11.953s
user    0m30.811s
sys     0m6.543s

Proc=10
real    0m12.327s
user    0m31.012s
sys     0m6.928s

Proc=11
real    0m12.521s
user    0m30.875s
sys     0m7.092s

Proc=12
real    0m12.992s
user    0m30.493s
sys     0m7.353s
```
Any ideas on whats causing this limitation and use more cores?
I have tried to disable last single threaded stage of writing compressed PNG image to ZIP file, but that does not change much so it does not seem to be a bottleneck. I've seen this discussion but it's a bit different story (Question: concurrency #561)

Best regards,
Maciej

**Comment by jcupitt** [comment]
Hi @maciej-zabielski,

It's quite hard to extract a lot of parallelism from deepzoom write, unfortunately. It does the read in one set of threads, so it can overlap that (though tiff read is usually very quick, so there's little gain there), and it writes each strip of tiles in parallel, so it can overlap the PNG writes there (PNG write is very, very slow, I'd guess >90% of your CPU time is being spent in libpng).

However, it only keep a single strip of tiles for each pyramid layer, so a set of tiles have to complete before it can move on. This limits concurrency: at the end of the strip you might only be using a single core. 

My work machine has 6 cores (12 threads), I might time on that thing tomorrow. Do you have 12 real cores, or 12 threads? If it's only 6 cores, you often won't see more than a 4x or 5x speedup, because of TurboBoost. A job with just one or two active threads will get a 30% clock boost, when you have all the cores active, you will get a downclock which will limit your maximum speedup.

Yes, zip write is fast (dzsave uses uncompressed zip by default), there's probably no saving there. 

The simplest way to speed up your dzsave would be to turn down PNG compression (the default is 6), or perhaps use another format, if that's possible. For example, for a 10k x 10k RGB image on this laptop I see:

```
$ time vips dzsave ../wtc.tif x --suffix .png
real	0m16.572s
user	0m53.680s
sys	0m1.344s
$ time vips dzsave ../wtc.tif x --suffix .png[compression=0]
real	0m4.875s
user	0m11.420s
sys	0m1.632s
```

JPG is much faster again:

```
$ time vips dzsave ../wtc.tif x 
real	0m2.224s
user	0m3.816s
sys	0m1.208s
```

**Comment by jcupitt** [comment]
I tried on my 6 core, 12 thread desktop machine:

```
$ vipsheader ../wtc.tif 
../wtc.tif: 9372x9372 uchar, 3 bands, srgb, tiffload
$ for i in {1..12}; do echo cpu = $i ...; time vips dzsave ../wtc.tif x --suffix .png --vips-concurrency=$i; rm -rf x*; done
cpu = 1 ...
real	0m59.599s
user	0m58.288s
sys	0m1.312s
cpu = 2 ...
real	0m19.949s
user	0m37.108s
sys	0m0.940s
cpu = 3 ...
real	0m11.284s
user	0m30.256s
sys	0m0.992s
cpu = 4 ...
real	0m9.184s
user	0m31.168s
sys	0m1.168s
cpu = 5 ...
real	0m7.998s
user	0m32.224s
sys	0m1.396s
cpu = 6 ...
real	0m7.506s
user	0m34.652s
sys	0m1.568s
cpu = 7 ...
real	0m6.863s
user	0m35.520s
sys	0m1.740s
cpu = 8 ...
real	0m6.615s
user	0m37.524s
sys	0m1.800s
cpu = 9 ...
real	0m6.474s
user	0m38.996s
sys	0m1.944s
cpu = 10 ...
real	0m6.402s
user	0m39.740s
sys	0m2.056s
cpu = 11 ...
real	0m6.541s
user	0m40.892s
sys	0m2.336s
cpu = 12 ...
real	0m6.623s
user	0m40.576s
sys	0m2.464s
```

I'm not sure why cpu=1 is so slow, that's curious, but overall I'm seeing about a 5x speedup, which seems roughly correct for a 6 cpu machine. 

What processor are you using? This is a E5-1650 @ 3.20GHz.

**Comment by maciej-zabielski** [comment]
HI @jcupitt, I appreciate your interactive feedback and thanks for the tips :)

I’am using Dell PowerEdge R710 serwer, with Intel Xeon CPU X5670 @ 2.93GHz
This server is a host for Hyper-V, and there is only one virtual machine with latest version of Centos ( x64 ) Cpu has 6 cores, and by default logical hyperthreading was enabled. So after reboot, I’ve disabled hyperthreading in bios and repeated the test. Nothing changes, everything remains nearly the same.

After looking in google, found suggestion about power profile. There are several modes, and default value was “Dell Active Power Control”.
Dell Active Power Control (or DAPC), relies on a BIOS-centric power control mechanism which offers excellent power efficiency advantages with minimal performance impact in most environments, and is the CPU Power Management choice for this overall System Profile.

Performance model is described in next words:
Performance profile provides potentially increased performance by maximizing processor frequency and the disabling certain power saving features such as C-states. Although not optimal for all environments, this is an excellent starting point for performance optimization baseline comparisons.

After switching to “Maximal Performance mode” times for vips processing was reduced twice. Current values are bellow.

Could you perform test on attached tiff file? 
[test.zip](https://github.com/jcupitt/libvips/files/748119/test.zip)

Attached is also screen from ‘top’ application taken when vips is working with 6 cores. All tests were made in the directory /tmp
![vips12](https://cloud.githubusercontent.com/assets/25347055/22555243/575f0e2e-e963-11e6-8094-5e975150a13e.png)

```
$df -hT
Filesystem                                Type            Size  Used Avail Use% Mounted on
….
tmpfs                                     tmpfs           2.0G   11M  2.0G   1% /tmp


$ for i in {1..12}; do echo "cpu=$i ...."; time vips dzsave test.tif test.zip --suffix=.png --vips-concurrency=$i ; done

cpu=1 ....
real    0m12.136s
user    0m12.380s
sys     0m0.851s

cpu=2 ....
real    0m7.788s
user    0m13.113s
sys     0m1.199s

cpu=3 ....
real    0m6.392s
user    0m13.447s
sys     0m1.422s

cpu=4 ....
real    0m6.067s
user    0m13.849s
sys     0m1.773s

cpu=5 ....
real    0m6.062s
user    0m14.493s
sys     0m2.115s

cpu=6 ....
real    0m6.276s
user    0m15.141s
sys     0m2.543s

cpu=7 ....
real    0m6.332s
user    0m15.186s
sys     0m2.725s

cpu=8 ....
real    0m6.579s
user    0m15.388s
sys     0m3.075s

cpu=9 ....
real    0m6.668s
user    0m15.429s
sys     0m3.231s

cpu=10 ....
real    0m6.996s
user    0m15.453s
sys     0m3.535s

cpu=11 ....
real    0m7.046s
user    0m15.580s
sys     0m3.581s

cpu=12 ....
real    0m7.133s
user    0m15.482s
sys     0m3.765s
```

**Comment by jcupitt** [comment]
Oh, interesting. I wonder if it could be a Hyper-V issue as well? You could try another hypervisor I guess, or maybe a bare metal install. Your user time is half mine, so you'd think there might be another x2 speedup somewhere. 

Sure, I'll try your tiff tomorrow at work.

**Comment by jcupitt** [comment]
Oh dear, sorry @maciej-zabielski :( this dropped off my radar.

I tried with vips8.5 on my 6 core Ubuntu 17.04 desktop and I see:

```
$ for i in {1..12}; do echo cpu = $i ...; time vips dzsave test.tif x --suffix .png --vips-concurrency=$i; rm -rf x*; done
cpu = 1 ...
real	0m10.864s
user	0m11.068s
sys	0m0.844s
....
cpu = 7 ...
real	0m3.131s
user	0m12.844s
sys	0m2.332s
```

So about a 3.5x speedup.

I had a look at your tiff and it's using LZW compression, single image plane:

```
$ tiffinfo test.tif 
TIFF Directory at offset 0x8 (8)
  Subfile Type: (0 = 0x0)
  Image Width: 9000 Image Length: 13736
  Resolution: 72, 72 pixels/inch
  Bits/Sample: 8
  Compression Scheme: LZW
  Photometric Interpretation: RGB color
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Rows/Strip: 19
  Planar Configuration: single image plane
```

This hurts speed slightly: libtiff only allows one reader at once, so threads have to queue up on image decompression. If I use an uncompressed tiff I see:

```
$ vips copy test.tif test2.tif
$ for i in {1..12}; do echo cpu = $i ...; time vips dzsave test2.tif x --suffix .png --vips-concurrency=$i; rm -rf x*; done
cpu = 1 ...
real	0m10.793s
user	0m10.772s
sys	0m0.884s
........
cpu = 9 ...
real	0m2.957s
user	0m12.740s
sys	0m2.896s
```

About a 3.65x speedup, a little better. I'm not sure why you're only seeing 2x.

**Comment by kmartinez** [comment]
Hi - if your server r710 has the usual pair of X5670 then its dual six-core - and as John says its difficult to get anything like 10x speed-up in that case - especially when spending a lot of time in libpng. It doesn't look like your run is very I/O bound - or I'd suggest SSD/nVME or even ramdisk as a test (easier to test on a desktop!). We had a big issue with PNG compression CPU usage in our current imaging project - so have another look at that...
