### ISSUE TITLE
Horizontal lines during shrink

### ISSUE THREAD

**Issue by tidus8** [jcupitt/libvips#596]
Hi all,

I have a problem when I try to shrink a picture (vips shrink).
It could happen that in modified picture I can see some horizontal lines.

Example:
Original picture: 1920 X 2250
I shrink it by a scale factor of 4.17 (because I want it 460 X 539)
I obtain a picture with right dimensions but with some horizontal empty lines

Can anyone help me?

Thanks
Marco

**Comment by tidus8** [comment]
I can add this:

vips warning: linecache: error reading tile 0x792: vipspng: out of order read at line 816

vips warning: linecache: error reading tile 0x800: vipspng: out of order read at line 816

vips warning: linecache: error reading tile 0x992: vipspng: out of order read at line 1016

vips warning: linecache: error reading tile 0x1000: vipspng: out of order read at line 1016

vips warning: linecache: error reading tile 0x1192: vipspng: out of order read at line 1216

vips warning: linecache: error reading tile 0x1200: vipspng: out of order read at line 1216

vips warning: linecache: error reading tile 0x1392: vipspng: out of order read at line 1416

vips warning: linecache: error reading tile 0x1400: vipspng: out of order read at line 1416

vips warning: linecache: error reading tile 0x1592: vipspng: out of order read at line 1616

vips warning: linecache: error reading tile 0x1600: vipspng: out of order read at line 1616

vips warning: linecache: error reading tile 0x1792: vipspng: out of order read at line 1816

vips warning: linecache: error reading tile 0x1800: vipspng: out of order read at line 1816

vips warning: linecache: error reading tile 0x1992: vipspng: out of order read at line 2016

vips warning: linecache: error reading tile 0x2000: vipspng: out of order read at line 2016
![dcl431c_8264_13640_f_modify](https://cloud.githubusercontent.com/assets/4437212/22554888/118dd71e-e962-11e6-90fc-a1c88026aaee.png)

**Comment by jcupitt** [comment]
Hi @tidus8, `shrink` is very low-level, it does integer factors only. It allows float factors for compatibility with some very old code, but you shouldn't really use it with float factors. 

If you are trying to resize images, `resize` does straightforward up/down scaling, or `vipsthumbnail` does everything (it does `resize`, but also handles transparency, colour management, shrink-on-load, and so on).

```
$ vipsheader x.png
x.png: 1920x2250 uchar, 3 bands, srgb, pngload
$ vips resize x.png y.png .2398081534
$ vipsthumbnail x.png --size 460x539 -o y.png
```

`shrink` should not have failed like that, it looks like it has the wrong cache hint set, I'll fix it.

Thanks for reporting this!

**Comment by jcupitt** [comment]
Please reopen if this isn't resolved.
