### ISSUE TITLE
Transparent PNG tile borders using dzsave

### ISSUE THREAD

**Issue by sickrandir** [jcupitt/libvips#599]
I noticed a quality issue when generating tiles with dzsave with a PNG source image with transparent borders.
It seems that when borders are bright, in low res generated tiles a darker border appear. I think it is something related with the "matte" settings during the scaling operation but I didn't find no option related to the matte of PNG images in libvips. 
Here you can see one example of source I'm using: https://dl.dropboxusercontent.com/u/3093480/COL1C-CMBSD_ATX-CNC-LI0-LNS-017.png
And here you can find the output produced with dzsave and options: 
options = { "suffix" => ".png[compression=9]" , "overlap" => 2, "tile_size" => 1024}

Dzi: https://dl.dropboxusercontent.com/u/3093480/COL1C-CMBSD_ATX-CNC-LI0-LNS-017.dzi.zip

**Comment by jcupitt** [comment]
Hi @sickrandir, I tried your image, and I see this:

```
$ vips dzsave COL1C-CMBSD_ATX-CNC-LI0-LNS-017.png x --suffix=.png
```

Then here is tile `x_files/10/0_0.png`: 

![0_0](https://cloud.githubusercontent.com/assets/580843/23122192/1d24dc4c-f75b-11e6-9416-6f92e1e5a769.png)

I agree, there's a dark border when viewed in a web browser (though not in the file, if you drop transparency). I think maybe dzsave needs to premultiply the alpha during shrink. I'll experiment. Thanks for pointing out this problem. 

In the meantime, you could do the premultiply yourself. If I run:

```
$ vips premultiply COL1C-CMBSD_ATX-CNC-LI0-LNS-017.png x.dz[suffix=.png]
$ cd x_files/10/
$ vips unpremultiply 0_0.png x.png
```

I see this for `x.png`:

![x](https://cloud.githubusercontent.com/assets/580843/23122551/96b53fec-f75c-11e6-9e3b-f6cc1a49d375.png)

Of course running every output tile though unpremultiply is very annoying, unfortunately.

**Comment by sickrandir** [comment]
That's very interesting and it looks promising. I don't mind using the workaround while you experiment to fix the problem however I'll need to set the compression level like I did in dzsave but I don't see the option with premultiply. The images generated like this are just too big for my use case. Thanx a lot for your time and effort!

**Comment by jcupitt** [comment]
You just do:

```
$ vips premultiply COL1C-CMBSD_ATX-CNC-LI0-LNS-017.png x.dz[suffix=.png[compression=9]]
```

You'll need 8.4 -- I think older vipses didn't support nested `[]`.

**Comment by sickrandir** [comment]
Ok, I'll try that! I'm doing some tests with another workflow just shrinking the same PNGS before making tiles with dzsave. It seems that the dark border is added also in the resizing process (I used the resize method).

**Comment by jcupitt** [comment]
Yes, resize on its own is not enough, you need to bracket it with a premultiply or you'll get dark borders on high-contrast transparent edges.

**Comment by jcupitt** [comment]
OK, fixed in git master, I think. It'll be in 8.5, due in a couple of weeks. 

Thanks for finding and reporting this error, @sickrandir !

**Comment by sickrandir** [comment]
Hey, that was fast! Thanks to you! Does it mean that now premultiply is not needed anymore also for the resize method? Thank you

**Comment by jcupitt** [comment]
Yes, `dzsave` does the premultiply / unpremultiply for you now.

**Comment by sickrandir** [comment]
Yes, I got the dzsave part. I meant if premultiply is not needed when using resize for transparent pngs, not dzsave.

**Comment by jcupitt** [comment]
Yes, no longer needed.
