### ISSUE TITLE
Question: RAW -> JPEG works but not RAW -> PNG

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#600]
I feel like I've been through this before but if you'll forgive me. I have a [U16 RAW image](https://github.com/jcupitt/libvips/files/770918/barbara-u16-512x512.raw.tar.gz) and when I convert it to JPEG it comes out just fine; convert it to PNG however and it appears all black.

```
vips rawload barbara-u16-512x512.raw barbara-u16-512x512.raw.vips 512 512 2

# Produces the correct image
vips copy barbara-u16-512x512.raw.vips barbara-u16-512x512.raw.jpeg --format=ushort --bands=1

# Produces a black image
vips copy barbara-u16-512x512.raw.vips barbara-u16-512x512.raw.png --format=ushort --bands=1
```

The only thing that is odd about it is that the actual range is 256 (I also have others that have a range of 4k). What I don't quite understand is why conversion to JPEG works but not PNG. I'd have thought if there was an "issue" it would be evident either way?

Thanks as always,

Simon

**Comment by jcupitt** [comment]
Hi Simon, yes, your image has 0 in all the even bytes. Could it maybe be least-significant byte first? Then byteswapping would give you 0 - 65535. 

You also need to tag 16 bit image as `GREY16`, or vips will think it's an 8-bit image that happens to be in a 16-bit container. 

```
john@kiwi:~/pics$ vips rawload barbara-u16-512x512.raw b1.v 512 512 2
john@kiwi:~/pics$ vips copy b1.v b2.v --format=ushort --bands=1 --interpretation=grey16
john@kiwi:~/pics$ vips byteswap b2.v b3.tif
```

And the `.tif` file looks sensible.
