### ISSUE TITLE
Cannot set temp in an XYZ2Lab conversion from C++

### ISSUE THREAD

**Issue by sprock** [jcupitt/libvips#603]
Hello,
I'm trying to set temperature in an XYZ2Lab conversion like this:

`#include <stdio.h>
#include <stdlib.h>
#include <vips/vips8>

//#include <iostream>

using namespace vips;

int
main (int argc, char **argv)
{
  if (VIPS_INIT (argv[0]))
    vips_error_exit (NULL);

  try
  {
    if (argc < 4)
      throw (VError ("args: in out cct"));

    double vad[3];
    vad[0]=109.85;
    vad[1]=100.00;
    vad[2]=35.58;

    VipsArrayDouble* illuminant = vips_array_double_new(vad,3);
    
    VImage in = VImage::new_from_file (argv[1]);
    VImage out1 = in.sRGB2scRGB()
      .scRGB2XYZ();
    VImage out=out1.XYZ2Lab(VImage::option()->set("temp",illuminant));
    out.write_to_file (argv[2]);

  }
  catch (const VError & e)
  {
    printf ("%s\n", e.what ());
  }

  return (0);
}
`
It compiles, but on execution returns this warning:

GLib-GObject-WARNING **: unable to set property 'temp' of type 'VipsArrayDouble' from value of type 'gboolean'

and the output image is identical to the input.

Am I doing something wrong?

Thanks,
sprock
vips-8.4.1 on FreeBSD 10.3

**Comment by lovell** [comment]
Hello, you should be able to use the `std::vector` type for this, something like (untested):
```cc
std::vector<double> illuminant { 109.85, 100.00, 35.58 };
```

**Comment by jcupitt** [comment]
Hi, yes @lovell is right, you can just pass a `std::vector<double>` to `set()`. I tried:

```c++
/* compile with
 *
 *      g++ -g -Wall temp.cpp `pkg-config vips-cpp --cflags --libs`
 */

#include <stdio.h>
#include <stdlib.h>
#include <vips/vips8>

using namespace vips;

int
main (int argc, char **argv)
{
        if (VIPS_INIT (argv[0]))
                vips_error_exit (NULL);

        try {   
                if (argc < 3) 
                        throw (VError ("args: in out"));

                VImage in = VImage::new_from_file (argv[1]);
                
                VImage out = in.sRGB2scRGB().scRGB2XYZ();
                out = out.XYZ2Lab(VImage::option()->
                        set("temp", std::vector<double> { 109.85, 100.00, 35.58 })); 
                out.write_to_file (argv[2]);
        }
        catch (const VError &e) {
                printf ("%s\n", e.what ());
        }

        return (0);
}
```

And it seems to work.

This isn't a great way to change colour temperature, I expect you know. I would calculate the x/y/z d0 from the cct, then go via Bradford cone space. There's some code to do this in nip2, but it's not made it into libvips yet. 

https://github.com/jcupitt/nip2/blob/master/share/nip2/start/Colour.def#L207

**Comment by sprock** [comment]
Hello,

Lovell Fuller <notifications@github.com> writes:

> Hello, you should be able to use the std::vector type for this, something like (untested):
>
> std::vector<double> illuminant { 109.85, 100.00, 35.58 };

That works perfectly.  Thank you.

Roger

**Comment by sprock** [comment]
Hello John,

John Cupitt <notifications@github.com> writes:

> Hi, yes @lovell is right, you can just pass a std::vector<double> to set(). I tried:
>
> /* compile with
>  *
>  *      g++ -g -Wall temp.cpp `pkg-config vips-cpp --cflags --libs`
>  */
>

[snip]

It works here too.  Thanks.

> This isn't a great way to change colour temperature, I expect you know. I would calculate the x/y/z
> d0 from the cct, then go via Bradford cone space. There's some code to do this in nip2, but it's not
> made it into libvips yet.
>
> https://github.com/jcupitt/nip2/blob/master/share/nip2/start/Colour.def#L207

Yes, I realise the method is crude but I don't know my way round the
various colour models and was hoping this quick & dirty hack would
suffice.  My tests indicate otherwise.  I'm trying to correct
differences betwen (microscope) images that will be mosaiced so they all
have the same colour temp, as you no doubt guessed.  Another obvious
remedy might be to run the microscope illumination from a stabilised
power supply, just in case that is the cause of the image-to-image
variation.  But I digress.

Thanks again,
Roger

**Comment by jcupitt** [comment]
I'd white-balance in camera space. The steps would be:

* capture in sRGB
* linearize to scRGB (you'll need to find out exactly what kind of gamma your camera puts on, hopefully just standard sRGB)
* subtract a lens-cap black (you may not need this)
* correct vignetting (the darkening of the field towards the edges of the frame)
* white balance (you'll need a pic of a white standard, and a reasonably stable light source)
* save corrected frames as sRGB again

You could also consider correcting lens aberration, I've no idea if this is an issue with microscopes. Anyway, do all that and they should mosaic nicely.

**Comment by sprock** [comment]
Hello John,

John Cupitt <notifications@github.com> writes:

> I'd white-balance in camera space. The steps would be:
>
> * capture in sRGB 
> * linearize to scRGB (you'll need to find out exactly what kind of gamma your camera puts on,
>  hopefully just standard sRGB) 
> * subtract a lens-cap black (you may not need this) 
> * correct vignetting (the darkening of the field towards the edges of the frame) 
> * white balance (you'll need a pic of a white standard, and a reasonably stable light source) 
> * save corrected frames as sRGB again 

Thank you.  That looks very doable.  The problem I'm seeing with colour
balance only seems to afflict a few frames per mosaic, which is why I
wonder about camera or light source (electrical) stability.

> You could also consider correcting lens aberration, I've no idea if
> this is an issue with microscopes.  Anyway, do all that and they
> should mosaic nicely.

I have wondered about this but the mosaics I've made so far don't appear
to suffer from lens aberration.  I'm using an occular in the trinocular
head that appears to take out of the chromatic and spherical aberration.
It should be possible to check for the latter by collecting both SEM and
optical images of the same regions and doing some distance measurements
on the images.  

Thanks again, and please close this issue.

Roger

**Comment by jcupitt** [comment]
It could be scatter as well. You may find light in bright areas scatters in the optics and around the barrel, bringing up the levels in the dark areas. If you try to mosaic with a tile which is mostly dark, you'll find the blacks are off. A simple first-order correction is just to subtract a proportion of the scene average. 

Good luck!
