### ISSUE TITLE
libMagick error: UnableToExtendCache. No space left on device

### ISSUE THREAD

**Issue by bender22** [jcupitt/libvips#604]
Hi John,

I'm using vips in Windows Azure Cloud Service. When tiling .psb image (23000x16000 pix) I got the following error:

magick2vips: unable to read file ""C:\Resources\directory\df63910619a94db8bc2023c74b3d68e1.EasyZoom.Tiler.LocalStorage\f3af0cd4-4dd5-4d38-85d2-8f7061b4fdc8.psb""
libMagick error: UnableToExtendCache `C:\Resources\directory\df63910619a94db8bc2023c74b3d68e1.EasyZoom.Tiler.LocalStorage\f3af0cd4-4dd5-4d38-85d2-8f7061b4fdc8.psb': No space left on device @ error/cache.c/OpenPixelCache/3689 (null)

Seems it's a problem of ImageMagick related to cache extending, but the thing is that CloudService has 40 Gb HDD (and 3.5Gb RAM) which is more than enough. On top of that, I tested it on a machine with 15 Gb HDD (and 1 Gb RAM) and there were no errors from vips.
From the other side when I used Photoshop and cut the canvas to 18000x14000 it worked perfectly in Azure. So, it seems to be related to lack of some resources, but I can't work out which. Any ideas what the problem could be?

image link: https://1drv.ms/u/s!AhuHvLqvJ4rHiB6bIobbZSfZQ7ME

Thanks in advance,
Alex

**Comment by jcupitt** [comment]
Hi Alex,

I tried your image here:

```
$ vips magickload testLarge.psb x.v
```

and it needed 3gb of ram for the conversion, so I think it's just running out of memory. You'll need to make imagemagick use the disc as a cache.

**Comment by bender22** [comment]
I run it (magickload testLarge.psb) on 1 Gb RAM machine - after about 10 minutes it generated a ~1,5 Gb file. As far as I know if imagemagick can't get enough memory it extends a cache and uses HDD, which is times slower but works. What's interesting that I don't have any specific config for imagemagick, so it's out-of-the-box behavior. But for some reason, it finds Azure Clour Service specific environment and doesn't work there. Is there any way to configure imagemagick when running it from vips?

**Comment by jcupitt** [comment]
On linux you set environment variables: 

```
export MAGICK_AREA_LIMIT=1024mb
```

means use no more than 1gb of ram. On Windows I think you can set some registry entries, or maybe env vars work too? There's another variable you can set to say where to keep any temp files.

**Comment by bender22** [comment]
I'm closing the issue because could not reproduce it anywhere except Azure, even with fewer RAM/HDD. No idea that's wrong with their environment, but it's not related to vips anyway

**Comment by HFrifelt** [comment]
I can add to this that it is indeed an azure specific error. The error is a bit misleading, but in my situation it was an access issue. The cache was located on a D:/ drive under users/.../.../.../2/temp... the point is that when you run the command through a cloud service, you don't have access to write to this folder. The fix for me was to use the command  -define registry:temporary-path={PathToLocalStorage}

Note: If you remote desktop to the service and try to run the magick command in cmd it wont fail, even without the temporary path as you obviously the correct access rights.

**Comment by bender22** [comment]
Hi @HFrifelt, 
Could you please tell how/where do you run this command? Can't find anything about it

**Comment by HFrifelt** [comment]
It didn't work when I defined it in the policy.xml for some reason, so I run it directly on the convertion command.

For example:
magick.exe convert -define registry:temporary-path={localPath]  -strip -auto-orient -resize X800 -quality 50% inputFilePath outputFilePath

**Comment by bender22** [comment]
I see, thanks! @jcupitt, is that possible to pass this setting when calling vips in a console?

**Comment by jcupitt** [comment]
libvips has its own copy of ImageMagick. Try changing the `policy.xml` in `vips-dev-8.5/etc/ImageMagick-6`.
