### ISSUE TITLE
VIPS fails to load TIFF file

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#605]
[Here](https://filebin.net/a4lfwdv4obwq6jpm) is an example of TIFF file that

    vips_image_new_from_file()

fails to load. The file can be opened correctly ex. with OSX preview application.

The problem might be connected with a NULL embedded ICC profile, however this example might also point to some weakness in the TIFF loader, so I provide it in case you want to investigate...

Thanks!

**Comment by jcupitt** [comment]
You're right, the empty profile was stopping the load. It seems to work now.

**Comment by aferrero2707** [comment]
I will check as soon as I manage, and let you know. Thanks!

**Comment by jcupitt** [comment]
This is in the 8.5 beta now, so I'll close.
