### ISSUE TITLE
How to fix a given tiles misalignment in a mosaic

### ISSUE THREAD

**Issue by alonit** [jcupitt/libvips#606]
Hi,

I'm using vips 8.4.4 C API on Windows 64bit OS, where `vips_mosaic `is being used for joining many small images (tiles) together to make one smooth seam large image.

The small images produced by a scanner machine, so that there is misalignment between successive images in both x and y axis.

This misalignment originated from:
1. static misalignment: the camera/xy_stage misalignment. xy_stage moves the slide in x and y axis and the camera is fixed and mounted on top on the microscope.
2. dynamic misalignment: natural shakes of the scanner machine (due to mechanical part movement, not stabilized table, buildings structure fluctuations (where the scanner is located) , etc..)

Given this, for every new tile that should be added to the mosaic, the `vips_mosaic `ref `and `sec` tie points should be calculated to fix this offset, so each successive tile will be positioning as close as possible to its neighbor tile in the mosaic, otherwise the resulted mosaic tiles will not be merged smoothly.

I think about the following solution for this calculation: 
assume we need to mosaic two tile horizontally:
for each new tile that should be added to the mosaic: go to the mosaic and extract the last column line where the new tile should be joined. this line should be composed of data (no black pixels), and a mosaic background (black pixels). The black are in the line told us the offset, so that the real data in the mosaic starts where the black pixel end in the column. the tie point should be calculated relative to the founded real data start point.

and in terms of vips operations:

1. call `vips_crop ()` to crop the last column in the mosaic (mosaic most left or most right column - depend on the side where the tile should be added, left or right)

2. call `vips_min ()` on the column line to get array of its zero's pixels (the offset area) and their corresponding (x,y) positions.

3. iterate over this zero's array, and find where the real data starts => this is the position where the mosaic tie pixel point should be referenced (and be used to tie the corresponded new added tile).

Is this right for vips? Can I use vips in other (efficient) way to fix this misalignment in term of vips best practice and performance - I suspect that step 3. does not scales as it iterates over each pixel in the zero's array? in addition I will need to crop a mosaic line and calc. min and iterate over the min. array for each new tile arrived which also might not scales.

your kind support would be highly appreciated

Thank you

**Comment by jcupitt** [comment]
Hi, you can just call `vips_mosaic()` repeatedly, it does a search for tie-points for you. The ref and sec that you give just suggest a start point for the search. How large are your overlaps? By default, `vips_mosaic()` likes 60 pixels or so. 

Building a mosaic as a set of pairwise joins has some limitations. If you join long rows of tiles (perhaps 20 tiles) left-right, then try to join two rows top-bottom, you'll find the accumulated 0.5 pixel errors from the left-right joins are enough to cause visible artifacts in the top-bottom join. 

The solution is to spread the small errors out so they are not visible. A simple way to do this is to join in small square groups, so you take the four tiles from the top-left:

```
A B 
C D
```

And join AB and CD left-right, then join AB - CD top-bottom. Repeat for the next four, and so on across the whole image. Now just repeat the process, treating ABCD as a single tile. 

A better solution is to do whole-mosaic optimisation. Load all the tile edges, do all the tie-point searching, and put all of the best overlaps into a large matrix. Solve with least-mean-square (SVD) to find the set of tile positions that minimise the maximum error.

**Comment by alonit** [comment]
Thanks for the fast response and for the proposed solutions - I will check if I can adopted them easily into the system.

Regarding your questions: 
Each tile is 8bit RGB, 2356 by 1772 pixels with overlap of about 80 pixels. `hwindow `is 5 and `harea `is 14 for the `vips_mosaic`.

Each row or column length can varied from few tiles to even 60 tiles. Typical misalignment offset between two neighbor tile is about 4 pixels.

For example, row with 40 tiles gets a total offset of 4*40=160 pixel just for the offset:
After tiling the 30th tile we accumulate offset of 30x4=120 pixels. The new 31th tile `sec` tie point is far from the 30th tile `ref` point, and even increased search box is not useful.

When trying to join two rows with this offset in each of them, a given overlap of 80 pixels is not enough - I think the overlap should be (80 + 160) - therefore, the tie points (`ref`, `sec`) are out of each other range, so that even increased search box cannot find the real tie point.

The misaligned mosaic problem raised also on small mosaics (12 by 8 tiles) given the above parameters. The problem is seen when joining two rows (12 tiles each,  total offset 12*4=48 pixels, 80 pixels overlap,  `hwindow `is 5 and `harea `is 14) - the rows are misaligned.

**Comment by jcupitt** [comment]
You need to adapt your coordinates as you go. After each join, read the alignment that mosaic found (look at the xoffset/yoffset fields), and update the position of that tile. When you do the next join, take that offset into account.

```
$ vips mosaic k2.jpg k4.jpg x.v horizontal 1000 10 10 10 
$ vipsheader -a x.v
...
xoffset: 985
yoffset: 0
```

xoff/yoff give the final position of sec in relation to ref.

The vips mosaic functions don't do sub-pixel alignment, so you can expect to get 0.5 pixels error per join, so 20 pixels over 40 tiles. As I said, the trick is to spread the error out.

**Comment by alonit** [comment]
Thank you very much. I'll try xoff/yoff as well as the spreading trick and let you know.

**Comment by alonit** [comment]
I have 3 tiles with about 4 pixels physical misalignment in y axis, each is 2356x1772 in size with horizontal overlap of about 94 pixels.

The tiles are joined from left to right using `vips_mosaic`, where the tie point defined to be the top_right corner of the left image.

The process is as follows:
1. `ref `tile image loaded: size: 2356x1772 , xoffset:2356 , yoffset:1772
2. `sec `tile image loaded: size: 2356x1772 , xoffset:2356 , yoffset:1772

3. call `vips_mosaic `on both `ref `and `sec`:

```
asi_vips_mosaic(ref, sec, &out, horizontal,
			xref(2356), yref(0), xsec(94), ysec(0),
			hwindow(5),
			harea(14));
```

`out `image: size: 4610x1776, xoffset:2254, yoffset:0

`out `image has 1776 pixels in height => this is the physical offset in y axis, although its direction is unknown (up offset, or down offset between `ref `and `sec`). On the other hand, this offset doesn't reflects in `yoffset` as its value is 0.

`ref`, `sec `and `out` files are attached. It can be seen in `out `that the y offset was detected by `vips_mosaic`, but this is not reflected in `out` header properties, that should be used for next tiles.

![ref](https://cloud.githubusercontent.com/assets/21310386/23166401/32dd8a2c-f849-11e6-9b93-7cbe96e321cb.jpg)
![sec](https://cloud.githubusercontent.com/assets/21310386/23166402/32e05c20-f849-11e6-922d-c96e4d89927d.jpg)
![out](https://cloud.githubusercontent.com/assets/21310386/23166403/32e21c90-f849-11e6-917c-6a13afe2f999.jpg)

**Comment by jcupitt** [comment]
Oops, you're right, funny, I thought it did record there, it's a while since I looked at this.

You'll find the correct detected offset in the image history. For your images I see this line:

```
#LRJOIN </data/john/pics/left.jpg> </data/john/pics/right.jpg> <mosaic-temp-0> <2253> <-4> <10>
```

But that's very irritating to parse. I'll make it use offset instead.

**Comment by alonit** [comment]
Thanks. 

In which version you think it will be implemented? Can you please publish this change locally (before a formal vips release) so I can use and test it in my system?

Where I can find and access this image history?

Thanks again :)

**Comment by alonit** [comment]
Oh, just to update that I found the image history under vips_image_get_history() - looks very helpful as debug information.

**Comment by alonit** [comment]
Hi @jcupitt,

Seam that I have to option to procees with the offset - parse it from history or wait for the change. It will be very helpul for me if you can tell when this change will be ready ( in terms of new vips version, or local publish that I can test and use) as it is very importent for our project timeline.

Many thank for your support.

**Comment by jcupitt** [comment]
Hi, I fixed it in git master. It was actually a bug, it was setting xoff / yoff, but due to an oversight in the clipping, it failed for negative offsets.

**Comment by alonit** [comment]
O.K. Thanks.

I'm working on Windows 64bit OS with MSVC compiler. How can I take and use this fix. Is there a build for Windows?

Thanks again

**Comment by jcupitt** [comment]
This thing makes the win binary:

https://github.com/jcupitt/build-win64

It all runs inside a docker container, so there's nothing to install (other than docker), it's a one-line command to do everything, and your host machine is not disturbed. 

You'd need to make an 8.5 and get it to build from git (not hard). I can make a test build of 8.5 later, if you like.

**Comment by alonit** [comment]
Oh, sorry, I'v no experience using docker to build binaries. It would be great if you could build this fix inside 8.5 for Windows 64bit.

Thanks

**Comment by jcupitt** [comment]
I put up a test win64 build of 8.5 here:

http://www.vips.ecs.soton.ac.uk/development/8.5/

Let me know if it works. I added an 8.5 build tree to build-win64, so it should be simple for you to rebuild, if you need to.

**Comment by alonit** [comment]
Thanks. I'll test this tomorrow and let you know.

**Comment by alonit** [comment]
Thanks for fast fix, it works well for me - image load, mosaic, dz pyramid etc.. !

Regarding specific offset fix, it seems now that the (xoffset,yoffset) are the final `sec` tie point the mosaic decided on => (xoffset,yoffset) point holds the coordinate of the vector starts at mosaic `out` (0,0) point and ends at final `sec `tie point, so that (xoffset,yoffset) point are not local offset from `ref `tie point, but a point in `out `mosaic that `ref `tie point is fit exactly to here (the real `sec` tie point). Am I right ? Is this how it should behave?

Thanks

**Comment by jcupitt** [comment]
Yes, it's the vector to add to (0, 0) in `ref` to get to (0, 0) in `sec`, if I understand you correctly. It was the position of `sec` in `out`, but that wasn't always useful, since you didn't know where `ref` was if `sec` was moved upwards. 

To work out where the two images ended up, you need to make two rectangles and find the bounding box. Something like:

```
rect1 = { 0, 0, ref.width, ref.height }
rect2 = { out.xoffset, out.yoffset, sec.width, sec.height }
rect3 = rect1.boundingbox(rect2)
```

Now `rect3` should be the size of `out`, and (rect3.left, rect3.top) is the vector from (0, 0) in `ref` to (0, 0) in `out`. I hope I have that right.

**Comment by alonit** [comment]
I'll check this out.

When I first load two images `ref `and `sec `from files I get the xoffset/yoffset initialized with the xsize/ysize of them.
These offsets are expected to be zero's (I think) as no mosaic have been made so far on them, and just the `out` should have the offsets. Am I right?

Thanks

**Comment by jcupitt** [comment]
Ooof, oh dear, I should have replied to this too.

1. Yes, I see `xoffset` 0 everywhere after load. I tried: 

```
$ vipsheader -a *.v | grep xoff | wc
     58     174    1260
```

So I have 58 vips image files with xoffset. 

```
$ vipsheader -a *.v | grep xoff | grep -v 0 | wc
      0       0       0
```

But 0 of them aren't set to zero.

2. After a mosaic, the xoff / yoff give the actual offset used. It's after correction, and it's just info given back to the caller.
