### ISSUE TITLE
memory leak in vips ( file reorder.c )

### ISSUE THREAD

**Issue by gczuba** [jcupitt/libvips#607]
Hi

I've found memory leak in vips file libvips/iofuncs/reorder.c
( multiple leaks during dzsave operation )

Current version of vips don't free arrays stored in pointers:
 reorder->input
 reorder->source
 reorder->cumulative_margin

My very simple solution is to free memory using code like this.

       if ( reorder->input ) VIPS_FREE( reorder->input );
       if ( reorder->score ) VIPS_FREE( reorder->score );
       if ( reorder->recomp_order ) VIPS_FREE( reorder->recomp_order );

        reorder->input = VIPS_ARRAY( NULL, reorder->n_inputs + 1, VipsImage * );
        reorder->score = VIPS_ARRAY( NULL, reorder->n_inputs, int );
        reorder->recomp_order = VIPS_ARRAY( NULL, reorder->n_inputs, int );

       if( reorder->source ) VIPS_FREE( reorder->source );
        reorder->source = VIPS_ARRAY( NULL, total + 1, VipsImage * );
       if( reorder->cumulative_margin ) VIPS_FREE( reorder->cumulative_margin );
        reorder->cumulative_margin = VIPS_ARRAY( NULL, total, int );

Regards
Grzegorz

**Comment by jcupitt** [comment]
Ooop, you're right. Thanks! It seems to be fixed in master now:

```
$ valgrind --leak-check=full vips dzsave k2.jpg x
==9352== Memcheck, a memory error detector
==9352== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==9352== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==9352== Command: vips dzsave k2.jpg x
==9352== 
memory: high-water mark 8.82 MB
==9352== 
==9352== HEAP SUMMARY:
==9352==     in use at exit: 901,320 bytes in 8,939 blocks
==9352==   total heap usage: 180,655 allocs, 171,716 frees, 36,285,705 bytes allocated
==9352== 
==9352== LEAK SUMMARY:
==9352==    definitely lost: 0 bytes in 0 blocks
==9352==    indirectly lost: 0 bytes in 0 blocks
==9352==      possibly lost: 0 bytes in 0 blocks
==9352==    still reachable: 160,940 bytes in 1,882 blocks
==9352==                       of which reachable via heuristic:
==9352==                         newarray           : 1,536 bytes in 16 blocks
==9352==         suppressed: 636,404 bytes in 6,323 blocks
==9352== Reachable blocks (those to which a pointer was found) are not shown.
==9352== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==9352== 
==9352== For counts of detected and suppressed errors, rerun with: -v
==9352== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 24 from 24)
```

**Comment by gczuba** [comment]
Thanks for fast correction in master repo.

Regards
