### ISSUE TITLE
rotate on portrait images together with crop fails at vipsthumbnail

### ISSUE THREAD

**Issue by ElHeineken** [jcupitt/libvips#608]
I'm currently in the process of developing a piwigo extension utilizing vipsthumbnail. A quick prototype (mimicking external imagemagick-calls) has been successful (and really fast) so far, except one thing.

When runing this command (wich is necessary for processing portrait images) ..
`vipsthumbnail IMG_4068.JPG -s 180x259 -f %s-cu_e260x180.JPG[Q=96,strip] --rotate --crop`

.. the following error message is created:
`/usr/local/bin/vipsthumbnail: unable to thumbnail IMG_4068.JPG extract_area: bad extract area`

I'm mostly wondering whether that's a limitation (which would require a workaround) or if it's expected to work?

PS: The file in the example above can be downloaded here: http://lln.prelude.de/~lars/IMG_4068.JPG

BTW: The latest source code was compiled and tested with the same result. Quick changes to the code and tests are no problem.

**Comment by jcupitt** [comment]
Hi @ElHeineken, looks like a bug, I think it's not rotating the crop rectangle. I'll have a look.

**Comment by ElHeineken** [comment]
Wow, thank you very much for the quick answer. If there are patches to test I'm more than happy to assist!

**Comment by jcupitt** [comment]
OK, fixed in git master, would you be able to test?

**Comment by ElHeineken** [comment]
Works nicely, all fine now!
