### ISSUE TITLE
How do I call vips_max() from C++ to get the position of the maximum?

### ISSUE THREAD

**Issue by sprock** [jcupitt/libvips#609]
Hello,

I want the get the x,y position of the max of an image in C++.  I can't figure out how to make the call from C++.

`VImage f = VImage::new_from_file("correlation/spcor.v");
  int xmax = f.max();`

What must I add to f.max() to return the desired quantity?

Thanks,
sprock

**Comment by jcupitt** [comment]
Hi, there's a convenience function to make this a bit less painful:

```C++
std::complex<double> maxpos( VOption *options = 0 );
```

You get (x, y) as the real and imaginary parts. 

It just calls `max()` for you like this:

```C++
VImage fred = ...;
int x;
int y;
double maxval = fred.max(VImage::option() ->
                        set( "x", &x ) ->
                        set( "y", &y ) );
```
