### ISSUE TITLE
NameError: name 'gi' is not defined

### ISSUE THREAD

**Issue by sprock** [jcupitt/libvips#610]
hello,

I'm testing smartcrop.py (from https://gist.github.com/jcupitt/a27d449c280863619035), with the intention of writing a C++ version for my mosaicing program).  When I invoke it:

`python3.5 smartcrop.py crop/red_1_1.v`

I get this warning:

`sys:1: PyGIWarning: Vips was imported without specifying a version first. Use gi.require_version('Vips', '8.0') before import to ensure that the right version gets loaded.`

After adding the specified line to smartcrop.py I get:

`python3.5 smartcrop.py crop/red_1_1.v
Traceback (most recent call last):
  File "smartcrop.py", line 8, in <module>
    gi.require_version('Vips', '8.0')
NameError: name 'gi' is not defined `

Any ideas?

Thanks,
sprock

**Comment by jcupitt** [comment]
Hi, I'll update the gist. You need `import gi` to add the gi namespace, then the require, then import vips.
