### ISSUE TITLE
Image rotation fails

### ISSUE THREAD

**Issue by sprock** [jcupitt/libvips#611]
Hello,

I'm working on a translation of smartcrop.py to C++.  In this function:

```C++
VImage feature_detect(VImage image, int M, int N) {
  cout << "feature-detect M = " << M <<  ", N ='" << N << endl;
  int third = (int)(M / 3);
  vector<double> mask;
  for (int i = 0; i < third; i++)
    mask.push_back(-0.1);
  for (int i = 0; i < third; i++)
    mask.push_back(1);
  for (int i = 0; i < third; i++)
    mask.push_back(-0.1);

  double* m = &mask[0];
  VImage hmask = vips_image_new_matrix_from_array(third, third, m, mask.size());
  mask.clear();

  third = (int)(N / 3);
    for (int i = 0; i < third; i++)
    mask.push_back(-0.1);
  for (int i = 0; i < third; i++)
    mask.push_back(1);
  for (int i = 0; i < third; i++)
    mask.push_back(-0.1);

    cout << "Line " << __LINE__ << endl;
  
  m = &mask[0];
  cout << "Line " << __LINE__ << " mask size is " << mask.size() << endl;
  VImage vmask = vips_image_new_matrix_from_array(third, third, m, mask.size());
  cout << "Line " << __LINE__ << endl;
  vmask.similarity(VImage::option()->set("angle", 90.0)); // <---- CRASH

    cout << "Line " << __LINE__ << endl;
  
    return image.conv(hmask) + image.conv(vmask);
}
```

The program segfaults at the line marked CRASH.

Thanks for any help.

sprock

**Comment by jcupitt** [comment]
Hi, by coincidence I'm just adding smartcrop to libvips. Hang on a moment and I should have some code I can point you at.

**Comment by jcupitt** [comment]
Here's the one I've tried hacking up for libvips:

https://github.com/jcupitt/libvips/blob/add-smartcrop/libvips/conversion/smartcrop.c

It's a slight variation on the one in sharp.

**Comment by jcupitt** [comment]
Here's the one from sharp for reference:

https://github.com/lovell/sharp/blob/master/src/operations.cc#L312

It's C++, so it's a bit easier to read.

**Comment by sprock** [comment]
Hi John,

John Cupitt <notifications@github.com> writes:

> Here's the one I've tried hacking up for libvips:
>
> https://github.com/jcupitt/libvips/blob/add-smartcrop/libvips/conversion/smartcrop.c
>
> It's a slight variation on the one in sharp.

Must this be compiled as part of a git checkout?

Here's what I'm doing:

(I copied bandary.h and pconversion.h to the current directory.)

clang -o jcsmartcrop.o jcsmartcrop.c -I/usr/local/include
-I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include
-I/usr/local/include/libxml2 -I/usr/local/include/libgsf-1
-I/usr/local/include/GraphicsMagick -I/usr/local/include/orc-0.4
-I/usr/local/include/OpenEXR -I/usr/local/include/poppler/glib
-I/usr/local/include/cairo -I/usr/local/include/pixman-1
-I/usr/local/include/freetype2    -I/usr/local/include/freetype2
-I/usr/local/include/libdrm -I/usr/local/include/libpng16
-I/usr/local/include/poppler -I/usr/local/include/librsvg-2.0
-I/usr/local/include/gdk-pixbuf-2.0 -pthread -D_THREAD_SAFE
-DH5_USE_18_API -I/usr/local/include/pango-1.0
-I/usr/local/include/harfbuzz -L/usr/local/lib -lvips-cpp -lvips
-lgobject-2.0 -lglib-2.0 -lintl

Result:

jcsmartcrop.c:58:2: error: unknown type name 'VipsInteresting'
        VipsInteresting interesting;
        ^
jcsmartcrop.c:309:3: error: use of undeclared identifier 'VIPS_TYPE_INTERESTING'
                VIPS_TYPE_INTERESTING, VIPS_INTERESTING_ATTENTION );
                ^
/usr/local/include/vips/object.h:199:4: note: expanded from macro 'VIPS_ARG_ENUM'
                (TYPE), (VALUE), \
                 ^
jcsmartcrop.c:316:27: error: use of undeclared identifier 'VIPS_INTERESTING_ATTENTION'
        smartcrop->interesting = VIPS_INTERESTING_ATTENTION;

Cheers

**Comment by jcupitt** [comment]
Yes, you'll need to checkout and build everything, sorry.

**Comment by jcupitt** [comment]
... or just copy-paste and adapt the code, of course.

**Comment by sprock** [comment]
John Cupitt <notifications@github.com> writes:

> ... or just copy-paste and adapt the code, of course.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

OK.  Thanks.

Just for information, how does one populate a new_matrixv()?

For example, in my code I have this:

  >  VImage mask = VImage::new_matrixv(3, 3,
  >  				    1, 0, -1,
  >  				    2, 0, -2,
  >  				    1, 0, -1);

which works.

If I do this:

  > int m[9] = {1, 0, -1, 2, 0, -2, 1, 0, -1};
  > VImage mask = VImage::new_matrixv(3, 3, m);

the code compiles but either the mask is never applied to an image or
the matrix entries are all set to zero, I'm not sure which.

**Comment by jcupitt** [comment]
`new_matrixv` uses varargs to set the matrix elements, so you must list the coefficients as function parameters. 

If you want to set from an array, use plain `new_matrix`. You can see the constructor here:

https://github.com/jcupitt/libvips/blob/master/cplusplus/include/vips/VImage8.h#L455

```C++
double m[] = {1, 0, -1, 2, 0, -2, 1, 0, -1};
VImage mask = VImage::new_matrix(3, 3, m, 9);
```

**Comment by jcupitt** [comment]
OK, vips 8.5 is out now and includes this feature. I'll close.
