### ISSUE TITLE
Cannot compile git version

### ISSUE THREAD

**Issue by sprock** [jcupitt/libvips#612]
Hello,

Compiling the git version (cloned this morning) on FreeBSD 10.3 ends like this:

`/morphology.h include/vips/type.h include/vips/rect.h include/vips/memory.h include/vips/region.h introspect --output Vips-8.0.gir

(vips:88837): VIPS-WARNING **: ABI mismatch

(vips:88837): VIPS-WARNING **: library has ABI version 0

(vips:88837): VIPS-WARNING **: application needs ABI version 42
vips: unable to start VIPS
vips_version: flag not 0, 1, 2
vips_version: flag not 0, 1, 2
vips_version: flag not 0, 1, 2
vips_version: flag not 0, 1, 2
vips_init: ABI mismatch
Command '['./introspect', '--introspect-dump=/tmp/tmp-introspectp0VTjm/functions.txt,/tmp/tmp-introspectp0VTjm/dump.xml']' returned non-zero exit status 1
gmake[3]: *** [/usr/local/share/gobject-introspection-1.0/Makefile.introspection:156: Vips-8.0.gir] Error 1`

Cheers,
sprock

**Comment by jcupitt** [comment]
Hi, that can happen if you have several different vipses installed. I'd clean out any old versions and try again.

**Comment by jcupitt** [comment]
If this is still a problem, please reopen.
