### ISSUE TITLE
Positioning of two tiles in a mosaic

### ISSUE THREAD

**Issue by alonit** [jcupitt/libvips#614]
Hi,

I'm using vips 8.5 C API which include latest `VIpsImage ` `xoffset`/`yoffset` fix that works perfect, where vips_mosaic is being used for joining many small tiles together to make one smooth seam large image.

The small tiles produced by a scanner machine, so that there is misalignment (offset) between successive tiles in both x and y axis, where these offsets are reported by the mosiac `out` image as expected.

Each tile holds some part of a tissue:  
1. data - real tissue 
2. background - with some minor dirt such as dust over it
3. mix - data and background

In case where both `ref` and `sec `tiles holds data in the overlap area, the mosaic return with real stitch `out` image with their given offsets, as there is enough data in them (features) to do the mosaic.

But in case where `ref` or `sec `tiles holds background in the overlap area, there is not enough data for the mosaic to decide what is the real positioning, so that the resulted `out ` image doesn't represent the expected result, as the out image doesn't reflects the existed misalignment. This situation is valid also when `ref` or `sec `tiles holds mix of data and background, where the overlap area has not enough features (data) to determine the real positioning of `ref `and `sec` in `out`.

1. How the `mosaic `determine the real positioning where there is not enough data in the overlaps area? - I saw that it searches for 60 high-contrast points of `ref `in `sec`, but how the `mosaic `behaves if for example the tiles are full white background (all pixels are 255 for 8 bit), where there is no contrast in the image, or given the real world situation the overlaps has very low contrast? I'm afraid that in these cases it would not result with the real positioning of `ref `and `sec `in `out`

2. Does vips holds information that can help with this? - useful information might be certainty score regarding the mosaic decided positioning, contrast values of the founded points in the overlap area (although dust is black, located over white background => very high contrast) , etc..

3. Given two tiles, `ref `and `sec `and their overlap, how can I determine, by using vips,  if their overlap area has enough data to do a mosaic, so that their real offset will be reflected in `out` as expected? In other words, how can I check if image is empty (not enough data for stitching) by using vips?

Thanks

**Comment by jcupitt** [comment]
Hi, sorry for the delay in replying. 

The mosaic functions will fail with an error if they can't find enough tie-points or if the points they find are inconsistent. The procedure is (from memory):

- split the overlap in ref into three areas: top, middle, bottom
- search for the top 20 high-contrast points in each area
- for each point, search the corresponding area in sec and note the offset
- fit a linear model to the set of 60 tie points
- remove points which fall a long way outside the model
- refit the model and try again until
- either we have a set of points which form a straight line, or there are too few points left
- either join the images or report an error

If you have no useful data in an overlap, you are in trouble. The best solution in this case would be a global optimisation: use the mosaic functions to find (or fail to find) a best offset for each overlap, then do a least-mean-square to find the set of tile positions that minimise peak error.

You can call the lower-level find overlap functions directly, for example:

```C
int
im__find_tboverlap( IMAGE *ref_in, IMAGE *sec_in, IMAGE *out,
        int bandno_in,
        int xref, int yref, int xsec, int ysec,
        int halfcorrelation, int halfarea,
        int *dx0, int *dy0,
        double *scale1, double *angle1, double *dx1, double *dy1 )
```
