### ISSUE TITLE
How to detect uniform images using vips?

### ISSUE THREAD

**Issue by alonit** [jcupitt/libvips#615]
Hi,

I have to determine if a `VipsImage`s are uniform or not, for the purpose of determine whether they can be stitched (`mosaic`), or they just can be joined manually (`merge`) using predefined offsets.

I figure out that there is lot of ways to determine image uniformity in general, for example by analyzing bins histogram of an image, and that it is depend on sort of image - 8 bit (R,G,B) tissue with sRGB color space in my case.

I think that API like `bool vips_is_uniform(VipsImage* in)' is what needed here.

What is the recommended approach using vips C API to determine image uniformity? 

your kind support would be highly appreciated.

Thanks

**Comment by jcupitt** [comment]
You'd need to pick a measure on uniformity. For example, a simple one might be max difference from mean, or you could perhaps calculate the kurtosis of the histogram. 

Max difference from mean in C would be something like:

```C
double mean;
double max;

if (vips_avg(image, &mean, NULL) ||
  vips_linear1(image, &t1, 1.0, -mean, NULL) ||
  vips_abs(t1, &t2, NULL) ||
  vips_max(t2, &max, NULL))
  return -1;
```

For a kurtosis measure, you'd find the histogram, then calculate the metric in the usual way

**Comment by alonit** [comment]
Thanks.

My images has white background that is uniform when no data existed, but there is always dirt such as dust, usually dirt is black, that is spread over it. So, I think that "max diff. from mean" is not fit here. Maybe i need to count the black pixels and the white pixels, and decide upon their precentage in the image. Maybe remove first the dust pixel and then use the "max diff. From mean"  . What fo you think?

Thanks.

**Comment by jcupitt** [comment]
How about just using standard deviation? A plain white image with a little dust will have a very low SD. You'll need to pick a single channel first, I'd suggest green.

**Comment by alonit** [comment]
Ah, OK. I'll check whether SD works in my case, and let you know.

Many thanks

**Comment by alonit** [comment]
How about first convert the R,G,B to single gray-scale image and calculate the s.d. over it - Is it more accurate than s.d. of 1 out of 3 channels ?

**Comment by jcupitt** [comment]
It probably doesn't matter. The usual grey formula is 60% green, 30% red, 10% blue, so it'll produce very similar results and be slower. I'd just take green.

**Comment by alonit** [comment]
Hi, 

I checked the sd measure, and it gives 90% of the time a correct indication about uniformity. So I think to add another kind of measure to increase certainty - somthing like searching edges in image by using canny edge detection operator.

1. Is that a right measure for uniformity or there are other simplest and light measure to increase certainty?

2. Does vips have support for image edge detection domain, such as algorithms (canny), filters etc..?

Your kind support is highly appreciated.

Many thanks

**Comment by jcupitt** [comment]
There's no Canny, but you could make a Sobel very easily, vips has a nice convolution operator. 

You could try kurtosis, but I expect it would be rather similar to SD. 

Could you post a pair of images with no features somewhere? The mosaic functions ought to fail with an error, I'd like to see why they don't.

**Comment by alonit** [comment]
Thanks for your helpful suggestions.

I'll try to get the pair of images as soon as I can and post them for you.
