### ISSUE TITLE
improved smartcrop

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#619]
The libvips smartcrop works by discarding boring parts of the image. But this means it cannot centre interesting content, for example @puzrin has this good test image:

![](https://c2.staticflickr.com/6/5525/11841147024_f7d0ec7dbe_o_d.jpg)

With:

```
$ vipsthumbnail -s 170x150 --smartcrop attention owl.jpg 
```

Gives:

![tn_owl](https://cloud.githubusercontent.com/assets/580843/23822278/e8d1c5a4-0641-11e7-9c9e-a12b65887951.jpg)

Which is off-centre. 

Possible new algorithm: make a single pass over the image and detect edges, skin and saturated areas, make a low-res score image, find the position of the crop rectangle that maximises enclosed score.

**Comment by puzrin** [comment]
I'd like to clarify one important thing. When people request smart crop, they (and me too) often means "as good as `smartcrop.js` or better". If quality is worse, result can be not acceptable and high speed does not helps. In my case often center errors make this feature not useable.

IMHO it would be good to port `smartcrop.js` logic "as is" and make it available asap. Then users will be able to test feature in production. Speed improvements could be done in next versions.

**Comment by puzrin** [comment]
Algorythm note. No need to process big image as is:

1. Scale big image down with fast filter (linear over RGB, for example)
2. Do calculations over reduced image.
3. Scale coordinates up to original.

That will reduce precision a bit (max area drift = 1*scale pixels), but that should be ok for this task.

**Comment by jcupitt** [comment]
I had an idea in the shower this morning, and it's much simpler than I thought. I've committed an improvement to master that gives this result:

```
$ time vipsthumbnail -s 170x150 --smartcrop attention owl.jpg
real	0m0.071s
user	0m0.064s
sys	0m0.008s
```

![tn_owl](https://cloud.githubusercontent.com/assets/580843/23898045/70f14df8-08a7-11e7-926c-7f3f6935c8ae.jpg)

It works by generating a score image, as before, but doing it for the whole frame. This is then shrunk and blurred and searched for a peak. The crop is centred on that. 

The old entropy-based smartcrop is still there and is a bit quicker:

```
$ time vipsthumbnail -s 170x150 --smartcrop entropy owl.jpg
real	0m0.054s
user	0m0.036s
sys	0m0.024s
```

But won't centre. Entropy cropping will be much quicker for large images.

**Comment by puzrin** [comment]
Looks good. As soon as it will be available in sharp, i rebuild images on my site.

**Comment by kleisauke** [comment]
How about this test image? https://upload.wikimedia.org/wikipedia/commons/4/45/Equus_quagga_burchellii_-_Etosha%2C_2014.jpg

300x300 attention returns this:
![image](https://cloud.githubusercontent.com/assets/12746591/23997504/dd4e3866-0a51-11e7-979e-816cede2a061.jpg)

Expected:
![expected](https://cloud.githubusercontent.com/assets/12746591/23997755/f83374d8-0a52-11e7-8c38-089046b77dcd.jpg)

**Comment by jcupitt** [comment]
That's a good test image, thank @kleisauke.

I added a gaussblur (I'd been lazy and skipped it before) and I now see:

```
$ vipsthumbnail quagga.jpg -s 128 --smartcrop attention
```

![tn_quagga](https://cloud.githubusercontent.com/assets/580843/23999380/26a69ab4-0a50-11e7-8620-8a4ac31578ac.jpg)

**Comment by jcupitt** [comment]
Here's a nip2 workspace which implements the libvips smartcrop algorithm:

![screenshot from 2017-03-16 13-57-08](https://cloud.githubusercontent.com/assets/580843/23999537/a0e97fee-0a50-11e7-9ee8-d56b27ceca7f.png)

You can see all the stages and how the score image is calculated. You can edit all the parameters and formula and watch the crop change. Handy!

[smartcrop.zip](https://github.com/jcupitt/libvips/files/847863/smartcrop.zip)

**Comment by kleisauke** [comment]
Looks good! Do you have any clue why the nip2 workspace are different then libvips master?

libvips master 128x128 attention:
![quagga1](https://cloud.githubusercontent.com/assets/12746591/24001577/c9191804-0a5e-11e7-8940-95f9f289191d.jpg)
(perfect)

libvips master 300x300 attention:
![quagga2](https://cloud.githubusercontent.com/assets/12746591/24001174/b99749ec-0a5d-11e7-9678-e186a8a5da06.jpg)
(deviates a little bit to the right)

nip2 128x128 attention:
![quagga1](https://cloud.githubusercontent.com/assets/12746591/24001537/ae7ec1f6-0a5e-11e7-8933-bf3eb3bd97ca.jpg)
(deviates a little bit to the left)

nip2 300x300 attention:
![quagga2](https://cloud.githubusercontent.com/assets/12746591/24001175/b997e5a0-0a5d-11e7-83f4-bb1a8eb67490.jpg)
(deviates a little bit to the left)

I've setup a test environment where you can test it:
http://t0.nl/?url=ssl:upload.wikimedia.org/wikipedia/commons/4/45/Equus_quagga_burchellii_-_Etosha%2C_2014.jpg&w=128&h=128&t=square&a=attention
(just change the `&w=128` and `&h=128` to the width and height you want)

**Comment by jcupitt** [comment]
I've fixed a few small things in git master and it seems to work better now.

```
$ vipsthumbnail quagga.jpg -s 300 --smartcrop attention
$ vipsthumbnail owl.jpg -s 300 --smartcrop attention
```

![tn_quagga](https://cloud.githubusercontent.com/assets/580843/24039964/f29361ee-0afe-11e7-9202-24e4f0bb2b71.jpg)
![tn_owl](https://cloud.githubusercontent.com/assets/580843/24039972/f8630638-0afe-11e7-97ea-7caff625fa32.jpg)

**Comment by kleisauke** [comment]
Perfect! 👍

Did some tests with libvips vs `smartcrop.js`, and it looks like it has now the same behavior as `smartcrop.js`. See this (prepared) test image which will 'fail' in libvips and  `smartcrop.js`:
![example](https://cloud.githubusercontent.com/assets/12746591/24045263/bde762c2-0b1e-11e7-9c35-d0abe1013f10.jpg)
(dowload it here: http://t0.nl/northern_cardinal_bird_fail.jpg)
```
$ vipsthumbnail northern_cardinal_bird_fail.jpg -s 300 --smartcrop attention
````
![fail](https://cloud.githubusercontent.com/assets/12746591/24045318/f097b258-0b1e-11e7-9cfc-a774a55466da.jpg)
(`smartcrop.js` has the same output, test it [here](https://29a.ch/sandbox/2014/smartcrop/examples/testbed.html))

The original image will successfully crop to the [bird](https://en.wikipedia.org/wiki/Northern_cardinal):
![example2](https://cloud.githubusercontent.com/assets/12746591/24045423/577a83ba-0b1f-11e7-9c7c-ffefc038434f.jpg)
(download the original here: http://t0.nl/northern_cardinal_bird.jpg)

```
$ vipsthumbnail northern_cardinal_bird.jpg -s 300 --smartcrop attention
````
![success](https://cloud.githubusercontent.com/assets/12746591/24045466/849b967c-0b1f-11e7-8be7-cab11a362317.jpg)
(Also `smartcrop.js` has the same output)

**Comment by kleisauke** [comment]
Update:
I've tested some images (which contains transparency) that are are not premultiplied before the smart crop operation. It's currently giving some 'weird' results.
[Non-optimized](https://upload.wikimedia.org/wikipedia/commons/archive/4/47/20170225194941%21PNG_transparency_demonstration_1.png)
[Optimized](https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png)

Optimized image - libvips master 128x128 attention:
![fail1](https://cloud.githubusercontent.com/assets/12746591/24047425/f4713992-0b25-11e7-90bb-964371d27733.png)
(deviates a little bit to the right)

Optimized image - libvips master 300x300 attention:
![fail2](https://cloud.githubusercontent.com/assets/12746591/24047522/488570d4-0b26-11e7-9833-b956b7418c68.png)
(deviates a little bit to the right)

Non-optimized image - libvips master 128x128 attention:
![pass1](https://cloud.githubusercontent.com/assets/12746591/24047476/2200e664-0b26-11e7-97c2-0230b67138f2.png)
(perfect)

Non-optimized image - libvips master 300x300 attention:
![fail3](https://cloud.githubusercontent.com/assets/12746591/24047576/6ee4de86-0b26-11e7-8505-926172f196c5.png)
(deviates a little bit to the right)

Is premultiplying required for these images before the `vips_smartcrop` operation?

**Comment by jcupitt** [comment]
Hi, you're right, it should premultiply alpha before searching, I've added that.

It'll always aim to the left, sadly. The attention smartcrop looks for edges, skin and saturated colour. There's no skin here, edges are everywhere, but the blue die on the left is extremely saturated, much more so than the red, greed or yellow; it's therefore trying to centre on that. I don't see a simple fix for this :(

**Comment by kleisauke** [comment]
Ah I see. Not sure if this is the correct behavior but [the image](https://upload.wikimedia.org/wikipedia/commons/archive/4/47/20100130232511%21PNG_transparency_demonstration_1.png) is centered correctly when the size is below 167x167 pixels. See this:
```
curl -o example-original.png https://upload.wikimedia.org/wikipedia/commons/archive/4/47/20100130232511%21PNG_transparency_demonstration_1.png
vipsthumbnail example-original.png -o example-167.png -s 167 --smartcrop attention
vipsthumbnail example-original.png -o example-166.png -s 166 --smartcrop attention
```

![example-167](https://cloud.githubusercontent.com/assets/12746591/24084106/69c8b638-0ce4-11e7-89ca-8b5dc5ba91b8.png)
![example-166](https://cloud.githubusercontent.com/assets/12746591/24084107/69c9b8b2-0ce4-11e7-8b6a-eaf66712b136.png)

Will do some tests with other images, but for now I think this feature is ready for production and 'shippable' in libvips 8.5. I think we can safely ignore this image as an example (in my opinion the attention strategy should only be used with photos for the best results).

**Comment by jcupitt** [comment]
OK, I'll close and put a beta for 8.5 together. Let's have a fresh issue for any further problems.
