### ISSUE TITLE
make issue on Centos 5

### ISSUE THREAD

**Issue by nobbih** [jcupitt/libvips#622]
Centos 5.11 kernel 2.6.18-419  
configure was suvccessful but make is giving 2 errors  

vips.o: In function `main':  
/opt/download/vips-8.4.5/tools/vips.c:1140: undefined reference to `g_option_context_get_help'
collect2: ld returned 1 exit status  
make[2]: *** [vips] Error 1  
make[2]: Leaving directory `/opt/download/vips-8.4.5/tools'  
make[1]: *** [all-recursive] Error 1  
make[1]: Leaving directory `/opt/download/vips-8.4.5'  
make: *** [all] Error 2  
Any idea what i did wrong ?
Thanks  
Norbert

**Comment by jcupitt** [comment]
Sorry, your OS is probably too old. `g_option_context_get_help()` was added in glib 2.14. What do you see if you run:

```
$ pkg-config glib-2.0 --modversion
2.50.3
```

**Comment by nobbih** [comment]
I get 2.12.3

**Comment by jcupitt** [comment]
I've tried making a vips which might work for you:

http://www.vips.ecs.soton.ac.uk/development/8.5/vips-8.5.0a.tar.gz

Would you be able to test it?

**Comment by nobbih** [comment]
Thank's a lot John ! I will try of course. 
If it works it will be good news because glib-2.12 is the version used in Centos 6,x as well

**Comment by jcupitt** [comment]
2.12 is from 2006 :-( centos really moves very slowly.

**Comment by nobbih** [comment]
Unfortunately I get the same error as before:  
../libvips/.libs/libvips.so: undefined reference to `g_slist_free_full'
collect2: ld returned 1 exit status
make[2]: *** [vips] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Do you need the full log ?

**Comment by nobbih** [comment]
> 2.12 is from 2006 :-( centos really moves very slowly.
Yes. But for production grade server OS that is quite ok. I have servers running for 10 years without any interruption or problem.

**Comment by jcupitt** [comment]
Thanks for doing this testing @nobbih, it's good to fix this. 

I committed another tweak, can you build from git master or should I make another tarball?

**Comment by jcupitt** [comment]
I expect you know, but to build from git, clone and then something like:

```
CFLAGS="-g -Wall" CXXFLAGS="-g -Wall" ./autogen.sh --prefix=/home/john/vips
make
make install
```

**Comment by nobbih** [comment]
I will try. Normally I am using git on my dev machine. This is the server. But never hurts to learn some things (-;

**Comment by jcupitt** [comment]
You'd need to install some extra stuff. Don't worry, I'll make a tarball for you. Hang on.

**Comment by jcupitt** [comment]
OK, here's another tarball:

http://www.vips.ecs.soton.ac.uk/development/8.5/vips-8.5.0b.tar.gz

**Comment by nobbih** [comment]
Thanks. got it. Not finished yet - but looks better

**Comment by nobbih** [comment]
Sorry - another error now.  
vipsthumbnail.c:277: error: expected ‘)’ before ‘*’ token
vipsthumbnail.c: In function ‘thumbnail_parse_geometry’:
vipsthumbnail.c:289: error: ‘GRegex’ undeclared (first use in this function)
vipsthumbnail.c:289: error: (Each undeclared identifier is reported only once
vipsthumbnail.c:289: error: for each function it appears in.)
vipsthumbnail.c:289: error: ‘regex’ undeclared (first use in this function)
vipsthumbnail.c:290: error: ‘GMatchInfo’ undeclared (first use in this function)
vipsthumbnail.c:290: error: ‘match_info’ undeclared (first use in this function)
vipsthumbnail.c:295: warning: implicit declaration of function ‘g_regex_new’
vipsthumbnail.c:296: error: ‘G_REGEX_CASELESS’ undeclared (first use in this function)
vipsthumbnail.c:296: error: ‘G_REGEX_EXTENDED’ undeclared (first use in this function)
vipsthumbnail.c:297: warning: implicit declaration of function ‘g_regex_match’
vipsthumbnail.c:298: warning: implicit declaration of function ‘g_match_info_matches’
vipsthumbnail.c:299: warning: implicit declaration of function ‘fetch_match’
vipsthumbnail.c:299: warning: initialization makes pointer from integer without a cast
vipsthumbnail.c:300: warning: initialization makes pointer from integer without a cast
vipsthumbnail.c:301: warning: initialization makes pointer from integer without a cast
vipsthumbnail.c:302: warning: initialization makes pointer from integer without a cast
vipsthumbnail.c:351: warning: implicit declaration of function ‘g_match_info_free’
vipsthumbnail.c:352: warning: implicit declaration of function ‘g_regex_unref’
make[2]: *** [vipsthumbnail.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by jcupitt** [comment]
OK, here's another one. Good luck!

http://www.vips.ecs.soton.ac.uk/development/8.5/vips-8.5.0c.tar.gz

**Comment by nobbih** [comment]
Thanks a lot, John. ! So far it worked ! Make and make install finished without errors. I will test now if it really works.

**Comment by jcupitt** [comment]
Try the test suite, `make check` should run it. You'll need to have the python binding built.

**Comment by jcupitt** [comment]
... and build with -O3. libvips is marked up for vectorization, so you can see a nice speedup, provided your gcc supports it.

**Comment by jcupitt** [comment]
Thinking about it, the test suit probably won't run, you'll need a more modern glib for that.

**Comment by nobbih** [comment]
Thanks John ! I tried the thumbnail creator - and it worked. Question: is there an easy way to deactivate the EXIF generation in thumbs ? I need small thumbs to save bandwidth and the exif information is not needed.

**Comment by jcupitt** [comment]
Hey, great! Is speed OK?

There's a blog post from a few years ago about `vipsthumbnail`:

http://libvips.blogspot.co.uk/2013/11/tips-and-tricks-for-vipsthumbnail.html

Which runs through the options. I should update it again. You'll see the smallest output with `strip` on write to remove all metadata, plus colour management to convert to sRGB, plus auto-rotate, plus `optimize-coding`.

```
$ vipsthumbnail fred.jpg -o tn_%s.jpg[optimize_coding,strip] --eprofile /usr/share/color/icc/sRGB.icc  --rotate
```

**Comment by jcupitt** [comment]
Hopefully we're done ... I'll close.
