### ISSUE TITLE
Is 8.5 ready for use / release?

### ISSUE THREAD

**Issue by rnanwani** [jcupitt/libvips#624]
Wanted to use the WebP ICC profile and try out the smart crop features.

**Comment by jcupitt** [comment]
Hi, it's now in beta:

http://www.vips.ecs.soton.ac.uk/development/8.5/

Depending on what people find, it'll become 8.5.1 in another week or so.

**Comment by jcupitt** [comment]
Blog post on what's new:

http://libvips.blogspot.co.uk/2017/03/whats-new-in-85.html

**Comment by jcupitt** [comment]
All done, so I'll close. 8.5.2 is due soon.

**Comment by rnanwani** [comment]
brew still shows the latest version as 8.4.5
Build using source code, then?

**Comment by jcupitt** [comment]
I've sent pull requests for an 8.5.2 package, it should be on brew soon, hopefully.

https://github.com/Homebrew/homebrew-science/pull/5399

Their CI seems to be broken at the moment :( `py2cairo` is broken and it's making the vips CI fail too. Perhaps they'll fix it.
