### ISSUE TITLE
Stuck at first steps.

### ISSUE THREAD

**Issue by betovidal** [jcupitt/libvips#625]
I downloaded the latest windows libraries for C and when I try to compile the example code I keep getting the next message:

C:\Users\MCHN\Documents\Code\vtfs>make
gcc -I vips-dev-8.4/include -I vips-dev-8.4/include/glib-2.0 -I vips-dev-8.4/lib/glib-2.0/include test.c -L vips-dev-8.4/lib -lvips -lz -ljpeg -lxml2 -lfftw3 -lm -lMagickWand-6.Q16 -llcms2 -lopenslide -llibpangowin32-1.0 -ltiff -lpng16 -lexif -lMagickCore-6.Q16 -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lglib-2.0 -lintl -o test.exe
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0xf): undefined reference to `vips__get_sizeof_vipsobject'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0x28): undefined reference to `vips_info'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0x2d): undefined reference to `vips__get_sizeof_vipsobject'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0x45): undefined reference to `vips_info'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0x61): undefined reference to `vips_info'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0x75): undefined reference to `vips_error'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0x89): undefined reference to `vips_init'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0x9e): undefined reference to `vips_error_exit'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0xa9): undefined reference to `g_get_prgname'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0xb9): undefined reference to `vips_error_exit'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0xd1): undefined reference to `vips_image_new_from_file'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0xe8): undefined reference to `vips_error_exit'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0x104): undefined reference to `vips_avg'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0x114): undefined reference to `vips_error_exit'
C:\Users\MCHN\AppData\Local\Temp\ccGDOaqy.o:vtfs.c:(.text+0x120): undefined reference to `g_object_unref'
collect2.exe: error: ld returned 1 exit status
make: *** [all] Error 1

My file structure is as follows:

+Code
|--makefile
|--test.c
|--+vips-dev-8.4 (as downloaded from the ftp)
|----+bin
|----+etc
|----+include
|----+lib
|----+share

I edited some libs from the flags line (e.g. -lMagickCore to -lMagickCore-6.Q16 and -lpng14 to -lpng16) and removed -lcfitsio in order to make a progress. I'm on Windows 10, compiling with mingw 5.3.0. Am I missing something obvious?

**Comment by betovidal** [comment]
Apparently I was missing something obvious. In case somebody else finds this useful I had to change mingw to mingw64 and use x86_64-w64-mingw32-gcc as compiler and mingw32-make as make tool.

**Comment by jcupitt** [comment]
Don't worry, it's not obvious, even vips is less confusing than the naming scheme for the mingw compilers :(
