### ISSUE TITLE
How to fill an image? Using Ruby interface.

### ISSUE THREAD

**Issue by PaulHowson** [jcupitt/libvips#626]
Hi John,

Back onto Vips after a gap of 6 months.

How do I make a Vips image filled with a solid colour? Obviously Vips::Image.black (using it from Ruby) will create an image filled with black. How to fill it with a colour or grey?

There is vips_draw_flood(), but that seems unnecessarily complicated. I just want to fill every pixel in the image.

I tried using vips_draw_rect() (or Vips::Image.draw_rect from Ruby) but that didn't seem to do anything. Part of the problem might be with the "ink" arg, declared in C as double *ink. If I'm working with an 8-bit (uchar?) image then what value to feed in for an RGB 8-bit colour? Basically I want to make a mid-grey image which I can then insert smaller images into with Vips::Image.insert.

Thanks,
Paul Howson

**Comment by jcupitt** [comment]
Hi Paul, there ought to be a convenience constructor this this job, perhaps `new_from_value` or something like that.

The fastest way is to make a one-pixel image of the type and value you want, then to expand it up to the size you need with `::embed`. Something like:

```ruby
pixel = Vips::Image.black(1, 1, :bands => 3) + [128, 255, 192]
pixel = pixel.cast "uchar"
image = pixel.embed 0, 0, 100000, 100000, :extend => "copy"
```

Makes a 100,000 x 100,000 pixel RGB uchar image.

**Comment by PaulHowson** [comment]
Thanks John. I realised I needed the result to be a 16-bit (ushort) image. Casting it directly to ushort didn't work, but casting it to uchar (as above) and then to ushort worked. :)

**Comment by jcupitt** [comment]
Oh, strange, it should be able to make a 16-bit mage in one step. I tried this:

```ruby
#!/usr/bin/env ruby

require 'vips'

pixel = Vips::Image.black(1, 1, :bands => 3) + [128, 255, 192]
pixel = (pixel * 256).cast "ushort"
image = pixel.embed 0, 0, 1000, 1000, :extend => "copy"
image.write_to_file ARGV[0]
```

And it seems to work. You need to multiply your pixel by 256 before casting to `ushort`, since the 128, 255, 192 numbers are in 0 - 255, the range for an 8-bit image. Or you could just use 32768, 65535, 48172 as the constants, of course.

**Comment by PaulHowson** [comment]
Hi John. Just noticed you closed this issue, which is OK since I was able to get it to work with the above tips. Just a couple of curious questions:

- What vips function is invoked by the Ruby ‘+’ operator? What does this actually do? vips_add expects two vips images. How does the second arg (a ruby array) get interpreted as an image?

- Similarly for ‘*’ operator. Which vips function?

- Why does the first line (adding the array to Image.black) return a float image when the inputs are all "integers"?

**Comment by jcupitt** [comment]
Hi Paul, you can see the code for +-*/ here:

**Comment by PaulHowson** [comment]
Where's here?

**Comment by jcupitt** [comment]
Sorry, my stupid browser keeps submitting early if I hit shift enter by mistake. I've updated my post.

**Comment by PaulHowson** [comment]
OK. Thanks John. That explains it. :)

**Comment by jcupitt** [comment]
I just pushed a new version of the gem with `new_from_image`:

http://www.rubydoc.info/gems/ruby-vips/1.0.5/Vips/Image#new_from_image-instance_method

So `x.new_from_image(12)` makes a new image, the same size as `x`, but with the value 12 in each pixel.

**Comment by PaulHowson** [comment]
On 29 Apr 2017, at 8:18 PM, John Cupitt <notifications@github.com> wrote:
> 
> I just pushed a new version of the gem with new_from_image:
> 
> http://www.rubydoc.info/gems/ruby-vips/1.0.5/Vips/Image#new_from_image-instance_method <http://www.rubydoc.info/gems/ruby-vips/1.0.5/Vips/Image#new_from_image-instance_method>
> So x.new_from_image(12) makes a new image, the same size as x, but with the value 12 in each pixel.
> 

OK. Thanks John. Will note it for next time. :)

----------------------------------------------------------------
Paul Howson
Warwick Qld Australia
e: paul@tdgq.com.au <mailto:paul@tdgq.com.au>    w: tdgq.com.au <http://tdgq.com.au/>
GRAPHIC DESIGN    WEB SITE DESIGN   WEB APPLICATIONS
