### ISSUE TITLE
Best strategy for maintaining packages

### ISSUE THREAD

**Issue by ioquatix** [jcupitt/libvips#627]
@jcupitt I've just asked and been granted co-maintainer status of the arch packages for libvips and nips packages.

Here was the feedback:

> Actually that's not a bad idea at all, thank you for offering the
help! <snip> Fortunately vips and nip2 doesn't have
any crazy build system and they keep with new library versions well,
too, so maintaining vips and nip2 basically means to bump pkgver every
now and then.

What would be the best strategy to ensure that the packages on arch are up to date? Should we set up some kind of automated process?

**Comment by ioquatix** [comment]
Just in case you are interested, here are the links:

- https://aur.archlinux.org/packages/vips/
- https://aur.archlinux.org/packages/nip2/

**Comment by ioquatix** [comment]
One option would be to have a post-hook on the stable master branch, and once a release is tagged, to trigger some sort of script in the CI.

**Comment by jcupitt** [comment]
I'm not sure, I've not looked into it. Currently releases are rather ad hoc -- I just upload tarballs to the old vips site:

http://www.vips.ecs.soton.ac.uk/supported/current/

I guess it would be better to use the github release system. And we should probably move the old site content into gh-pages too. Would automating things like arch packages be part of the same project?

**Comment by ioquatix** [comment]
Making and releasing the arch packages is basically a handful of commands. Using github for releases works well with arch packages. So, I think that's a good way forward if you are happy with that.

My opinion about websites.. I think you should avoid the need for a specific website for a project unless there is some really specific case, e.g. it's a commercial project. The reason why I say this is because I think that the project should be self-contained within the code itself. A website is a management burden which takes away from software development.

While it's not totally relevant, I actually just added a wiki directly into the code repository in one of my projects. It's awesome because the wiki is always specific to what version of the code you have, so any code examples in the wiki are for that version. Anyone can clone the code and make a PR on the wiki. These are all options to think about, and as the maintainer only you can really make a decision. But, I can tell you, having quite a few projects, that a website-per-project is simply unpaintable. For now, I strive to just have really good README.md files.

**Comment by ioquatix** [comment]
I thought about it some more. You should be a co-maintainer on the Arch packages, and Debian packages, and * packages. You should have a script (e.g. Rakefile), which you run, and it simply bumps everything everywhere.

**Comment by jcupitt** [comment]
There's a new libvips website here:

http://jcupitt.github.io/libvips/

This one is supposed to replace the current main site at http://www.vips.ecs.soton.ac.uk and the blog at http://libvips.blogspot.co.uk and integrate nicely with the github repo. I've moved the more useful blog posts into the core docs. 

The wiki part of the new site has all the old pages from the soton site. I still need to go through them and throw away the useless stuff :( 

Anyway, hopefully this new thing will be simple to maintain and all in one place.

**Comment by jcupitt** [comment]
... any comments would be very helpful, I meant to add.

**Comment by ioquatix** [comment]
Did you rename the package from "vips" to "libvips" ? because it's breaking the arch PKGBUILD.

The package is called "`vips`" but the github project is called `libvips`.

When you download the release archive from github, it extracts to a directory "libvips-$version". Previously it extracted to "vips-$version".

**Comment by ioquatix** [comment]
It's no longer possible to run ./configure as indicated in the README, it does not exist.

**Comment by jcupitt** [comment]
There are two links on the release page:

https://github.com/jcupitt/libvips/releases

You need `vips-8.5.5.tar.gz`. This is a proper tarball made with `make dist` which should configure very simply. It will extract to `vips-8.5.5` and contains a pre-built `configure` script.

github add a link labelled `Source code (tar.gz)` which you must fetch as `v8.5.5.tar.gz`, but downloads `libvips-8.5.5.tar.gz` and extracts to  which extracts to `libvips-8.5.5`. It's a snapshot of the repository at that tag and does not contain a `configure`. It's a lot harder to build: you'll need swig and autotools, all in versions compatible with the ones used to make the proper tarball.

I'd like to get rid of the link that github generates, but I've not found the button yet :(

**Comment by ioquatix** [comment]
Okay great, I've made this change and it appears to be working well.
