### ISSUE TITLE
Process Error - vipspng: Not enough image data

### ISSUE THREAD

**Issue by yurykovshov** [jcupitt/libvips#629]
Hi John,

After **dzsave** on some PNG file we got output error in the end:

`vips.exe temp-2: 28800 x 16200 pixels, 2 threads, 28800 x 1 tiles, 256 lines in buffer
vips.exe temp-2: 0% complete
vips.exe temp-2: 1% complete
vips.exe temp-2: 2% complete
...
vips.exe temp-2: 98% complete
vips.exe temp-2: 99% complete
vips.exe temp-2: done in 111s          

**ProcessError: vips warning: linecache: error in tile 0 x 16192
vipspng: IDAT: invalid stored block lengths
vipspng: Not enough image data**
`

Thumbnails were created fine.
The file itself are viewable fine also on a local machine, despite being 800mb.

Any suggestions?

Many thanks
Yury

**Comment by jcupitt** [comment]
Hi Yury, this is with a PNG source file, is that correct? Could the PNG file be corrupt? I would try:

```
vips avg somefile.png
```

which will scan the PNG file and print the image average. If the file is damaged, you should see an error message.

**Comment by yurykovshov** [comment]
Tried and got the same:
`vips warning: linecache: error in tile 0 x 16192`
`vipspng: IDAT: invalid stored block lengths`
`vipspng: Not enough image data`

Also I checked this file with [pngcheck](http://www.libpng.org/pub/png/apps/pngcheck.html) utility and got no errors:
`OK: game.png (28800x16200, 24-bit RGB, non-interlaced, 39.6%).`

What do you think?

**Comment by jcupitt** [comment]
Then I think the PNG file is damaged, perhaps it has been truncated. I doubt if pngcheck has scanned the whole thing, I expect it just checked the header.

If you put a copy of the file somewhere I'll have a look. Mail me a URL privately if it's confidential.

**Comment by yurykovshov** [comment]
I think it's not confidential. So I will put a link here - https://drive.google.com/open?id=0B1f6TV1IYgphNmRnQ0FLNFNxQVU

**Comment by jcupitt** [comment]
Yes, the file has been truncated, I think irfanview is just hiding the error. Try looking at the bottom edge of the image, I think you'll see some missing areas.

**Comment by jcupitt** [comment]
It's the very final line, 16199, that has the error. Irfanview probably displays it as black, but you wouldn't be able to tell.

I looked at the PNG reader again, and it was flagging an error when it probably should have just issued a warning. I've changed it for 8.5.2. 

I now see:

```
$ vips avg png-issue.png
libpng error: IDAT: invalid stored block lengths
libpng error: Not enough image data
53.052345
$ vips avg png-issue.png[fail]
libpng error: IDAT: invalid stored block lengths
libpng error: Not enough image data

(vips:26882): VIPS-WARNING **: error in tile 0 x 16192
vipspng: IDAT: invalid stored block lengths
vipspng: Not enough image data
$ 
```

Thanks Yury!

**Comment by yurykovshov** [comment]
Thanks, John. 
When do you plan to release 8.5.2 windows bins? Any chance to have it in 8.4.4? (don't know your dev process)

**Comment by jcupitt** [comment]
Yes, there's an 8.5.2 coming soon. Another week? Or you can build yourself, of course. The builder is here:

https://github.com/jcupitt/build-win64

Just install docker and type:

```
build.sh 8.5
```

And it'll download, patch, configure, build and package the entire thing. It takes an hour or so to run. On Windows you'll need to adapt the `build.sh` script, but it's very small.

**Comment by jcupitt** [comment]
8.5.2 is out now, with windows binaries as well:

https://jcupitt.github.io/libvips/

click on "download".
