### ISSUE TITLE
vips_colourspace: no known route between 'cmyk' and 'srgb'

### ISSUE THREAD

**Issue by bender22** [jcupitt/libvips#630]
Hi John,

I'm using vipsthumbnail.exe to apply icc_profile to a jpeg image https://www.dropbox.com/s/k8x0q9omqd9ibxa/89cd2470-34f7-43e6-bf88-d29fb3757d65.jpg

When running the command with I'm getting the following error: 

unable to thumbnail C:\718a4603-2884-476b-be8c-050f22ffd1be.jpg
vips_colourspace: no known route between 'cmyk' and 'srgb'

The command I'm running:
vipsthumbnail.exe --C:\718a4603-2884-476b-be8c-050f22ffd1be.jpg --output=%s_iccApplied.jpg  --size=18034x7534 --eprofile sRGB_v4_ICC_preference.icc --delete

Is it a bug or I'm doing something wrong? 

Thanks in advance.

**Comment by jcupitt** [comment]
Hi @bender22, your JPG file is CMYK and it doesn't have en embedded profile. You'll need to give `vipsthumbnail` an input profile for this image. 

I usually use this one:

https://github.com/jcupitt/nip2/blob/master/share/nip2/data/cmyk.icm

It works well for untagged CMYK. Use the `iprofile` option to `vipsthumbnail`.

**Comment by bender22** [comment]
Thanks a lot!
