### ISSUE TITLE
vips_mosaic Quality

### ISSUE THREAD

**Issue by zarlior** [jcupitt/libvips#631]
Hi,
Is there any quality measure parameter that mosaic method can return in case the mosaic of two images returns success.
I'm asking since sometimes the mosaic output image and offsets are wrong (because of bad input points) and it returns success. In this case we’d like to be aware of this situation to handle it better.

Also I would like to know if there is any way to insert image on to a large main image with the mosaic blending.

Thanks,
Lior.

**Comment by jcupitt** [comment]
You can use `merge` to join two images exactly where you say with no searching. 

The success / fail test for mosaicing could probably use some tuning. Do you have a pair of images that fail?

**Comment by zarlior** [comment]
Thanks a lot for the fast response!

From what I saw vips_merge fails if the inserted image is contained inside the main image.
I need the same functionality as vips_insert but with blending of everything that is not the background color of the main image (i.e black).

Sent two examples by mail.

Thanks again!
Lior.

**Comment by jcupitt** [comment]
Yes, merge joins a pair of images along a single edge.

You could make your own thing to blend one image into another. Make a mask, use gaussblur to feather the edge, use blend with the mask to mix the two images. It should be pretty quick.

**Comment by jcupitt** [comment]
I made you a tiny example program:

```python
#!/usr/bin/env python

import sys
import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

main = Vips.Image.new_from_file(sys.argv[1], access = Vips.Access.SEQUENTIAL)
sub = Vips.Image.new_from_file(sys.argv[2], access = Vips.Access.SEQUENTIAL)
output_filename = sys.argv[3]
x = int(sys.argv[4])
y = int(sys.argv[5])

# we want to make a mask to feather sub into main ... first, make a solid block
# of 255s the same size as sub
pixel = (Vips.Image.black(1, 1) + 255).cast("uchar")
mask = pixel.embed(0, 0, sub.width, sub.height, extend = "copy")

# now add a 1 pixel black border all around it
mask = mask.embed(1, 1, mask.width + 2, mask.height + 2, extend = "black")

# and blur with a large radius to feather the edges
mask = mask.gaussblur(20)

# the edge pixels will now be 128, but we want them to be zero ... subtract 128
# and *2 to get a 0 - 255 mask
mask = ((mask - 128) * 2).cast("uchar")

# now expand that up to the size of main, with the top-left of the mask 
# at (x, y)
mask = mask.embed(x - 1, y - 1, main.width, main.height, extend = "black")

# also expand sub up to the size of main, in the same way 
sub = sub.embed(x, y, main.width, main.height, extend = "black")

# and use the mask to blend between the main image and the sub we are pasting in
out = mask.ifthenelse(sub, main, blend = True)

out.write_to_file(output_filename)
```

**Comment by zarlior** [comment]
Thanks a lot!
I'll try it

**Comment by zarlior** [comment]
Blending works great... Thanks!
P.S did you get my examples by mail?

**Comment by jcupitt** [comment]
Yes, sorry, not got around to looking at them in detail yet.

**Comment by jcupitt** [comment]
I mailed you back the examples. I see a much larger xoff / yoff, larger by perhaps 20 or 30 pixels. I would guess this is cased by the pixel grid in the camera not being aligned with the axes of the translation stage. 

It doesn't matter, except that you will see a rotated final image with jaggy edges.

**Comment by zarlior** [comment]
I got your mail, thank you!

The thing is I know the tie point is wrong, but the problem is inaccurate HW which cases the offset so there is no way to predict it.
I need some way to know this is the case in order to handle it better.
What I did is calculated the coefficient correlation of the overlapped areas according to the mosaic output in order to get some scene of stitching quality.

Any thoughts of a better solution?

**Comment by jcupitt** [comment]
Ah OK. What causes the inaccurate movement? Your translation stage should get you within a couple of pixels --- 20 or 30 seems much too high.

**Comment by zarlior** [comment]
This is very high magnification (Around x40) so every small vibration causes big offset :)

**Comment by jcupitt** [comment]
Perhaps you could isolate the microscope more from vibration? Conical mounts are very effective, eg.:

https://www.amazon.co.uk/Vibration-Mounts-Stops-Rubber-AV/dp/B01JIVXAHG

You can change the parameters vips uses for the search algorithm. Normally it looks for object of size 11x11 pixels in an area of 30x30 pixels, but it seems you need at least double that. 

I tried:
