### ISSUE TITLE
Java wrapper

### ISSUE THREAD

**Issue by Tosken1337** [jcupitt/libvips#633]
Hi,

is there a java wrapper to the library?
Or can you help me in creating the java classes?

Thanks and best regards
Sebastian

**Comment by jcupitt** [comment]
Hi @Tosken1337, I think a few people are using it via JNI calls, but I don't think anyone's made a full binding.

If you'd like to make a proper binding I'd be delighted to help if I can. I don't know Java well, but I could help on the C side. I wrote some notes here: https://github.com/jcupitt/libvips/issues/59#issuecomment-291464701

I'll copy-paste them below for reference:

You can call the C API directly, for example `vips_extract_band()`:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-extract-band

But the C API is supposed to be nice for C programmers, it's not designed to be easy to call from other languages. For example, it makes heavy use of varargs, which is difficult to bind safely. 

I think the best solution would be to use the layer below: the thing that the C API calls. This gobject layer supports full introspection -- you can write a general function which can invoke any operation in libvips. If you write this one function, you then get the whole libvips API. 

I did a PHP binding recently like this. There's a 1,500 line C module you install that adds `vips_call`, a single php function that can run any vips operation:

https://github.com/jcupitt/php-vips-ext/blob/master/vips.c

It adds a couple of other functions too. Then there's a larger layer over that, all in php, that makes a nice php API:

https://github.com/jcupitt/php-vips

That's about 1000 lines of hand-written docs, 1000 lines of hand-written PHP, and 3000 lines of automatically-generated phpdoc. 

So I think I would reimplement the C stuff above in JS using node-ffi, then write a little wrapper to make it nice to use, then auto-generate everything else .It should only be a few days work, and you'd have a complete, dynamic libvips binding that kept itself up to date as the library expanded. 

There are some more notes on binding here:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/binding.html

They should be expanded a bit. 

Here are all the implementations of the call-anything function, for reference: 

PHP; https://github.com/jcupitt/php-vips-ext/blob/master/vips.c#L927
Python: https://github.com/jcupitt/libvips/blob/master/python/packages/gi/overrides/Vips.py#L279
C++: https://github.com/jcupitt/libvips/blob/master/cplusplus/VImage.cpp#L459
Ruby: https://github.com/jcupitt/ruby-vips/blob/master/lib/vips/call.rb
Ruby, but using ffi: https://github.com/jcupitt/gir_ffi-vips/blob/master/lib/vips8/call.rb
Command-line: https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/operation.c#L1328
C (this implements the varargs interface to libvips): https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/operation.c#L937

**Comment by jcupitt** [comment]
I'll close. Please reopen if you are interested in pursuing this.

**Comment by lopcode** [comment]
This thread shows up as result number 2 for me on Google if you search for "libvips java", so posting a couple of current options:
* https://github.com/lopcode/vips-ffm using FFM in JDK 22+
* https://github.com/criteo/JVips using JNI for older JVM versions (but now out of date, older libvips versions, 2 years since the last release)
