### ISSUE TITLE
new prototype libvips website ... feedback very welcome

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#634]
We have a new prototype website for vips!

http://jcupitt.github.io/libvips/

Good things about it:

* simple, quick, low maintenance
* integrates the old wiki pages, plus the github wiki pages
* integrates the blog as well
* integrates with the github release system
* integrates formatted docs

The blog is at the bottom of the main page. Click on "what's new" to
see a sample post.

The documentation is all generated automatically from the sources, and styled to match the site, for example:

http://jcupitt.github.io/libvips/API/current/using-from-python.html

I've converted all the pages on the old site and copied them over, but many need revising. You can see a list here:

https://github.com/jcupitt/libvips/wiki

Does anyone have any comments? The plan would be to point the old

http://www.vips.ecs.soton.ac.uk/

link at this some time soon and remove all the old content.

Possible questions:

* all the links to the old site scattered around the web will break, including scripts which expect to be able to download `www.vips.ecs.soton.ac.uk/supported/current` etc.
* there really are a lot of useless old pages on the wiki
* I've copied all the old images over, but pages don't always link to images correctly
* lots more, I'm sure

**Comment by ioquatix** [comment]
It's nice. I think that the intallation page could be a bit simpler.

I like keeping installation simple, perhaps you could list stuff like valgrind somewhere else, e.g. the Wiki?

**Comment by jcupitt** [comment]
Good idea, I've slimmed down the install page. The build on win and build on macos wiki pages need revising too.

**Comment by lovell** [comment]
It looks much cleaner and easier to read, plus is faster loading, thanks John.

I like having versioned API docs - is this in the plan for the new website?

**Comment by jcupitt** [comment]
That's true. How about:

```
API/8.5/index.html
API/8.4/index.html
... etc
```

And then `API/current` as a symlink to the currently supported one?

**Comment by jcupitt** [comment]
OK, seems to work! I shrank the banner a little more too.

**Comment by laszbalo** [comment]
IMO, it is hard to read, because the contrast ratio is to small (5.41:1).  Black text colour would be much better, instead of #606c71.

**Comment by jcupitt** [comment]
OK, I think I've made the body text darker. It might take a 'mo for the CSS to update.

**Comment by kleisauke** [comment]
Nice improvement!

Found a few (small) things:
- It looks like the syntax highlighting [for PHP](https://jcupitt.github.io/libvips/2017/03/16/What's-new-in-8.5.html) doesn't work? Maybe adding [this](https://sacha.me/articles/jekyll-rouge/#using-rouge-in-jekyll-3-on-github-pages) to `_config.yml` will fix that (or try to change `$filename = ...;` to `$filename = "image.jpg";`).

- Highlighting bash/shell code in markdown should work, instead of [tabs](https://raw.githubusercontent.com/jcupitt/libvips/gh-pages/install.md) you can use:
```
```shell
```

- The code-block generated by GTK-Doc looks weird. See [this](http://jcupitt.github.io/libvips/API/current/using-from-c.html#using-C-example) and [this](http://jcupitt.github.io/libvips/API/current/using-threads.html#id-1.2.11.7.3).

**Comment by jcupitt** [comment]
Thanks for having a look!

I tried rouge, but still no php highlighting :( strange.

I tried `shell` in a couple of places, it seems to help a little.

Not much we can do about `gtk-doc` output. It's being rewritten, apparently, so maybe in the next version.

**Comment by harukizaemon** [comment]
Not earth shattering feedback but LOVE IT!

**Comment by jcupitt** [comment]
OK, we finally have a redirect, so `www.vips.ecs.soton.ac.uk` is now pointing to the new site!

I asked them to redirect some popular URLs as well, but no luck so far :( Anyway, I'll close.
