### ISSUE TITLE
How to take advantage of libvips ?

### ISSUE THREAD

**Issue by betovidal** [jcupitt/libvips#635]
During some tests I found out that time taken by imagemagick's convert tool for scaling down by half and making tiles out of an image of 16384x16384 is faster than my method implemented in C with the libvips library. What I do in libvips is load the image, use the extract_area function for every tile I want (246x256 pixeles, making a total of 64x64=4096 single tiles for the initial image of 16384x16384 pixels) then scale down by half and extract tiles of the same size again until the whole image is scaled down to 256x256 pixels.

Can I make it faster using a different approach ? From the looks of my code I do it all sequentially: I use the same object for storing the current image for area extraction, I then scale down the image and store it in the same VipsImage object. Area extractions and file writing occur inside a double nested for loop.

**Comment by jcupitt** [comment]
Hi @betovidal, libvips has an operation that does exactly what you want very quickly. You can use the deepzoom pyramid builder, there are some notes here:

http://jcupitt.github.io/libvips/API/current/Making-image-pyramids.md.html

For example on my modest laptop, I see:

```
$ vipsheader 16k.jpg 
16k.jpg: 16384x16384 uchar, 3 bands, srgb, jpegload
$ time vips dzsave 16k.jpg x --depth onetile --tile-size 256 --overlap 0
real	0m6.906s
user	0m13.620s
sys	0m3.304s
```

Makes a directory  called `x_files` containing a subdirectory for each pyramid layer, with 0 being the smallest one. The `onetile` option means stop as soon as the image fits in to one tile.

```
$ ls x_files/
0  1  2  3  4  5  6
$ ls x_files/6
0_0.jpeg    18_50.jpeg  28_31.jpeg  38_12.jpeg  47_52.jpeg  57_33.jpeg
0_10.jpeg   18_51.jpeg  28_32.jpeg  38_13.jpeg  47_53.jpeg  57_34.jpeg
0_11.jpeg   18_52.jpeg  28_33.jpeg  38_14.jpeg  47_54.jpeg  57_35.jpeg
0_12.jpeg   18_53.jpeg  28_34.jpeg  38_15.jpeg  47_55.jpeg  57_36.jpeg
0_13.jpeg   18_54.jpeg  28_35.jpeg  38_16.jpeg  47_56.jpeg  57_37.jpeg
... etc.
$ ls x_files/6 | wc
   4096    4096   43776
```

So `x_files/6` has the 4096 tiles that make up the highest res layer.

You can call dzsave from C/C++/Python/PHP etc. as well:

http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-dzsave

It can do very large images using only a little memory. I regularly make pyramids of 200,000 x 200,000 pixels on this small laptop.

**Comment by betovidal** [comment]
Thanks for the quick response. Is there any way to have control over the names? So instead of having:

0_0, 1_0, 2_0
0_1, 1_1, 2_1
0_2, 1_2, 2_2

I get:

0_2, 1_2, 2_2
0_1, 1_1, 2_1
0_0, 1_0, 2_0

**Comment by jcupitt** [comment]
You could try google maps mode. That names the tiles as `dir/z/y/x.jpg`, so it's easy to rename any way you like.

**Comment by betovidal** [comment]
Thank you very much.
