### ISSUE TITLE
Homebrew installation currently broken

### ISSUE THREAD

**Issue by joao** [jcupitt/libvips#636]
Just to give a heads up that a dependency,  giflib, of installing via homebrew on macOS was updated to its latest version, with Vips no longer working.

If giflib is updated to the new giflib-5.1.4, vips on the command line will return:
`dyld: Library not loaded: /usr/local/opt/giflib/lib/libgif.4.dylib
  Referenced from: /usr/local/bin/vips
  Reason: image not found
Abort trap: 6`

To fix this for now you have to uninstall giflib:
`brew uninstall --ignore-dependencies giflib`
and reinstall using an older version, 4.2.3, using:
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/5e869b6975f1d031e85609eba32ab62412cf7ed8/Formula/giflib.rb`

Vips will work properly now.

**Comment by evadne** [comment]
At this moment I have the same issue, but worked around it differently using:

    $ brew install --build-from-source vips

This builds a fresh version which seems unaffected. I can only presume that otherwise Homebrew is pulling down a binary which refers to an old version of libgif.

**Comment by jcupitt** [comment]
Looks like homebrew is fixed now, with a `vips.rb` for 8.5.3. I'll close.
