### ISSUE TITLE
webp vips issue

### ISSUE THREAD

**Issue by juyunsang** [jcupitt/libvips#637]
Good morning.
I am creating a webp thumbnail using vips.
By the way, when creating webp thumbnail in vips, do not copy exif.
I have developed a logic to exif copy using libwebp. Exif copying while creating thumbnail inside vips seems to improve performance.
I checked using libwebp 0.4.x version from vips,
I have libwebp 0.6.0 and do not plan to use the higher version of libwebp in vips?
And do not plan to exif copy when you create a webp thumbnail?

**Comment by jcupitt** [comment]
Good morning,

You can disable metadata (EXIF, ICC, XMP) copying with `--strip`, for example, for a 10000 x 10000 pixel webp image on this laptop I see:

```
$ time vipsthumbnail wtc.webp -o x.jpg[strip]
real	0m1.308s
user	0m1.628s
sys	0m0.016s
$ time vipsthumbnail wtc.webp -o x.jpg
real	0m1.331s
user	0m1.668s
sys	0m0.012s
```

But I don't think it will make much difference to speed.

I'm using 0.5.1, but I think it ought to work with 0.6.

**Comment by lovell** [comment]
IIRC libwebp has to be compiled with the `--enable-libwebpmux` flag to enable writing metadata to the WebP container.

**Comment by jcupitt** [comment]
Yes, and libvips needs to be able to find libwebpmux as well. You should see something like this in libvips configure output:

```
support webp metadata:			yes
  (requires libwebpmux-0.5 or later)
```

I hope they move libwebpmux into the core library, it seems a little crazy to have metadata in a separate thing.

**Comment by juyunsang** [comment]
Good morning.
If you install the webp master branch, libwebpmux is lower than the version required by libvips.
Ldconfig -p | Grep webp
Libwebpmux.so.3 (libc6, x86-64) => /usr/lib/libwebpmux.so.3
Libwebpmux.so (libc6, x86-64) => /usr/lib/libwebpmux.so
Libwebp.so.7 (libc6, x86-64) => /usr/lib/libwebp.so.7
Libwebp.so (libc6, x86-64) => /usr/lib/libwebp.so

Webpmux -version
0.4.0

The result of configure.

* Build options
Native win32: no
Native OS X: no
Open files in binary mode: no
Enable debug: yes
Build deprecated components: yes
Build docs with gtkdoc: no
Gobject introspection: no
Build vips7 Python binding: yes
Install vips8 Python overrides: no
  (Requires pygobject-3.13.0 or later)
Build radiance support: yes
Build analyze support: yes
Build PPM support: yes

* Optional dependencies
Use fftw3 for FFT: yes
Magick package: MagickCore
File import with libMagick: yes (magick6)
Accelerate loops with orc: no
  (Requires orc-0.4.11 or later)
ICC profile support with lcms: yes (lcms2)
File import with OpenEXR: yes
File import with OpenSlide: no
  (Requires openslide-3.3.0 or later)
File import with matio: no
PDF import with poppler-glib: no
  (Requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0: yes
  (Requires librsvg-2.0 2.34.0 or later)
Zlib: yes
File import with cfitsio: yes
File import / export with libwebp: yes
  (Requires libwebp-0.1.3 or later)
Support webp metadata: no
  (Requires libwebpmux-0.5 or later)
Text rendering with pangoft2: yes
File import / export with libpng: yes (pkg-config libpng> = 1.2.9)
  (Requires libpng-1.2.9 or later)
File import / export with libtiff: yes (pkg-config libtiff-4)
File import / export with giflib: no
File import / export with libjpeg: yes
Image pyramid export: no
  (Requires libgsf-1 1.14.26 or later)
Use libexif to load / save JPEG metadata: yes

How do I install libwebpmux-0.5?
Thank you for your reply.

**Comment by jcupitt** [comment]
Did you build your own copy of libwebp? If you did, check the output of configure when you built it. As @lovell says, you need to enable libwebpmux. 

I tried with:

```
$ git clone https://chromium.googlesource.com/webm/libwebp
$ cd libwebp
$ ./autogen.sh
$ ./configure --prefix=/home/john/vips --enable-libwebpmux --enable-libwebpdemux --enable-libwebpdecoder
$ make
$ make install
```

Where `/home/john/vips` is the prefix I build experimental stuff to, then I see:

```
$ pkg-config libwebpmux --modversion
0.6.0
```

I'm not sure if I need all those config flags. Anyway, webp is daft to be split up so much, and to have essential functionality off by default.

**Comment by juyunsang** [comment]
안녕하세요
dependency문제로 libwebp version이 꼬였습니다.
문제는 해결했고 vipsthumbnail로 Thumbnail을 생성했습니다.
그런데 jpeg -> webp Thumbnail 생성시에는 exif가 제거되었습니다.
webp -> jpeg일때도 Exif Width, Height, Orientation이외의 exif 정보들은 삭제가 되었습니다.

**Comment by juyunsang** [comment]
Good morning
The libwebp version is corrupted due to a dependency problem.
I solved the problem and created a Thumbnail with vipsthumbnail.
However, exif is removed when jpeg -> webp Thumbnail is created.
Exif information other than Exif Width, Height and Orientation has been deleted even when webp -> jpeg.

**Comment by jcupitt** [comment]
Hello again, could you try just using copy? With this test image:

https://upload.wikimedia.org/wikipedia/commons/4/45/Equus_quagga_burchellii_-_Etosha%2C_2014.jpg

I see this:

```
$ vipsheader -a quagga.jpg 
quagga.jpg: 4120x2747 uchar, 3 bands, srgb, jpegload
width: 4120
height: 2747
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 11.811
yres: 11.811
filename: quagga.jpg
vips-loader: jpegload
jpeg-multiscan: 0
exif-data: 7618 bytes of binary data
ipct-data: 9112 bytes of binary data
xmp-data: 8812 bytes of binary data
icc-profile-data: 560 bytes of binary data
resolution-unit: in
exif-ifd0-Make: Canon (Canon, ASCII, 6 components, 6 bytes)
exif-ifd0-Model: Canon EOS-1D Mark IV (Canon EOS-1D Mark IV, ASCII, 21 components, 21 bytes)
exif-ifd0-Orientation: 1 (Top-left, Short, 1 components, 2 bytes)
exif-ifd0-XResolution: 3000000/10000 (300.0000, Rational, 1 components, 8 bytes)
exif-ifd0-YResolution: 3000000/10000 (300.0000, Rational, 1 components, 8 bytes)
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd0-Software: Adobe Photoshop CC (Macintosh) (Adobe Photoshop CC (Macintosh), ASCII, 31 components, 31 bytes)
.... snip
```

Then:

```
$ vips copy quagga.jpg quagga.webp
john@kiwi:~/pics$ vipsheader -a quagga.webp 
quagga.webp: 4120x2747 uchar, 3 bands, srgb, webpload
width: 4120
height: 2747
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 11.811
yres: 11.811
filename: quagga.webp
vips-loader: webpload
icc-profile-data: 560 bytes of binary data
xmp-data: 8812 bytes of binary data
exif-data: 7532 bytes of binary data
resolution-unit: in
exif-ifd0-Make: Canon (Canon, ASCII, 6 components, 6 bytes)
exif-ifd0-Model: Canon EOS-1D Mark IV (Canon EOS-1D Mark IV, ASCII, 21 components, 21 bytes)
exif-ifd0-Orientation: 1 (Top-left, Short, 1 components, 2 bytes)
exif-ifd0-XResolution: 3000000/10000 (300.0000, Rational, 1 components, 8 bytes)
exif-ifd0-YResolution: 3000000/10000 (300.0000, Rational, 1 components, 8 bytes)
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd0-Software: Adobe Photoshop CC (Macintosh) (Adobe Photoshop CC (Macintosh), ASCII, 31 components, 31 bytes)
... snip
```

If your webp image is missing metadata, you need to check that your libvips has both libexif and libwebpmux support working.

**Comment by juyunsang** [comment]
Good morning
Vips webp thumbnail generation is very successful and well done.
The speed is also satisfactory.
I created the code using the webpmux library separately
I am very sorry that webpmux is slow to exif copy.
Thank you for answer.
Vips I am using it very satisfactorily.

**Comment by jcupitt** [comment]
OK, glad it's working, I'll close.
