### ISSUE TITLE
FITS error

### ISSUE THREAD

**Issue by benepo** [jcupitt/libvips#640]
The Ubuntu repository version and the master version compiled from source both throw this error when converting the [attached FITS image](https://www.dropbox.com/s/qc15szdrktir0yq/S11.zip?dl=0):

```
$ vips -v
vips-8.5.3-Fri Apr 14 20:25:08 UTC 2017
$ vips cast S11.fits example.png uchar
fits: bad number of axis 0
```

Note: The FITS image converts fine with imagemagick, fitspng, and loads fine in FITS Liberator 3.

**Comment by jcupitt** [comment]
Looking at the file, it has a huge chunk of metadata at the start (with naxis set to 0), then an END, then a second chunk of data containing the image.

```
$ fold S11.fits | more
SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                    8 / number of bits per data pixel                  
NAXIS   =                    0 / number of data axes                            
EXTEND  =                    T / FITS dataset may contain extensions  
```

Is that a standard way to ad extra metadata? Should vips just skip all sections with naxis == 0?

I'll see it I can get cfitsio to do this.

**Comment by jcupitt** [comment]
git master libvips seems to work on your image now, though I'm seeing some black pixels in the centre of the brightest stars, which is worrying. It looks like a wrap-around error. 

vips isn't doing this, it's cfitsio, I think. Do you see black pixels in other viewers? ImageMagick seems to have the same problem.

**Comment by jcupitt** [comment]
Possible overflow:

![screenshot from 2017-04-15 13-33-39](https://cloud.githubusercontent.com/assets/580843/25063589/4636fe76-21e0-11e7-854f-90fc6fb7f597.png)

**Comment by benepo** [comment]
Sorry for the delayed response....

Yes, the new version of VIPS now works (thanks!) and the black pixels appear to be artifacts introduced by our PhoSim algorithm and can be ignored.
