### ISSUE TITLE
Question: Am I using mosaic1 correctly?

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#641]
I have [two images from a mosaic](https://www.dropbox.com/s/6iisrxer6ttqi26/mosaic.tar.gz?dl=0) I'm trying to stitch together, somewhat automagically.

At face value the images look pretty simple to stitch: they are each 4096 x 3536 with approximately 15% overlap in the horizontal; a little bit in the vertical.

I used the following command:

```
vips mosaic1 lhs.tif rhs.tif stitched.tif horizontal \
  3481 0 0 0 \
  3481 3535 0 3535 \
  --search=true
```

Is there something I could/should be doing to improve the results?

Thanks,
Simon

**Comment by jcupitt** [comment]
Hi, tried like this:

```
vips mosaic1 lhs.tif rhs.tif x.v horizontal 3665 442 194 270 3551 3142 87 2971 --search
```

And it looks mostly OK. You can just make out the join, since the noise is different in the two images. It looks like about 175 pixels offset vertically, 640 horizontally, plus a small rotation, though that's so small it may just be noise. i guess the slide is on a translation stage? In which case, i would just do a simple translation and not rotate at all.

**Comment by harukizaemon** [comment]
Interesting, thanks.

So I guess I don't really understand what the tie points are but it seems like they're most useful if you can visually inspect the images. Something that may not be practical given that those were two slides from a much larger image.

In this case there's not much rotation but I have other examples where there is quite a bit.

Sounds like I might need to try a different approach, something more exhaustive like a FFT for example like [this](http://imagej.net/Image_Stitching#Overview_of_the_Stitching_Plugins).

As always, thank you so much for your help.

**Comment by jcupitt** [comment]
Yes, FFT is a good choice for a large search. You'll need a big overlap, of course. 

It might be worthwhile to look into the causes of rotation. I'd consider:

* Problems with the translation stage. If the axies are not quite straight, the stage could rotate slightly as it moves. I'd expect this sort of rotation to be rather small, perhaps under a micron, and maybe you could just ignore it. One scanner project we did used the stepper motors on a stage to drive the platform to sub-pixel precision and for that we had to calibrate for the variable threading on the drive shafts. Hopefully you won't need to do that. 
* Misalignment of the camera and stage axies. If the XY of the grid of pixels in the camera is not aligned with the translation stage axies, you'll see a constant XY displacement on every join. It doesn't really matter, except that you will see jaggy edges and a rotated final image. I remember spending a lot of time with an allen key trying to fix this with our large scanner :( 
* Misalignment of the focal plane and translation plane. This will cause things to get slightly larger or smaller as they move across the camera's field of view. Again, the quality of your camera mount would be important. 
* Rotation of the camera during scanning. I think this is the only thing that could cause a large rotational error in mosaicing. This is obviously a disaster and anything you could do to fix the camera more securely would be great.

**Comment by jcupitt** [comment]
(perhaps you're doing all these things already)
