### ISSUE TITLE
24 bits bit-depth

### ISSUE THREAD

**Issue by sohaibghani1** [jcupitt/libvips#642]
For the same image, if i generate deep zoom tiles through deep zoom composer i am getting images in the tiles with bit depth of 32 bits. However for the same image vips is generating tile images with bit depth of 24 bits. So colors look bit bad as compare to deep zoom composer tiles images. Why is it so? How can i generate deep zoom tiles with better bit rate? Thanks

**Comment by jcupitt** [comment]
Hi again, could you post a sample tile from deep zoom and one from vips to show the colour difference? Drag the png files into the comment window to upload.

**Comment by sohaibghani1** [comment]
![deepzoomcomposer_tiles](https://cloud.githubusercontent.com/assets/24861964/25218070/2def8434-25b2-11e7-9564-379d279e9cbe.PNG)
![vips tiles](https://cloud.githubusercontent.com/assets/24861964/25218087/3d6bf03c-25b2-11e7-9749-f6a08d9b494a.PNG)

These are two images zoomed in the open sea dragon viewer. First shows tiles generated by deep zoom composer and second by vips. The screenshot may have reduced the difference but it is still there to see.

**Comment by jcupitt** [comment]
Sorry, I need the actual tiles so I can check the profiles. Go into the tree of tiles made by DZC and by vips, and upload the same `mypyr_files/9/0_0.png` or whatever tile from each tree.

**Comment by sohaibghani1** [comment]
![0_0](https://cloud.githubusercontent.com/assets/24861964/25219014/951bf00e-25b5-11e7-8fdf-2c2243e8b03a.png)
![0_0](https://cloud.githubusercontent.com/assets/24861964/25219036/ae86341e-25b5-11e7-8d95-1171173aa781.png)
first one is deep zoom composer second one is vips.

**Comment by jcupitt** [comment]
Hmm, those two tiles are identical, the dzc one just has an alpha channel, with every pixel set to opaque. There's no ICC profile, and every pixel has the same value. I also tried loading into two Chrome tabs and flipping, but I couldn't see any change.

Can you find a pair of tiles which look different?

**Comment by sohaibghani1** [comment]
The tiles look similar but on zooming in the viewer there is minor difference in color.

**Comment by jcupitt** [comment]
I think they are identical, try loading them into Photoshop and examining pixels with the eyedropper, I think you'll find the same numeric value at every point. 

Could the difference be in your display? LCD screens do not have very good colour uniformity --- if you put two images side by side, they will always look slightly different, because the angle to your eye will not be the same. The best way to see differences is to put the two images into two browser tabs, and then flip quickly back and forth between them.

You can find the maximum absolute pixel difference with vips as well. I have them saved as `vips.png` and `dzc.png`. First drop the extra alpha channel from the dzc tile:

```
$ vips extract_band dzc.png x.v 0 --n 3
```

That will create the file `x.v`, with 3 bands starting from band 0 (ie. no 4th band, the alpha), then:

```
$ vips subtract x.v vips.png x2.v
$ vips abs x2.v x3.v
$ vips max x3.v
0.000000
```

The subtract, abs, max.

**Comment by sohaibghani1** [comment]
ok.  Thank you for the details.

I have another question which is not directly related to vips but since you are the expert in this area i hope you can help me.

I am generating pixel based image of high resolution where each pixel color is representing some information. I then generate deep zoom tiles through vips and show it in the open sea dragon viewer. The problem i am getting is that in the open sea dragon viewer when i am zooming down pixels seems to be distorted. In the original image if i zoomed in, at the lowest zoom in level i can clearly see pixels. In the generated deep zoom tiles as well, at the highest tile level each tile image can be zoomed in to see clear pixels. Why open sea dragon not showing clear pixels at the zoom in?

Original image: https://www.dropbox.com/s/m7zj572vr1bizk3/y.png?dl=0

I zoomed in one of the highest level tiles images to show how each pixel is looking at zoom in. (i took tile of level 13, 4_3)
https://www.dropbox.com/s/x0y6uphp1snzqwh/zoomed%20in%20tile4_3%20level13.PNG?dl=0

This image is zoomed in open sea dragon: https://www.dropbox.com/s/4zbx07qqdpvdic5/zoomed%20in%20open%20sea%20dragon%20image.PNG?dl=0

Please let me know how i can see clear pixels at zoom in in the open sea dragon. Thank You so much.

**Comment by jcupitt** [comment]
OpenseaDragon is using an interpolator to upsize your images. You want nearest-neighbour (hard pixel edges), but they are using something like bilinear (soft edges).

I would check the docs, and then ask on the openseadragon issue tracker is you can't see the option to turn interpolation off.

As a quick hack, you could do the pixel scaling on the source image instead. Type:

```
vips zoom myfile.tif mydz.dz[suffix=.png] 5 5
```

That will do a 5x zoom on your image before writing the deepzoom pyramid.

**Comment by jcupitt** [comment]
I meant to say, I guess you saw the zip write option? You can use `dzsave` with a .zip suffix:

```
vips dzsave hugetif mypyr.zip --suffix .png
```

And it'll create a zip file containing the tiles. On Windows, this is much faster than writing the pyramid directly, and it makes it easy to upload to your server.

**Comment by sohaibghani1** [comment]
Thanks alot John. 

I only need interpolation off in the open sea dragon viewer so that i can see clear pixels. Please let me know once you find in the docs how to turn off this interpolation.

I will also try pixel scaling and will see the results.
The zip is fast but will it have any effect on the pixel or interpolation?

Once again thank you for your great help.

**Comment by jcupitt** [comment]
I'm not an openseadragon expert, you should ask there.

No, the zip won't affect pixels or interpolation.

I'll close this issue, I think we're done.

**Comment by sohaibghani1** [comment]
ok. Thank You.
