### ISSUE TITLE
compromised arrayjoin

### ISSUE THREAD

**Issue by tumagonx** [jcupitt/libvips#643]
I'm making comic strip,  where sometime double page (single image from joined two pages) appear , thus screw the grid proportion of arrayjoin. Is it possible that images that surpass hspacing automatically split into two (or more) grid instead of being cropped?

**Comment by jcupitt** [comment]
I'm not sure I understand exactly, could you post an example?

`arrayjoin` is really for joining many thousands of images in a regular grid. If you have less than 1000 or so, you can just use `insert` and put the frames where you like.

**Comment by tumagonx** [comment]
A regular manga book will be about 200 pages, multiple series could well exceed 1000 pages.
I'm still experimenting this "image strip" in a panoramic viewer (the width may close to PNG limit of 1MP)
all page is 1200px height, with width ~850px (irregularities still within 20px difference). However once vips encounter joined (landscape) double page image (which its width will set for hspacing) thus output looks bad (gaps between images to big).

Example :
Spec:
Windows 10 64bit
Python 3.4 VIPS 8.4.5

taken from your example:
...
import os
import sys
import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

Vips.progress_set(True)

images = []
for dirname in sys.argv[2:]:
    for filename in os.listdir(dirname):
        images.append(Vips.Image.new_from_file(os.path.join(dirname,filename),
                                               access = Vips.Access.SEQUENTIAL))

join = Vips.Image.arrayjoin(images, hspacing = 850)
join.write_to_file(sys.argv[1])
...

what I wish is the double page being split into/treated as two grid allocation, instead being cropped. I could do this separately, but since special treatment already there (crop) I wonder if different treatment possible too (slice).

**Comment by tumagonx** [comment]
Will "insert" perform as fast as arrayjoin?
my case above, 850000x1200 output from 1000 input take 4 minutes.

**Comment by jcupitt** [comment]
Ah OK, I think I see. Yes, `insert` is the same speed as `arrayjoin`, the difference is that you can use `arrayjoin` to join up 10,000 or more images. 

I think most of your 4 minute run time with be spent on image read and write. I guess these are PNG files? I think 90%+ of the time will be in PNG write, it is very slow. If you write TIFF you'll find it's a lot quicker.

**Comment by tumagonx** [comment]
OK thanks.
Inputs are webp, Yes, mostly spent for PNG write, though I already use special optimized zlib...
hmm.. TIFF lzma might be smaller size than PNG...  but read and write will take forever :D
unfortunately VIPS not yet support BPG, I think it also capable of "Big Image" format.

**Comment by jcupitt** [comment]
For a 10k x 10k jpg on this laptop, I see:

```
$ time vips copy wtc.jpg wtc.png
real	0m27.804s
user	0m27.976s
sys	0m0.180s
```

Uncompressed tiff is more than 10x faster:

```
$ time vips copy wtc.jpg wtc.tif
real	0m2.313s
user	0m1.060s
sys	0m0.380s
```

WIth deflate (zip) compression, you see almost the same file size as PNG, but 3x faster:

```
$ time vips copy wtc.jpg wtc.tif[compression=deflate]
real	0m11.028s
user	0m11.268s
sys	0m0.256s
```

Or conversely, with PNG compression off, you see the same size as uncompressed TIFF, but 3x slower:

```
$ time vips copy wtc.jpg wtc.png[compression=0]
real	0m4.574s
user	0m4.144s
sys	0m0.248s
```

libpng is really very slow :-(
