### ISSUE TITLE
Question: How to make sure that converted image always has a gamma of 2.2?

### ISSUE THREAD

**Issue by laszbalo** [jcupitt/libvips#644]
I have tif, png and jpeg images. I want to re-sample them with vipsthumbnail and then feed the result to Google's Guetzli. Guetzli requires PNG or JPEG images in sRGB profile with a gamma of 2.2.

First, all files are converted to PNG. I assume, that embedding the colour profile will fulfil the first requirement of Guetzli. Also, without this conversion, the JPEG files would suffer quality loss twice (both after resampling, and after Guetzli). By converting them first to PNG, the JPEG re-save will happen only once (after Guetzli)
```bash
vips copy input.(jpg|png|tif) foo.png[profile=/usr/share/color/icc/colord/sRGB.icc,strip]
```

Now, how can I make sure, that all my files will have a gamma of 2.2?
Thanks.

**Comment by jcupitt** [comment]
Hi, 2.2 is the sRGB standard gamma, pretty much everything will be 2.2 already. If you have some crazy images in some other space, you can use `icc_transform` to force them to sRGB, or use the colour management stuff in `vipsthumbnail` to do it for you.

For example:

```
vipsthumbnail foo.tif -o out.png[strip] -s 128x128 --eprofile=/usr/share/color/icc/colord/sRGB.icc
```

That will write `out.png` in sRGB space with no profile.
