### ISSUE TITLE
Docs about resize algorythm?

### ISSUE THREAD

**Issue by puzrin** [jcupitt/libvips#645]
IMHO it would be nice to document resize algorythm in details. Because it's a one of the most frequent feature to use. That will help to understand difference with another packages (im/gm).

As far as i remember, last time you described logic here https://github.com/lovell/sharp/issues/310#issuecomment-195054707.

There are still some unclear places. At first stage, as far as i understand, you use integer scaledown. Having integer scale allows use linear filtering (just count average on window, with window size = 1.0). But what happens on image edges?

> For example, to shrink a 1000 x 1000 pixel image down to 128 x 128, you would first do a 7 x 7 box shrink to get a 142 x 142 image, then lanczos3 with a residual of (128 / 142), about 0.9, to get exactly to 128 x 128.

`1000 x 1000 -> 142 x 142` is not dividable by 7 exactly.

**Comment by jcupitt** [comment]
Hi, there's a page on the wiki:

**Comment by puzrin** [comment]
Seems link is not shown in your message. I've looked all wiki pages and could not find something similar.

**Comment by jcupitt** [comment]
Sorry, I pressed comment by mistake before finishing the message. Have a look on the github page for this issue.
