### ISSUE TITLE
Question: Any good plotting tools?

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#647]
I want to take a histogram produced by VIPS and generate an visualisation as an image. Is there anything you can think of that might be of use?

**Comment by jcupitt** [comment]
nip2 can do this. For example, this command:

```
$ nip2 -e '(hist_find(Image_file argv?1)).to_image 100' /data/john/pics/k2.jpg -o x.png
```

Writes this PNG:

![x](https://cloud.githubusercontent.com/assets/580843/25434737/66dc178a-2a85-11e7-9347-8d1624626c26.png)

You can add labels and stuff, though it gets a little more complicated. I made a demo script:

```
#!/home/john/vips/bin/nip2 --script

image = Image_file argv?1;
hist = hist_find image;
plot = Plot [
        $style => Plot_style.LINE,
        $format => Plot_format.YYYY,
        $xmin => 0,
        $xmax => 255,
        $ymin => 0,
        $ymax => 50000,
        $xcaption => "I'm a banana",
        $ycaption => "Oh yes I am",
        $caption => "Bananation",
        $series_captions => ["one", "two", "three"]
] hist.value;
main = plot.to_image 100;
```

You can run it like this:

```
$ ./try239.nip2 /data/john/pics/k2.jpg -o x.png
```

And it'll make something like this:

![x](https://cloud.githubusercontent.com/assets/580843/25435318/822b399c-2a87-11e7-8d2e-ccfd3441bb9e.png)

Explanation:

* `Image_file` is a constructor for the `Image` class: it makes an image from a string (by loading it).
* `argv` is a list of the command-line arguments.
* `?` is infix list index.
* `hist_find` finds a histogram, returning a `Plot_histogram` object ... this is a subclass of `Plot` set up to display a basic histogram, and `Plot` is in turn a subclass of `Image`.
* You can use `Plot` directly to make a plot object from an image, passing in a set of options. This example sets all the options that `Plot` supports at the moment. You can also plot `XYXY` (ie. a scatter plot) and `XYYY` (ie. first band is index) and display as bar, line or point.
* The `to_image` method on a `Plot` object renders to a bitmap at a specific DPI.

**Comment by jcupitt** [comment]
The easy answer is to save as CSV and load into a spreadsheet or gnuplot.
