### ISSUE TITLE
8.4.5 compile error on Centos 6.5

### ISSUE THREAD

**Issue by Vaz133** [jcupitt/libvips#649]
Hi,

I am receiving the following error on Centos 6.5 when running make:

```
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../.. -I../../libvips/include -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -I/usr/lib64/glib-2.0/include -I/usr/include/pango-1.0 -I/usr/include/libxml2 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/include/freetype2 -g -O2 -MT vips2jpeg.lo -MD -MP -MF .deps/vips2jpeg.Tpo -c vips2jpeg.c  -fPIC -DPIC -o .libs/vips2jpeg.o
In file included from vips2jpeg.c:148:
jpeg.h:80: error: expected ‘)’ before ‘*’ token
make[3]: *** [vips2jpeg.lo] Error 1
make[3]: Leaving directory `/var/tmp/vips-8.4.5/libvips/foreign'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/var/tmp/vips-8.4.5/libvips'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/tmp/vips-8.4.5'
make: *** [all] Error 2
```

Any help would be greatly appreciated.

Thanks

**Comment by jcupitt** [comment]
Hi, I think you're missing the headers for libexif. 

8.4.5 had a small bug where compile would fail if jpeg was enabled but there was no libexif. This is fixed in the current version, 8.5.4:

https://github.com/jcupitt/libvips/releases

**Comment by Vaz133** [comment]
Thank you! This worked great.

I do have one more question if you don't mind. I am hoping to use the dzsave function, but it seems that for some reason libgsf-1 is not found during configure, even though I have it installed. Forgive my ignorance as computer science/programming is not my background, but do I need to do something specific so that it can find libgsf-1 during configure? Does it need to be added to my PATH?

Thanks again so much for your help!

**Comment by jcupitt** [comment]
You don't need to build from source, it's in centos6, called `libgsf-devel`, I think:

https://centos.pkgs.org/6/centos-x86_64/libgsf-devel-1.14.15-5.el6.x86_64.rpm.html

Don't download that RPM, just search for it in your package manager.
