### ISSUE TITLE
Reading pixel value from a 16 bit greyscale image

### ISSUE THREAD

**Issue by starcraft4390** [jcupitt/libvips#650]
Hello everyone, 

I'm new in the image processing field, and I'm trying to use libvips with c++ to get some stats from my images. 
The idea is to calculate the pixels mean value and the standard deviation from an image where the value of the related mask is different than 0.  The image is a 16 bit greyscale image.

Here are some part of my code:

```
VImage img = VImage::new_from_file(imgPath).colourspace(VIPS_INTERPRETATION_GREY16);
VImage mask =  VImage::new_from_file(imgPath);

VipsRegion  *regionMask = NULL;
VipsRegion  *regionImg = NULL;
VipsRect    rect;
int height = img.height(),
     width = img.width();
statList<double> myStatList;
regionMask = vips_region_new(mask.get_image());
regionImg = vips_region_new(input.get_image());
 for (int j = 0; j < height; ++j) {
    rect = {0, j, width, 1};
    if (vips_region_prepare(regionMask, &rect))
        exit(1);
    if (vips_region_prepare(regionImg, &rect))
        exit(1);
    for (int i = 0; i < width; ++i) {
        if ((ushort)VIPS_REGION_ADDR(regionMask, i, j)[0] != 0) {
            cout << "ushort: " << (ushort) VIPS_REGION_ADDR(regionImg, i, j)[0]
                 << " int: " << (int) VIPS_REGION_ADDR(regionImg, i, j)[0]
                 << " ref: " << img.getpoint(i, j)[0] << endl;
            myStatList.push_back((short) VIPS_REGION_ADDR(regionImg, i, j)[0]);
        }
    }
}
```
The output I get is: 

ushort: 246 int: 246 ref: 246
ushort: 2 int: 2 ref: 258

The problem seems to come from my usage of "VIPS_REGION_ADDR" against "getpoint".
What did I miss ? What is the good way of using "VIPS_REGION_ADDR" to get the same result as "getpoint" ? 

Any help would be greatly appreciated.

Thanks

**Comment by jcupitt** [comment]
Hi, just use the vips operators to do what you want, you don't need to loop yourself.

* test for mask != 0, take the average, divide by 255 and multiply by the number of pixels to get the number of masked elements
* use ifthenelse to set all non-masked pixels in your source image to 0
* take the histogram of the masked image
* now you know the 0 pixels won't contribute to sum or sum of squares, so you can calculate average and deviation from the histogram in the obvious way

I'll make you a sample program.

**Comment by starcraft4390** [comment]
Thank you a lot for your help, it's much appreciated.

**Comment by jcupitt** [comment]
Untested, but I think it'll work. It should get you started anyway:

```C++
// compile with
//      g++ masked-stats.cpp `pkg-config vips-cpp --cflags --libs`

#include <stdio.h>
#include <stdlib.h>

#include <vips/vips8>

using namespace vips;

int
main( int argc, char **argv )
{ 
        if (VIPS_INIT (argv[0]))
                vips_error_exit (NULL);
  
        if( argc != 3 ) 
                vips_error_exit( "usage: %s image-file mask-file", argv[0] );

        // we need to make two passes over the mask file: one to get some
        // stats, one to use it as a mask

        // do the stats pass first
        VImage mask = VImage::new_from_file( argv[2],
                VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );
        if( mask.bands() != 1 )
                vips_error_exit( "mask has more than one band" );

        // !=0 will set non-zero pixels to 255 ... so N is the number of
        // non-zero pixels
        double N = ((mask != 0).avg() * mask.width() * mask.height()) / 255.0;

        // second pass ... mask with the image and find the histogram
        mask = VImage::new_from_file( argv[2], 
                VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );

        // we make a single pass over the main image
        VImage image = VImage::new_from_file( argv[1],
                VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );

        // vips_stats() is a thing that calculates many image stats in a
        // single pas
        VImage stats = mask.ifthenelse( image, 0 ).stats();

        // we want sum and sum of squares from the stats image ... columns 2
        // and 3
        double sum = stats.getpoint( 2, 0 ).front();
        double sum2 = stats.getpoint( 3, 0 ).front();

        printf( "mean of masked pixels = %g\n", sum / N );
        printf( "sdev of masked pixels = %g\n", 
                sqrt( (sum2 - sum * sum / N) / (N - 1) ) );

        return( 0 );
}
```

**Comment by jcupitt** [comment]
.. I used `vips_stats()` in the end, it was a bit simpler than calculating a histogram.

**Comment by starcraft4390** [comment]
I will integrate it right now and keep you up to date. Thank you again for your amazing help.

**Comment by starcraft4390** [comment]
It's working really well, thank you again. 
Last question, why do you open the mask twice ? The calcul of N is non-destructive, so can we do the following ? 
```
VImage image = VImage::new_from_file( argv[1],  VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );
VImage mask = VImage::new_from_file( argv[2],  VImage::option()->set( "access", VIPS_ACCESS_SEQUENTIAL ) );
    if( mask.bands() != 1 )
        vips_error_exit( "mask has more than one band" );
double N = ((mask != 0).avg() * mask.width() * mask.height()) / 255.0;
VImage stats = mask.ifthenelse( image, 0 ).stats();
```

**Comment by jcupitt** [comment]
Hi, the `SEQUENTIAL` flag means "I guarantee I will access each pixel exactly once and exactly top to bottom". In fact it keeps a small cache, so you can make small non-local references. 

If you set the flag, vips can stream the image though your computer. If you don't set it, vips will assume you want random access, so it has to decompress the entire image in advance and keep it in a huge memory buffer or temporary disc file.

So ... don't use SEQ and you can just reuse the mask, no need to open again. Use SEQ and you should see a good drop in memuse and a nice speed increase, but you have to open again for the second pass over the image.

**Comment by starcraft4390** [comment]
Got it ! Thank you again for your help and your time.

**Comment by jcupitt** [comment]
No problem, glad it's working.
