### ISSUE TITLE
Question: CZI format support

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#651]
Anyone know of something that can open CZI (Carl Zeiss Image) format files?

**Comment by bgilbert** [comment]
Check out Bio-Formats and czifile.py.

**Comment by harukizaemon** [comment]
@jcupitt Hi John. We are seeing more and more people using CZ light microscopes and wondered if you'd consider supporting the file format? We would be more than happy to help out—one of us is a C/C++ dev and I was once accused of being so myself, albeit 20 years ago :)

**Comment by jcupitt** [comment]
Hi, I think czi support should probably go into openslide rather than directly into libvips. 

There's an issue here:

https://github.com/openslide/openslide/issues/144

I'd ask there about how you could contribute.

**Comment by harukizaemon** [comment]
Fair enough. I suspect we'll just end up writing our own. All I need is to extract the original—none of the tile stuff. And critically, to support really large images which I suspect will cause OpenSlide issues. Thanks.

**Comment by jcupitt** [comment]
I think czi files are tiled: they are the shots from the camera plus some metadata to say how to stitch them together. You'll need to do something like openslide to load them. The openslide codebase is quite nice, it shouldn't be too hard to add. 

I've used openslide on 250,000 x 250,000 pixel images on this modest laptop without any problems, so it should be able to cope.

**Comment by jcupitt** [comment]
Oh, and my university has annoyingly gone for the Zeiss as well, so a czi module for openslide would be great for me too!

**Comment by harukizaemon** [comment]
Awesome. Sounds good. Yeah many of our university and corporate clients are ditching pretty much everything else in favour of CZI.

**Comment by bgilbert** [comment]
@harukizaemon OpenSlide maintainer here.  We'd be happy to accept a CZI driver.  Please note, however, the caveat in https://github.com/openslide/openslide/issues/144#issuecomment-75203404.  The discussion in https://github.com/openslide/openslide/issues/214 may also be relevant.
