### ISSUE TITLE
Get aspect ratio

### ISSUE THREAD

**Issue by svnpenn** [jcupitt/libvips#652]
I see that VIPS can get width and height pretty simple:

~~~sh
$ vipsheader -f Xsize example.jpg
1000

$ vipsheader -f Ysize example.jpg
563
~~~

but can it get aspect ratio? ImageMagick can do this:

~~~sh
$ identify -format '%[fx:w/h]' example.jpg
1.7762
~~~

**Comment by jcupitt** [comment]
Hi, you'd need to do that in some scripting language. For example:

```bash
#!/bin/bash

width=$(vipsheader -f width $1)
height=$(vipsheader -f height $1)
aspect=$(bc -l <<< "$width / $height")

echo "aspect = $aspect"
```

Python / Ruby / PHP / nip2 / javascript etc etc would all work well too.

**Comment by ui4j** [comment]
Today is sunday, you should rest instead of answering issues :)

**Comment by jcupitt** [comment]
Hehe, perhaps I will play Mario Kart instead.

**Comment by svnpenn** [comment]
@jcupitt I was afraid you would say that. I was interested in this project, but I will not be using it because it requires 2 calls to the binary instead of 1. Thanks for your help

**Comment by jcupitt** [comment]
It's only one in Python, for example:

```python
image = Vips.Image.new_from_file(sys.argv[1])
aspect = image.width / image.height
```

But of course it's up to you. I'll close.
