### ISSUE TITLE
How to tiffsave in python?

### ISSUE THREAD

**Issue by tumagonx** [jcupitt/libvips#654]
OS: Windows 10 64bit
Python: 3.4 64-bit
Vips : 8.4.5 64-bit

I want use TIFF tile_width, compression, pyramid, and Q property but it seems Vips.tiffsave is not introspectable (in my Vips.gir).
I can do this in commandline though.

**Comment by jcupitt** [comment]
Hello, you can just use `.write_to_file()`, for example:

```python
im.write_to_file("something.tif", Q = 95, compression = "jpg", tile = True, pyramid = True, tile_width = 512)
```

I'm not sure why `.tiffsave()` isn't working for you.

**Comment by tumagonx** [comment]
Thanks I didn't try .tiffsave before, I misunderstood the method. 
both .write_to_file and .tiffsave works the same
