### ISSUE TITLE
Raise tile-width/height limit in tiff writer to 32768

### ISSUE THREAD

**Issue by tumagonx** [jcupitt/libvips#655]
I have so wide image which well exceed JPEG limit, therefor use tile-width in TIFF. However through trials with tiffcp I found that bigger width make encoding much faster. In VIPS width is limited to 1024, but I don't seems get restriction on tiffcp, I could use for example 12480.
An image of 162244 x 1200 (tile-width = 1024) need more than 1 minute spent on encoding alone, where tiffcp take 34 seconds.

Any reason about it? I do remember 512 or 1024 are common for geotiff.

**Comment by tumagonx** [comment]
The code is here

```
import os
import sys

import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

Vips.progress_set(True)

images = []
for filename in os.listdir(os.getcwd() ):
    images.append(Vips.Image.new_from_file(os.path.join(os.getcwd(), filename),
                                           access = Vips.Access.SEQUENTIAL))

images.reverse()
strip = Vips.Image.new_memory()
strip = Vips.Image.copy_memory(images[0])
images.pop(0)

for i in images:
    strip = strip.join( i, "horizontal", shim = 6, expand = 1)
#bigtiff = True; make tiff not readable by WIC
strip.tiffsave("strip.tiff", compression = "jpeg", Q = 30, tile = True, tile_width = 1024)
```

**Comment by jcupitt** [comment]
Yes, I think the vips limit is just to stop crazy values, we could change it. I'll do some tests.

**Comment by jcupitt** [comment]
You can make your program slightly simpler. This should work just as well:

```python
strip = images[0]
for i in images[1:]:
    strip = strip.join(i, "horizontal", shim = 6, expand = 1)
```

I tried different values for `tile_width` but it didn't seem to make much difference. I made a directory containing 1,000 copies of a 1450 x 2400 jpg image:

```
$ mkdir x
$ cd x
$ for i in {1..1000}; do cp ~/pics/k2.jpg $i.jpg; done
```

Then with `tile_width = 512` I see:

```
...
strip.py temp-9993: 1455994 x 2048 pixels, 4 threads, 128 x 128 tiles, 128 lines in buffer
strip.py temp-9993: done in 96.6s          
real	1m39.927s
user	5m15.152s
sys	0m5.780s
```

with 1024 it's 1m43s, with 128 it's 1m40s.

**Comment by jcupitt** [comment]
I tried your program with just 100 images to get an output size closer to what you are using:

```
strip.py temp-993: 145594 x 2048 pixels, 4 threads, 128 x 128 tiles, 128 lines in buffer
strip.py temp-993: done in 3.39s          
real	0m3.746s
user	0m7.460s
sys	0m0.612s
```

With `tile_width = 128` it's under 4s on this old laptop. I'm surprised you are seeing times over a minute, could something else be slowing you down?

**Comment by tumagonx** [comment]
Thanks for the simplified code!

can you test using tiffcp? I start to wonder if this libjpeg issue (I use mozjpeg 3.1 to squeeze more bytes).
using this it never finished (I still waiting...)
tiffcp -c jpeg:30 -w 128 strip.tiff strip2.tiff

using this, done in 70 seconds:
tiffcp -c jpeg:30 -w 1024 strip.tiff strip2.tiff

using this, done in 34 seconds:
tiffcp -c jpeg:30 -w 10480 strip.tiff strip2.tiff

**Comment by jcupitt** [comment]
How is `strip.tiff` written? Is it a tiled jpeg? What is the tile size?

**Comment by jcupitt** [comment]
With the `strip.tiff` from the last test (145594 x 2048 pixels, 128 x 128 pixel tiles, jpg compression) I see:

```
$ time tiffcp -c jpeg:30 -w 128 strip.tiff strip2.tiff
real	0m4.533s
user	0m4.360s
sys	0m0.168s
$ time tiffcp -c jpeg:30 -w 1024 strip.tiff strip2.tiff
real	0m4.188s
user	0m4.080s
sys	0m0.108s
$ time tiffcp -c jpeg:30 -w 10480 strip.tiff strip2.tiff
real	0m4.146s
user	0m4.036s
sys	0m0.108s
```

So not a huge difference.

I'm using libjpeg-turbo, the standard SIMD one. mozjpeg is very slow :(

**Comment by tumagonx** [comment]
Sorry for the delay...
Yep confirmed: http://www.libjpeg-turbo.org/About/Mozjpeg 
Guess I have no choice with the tradeoff, will you still consider raise the tile size limit? say half of jpeg size limit: 32768? when I try that in vips the whole process completed in 26 seconds (with even smaller file size)

**Comment by jcupitt** [comment]
OK, bumped to 32768 in master. Thanks!
