### ISSUE TITLE
add porter-duff compositing operator

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#657]
Add `vips_composite()`, something to blend a stack of images with alphas and compositing operators.

This is mostly done in ruby or whatever at the moment. It would be good to put all these implementation into the libvips core. We could make it a bit quicker and reduce maintenance by having it in one place. sharp, photoflow and nip2 would be possible users. 

Any potential users, please feel free to add notes about your requirements.

References:

Ruby implementation https://github.com/jcupitt/ruby-vips/issues/28

In C https://gist.githubusercontent.com/jcupitt/abacc012e2991f332e8b/raw/0a7ffba90c7b954661184c0caf393e94b921b4fd/composite2.c

http://en.wikipedia.org/wiki/Alpha_compositing

https://github.com/lovell/sharp/blob/master/src/operations.cc#L92

Notes:

* input is an array of N images and N-1 blending modes
* images are transformed to a compositing space (scRGB? XYZ? it should probably be an optional param)
* opaque alphas are added to any images missing them
* the first image with no alpha is the background, the images before that in the input array are composited on top according to their blending mode
* the output has no alpha if any of the inputs has no alpha
* the output is in compositing space
* check colourspace.c ... it should only detach and reattach alpha if it is changing the space
* use orc for the blend
* think about alpha convention: should it be the final channel, or the one just after RGB? we need to allow many alphas
* need to support RGBA and GA, add CMYKA later, perhaps
* assume everything has been premultiplied, --- applications are responsible for calling `vips_premultiply()` on the inputs and `vips_unpremultiply()` on the output as appropriate

**Comment by lovell** [comment]
Hi John, this is excellent news! A couple of initial questions spring to mind:

* Will this assume/verify images have the same dimensions, or will a per-image `top, left` position be an optional param?
* Will (un)premultiplication be required/optional before and after? Perhaps each vips image could have a flag/hint for its current premultiplication state?

**Comment by jcupitt** [comment]
Hi Lovell, thanks for responding!

1. My feeling was that extract/compose/insert would be just as fast, so there's no need to build an offset into a `composite` operator, it can just concentrate on a quick merge.
2. Yes, I'm not sure. I thought perhaps try without a has-been-premultiplied flag and add it later as a performance tweak if necessary. 

I suppose I didn't mention CMYKA, though I imagine this is of very limited interest.

**Comment by lovell** [comment]
Images needing to be of the same dimensions works for sharp.

I have a slight preference for (un)premultiplication to occur outside this operation, at least for the base image and final output, if only because sharp is already doing this.

Perhaps add CMYKA support later if/when someone asks for it :)

**Comment by jcupitt** [comment]
You're right, it should assume everything has been premultiplied, otherwise what's the point of having a separate `vips_premultiply()` operator. We can add automatic premultiplication later if we add a flag. I'll update the notes at the top.

**Comment by jcupitt** [comment]
@aferrero2707, can I ping you? What would this need to be useful to photoflow?

**Comment by mhirsch** [comment]
What's the status of this feature? I would find it very useful in vips! I've been using the C code posted above.

**Comment by jcupitt** [comment]
Sorry, no progress, the summer has been spent fixing up the language bindings. We should get 8.6 out, so this will probably have to slip to 8.7.

**Comment by aferrero2707** [comment]
Sorry for answering so late!

The image blending in PhotoFlow is rather complex (not sure if it can be called Porter-Duff compositing...), and does most of what you describe, but limited to two input images.
Shortly speaking, a native VIPS implementation should at least:

* support most of the "standard" blend modes. The list of those implemented in PhF can be found [here](https://github.com/aferrero2707/PhotoFlow/blob/stable/src/base/pftypes.hh#L89)
* blend two images into a single output one. I do not have a need for blending three or more images
* take a third grayscale image as an optional parameter, and use its contents as the alpha channel if present
* handling of different colorspaces: if the two images are not in the same colorspace, do an ICC conversion of the foreground image to the background colorspace BEFORE the actual blending
* if larger, crop the foreground image to the size of the background one. If the foreground image is smaller, allow to specify an offset from the top-left corner for embedding the foreground onto the background

I thinks that's all. If something else comes to my mind I will post it here.

**Comment by jcupitt** [comment]
There's a branch here with an experimental `composite` operator:

https://github.com/jcupitt/libvips/tree/add-composite

It only does OVER, and it's not especially quick. I'll tinker with it a bit.

**Comment by jcupitt** [comment]
Thank you all for the feedback! The experimental implementation tries to incorporate what everyone has said:

* It has an array of input images. The first one will come out at the top, the last at the bottom. You can use it with just two images in the stack, of course.
* It assumes images are not premultiplied. This lets it work directly on PNG images on the command-line. You can set the `premultiplied` flag to indicate that the source images have already been premultiplied.
* Images are transformed to a compositing space before processing. This is `sRGB` or `B_W` by default, depending on how many bands the input images have. You can pick any other space, like `LAB` or `scRGB`.
* Images which are smaller than the maximum in the array are padded up with zeros at the bottom and right. If you want a different gravity, there's a new `vips_gravity()` operator you can use on that input.
* If you want to blend with a mask, you can set that as the alpha of the top image. 
* Images with missing alphas become solid and mark the bottom of the stack.
* CMYK is not supported (since it needs an ICC profile transform), though it would be simple to add.

**Comment by aferrero2707** [comment]
That's very interesting! I cannot promise to test this very quickly, but I definitely will give it a try as soon as I can.

> Images are transformed to a compositing space before processing

How can you do that without an ICC profile conversion? I would leave it up to the user to make sure that the images are in the same colorspace, as this is a really tricky aspect to handle. In particular, choosing a small-gamut colorspace as sRGB is in my opinion not a good choice. In unbounded mode, out-of-gamut sRGB colors are likely to have at least one channel which is negative, and this might create problems when using multiplicative blend modes...

**Comment by jcupitt** [comment]
It just uses `colourspace`, so XYZ, for example, might be good for linear, wide-gamut compositing.

It could use `icc_import`, but as you say that can be tricky, since profiles can be in error or rendering intents might need tweaking.

**Comment by aferrero2707** [comment]
Sorry for insisting on this, but how do you compute the ```XYZ``` values without an ICC conversion?

**Comment by jcupitt** [comment]
libvips assumes RGB images are sRGB, so it just uses the standard sRGB -> XYZ formula. If you have something else, yes, you'll need to import with an ICC profile. 

The compositing space is a parameter, so the user can pick whatever they like.

**Comment by mhirsch** [comment]
That's fantastic! Thank you.

**Comment by jcupitt** [comment]
It now does the 11 separable PDF blend modes too. The cairo docs have a nice summary:

https://www.cairographics.org/operators/

MULTIPLY onwards.

**Comment by jcupitt** [comment]
OK, done and merged to master. That was very painful :( It has a vector path too! It supports all the separable PDF blend modes as well as regular Porter-Duff, so SCREEN, COLOUR_DODGE and so on. The Cairo docs have a nice list of all the modes:

https://www.cairographics.org/operators/

It's about 2x faster than ImageMagick:

```
john@mm-jcupitt5 /data/john/pics $ time convert -compose over -composite wtc.jpg wtc_overlay.png x.jpg
real	0m4.512s
user	0m8.260s
sys	0m0.152s
john@mm-jcupitt5 /data/john/pics $ time vips composite "wtc_overlay.png wtc.jpg" x.jpg 2
real	0m2.115s
user	0m6.304s
sys	0m0.108s
```

I'll add some menu items to nip2 and some tests to pyvips. If anyone tests it and finds a problem, please open a new issue.

**Comment by jcupitt** [comment]
There's a new C++ convenience method to composite two images:

```
VImage VImage::composite( VImage other, VipsBlendMode mode, VOption *options );
```

Or you can composite many images by passing arrays. 

nip2 has a new Composite menu item, under Image / Alpha. Handy for testing!
