### ISSUE TITLE
lua-wrapper

### ISSUE THREAD

**Issue by lexusburn** [jcupitt/libvips#658]
Hello,

would like to use vips in lua scripts to resizeand combine images.

Found only a lua-wrapper that isn't working and and a unfinished ffi-version that only loads/saves images, but not modify them. On trying to use vips_insert i always get a SIGCHLD. :(

Would be great to get a lua wrapper or someone who can help me to get the ffi-version working.

Best regards
Frederic

**Comment by jcupitt** [comment]
Hi @lexusburn, sure, I like Lua (though all I've done is a couple of pico8 games), a binding for libvips would be fun.

The php binding might be the simplest model. It's 1500 lines of C which implements a few basic functions, then the rest of the binding is a pure PHP layer on top of that. If you use lua-ffi, I guess you could do the whole thing in Lua. 

https://github.com/jcupitt/php-vips-ext

`vips.c` has the C source in.

**Comment by jcupitt** [comment]
... if you have a `lua-vips-ffi` repository, I could have a quick look, if you like.

**Comment by lexusburn** [comment]
i uploaded my stuff here: https://github.com/lexusburn/lua-vips-ffi

It's at the moment only work in progress: it's a simple docker container with all stuff and if you call localhost/vips/foo.png you can see that it loads two images and tries to combine them.

**Comment by jcupitt** [comment]
Hi, got it working here and I see a crash too. The FFI stuff is nice, I didn't realize lua had that all integrated, it's rather slick!

The problem is with the way `vips_insert()` is being called. Here's a tiny C program to show how the API works:

```C
/* compile with
 * 	gcc -g -Wall insert.c `pkg-config vips --cflags --libs`
 */

#include <stdio.h>
#include <stdlib.h>

#include <vips/vips.h>

int
main( int argc, char **argv )
{
	VipsImage *big;
	VipsImage *small;
	VipsImage *out;

	if( VIPS_INIT( argv[0] ) )
		vips_error_exit( NULL );

	// this makes vips track references and print a leak summary on exit
	vips_leak_set( TRUE ); 

	// big will have one ref on success
	if( !(big = vips_image_new_from_file( argv[1], NULL )) ) {
		// vips keeps error messages in a global log ... print and
		// clear the log to get an error summary to that point
		printf( "error: %s\n", vips_error_buffer() ); 
		vips_error_clear();
		exit( 1 );
	}

	// small will have one ref
	if( !(small = vips_image_new_from_file( argv[2], NULL )) ) {
		// ... so drop the big ref
		g_object_unref( big ); 
		printf( "error: %s\n", vips_error_buffer() ); 
		vips_error_clear();
		exit( 1 );
	}

	// this will create a new image and return a pointer to it via &out
	// with a single reference
	if( vips_insert( big, small, &out, 100, 100, NULL ) ) {
		g_object_unref( big ); 
		g_object_unref( small ); 
		printf( "error: %s\n", vips_error_buffer() ); 
		vips_error_clear();
		exit( 1 );
	}

	// the new image will hold references to its inputs, so we can drop
	// the ones we hold
	g_object_unref( big ); 
	g_object_unref( small ); 

	if( vips_image_write_to_file( out, argv[3], NULL ) ) {
		g_object_unref( out ); 
		printf( "error: %s\n", vips_error_buffer() ); 
		vips_error_clear();
		exit( 1 );
	}

	g_object_unref( out ); 

	return( 0 );
}
```

libvips operations all make new images, they don't modify existing images. 

The C API is supposed to be convenient for C programmers, it's not very binding-friendly. It makes heavy use of varargs, for example, which will be awkward.

I would use the lower-level GObject API. It's more verbose, but simple to bind to. I'll make you an example (or you can look at that PHP binding in the meantime).

**Comment by lexusburn** [comment]
Hi John,

thank you for the example.

I will have a look on the GObject API/ PHP API tomorrow morning. 

Best regards
Frederic

**Comment by jcupitt** [comment]
I made a connector for GValue:

https://github.com/jcupitt/lua-vips-ffi/blob/john-experiment/experiment/gvalue_connector.lua

It seems to work. I'll try using that to create vips objects and pass them parameters.

**Comment by jcupitt** [comment]
We now have a lua-vips repo and it more or less works:

https://github.com/jcupitt/lua-vips

There's an issue for tracking the progress to 1.0:

https://github.com/jcupitt/lua-vips/issues/1

**Comment by jcupitt** [comment]
(sorry Frederick, I had to delete and remake the lua-vips-ffi repo to get issues turned on)

**Comment by lexusburn** [comment]
No problem!

Glad to see that it’s now an official repo.
I’m still on the buffer methods. 

Best
Frederic
