### ISSUE TITLE
Question: JPEGCOLORMODE set to RGB only when Quality < 90?

### ISSUE THREAD

**Issue by beaudet** [jcupitt/libvips#660]
Greetings, there's some code around line 1745 in foreign/vips2tiff.c that seems to set the JPEG output color mode to RGB only in cases where the quality is < 90.  What's the rationale behind that check as opposed to say, setting RGB as the mode regardless of the JPEG quality in use?

                        if( !write->rgbjpeg &&
                                write->jpqual < 90 )
                        {
                                TIFFSetField( out,
                                        TIFFTAG_JPEGCOLORMODE,
                                                JPEGCOLORMODE_RGB );
                        }

Thanks!

**Comment by jcupitt** [comment]
Hi again, that's the standard way to disable chroma subsampling for jpeg-in-tiff. Imagemagick has the same logic: >= Q90, no subsample.

**Comment by beaudet** [comment]
Ok, thanks, so just to clarify, if the original TIFF is already in RGB space, this setting won't have any effect, right?  It's only used in cases where YCbCr is the original TIFF space?

**Comment by jcupitt** [comment]
It's a pseudo-tag, not a real one. It's a hint to the jpeg encoder that it can do chroma subsampling on this image.

**Comment by beaudet** [comment]
So chroma subsampling might be performed by the JPEG encoder regardless of the original color space if this hint is set?

**Comment by jcupitt** [comment]
Yes, if the hint is set, the jpeg encoder will assume RGB colourspace, transform the image to YCbCr, subsample, and write. On decode, readers set the RGB hint and the jpeg decoder will transform the YCbCr back to RGB again. 

If you don't set the hint, it will write as YYY, and you'll get much larger files.

**Comment by beaudet** [comment]
Thanks John.
