### ISSUE TITLE
Building for Python 3.x on Ubuntu (and CentOS 6)

### ISSUE THREAD

**Issue by benhoyt** [jcupitt/libvips#661]
We're currently using ImageMagick in Python (via wand) to resize images in a real-time image scaling server, but I'd like to switch to libvips for the core crop+resize part -- in my early tests it's 2-3x as fast and produces smaller JPEG files. Awesome!

I'm able to build the command line version (vips and vipsthumbnail), but I'm having trouble getting the Python bindings built and working.

Our dev VM and production environments run on CentOS 6.5 with a build of Python 3.5, so that's what we want to actually build it for. However, I was having trouble getting it working on CentOS, so was trying on the latest version of Ubuntu just as a reference point -- Ubuntu desktop 17.04.

Ubuntu has a nice package `libvips-dev` that just works (I also installed `libvips-tools`). That gave me the command line tools `vips` and `vipsthumbnail`. And I've installed `gobject-introspection` and `python3-gi` to try to get the Python bindings added. It almost works, but I get this error:

    $ python3
    Python 3.5.3 ...
    >>> from gi.repository import Vips
    Traceback (most recent call last):
      ...
    ImportError: cannot import name Vips, introspection typelib not found

Sure enough, there's no `Vips*.typelib` in either `/usr/lib/girepository-1.0` or `/usr/lib/x86_64-linux-gnu/girepository-1.0`. Is there a package I can install to install the typelib, or do I need to build?

In any case, I tried to download and build, still on Ubuntu, so I downloaded `vips-8.5.5.tar.gz` from the GitHub releases page, uncompressed it, then ran `./configure`, and it all looks good, but it says this about gobject introspection and the Python bindings:

    gobject introspection:                  no
    build vips7 Python binding:             yes
    install vips8 Python overrides:         no
      (requires pygobject-3.13.0 or later)

So even though we have `gobject-introspection` installed according to `apt`, it says "no" for both the gobject introspection and the vip8 Python overrides (the latter is probably okay, as I can move that over manually). Then `make` and `sudo make install` work, but I assume due to the above, don't give me the Python bindings either.

As for CentOS 6.5, that was much more problematic. I needed to install a lot of packages and their dependencies and build from source, and got stuck building glib2 because "The system-supplied PCRE does not support Unicode properties or UTF-8." (even though I built pcre with those enabled). 

I'm going to try some more things on the CentOS front, but I'm wondering if you have any suggestions re Ubuntu. (I'm also kind of wondering if I'd be able to copy the binaries from my Ubuntu build to CentOS ... though that might be a terrible idea.)

**Comment by jcupitt** [comment]
Hello @benhoyt, for ubuntu you need the `gir1.2-vips-8.0` package to get the typelib.

To build, you need `gobject-introspection`, `python-gi-dev`, and `libgirepository1.0-dev`. There are some notes in the README.

You're right, CentOS will be harder. Try configuring glib with `--with-pcre=internal` to use the pcre that is shipped with glib.
`

**Comment by benhoyt** [comment]
Excellent, thank you! Mind if I update https://github.com/jcupitt/libvips/wiki/Build-for-Ubuntu with that info? That was one of the places I was looking and it didn't mention the gir-vips or python-gi-dev or libgirepository libs.

Trying the `--with-pcre=internal` thing on CentOS now (configure works at least!).

With all these libraries, compilation flags, etc., are there some good documents I can read for a way into "building stuff on Linux for noobs", or is it just a matter of getting more familiar with all the moving pieces? (I've learned a little about pkg-config.)

**Comment by jcupitt** [comment]
Sure, edit away. I'd put in a link to the README, that's probably the most-maintained place.

https://github.com/jcupitt/libvips/blob/master/README.md

With linux your choices are using the packages that came with your distribution, or learning enough that you can make them yourself, which can mean becoming at least a minor-level developer. CentOS is great, but it's very, very cautious, and if you want anything written in the last five years, you will end up compiling yourself. And of course you can easily find yourself chasing down dependency after dependency trying to get something to work. 

Your other obvious options on the server are Ubuntu and Debian. Debian stable is like centos: very cautious, but also very safe, well-understood, documented and reliable. Ubuntu chooses to sail closer to the wind and might be more appropriate if you need recent features.

**Comment by benhoyt** [comment]
Thanks for the pointers! Still having trouble with CentOS "vips" compilation saying it doesn't see `gobject introspection`, but I'm going to close this issue and play with that some more another day.

**Comment by jcupitt** [comment]
You won't be able to simply copy binaries from ubuntu to centos, by the way :-(

**Comment by benhoyt** [comment]
FYI, I updated python-gi-dev libgirepository1.0-dev with the additional packages needed, especially for using the Python bindings.

**Comment by jcupitt** [comment]
OK, thanks Ben!
