### ISSUE TITLE
Opening slide: Inconsistent main image resolutions

### ISSUE THREAD

**Issue by bender22** [jcupitt/libvips#662]
Hi John,
I'm processing [.scn slide](https://1drv.ms/u/s!AhuHvLqvJ4rHiCcK4Swm_9QEsxwO) and getting error from openslide2vips: 'opening slide: Inconsistent main image resolutions'. Apparently, this is a standard openslide implimentation [1](http://openslide.org/formats/leica) [2](https://github.com/openslide/openslide/blob/master/src/openslide-vendor-leica.c#L676). However, I'm able to view the slide in [this](http://free.pathomation.com) piece of software. 
Is there any way to ignore this inconsistency of macro and main images when using vips (for example skip the macro)? 
Don't you know other libs to deal with .scn?
Thanks in advance

**Comment by jcupitt** [comment]
Hi @bender22, looking at the openslide2vips sources, the error comes from the initial slide open:

https://github.com/jcupitt/libvips/blob/master/libvips/foreign/openslide2vips.c#L279

So I don't think there's much vips can do except report it.

I would open an issue on openslide:

https://github.com/openslide/openslide/issues

Benjamin is very responsive, I'm sure he'd be interested to see an scn file that openslide couldn't open.

**Comment by bender22** [comment]
I don't think it's a bug, because they are saying about this problem on the first page of http://openslide.org/formats/leica:
'the images in a collection cannot be rendered into a unified pyramid without scaling the original pixel data. OpenSlide does not attempt to do this. Instead, OpenSlide omits the macro image from the pyramid and refuses to open slides whose main images have inconsistent resolutions.'
I just can't find other libs which can read this. Ok, I'll try to ask Benjamin. Thanks
