### ISSUE TITLE
Question: Is there a method like imagemagick jpeg:extent

### ISSUE THREAD

**Issue by rbruhn** [jcupitt/libvips#663]
In ImageMagick there is an option to limit the size of the file
```
setOption('jpeg:extent', '600kb');
```
Is there something similar in libvips? I'm looking for a way to convert a directory of images ranging from 5-6MB each to 600Kb while keeping the same dimensions.

**Comment by jcupitt** [comment]
Hello, sorry, no, you'd need to try to compress repeatedly, adjusting the Q each time.

I would use `vips_jpegsave_buffer()` (one of the outputs is the size of the compressed object) then do a binary search.

http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-jpegsave-buffer
