### ISSUE TITLE
Segmentation fault when resizing image bigger than VIPS_DISK_THRESHOLD

### ISSUE THREAD

**Issue by jaume-pinyol** [jcupitt/libvips#666]
Hi,

I think I've found some kind of segfault when resizing big images bigger than VIPS_DISK_THRESHOLD. The case is that depending on which packages are installed it works or not.

In here I've made a test to show what's going on [this tests](https://github.com/jaume-pinyol/libvips/tree/TEST_SEG_FAULT/failing-test). I've added more info in the README file on how to reproduce it, plus a docker container with the packages that are making it fail.

The test try to resize a 21000 x 14400 resolution to a 6k width image but it fails with a segmentation fault.
Depending on the packages installed it works or not, also it is worth to say that I've tried with version *8.4.5*, *8.4.6* and *8.5.5* and I have the same issue in all the them.

From what I've figured out it is related to having a large file in disk, the resize is more than 100mb so vips uses disk to transform the image (I have enough space on disk). If I increase the VIPS_DISK_THRESHOLD to fit in memory then it works fine.

I've traced the segfault to this line [vips.c line 608](https://github.com/jcupitt/libvips/blob/84270ce787f4d19859f1ceab8d8a9801a865a06a/libvips/iofuncs/vips.c#L608)

If I enable debug mode when compiling libvips then when running the test there is an error in [type.c line 1409](https://github.com/jcupitt/libvips/blob/84270ce787f4d19859f1ceab8d8a9801a865a06a/libvips/iofuncs/type.c#L1409)
```
VIPS:ERROR:type.c:1409:vips_value_set_save_string: assertion failed: (G_VALUE_TYPE( value ) == VIPS_TYPE_SAVE_STRING)
```
Do you think it's something wrong with the code or I have something badly configured.
I compile it with
```
CFLAGS="-g -Wall" CXXFLAGS="-g -Wall" ./configure --enable-debug --disable-docs --disable-static --disable-introspection --disable-dependency-tracking --enable-cxx=yes --without-python --without-orc --without-fftw  --prefix="/usr"
 
```
 I'll try to figure out something more tomorrow.

If you need more info do not hesitate, thank you very much!

Best Regards,
Jaume

**Comment by jcupitt** [comment]
How strange, I'll see if I can reproduce it here. Thanks for the very comprehensive bug report.

**Comment by jcupitt** [comment]
OK, I think I've fixed it, thank you very much for the report Jaume. There were two problems: you image had a 2.7MB ICC profile, and the thing that packs binary data into save strings had a 1MB sanity limit. I've raised that to 10MB.

The second problem was that the error fallback from failed binary string encode set the wrong type (it was a copy-paste error), setting the wrong type failed, and that potentially left a dangling pointer.

The fix is in the 8.5 branch and master. Could you try building from 8.5 HEAD and see if it fixes it?

**Comment by jaume-pinyol** [comment]
I'm gonna try it now ;)

**Comment by jcupitt** [comment]
I tried timing your program here. For your version I see:

```
$ time ./a.out ~/pics/twin-peaks.jpeg 
real	0m6.906s
user	0m8.076s
sys	0m0.600s
peak mem 330MB
```

If I change access to SEQUENTIAL, libvips can overlap jpeg encode and decode, and can avoid a temporary file. libvips also has a handy thing to load a file as a string, so you avoid the copy on load. If I change it to be:

```C++
        size_t length;
        char *buffer;
        if( !(buffer = vips__file_read_name(argv[1], NULL, &length)) )
                vips_error_exit( NULL );

        VImage out = VImage::new_from_buffer(buffer, length, "", VImage::option()->
                 set("access", VIPS_ACCESS_SEQUENTIAL) ->
                 set("shrink", scale));
```

I see:

```
real	0m5.767s
user	0m7.016s
sys	0m0.148
peak mem 260MB
```

Which is a bit quicker.

I tried `thumbnail_buffer` as well, but it was over a minute. It tries hard to avoid aliasing and so can't use shrink-on-load as much, plus lanczos3 is more expensive than bilinear.

**Comment by jaume-pinyol** [comment]
Hi,

I've tried and it solves the issue 👍 

I'll do some test with what you are proposing. 

The case is that transforming big images is kind of a weird case, most of the images have widths between 1000 and 5000. Would you still recommend using VIPS_ACCESS_SEQUENTIAL rather than VIPS_ACCESS_RANDOM?

Thanks for the feedback! 

Best Regards,
Jaume Pinyol

**Comment by jcupitt** [comment]
Oh, certainly, there's no downside to SEQUENTIAL if you are just resizing images. If you want to rotate as well, you'll need to go via a memory buffer, but that's a simple thing to do.

I would look at `thumbnail_buffer`. The quality is much better, and the speed penalty may be acceptable, depending on your needs. You'd need to do some tests.
