### ISSUE TITLE
Does vipsprofile work with python3?

### ISSUE THREAD

**Issue by ioquatix** [jcupitt/libvips#667]
We currently have this patch in the arch linux package:

```
  # fix vipsprofile
  sed -i 's|^#!.*python$|&2|' "$pkgdir/usr/bin/vipsprofile"
```

That's because `vipsprofile` 

```
#!/usr/bin/python

import re
import math
import cairo

class ReadFile:
    def __init__(self, filename):
        self.filename = filename

```

These days, `python` could be either 2 or 3 depending on the system. So - is that okay? Does it work with either python2 or python3?

**Comment by jcupitt** [comment]
You're right, it's py2 only (the Ubuntu default). I've changed it to be explicitly python2. Thanks!

**Comment by jcupitt** [comment]
... if you have any other general patches, I'd be very happy to incorporate them, of course.

**Comment by ioquatix** [comment]
That's the only one we had. Will this be part of 8.6.0?

**Comment by jcupitt** [comment]
Yes, and 8.5.6. That's waiting on someone running some tests and confirming a fix, I should probably chase them.

**Comment by hroncok** [comment]
See also https://github.com/libvips/libvips/pull/1262
