### ISSUE TITLE
How to combine bands with scaling (for example for rgb to bw conversions)

### ISSUE THREAD

**Issue by rikh42** [jcupitt/libvips#669]
For example, say I have an RGB image. I want to generate a single band image using the following calculations...

`output = (Red * 0.3) + (Green * 0.59) + (Blue * 0.11);`

Where I want to be able to pass in the values of the 3 constants there. 
At the moment I am splitting up the bands from my  sRGB image int 3 separate images (one per band), performing the multiply in each band, then adding them all together to get my final 1 band image.

Is there a function to do this more efficiently already?

**Comment by jcupitt** [comment]
Hi, yes, you want `recomb` (recombine):

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-recomb

For your example, you would do (in Ruby):

```ruby
image = image.recomb [0.3, 0.59, 0.11]
```

You can also just change the colourspace, so:

```ruby
image = image.colourspace "b_w"
```

For an sRGB source that'll do (under the hood) sRGB -> scRGB (linear sRGB), then combine bands with the ratios you quote to get linear greyscale, then do linear greyscale -> sRGB gamma greyscale. Use `GREY16` for 16-bit output.

**Comment by jcupitt** [comment]
Oh, the `colourspace` operator knows about alpha, so it'll work for PNG as well.

**Comment by rikh42** [comment]
Awesome - `recomb` was indeed the thing I'm looking for. I was aware of the B&W colourspace conversion, but am actually trying to do goofy filtered stuff and wanted more control over the input parameters.

**Comment by rikh42** [comment]
The other thing I'm struggling to figure out is how to find the min and max of an rgb colour.

so, if I have a 3 band rgb image, I want to create a 1 band image where each pixel contains the min of r, g or b for the input image. Same again for the max value of r, g and b.

**Comment by jcupitt** [comment]
You need `bandrank`:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-bandrank

It's an image-wise rank filter. Split your input RGB image into three one band images, then call bandrank twice. In Ruby:

```ruby
mins = Vips::Image.bandrank image.bandsplit, index: 0
maxes = Vips::Image.bandrank image.bandsplit, index: image.bands - 1
```
