### ISSUE TITLE
Trim (auto crop) - native, is planed?

### ISSUE THREAD

**Issue by uasan** [jcupitt/libvips#670]
Hello.

I've seen how to do it myself, but usually this function is inside the library.
http://libvips.blogspot.co.uk/2014/02/trim-auto-crop-with-ruby-vips.html

You do not plan to implement in `libvips`?

It would be very good, thank.

**Comment by jcupitt** [comment]
Hello, we could do I guess. There's smartcrop in there now, so an autotrim doesn't seem like a huge stretch.

**Comment by uasan** [comment]
It was very good, thank!

**Comment by kleisauke** [comment]
I would also like to see that this feature is included in libvips. Also, it would be nice that this was implemented in the `vipsthumbnail` operator (it should occur before any resize operation and users should be able to define a `trim percentage`).

Hopefully this operator is possible without breaking sequential mode. I'm not sure if copying the image to a memory buffer (before trimming) fixes this.

**Comment by jcupitt** [comment]
Hello, this is in 8.6 as `find_trim`, pre-release here:

https://github.com/jcupitt/libvips/releases/tag/v8.6.0-alpha1

**Comment by uasan** [comment]
Thank!
Where can I read the documentation for function `vips_find_trim()`?

Here, not found - `vips_find_trim()`
http://jcupitt.github.io/libvips/API/current/api-index-full.html

**Comment by uasan** [comment]
Found, in the comments :)
https://github.com/jcupitt/libvips/blob/9c1af2289c802edb42306a722abad148b7dc5a84/libvips/arithmetic/find_trim.c#L230

Thank.

**Comment by jcupitt** [comment]
Yes, build from source with `--enable-gtk-doc` and it'll install docs for you. The on-line ones are for 8.5, the current supported version.

**Comment by kleisauke** [comment]
It seems that `find_trim` is a more aggressive trim then the [auto-trim with vips8 python](https://gist.github.com/jcupitt/eecd6d24692c388799e5) (using the same threshold).

I've made a testcase in PHP to demonstrate this issue, see: https://gist.github.com/kleisauke/4da55c946bc9ec3bdd44e2a1ad428f85

Test image:
https://raw.githubusercontent.com/lovell/sharp/master/test/fixtures/alpha-layer-1-fill.png

`find_trim` threshold 10:
![imagetrim1](https://user-images.githubusercontent.com/12746591/28823956-405b6070-76c0-11e7-8550-c61c9078476a.png)

Original auto-trim threshold 10:
![imagetrim2](https://user-images.githubusercontent.com/12746591/28823979-58dbde7c-76c0-11e7-840b-9cb8d842184e.png)

By the way,
Is there a reason why we can't use `getpoint` directly for the `background` option? If I do this I'll get this error: `linear: vector must have 1 or 3 elements`. I fixed this by slicing the `getpoint` array by 0 to `bands - 1` (see [here](https://gist.github.com/kleisauke/4da55c946bc9ec3bdd44e2a1ad428f85#file-trim-php-L23-L26)), but this seems to be a bit strange.

**Comment by kleisauke** [comment]
@jcupitt Sorry for pinging you, but did you see the above post? If you want, I could make a [pyvips](https://github.com/jcupitt/pyvips) code example as well (to demonstrate this issue).

(sharp's internal trim operation is also going to be switched to the `vips_find_trim` operation, so I want to avoid that more users are noticing a "more aggressive trim")

**Comment by jcupitt** [comment]
Ooop, I lost this issue Kleis, I'll reopen.

**Comment by kleisauke** [comment]
I had some time to demonstrate this issue from the command-line. 

<details>
 <summary>Click for details</summary>

[Test image](https://raw.githubusercontent.com/lovell/sharp/master/test/fixtures/alpha-layer-1-fill.png)

**Working (without `vips_getpoint`)**
```bash
trim_area=$(vips find_trim alpha.png --threshold 10 | xargs)
vips crop alpha.png alpha-crop.png $trim_area
```

Output:
[alpha-crop](https://user-images.githubusercontent.com/12746591/30519729-ad8f0118-9b9d-11e7-8401-c3ef4d78defe.png) (expected)

**`vips_getpoint` as background:**
```bash
point=$(vips getpoint alpha.png 0 0)
trim_area=$(vips find_trim alpha.png --threshold 10 --background "$point" | xargs)
vips crop alpha.png alpha-crop2.png $trim_area
```

Output:
```bash
linear: vector must have 1 or 3 elements
extract_area: too few arguments
```

**`0 0 0` as background:**
```bash
trim_area=$(vips find_trim alpha.png --threshold 10 --background "0 0 0" | xargs)
vips crop alpha.png alpha-crop3.png $trim_area
```

Output:
[alpha-crop3](https://user-images.githubusercontent.com/12746591/30519760-3536ae36-9b9e-11e7-8532-e225b3a90983.png) (wrong, too aggressive)
</details>
&nbsp;

Summary:
Once I define the `--background`  option directly with `vips_getpoint`, I'll get errors. When I define it with `0 0 0` (slicing the  `vips_getpoint` by 0 to `bands - 1`) the crop is too aggressive. 

Note: 
Everything is working fine without defining the `--background` option, so the background option is the culprit here.

**Comment by jcupitt** [comment]
I agree Kleis, this behaviour should be improved. I'll try to look at this later today.

**Comment by jcupitt** [comment]
Ooof, there was a missing `bandor`. It's working better now -- I see:

```
john@kiwi:~/pics$ vips find_trim alpha-layer-1-fill.png 
204
0
1758
1256
john@kiwi:~/pics$ vips find_trim alpha-layer-1-fill.png --background 0
204
0
1758
1256
```

Nice find Kleis!

**Comment by jcupitt** [comment]
Regarding 3 vs. 4 bands, it flattens out alpha before searching for edges (or it would see junk left in transparent areas), so you need to give 3 bands for the background value. 

I agree, this is tricky, I'm not sure what the best solution is. It would be much better if you could just `getpoint()` on the top-left corner and pass that value.

Perhaps we should note in the docs that you should flatten before getpoint if you want to find a background value?

**Comment by jcupitt** [comment]
Added a note to docs on flatten.

**Comment by kleisauke** [comment]
It seems to work for PNG with transparency now (calling `flatten()` before `getpoint()` fixes this). Unfortunately a regular JPEG appears to be broken (tested with https://github.com/jcupitt/libvips/commit/0d93f9f9dd1996a74e318b90765c8f061ec8746c):

[Test image](https://raw.githubusercontent.com/lovell/sharp/master/test/fixtures/alpha-layer-2-ink.jpg) (2048x1536 uchar, 3 bands, srgb, jpegload)

```bash
vips find_trim alpha-layer-2-ink.jpg --threshold 10 --background "0 0 0"
```

Output:
```
linear: vector must have 1 or 2 elements
```

Calling it with `--background "0 0"` fixes this, but seems rather confusing. I agree, it would be much better if you could just pass the `getpoint()` as background value. 

In the past, I did use `premultiply()` (if the image has an alpha channel)  to remove the extraneous crap in the transparent areas. Perhaps we should add a note in the docs that the operation expects a premultiplied image? As a disadvantage, it may not be good for performance (I think `flatten()` should be faster).

By the way,
_"A faster alternative for trimming images with an alpha channel would be to just test the final channel for non-zero. It's obviously fine to trim away all transparent parts."_ (see: https://github.com/jcupitt/php-vips/issues/36#issuecomment-285863592).
Perhaps we should choose a different path for images with transparency?

**Comment by jcupitt** [comment]
Oh dear, flatten always removes the last channel, it doesn't check for alpha first. Try again, it seems to work now.

I'll add a test for this.

**Comment by kleisauke** [comment]
OK, everything seems to be good now! 👍

**Comment by jcupitt** [comment]
Phew! I'll close.

**Comment by jcupitt** [comment]
And thanks very much for flagging up all the issues, it was great.

**Comment by sergeevabc** [comment]
Dear @jcupitt,
I am looking for a way to crop the following image as follows.
Trim seems to be the key, but I'm not sure how to get it right with `vipsthumbnail`.

* [Original](https://github.com/libvips/libvips/assets/373718/8204e539-9e49-44b6-959c-477fb83ad795)
* [Current smartcrop](https://github.com/libvips/libvips/assets/373718/c36d2d3d-5b2c-4cab-b1e7-a2cc6bb7425d) via `--smartcrop entropy -s 600x100`
* [Expected smartcrop](https://wsrv.nl/?url=https://pic.maxiol.com/images2/1705634494.774319425.conceptmap.png&w=600&&height=100&trim=100&fit=cover&a=entropy) via third-party service with additional trim set to 100

**Comment by jcupitt** [comment]
Hi @sergeevabc, please open a new discussion rather than adding to a closed issue.
