### ISSUE TITLE
tweak smartcrop

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#672]
From https://github.com/lovell/sharp/issues/832

Some more sample images from @puzrin :

https://www.flickr.com/photos/136807076@N07/24161551991/
https://www.flickr.com/photos/136807076@N07/24161549231/

Running 8.5 `vipsthumbnail` like this:

```
$ vipsthumbnail -s 128 --smartcrop attention bunny.jpg cat.jpg
```

Gives:

![tn_bunny](https://user-images.githubusercontent.com/580843/26871655-d9604626-4b6b-11e7-8f0e-94d05d908b75.jpg)
![tn_cat](https://user-images.githubusercontent.com/580843/26871659-dda31ff6-4b6b-11e7-92b3-471e0b2b52b1.jpg)

Obviously the ideal would be to centre the animals.

**Comment by uasan** [comment]
Yes, I noticed that I often prefer the left side, even if this photo is rotated horizontally, cropped to left side.

**Comment by jcupitt** [comment]
It seems to be the skin detector, as @kleisauke said in the linked issue. The libvips one is a rather brutal 255/0 if a pixel falls into the skin box; the smartcrop.js one gives each pixel a 0 - 1 score based on skinniness.

**Comment by uasan** [comment]
It is more correct to look for the eyes and nose, instead of the skin color, so does the human visual brain.

**Comment by jcupitt** [comment]
Here's a branch with a revised smartcrop:

https://github.com/jcupitt/libvips/tree/tweak-smartcrop

Running like this:

```
vipsthumbnail --smartcrop attention *.jpg
```

Produces this:

![output](https://user-images.githubusercontent.com/580843/26942298-707e9838-4c79-11e7-954b-ca6723654d75.png)

Images plus a nip2 workspace that implements the new smartcrop:

http://www.rollthepotato.net/~john/smartcrop/

**Comment by jcupitt** [comment]
I meant to say, this is a patch to the 8.6 branch, but perhaps this should go into 8.5.

**Comment by puzrin** [comment]
Looks nice.

I have no specific testing stategy, just check on live site from time to time. Would be good to push into 8.5 for fast `sharp` update.

**Comment by jcupitt** [comment]
Here's a branch based on 8.5

https://github.com/jcupitt/libvips/tree/tweak-smartcrop-8.5

**Comment by rnanwani** [comment]
Is this merged with 8.5.x or will it go live with 8.6?

**Comment by jcupitt** [comment]
It hasn't been merged yet, I should get around to it.

**Comment by jcupitt** [comment]
OK, merged to 8.5, this improvement will be in 8.5.7, out in the next week or so.

**Comment by uasan** [comment]
Unexpected result :)
`vipsthumbnail -s 300x200 --smartcrop attention in.jpg -o out.jpg`
IN
![IN](https://lh3.googleusercontent.com/ewTNKYPA_q2FAAIGbwp185Fg0WqCoar4FtGLzV4m9SuoiEXoqCLwoHm4KYDBxHLWuQsWMwg4dWOPzIjTHjxKEBYipsWi4eCNN0CR=w1280-h1024-rw-no)

OUT
![OUT](https://lh3.googleusercontent.com/YqZWryMC7GKWQOZo4Osma1er4si87FtD_LmnUOZvfU31y4v3M8e1u1oJpy9mVD1O022HzwRK3Ms9aOvgONQaOEWGeYzap55_udh8=w1280-h1024-rw-no)

Is this normal behavior, or am I doing something wrong?

```
vips --version
vips-8.6.0-Sat Jul 29 13:02:38 GMT 2017
```

**Comment by jcupitt** [comment]
It looks for brightly-coloured areas with edges and skin, so it thinks the top of the screen looks great.

You can try out smartcrop.js here:

https://29a.ch/sandbox/2014/smartcrop/examples/testbed.html

You'll find it makes the same wrong choice, unfortunately.

**Comment by rnanwani** [comment]
A case that changed from 8.5.6 to 8.5.7 and for the worse in my opinion

Command
```
vipsthumbnail --smartcrop attention image.jpg
```

Original
![image](https://user-images.githubusercontent.com/4739557/29455710-d9dc2fd2-842f-11e7-8557-ccec37c65af3.png)


With 8.5.6
![image](https://user-images.githubusercontent.com/4739557/29455718-e1db7710-842f-11e7-9b0b-18c00eb639a7.png)


With 8.5.7
![image](https://user-images.githubusercontent.com/4739557/29455728-ecde0984-842f-11e7-888d-de97c488c869.png)


Any particular change in the last release that could have caused this?

Also, another case where smartcrop fails
![image](https://user-images.githubusercontent.com/4739557/29455829-501b3396-8430-11e7-9728-046c24640f3a.png)

Output
![image](https://user-images.githubusercontent.com/4739557/29455846-652a1e32-8430-11e7-940c-c8cbcdbbe5e2.png)
