### ISSUE TITLE
Install libvips for python3.6 - Issue with gobject-introspection, python-gi-dev

### ISSUE THREAD

**Issue by vishnuprasadh** [jcupitt/libvips#674]
Guys,
I have downloaded the vips tar file and did run ./configure, make & sudo make install on my mac. I see vips running properly from my terminal when i hit vips -v which gives me the output.

One of the callout in the support for python suggests the following.

> If gobject-introspection, python-gi-dev, and libgirepository1.0-dev are available, libvips will install the vips8 Python binding.

I did run the following because not sure if the above can be downloaded & compiled or ???

pip install pgi --> but this keeps crashing. So, how do i install the above bindings and associate into my python3 libs ?

Also if i were to use virtualenv would this work or ? Any help would be deeply appreciated.

**Comment by jcupitt** [comment]
Hello, on a mac you can just install with `brew install vips`, you don't need to build it yourself.

**Comment by vishnuprasadh** [comment]
Thanks for the response. I did that. Post that, I had to run the following since bindings were on Py2.7. 

```
mkdir` -p /Users/vph/.local/lib/python3.6/site-packages
  echo` 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/vph/.local/lib/python3.6/site-packages/homebrew.pth
```

I did that too but the python3 is failing with exception when i do import from gi. Hence ventured into compilation and installation. 

Any options ? Iam running 3.6.1

**Comment by jcupitt** [comment]
I'm glad py2 is working. 

I tried py3 here. I ran:

```
# I have some py2 stuff in my pythonpath
unset PYTHONPATH
brew install python3
brew install pygobject3 --with-python3
brew install vips
```

And I can now run:

```
$ python3
Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Vips', '8.0')
>>> import gi.repository.Vips
>>> 
```

**Comment by vishnuprasadh** [comment]
Is there no other way for me to run this with python3 ? I have not run brew install have installed anaconda python3 running in a bin. When ever i try to run brew, obviously it asks for brew link python3 to be executed which is a issue ...

what options I got ? Pls let me know ...

**Comment by jcupitt** [comment]
Sure, you can install it in any way you like, `brew` is just a simple and automated way to do it.

There are vips packages in MacPorts and Fink as well, I don't know if one of them would integrate with anaconda more simply.

**Comment by vishnuprasadh** [comment]
one more thing, i found...import gi.repository works in python2...but import gi.repository.Vips through cannot import name Vips though vips command returns version number.

**Comment by jcupitt** [comment]
Sorry, I made a mistake, it should be:

```
from gi.repository import Vips
```

**Comment by jcupitt** [comment]
Sorry, one more thing, you must copy the overrides file into the python3.6 lib, it's not done by default.

```
cp /usr/local/lib/python2.7/site-packages/gi/overrides/Vips.py /usr/local/lib/python3.6/site-packages/gi/overrides/
```

Now I see:

```
 $ python3
Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Vips', '8.0')
>>> from gi.repository import Vips
>>> x = Vips.Image.new_from_file("/Users/john/pics/k2.jpg")
>>> x.width
1450
```

**Comment by vishnuprasadh** [comment]
Unfortunately i cant find vips.py anywhere...been very painful until now to get this installed :-)

**Comment by jcupitt** [comment]
Just search the `/usr/local/` area:

```
$ cd /usr/local/
$ find . -name Vips.py
/usr/local/lib/python2.7/site-packages/gi/overrides/Vips.py
/usr/local/Homebrew/Cellar/vips ...
```

You are using `brew` to build vips, aren't you? 

If you want to build vips yourself, you'll need to make sure you also build all of the machinery for introspection. There are three or four other packages you need, have a look at the README.

**Comment by jcupitt** [comment]
I'll see if I can get the homebrew formula to do more of this for you.

**Comment by jcupitt** [comment]
I had a look at Anaconda (I don't use it myself) and they have their own package manager. You'll need to ask them to make a vips package for you. 

You should apparently open an issue here:

https://github.com/ContinuumIO/anaconda-issues/issues

According to:

https://docs.continuum.io/anaconda/pkg-docs

**Comment by vishnuprasadh** [comment]
Thanks a ton @jcupitt for trying options. 

Dont know what i even used port but vips file is not getting into my system :-( ...strangely!

I am currently using Pillow-SIMD for image resize dynamically through mod_wsgi python program routed through apache server. One of the biggest issues i see is that the process is highly CPU intensive and needs very high # of cores. I am looking to dynamically resize and output images to the order of 600-700 TPS from webserver. Currently, i see per core its about 10TPS with <350ms and 70%CPU. If I were able to quickly use vips, nothing like it. Based on performance you have given, could save 5-10X cores hence was trying hard to integrate with vips. I will keep trying ....

Does vips support lanzos, bicubic models and do you have any viewpoint on performance vs imagequality(for resize - downscale/upscale) here ?

**Comment by jcupitt** [comment]
I guess you are not deploying on macOS though, right? Is this AWS?

vips is lanczos3 by default, but there are quite a few to choose from.

I would just use the `thumbnail` operator, it's the thing used by most of the on-demand image resizing proxys, it's high-quality, quick, and doesn't need much memory.

The libvips node binding is used a lot for image proxies:

http://sharp.dimens.io/en/stable/performance/

It's about 30 ops/s per core. If you need 700 op/s, I suppose that would be 5 - 10 large instances.

**Comment by vishnuprasadh** [comment]
Thanks @jcupitt. I will review how to integrate this. However not sure how when I hit vips it works while vips.py is missing.

**Comment by jcupitt** [comment]
This issue is tracking anaconda installation: https://github.com/jcupitt/libvips/issues/673
