### ISSUE TITLE
High memory usage when using vips

### ISSUE THREAD

**Issue by alonit** [jcupitt/libvips#677]
Hi,

I have been using vips to create pyramid and get very high memory usage in my system:

First, the scanner saves its RGB images to disk by using OpenCV `imwrite `as tiff format with LZW compression.
Each image have 2356x1772 pixels, 8 bit per channel, 24 bit per pixel, where image data is organized in pixel order (not planner), so every image have 12MB of data.

Those images are then processed by vips as the following stages:
1. Loading: the tiff images are loaded from disk by calling `vips_image_new_from_file(fileName, VIPS_ACCESS_RANDOM)` . After this call, the process memory use does not change.
2. Stitch: the images are then stitched by calling functions such as `vips_deviate`, `vips_mosaic`, and `vips_insert `on each image, so that the process memory use is increased with about 12MB per image in this stage.
3. Pyramid: the pyramid is built out of the stitched image and saved on disk by calling to `vips_dzsave`(...). This increase process memory use with additional several Gigs - I guess that these Gigs are because vips executes the actual pipeline computed earlier in stage 2 (stitch) + pyramidal required memory that scales to image_width x tile_hight x byte_per_pixel.

Example using tiff file format:
 40x40=1600 tile images:
1. Loading: no additional memory use.
2. Stitch: ~12GB
3. Pyramid: ~16GB

...............

I tried to convert the scanner images to vip format, and save them back to disk, and check the memory behavior - when I process them with vips, the memory behavior is change as follows:

Example using vips file format:
 40x40=1600 tile images:
1. Loading: no additional memory use.
2. Stitch: no additional memory use.
3. Pyramid: ~5.5GB

I tried to realize the memory usage for the stitcher pipeline and the memory usage of the pyramid building, and it turns out that from the total 5.5GB, the stitcher vips pipeline consumes 4.7GB and the pyramid building consume 0.7GB - I done this by first save the stitched image to disk as vips format. Than, just load the stitched (vips format) image from disk and dzsave it.

(pyramid tile height is 1024, so 40 x 2100 x 1024 x 3 = 246MB = 0.24GB, so it is not clear why dzsave actually consumes 0.7GB of memory)

I also tried to convert the .tiff files to jpg using vips and the memory was high as with tiff format files.

I'm using Vips 8.5.0 C API on Windows 64bit OS, 32GB RAM.

Given the above, what can cause my tiff files to be handled inefficiently by vips, leading to a very high and sometimes out of memory status?

your kind support would be highly appreciated

Thanks

**Comment by jcupitt** [comment]
Hi, when you open an image as `RANDOM`, vips has to make sure the image supports random access. In the case of strip TIFFs, it will need to unpack somewhere first, since strip TIFF does not allow random access. If the unpacked image is under 100MB, then vips will unpack to memory, so as you say, high memory use. 

If you know the exact position of all of your images, you don't need `RANDOM`, you can just open all of your images as `SEQUENTIAL` and libvips will stream them with no unpacking. This should save a lot of memory. 

If you need to do some analysis to find the positions, then you do need `RANDOM` (I expect?) since you will be searching the overlap areas. In this case, try setting the environment variable `VIPS_DISC_THRESHOLD` to something like `10m` (10 megabytes). This will make vips keep temporary files for the unpacked objects, which (again) should save some memory.

**Comment by alonit** [comment]
Thanks for your quick reply.

Why the vips format images that are loaded also with RANDOM does not consume large memory up until calling `dzsave` ?

**Comment by alonit** [comment]
Can I first convert my tiff files to vips format in memory at run-time and use the converted vips format in the Stitcher and Pyramid stages to save memory?

Thanks

**Comment by jcupitt** [comment]
vips format supports random access directly from the file, so no conversion is necessary. TIFF format can only be read from top to bottom. 

The unpacked objects are just huge arrays. 

The tiffs are (in effect) converted to vips format in memory during load.

**Comment by alonit** [comment]
For 400 tiff tiles:

1. Using VIPS_ACCESS_RANDOM, memory usage is very high, and it take 2 minutes to get pyramid.
2 using VIPS_DISC_THRESHOLD with 10mb, the memory usage was very low, but it takes 4.5 minutes to get pyramid
3. using VIPS_ACCESS_SEQUENTIAL, (no VIPS_DISC_THRESHOLD), memory usage is very low, but it takes 7 minutes to get pyramid

**Comment by jcupitt** [comment]
So you have an analysis phase where you use `mosaic` to find offsets, then a separate merge and pyramid phase? Yes, you'll need RANDOM for the first, but you can use SEQ for the second. 

Why do you turn concurrency to 1? Do higher values help much?

**Comment by alonit** [comment]
Set the `concurrency `to 2 with `VIPS_ACCESS_RANDOM `and `VIPS_DISC_THRESHOLD `help to save time (about 3 minutes less) and memory (about 7 Gigs less) running on 6 cores cpu for a grid of 23x32. Set the `concurrency `to 3 or 4 doesn't give additional performance gain.

Now, I am facing a new problem: I have 50x50 images, for each one vips open temporary file as a result of using the `VIPS_DISC_THRESHOLD`, but it seams that the program is limited by the number of files that can be opened simultaneously. I call `_setmaxstdio `to 2048 - max on Windows 7 64bit, and vips fail with error `unable to make temporary file C:\Users\asi\AppData\Local\Temp\vips-2046-CSUV2Y.v` when opening the 2045 temp file (Vips temp folder contain 2045 file when this error raised). Is there a way to work around this limit and use the major memory saving offered by using VIPS_DISC_THRESHOLD without this maxstdio limit?

Thanks

**Comment by jcupitt** [comment]
Sorry, 2048 is a hard Windows limit, you just can't go higher (I think). 

You could install a linux VM and do the work there, or maybe tile your image in sections.

**Comment by alonit** [comment]
Thanks for your suggestions.

I'm trying to force `vips_image_new_from_file` to load the first 2045 tiles of the grid via disk in order to save memory all the way to the pyramid. First, I removed the VIPS_DISC_THRESHOLD and TMPDIR from windows environment variables, and then set `vips_image_new_from_file` `disc` parameter to `TRUE`, yet it doesn't works as no vips-tmp-file is created on windows temp directory.

The code is look like the following:

```
vips_image_new_from_file(name, 
		"access", VIPS_ACCESS_RANDOM,
		"disc", TRUE,
		NULL);
```
Did I missed something?

Thanks again for your kind support

**Comment by alonit** [comment]
I found vips operate as follows:
1. I set `VIPS_DISC_THRESHOLD `to `10m`, my images are 12mb uncompressed
2. When call `vips_image_new_from_file` with `disc `parameter equal `FALSE `, the file loaded via temp file on disc
3. When Call `vips_image_new_from_file` with `disc `parameter equal `TRUE`, the file loaded to memory, no temp file

It seems that it is just the opposite than `vips_image_new_from_file ` official documentation:
`Set disc to TRUE to force loading via disc. `

When set VIPS_DISC_THRESHOLD greater than 12m, and `disc` value TRUE or FALSE the load does not forced via disk.

Your help is highly appreciated

Thanks

**Comment by jcupitt** [comment]
You're right, the docs are incorrect. `disc` defaults to TRUE, meaning large files are loaded via disc. Setting FALSE forces all files to be loaded to memory. 

It should probably be called `memory` and default FALSE. I'll tag it as deprecated and add a new `memory` flag for 8.6.

**Comment by jcupitt** [comment]
I think we've moved the discussion to the newer issue, I'll close this one. Thanks for pointing out the `disc` dumbness.

**Comment by zarlior** [comment]
Hi,
I saw you use the _setmaxstdio to 2048 on vips_init.

I there any chance you can make the 2048 a parameter?
I tested a standalone application on my Win 7 and it can go up to 8192.
I ran the following code from [https://msdn.microsoft.com/en-us/library/xt874334.aspx](url)
with 8192 and the output was 8192.
I also tried to load 8189 files simultaneously and it worked (it has to be 8192-3 because of stdin\stdout\stderr).

Also, I would be more than happy to test it if you could compile a test version for me...

Thanks,
Lior.
