### ISSUE TITLE
vips installation on CentOS6.9 does not detect gobject-introspection or openslide

### ISSUE THREAD

**Issue by valkaben** [jcupitt/libvips#678]
Hello,  

I've recently installed libvips from source file but during the run of ./configure, my install of vips does not detect my gobject-introspection and openslide libraries.  

Here, the below lines show that I have these files in my library directories.  
```
# ls /usr/local/lib | grep openslide
libopenslide.la
libopenslide.so
libopenslide.so.0
libopenslide.so.0.4.1
// I also have a symlink in /usr/local/lib for gobject-introspection that links to below directory 
# ls /usr/lib64/gobject-introspection/giscanner/
annotationparser.py   dumper.py      glibast.pyo          minixpath.pyo      sourcescanner.pyo
annotationparser.pyc  dumper.pyc     glibtransformer.py   odict.py           transformer.py
annotationparser.pyo  dumper.pyo     glibtransformer.pyc  odict.pyc          transformer.pyc
ast.py                girparser.py   glibtransformer.pyo  odict.pyo          transformer.pyo
ast.pyc               girparser.pyc  __init__.py          scannermain.py     utils.py
ast.pyo               girparser.pyo  __init__.pyc         scannermain.pyc    utils.pyc
cachestore.py         girwriter.py   __init__.pyo         scannermain.pyo    utils.pyo
cachestore.pyc        girwriter.pyc  libtoolimporter.py   shlibs.py          xmlwriter.py
cachestore.pyo        girwriter.pyo  libtoolimporter.pyc  shlibs.pyc         xmlwriter.pyc
config.py             _giscanner.so  libtoolimporter.pyo  shlibs.pyo         xmlwriter.pyo
config.pyc            glibast.py     minixpath.py         sourcescanner.py
config.pyo            glibast.pyc    minixpath.pyc        sourcescanner.pyc
```
When, I run ./configure on vips-8.5.5, it shows the following lines regarding the relevant libraries:
```
checking for OPENSLIDE... no
configure: OpenSlide >= 3.4.0 not found; checking for >= 3.3.0
checking for OPENSLIDE... no
configure: WARNING: OpenSlide >= 3.3.0 not found; disabling virtual slide support
...
checking for gobject-introspection... no
```
I downloaded gobject-introspection through the nux.dextop repo: 
```
# yum list gobject-introspection-devel
Installed Packages
gobject-introspection-devel.x86_64                      0.9.3-1.el6.nux                       @nux-dextop
```
I got openslide from here https://github.com/openslide/openslide/archive/v3.4.1.tar.gz.  

Do you know what could possibly cause this?

**Comment by evadne** [comment]
Wild guess but does ldconfig help?

**Comment by valkaben** [comment]
Sadly not, I've run ldconfig after every installation of the software but it hasn't changed the status message at the end.  

I have solved the openslide issue but I'm still having trouble with the gobject-introspection.  It seems I had to configure my PKG_CONFIG_PATH manually with:

`export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig`

Yet, I'm left with the gobject-introspection issue.  I believe I need a version of gobject-introspection that is over 1.30 but my yum install only provided me with 0.9.3.  I've tried to install a more recent version but it requests a version of glib2-devel that I can't get yet with centos 6.9 from just a repo.  I'm looking into maaaybe alternatively installing an up-to-date glib2-devel somehow.

**Comment by jcupitt** [comment]
Hello, you may not need gobject-introspection. It's needed by the Ruby and Python bindings, but obviously if you're not using them, you're OK without it. C, C++, shell, PHP, node, Go etc etc should all work fine. 

If you do need it, yes, you're going to have to build quite a few packages. I would build to a prefix in my home directory and then set environment variables to make processes I wanted to use the new stuff see that first.
