### ISSUE TITLE
Issue with Bintray hosting

### ISSUE THREAD

**Issue by priyadarshy** [jcupitt/libvips#679]
It seems like the 8.3.1 Linux Version is no longer working on Bintray.

https://bintray.com/lovell/sharp/download_file?file_path=libvips-8.3.1-lin.tar.gz

**Comment by lovell** [comment]
Hello, this will be due to a temporary networking problem between you and Bintray/Akamai. Watch http://status.bintray.com/ for possible announcements.

**Comment by lovell** [comment]
I've reopened https://github.com/lovell/sharp/issues/841 as this is causing a lot of problems for people right now.

**Comment by jcupitt** [comment]
I'll close, this doesn't seem to be a libvips problem (for once).
