### ISSUE TITLE
Question: hist_equal output 

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#680]
Is it expected that `hist_equal` will "optimise" the storage of the output such that if the resulting values fit in a smaller data type, it will use that instead?

For context, I'm have some `ushort` + `grey16` images that after running `hist_equal` have values that fit in a  `uchar`.

**Comment by jcupitt** [comment]
Hi, that's strange, `hist_equal` shouldn't change the numeric range much.

I tried here:

```
$ vipsheader shrunk.v 
shrunk.v: 1009x799 ushort, 1 band, grey16, tiffload
$ vips max shrunk.v 
63000.000000
$ vips min shrunk.v 
2000.000000
$ vips hist_equal shrunk.v x.v
$ vipsheader x.v 
x.v: 1009x799 ushort, 1 band, grey16, tiffload
$ vips max x.v 
63001.000000
$ vips min x.v 
2138.000000
```

Could something else be causing the truncation?

**Comment by harukizaemon** [comment]
Heres are the files: [512x512x1-U16.zip](https://github.com/jcupitt/libvips/files/1084013/512x512x1-U16.zip)

**Comment by harukizaemon** [comment]
To be fair the original has issues (the byte order is wrong), but we do get these kinds of images from time to time (as RAW files) and they do process them through the system and whilst the output might be nonsense (although in this case it did a fine job) the downcast from `ushort` to `uchar` surprised me if nothing else.

**Comment by jcupitt** [comment]
Oh, that surprises me a little too. Looking at it, it's `hist_norm` (histogram normalisation) that's doing it:

```
$ vips hist_find 512x512x1-U16.tiff x.v
$ vipsheader x.v
x.v: 247x1 uint, 1 band, histogram, tiffload
$ vips hist_norm x.v y.v
$ vipsheader y.v
y.v: 247x1 uchar, 1 band, histogram, tiffload
```

So I think I'd say: odd, but correct.

**Comment by harukizaemon** [comment]
Ahh. Yes. I've seen `hist_norm` up the upscale (e.g. to `uint`) and given it's being used in `hist_equal` that now makes sense that it could potentially go either way?

Unfortunately, the downstream system expects the data type to remain unchanged, so I may need to re-think my strategy for using it 🤔

In the case of downcast, I presume I can expand the type relatively simply (e.g. by adding a band and then re-interpreting?).

In the case of an upcast, I'm not quite sure what I'll do.

**Comment by jcupitt** [comment]
You can just add a cast, so:

```ruby
def equalize(in)
    in.hist_equal.cast(in.format)
end
```

I think you're right, this is too unexpected, I've added the cast to git master libvips too.

**Comment by harukizaemon** [comment]
Perfect! Thank you. Have added that to my code. Should turn out to be a no-op if you decide to make that change permanent anyway so in the meantime it's a great workaround. Thank you as always!
