### ISSUE TITLE
In Memory Processing

### ISSUE THREAD

**Issue by bubba-h57** [jcupitt/libvips#681]
I have a desire to implement a memory only pipeline for processing PDF Pages -> IMG. Initially, I only need to handle single page PDFs. They will contain a single page with anything from a letter sized page to a large format blueprint, the large format will make up about 95% of all the conversions.

I can not use any disk space at all, nor an OS  implemented ramdisk or tmpfs or any mounts at all for that matter, but I have more than enough RAM to do everything I want to do. The high-level pipeline would look like:

1. Download PDF to Blob from URL
2. Load PDF into _(libvips, poppler, libgs, ?)_
3. Convert PDF to some reasonable image format. _(Generic Ghostscript command line for this would look like_ `gs -dNOPAUSE -q -dBATCH -o"out.png" -dFirstPage=1 -dLastPage=1 -sDEVICE=png256 -r300x300  in.pdf` _although I hope to tweak that such that for black & white blueprints I can get a much smaller file size but still have good support for full-color blueprints/graphics. I would also like to come up with a process to resize these large format images to something that is still big enough to allow zooming in and seeing all the detail w/out being so massive.)_
4. Upload resulting image to URL

Ultimately I desired to do this in PHP _(because that is what everyone else on the team writes in)_ and I tried using the [imagick](https://github.com/mkoppanen/imagick) PHP extension. However, the 
underlying [ImageMagick](https://github.com/ImageMagick/ImageMagick) library always writes a PDF Blob to a temp file prior to passing it off to gslib.

Here is some sample code of what I was trying in PHP:
```php
$data = file_get_contents($uri); //560MB Single Page PDF
$image = new Imagick();
$image->readImageBlob($data);

$colorCount = $image->getImageColors();

 //Reduce the image to 256 colours nicely.
if ($colorCount > 256) {
     $this->info('Reduce the colors nicely.');
     $image->quantizeImage(256, \Imagick::COLORSPACE_RGB, 0, false, false);
} else {
     $image->setColorspace(\Imagick::COLORSPACE_RGB);
}
$image->setImageDepth(8);
$image->setImageFormat('png8');
$this->info('Writing Image: ' . $outputPath);
$image->writeImage($outputPath);
```

Here are the relevant calls:
[imagick](https://github.com/mkoppanen/imagick/blob/3acc635fe321bde7e2154f0cd01e6aa7d970bc3f/imagick_class.c#L3840)->[magick-wand](https://github.com/ImageMagick/ImageMagick/blob/f19d414d0ac4527544fef324969aa2a5d38b1027/MagickWand/magick-image.c#L8248) -> [magic-core](https://github.com/ImageMagick/ImageMagick/blob/3e69675df13c81e9acee2a532b1b31f947985271/MagickCore/blob.c#L434)

So I could successfully load the blob in memory via PHP, pass it off to imagick, and not matter what else I do, it always writes a temp cache and then finishes the process with nother disk activity.

I would prefer to do this in a scripting language like PHP, Python, Nodejs _(in order of personal preference)_ although I am not opposed to doing it in C#, Go, Java, or C++ _(in order of personal preference)._ 

I know this seems to go against the vips paradigm of _'use as little memory as possible'_ but I am really hopeful that I can find a way to do this entirely within libvips. I spent most of the day yesterday trying to solve this challenge and came up empty. It seemed wise to ask you experts for advice before I go any further.

**Comment by evadne** [comment]
I had a similar use case and ended up using Poppler + GDK-Pixbuf directly and handle each page separately, partially due to how VIPS (to my understanding) prints a “toilet roll” of images which can cause thumbnails to have different scale factors should the pages in the underlying PDF have different widths.

One thing about PDFs is that sub-resources are often referenced and the pages and resources (images, fonts, etc.) can be interleaved in the file in any order (see: PDF Linearisation or Fast Web View), so it is good to know that you have more than enough memory. :)

**Comment by jcupitt** [comment]
Hi, you can use `php-vips`, I think it'll do what you need. It uses poppler behind the scenes, so it's quick and there are no temporary files. Something like:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Jcupitt\Vips;

$buffer = file_get_contents($uri);
$image = Vips\Image::newFromBuffer($buffer, ['page' => 12, 'dpi' => 144]);
$pngfile = $image->writeToBuffer('.png');
```

Do you need a Windows host? I've not done a win version, though it should work. You'll find you'll need to fix the build system for the extension. On Linux and mac, it's just `pecl install vips` and off you go.

@evadne, you're right, for multi-page output you need to have all the pages the same size. If you are just pulling out single pages from a document, it's OK, they'll come out to the same scale.

**Comment by jcupitt** [comment]
Ooops wrong button.

**Comment by bubba-h57** [comment]
I will give it a shot! No windows here. I just need to compile the `php-vips-ext` and get it all setup. as for the extension, what is actually the latest version or perhaps, which do you recommend? https://github.com/jcupitt/php-vips-ext/releases seems to indicate 1.0.2 is the latest release, but I notice that you have a v1.0.5 tagged release, and the repo itself contains a vips-1.0.7.tgz

I will get the ext compiled this afternoon and run some tests. I really hope it is just as easy as this!

**Comment by jcupitt** [comment]
Just enter `pecl install vips` and it'll download, configure, compile and install the latest version for you automatically. Then add vips to your composer file and you're done. 

API docs here:

https://jcupitt.github.io/php-vips/docs/classes/Jcupitt.Vips.Image.html

**Comment by bubba-h57** [comment]
pecl isn't going to work for my environment. I will just grab a pretty version.

**Comment by bubba-h57** [comment]
Well, I got it working and it works much better. The latest release of [libvips-lambda](https://github.com/stechstudio/libvips-lambda/releases/tag/v1.2.0) allows building PHP _(and the ultimately the vips extension)_ against the same libraries as `libvips.`

`$image = \Jcupitt\Vips\Image::newFromBuffer(file_get_contents($s3Uri), '', ['page' => 0, 'dpi' => 300]);`

Successfully slurps in the file from S3 and nothing is being written to disk. I love it!

Using a 550M [singlePagePdf_0.pdf](https://s3.amazonaws.com/rc-testing/single_page_pdf/singlePagePdf_0.pdf) seems to just hang indefinitely though. Here is a simple test using the same S3 files that I am using:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Jcupitt\Vips\Image;

print("Configuring\n");
ini_set('memory_limit', -1);
ini_set('sys_temp_dir', '/tmp');

testVips('https://s3.amazonaws.com/rc-testing/single_page_pdf/singlepage2.pdf');     // 1.2 M PDF
testVips('https://s3.amazonaws.com/rc-testing/single_page_pdf/singlePagePdf_0.pdf'); // 550M PDF

function testVips(string $url)
{
    $start = microtime(true);
    $outputPath = '/tmp/' . basename($url, '.pdf') . '.png';
    @unlink($outputPath);

    print("Loading file from $url\n");
    print("Current Memory Usage: " . humanReadable(memory_get_usage()) . "\n");
    $image = Image::newFromBuffer(file_get_contents($url), '', ['page' => 0, 'dpi' => 300]);
    print("File was Loaded \n");
    
    print("Writing File to $outputPath\n");
    print("Current Memory Usage: " . humanReadable(memory_get_usage()) . "\n");
    $image->writeToFile($outputPath);

    unset($image);
    print('Execution time in : ' . (microtime(true) - $start) . " seconds.\n");
}

function humanReadable($bytes)
{
    $unit = ['B','KB','MB','GB','TB','PB'];
    if ($bytes == 0) {
        return '0 ' . $unit[0];
    }

    return @round($bytes / pow(1000, ($key = floor(log($bytes, 1000)))), 2) .
        ' ' .
        (isset($unit[$key]) ? $unit[$key] : 'B');
}
```

```
>>> php vipstest.php
Configuring


Loading file from https://s3.amazonaws.com/rc-testing/single_page_pdf/singlepage2.pdf
Current Memory Usage: 1.3 MB
File was Loaded 
Writing File to /tmp/singlepage2.png
Current Memory Usage: 1.56 MB
Execution time in : 4.4177839756012 seconds.


Loading file from https://s3.amazonaws.com/rc-testing/single_page_pdf/singlePagePdf_0.pdf
Current Memory Usage: 1.56 MB
```

Watching the process, I can that it grows up to 1G RAM usage. I generate the filename in the `/tmp/ directory, and then it just seems to hang out there fluctuating between 800MB -> 1.2GB of ram usage. I've let it sit for up to 5 minutes with no output.

Any ideas?

**Comment by bubba-h57** [comment]
For what it is worth, Ghostscript and Imagick converts both of these as expected ... it just writes to a temp file.

**Comment by bubba-h57** [comment]
It looks like pdftoppm on the command line can not convert that file at all, so I suspect Poppler just has issues with it. I am running a series of pdfs through a script to measure execution time and output filesizes between the `vips-php-ext` and the `imagik` php extentions. Here are the result of the first 11/80. The script starts with the smallest PDF filesize and then goes up from there.

```
#: 1/80 singlePagePdf_122.pdf   754.62 KB
=========================================
/tmp/vips/singlePagePdf_122.png [5.42 MB]       ran in 185.59 seconds.
/tmp/imgk/singlePagePdf_122.png [956.38 KB]     ran in 18.82 seconds.
=========================================

#: 2/80 singlePagePdf_154.pdf   980.03 KB
=========================================
/tmp/vips/singlePagePdf_154.png [4.04 MB]       ran in 186.74 seconds.
/tmp/imgk/singlePagePdf_154.png [652.49 KB]     ran in 18.76 seconds.
=========================================

#: 3/80 singlePagePdf_67.pdf    1.19 MB
=========================================
/tmp/vips/singlePagePdf_67.png [28.95 MB]       ran in 17.88 seconds.
/tmp/imgk/singlePagePdf_67.png [11.8 MB]        ran in 18.12 seconds.
=========================================

#: 4/80 singlePagePdf_71.pdf    1.23 MB
=========================================
/tmp/vips/singlePagePdf_71.png [27.56 MB]       ran in 18.90 seconds.
/tmp/imgk/singlePagePdf_71.png [11.29 MB]       ran in 18.03 seconds.
=========================================

#: 5/80 singlePagePdf_75.pdf    1.23 MB
=========================================
/tmp/vips/singlePagePdf_75.png [27.37 MB]       ran in 18.46 seconds.
/tmp/imgk/singlePagePdf_75.png [11.25 MB]       ran in 17.90 seconds.
=========================================

#: 6/80 singlePagePdf_48.pdf    1.58 MB
=========================================
/tmp/vips/singlePagePdf_48.png [38.61 MB]       ran in 18.63 seconds.
/tmp/imgk/singlePagePdf_48.png [15.48 MB]       ran in 19.97 seconds.
=========================================

#: 7/80 singlePagePdf_73.pdf    1.94 MB
=========================================
/tmp/vips/singlePagePdf_73.png [45.25 MB]       ran in 22.57 seconds.
/tmp/imgk/singlePagePdf_73.png [18.09 MB]       ran in 19.07 seconds.
=========================================

#: 8/80 singlePagePdf_103.pdf   9.26 MB
=========================================
/tmp/vips/singlePagePdf_103.png [15.54 MB]      ran in 95.89 seconds.
/tmp/imgk/singlePagePdf_103.png [4.45 MB]       ran in 32.44 seconds.
=========================================

#: 9/80 singlePagePdf_95.pdf    10.23 MB
=========================================
/tmp/vips/singlePagePdf_95.png [55.93 MB]       ran in 696.74 seconds.
/tmp/imgk/singlePagePdf_95.png [61.98 MB]       ran in 84.87 seconds.
=========================================

#: 10/80        singlePagePdf_81.pdf    63.88 MB
=========================================
/tmp/vips/singlePagePdf_81.png [5.71 MB]        ran in 644.42 seconds.
/tmp/imgk/singlePagePdf_81.png [1.66 MB]        ran in 53.30 seconds.
=========================================

#: 11/80        singlePagePdf_80.pdf    65.49 MB
=========================================
/tmp/vips/singlePagePdf_80.png [7.8 MB] ran in 666.11 seconds.
/tmp/imgk/singlePagePdf_80.png [2.31 MB]        ran in 55.30 seconds.
=========================================
```
at this rate, it will probably be tomorrow before the other 69 pdf files get tested. ;-)

**Comment by bubba-h57** [comment]
I suppose I simply didn't wait long enough

```
>> time pdftoppm -png -f 1 -singlefile -r 300 singlePagePdf_0.pdf poppler.png
pdftoppm -png -f 1 -singlefile -r 300 singlePagePdf_0.pdf poppler.png  900.98s user 7.28s system 99% cpu 15:13.45 total
```

```
>> time gs -dNOPAUSE -dBATCH -o"test1.png" -dFirstPage=1 -dLastPage=1 -sDEVICE=png256 -r300x300  singlePagePdf_0.pdf
GPL Ghostscript 9.21 (2017-03-16)
Copyright (C) 2017 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
Processing pages 1 through 1.
Page 1
gs -dNOPAUSE -dBATCH -o"test1.png" -dFirstPage=1 -dLastPage=1 -sDEVICE=png256  50.92s user 0.77s system 99% cpu 52.085 total
```

**Comment by jcupitt** [comment]
Hi, it looks like there are a couple of issues here.

First, libvips does progressive rendering of PDFs. It defines a window on the file `tile_height` pixels high (128 by default), renders the whole page, outputs those pixels, and moves the window down. Poppler handles this pretty well: it's good at just drawing the parts that appear in a window. This means you can use libvips to render enormous PDFs, 100,000 x 100,000 pixels is no problem.

Unfortunately in this case, there's a single image in the background, and it'll have to render that huge image for each strip. This makes it appallingly slow:

```
$ time vips copy singlePagePdf_0.pdf vips.tif --vips-progress
vips temp-1: 2124 x 4680 pixels, 4 threads, 2124 x 16 tiles, 128 lines in buffer
vips temp-1: 4% complete
...
```

I changed the libvips PDF loader to render in 5,000 pixel strips (larger than the default size for this image) and it does now complete in a more reasonable time:

```
$ time vips copy singlePagePdf_0.pdf vips.tif
real	1m40.935s
user	1m40.676s
sys	0m0.280s
```

Secondly, `gs` is just a lot quicker than poppler on this file. I tried:

```
$ time gs -o gs.tif -sDEVICE=tiffscaled24 -dDownScaleFactor=8 singlePagePdf_0.pdf
GPL Ghostscript 9.19 (2016-03-23)
Copyright (C) 2016 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
Processing pages 1 through 1.
Page 1
real	0m19.074s
user	0m16.708s
sys	0m0.788s
```

You need the `-sDEVICE=tiffscaled24 -dDownScaleFactor=8` to get anti-aliased output, to match poppler. So that's about 6x faster. 

I'll change libvips to use the larger rendering window.

**Comment by bubba-h57** [comment]
Can this be a setting/option to pass in? Default to the smaller strip, but allow someone like me to pass in an argument for a larger one? 

Currently, if I want to use __GhostScript__  with __vips__ , I can compile __vips__  against __ImageMagick__  instead of __poppler?__  

Historically, I would use command line `gs` to convert to an image, then command line `vips` to convert that into the appropriate tiles _(Zoomify or Google)._ 

In the past, perhaps three or four years ago, I tried command line __popper__  against our clients PDFs and found that it either couldn't process some of them at all _(our clients generate a lot of non standard PDFs)_  or was extremely slow. Ghost Script just seemed tho handle non standard pdfs better.

I suppose I have remained biased since then. However, the move to AWS lambda provides a new set of challenges.

Of the hundreds of thousands of single page PDFs we have, that is the single largest and definitely an outlier. The majority of them are less than 100MB.

I get 1.5G of ram to process with, but only 500M of writeable disk space and no more than 5 minutes of execution time. Thus my need to do all the processing in memory. I can't even download that original PDF to the temp folder, it is too large. But the resulting image file is always small enough to work with given the constraints.

So the single biggest hurdles seems to be the initial conversion from PDF to image. 90% of our PDFs will be exactly like this, one page with a huge blueprint image scanned in. This one just happens to not be a blueprint.

Hopefully that provides a bit more insight to my use case, and I thoroughly appreciate all your advice and time to help, not just today, but of the past six years. 😎 Thank you!

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jcupitt** [comment]
Yes, if you disable poppler and build libvips against imagemagick, vips will use IM for PDFs, and (in turn) IM will use gs. However, IM will call gs via the command-line, and it'll pass intermediates via disk files, so I think that's a no-go for you.

I think you'll have to use poppler. The larger window size is a one-line change, I'd test that and see if it works for you:

https://github.com/jcupitt/libvips/commit/61d5ba7b58af0bbd51ef26fa875713a0014e457b#diff-c8112ec7c4f4ddf9c8ac93894ebfef11L438

**Comment by bubba-h57** [comment]
Here is a summary of my findings in trying to answer the question.

- Vips using Poppler as the PDF Loader does indeed allow for completing the entire job in RAM, if enough RAM is available.
- Vips/Poppler PDF conversion is significantly faster with the larger window size.
- In head to head PDF to Image conversions, Ghostscript command line vs Poppler command line (pdftoppm) showed Ghostscript to be significantly faster in my tests.
- The ImageMagick guys say that ImageMagick can be compiled from source with the `--with-gslib` option set to `true` in order to get ImageMagick to call GS in memory and not use a Temp file.  The only downside of using the GS library instead of the GS Executable is that you can't do it in parallel. The Ghostscript library is not thread-safe, so there is some protection in place that prevents a concurrent call from using the library. That second call will use the executable and create a temp file. So we can use the GS library but we have to make sure we only convert one file at the same time.

Ultimately, I am going to stick with Ghostscript for our initial PDF->Image conversion, then feed the resulting Image into VIPS to complete the tiling process. We have a constraint in Lambda of no more than 512MB of writable disk space. So I will use a pipeline like this:

1. Download Source PDF and write to `/tmp/source.pdf` _(source can not be larger than 512MB)._
2. Use cmd line GS to convert PDF to Image. `$process = new Process("gs -dNOPAUSE -q -dBATCH -sOutputFile=%stdout -dFirstPage=1 -dLastPage=1 -sDEVICE=png256 -r300  /tmp/source.pdf")` This writes the result to STDOUT and I will capture that and save it in memory. The resulting Image is typically a fraction of the size of the source, a 500MB PDF tends to give me approximately a 100MB image.
3. With the resulting image in memory, I delete `/tmp/source.pdf`
4. Write the blob to disk `file_put_contents('/tmp/img.png', $process->getOutput())`. (I tried using `Image::newFromBuffer($process->getOutput())` but I couldn't get it to accept any sort of variable or stream holding the output from the GS Process).
5. `$image = Image::newFromFile('/tmp/img.png');`
6. `rm -rf '/tmp/img.png'`
7. `$image->dzsave('/tmp/zoomified', ['layout' => 'zoomify']);`

So far this seems to be working fine for us and it is fast enough that even processing big files can be done on demand without users getting impatient. Thanks for all your help. I will close the question in a few days if not more conversation pops up about it.

**Comment by jcupitt** [comment]
That all sounds good. I can help a little on two points:

1. The reason IM doesn't use gslib by default is licence compliance. GS is AGPL, so if you link to it, you (probably) become AGPL as well. This means that if you make your code usable over a network, you must open-source everything. 

   http://artifex.com/licensing/

   Shelling out to a separate GS process is probably OK though. 

2. You should be able to get php-vips to load from memory rather than a file. There's an example here:

   https://github.com/jcupitt/php-vips/blob/master/tests/new.php#L65

**Comment by BoLaMN** [comment]
I asked a similar question in the sharp module as I found PDF convert times fairly slow even with changing the tile height and recompiling https://github.com/lovell/sharp/issues/840

I started doing some research and found cairo was the party responsible for the bottleneck which then I stumbled upon the open sources pdfium from google + foxit which from the benchmarks blows poppler out of the water https://github.com/nathanstitt/dc-pdf-raster-test

I was going to investigating using pdfium instead but haven't had time to deep dive into it.

is it at all possible for libvips to integrate pdfium seeing as the open sourced license seems to fit better with the project?

**Comment by jcupitt** [comment]
Oh, interesting, I hadn't seen pdfium. I'll have a look.

**Comment by jcupitt** [comment]
pdfium seems a little immature still. It's not packaged for Debian, so I tried downloading the sources, but their build system is the Chrome one, so it's really complicated, comes with it's own compiler, and only works on certain versions of Ubuntu (not the one I have).

It looks like a great library, so I'm sure in another year or two it'll have been cleaned up and packaged for easy reuse. I'll open an enhancement issue for this.

**Comment by jcupitt** [comment]
Enhancement issue: https://github.com/jcupitt/libvips/issues/689

**Comment by BoLaMN** [comment]
Thanks for taking a look not sure if https://github.com/klokantech/pdfium might help? check the build folder out
