### ISSUE TITLE
How to run vips example program by Visual stdio in windows10?

### ISSUE THREAD

**Issue by zhouzhognwen** [jcupitt/libvips#683]
Hi,I am a fresh man in VIPS,recently I want to run a program by vips API.But I fall to run the examle proaram.I want to know that can I run it by Visual stdio?Thank you for your answer.

**Comment by jcupitt** [comment]
Hello, yes, it should work. Download the Windows development zip from here:

https://github.com/jcupitt/libvips/releases/download/v8.5.6/vips-dev-w64-all-8.5.6.zip

Add the includes and libraries to a project in the usual way, and compile.

**Comment by zhouzhognwen** [comment]
Thank you for your pretty answer.Maybe I should try it again.Sorry for my poor level of English.

**Comment by jcupitt** [comment]
This is how I compile for Windows using mingw:

```
i686-w64-mingw32-gcc \
    -mms-bitfields -march=i686 \
    -I/home/john/GIT/build-win32/7.32/inst/include \
    -I/home/john/GIT/build-win32/7.32/inst/include/glib-2.0 \
    -I/home/john/GIT/build-win32/7.32/inst/lib/glib-2.0/include \
    myprog.c \
    -L/home/john/GIT/build-win32/7.32/inst/lib \
    -lvips -lz -ljpeg -lstdc++ -lxml2 -lfftw3 -lm -lMagickWand -llcms2 \
    -lopenslide -lcfitsio -lpangoft2-1.0 -ltiff -lpng14 -lexif \
    -lMagickCore -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 \
    -lgmodule-2.0 -lgthread-2.0 -lglib-2.0 -lintl \
    -o myprog.exe
```

You will need to change it a bit for MSVC, but perhaps it could help to have the list of libraries you need.

**Comment by jcupitt** [comment]
I added that compile line to the "Hello World" page on the wiki.

https://github.com/jcupitt/libvips/wiki/Hello-World

**Comment by jcupitt** [comment]
I'll close, this seems to be done. Please reopen if there's still a problem.
