### ISSUE TITLE
vips core dump file path

### ISSUE THREAD

**Issue by juyunsang** [jcupitt/libvips#684]
Good morning.
The vips core dump file is created with the following path.
Ex) /tmp/vips-1-1ZJW2Y.v, /tmp/vips-1-BM4O2Y.v
I want to specify the directory where the core dump file is stored,
Which environment_variable specifies the core dump file path?

**Comment by jcupitt** [comment]
Hello, have a look at:

http://man7.org/linux/man-pages/man5/core.5.html

You probably need to set `/proc/sys/kernel/core_pattern`, though it varies a bit with the platform.

**Comment by jcupitt** [comment]
I'll close, this seems to be done. Please reopen if there's still a problem.
