### ISSUE TITLE
microsoft xps support

### ISSUE THREAD

**Issue by wanghaisheng** [jcupitt/libvips#687]
there is doc "t supports a good range of image formats, including JPEG, TIFF, PNG, WebP, FITS, Matlab, OpenEXR, **PDF**, SVG, HDR, PPM, CSV, GIF, Analyze, DeepZoom, and OpenSlide"
xps is a similar format like pdf ,does vips support loading xps file and saving it as jpeg?

**Comment by jcupitt** [comment]
Hello, yes, they can be loaded via libMagick. However, it will be slow and will use a lot of memory.

**Comment by wanghaisheng** [comment]
@jcupitt  right now  we have a lot pdf and xps from external sources , for both of them ,we first convert them to jpeg using mupdf,  i carefully read your wonderful lib and find that we can load pdf into  jpeg through vips  ,what the best solution for the left xps document ?

**Comment by jcupitt** [comment]
xps will work, as I said, it's loaded via libMagick. Try:

```
$ vips copy something.xps something.jpg
```

But it will not be too quick, and will need a lot of memory.

**Comment by evadne** [comment]
Hey. Would you mind checking whether MuPDF actually supports XPS

**Comment by jcupitt** [comment]
I like MuPDF, but like GhostScript it's AGPL, so if libvips links to it, libvips users in turn must open source all of their code, even if it's just running on a webserver and no software is being distributed.

I don't have a problem with that, but I think it's a blocking issue for many users.

**Comment by evadne** [comment]
The point is that @wanghaisheng already uses MuPDF so I would think that asking them to also use it for XPS conversation may be a good idea if already supported by MuPDF

**Comment by wanghaisheng** [comment]
@evadne  we actually use mupdf to convert xps or pdf documents into jpeg first

**Comment by jcupitt** [comment]
Ah, I didn't realize you were already using mupdf. Yes, I think that would probably be your best path.

**Comment by wanghaisheng** [comment]
we are evaluating  webp instead of jpeg. then we will  add a conversion step after xps/pdf to jpeg through vips　＠jcupitt

**Comment by jcupitt** [comment]
I'll close, this seems to be done. Please reopen if there's still a problem.
