### ISSUE TITLE
Resolution issue when rasterizing svg files through svgload

### ISSUE THREAD

**Issue by llwy** [jcupitt/libvips#688]
Hello,

I found a strange behaviour in the svgload command: I never seem to get the requested rasterizing resolution.

To illustrate the issue, I created 3 svg files of 10mm, 25.4mm and 50mm width (Files sent to the mailing list - I could not find a way to add files to the bug report.).

if I run the bellow command on the 25.4mm file (1 inch) requesting 8000dpi resolution, I get a file which is 10000 pixels wide (where it should be 8000 since we are talking about a 1 inch file):
vips.exe extract_band F254mm.svg[dpi=8000] F254mm.tiff[compression=ccittfax4,squash,miniswhite,resunit=VIPS_FOREIGN_TIFF_RESUNIT_INCH] 2

If I run the same command requesting a 2000dpi resolution rasterization, I obtain a file which is 2500 pixel wide instead of the theoretical 2000 pixels.

For both cases, the ratio between the actual and theoretical number of pixels is exactly 1.25.

Now if I do the same experiment with the 10mm wide image, I get 3888 pixels instead of 3150 at 8000dpi and 972 pixels instead of 787 at 2000dpi. The ratio between the actual and theoretical number of pixels is 1.23444

Finally, the same experiment performed with the 50mm wide image, I get 19666 pixels instead of 15748 at 8000dpi and 4916 pixels instead of 3937 at 2000dpi. The ratio between the actual and theoretical number of pixels is 1.24879

What is strange is that for each input image size, I get a different ratio between the requested resolution and the obtained resolution. The difference between the ratio is big enough between those files that I cannot use one ratio to correct all resolution requests.

As an alternative test, I tried to use the "scale" parameter instead of the DPI parameter. The documentation says that the default resolution is 72dpi so I tried using the scale parameter set to 72/8000 for instance but still did not get the right amount of pixels. 
As a final test, I rasterized the 25.4mm file without any scale or dpi parameter and I got a 90 pixels wide tiff file instead of a 72dpi file.

This looks like a bug to me but maybe I am missing something?

Does anyone have an idea of what is hapening here?

Thank you in advance,

Fosk

**Comment by jcupitt** [comment]
Hello, it looks like librsvg defaults to 90 DPI, but vips thinks it defaults to 72 DPI. I'll see if I can fix it.

**Comment by jcupitt** [comment]
It seems to be working better now. With this patch I see:

```
john@kiwi:~/pics$ vips copy F10mm.svg[dpi=8000] x.jpg 
john@kiwi:~/pics$ vipsheader x.jpg 
x.jpg: 3111x3111 uchar, 3 bands, srgb, jpegload
```

Though I would expect 3150, as you say. I'll keep trying.

**Comment by jcupitt** [comment]
I think I have it, it was an int truncation issue on dimension calculation. I now see:

```
john@kiwi:~/pics$ vips copy F10mm.svg[dpi=8000] x.jpg
john@kiwi:~/pics$ vipsheader x.jpg
x.jpg: 3150x3150 uchar, 3 bands, srgb, jpegload
```

This fix will be in 8.5.7, thanks!

**Comment by llwy** [comment]
Thank you very much for working on this issue so quickly!
Is there a roadmap as to when 8.5.7 is planned for release?

Best regards,

Fosk

**Comment by jcupitt** [comment]
In a week or two I'd guess. We usually wait for a few fixes to collect before doing a release, unless it's very urgent.

**Comment by llwy** [comment]
I am looking forward to downloading the next binaries.
Thank you very much

**Comment by jcupitt** [comment]
You can built it yourself, of course, the build system is here:

https://github.com/jcupitt/build-win64

Or wait a few weeks, as you say.

**Comment by jcupitt** [comment]
OK, this fix is in 8.5.7, out now. Thanks!

**Comment by llwy** [comment]
Thank you John,
Could you please direct me to the download link for the binaries?
The only download source I know is http://www.vips.ecs.soton.ac.uk/supported/current/win32/ but 8.5.7 is not available there.

Best regards,

Fosk

**Comment by jcupitt** [comment]
That's the old website. It's supposed to redirect to the new one, but they've not set it up yet.

This is the new release area:

https://github.com/jcupitt/libvips/releases

Here's the new site:

https://jcupitt.github.io/libvips/

**Comment by llwy** [comment]
I tested it and it  worked fine. Now the correct resolution is generated.
Thank you

**Comment by lovell** [comment]
I'm currently doing some preliminary testing of sharp with libvips v8.6.0 and it causes an SVG scaling test to fail (libvips v8.5.6 passes, v8.5.7+ fails). I need to spend a little more time debugging but my best guess is that this change altered the behaviour when scaling up an SVG during the raster process. Could the use of `cairo_scale` still be required for a non-default DPI?

(No urgency for anyone else to investigate yet - I'll try to provide examples using vips only, removing sharp from the equation, over the weekend.)

**Comment by jcupitt** [comment]
Hello, yes, this change will probably break SVG tests, sorry. Perhaps it should have been held back for 8.6.

**Comment by tariq1890** [comment]
@lovell I got to this page when I had looked at the "high banding from SVG to PNG" issue. Thanks!

Apologies if my issue is tangential to this thread.

@jcupitt I am not sure if I understand what's going on in this thread. I am trying to generate a linear gradient PNG from an SVG using vips copy. 

 The SVG resolution is 1920 by 1080 and I see high banding in the generated PNG.  You mention that this fix has been pushed to 8.5.7. I am, however, using 8.5.8. If my understanding is correct, the banding issue should not occur correct? Please let me know if I am doing anything wrong

**Comment by jcupitt** [comment]
Hello @tariq1890, I don't think the problem you are seeing is related. Could you open a new issue please, with a sample file that fails to render properly.

**Comment by tariq1890** [comment]
Sure! @jcupitt ! Thank you for your response.
