### ISSUE TITLE
Investigate pdfium as a possible replacement PDF loader

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#689]
pdfium is a very fast PDF rendering library, perhaps 2x to 5x faster than poppler.

https://pdfium.googlesource.com/pdfium/

https://github.com/nathanstitt/dc-pdf-raster-test

It's currently a little immature in terms of packaging -- when there's an official Debian package, investigate a `pdfload` using this instead of poppler.

**Comment by jcupitt** [comment]
Tried to build with these steps:

### Install depot tools

        cd GIT
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH=`pwd`/depot_tools:"$PATH"

### Fetch PDFium

        gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
        gclient sync

### Pull in other deps

        cd pdfium
        ./build/install-build-deps.sh

Fails saying Ubuntu 17.04 is not a supported build platform. 

### Links

    http://www.chromium.org/developers/how-tos/install-depot-tools

    https://pdfium.googlesource.com/pdfium/

**Comment by BoLaMN** [comment]
i put together a build script you can throw in docker to make it easier to get a packaged lib will generate a tar.gz with the include & lib folders

```shell
#!/usr/bin/env bash

set -e

PLATFORM=linux-x64
LIBNAME="libpdfium-dev"

git=$(which git)

BUILD_DIR="$(pwd)/build"
BUILD_PKG="$(pwd)/package"

BUILD_PDFIUM="${BUILD_DIR}/pdfium-${VERSION_PDFIUM}"
BUILD_RES="out/Release_${PLATFORM}"

TARGET_PDFIUM="$(pwd)/target"

mkdir -p ${BUILD_DIR}
cd ${BUILD_DIR}

DEPOT_TOOLS="${BUILD_DIR}/depot_tools"

if [ ! -d "${DEPOT_TOOLS}" ]; then
    ${git} clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
fi

export PATH="${DEPOT_TOOLS}":"$PATH"

gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
gclient sync

cd pdfium

gn gen "${BUILD_RES}" --args='pdf_bundle_freetype = true pdf_enable_v8 = false pdf_enable_xfa = false pdf_use_skia = false pdf_use_skia_paths = false is_component_build = true pdf_is_complete_lib = true'

# ninja -C "${BUILD_RES}"

if [ -d ${BUILD_PDFIUM} ]; then
    rm -rf ${BUILD_PDFIUM}
fi

mkdir -p ${BUILD_PDFIUM}

if [ -d ${TARGET_PDFIUM} ]; then
    rm -rf ${TARGET_PDFIUM}
fi

mkdir -p ${TARGET_PDFIUM}
mkdir -p "${TARGET_PDFIUM}/lib"
mkdir -p "${TARGET_PDFIUM}/include"

find ${BUILD_RES} -name '*.a' -not -path "**/testing/*" -not -path "**/build/*" -not -name 'libtest_support.a' -exec cp {} ${TARGET_PDFIUM}/lib \;

cp public/*.h ${TARGET_PDFIUM}/include

if [ -d ${BUILD_PKG} ]; then
    rm -rf ${BUILD_PKG}
fi

mkdir -p ${BUILD_PKG}

cd ${TARGET_PDFIUM}

tar czf /${BUILD_PKG}/libpdfium-${VERSION_PDFIUM}-${PLATFORM}.tar.gz include lib
```
i noticed libreoffice now use pdfium for rendering pdfs as images too 

https://github.com/LibreOffice/core/blob/master/vcl/source/filter/ipdf/pdfread.cxx

**Comment by jcupitt** [comment]
I made a repo with a tweaked version of @BoLaMN 's nice script:

https://github.com/jcupitt/build-pdfium

It makes a libpdfium.tar.gz, and I included the binary for convenience. I had to turn off sysroot and patch some v8 flags. I don't know much about Docker, no doubt it can be fixed up.

Of course it's built for xenial, so you'll probaly need to build on that as well, which is a pain.

**Comment by BoLaMN** [comment]
Nice! I'll see if I can wire up some travis-ci builds 

it built successfully on OS X thou I don't have a windows box to write a script against but it should be similar something like https://gist.github.com/BoLaMN/e26ac403cbe7a6057f488f895f3a2785

**Comment by tomasc** [comment]
It would be fantastic to improve the speed of PDF rendering in libvips.

I have been using libpoppler backed libvips, however with any larger PDF (100MB+) rendering a single page might take up to 10 seconds or even more.

For now, the work around I am using is to pre-render the page using [MuPDF](https://mupdf.com) to PNG (`mutool convert` does not support JPG among others) and then use libvips for JPG conversion. The performance gain is significant.

**Comment by swftvsn** [comment]
This change would be really appreciated! Any news about this lately?

**Comment by jcupitt** [comment]
I had another look: pdfium now builds on current Ubuntu, so that's a good step forward. I updated my build-pdfium repo and I now have an updated binary for my platform.

I'll make a branch to experiment with it in.

**Comment by swftvsn** [comment]
Awesome news! Don't know if this is obvious, but here's an example how they render to png in their tests: https://pdfium.googlesource.com/pdfium/+/master/samples/pdfium_test.cc (And ppm and what not)

**Comment by tomasc** [comment]
Just to add to this – I am currently rerouting to MuPDF for conversion and then loading the result back to libvips. Having libvips fast by default would be super!

**Comment by swftvsn** [comment]
I just built by hand the pdfium test package and am using it to preprocess stuff before libvips until this hits stable. So far it's proven to be both faster and to produce better quality when fed our library of problematic PDFs! Really excited!

**Comment by jcupitt** [comment]
Branch here:

https://github.com/jcupitt/libvips/tree/pdfium-experiment

Though it doesn't do much yet. I can't even get a basic pdfium "hello world" program to link correctly :(

**Comment by jcupitt** [comment]
... it's now detecting and linking to PDFium, at least if it's been packaged by the build-pdfium repo above. I'll have a quick go at a load operation.

**Comment by jcupitt** [comment]
I got it working, or enough to test anyway.

Here's the pdfium branch:

```
$ # load single page at screen res
$ time vips pdfload nipguide.pdf x.jpg
real	0m0.063s
user	0m0.067s
sys	0m0.010s
$ # load single page at high res
$ time vips pdfload nipguide.pdf x.jpg --page 10 --scale 5
real	0m0.596s
user	0m0.846s
sys	0m0.056s
$ # load whole document at screen res
$ time vips pdfload nipguide.pdf x.jpg --n -1
real	0m3.914s
user	0m4.490s
sys	0m0.107s
```

And poppler, for comparison:

```
$ time vips pdfload nipguide.pdf x.jpg --page 10 --scale 5
real	0m0.349s
user	0m0.584s
sys	0m0.037s
$ time vips pdfload nipguide.pdf x.jpg --n -1
real	0m1.445s
user	0m2.080s
sys	0m0.066s
```

So on those timings, poppler is faster. Does anyone have a link to a PDF that they would expect PDFium to be quicker on?

It's a pain to build. You have to package pdfium with this thing:

https://github.com/jcupitt/docker-builds/tree/master/pdfium

Then untar that to your libvips install prefix, or somewhere else and configure with `--with-pdfium-libraries` etc.

**Comment by jcupitt** [comment]
I checked the size: git master `libvips.so` is about 2.8MB stripped, the pdfium branch ups that to about 10MB stripped. 

Yes, my test PDF was from pdflatex and not very complicated. 

PDFium is not a simple shared library you can just add to your project -- it's a huge wodge of object code you have to paste in statically. I think this is (in part anyway) because of the way the project started as a desktop PDF viewer on Windows called foxit. PDFium has been made by (quite crudely) cutting code out of foxit. Perhaps PDFium packaging will improve in future and it'll become easier to reuse. 

There's some stuff I've not done:

- Filename encodings will need some sorting out, especially on Windows. 
- It always generates RGBA to match poppler.
- I've not done `new_from_buffer` -- it's files only for now.

**Comment by swftvsn** [comment]
Wow, that's slim! My build is 43Mb and I though it's nice and light package :) Too bad it's not easier to integrate :( Let's hope it gets better eventually.

Re: speed, I can sacrifice speed to get the better licensing of pdfium. For me the motivator is first and foremost licensing. I also thought that pdfium is superior on large pdfs, but I may be wrong here.

Thanks for the good work so far!

**Comment by BoLaMN** [comment]
Maybe try some PDFs from with http://www.auto-brochures.com/audi.html might result differently due to the graphics, etc...

**Comment by jcupitt** [comment]
I tried the R8 one. PDFium:

```
john@kiwi:~/pics$ time vips pdfload Audi_US\ R8_2017-2.pdf x.v --scale 2 --n -1
real	0m43.799s
user	0m43.139s
sys	0m0.804s
```

Poppler:

```
john@kiwi:~/pics$ time vips pdfload Audi_US\ R8_2017-2.pdf x.v --scale 2 --n -1
real	0m40.478s
user	0m39.947s
sys	0m0.660s
```

So poppler wins, but not by much. 

I can see the licence is a big draw for PDFium.

**Comment by jcupitt** [comment]
I did some final fixups. It runs cleanly under valgrind and passes all tests. I think the only remaining issue is filename encodings on Windows -- I've no idea if it'll work for non-ascii filenames. They are fine on Linux, fwiw.

Getting this to work on Windows will be rather challenging anyway, so perhaps that's not important. I'll merge to master and close.

Well done to all contributors!

**Comment by jcupitt** [comment]
I found another interesting image to benchmark on: a complex architectural drawing (which I can't share unfortunately).

PDFium:

```
$ time vips pdfload --dpi 600 --scale 3 big.pdf image.jpg
real	0m37.742s
user	0m40.802s
sys	0m0.565s
peak mem 900mb
```

Poppler:

```
$ time vips pdfload --dpi 600 --scale 3 big.pdf image.jpg
real	0m11.147s
user	0m14.335s
sys	0m0.337s
peak mem 300mb
```

So it seems PDFium is somewhat slower at issuing drawing commands. 

The memory use is interesting: PDFium does not support rendering part of the page -- you have to allocate a huge memory buffer and render the entire page in one go. This pushes memory use up quite a bit. Poppler (in that example) is rendering as s series of strips.

PDFium does support partial rendering if the output is a Windows drawable. It uses the InvalidateRect message to redraw just a section of the page. This obviously won't work when rendering to a bitmap though. 

PDFium fails in this example if you turn scale to 4. I guess it does not like very large image output. Poppler fails at scale 6, since cairo gives up if an axis goes over 32768.

**Comment by swftvsn** [comment]
@BoLaMN @jcupitt  I added a new ticket for the optimization here: #957
