### ISSUE TITLE
Ubuntu Package Name?

### ISSUE THREAD

**Issue by anishpatel** [jcupitt/libvips#691]
What is the correct (official?) package name for libvips on Ubuntu?

The package `libvips` [does not exist](https://packages.ubuntu.com/search?keywords=libvips), but there is `libvips37` and `libvips42`. Is libvips42 supposed to be the correct package name? I ask because I the 42 doesn't seem to match with a recent version as far as I can tell. Also `libvips-dev` and `libvips-tools` depend on libvips37, so not being an expert on the way packaging works, I am not sure if having libvips42 will conflict with any of the other packages.

**Comment by jcupitt** [comment]
Hello, `libvips42` is the library binary. The 42 is the libtool version number, which is not the same as the user-visible version, as you say -- 42 is the 8.x series, libvips37 is the old 7.x series. You wouldn't ever install `libvips42` yourself, it's there for other packages to depend on. 

The packages `libvips-tools` and `libvips-dev` are the headers and tools for the current version. They will depend on the latest version of the library, so they don't have a version number in the package name. These are the thing you'd install as a user.

**Comment by anishpatel** [comment]
Thanks!

If the VipsWiki is still active, it might be useful to update this information on [Build on Ubuntu](http://www.vips.ecs.soton.ac.uk/index.php?title=Build_on_Ubuntu) and [Links](http://www.vips.ecs.soton.ac.uk/index.php?title=Links).

**Comment by jcupitt** [comment]
That's the old site, the new one is here:

https://jcupitt.github.io/libvips/

The old site is supposed to just forward people to the new one, but the admins still haven't put the fwd links in :(
