### ISSUE TITLE
Minimize libvips.so

### ISSUE THREAD

**Issue by bubba-h57** [jcupitt/libvips#692]
I have a managed pipeline that always takes a `png` input and will output either `zoomify` or `google` layouts to a buffer via `$event->sourceBlob = $image->dzsave_buffer(['layout' => 'zoomify', 'container' => 'zip']);`

I am trying to figure out how to build the smallest possible `libvips.so` to support this. Any advice on what build options to use and what dependencies can be left out to achieve it would be appreciated!

**Comment by jcupitt** [comment]
Hello, I'd make a fork of `build-win64`, look though `vips.modules`, and then start deleting things. You can get rid of all the lcms colour management, all the font rendering, tiff, fftw, cfitsio, openslide, matlab and probably quite a few others.

**Comment by jcupitt** [comment]
I just looked at this again and realized you mean linux. Try `./configure --help` and you'll see a list of the options. I would run configure, look at the summary at the end, and turn things off. You'll need libpng and libgsf, but you should be able to disable almost everything else.

You can also strip the library and remove any debugging symbols with`strip libvips.so`. It can save quite a bit, depending on the compiler flags you've used.

**Comment by bubba-h57** [comment]
`strip libvips.so` Nice .. thank you sir!
