### ISSUE TITLE
vips_text coordinates?

### ISSUE THREAD

**Issue by dubcanada** [jcupitt/libvips#693]
Hello,

Is there a way to specify the location of the vips_text? Like x,y where to start writing text?

I did not find anything in all of my searching.

**Comment by jcupitt** [comment]
Hello, no, `text` makes a new image holding the text, it doesn't add text to an existing image.

If you want to write text at an (x, y) position into an existing image, the best way is to make the text overlay, blow it up to the size of your image, and blend them together. 

In Ruby, something like:

```ruby
require 'vips'

im = Vips::Image.new_from_file ARGV[0], :access => :sequential

# render text, blow up to the size of the source image, with the text offset 
# at position (100, 100)
text = Vips::Image.text ARGV[2], :dpi => 300
text = text.embed 100, 100, im.width, im.height 

# blend with original image using a pale red for the text
im = text.ifthenelse [128, 0, 0], im, :blend => true

im.write_to_file ARGV[1]
```

There was a blog post a few years ago about something a bit like this:

http://libvips.blogspot.co.uk/2014/10/image-annotation-with-pyvips8.html

**Comment by jcupitt** [comment]
I'll close, please reopen if you still have problems.
