### ISSUE TITLE
Dead link in image pyramids doc

### ISSUE THREAD

**Issue by rmcloughlin** [jcupitt/libvips#694]
On this page https://jcupitt.github.io/libvips/API/current/Making-image-pyramids.md.html there is a link for the "NYU Pathology pyramid builder" but the link is dead.  Perhaps the right link is https://iime.github.io/virtualmicroscope/ or maybe it should link directly to Google Maps and leaflet.js.

**Comment by jcupitt** [comment]
Thanks for pointing this out! Fixed in master.

**Comment by rmcloughlin** [comment]
Nitpick:  It should say "compatible with leaflet" not "compatible with the leaflet."

**Comment by jcupitt** [comment]
Ooops! Fixed, thanks.
