### ISSUE TITLE
Running VIPS COPY on JPG -> PNG image rotates it unintentionally

### ISSUE THREAD

**Issue by devedse** [jcupitt/libvips#696]
I'm currently using VIPS to convert a JPG image to PNG. However, when I run VIPS COPY on a 'standing' image and convert it to png it will rotate it to 'landscape' orientation. When I convert the same Image to JPG it will stay straight up.

![image](https://user-images.githubusercontent.com/2350015/28596828-15595a28-719b-11e7-89e3-c9548ae66a1c.png)

The same issue occurs when converting to PNG, TIFF, WebP and possibly others.

Commands I ran:
![image](https://user-images.githubusercontent.com/2350015/28596864-514988c8-719b-11e7-9996-74517c661dbb.png)

This issue didn't seem to occur for images that already were in 'landscape' orientation.

I ran the image through some lossless JPG optimizers and after that the issue didn't seem to occur anymore (also included this image as Image2B.JPG in the attached zip file).

[TestImages.zip](https://github.com/jcupitt/libvips/files/1174973/TestImages.zip)

Edit:
When I call `vips.exe rot Image2A.JPG output.png d270` the output image will be straight up.

Edit2:
After doing some further investigation I found out that the Image2A.JPG has it's Orientation Exif Data set to 270CW and Image2B.JPG to normal. It seems that VIPS doesn't look at this data when loading the image.

**Comment by jcupitt** [comment]
Hello, that's right, PNG has no orientation tag, so although your image seems to rotate, in fact it's just orientation being lost. 

Use `autorotate` to spin an image upright and remove the tag:

```
vips copy x.jpg[autorotate] y.png
```

**Comment by jcupitt** [comment]
TIFF has an orientation tag, and vips sets it, but sadly very few viewers support it.

**Comment by devedse** [comment]
Ah thanks, that helps.
