### ISSUE TITLE
webp transparency bug

### ISSUE THREAD

**Issue by xinuc** [jcupitt/libvips#700]
We found (transparency?) problems when converting some images from jpg to webp

here's one of the original image
![original image](https://s2.bukalapak.com/img/7668261241/original/13156912_41c5da9e_5d0e_4c28_95b7_de1f68e00fe0.jpg)

and this is the result in webp 
![webp image](https://s2.bukalapak.com/img/7668261241/m-1000-1000/13156912_41c5da9e_5d0e_4c28_95b7_de1f68e00fe0.jpg.webp)

**Comment by jcupitt** [comment]
Hello, this was fixed in 8.5.7, released a couple of days ago. Could you try updating? 

Your JPG image is CMYK --- 8.5.7 has a new thing that automatically transforms CMYK -> RGB if the writer does not support CMYK and there is an embedded profile.

**Comment by xinuc** [comment]
Awesome, thanks :+1:

**Comment by xinuc** [comment]
Hi,

I've tried to update to 8.5.7 in mac and linux (alpine)
in mac, it works as expected, but in alpine linux, I got image like this

![13156912_41c5da9e_5d0e_4c28_95b7_de1f68e00fe0](https://user-images.githubusercontent.com/57373/28859854-1644a836-7784-11e7-970b-df6c700ed955.jpg)

this is my steps when compiling libvips
```
  curl -LO https://github.com/jcupitt/libvips/releases/download/v8.5.7/vips-8.5.7.tar.gz && \
  tar zvxf vips-8.5.7.tar.gz && \
  cd vips-8.5.7 && \
  ./configure --without-python --with-webp && \
  make && \
  make install
```

**Comment by jcupitt** [comment]
Do you have lcms on alpine? Vips needs it to transform cmyk to rgb.

**Comment by xinuc** [comment]
yes, lcms & lcms-dev are already installed.

**Comment by jcupitt** [comment]
Huh, strange!

Could you try converting to PNG? That also has no CMYK support, so vips will need to convert.

**Comment by xinuc** [comment]
Ah yes, we got the same strange image for PNG

![png](http://xinuc.org/13156912_41c5da9e_5d0e_4c28_95b7_de1f68e00fe0.png)

**Comment by jcupitt** [comment]
Could you try just running the CMYK to RGB conversion? Something like:

```
$ vips icc_transform cmyk2.jpeg x.jpg /usr/share/color/icc/sRGB.icc 
```

where `cmyk2.jpeg` is your source image.

**Comment by xinuc** [comment]
`icc_transform: unable to open profile "/usr/share/color/icc/sRGB.icc"`

I tried to install `colord` package (https://pkgs.alpinelinux.org/contents?file=sRGB.icc&path=&name=&branch=&repo=&arch=)
but apparently it's not available in alpine 3.4

**Comment by jcupitt** [comment]
There should be an sRGB profile on your system somewhere. Try:

```
$ locate -i srgb.ic
```

**Comment by xinuc** [comment]
to be clear, I use alpine in docker, so maybe the packages is very minimal.

I just downloaded the icc file from here
https://github.com/lovell/sharp/blob/master/lib/icc/sRGB.icc

and this is the image result
![x](https://user-images.githubusercontent.com/57373/28868670-5eea6736-77a4-11e7-9975-a10bfd44c3ad.jpg)

**Comment by jcupitt** [comment]
Then it seems there is a problem with lcms on alpine. Do you know which version they are using?

**Comment by xinuc** [comment]
```
# apk info lcms
lcms-1.19-r6 description:
Lightweight color management development library/engine

lcms-1.19-r6 webpage:
http://www.littlecms.com

lcms-1.19-r6 installed size:
159744
```

**Comment by jcupitt** [comment]
Wow that's a version from 10 years ago. Maybe they have another package for lcms2?

libvips should probably refuse to work with lcms1.

**Comment by xinuc** [comment]
ah, yes, got it.

will give it a try

**Comment by xinuc** [comment]
It works with lcms2.

Thanks a lot for your help & patience.
And also for this wonderful piece of software.

**Comment by jcupitt** [comment]
I'm glad it's working. I've removed lcms1 support from 8.6, since it was (obviously) no longer being tested.
