### ISSUE TITLE
vips small dimension thumbnail issue

### ISSUE THREAD

**Issue by juyunsang** [jcupitt/libvips#711]
when I have generated thumbnail, there is some issue.
When creating a thumbnail from the Large resolution original, the thumbnail becomes more damaged.
1900x1900 -> 240x240
540x676 -> 240x300
Attached with original and generated thumbnail file.
Please explain why.

![Uploading 540x676_thumbnail.jpg…]()
![Uploading 1900x1900_original.jpg…]()
![Uploading 1900x1900_Thumbnail.jpg…]()
![540x676_original](https://user-images.githubusercontent.com/13113520/29255454-785aae1a-80dc-11e7-983c-ab169d7a3540.jpg)

**Comment by jcupitt** [comment]
Hello, sorry for the delay in responding.

Could you upload the full-size image please?

My guess would be that you need to set a higher JPEG compression quality if you want the text to look good, or perhaps use PNG. 

Try:

```
vipsthumbnail huge_original.jpg --size 240 -o thumb.jpg[Q=95]
```

**Comment by jcupitt** [comment]
I found this version of your iamge:

**Comment by jcupitt** [comment]
Sorry for the half-post, I've updated it. 

Please reopen if you still have issues.
