### ISSUE TITLE
vips_thumbnail: "perceptual" ICC profile output

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/libvips#714]
It looks like there isn't a way to tell `vips_thumbnail` (and thus `lcms2`) that the export ICC profile uses a "perceptual" intent. See this example:

```php
<?php

use Jcupitt\Vips\Image;

require __DIR__ . '/vendor/autoload.php';

// Image: https://t0.nl/original.jpg
// sRGB ICC profile: https://github.com/lovell/sharp/raw/master/lib/icc/sRGB.icc
// (https://packages.debian.org/sid/all/icc-profiles-free/filelist)
$image = Image::thumbnail(__DIR__ . '/original.jpg', 681, [
    'height' => 1000,
    'export_profile' => __DIR__ . '/sRGB.icc',
]);

$image->writeToFile(__DIR__ . '/output.jpg');
```

[Input](https://t0.nl/original.jpg) (has a embedded CMYK profile that uses a "relative" intent)
[Output](https://user-images.githubusercontent.com/12746591/29409738-ed5bca00-834d-11e7-9d1d-2d31844d119d.jpg)
[Expected output](https://user-images.githubusercontent.com/12746591/29409747-fe1d4774-834d-11e7-9d80-c7b942482b79.jpg)

My search for a free (licensed for distribution)  sRGB ICC profile using a "relative" intent led to nothing, so maybe `vips_thumbnail` could force it always to `VIPS_INTENT_PERCEPTUAL` when transforming between ICC profiles.

**Comment by jcupitt** [comment]
I don't like perceptual much, it means "do whatever you like, as long as it looks good", there's no requirement to be colorimetrically accurate. Relative means "transform as specified in the profile, but adapt white to device white", so it's the simplest one that looks OK.

I think most srgb profiles support relative, don't they? The one in nip2 does:

https://github.com/jcupitt/nip2/blob/master/share/nip2/data/sRGB.icm

**Comment by kleisauke** [comment]
I checked the nip2 sRGB ICC profile (with [`iccdump`](http://argyllcms.com/doc/iccdump.html)), it seems that the rendering intent is "perceptual":
```bash
iccdump sRGB.icm
```

<details>
 <summary>Output</summary>

```
icc:
Header:
  size         = 6922 bytes
  CMM          = 'lcms'
  Version      = 2.3.0
  Device Class = Display
  Color Space  = RGB
  Conn. Space  = XYZ
  Date, Time   = 13 Aug 2004, 12:18:06
  Platform     = Microsoft
  Flags        = Not Embedded Profile, Use anywhere
  Dev. Mnfctr. = 'lcms'
  Dev. Model   = 0x0
  Dev. Attrbts = Reflective, Glossy, Positive, Color
  Rndrng Intnt = Perceptual
  Illuminant   = 0.964203, 1.000000, 0.824905    [Lab 100.000000, 0.000498, -0.000436]
  Creator      = 'lcms'

tag 0:
  sig      'dmnd'
  type     'desc'
  offset   276
  size     106
TextDescription:
  ASCII data, length 16 chars:
    0x0000: lcms generated
  No Unicode data
  No ScriptCode data

tag 1:
  sig      'desc'
  type     'desc'
  offset   384
  size     104
TextDescription:
  ASCII data, length 5 chars:
    0x0000: sRGB
  No Unicode data
  No ScriptCode data

tag 2:
  sig      'dmdd'
  type     'desc'
  offset   488
  size     104
TextDescription:
  ASCII data, length 5 chars:
    0x0000: sRGB
  No Unicode data
  No ScriptCode data

tag 3:
  sig      'wtpt'
  type     'XYZ '
  offset   592
  size     20
XYZArray:
  No. elements = 1

tag 4:
  sig      'rXYZ'
  type     'XYZ '
  offset   612
  size     20
XYZArray:
  No. elements = 1

tag 5:
  sig      'bXYZ'
  type     'XYZ '
  offset   632
  size     20
XYZArray:
  No. elements = 1

tag 6:
  sig      'gXYZ'
  type     'XYZ '
  offset   652
  size     20
XYZArray:
  No. elements = 1

tag 7:
  sig      'rTRC'
  type     'curv'
  offset   672
  size     2060
Curve:
  No. elements = 1024

tag 8:
  sig      'gTRC'
  type     'curv'
  offset   2732
  size     2060
Curve:
  No. elements = 1024

tag 9:
  sig      'bTRC'
  type     'curv'
  offset   4792
  size     2060
Curve:
  No. elements = 1024

tag 10:
  sig      'chrm'
  type     'chrm'
  offset   6852
  size     36

tag 11:
  sig      'cprt'
  type     'text'
  offset   6888
  size     33
Text:
  No. chars = 25
    0x0000: no copyright, use freely
```
</details>


With the provided picture I see that the rendering intent is "relative":
```bash
convert -size 64x64 original.jpg profile.icm
iccdump profile.icm
```

<details>
 <summary>Output</summary>

```
icc:
Header:
  size         = 557168 bytes
  CMM          = 'ADBE'
  Version      = 2.1.0
  Device Class = Output
  Color Space  = CMYK
  Conn. Space  = Lab
  Date, Time   = 26 Jul 2000, 5:41:53
  Platform     = Macintosh
  Flags        = Not Embedded Profile, Use anywhere
  Dev. Mnfctr. = 'ADBE'
  Dev. Model   = 0x0
  Dev. Attrbts = Reflective, Glossy, Positive, Color
  Rndrng Intnt = Relative Colorimetric
  Illuminant   = 0.964203, 1.000000, 0.824905    [Lab 100.000000, 0.000498, -0.000436]
  Creator      = 'ADBE'

tag 0:
  sig      'desc'
  type     'desc'
  offset   252
  size     116
TextDescription:
  ASCII data, length 26 chars:
    0x0000: U.S. Web Coated (SWOP) v2
  No Unicode data
  No ScriptCode data

tag 1:
  sig      'cprt'
  type     'text'
  offset   368
  size     43
Text:
  No. chars = 35
    0x0000: Copyright 2000 Adobe Systems, Inc.

tag 2:
  sig      'wtpt'
  type     'XYZ '
  offset   412
  size     20
XYZArray:
  No. elements = 1

tag 3:
  sig      'A2B0'
  type     'mft2'
  offset   432
  size     41478
Lut16:
  Input Channels = 4
  Output Channels = 3
  CLUT resolution = 9
  Input Table entries = 256
  Output Table entries = 2
  XYZ matrix =  1.000000, 0.000000, 0.000000
                0.000000, 1.000000, 0.000000
                0.000000, 0.000000, 1.000000

tag 4:
  sig      'A2B2'
  type     'mft2'
  offset   432
  size     41478
Lut16:
  Input Channels = 4
  Output Channels = 3
  CLUT resolution = 9
  Input Table entries = 256
  Output Table entries = 2
  XYZ matrix =  1.000000, 0.000000, 0.000000
                0.000000, 1.000000, 0.000000
                0.000000, 0.000000, 1.000000

tag 5:
  sig      'A2B1'
  type     'mft2'
  offset   41912
  size     41478
Lut16:
  Input Channels = 4
  Output Channels = 3
  CLUT resolution = 9
  Input Table entries = 256
  Output Table entries = 2
  XYZ matrix =  1.000000, 0.000000, 0.000000
                0.000000, 1.000000, 0.000000
                0.000000, 0.000000, 1.000000

tag 6:
  sig      'B2A0'
  type     'mft1'
  offset   83392
  size     145588
Lut8:
  Input Channels = 3
  Output Channels = 4
  CLUT resolution = 33
  Input Table entries = 256
  Output Table entries = 256
  XYZ matrix =  1.000000, 0.000000, 0.000000
                0.000000, 1.000000, 0.000000
                0.000000, 0.000000, 1.000000

tag 7:
  sig      'B2A1'
  type     'mft1'
  offset   228980
  size     145588
Lut8:
  Input Channels = 3
  Output Channels = 4
  CLUT resolution = 33
  Input Table entries = 256
  Output Table entries = 256
  XYZ matrix =  1.000000, 0.000000, 0.000000
                0.000000, 1.000000, 0.000000
                0.000000, 0.000000, 1.000000

tag 8:
  sig      'B2A2'
  type     'mft1'
  offset   374568
  size     145588
Lut8:
  Input Channels = 3
  Output Channels = 4
  CLUT resolution = 33
  Input Table entries = 256
  Output Table entries = 256
  XYZ matrix =  1.000000, 0.000000, 0.000000
                0.000000, 1.000000, 0.000000
                0.000000, 0.000000, 1.000000

tag 9:
  sig      'gamt'
  type     'mft1'
  offset   520156
  size     37009
Lut8:
  Input Channels = 3
  Output Channels = 1
  CLUT resolution = 33
  Input Table entries = 256
  Output Table entries = 256
  XYZ matrix =  1.000000, 0.000000, 0.000000
                0.000000, 1.000000, 0.000000
                0.000000, 0.000000, 1.000000
```
</details>

Would everything go well if we transforming it with the "relative" intent (`VIPS_INTENT_RELATIVE`) if the provided ICC profile is "perceptual"?

**Comment by kleisauke** [comment]
**Update**:
I tried to patch the thumbnail class to use a "perceptual" intent for the `vips_icc_transform` function, see:
```diff
--- /home/kleisauke/libvips-master/libvips/resample/thumbnail.c	Tue Aug 29 02:33:44 2017
+++ /home/kleisauke/libvips-master/libvips/resample/thumbnail.c	Wed Aug 30 12:14:31 2017
@@ -471,6 +471,7 @@
 			if( vips_icc_transform( in, &t[7], 
 				thumbnail->export_profile,
 				"embedded", TRUE,
+				"intent", VIPS_INTENT_PERCEPTUAL,
 				NULL ) ) {
 				g_warning( _( "unable to import with "
 						"embedded profile: %s" ),
@@ -490,6 +491,7 @@
 				thumbnail->export_profile,
 				"input_profile", thumbnail->import_profile,
 				"embedded", FALSE,
+				"intent", VIPS_INTENT_PERCEPTUAL,
 				NULL ) )  
 				return( -1 );
```

Unfortunately, this doesn't seem to make any improvements for the "colourfulness".  Tested with:

```bash
vipsthumbnail original.jpg \
    --size 1000x \
    -o %s_thumbnail.jpg[optimize_coding,strip] \
    --eprofile sRGB.icm
```
<sup>(I’ve opened this issue because I did encounter problems with the "colourfulness" for images with an embedded CMYK profile)</sup>

I'm aiming for the [expected output](https://user-images.githubusercontent.com/12746591/29409747-fe1d4774-834d-11e7-9d80-c7b942482b79.jpg) that is generated with sharp which forces the "perceptual" intent when transforming between ICC profiles (see [source code](https://github.com/lovell/sharp/blob/5f29d1ba9c2ca89b3e1e166e2747b99e7c6622b9/src/pipeline.cc#L303-L311)). The [output](https://user-images.githubusercontent.com/12746591/29409738-ed5bca00-834d-11e7-9d1d-2d31844d119d.jpg) from `vips_thumbnail` looks less colourful. My first thought was that this problem would lie in the handling of ICC profiles and the associated options but maybe I'm on the wrong track.

As a side note, it might be better to let users define `vips_icc_transform` options with in the path (just like the `[page=1]` property for `pdfload`, `tiffload` and `magickload`). See for example: 
```bash
vipsthumbnail original.jpg \
    --size 1000x \
    -o tn_%s.jpg[optimize_coding,strip] \
    --eprofile sRGB.icm[intent=perceptual]
```

**Comment by jcupitt** [comment]
I really don't like perceptual :( all it's doing here is dropping the black point and making the image look more contrasty, perhaps by handling GCR differently. You could boost the contrast on all the images passing though vips, but it wouldn't make them any better. 

If we were to add an intent, I think it would need to be an extra thumbnail argument, eg.:

```
vipsthumbnail original.jpg \
    --size 1000x \
    -o tn_%s.jpg[optimize_coding,strip] \
    --intent perceptual \
    --eprofile sRGB.icm
```

**Comment by jcupitt** [comment]
There's an `intent` option for thumbnail now. It gives the same results as imagemagick:

![x](https://user-images.githubusercontent.com/580843/29881180-c9e74f28-8da1-11e7-994c-dc5ea5bf8b98.jpg)

relative on the left, percep on the right.

**Comment by kleisauke** [comment]
Thanks for adding this! Just tested and it seems to do its job (I didn't saw any difference with my patch).

Just one last question:
If the provided export ICC profile is perceptual (see [`iccdump sRGB.icm`](https://github.com/jcupitt/libvips/issues/714#issuecomment-323071514)) do you then also prefer to use the relative intent over the perceptual intent? I thought the intent flag (with the `vips_icc_*` operations) should match the ICC profile rendering intent.

**Comment by jcupitt** [comment]
I don't think the profile type means much for monitors: they are just three curves and a matrix. I think relative is fine there.

**Comment by kleisauke** [comment]
Thanks, we see better results for some CMYK images now. You may close this issue.

**Comment by jcupitt** [comment]
OK, good stuff!
