### ISSUE TITLE
VIPS_WARNING environment variable not working in vips 8.5.6

### ISSUE THREAD

**Issue by apacheark** [jcupitt/libvips#715]
I have searched the repository and found some answers for ruby and for C, but is there another way to disable the warnings for the python bindings for libvips 8.5.6?  The VIPS_WARNING environment variable no longer works.  I think 8.5.8 is supposed to fix that. But, is there a way to disable them in 8.5.6?

I am running on Ubuntu 16.04 LTS running VIPS 8.5.6.

Thanks!

**Comment by jcupitt** [comment]
Hello, you need to set a handler for warning messages. Here's the C code for this:

https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/init.c#L455

So you need to match that in Python using the glib binding. I'll see if I can make an example.

There's a new, much simpler Python binding here, which should be compatible:

https://github.com/jcupitt/pyvips

not quite done yet though.

**Comment by apacheark** [comment]
That's great, thanks.

**Comment by jcupitt** [comment]
This seems to work:

```python
import sys
import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips, GLib

def empty_log_handler():
    pass

GLib.log_set_handler("VIPS", GLib.LogLevelFlags.LEVEL_WARNING, empty_log_handler)

x = Vips.Image.new_from_file(sys.argv[1])
print x.avg()
```

If I comment out the `log_set_handler` and run on a broken jpg file, I see:

```
$ python py-warnings.py ~/pics/broken.jpg 
156.440825144
(py-warnings.py:22639): VIPS-WARNING **: read gave 2 warnings
(py-warnings.py:22639): VIPS-WARNING **: VipsJpeg: Premature end of JPEG file
```

If I have the handler set in there, I see:

```python
$ python py-warnings.py ~/pics/broken.jpg 
156.440825144
```

Though I'm not sure hiding the warnings is a good idea :(

**Comment by apacheark** [comment]
Thanks for that.  Yes, I understand that hiding warnings is not a good
idea, but for this use case, I have other checks.
Will try this out, thanks again!

**Comment by jcupitt** [comment]
I'll close, please reopen if you still have problems.

**Comment by apacheark** [comment]
Ok, thanks

**Comment by apacheark** [comment]
I did try the code you sent, but am getting the following error:

"TypeError: empty_log_handler() takes 0 positional arguments but 3 were
given"

Here is the code part.  The Vips.Image.new code line is just to provide you
the triggering code.

import os, time
import sys
#from gi.repository import Vips
from gi.repository import Vips, GLib

def empty_log_handler():
    pass

GLib.log_set_handler("VIPS", GLib.LogLevelFlags.LEVEL_WARNING,
empty_log_handler)

rim = Vips.Image.new_from_file(in_img_path+r_name,access =
Vips.Access.SEQUENTIAL)


Any ideas?  Thanks.

**Comment by apacheark** [comment]
Just found a fix.  You can replace the function to be:


def empty_log_handler(domain, level, message):
    pass

**Comment by jcupitt** [comment]
Huh strange, it must depend on the gobject-introspection version. I'm glad it's working!

You probably saw, the new python binding is out now:

https://pypi.python.org/pypi/pyvips

It's much, much simpler: you can install it just with `pip install pyvips` and it'll work with any libvips back to 8.2. The API is the same.

It doesn't have any support for hiding warnings, that would need to be added (or use `VIPS_WARNING`). I guess something like:

```
pyvips.set_warnings(False)
```

would be enough?

**Comment by jcupitt** [comment]
Actually, it would be best if it redirected warnings to the standard Python `logging` module. Would that work?

**Comment by jcupitt** [comment]
pyvips 2.0.1 now redirects libvips warnings to the logging module.

This test program generates no output, except the print (obviously).

```python
import pyvips

x = pyvips.Image.new_from_file("truncated.png")
print 'avg =', x.avg()
```

But this produces a lot of output:

```python
import logging
logging.basicConfig(level=logging.WARNING)

import sys
import pyvips

x = pyvips.Image.new_from_file("truncated.png")
print 'avg =', x.avg()
```

**Comment by apacheark** [comment]
Thanks for the update on pyvips. And yes, that addition to disable warnings
would be useful!
