### ISSUE TITLE
How to join big tiff in window?

### ISSUE THREAD

**Issue by FreeAJust** [jcupitt/libvips#717]
Hi, I want to join two big tiff images(about 5GB) with vips like this in window : 
vips.exe  join  in1.tiff in2.tiff out.tiff  horizontal  
It  failed because of the limitation of Maximun of TIFF file.
but I when I join the same images in ubuntu with the same command line , it works well, because it used biftiff mode automatically.
So ,how can I join two big tiff images in window?
Thanks a lot!

**Comment by jcupitt** [comment]
Strange, it should automatically enable bigtiff on Windows too. What version are you using?

You can try enabling bigtiff save by hand, like this:

```
vips.exe join in1.tiff in2.tiff out.tiff[bigtiff] horizontal
```

**Comment by jcupitt** [comment]
I just tried with two 6GB tiffs and it worked for me on Windows with 8.5.8. Which version of libvips are you using? The Windows build has improved recently, it might be worth updating if you're on an older version:

https://github.com/jcupitt/libvips/releases

I noticed that `join` is not running in streaming mode, so it's rather slow with large TIFFs. I'll fix this for the next version.

**Comment by jcupitt** [comment]
With seq enabled, CLI join is now much quicker. On my tiny laptop I see:

```
$ time vips join left.tif right.tif x.tif horizontal

(vips:7258): VIPS-WARNING **: image over 4gb, enabling bigtiff

real	2m49.287s
user	0m15.300s
sys	0m17.744s
$ ls -l left.tif right.tif x.tif 
-rw-r--r-- 1 john john  6587588168 Aug 25 09:44 left.tif
-rw-r--r-- 1 john john  6587588168 Aug 25 10:38 right.tif
-rw-r--r-- 1 john john 13175166968 Aug 25 11:08 x.tif
```

So a 13gb file in under 3 minutes. It's IO-limited, so it'd be faster on a machine with a better SSD.

**Comment by FreeAJust** [comment]
Thanks a lot !
I used 8.4 before,and after update to 8.5, it automatically using bigtiff mode.

Thanks for your answering!

**Comment by jcupitt** [comment]
Good! There's a pre-release of 8.6 here:

https://github.com/jcupitt/libvips/releases/tag/v8.6.0-alpha2

It should be a lot quicker for this use case.
