### ISSUE TITLE
Libvips equivalent of spread in imagemagick

### ISSUE THREAD

**Issue by tariq1890** [jcupitt/libvips#718]
This is the link in case you need more details

http://www.imagemagick.org/Usage/transform/#spread

**Comment by jcupitt** [comment]
Sorry, I don't think there is an equivalent. Gaussian blur is sort-of similar, I guess. Would that work?

**Comment by tariq1890** [comment]
Thanks for the quick response @jcupitt . Oh that is unfortunate. I use spread to remove banding in the gradients that I create.

Is it possible to create multi-color linear gradients with less banding through libvips?

**Comment by jcupitt** [comment]
You can make smooth gradients in many ways, for example in Ruby:

```ruby
# make a 256 element colour map: a linear fade from start to stop, with
# start and stop as CIELAB colours, the output map as sRGB
def gradient(start, stop)
    lut = Vips::Image.identity / 255
    lut = lut * start + (lut * -1 + 1) * stop
    lut.colourspace(:srgb, :source_space => :lab)
end
```

So you could take a black and white image and recolour it from dark brown to white with:

```ruby
mono = Vips::Image.new_from_file "some-mono-image.png"
dark_brown = [7.45, 4.3, 8]
white = [100, 0, 0]
rgb = mono.maplut(gradient(dark_brown, white))
```

If you want to paint a gradient across an image, you'd use `xyz` to make an index image, then colour that with the gradient.

**Comment by jcupitt** [comment]
Here's another example, this:

```ruby
require 'vips'

def gradient(start, stop)
    lut = Vips::Image.identity / 255
    lut = lut * start + (lut * -1 + 1) * stop
    lut.colourspace(:srgb, :source_space => :lab)
end

def circular_index(width, height)
    # xy image with 0 at the centre
    xy = Vips::Image.xyz(width, height) - [width / 2, height / 2]

    # diagonal size
    size = (width ** 2 + height ** 2) ** 0.5

    # so 0 - 1 circular image, with 1 at the edge and 0 at the centre
    (xy[0] ** 2 + xy[1] ** 2) ** 0.5
end 

red = [50, 100, 0]
green = [50, -100, 0]
rgb = circular_index(512, 512).maplut(gradient(red, green))

rgb.write_to_file("circ.png")
```

Generates this:

![circ](https://user-images.githubusercontent.com/580843/29720076-99bfe750-89b0-11e7-935f-9722592b1774.png)

Is that anything like what you need?

**Comment by jcupitt** [comment]
(Lua, PHP, and Python all work about the same, it doesn't need to be Ruby, fwiw)

**Comment by tariq1890** [comment]
Thanks so much.! I'll look over these. Very helpful :)l
