### ISSUE TITLE
Exclude dependencies (installing libvips with Homebrew)

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/libvips#719]
It looks like it's currently not possible to exclude GObject Introspection (`--without-gobject-introspection`), Python (`--without-python`) and PyGObject (`--without-pygobject3`) while installing libvips through `homebrew/core` because these dependencies don't have a `=> :recommended` tag (it's a `hard`-dependency currently).

I need to exclude these dependencies to make [pyvips](https://github.com/jcupitt/pyvips) run on OS X (see my Travis OS X attempt [here](https://github.com/kleisauke/pyvips/tree/improve-travis)).

A simple way to reproduce this:
```bash
# install optional add-ons for libvips
brew install cfitsio libmatio

# install libvips
brew install vips \
  --env=std \
  --with-imagemagick \
  --with-mozjpeg \
  --with-openexr \
  --with-openslide \
  --with-webp \
  --without-python \
  --without-pygobject3 \
  --without-gobject-introspection
```

This will give these warnings:
```bash
Warning: vips: this formula has no --without-gobject-introspection option so it will be ignored!
Warning: vips: this formula has no --without-pygobject3 option so it will be ignored!
Warning: vips: this formula has no --without-python option so it will be ignored!
```

I don't understand why the `=> :recommended` tag was [removed](https://github.com/Homebrew/homebrew-core/blob/436f8829ea7895aaabf41e80666bde5bc3f189ce/Formula/vips.rb) (previously it was working with `homebrew/science`, I think). If we take (for example) a look at the [ImageMagick bottle](https://github.com/Homebrew/homebrew-core/blob/436f8829ea7895aaabf41e80666bde5bc3f189ce/Formula/graphicsmagick.rb) the only `hard`-dependency they have is `xz`. And the [GraphicsMagick bottle](https://github.com/Homebrew/homebrew-core/blob/436f8829ea7895aaabf41e80666bde5bc3f189ce/Formula/graphicsmagick.rb) don't have `hard`-dependencies. 

Tested with Travis see the [install script](https://github.com/kleisauke/pyvips/blob/ec8922925749ddb34d880d35476453a128bf9fbc/.travis/before-install.sh#L18-L34) and the [build log](https://travis-ci.org/kleisauke/pyvips/jobs/268885788#L1655-L1657).

(maybe I should report this issue at https://github.com/Homebrew/homebrew-core/, but I'm not sure)

**Comment by jcupitt** [comment]
The homebrew maintainer was keen to reomve as many options as possible. This way, the bottled version of the formula will work for as many people as possible, and not many will have to compile:

https://github.com/Homebrew/homebrew-core/pull/14300

I had to argue to not have IM as a hard dep.

Perhaps for 8.6 (due in September) we should start to deprecate the libvips Python binding and push people towards pyvips instead. Slimming down the list of dependencies for the homebrew vips package could be part of that.

**Comment by kleisauke** [comment]
Deprecating the libvips Python binding and forwarding people towards (the more powerful alternative) [pyvips](https://github.com/jcupitt/pyvips) instead seems like the best option. 

As far as I know, the Python binding for libvips is the only one that needs GObject Introspection (the [Ruby](https://github.com/jcupitt/ruby-vips) (since version `2.0.0`), [PHP](https://github.com/jcupitt/php-vips), and [Lua](https://github.com/jcupitt/lua-vips) bindings doesn't need it) so that could be removed from the Homebrew vips package as well.

I can not wait to test 8.6 (under very heavy load, as usual). The tests on our test environment (with `8.6.0-alpha1`) are going well (only a few problems were found in libvips as you may have noticed on the issue tracker).

**Comment by lovell** [comment]
In a somewhat-related move, I'd like to switch `fftw` and `poppler` to `:optional` as they are made available under a GPL licence.

I'm happy to submit a PR to homebrew-core with this change if there's no opposition here.

**Comment by jcupitt** [comment]
Is GPL compliance important on macOS? It's very rarely used on servers, just on dev desktops, so you wouldn't think it'd be an issue. But I'm happy for them to be made optional if it's important.

**Comment by jcupitt** [comment]
@kleisauke 8.6 now defaults the built-in Python binding to "off" and the docs point people towards pyvips. 

I'd like to keep the typelib generation on, since it is used by Vala.

**Comment by lovell** [comment]
@jcupitt The GPL concern is because the homebrew-installed `vips` package is used as the basis for pre-compiled OS X binaries generated by https://github.com/lovell/package-libvips-darwin/ used in *distributed* Electron-based apps.

**Comment by jcupitt** [comment]
Ah I hadn't realized. Sure, please go ahead then. Thanks for the explanation.

**Comment by lovell** [comment]
PR created to move `fftw` and `poppler` to `:recommended` at https://github.com/Homebrew/homebrew-core/pull/18576
