### ISSUE TITLE
High banding when converting Linear Gradient SVGs to PNG

### ISSUE THREAD

**Issue by tariq1890** [jcupitt/libvips#720]
Hello. I am trying to render an SVG into PNG. 

The command that I am using is vips copy. 

Here is the Linear Gradient SVG which I am trying to render.

```
<?xml version="1.0"?>
<!-- Generated by SVGo -->
<svg width="1920" height="1080"
     xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
<rect x="0" y="0" width="1920" height="1080" style="fill:url(#h)"/>
<title>Gradients</title>
<defs>
<linearGradient id="h" x1="0%" y1="0%" x2="100%" y2="0%">
<stop offset="10%" stop-color="rgb(0,0,0)" stop-opacity="0.70"/>
<stop offset="90%" stop-color="rgb(0,0,0)" stop-opacity="0.50"/>
</linearGradient>
</defs>
</svg>
```
I have also attached the resulting PNG for your reference.
![lgrad](https://user-images.githubusercontent.com/2658224/29760576-292e18d4-8b79-11e7-8da3-f80b34adf032.png)

**Comment by jcupitt** [comment]
Hello, if you look at the generated image, you'll see the pixels are all something like:

(0, 0, 0, 134)

With the 134 changing in steps on 1 left to right across the image. I think any banding you're seeing is just the limit of 8-bit rendering. I can see banding in inkscape as well, for example. 

libvips uses librsvg to render SVG images; librsvg renders to cairo surfaces; and cairo does not support more than 8 bits per channel. I think you're just at the limit of SVG.

You can generate floating point gradients with libvips. Would that help, or do you need SVG?

**Comment by jcupitt** [comment]
Oh, I guess you could blur the image generated by librsvg, that would remove the banding.

**Comment by tariq1890** [comment]
@jcupitt Thank you for your response. I believe you did tell me earlier about generating gradients through libvips directly. Is there any documentation or tutorial that would help me understand this better? I need to create customizable gradients with multiple color stops and also be able to change the opacity of the colors used.

**Comment by jcupitt** [comment]
It's quite easy, I think, you just combine `xyz` with the arithmetic operators. 

What platform are you using, and what languages are you familiar with? Python / Ruby / Lua on Windows / macOS / linux are the simplest. 

A linear left-to-right gradient is straightforward. Radial or angled are slightly harder.

**Comment by tariq1890** [comment]
I use Golang. There is a library call bimg which uses libvips in the background

**Comment by jcupitt** [comment]
I think bimg only exposes small parts of libvips, so you'd need to extend it to wrap the whole thing. Alternatively, you could use `system()` to execute a small program written in Python/Ruby/Lua.
