### ISSUE TITLE
Proper way to set Image dpi using pyvips

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#721]
Before pngsave or jpegsave I tried :
Image.set("xres", SomeDpiValue) 
Image.set("yres", SomeDpiValue)
and 
Image.xres = SomeDpiValue
Image.yres = SomeDpiValue

but not work.

**Comment by jcupitt** [comment]
Hello, images are cached and reused inside libvips, so you can't change them, you can only make new images. 

To change xres/yres, use copy:

```python
image = image.copy(xres=12, yres=13)
```

https://jcupitt.github.io/pyvips/vimage.html#pyvips.Image.copy

I'll add a note to the documentation about this.

**Comment by jindili** [comment]
It works!
