### ISSUE TITLE
Cut out portion of image with xyz() generated Mask returns black image

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#722]
using pyvips scripts to generate a black on white shape, and use the shape to cut out image loaded.
but the resulting image is all black.

here is the script

```python
import pyvips

Image = pyvips.Image.new_from_file("input.jpg")
print("Image: ", Image)

def triangle(size):
    index = pyvips.Image.xyz(size * 2, size * 2)
    index = index - [size, size]
    index = index.polar()
    triangle = (index[1] > 68) & (index[1] < 112)
    return triangle.shrink(2, 2).invert()

Mask = triangle(1000)
print("Mask Image: ", Mask)

output = Image + Mask
print("Output Image: ", output)
output.write_to_file("imageAdd_output_1.png")
```

and the input image
![input](https://user-images.githubusercontent.com/73845/29995939-8b3a3bae-9027-11e7-81bd-5cdec59c88b4.jpg)

the print output of the script:
('Image: ', <pyvips.Image 1000x1000 uchar, 3 bands, srgb>)
('Mask Image: ', <pyvips.Image 1000x1000 uchar, 1 bands, multiband>)
('Output Image: ', <pyvips.Image 1000x1000 ushort, 3 bands, srgb>)

expected result (screenshot from nip2)
![2017-09-02 21_45_37-_unsaved workspace - tab1 - nip2](https://user-images.githubusercontent.com/73845/29995974-3a9afb1a-9028-11e7-8bb8-00ac5358378b.png)

**Comment by jcupitt** [comment]
Hello, don't use `+` to mask out images, it's just adding the two images together.

What's happening is that you are adding two 8-bit images, so you get a 16-bit image. When you save as PNG, you save a 16-it PNG, but the range is wrong for a 16-bit PNG, so it looks very dark. If you turn up the brightness in your PNG viewer, you might be able to see the pixels.

An easy way to mask is to use `ifthenelse` with the mask as the condition image. For example:

```python
image = pyvips.Image.new_from_file("input.jpg")
mask = triangle(image.width)
result = mask.ifthenelse(255, triangles, blend=True)
```

See:

https://jcupitt.github.io/pyvips/vimage.html#pyvips.Image.ifthenelse

There are some notes on this in the "calling" section:

https://jcupitt.github.io/pyvips/intro.html#calling-libvips-operations

**Comment by jindili** [comment]
It works as expected, Thanks, John!
