### ISSUE TITLE
Image Pattern Fill with pyvips

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#723]
Want to do an Image Pattern Fill like this:
![2017-09-03 12_30_19-coreldraw 2017 64-bit - d__dev_tetvips_tetvips_rot45_shape cdr](https://user-images.githubusercontent.com/73845/30000599-10c67788-90a5-11e7-83d1-014ca58c792a.png)

the image used as the pattern is translated, rotated and scaled, then tiled to fill a specified rect area

can't find the proper function to do this, this one might close:
http://www.vips.ecs.soton.ac.uk/supported/7.42/doc/html/libvips/libvips-conversion.html#VIPS-EXTEND-REPEAT:CAPS
which has an option 
VIPS_EXTEND_REPEAT --- the image is tiled to fill the new area

but when use affine() in pyvips, it failed to accept the "extend" parameter.

**Comment by jcupitt** [comment]
Hello, you make complex operations by chaining the simple ones together. pyvips is demand-driven and streaming, so you can make huge intermediate images at no cost. 

I would load the overlay image, use replicate to tile to a large area, then rotate and cut out the bit you need. For example:

```
import pyvips

im = pyvips.Image.text("ABC", font="sans 64").invert()
im = im.embed(10, 10, im.width + 20, im.height + 20, extend="white")
# huge! but it doesn't matter
im = im.replicate(100000, 100000)
im = im.similarity(angle=30)
im = im.crop(im.width / 2 - 1000, im.height / 2 - 1000, 1000, 1000)

im.write_to_file("x.png")
```

**Comment by jindili** [comment]
It Works, Thanks, John!
