### ISSUE TITLE
The command `jpegsave` ignores settings

### ISSUE THREAD

**Issue by daaain** [jcupitt/libvips#725]
I had a bit of a head-scratcher trying to use the CLI, as it turns out for some reason the settings don't get passed on when using `jpegsave`, but things work when using `copy`.

I have the latest version installed this morning via Homebrew:

```
vips -v
vips-8.5.8-Tue Aug 29 10:02:35 BST 2017
```

This doesn't work:

```
vips jpegsave in.jpg out.jpg[Q=10,strip]
```

Results in a file `out.jpg[Q=10,strip]` with default settings.

This works:

```
vips copy in.jpg out.jpg[Q=10,strip]
```

Results in a file `out.jpg` with the chosen settings.

**Comment by jcupitt** [comment]
Hello, `jpegsave` uses the filename you give literally, it doesn't try to parse out arguments:

```
john@kiwi:~/pics$ vips jpegsave k2.jpg x.jpg[Q=100]
john@kiwi:~/pics$ echo x*
x.jpg[Q=100]
```

If you call the savers directly, you use the command-line switches:

```
john@kiwi:~/pics$ vips jpegsave
save image to jpeg file
usage:
   jpegsave in filename
where:
   in           - Image to save, input VipsImage
   filename     - Filename to save to, input gchararray
optional arguments:
   page-height  - Set page height for multipage save, input gint
			default: 0
			min: 0, max: 10000000
   Q            - Q factor, input gint
			default: 75
			min: 1, max: 100
... etc.
john@kiwi:~/pics$ vips jpegsave k2.jpg x.jpg --Q 90
```

It seems a bit odd at first. If you look at the types of the arguments maybe it's clearer:

```
$ vips jpegsave
save image to jpeg file
usage:
   jpegsave in filename
where:
   in           - Image to save, input VipsImage
   filename     - Filename to save to, input gchararray
```

So the input filename for `jpegsave` is an image, the filename to save to is a `gchararray`. For `copy`, it's:

```
john@kiwi:~/pics$ vips copy
copy an image
usage:
   copy in out
where:
   in           - Input image, input VipsImage
   out          - Output image, output VipsImage
```

They are both images.

When `vips` links up image arguments, it uses the string you pass to make the image, parsing out any [] as arguments. The output of `jpegsave` is just a string (the file to write to), so no parsing and building happens.

**Comment by daaain** [comment]
Ah right, I see now, thanks a lot for the thorough explanation!

I tried to use the argument as `-optimize-coding=true` first which errored out and then saw that arguments are not shown in the `usage` line so I just ended up searching for some other solution and found the `copy` example.

Maybe it would be useful to include a hint about argument usage like below?

```
$ vips jpegsave
save image to jpeg file
usage:
   jpegsave in filename --argument1 argument1option
where:
...
```

Or alternatively giving a verbose example like:

```
$ vips jpegsave
save image to jpeg file
usage:
   jpegsave in filename
example:
   jpegsave in.png filename.jpg --Q 90 --optimize-coding --strip --quant-table 8 --interlace ...
...
```

**Comment by jcupitt** [comment]
The help text is generated automatically from introspection of the classes, so it couldn't really give an example. 

We could add something like:

```
usage:
   jpegsave in filename [--option-name option-value ...]
```

it might make it clearer. 

There's a chapter in the docs as well, you probably saw:

http://jcupitt.github.io/libvips/API/current/using-cli.html

**Comment by daaain** [comment]
That sounds perfect!

I did have a look at the docs, but the examples didn't cover my use case and the list of classes looked very intimidating 😸  so I just glossed over it (as users do)...

**Comment by jcupitt** [comment]
Git master goes this now:

```
john@kiwi:~/GIT/libvips (master)$ vips jpegsave
save image to jpeg file
usage:
   jpegsave in filename [--option-name option-value ...]
where:
   in           - Image to save, input VipsImage
   filename     - Filename to save to, input gchararray
optional arguments:
   page-height  - Set page height for multipage save, input gint
			default: 0
			min: 0, max: 10000000
   Q            - Q factor, input gint
			default: 75
			min: 1, max: 100
... etc.
```

I'll close. Thanks for the suggestion!
