### ISSUE TITLE
Error calling library function "im_text" on making text bitmap in nip2

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#726]
VIPS library error occur on making text bitmap in nip2

![2017-09-04 19_31_29-](https://user-images.githubusercontent.com/73845/30024881-61124ae2-91a8-11e7-89d6-0287682d8f28.jpg)

Error Screenshot:
![2017-09-04 19_31_48-](https://user-images.githubusercontent.com/73845/30024902-77bca5da-91a8-11e7-8c4e-1d35bfea2900.jpg)

Error Message:
Error calling library function "im_text" (generate text image).
VIPS library: VipsOperation: class "text" not found

You passed:
  text - "<i>Hello</i> world!"
  font - "Sans 12"
  width - 500
  alignment - 0
  dpi - 300

Usage:
CALL operator "im_text"
generate text image, from package "conversion"
"im_text" takes 5 arguments:
  text  - string
  font  - string
  width  - integer
  alignment  - integer
  dpi  - integer
And produces 1 result:
  out  - image
Flags:
  (PIO function) (no coordinate transformation) (area operation) (operation can be cached)

I use the vips-dev-w64-all-8.5.8.zip on the libvips github release channel and have vips.exe on the system path,  may be I miss some other dependencies needed.

**Comment by jcupitt** [comment]
Yes, the 32-bit nip2 Windows build is missing `text`, unfortunately. I've been trying to improve the build, I think 8.6 might have a working `text` in Windows nip2.

The 64-bit libvips DLL ought to work. Can you render text from `pyvips`?

**Comment by jindili** [comment]
I use 64-bit Python:
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
and 64 bit vips:
vips-dev-w64-all-8.5.8
and pyvips 2.0.3

pyvips Render Correctly.
