### ISSUE TITLE
pyvips.Image.text very slow on some windows machine

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#727]
**simple pyvips script to generate text image:**

```python
import pyvips

im = pyvips.Image.text("ABC", font="sans 64").invert()
im.write_to_file("text.png")
```

**Running Setups:**
Windows 7 64bit
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
vips-dev-w64-all-8.5.8
pyvips 2.0.3

The Same script run on another Win7 Machine with the same setup works all right, generate the text image instantly.

**Running Profile**
![2017-09-05 10_30_04-](https://user-images.githubusercontent.com/73845/30042686-652bdf44-9225-11e7-9b7f-d656b91b99be.jpg)

![2017-09-05 10_30_44-](https://user-images.githubusercontent.com/73845/30042691-6d49715a-9225-11e7-8f61-616655865f98.jpg)

**Comment by jcupitt** [comment]
Huh, how weird. 

Could you add some `print()` to `call` and try to see where the slow part is? It's quite a long method:

https://github.com/jcupitt/pyvips/blob/master/pyvips/voperation.py#L141

**Comment by jindili** [comment]
after adding some probe in call()

```python
print("start vips_cache_operation_build: ", time.asctime())
vop = vips_lib.vips_cache_operation_build(op.pointer)
print("end vips_cache_operation_build: ", time.asctime())
```

get:
start vips_cache_operation_build:  Wed Sep 06 10:11:08 2017
end vips_cache_operation_build:  Wed Sep 06 10:11:30 2017

this line is where the script slowed down that much.

**Comment by jcupitt** [comment]
So it sounds like startup time for the font rendering system.

libvips uses pango, which in turn uses fontconfig. fontconfig keeps a cache file of all the fonts on your system, so perhaps it's rebuilding the cache each time, or perhaps it's searching a network drive?

https://www.freedesktop.org/software/fontconfig/fontconfig-user.html#DEBUG

Try setting `FC_DEBUG` to 128. Perhaps it will print lots of stuff during the pause. You could try other values too.

**Comment by jindili** [comment]
I only found libfontconfig-1.dll in the /bin directory, where's the right place to set  FC_DEBUG value for debugging.

**Comment by jcupitt** [comment]
It's an environment variable, just set it before you start the program.

**Comment by jindili** [comment]
After a system restart, the env variable starts to take effect.

I see lots of 
...
 Scanning file C:/Windows/fonts/...done
 Scanning file C:/Windows/fonts/...done
 Scanning file C:/Windows/fonts/...done
...
which take the time.

But there are already fontconfig cache files in:
C:\Users\(UserName)\AppData\Local\fontconfig\cache

Are there some directions I can try to disable rebuilding the cache each time?

**Comment by jcupitt** [comment]
Is the cache being updated? Try this:

* check the "last modified" date and time on the cache file 
* try running pyvips text, and make sure it's trying to rebuild the cache
* once it finishes, check the "last modified" time on the cache again

If the time does not change, then fontconfig has regenerated the cache file, but not been able to update it. This would cause it to regenerate file file again the next time you run the program.

**Comment by jindili** [comment]
The cache is not updated. I'll try use a file system monitor to see whether pyvips write to the same location.

**Comment by jcupitt** [comment]
Could the cache file be locked somehow? Perhaps it was originally created by a program running as administrator?

**Comment by jindili** [comment]
Solve by removing existing fontconfig cache files in:
C:\Users(UserName)\AppData\Local\fontconfig\cache

**Comment by jcupitt** [comment]
Great!
