### ISSUE TITLE
win32 binaries?

### ISSUE THREAD

**Issue by sonoro1234** [jcupitt/libvips#728]
Hi,

I have downloaded vips-dev-w64-all-8.5.8.zip but there is not 32bits version.
Can I find it anywhere?

Thanks
victor bombi

**Comment by jcupitt** [comment]
Hello, I made some experimental 32-bit ones here:

http://www.rollthepotato.net/~john/vips-dev-w32-all.8.5.6-1.zip

I'm hoping to make them official for 8.6 (due in a few weeks). Please let me know if they work OK.

**Comment by sonoro1234** [comment]
I am trying to use lua-vips and the main problem is that all my binaries are compiled with gcc version 4.8.2 (i686-posix-dwarf, Built by MinGW-W64 project) and yours is sjlj instead of dwarf (and may be from the mingw project instead of mingw-w64 project ?)

**Comment by jcupitt** [comment]
The WIndows binaries are built on linux. The 64-bit ones with `x86_64-w64-mingw32-gcc-win32`, the 32-bit ones with `i686-w64-mingw32-gcc`. The build projects are here:

https://github.com/jcupitt/build-win32

https://github.com/jcupitt/build-win64

They use the standard MS ABI, so they should work with anything, I think. I downloaded luajit from luapower and I was able to use them under Wine, there are some notes here:

https://github.com/jcupitt/lua-vips#running-under-wine-windows-emulation-on-linux

**Comment by sonoro1234** [comment]
I could help in doing a cmake build by testing the windows build

**Comment by jcupitt** [comment]
It builds in a docker container, so you just need to install that, then "build 8.6" and it should do everything for you on any platform. Any patches to improve the process would be extremely welcome.

**Comment by jcupitt** [comment]
We're about to start making all the binaries for 8.6, so please open a new issue if there are problems with them.
