### ISSUE TITLE
On Windows, when creating a file, always set creation date

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#729]
Windows has a file attribute called "creation time". This should be set by programs when they create a file, or Windows might copy it from a previous file of the same name. See:

https://blogs.msdn.microsoft.com/oldnewthing/20050715-14/?p=34923/

From:

https://github.com/lovell/sharp/issues/901#issuecomment-327700166

**Comment by jcupitt** [comment]
Might be enough, I'll make a test win32 binary.

**Comment by jcupitt** [comment]
Test binary here:

https://github.com/jcupitt/libvips/releases/tag/v8.6.0-alpha2

But it's not enough, ctime is not updated. I'll try again.

**Comment by jcupitt** [comment]
Looks like you must call `SetFileTime()`:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms724933(v=vs.85).aspx

You can call it on the result of _wopen/_wopenf -- use _fileno to get the fd, then _get_osfhandle to get the HANDLE.

**Comment by jcupitt** [comment]
This might do it:

https://github.com/jcupitt/libvips/releases/download/v8.6.0-alpha3/vips-dev-w64-all-8.6.0-2.zip

If anyone could test (I don't have a win machine handy).

**Comment by jcupitt** [comment]
Current failing code here:

https://github.com/jcupitt/libvips/blob/reset-create/libvips/iofuncs/util.c#L547

It's in the `reset-create` branch, not master.

**Comment by jcupitt** [comment]
@dlong500 more details here.

**Comment by dlong500** [comment]
**EDITED**
Maybe it's because the `GetSystemTime()` function expects a pointer to a `SYSTEMTIME` structure rather than a `FILETIME`?

I notice there is also a [SystemTimeToFileTime()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724948(v=vs.85).aspx) function for conversion, and [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724205(v=vs.85).aspx) is a snippet for changing a file time to the current time (though that snippet appears to only change the modified time and leave the creation and access times the same, but it would appear trivial to change the code to use the same value for the other timestamps as well).

**Comment by jcupitt** [comment]
Oh good point, duh. 

I've pushed this change, I'll set another Windows binary building.

**Comment by jcupitt** [comment]
Here's another build:

https://github.com/jcupitt/libvips/releases/download/v8.6.0-alpha4/vips-dev-w64-all-8.6.0-3.zip

Maybe this time!

**Comment by dlong500** [comment]
Also, I'd still like to to some testing related to some other stuff myself, but I'm having problems building the library.  I'm following the steps on the [build-win64](https://github.com/jcupitt/build-win64) repo and using an Ubuntu 16.04 machine but it's failing to finish the docker build (I've tried several times).  Is there anything I'm missing?

I can open a new issue on the build-64 repo with more details, but I'd thought I'd see if you have any quick pointers.  I've posted the entire build output as a gist here:
https://gist.github.com/dlong500/cfaf1ffa937783ba52fb799f184446a2

**Comment by jcupitt** [comment]
I've not actually tried 8.6 in docker, I've been building on 17.04, it's obviously got a couple of things wrong. 

8.5 is the one that's built regularly in the container.

**Comment by dlong500** [comment]
Actually it was 8.5 I tried first and then 8.4 with the same errors.  I figured the 8.6 branch might be unstable so I was just trying to get the basic build working first.  There are a lot of messages seemingly related to permission problems but I was building as root.

**Comment by jcupitt** [comment]
Oh dear, sorry. I'll have a look tomorrow.

**Comment by dlong500** [comment]
Just FYI I tried installing the latest version of Docker (via their own apt repo as shown on their [installation docs](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository) and it's still failing to complete with some types of permission issues.  If you want we can move this discussion to a new issue on the build-win64 repo.

**Comment by jcupitt** [comment]
Yes, could you open an issue on the build64 repo?

**Comment by jcupitt** [comment]
OK, set all three times and merged to master. I'll close.

**Comment by jcupitt** [comment]
And thank for working on this issue! I'll add your name to the ChangeLog.

**Comment by dlong500** [comment]
Great!  Thanks.  I'll open an issue on the build64 repo for the build problems I'm having.
