### ISSUE TITLE
magickload memory and Python bindings

### ISSUE THREAD

**Issue by gdunstone** [jcupitt/libvips#731]
vips_magickload doesn't seem to free memory or delete temporary files when objects go out of scope, only when shutdown occurs.

I think this might be a duplicate of https://github.com/jcupitt/libvips/issues/604

I'm using the python bindings for 8.6.0

Behaviour: vips/magick creates a temporary file when an image is opened, and doesn't free the memory/delete the tempfile even when the object goes out of scope/is explicitly deleted.

Expected behaviour: vips/magick creates a temporary file when an image is opened, and deletes the tempfile when the object is deleted/goes out of scope.

To reproduce (in Python):

```
import os
os.environ['MAGICK_AREA_LIMIT'] = "100MB"
os.environ['MAGICK_TEMPORARY_PATH'] = "."
os.environ['MAGICK_TMPDIR'] = "."

from gi.repository import Vips

im = Vips.Image.magickload("image1.cr2")
del im
im = Vips.Image.magickload("image2.cr2")
del im
im = Vips.Image.magickload("image3.cr2")
del im
# there are now 3 tempfiles when there should be 0
```

Is there some way I can tell imagemagick through vips to free its memory? Currently I'm just deleting tempfiles on return from any function that uses magickload. A stopgap would be being able to explicity free the memory allocated by magickload

**Comment by jcupitt** [comment]
Hello, I see slightly different behaviour. With this program:

```python
import os
import time

os.environ['MAGICK_AREA_LIMIT'] = "100MB"
os.environ['MAGICK_TEMPORARY_PATH'] = "."
os.environ['MAGICK_TMPDIR'] = "."

import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

im = Vips.Image.magickload("65346_02_rg830_02.CR2")
print('loaded ...')
time.sleep(5)
del im
print('deleted ...')
time.sleep(5)
```

If I watch the directory, I see five magick temp files during the load, but then once that returns, they are removed. 

```
john@kiwi:~/pics/x$ python vips.py & 
[1] 22618
john@kiwi:~/pics/x$ ls
65346_02_rg830_02.CR2         magick-22618ppxVIDV9DkMz  pyvips.py
magick-22618nrAGVfzFQOeH      magick-22618wV7VqlKKAQjs  vips.py
magick-22618nrAGVfzFQOeH.png  magick-22618zrCzvbbB7iHO
john@kiwi:~/pics/x$ loaded ...
ls
65346_02_rg830_02.CR2  pyvips.py  vips.py
john@kiwi:~/pics/x$ deleted ...
```

What platform and magick are you using? I'm ImageMagick 6.9.7-4 on Ubuntu.

**Comment by jcupitt** [comment]
It could be the vips operation cache. I've tried disabling it for magickload, it might help. Would you be able to test against git master?

**Comment by gdunstone** [comment]
I can do the test against git master on monday.

I'm using ImageMagick 6.9.9-9 on Archlinux.

**Comment by gdunstone** [comment]
I got a little further. 

The git version now does clean up those temporary files if you magickload multiple images in a row.

If you do any operations on them (including writing out), the temp files remain. It does now look like the vips operation cache.

Ill have a play around with that and see where it gets me.

**Comment by jcupitt** [comment]
You can turn the cache off for everything with:

```python
Vips.cache_set_max(0)
```

ie. cache zero operations. If you're doing (fairly) simple operations on many files (rather than something complex on one file), the cache might not be helping performance much anyway.

**Comment by gdunstone** [comment]
I played around with it a bit and got vips to do what I want (not cache so many ops that it eats every available byte. I chose a number, its fast enough).

The problem seems to me to be that while the operation cache counter is incremented when magickload is used (and operations happen), the memory cache counter is not incremented and remains at 0, despite the actual memory usage.

I think that vips will do 1000 ops (270mb/op for me, including write_to_file) before hitting that cache limit. Ofc this hits some physical hardware limits way before it hits the operation cache limit. I did notice that when not using magickload, the memory cache counter is incremented appropriately and it handles the cache as expected.

The main question is: should magickloaded images and their operations increment the vips memory cache counter or not? I think it should but I'm dont know how that would be implemented or whether its in development goals for vips.

Now that I know how to limit the operation cache to a reasonable value for my usage, its not as critical a bug for me. My issue has been resolved, I just want to make sure if there is an actual bug with tracking memory for magickloaded images, that it is fixed for future users (and I'd rather not have to disable caches).

You can close this issue if it fits your best judgement to do so. I will remain available to help either way. 

Lastly, thanks for making the best image processing library.

**Comment by jcupitt** [comment]
Hi again, I'm gad it's mostly working for you now, I'll close.

The memory limit is for memory used by libvips, it doesn't include memory allocated by external libraries. I don't think IM has any way to feed that back, unfortunately. Perhaps the docs should include a note on this. 

It's the same for the file descriptor limit: it only includes resources allocated by libvips.

**Comment by jcupitt** [comment]
Note added here: https://github.com/jcupitt/libvips/commit/906dc504623bc837f1d7e6d2795e54146408d9da
