### ISSUE TITLE
vips_check_coding issue on Debian 8 

### ISSUE THREAD

**Issue by eichstaedtk** [jcupitt/libvips#733]
Hi There, i wrote a java warpper for livips using the library for a IIIF project. On Windows 7 the java service is running without any errors but on Debian Linux 8 the vips crached with the following error: 

 A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f4df0f5e660, pid=12065, tid=0x00007f4db6fe5700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libvips.so+0x152660]  vips_check_coding_known+0x0
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

Vips Version 8.6.0.2
Java 8 
Framework Spring Boot 
Mapping JNA 

Can you please help ?

**Comment by jcupitt** [comment]
Hi @eichstaedtk, that's very impressive!

Sorry, I don't know what could be causing the error. A bad pointer, I guess? If you can build libvips with the "-g" flag, you should be able to run in a debugger and see all the variables. Something like:

```
cd vips-x.y.x
CFLAGS=-g CXXFLAGS=-g ./configure --prefix=/my/install/prefix
make
make install
```

If you can put a copy of your binding on github, I could have a look, if you like. You will need to include some instructions on setting up the development environment -- I've not used Java for a long time.

If it's confidential, I could create a private repository and set you as a collaborator, which I think should allow you to upload it without sharing it.

**Comment by eichstaedtk** [comment]
Hi @jcupitt , Many Thanks I solved my issue. But know I have a running application which will faile after 200 request using jmeter with i guess outOfMemory or something like this. I'am not sure why but maybe I can upload my code and you have any hint for me. 

Many Thanks , Best regards Konrad
