### ISSUE TITLE
8-bit PNG Support

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/libvips#734]
It would be great if libvips had support for saving 8-bit palette based PNG with alpha transparency which are a great choice for saving small images with transparency on the web.

More info: [pngquant](https://pngquant.org)

From my limited understanding this would require the following changes:

* Add a good quantizer algorithm to reduce from RGBA to 8-bit indexed-color (eg. [libimagequant](https://github.com/ImageOptim/libimagequant))
* Add support for writing to PNG8 format with the proper tRNS-Chunk

Note that there are two ways to store transparency in 8-bit PNG:

* Mark a single color as transparent
* Store a transparency value for each color in the index (so eg. if you have 256 colors in the index, you have 256 transparency values in the same order that specify the transparency for the color)

I think only the latter is useful and makes sense to implement.

Here's some info on the tRNS chunk from libpng:

* [png_get_tRNS](http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Desktop-generic/LSB-Desktop-generic/libpng12.png.get.trns.1.html)

There is similar discussion in #620 regarding gifsave support.

One approach to make it simpler to integrate could be to move the quantization logic into a custom saver like png8save which accepts RGBA data and then does the quantization internally.

**Comment by jcupitt** [comment]
Sure, sounds useful.

**Comment by lovell** [comment]
Dennis Ranke recently updated and improved his MIT-licensed "exoquant" quantiser to use k-means clustering.

https://github.com/exoticorn/exoquant-rs

It is now written in Rust, not a bad thing where security is concerned (librsvg is currently undergoing a rewrite in Rust too), but another layer of tooling to consider.

There's an example, again in Rust, of using it with lodepng at https://github.com/exoticorn/pngeq/blob/master/src/main.rs

**Comment by fangqiao** [comment]
Any plan to implement this? 

I am still testing libvips. One test case is that I use libvips to resize a palette based png, blend it with a four channel png, and then save it using libvips' output api, the output file size tripled. Ideally, when processing an image, the output should be encoded the same way.

**Comment by fangqiao** [comment]
@jcupitt  do you mean this ? How to set format/quality to save as palette based png ? I can run a test. I just haven't tried libMagic before and don't know how to set the options.

```
/**
 * vips_magicksave: (method)
 * @in: image to save 
 * @filename: file to write to 
 * @...: %NULL-terminated list of optional named arguments
 *
 * Optional arguments:
 *
 * * @quality: %gint, quality factor
 * * @format: %gchararray, format to save as
 *
 * Write an image using libMagick.
 *
 * Use @quality to set the quality factor. Default 0.
 *
 * Use @format to explicitly set the save format, for example, "BMP". Otherwise
 * the format is guessed from the filename suffix.
 *
 * See also: vips_magicksave_buffer(), vips_magickload().
 *
 * Returns: 0 on success, -1 on error.
 */
int
vips_magicksave( VipsImage *in, const char *filename, ... )
{
	va_list ap;
	int result;

	va_start( ap, filename );
	result = vips_call_split( "magicksave", ap, in, filename );
	va_end( ap );

	return( result );
}
```

**Comment by felixbuenemann** [comment]
Setting format to "PNG8" should do the trick (untested).

**Comment by fangqiao** [comment]
Checked foreign.h of 8.6.3. this function vips_magicksave isn't there. Is it only avaible at 8.7?

**Comment by jcupitt** [comment]
Yes, it's an unfinished feature of 8.7. Development is being tracked here: https://github.com/jcupitt/libvips/issues/839

**Comment by jcupitt** [comment]
It seems to work with git master libvips:

```
$ ls -l nike.png
-rw-rw-r-- 1 john john 12232 Apr 11 12:31 nike.png
$ vips magicksave nike.png x.png --format=PNG8
$ ls -l x.png 
-rw-r--r-- 1 john john 2982 Apr 24 15:15 x.png
```

It works on colour photos too, but it looks like it simply makes a 3:3:2 colourcube and does no dithering, so it looks pretty terrible.

**Comment by fangqiao** [comment]
Thanks for following up. 

I did some test run with pngquant and found out its quality is very good and the library libimagequant is also pretty easy to use. I decided to go with  libimagequant.

**Comment by felixbuenemann** [comment]
@jcupitt Would you accept a pull request that adds optional 8-Bit support using libimagequant directly to pngsave?

It is not as nice as having true 8-bit/indexed image support in vips, but a lot easier to implement.

**Comment by jcupitt** [comment]
Sure, that would be great Felix!

**Comment by felixbuenemann** [comment]
For anyone interested, I've started working on PNG8 support using libimagequant this past weekend and pushed my WIP branch to https://github.com/felixbuenemann/libvips/tree/8bit-png-quantization-support.

It already works with RGB and RGBA source images with 8-Bit per channel.

It still requires some refactoring, memory usage optimizations and tweaks to support grayscale and 16-Bit per channel images.

If you want to try it out, you need to have the latest [libimagequant](https://github.com/ImageOptim/libimagequant) 2.12.1 shared library installed, so configure can detect it using pkg-config.

If everything is set-up you can try it out using `vips copy`:

```
vips copy tux.png tux_8bpp.png'[colors=256,Q=90,compression=9,filter=none]'
```

Comparison with `magicksave --format=PNG8`:

**Original:** (41 KB)
![tux](https://user-images.githubusercontent.com/909587/41255217-16003a28-6dc6-11e8-87ee-d25b37c7e440.png)

**8-Bit w/Alpha (pngsave, Q=90):** (20 KB)
![tux_8bpp](https://user-images.githubusercontent.com/909587/41255330-7669521e-6dc6-11e8-8084-5397ebf8a50e.png)

**8-Bit w/Alpha (pngsave, Q=1):** (11 KB)
![tux_q1_8bpp](https://user-images.githubusercontent.com/909587/41255400-b1657e10-6dc6-11e8-88ce-877cce8f47c4.png)

**8-Bit w/Alpha (magicksave):** (11 KB)
![tux_im_8bpp](https://user-images.githubusercontent.com/909587/41255423-c81e222e-6dc6-11e8-9896-87dba48facd5.png)

**Comment by felixbuenemann** [comment]
To be fair it is certainly possible to write good-looking PNG8+Alpha files with ImageMagick, but it requires a few more tweaks:

```
convert tux.png -dither FloydSteinberg -colors 128 -type palettealpha tux_im_dither_8bpp.png
```

**8-Bit w/Palette-Alpha (im7 convert):** (22 KB, 127 colors)
![tux_im_dither_8bpp](https://user-images.githubusercontent.com/909587/41257043-bfe53f0c-6dcb-11e8-9cd6-8e5f46e9a2b4.png)

**Comment by jcupitt** [comment]
That's great Felix!

I was thinking about this last night and perhaps the best solution might be to add indexed images to libvips. It would actually be quite easy: we have a header field called `coding` which indicates pixel coding type (for example, `rad`, meaning Radiance 32-bit RGB), so all we need to do is add a new type called maybe `indexed` and attach a LUT which maps pixel values to RGB or RGBA or whatever.

We'd need a pair of operations to turn indexed -> RGB (easy) and RGB -> indexed (hard, but what you've done), then GIF, TIFF and PNG load and save would need to be able to read and write these new indexed images.

**Comment by jcupitt** [comment]
Sorry, I didn't mean to head off at a tangent. It's much better to be pragmatic.

In the short term, let's fix up and merge your nice pngsave improvement. In the longer term (and in a separate issue), think about generalizing this into proper support for indexed images.

**Comment by jcupitt** [comment]
Yes, that was my thought too. There's already API to attach one image to another, we'd just need to make a tiny wrapper. There's also a system to automatically unpack images for operations that need to access actual pixel values (eg. resize), but leave them coded for crop, flip etc. so we can just use that.

nip2 has an interesting optimisation: any time you do an arithmetic operation (eg. *2, cos, etc.) on a uchar or ushort image, it leaves the image alone, attaches a linear LUT, and does the operation just on that. You can evaluate quite complex expressions without touching the actual pixels at all. It wouldn't be too hard to push this down into libvips. As you say, indexed images could use it too.

**Comment by felixbuenemann** [comment]
I've polished up my code and refactored it so that the quantization code should be easy to reuse among writers and can be swapped out for different implementations. See PR #1009 for details.

**Comment by CanadianHusky** [comment]
Hello,
Is there an update on 8 bit PNG output directly in Libvips, not with Magicksave ?

This command does nothing. The output is still 24bit.

`vipsimg.Pngsave("C:\temp\vips_8bit.png", compression:=75, interlace:=False, profile:=Nothing, filter:=Nothing, palette:=True, colours:=250, q:=20)
`

The documentation at http://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-pngsave make it sound like 8bit is implemented 'max number of palette colours for quantisation'

GraphicsMagick is much faster then MagickSave and ImageMagick, and for MagickSave to work, the extended libvips library must be used anyways, so I have to stick to GraphicsMagick for 8bit output if it does not exist in libvips.
Thank you

**Comment by felixbuenemann** [comment]
It is already implemented, but you need to compile libvips against libimagequant to use it.

**Comment by CanadianHusky** [comment]
Thank you for the explanation. 
I use the Nuget Package with the Netvips binding that @kleisauke prepared. Maybe he can comment if there is a Nuget Package that is precompiled because my personal C/C++ knowledge is not sufficient to do that

**Comment by kleisauke** [comment]
@CanadianHusky See https://github.com/kleisauke/libvips-packaging/issues/2#issuecomment-583392448 for the reason why this isn't included within the pre-built binaries.

**Comment by CanadianHusky** [comment]
Understood. thank you

**Comment by sergeevabc** [comment]
Windows 7 x64 user here, with VIPS 8.15.1.

Trying out the commands mentioned here earlier.

``` console
$ vips magicksave in.png out.png
magicksave: libMagick error: NoEncodeDelegateForThisImageFormat `' @ error/constitute.c/WriteImage/1302
```

I have ImageMagick in PATH, can execute magick.exe in.png out.png. Hmm.

``` console
$ vips copy in.png out.png'[colors=256,Q=90,compression=9,filter=none]'
VipsForeignSave: "out.png'[colors=256,Q=90,compression=9,filter=none]'" is not a known file format

$ vips copy in.png out.png[colors=256,Q=90,compression=9,filter=none]
pngsave_target: no property named `colors'
```

Aggrrhh.

**Comment by jcupitt** [comment]
Hi @sergeevabc,

> pngsave_target: no property named `colors'

libvips uses UK spelling, so it's "colours".

> ```
> vips pngsave in.png out.png --palette --effort=10
> ```
> Hope these are the settings for the best possible png32->png8?

Yes, that should work OK. The best settings depend on the image (photo, line art, etc.), so it can vary a bit. You could try experimenting with the filter settings, or in some cases reducing the size of the palette.

**Comment by sergeevabc** [comment]
> You could try experimenting with … reducing the size of the palette.

As I understand it, there is no way to set the max colours limit of the palette here, so I have to play with --Q parameter? I tried --Q 90 and it generated the same palette as 100, but 80 reduced it almost by half.

**Comment by jcupitt** [comment]
> As I understand it, there is no way to set the max colours limit of the palette here, 

Due to the way PNG works, you have to set the max colours with `bitdepth`. So:

```
$ vips copy nipguide.pdf x8.png[palette,effort=10]
$ vips copy nipguide.pdf x2.png[palette,bitdepth=2,effort=10]
$ ls -l x* 
-rw-r--r-- 1 john john    2698 Jan 14 10:05 x2.png
-rw-r--r-- 1 john john    8179 Jan 14 10:05 x8.png
```

That's just some back and white text, so 2 bits is enough:

![x2](https://github.com/libvips/libvips/assets/580843/15b313c2-0607-429c-9d7f-1995f391ad03)

You can see all the options if you run the saver with no arguments (you probably know):

```
$ vips pngsave
save image to png file
usage:
   pngsave in filename [--option-name option-value ...]
where:
   in           - Image to save, input VipsImage
   filename     - Filename to save to, input gchararray
optional arguments:
   compression  - Compression factor, input gint
			default: 6
			min: 0, max: 9
   interlace    - Interlace image, input gboolean
			default: false
   filter       - libpng row filter flag(s), input VipsForeignPngFilter
			default flags: none
			allowed flags: none, sub, up, avg, paeth, all
   palette      - Quantise to 8bpp palette, input gboolean
			default: false
   Q            - Quantisation quality, input gint
			default: 100
			min: 0, max: 100
   dither       - Amount of dithering, input gdouble
			default: 1
			min: 0, max: 1
   bitdepth     - Write as a 1, 2, 4, 8 or 16 bit image, input gint
			default: 8
			min: 1, max: 16
   effort       - Quantisation CPU effort, input gint
			default: 7
			min: 1, max: 10
   keep         - Which metadata to retain, input VipsForeignKeep
			default flags: exif:xmp:iptc:icc:other:all
			allowed flags: none, exif, xmp, iptc, icc, other, all
   background   - Background value, input VipsArrayDouble
   page-height  - Set page height for multipage save, input gint
			default: 0
			min: 0, max: 10000000
   profile      - Filename of ICC profile to embed, input gchararray
operation flags: sequential nocache 
```

**Comment by jcupitt** [comment]
`Q` set the quality factor for dithering, so high Q will set a finer dither pattern.
