### ISSUE TITLE
run pyvips test suite in travis on commit

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/libvips#742]
libvips no longer has the Python test suite built in, so Travis is currently running rather a small set of tests on each commit.

After building libvips, Travis should clone pyvips and run the test-suite in that.

**Comment by felixbuenemann** [comment]
I have this working in https://github.com/felixbuenemann/libvips/tree/run-pyvips-on-travis-ci.

I'm currently still wrangling with getting the macOS build fully working, will submit a PR once it's ready.
