### ISSUE TITLE
vips_jpegsave_buffer not saving progressive jpegs

### ISSUE THREAD

**Issue by ismikhail** [jcupitt/libvips#744]
Hi,

I am trying to save a jpeg with the "interlace" option set to TRUE. It works great with vips_jpegsave and I see it in the image header. However when I try to use vips_jpegsave_buffer it doesn't seem to have any effect. After writing the buffer to a file, MD5 returns the same hash regardless whether the "interlace" is set or not.

I'm running vips-8.5.8.

**Comment by jcupitt** [comment]
Hello, it seems to be working for me in master. I see:

```
john@kiwi:~/pics$ vips copy k2.jpg x.jpg
john@kiwi:~/pics$ vips copy k2.jpg x2.jpg[interlace]
john@kiwi:~/pics$ ls -l x* 
-rw-r--r-- 1 john john 260687 Sep 20 11:11 x2.jpg
-rw-r--r-- 1 john john 271853 Sep 20 11:11 x.jpg
john@kiwi:~/pics$ vips jpegsave_buffer k2.jpg 
VIPS_TYPE_BLOB, data = 0x5639fb8ccb00, length = 271853
john@kiwi:~/pics$ vips jpegsave_buffer k2.jpg --interlace
VIPS_TYPE_BLOB, data = 0x557a9232de00, length = 260687
```

I'll try in 8.5.

**Comment by jcupitt** [comment]
8.5 seems to work too. I tried Ruby:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.new_from_file "k2.jpg"
=> #<Image 1450x2048 uchar, 3 bands, srgb>
irb(main):003:0> (x.write_to_buffer ".jpg").length
=> 271853
irb(main):004:0> (x.write_to_buffer ".jpg", interlace: true).length
=> 260687
irb(main):005:0> Vips::LIBRARY_VERSION
=> "8.5.9-Wed Sep 20 11:13:40 BST 2017"
```

Could you post some sample code to show the error?

**Comment by ismikhail** [comment]
I followed your steps and it worked for me as well. I'll check my code again -- there must be a bug on my end. Thanks for checking!

**Comment by jcupitt** [comment]
It could be a bug somewhere in the chain. What platform and language are you using?

**Comment by ismikhail** [comment]
I use the C API. I found the issue in my code. It was a missing break statement in my switch case which basically resulted in vips_jpegsave_buffer being called twice -- once with the interlace set and then again without it. Embarrassing I know. It's safe to close this issue.
