### ISSUE TITLE
vipsheader with .psb performance

### ISSUE THREAD

**Issue by bender22** [jcupitt/libvips#745]
Hi John!

I'm experiencing strange behavior with using vipsheader.exe with psb file. First, It takes much more time than with other formats, but I think that's specific of psb and the library which vips is using (correct me if I'm wrong).
Second and more interesting: when I run command "vips-dev-8.3/bin/vipsheader.exe" "myfile.psb" it takes ~7 seconds.
But if I run it with parameter "vips-dev-8.3/bin/vipsheader.exe" -f width "myfile.psb"it takes ~28 seconds! 
I'm playing with 450Mb file (http://sources.smartinmedia.com/93f2f3d2-87a5-4263-9159-c132e70f616c.zip). 
Could you check this performance issue? Where can I see the code for output formatting in case I decide to parse it?

**Comment by jcupitt** [comment]
Hello @bender22,

psb load is handled by imagemagick, (`vips_magickload()`) so you're mostly just seeing IM behaviour here. 

I'm not sure why `-f` is slower than a full header get, I'll have a look.

**Comment by jcupitt** [comment]
I tried on my laptop. I see:

```
$ time vipsheader bender22.psb 
bender22.psb: 27725x6501 uchar, 3 bands, srgb, magickload

real	1m0.011s
user	0m6.328s
sys	0m5.168s
$ time vipsheader bender22.psb 
bender22.psb: 27725x6501 uchar, 3 bands, srgb, magickload

real	1m3.857s
user	0m6.084s
sys	0m5.116s
$ time vipsheader -f width bender22.psb
27725

real	1m0.114s
user	0m6.024s
sys	0m4.688s
$ time vipsheader -f width bender22.psb
27725

real	0m52.228s
user	0m6.264s
sys	0m4.644s
```

So it varies a bit, but it's always around a minute (for me).

The reason it's so slow is that IM has separate calls for getting an image header, and for reading an image in. You can call `PingImage()` to just quickly get some of the header fields (this is what `identify` uses), or you can use `ReadImage()` to get the whole header and all the pixels.

Unfortunately, some important header fields change value between Ping and Read. This breaks libvips, which assumes that header fields don't change value. So libvips is forced to always use `ReadImage()`, and read the entire image in.

I think I would use the imagemagick `identify` command to quickly get some header fields, then use vips later for conversion.

With identify, I see:

```
$ time identify bender22.psb 
bender22.psb PSD 27725x6501 27725x6501+0+0 8-bit sRGB 475.4MB 0.370u 0:00.370

real	0m0.387s
user	0m0.372s
sys	0m0.004s
```

So just 0.4s.

**Comment by jcupitt** [comment]
A bug I posted about this issue:

http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=20017

So with imagemagick, it's not possible to reliably get the number of image channels with identify.

I tried again recently and it was still broken. Perhaps it's fixed now.

**Comment by bender22** [comment]
Thanks for the explanation! I'll close it then
