### ISSUE TITLE
Blurry image when scaling up SVGs

### ISSUE THREAD

**Issue by brewin** [jcupitt/libvips#746]
`vips resize input.svg output.png 4` generates a blurry image. It seems to be rasterizing first and then scaling it up. If it scaled up first, then rasterized, it would not be blurry.

**Comment by jcupitt** [comment]
Hello, `resize` is a raster resizer, so it takes whatever raster SVG load makes and upsizes it. 

If you want to make a larger SVG, you need to ask the SVG loader to make a larger raster in the first place. You can scale SVG images by setting the DPI (the default is 72), or by setting a scale factor.

For example:

```
john@kiwi:~/pics$ vips copy logo.svg x.png
john@kiwi:~/pics$ vipsheader x.png
x.png: 736x552 uchar, 4 bands, srgb, pngload
john@kiwi:~/pics$ vips copy logo.svg[scale=4] x.png
john@kiwi:~/pics$ vipsheader x.png
x.png: 2944x2208 uchar, 4 bands, srgb, pngload
john@kiwi:~/pics$ vips copy logo.svg[dpi=300] x.png
john@kiwi:~/pics$ vipsheader x.png
x.png: 3066x2300 uchar, 4 bands, srgb, pngload
```

The docs for `vips_svgload()` have the details:

http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-svgload

**Comment by brewin** [comment]
Thanks! I didn't see any examples showing options passed on load, so I just assumed that only worked for saving.
