### ISSUE TITLE
Question: VIPS_INIT should be used or not ?

### ISSUE THREAD

**Issue by yaourt** [jcupitt/libvips#747]
I would to thank you for this great library !

I noticed something in the documentation that is not completely consistent:

In the documentation, there : http://jcupitt.github.io/libvips/API/current/libvips-vips.html#VIPS-INIT:CAPS , it is stated:

> VIPS_INIT is deprecated and should not be used in newly-written code.

but is it not clear what should be used instead ...

And if VIPS_INIT should not be used eventually, then this part of the documentation should also be updated:

http://jcupitt.github.io/libvips/API/current/using-from-c.html

> Library startup
>    When your program starts, use VIPS_INIT() to start up the VIPS library ...

**Comment by jcupitt** [comment]
Hello, the "deprecated" warning is generated automatically and I've no idea why :( I've filed a bug about this, but it's not resolved yet.

Anyway, it's NOT deprecated and you should use it.

**Comment by jcupitt** [comment]
I've added a note to the `VIPS_INIT` docs apologizing for the deprecation note. Thanks for pointing this out.

**Comment by yaourt** [comment]
Loud & clear !

Thanks
