### ISSUE TITLE
dzsave with psb file - only white tiles as a result

### ISSUE THREAD

**Issue by yurykovshov** [jcupitt/libvips#750]
Hi John,

I have some issue with PSB file, which is around 6Gb. When I tile it (with dzsave) I get a totally white pyramid (white tiles) (total size of the pyramid ~60Mb). It seems that only the base layer of psb is tiled. 
This PSB file was made with Kolor Autopano Giga and then edited in Photoshop.

Initial file is [here](https://easyzoom.blob.core.windows.net/share/2a52a75f-7808-47a4-895c-6547c9fd3653.psb) (6gb)
The result viewable & downloadable is [here](https://easyzoom.com/imageaccess/bb19bcfdd4a74b87ab09a57b2573f837)

Any ideas how I can proceed in order to find out why it's white?

Best, 
Yury

**Comment by yurykovshov** [comment]
I ran avg on PSB:
```
PS D:\vipsbin> .\vips.exe avg .\psb\panorama.psb
255.000000
```
Does it mean that vips see it as white?

**Comment by jcupitt** [comment]
Hello Yury, I tried here and it worked for me on Linux. 

libvips uses ImageMagick to load PSB files, so perhaps the ImageMagick that ships with the Windows libvips has been configured to disallow images this large. 

Have a look at `vips-dev-8.5/etc/ImageMagick-6/policy.xml` and try changing the settings. I have:

```
  <policy domain="resource" name="memory" value="4GiB"/>
  <policy domain="resource" name="map" value="4GiB"/>
  <policy domain="resource" name="width" value="500KP"/>
  <policy domain="resource" name="height" value="500KP"/>
  <policy domain="resource" name="area" value="20GiB"/>
  <policy domain="resource" name="disk" value="20GiB"/>
```

And then run the conversion again.

**Comment by jcupitt** [comment]
That's for my laptop, of course, you might want higher settings on a server.

**Comment by yurykovshov** [comment]
Can't make it work so far... I will postpone it because the workaround with conversion to TIF works. You may close or leave it.
