### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [jcupitt/libvips#761]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “VImage::call_option_string”](https://github.com/jcupitt/libvips/blob/39ea6ce49247fcc43245aa97025b8c647feaec62/cplusplus/VImage.cpp#L458 "VImage::call_option_string function").

**Comment by jcupitt** [comment]
Line 468? I guess that's true. Thanks!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/jcupitt/libvips/commit/d601c5ee197380f188088f0143f0f496303f0f43 "Remove extra null check").

**Comment by jcupitt** [comment]
Oh no problem, thank you for pointing out this dumbness.
