### ISSUE TITLE
_setmaxstdio as 2048 

### ISSUE THREAD

**Issue by zarlior** [jcupitt/libvips#762]
Hi,

I saw you use the _setmaxstdio to 2048 on vips_init as part of issue #677(High memory usage when using vip).

I there any chance you can make the 2048 a parameter?
I tested a standalone application on my Win 7 and it can go up to 8192.
I ran the following code from https://msdn.microsoft.com/en-us/library/xt874334.aspx
with 8192 and the output was 8192.
I also tried to load 8189 files simultaneously and it worked (it has to be 8192-3 because of stdin\stdout\stderr).

Also, I would be more than happy to test it if you could compile a test version for me...

Thanks,
Lior.

**Comment by jcupitt** [comment]
Hello, are you sure you can get over 2048? This seems to say that the 2048 is a hard limit:

https://msdn.microsoft.com/en-us/library/6e3b887c.aspx

_Because stdio-level functions, such as fopen, are built on top of the lowio functions, the maximum of 2,048 is a hard upper limit for the number of simultaneously open files accessed through the C run-time library._

https://stackoverflow.com/questions/1803552/setmaxstdio-max-open-files-is-2048-only

Seems to say that the 2048 limit applies to `_wopen` and friends. 

Why do you need a higher number? Perhaps there's some other way to reach your goal.

**Comment by zarlior** [comment]
Hi,
Thanks for the fast response!

I am sure since I tested the following code:
`#include <stdio.h>
#include <stdlib.h>

void main()
{
	int currmax = _getmaxstdio();
	printf("CurrMax: %d\n", currmax);
	_setmaxstdio(8192);
	int newmax = _getmaxstdio();
	printf("NewMax: %d\n", newmax);
	for (int i = 0; i < 8189; i++)
	{
		FILE * pFile;
		int err = fopen_s(&pFile, "C:\\temp\\a.tif", "rb");
		if (err != 0)
			printf("error %d\n", i);
	}

	//let try one more file:
	FILE * pFile;
	int err = fopen_s(&pFile, "C:\\temp\\a.tif", "rb");
	if (err != 0)
		printf("Last file failed since it's more then 8192 files\n");
}`

and got the output 
_CurrMax: 512
NewMax: 8192
Last file failed since it's more then 8192 files_

I can test another function to load the files if you like...
I need such high numbers since i'm limited by RAM and once I get to paging everything works extremely slow so I would like to avoid it by loading the files on disc mode.

Thanks again,
Lior.

**Comment by jcupitt** [comment]
Would it work if you call `_setmaxstdio()` after `VIPS_INIT()`? For example:

```C
  if (VIPS_INIT(""))
    error(...);

  _setmaxstdio(8192);
```

It should change the vips setting, I think.

**Comment by zarlior** [comment]
Hi,
I tried it and it does not change the vips settings. It still fails on file 2045.
I also tried to disable my call to _setmaxstdio and call vips_init and right after _getmaxstdio() returned 512 so I guess they are separate values.

Thanks!
Lior.

**Comment by jcupitt** [comment]
I'll try making a test libvips for you.

**Comment by zarlior** [comment]
OK
Thanks a lot!

**Comment by jcupitt** [comment]
There's a `vips-dev-w64-all-8.6.0-4.zip` here:

https://github.com/jcupitt/libvips/releases/tag/v8.6.0-alpha5

I just changed 2048 to 8192, perhaps it'll work.

**Comment by zarlior** [comment]
Hi,
I really appreciate you taking the time making this test!

Unfortunately the problem still occurs... 
I just noticed that in my case I get a different error than issue  #677 while trying to load the image 2045.

I call 
```C
m_pImage = vips_image_new_from_file_raw(fileName.data(), imageSize.width, imageSize.height, 3, 0);
```
and on the image 2045 I get the error:
`
VipsImage: unable to open "C:\temp\a.tif" windows error: The storage control block address is invalid.
`

Any thoughts about this error?

Thanks,
Lior.

**Comment by jcupitt** [comment]
Sorry, I expect it just doesn't work beyond 2048. My guess is it's a hard windows limit that you somehow are not bumping into with your other fopen() calls. 

Are you opening the same file each time beyond 2045? It could be sharing the handles. Or maybe open will work, but not read?

I should be able to get to a Windows machine at work tomorrow, I'll see if I can do any more digging.

**Comment by zarlior** [comment]
Hi,
Great! 
Debugging it on a windows system sound promising.

Regarding the handles sharing, I don't think it's the case since it won't let me load more then maxstdio files. Also I tried loading all different files and still same results.

Thanks,
Lior.

**Comment by jcupitt** [comment]
I think the 2048 limit is real, but libvips is using a different libc, so you don't see the same limit in your code. 

The 2048 is set by libc, the library that implements `fopen()` and friends on top of the `CreateFile()` etc. win32 API. libvips is built with mingw and uses a version of Windows libc derived from VS6. Your code will use a different libc (a single executable can have several different libcs linked to it) from building with your VS version. The libvips libc can hit the 2048 limit while your libc can still be able to function. 

Sorry :( I don't see an easy solution. You could install linux in a VM and run your code there, I guess?

**Comment by zarlior** [comment]
Hi,
Unfortunately I cannot work on a Linux machine. 

Thanks a lot for your help and input,
Lior.
