### ISSUE TITLE
What is the vipsthumbnail equivalent for imagemagick resize with bilinear interpolation?

### ISSUE THREAD

**Issue by rnanwani** [jcupitt/libvips#767]
I tried these. But the output of the two commands varies significantly. Am I missing some parameter? Or are these commands even equivalent?

` convert in.jpg -filter triangle -resize 470x705 out.jpg `
` vipsthumbnail -o out.jpg -s 470x705 --interpolator bilinear  in.jpg `

**Comment by jcupitt** [comment]
You can probably get closer with:

```
vips reduce k2.jpg x.png 5 5 --kernel linear
```

The vips thumbnail program tries to pick the best resize algorithm for you. The interpolator hint doesn't make a lot of difference.

**Comment by jcupitt** [comment]
8.6 includes a revised linear resize which should be closer to imagemagick's triangle filter.
