### ISSUE TITLE
Dissolve an image into another by a given percent

### ISSUE THREAD

**Issue by stefanobaldo** [jcupitt/libvips#768]
It would be possible dissolve a transparent image into a jpeg (overlay) by a given percent using libvips, like this? 👇 

![opacity-ok](https://user-images.githubusercontent.com/1918151/31346147-88960fac-acee-11e7-96cc-178f0fc8073b.png)

I used to do this using GM `-dissolve` option, but I am migrating my API to use `libvips` and this is the only feature I could not get done.

**Comment by lovell** [comment]
Please don't cross-post. https://github.com/lovell/sharp/issues/981

**Comment by jcupitt** [comment]
Cross-posting questions doubles (at least) the amount of support work for the volunteers working on these projects, so it's frowned upon.

If you're using sharp, you probably need `overlayWith`:

http://sharp.dimens.io/en/stable/api-composite/

libvips 8.6, due in a few weeks, hopefully, has a new `composite` operation which will merge a stack of transparent images using the PDF blend operations, but it's not out yet.

**Comment by stefanobaldo** [comment]
I'm sorry for the cross-post, I was not sure where to post - it won't happen again.
I'm using sharp, but it seems not to be possible to dissolve a transparent png image into a jpeg as in the above example. Any workaround, @lovell?

**Comment by lovell** [comment]
@stefanobaldo https://github.com/lovell/sharp/issues/981#issuecomment-335218763

**Comment by jcupitt** [comment]
I'll close. 8.6, dur this week, should make this simpler from the command-line.
