### ISSUE TITLE
How to achieve HSL/HSV/HSB filter using CLI?

### ISSUE THREAD

**Issue by swabha1** [jcupitt/libvips#770]

**Comment by jcupitt** [comment]
Hello, you need to give more details, what do you want to achieve?

You can use `colourspace` to move an image into HSV, though HSV is a very poor space, so I would not use it.

```
$ vips colourspace ~/pics/k2.jpg x.tif hsv
```

**Comment by swabha1** [comment]
Hello John,

Hope you are doing well, Here is my requirement.

I have following png image.

![t-shirt](https://user-images.githubusercontent.com/18137958/31487628-d6ab267a-af58-11e7-97c3-e0fc6ae5c62d.jpg)

I want to change the color of it to green ( or any color I want ) and it should look like.

![t-shirt_modulated](https://user-images.githubusercontent.com/18137958/31487890-99fc9fc8-af59-11e7-9f30-885b8f01a3ff.png)

how can I achieve this with libvips?

Thanks in Advance.

**Comment by jcupitt** [comment]
Hello, I would use LCh space and add some number of degrees to the hue angle (h). At the command-line:

```
$ vips colourspace red-shirt.jpg x.v lch
$ vips linear x.v green-shirt.jpg 1 "0 0 120"
```

![green-shirt](https://user-images.githubusercontent.com/580843/31488595-0b808b6a-af36-11e7-9484-5a4cccd6e1a5.jpg)

The intermediate image is float, so I would use vips format (`.v`) for the file. Use other angles (0-360) for other colours.

With node-vips, you can do:

```
var vips = require('vips');

var image = vips.Image.newFromFile(process.argv[2]);
image = image.colourspace('lch').add([0, 0, 120]).colourspace('srgb')
image.writeToFile(process.argv[3]);
```

https://github.com/jcupitt/node-vips

**Comment by jcupitt** [comment]
Oh, and multiply the first band to change lightness and the second to change colourfulness, for example:

```
$ vips linear x.v green-shirt.jpg "1.5 1.5 1" "0 0 120"
```

![green-shirt](https://user-images.githubusercontent.com/580843/31488916-1c978eac-af37-11e7-88d5-a9430d8220f6.jpg)

**Comment by jcupitt** [comment]
I'll close. Please reopen if you still have questions.
