### ISSUE TITLE
vipsheader: MRXS size

### ISSUE THREAD

**Issue by bender22** [jcupitt/libvips#774]
Hi John,
I'm using vips to tile mrxs image (CMU-1-Saved-1_16.zip from http://openslide.cs.cmu.edu/download/openslide-testdata/Mirax/). After tiling the size in vips-properties.xml (width 4273, height 5940) equals the size of the stitched top level tiles, so everything seems fine. But when I run vipsheader to get the size it returns different values (width 7436, height 15494). Could you check and confirm is that a bug or a feature of mrxs?

**Comment by jcupitt** [comment]
Hello, did you use `--autocrop` when you converted? By default, vips openslideload will output the entire slide area, not just the actual pixels. If you use the `autocrop` flag it'll cut it down to just the pixels. I think the openslide PNG converter has the same behaviour. 

For example:

```
john@kiwi:~/pics/openslide/mrxs$ vipsheader CMU-1.mrxs 
CMU-1.mrxs: 109240x220696 uchar, 4 bands, rgb, openslideload
john@kiwi:~/pics/openslide/mrxs$ vipsheader CMU-1.mrxs[autocrop] 
CMU-1.mrxs: 68315x94972 uchar, 4 bands, rgb, openslideload
```

So try:

```
$ vips dzsave CMU-1.mrxs[autocrop]  x
```

**Comment by bender22** [comment]
Thanks a lot, this helped
