### ISSUE TITLE
Q: extract layer 0 from tiff, convert to jpg

### ISSUE THREAD

**Issue by jrochkind** [jcupitt/libvips#775]
Sorry if there's a better place to ask such a question than Issues, I couldn't find one but let me know if there is!

I have a TIFF that may have mutliple layers. I want to extract just layer 0 from the tiff, and convert it to a JPG, with no size change. I can do the conversion no problem:

     vips copy really_big.tiff really_big_full.jpg[Q=85,optimize_coding]

But I'm not sure what that will do with multiple TIFF layers, flatten then, or just take layer 0, or what. 

Can I give an argument on input saying only take layer 0 for everything else? Or something like that?

Thanks for any advice!

**Comment by jcupitt** [comment]
Hello, an issue is fine, we use this as a support forum.

The tiff loader just takes page 0 by default. You can pick another page like this:

```
vips copy huge.tif[page=12] x.jpg
```

If pages are the same size, you can run them together into a single image:

```
vips copy huge.tif[page=12,n=3] x.jpg
```

To read three pages, starting from page 12. The pages will be arranged one above the other in a "toilet roll" image.

The docs page has more detail:

http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-tiffload

**Comment by jrochkind** [comment]
Awesome! So it takes page 0 (which apparently is alternate or more correct terminology for 'layer 0' that i've seen elsewhere) by default, but if I wanna be really really explicit and clear, I can probably do `[page=0]` too. Sweet.

**Comment by jcupitt** [comment]
tiff calls them pages, other formats call them layers. In TIFF they were originally added for multi-page documents, like fax, I think.
