### ISSUE TITLE
Q: encode in sRGB, color profile file

### ISSUE THREAD

**Issue by jrochkind** [jcupitt/libvips#776]
I like the advice in [tips and tricks for vipsthumbnail](http://libvips.blogspot.com/2013/11/tips-and-tricks-for-vipsthumbnail.html) to "encode with sRGB and delete any embedded profile"

It suggests doing this with `--eprofile /usr/share/color/icc/sRGB.icc --delete`. 

I don't actually have a `/usr/share/color/icc/sRGB.icc`. Although I do have, I believe, LittleCMS installed. Is this icc file something I need to get from a non-vips source?  Or, I see from other googling, that vips has potentially more built-in color management capability than it used to, I wonder if there's something built into vips at this point that can let me do the sRGB encode without an external file? Any advice? Appreciate it, thank you!

**Comment by jcupitt** [comment]
I usually use this one:

https://github.com/jcupitt/pyvips/blob/master/tests/images/sRGB.icm

But you can use any sRGB profile. You'll have several on your machine somewhere.

**Comment by jrochkind** [comment]
Thanks. My deployment AWS machine doesn't seem to have one already, so I had to get one from _somewhere_, properly licensed. 

After quite a bit of googling between when I filed the issue and now, I found another one, that may even be somehow "official" ICC? And is licensed for pretty much any use, including commercial, without restriction. 

http://www.color.org/srgbprofiles.xalter#v2

Is there any reason that would one not do too?

It actually was really hard to find a free one on google, and also led me to a bunch of reading (why are there _different_ sRGB profiles that all claim to be ICC sRGB and have somewhat different parameters? Phew!).  So perhaps this issue existing, even once closed, will be more findable on google for people looking for "where do I get an sRGB.icc profile for use with vips?" :)

**Comment by jcupitt** [comment]
We spent some time looking into this, and the one from pyvips I linked is the best I've found, and has an unrestricted licence. But any profile should work.

**Comment by jrochkind** [comment]
Awesome. It might make sense to document that somewhere; but this issue now existing and being findable may serve as sufficient documentation. If you feel like it though, an edit to the "tips and tricks for vips thumbnails" blog posts directing users to the pyvips profile if they need a profile might be helpful for people who come across that.
