### ISSUE TITLE
Q: TIFF compression, final size vs imagemagick/graphicsmagick

### ISSUE THREAD

**Issue by jrochkind** [jcupitt/libvips#777]
I have a large TIFF, with no internal compression. It's 165MB originally. 

I want to make it use internal deflate/zip compression instead. 

If I use graphics magick:

    gm convert original.tif -compress zip gm_zip_compressed.tif

I wind up with a 99MB file. 

If I use vips:

    vips copy original.tif vips_zip_compressed.tif[compression=deflate]

I wind up with a 131MB file instead. 

I have seen this general pattern with other files too, it's not unique to this sample file. 

Why is vips being so much less effective at applying internal deflate compression in a TIFF than gm/im? Can anything be done?

**Comment by jcupitt** [comment]
Hello, try setting a predictor. Perhaps:

```
vips copy wtc.tif x.tif[predictor=horizontal,compression=deflate]
```

It depends a bit on the image. 

By default, vips will simply use the deflate compressor on your pixels. With a predictor, it takes left-right (in this example) pixel differences, and then compresses them. Since pixels are often similar to their neighbours, there are fewer bits to compress.

**Comment by jrochkind** [comment]
Thanks!

That worked! With predictor=horizontal, my sample file got down to 96M, even slightly smaller than the GraphicsMagick output. 

I wonder if there's any way to figure out what ImageMagick/GraphicsMagick are doing with a simple `-compress zip`; I guess something like this. 

I wonder if it would be beneficial to have better defaults here, I almost didn't notice my compressed TIFFs were so much larger than the comparable from IM/GM, and I would not have figured out the solution without your help. Thanks for all your help on my several issues today, and for vips which is pretty amazing!

**Comment by jcupitt** [comment]
You're right -- the option was put in 10 years ago when the predictor flag was new and experimental. It's fine to have it on by default now. I've changed it for 8.6.

**Comment by jcupitt** [comment]
Off-topic: I noticed you're using Ruby. I guess you found ruby-vips?

https://rubygems.org/gems/ruby-vips

If you are doing a series of operations, then the CLI will use temp files for intermediates. You need a lot of disk space, and you'll spend a lot of time in IO. This can be a problem on AWS. 

Ruby-vips calls directly into libvips and it can use libvips' "chaining" system. When you do a series of operations, they delay computation and link up behind the scenes. When you do the final write, the whole pipeline executes at once and in parallel, streaming your image though the system quickly and with little memory use.

The interface is higher-level and more convenient too, for example:

```ruby
require 'vips'

x = vips::Image.new_from_file "some-input-file"
x.write_to_file "x.tif", predictor: :horizontal, compression: :deflate
```

It supports memory operations too, so you can work directly with S3 buckets and the client and avoid the filesystem completely.

**Comment by jrochkind** [comment]
Thanks! I was aware of ruby-vips (and it's recent strides), and realized it would probably be an improvement.... but just haven't had time to mess with it. 

Since i was using IM/GM via command line, swapping it out for vips via command line was the smallest initial change.  Image manipulation is conceptually complicated, figuring out the _right_ operations in vips instead of IM/GM was challenging already, and it's been easier to google for vips command line options than to figure out the right ruby-vips API. 

I also _know_ that shelling out to command line in multiple concurrent threads I've created will be completely thread-safe, and use all CPU cores when done multi-threaded even though I'm in MRI (which can only use one core simultaneously), and not leak RAM into my ruby process etc. It may be that ruby-vips would be just fine here too, it's just another thing to investigate. (If you have anything to share about ruby-vips under concurrency in MRI, that'd be helpful. :) ). 

I def have ruby-vips in mind as a potential future improvement, but I can say that swapping from IM or GM command line to vips command line has already had major improvements with no downsides yet seen, even on AWS.

**Comment by jrochkind** [comment]
(I am doing all the operations I need in _one_ vips command line call, so I suspect it should be doing all the operations as a chained pipeline at once and in parallel that way too? At any rate, whatever it's doing is working much better than IM/GM command-line was in terms of end-to-end latency and RAM use)

**Comment by jcupitt** [comment]
Fair enough, I wasn't certain you'd seen it.

Yes, ruby-vips should be thread-safe and not leak, but of course you're right, true process separation is even safer. 

The node.js binding is used on huge sites with 1000s of concurrent imaging operations, so the underlying library at least ought to be solid (I hope).

I think avoiding the filesystem should give you a useful drop in latency, but you'd need to experiment.

**Comment by jrochkind** [comment]
Do you happen know if ruby-vips can make use of multiple cpu cores for cpu-heavy transformation work, even when run under MRI ruby which has the "GIL"?  This is hypothetically conceptually possible, since ruby-vips cpu heavy lifting is done through C (or Go or whatever) code instead of ruby code, but I don't know enough about ruby/ffi/etc to know what/if you need to do to make it so.

**Comment by jcupitt** [comment]
Yes, libvips pipelines will run on all your cores by default, you don't need to do anything.

**Comment by ioquatix** [comment]
> It supports memory operations too, so you can work directly with S3 buckets and the client and avoid the filesystem completely.

Do you have an example of how to do this @jcupitt

**Comment by jcupitt** [comment]
Perhaps "directly" was the wrong word --- I meant via a memory buffer. It is avoiding the filesystem at least.

True streaming from a socket is still being discussed, but some way off.

**Comment by jcupitt** [comment]
In case anyone comes across this old thread, libvips 8.9+ now has true streaming. For example, this:

```
aws s3 cp s3://mybucket/input.jpg - | \
  vips thumbnail_source [descriptor=0] .jpg 128 | \
    aws s3 cp - s3://mybucket/output.jpg
```

Will thumbnail an image from one S3 bucket to another, without touching the filesystem, and with only minimal buffering in memory. ruby-vips supports this in the obvious way.

See:

https://libvips.github.io/libvips/2019/12/11/What's-new-in-8.9.html

**Comment by jrochkind** [comment]
wow, this is huge, thanks!
