### ISSUE TITLE
openslide2vips: opening slide: No such value: directory 0, tag 278

### ISSUE THREAD

**Issue by Pashtewan** [jcupitt/libvips#778]
Hello guys,

my machine is ubuntu.

my vips -v is 
vips-8.5.9

when i run this 
vips dzsave LC31\(A\)-new_x40_z0.tif mydz

I get this error

openslide2vips: opening slide: No such value: directory 0, tag 278

does this look familiar to anyone ?

**Comment by jcupitt** [comment]
Hello, sounds like your vips may not have been compiled with openslide support. 

You should see:

```
john@kiwi:~$ vips openslideload
load file with OpenSlide
usage:
   openslideload filename out [--option-name option-value ...]
where:
   filename     - Filename to load from, input gchararray
   out          - Output image, output VipsImage
optional arguments:
   flags        - Flags for this file, output VipsForeignFlags
   memory       - Force open via memory, input gboolean
			default: false
   access       - Required access pattern for this file, input VipsAccess
			default: random
			allowed: random, sequential, sequential-unbuffered
   level        - Load this level from the file, input gint
			default: 0
			min: 0, max: 100000
   autocrop     - Crop to image bounds, input gboolean
			default: false
   fail         - Fail on first error, input gboolean
			default: false
   associated   - Load this associated image, input gchararray
```

If not, you'll need to rebuild vips.

**Comment by bgilbert** [comment]
OpenSlide thinks that's a Hamamatsu NDPI file, but it's missing an expected TIFF tag.  Is it NDPI?  Is there anything unusual about how it was produced?

**Comment by Pashtewan** [comment]
Hello guys thank u for the response.
they are big ndpi files which i convert into tifs by:
ndpisplit -x40 filename.ndpi
then i try to convert them into dzi but no luck

here is a dropbox link to the ndpi file, its 1.3Gig
https://www.dropbox.com/s/3f1g6qzh5sz7158/LC20%28A%29-new.ndpi?dl=0

**Comment by jcupitt** [comment]
Hello, don't use ndpisplit, it makes invalid tiff files -- or at least tiffs that libvips can't read.

You can work directly from the ndpi image, for example:

```
john@kiwi:~/pics/openslide$ vipsheader LC20\(A\)-new.ndpi 
LC20(A)-new.ndpi: 122880x71168 uchar, 4 bands, rgb, openslideload
john@kiwi:~/pics/openslide$ vips crop LC20\(A\)-new.ndpi x.tif 10000 10000 1000 1000
```

and `x.tif` is something I can view. You probably need:

```
$ vips dzsave LC20\(A\)-new.ndpi mydz
```

**Comment by Pashtewan** [comment]
it worked !!
Thank u so much.

**Comment by Pashtewan** [comment]
Sorry one more question
does this command 
vips dzsave LC20\(A\)-new.ndpi mydz
produce the highest magnification available ?

**Comment by jcupitt** [comment]
Yes, you'll get a 122880 by 71168 pixel image for that file.

**Comment by Pashtewan** [comment]
thank u for responding.
how would i be able to get the maximum possible dzi file

**Comment by jcupitt** [comment]
That is the maximum possible dzi file, I think. What size are you expecting?

**Comment by Pashtewan** [comment]
sorry i just saw your vipsheader output, yes thats the maximum.
may thanks for the quick responses.
