### ISSUE TITLE
Proper way to save tiff image in CMYK format using pyvips

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#780]
Anyone know the proper way to save an image in CMYK Tiff format using pyvips?

with sharp the convertion can be achieved by:
sharp('path/to/file_input.jpg') 	
   .toColorspace('cmyk') 	
   .withMetadata({ profile: 'path/to/profile.icc' }) 	
   .toFile('path/to/file_output.jpg');

**Comment by jcupitt** [comment]
Hello, try:

```python
im = pyvips.Image.new_from_file('some-file.jpg')

cmyk = im.icc_transform('/path/to/cmyk-profile.icc', 
                        embedded=True,
                        input_profile='/path/to/fallback/input/profile.icc')
cmyk.write_to_file('x.tif')
```

You should give two profiles: a fallback input profile to use if the input JPEG image has no embedded profile (I would use an sRGB profile), and a CMYK profile for your printer. 

There are two good profiles here:

https://github.com/jcupitt/pyvips/blob/master/tests/images/sRGB.icm

https://github.com/jcupitt/nip2/blob/master/share/nip2/data/cmyk.icm

**Comment by jcupitt** [comment]
Transform docs here:

http://jcupitt.github.io/libvips/API/current/libvips-colour.html#vips-icc-transform

**Comment by jindili** [comment]
I found this work too:
cmyk = rgbIMAGE.icc_export(pcs="lab", intent="relative", output_profile="cmyk.icc")

**Comment by jcupitt** [comment]
Yes, that will work too. You can remove the `pcs` and `intent` arguments, they won't make any difference in this case.
