### ISSUE TITLE
Q: vipsthumbnail, constrain width but not height

### ISSUE THREAD

**Issue by jrochkind** [jcupitt/libvips#781]
I want to use vipsthumbnail to make thumbnails that are no more than X pixels wide, with height proportional for the original. Say 40px is X. 

I can't seem to do this. All of these create a thumb which is 40px _high_, with width set proportionally for original aspect ratio. I want one that is 40px wide, with height varying. vips 8.5.7.

     vipsthumbnail original.jpg --size 40x -o thumb.jpg
     vipsthumbnail original.jpg --size x40 -o thumb.jpg
     vipsthumbnail original.jpg --size 40 -o thumb.jpg

Anything I'm missing?  Man page just says:

~~~
       -s N, --size=N
              Set the output thumbnail size to N x N pixels.

              You can use "MxN" to specify a rectangular bounding box.  The image is shrunk so that it just fits within this area, images which are  smaller  than
              this are expanded.

              Use "xN" or "Mx" to just resize on one axis.

              Append "<" to only resize if the input image is smaller than the target, append ">" to only resize if the input image is larger than the target.
~~~

If I can do this with `vips copy` rather than `vipsthumbnail`, can you give me the args to give `vips copy` to duplicate the defaults of `vipsthumbnail`? Or is that documented anywhere? Thanks!

**Comment by jcupitt** [comment]
Huh funny, `--size 40x` should do what you want, but it's obviously broken, sorry about that.

I'll have a look.

**Comment by jcupitt** [comment]
git master seems to be working now:

```
john@kiwi:~/pics$ vipsthumbnail k2.jpg wtc.jpg --size 40x
john@kiwi:~/pics$ vipsheader tn_k2.jpg tn_wtc.jpg 
tn_k2.jpg: 40x56 uchar, 3 bands, srgb, jpegload
tn_wtc.jpg: 40x40 uchar, 3 bands, srgb, jpegload
```

Thank you for reporting this dumbness -- it'll be in 8.6, due in a week or two.

I'll see if I can think of a workaround for you until then.

**Comment by jrochkind** [comment]
Hmm, if I say like `--size 40x10000000` or something, will that basically ignore the second one since it'll never be a constraint, still keeping it proportional to original aspect ratio? Or something along those lines I can use to fake it out?

Alternately, if the bug only effects vipsthumbnail and not `vips copy` used similarly, is there a way to use `vips copy`, when operating on a single image at a time, with proper args to be equivalent in effect to `vipsthumbnail`?  That'd be useful to know in general.

**Comment by jrochkind** [comment]
Incidentally, from that commit "If there was no 'x' we have just width. vipsthumbnail history means this is a square bounding box" -- that's how it was documented and intended, and maybe it used to work that way, but in current version no 'x' actually does the same thing as "xM". I guess that was a bug, does make sense to make it how you have to match docs, I guess, whether or not it's ever done that!

**Comment by jcupitt** [comment]
The bug was in the way that the `vipsthumbnail` program parsed geometry strings. If you call the `thumbnail` operation directly, it works fine.

Try:

```
$ vips thumbnail k2.jpg x.jpg 10000 --height 40
$ vipsheader tn_k2.jpg 
tn_k2.jpg: 29x40 uchar, 3 bands, srgb, jpegload
```

ie. resize to fit within a box 10,000 pixels high, but only 40 pixels wide.

**Comment by jcupitt** [comment]
Oh, or as you say:

```
$ vipsthumbnail k2.jpg --size 40x10000
```

does the same thing.

**Comment by jrochkind** [comment]
Ah, I actually did not know htere was a `vips thumbnail` operation!  Still figuring out how to find my way around the command line.  That'd be another good thing to provide an example of on the "tips and tricks for vipsthumbnail" page maybe. 

The main difference with `vipsthumbnail` is just it's superior ability to handle multiple input files automatically creating output filenames?

**Comment by jrochkind** [comment]
Hm, I don't want a fixed height of course, I want a fixed width. Is the whole issue! 

So I probably don't want `vips thumbnail ... --height 40`.  If I try `vips thumbnail ... --width 40`, `Unknown option --width`.  If I try `--size 40x`, `thumbnail: enum 'VipsSize' has no member '40x', should be one of: both, up, down`.

**Comment by jcupitt** [comment]
Oh duh, sorry, I swapped them.

Try:

```
$ vips thumbnail k2.jpg x.jpg 10000 --height 40
$ vipsheader x.jpg 
x.jpg: 29x40 uchar, 3 bands, srgb, jpegload
```

You can see the CLI arguments by just using the name:

```
$ vips thumbnail
generate thumbnail from file
usage:
   thumbnail filename out width [--option-name option-value ...]
where:
   filename     - Filename to read from, input gchararray
   out          - Output image, output VipsImage
   width        - Size to this width, input gint
			default: 1
			min: 1, max: 10000000
optional arguments:
   height       - Size to this height, input gint
			default: 1
			min: 1, max: 10000000
   size         - Only upsize, only downsize, or both, input VipsSize
			default: both
			allowed: both, up, down, force
   auto-rotate  - Use orientation tags to rotate image upright, input gboolean
			default: true
   crop         - Reduce to fill target rectangle, then crop, input VipsInteresting
			default: none
			allowed: none, centre, entropy, attention
   linear       - Reduce in linear light, input gboolean
			default: false
   import-profile - Fallback import profile, input gchararray
   export-profile - Fallback export profile, input gchararray
   intent       - Rendering intent, input VipsIntent
			default: relative
			allowed: perceptual, relative, saturation, absolute
operation flags: nocache 
```

**Comment by jrochkind** [comment]
Ah, after saying you swapped them, I believe you just pasted in the exact same thing again. Unless I'm getting confused. `vips thumbnail k2.jpg x.jpg 10000 --height 40`.  I do not want to constrain height, I want to constrain width. 

From the help page you pasted though (thanks!), it looks like the first number on the command line, without an argument, is width constraint, and then you can also supply a height constraint with `--height`?  

Okay, experimenting, 

      vips thumbnail input.tiff out.jpg 40

Still constrains height to 40, not width. (It may be constraining both in a square, but my source input is higher than it is wide).  

    jrochkind-chf sample pictures  $ vipsheader out.jpg
    out.jpg: 29x40 uchar, 3 bands, srgb, jpegload

So I think there is a bug in `vips thumbnail` too, it may not be true that ' If you call the thumbnail operation directly, it works fine." Or I may just be getting confused somehow. 

However, this works:

     vips thumbnail input.tiff out.jpg 40 --height 100000

If I have to provide a fake 'height' to fool it, indeed I'm no better off with `vips thumbnail` then `vipsthumbnail`, both need that. 

I don't really understand the difference between `vips thumbnail` and `vipsthumbnail`. 

Still curious if there's a way to use `vips copy` with arguments that will duplicate `vipsthumbnail`, in a way that will let me specify just width and not a fake height. I'm trying to wrap my head around all the different ways there are to call vips cli, and how they relate.

**Comment by jcupitt** [comment]
That's right:

```
$ vips thumbnail x.jpg y.jpg 40
```

Means shrink to fit within a 40x40 box, and:

```
$ vips thumbnail x.jpg y.jpg 40 --height 10000
```

Means a 40 by 10,0000 box, so images will really just be constrained on width. Got it right this time, sigh.

`thumbnail` is the basic libvips operation for thumbnailing. You can call it from C as `vips_thumbnail()`. The docs are here:

http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail

You can run this from the CLI with the `vips` program (that's what `vips thumbnail`) is doing. You can call it from PHP, Python, Ruby, JavaScript etc as well.

`vipsthumbnail` is a program that's supposed to make command-line thumbnailing easier. It will loop, it has an easier syntax for expressing size constraints, and it can generate filenames for you.

**Comment by jcupitt** [comment]
Oh, the `vips` program will automatically convert file formats for the libvips operator you call. So:

```
$ vips invert x.tif y.png
```

Will call the libvips `invert` operator. `vips` will actually call three operators here: `vips_tiffload()`, `vips_invert()` and `vips_pngsave()`. It has extra syntax with `[]` brackets so you can pass parameters to the file format operators:

```
$ vips invert x.tif[page=12] y.png[compression=7]
```

So you can control the load and save process.

When you run `vips copy`, you're just running the `copy` operator:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-copy

So you can give params to the load and save operators you use, but that's all.

Anyway, there's no way to use `thumbnail` from `copy`.

**Comment by jcupitt** [comment]
OK, bug resolved, thank you for pointing out this dumbness. 

I'll close.

**Comment by jrochkind** [comment]
Thank you! 

I was thinking there might be a way to duplicate `thumbnail` from `copy` with the right arguments, such as `resize` etc. But I guess  `thumbnail` may be doing things that can't be done with `copy`.  Image manipulation ends up much more complicated than one might naively think before diving into it! 

Thanks for vips!
