### ISSUE TITLE
vips2tiff: image height 19305 is not a factor of page-height 4862

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#782]
Error while saving image to tif format, work fine when save in jpg or png format

Traceback (most recent call last):
  File "H:/testPyVips.py", line 320, in <module>
    output.write_to_file("final.tif")
  File "C:\Python27_64\lib\site-packages\pyvips\vimage.py", line 519, in write_to_file
    ), **kwargs)
  File "C:\Python27_64\lib\site-packages\pyvips\voperation.py", line 213, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call VipsForeignSaveTiffFile
  vips2tiff: image height 19305 is not a factor of page-height 4862

**Comment by jcupitt** [comment]
Hello, add:

```python
image.remove('page-height')
```

Before you write.

You have loaded a multi-page tiff, then changed it, then you are saving. The page height for the image is no longer correct, so the save cannot work.

**Comment by jcupitt** [comment]
I've made it not error out for this case, the message was confusing.

**Comment by jindili** [comment]
It Works!
