### ISSUE TITLE
0-9 levels size calculation logic

### ISSUE THREAD

**Issue by bender22** [jcupitt/libvips#783]
HI John,
I tiled an image (4650x4650) with 192 tile size and a bit surprised by how the tile sizes for low levels calculated (when the level size is smaller than tile size). So I got the following sizes:
level	        size, px
0		1x1
1		2
2		3
3		5
4		10
5		19
6		37
7		73
8		146
9		4 tiles 192x192...
I expected it to be 192(level 8)->96->48->24->12->6->4->2->1
Could you, please, explain the logic of the calculating level sizes, or reference to some source files?

**Comment by jcupitt** [comment]
Hello @bender22, deepzoom has fractional tiles, so:

```
$ vips crop wtc.jpg x.jpg 0 0 4650 4650
$ vips dzsave x.jpg x --tile-size 192 --overlap 0
$ cd x_files/
$ ls 9/
0_0.jpeg  0_1.jpeg  1_0.jpeg  1_1.jpeg
$ vipsheader 9/1_0.jpeg 
9/1_0.jpeg: 99x192 uchar, 3 bands, srgb, jpegload
```

So layer 9 is 192 + 99 = 291 pixels across, and layer 8 is 145.5. It rounds to nearest, so 146 pixels for layer 8. 

In Google layout tiles are always full size, that might work better for you, perhaps?

**Comment by bender22** [comment]
I see, thanks!
