### ISSUE TITLE
Generate a perfect polygon with pyvips

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#785]
Try to implement a polygon generator with pyvips

Function to describe a n-side polygon:
![image](https://user-images.githubusercontent.com/73845/32081118-1453c8a4-bae6-11e7-8887-fec661c450a7.png)

My code:

```
def polygon(size=1000, n=8):
    index = pyvips.Image.xyz(size * 2.0, size * 2.0)
    index = index - [size, size]
    index = index.polar()
    polygon0 = index[0] < math.cos(math.pi / n) / math.cos(
        index[1] - math.pi * 2 / n * pyvips.Image.floor((n * index[1] + math.pi) / 2 * math.pi))
    return polygon0.shrink(2, 2).invert()
```

get error on the polygon0 equation line:
```
TypeError: a float is required
```

**Comment by jcupitt** [comment]
Instead of `pyvips.Image.floor(x)`, use `x.floor()`.

**Comment by jcupitt** [comment]
You can also make the shape as an SVG. 

libvips has a very fast SVG loader, and it can make images very quickly and with little memory use.

**Comment by jindili** [comment]
This line works
```
polygon0 = index[0] < (size * math.cos(math.pi/n)) / pyvips.Image.cos(index[1] - 360.0/n * ((n*index[1] + 180)/360.0).floor())
```

Still need some test which methods is better in creating a large polygon shape

Generate by xyz function 
or
load from SVG shape
