### ISSUE TITLE
Extend image edge using pyvips

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#786]
Try to extend image edge by certain pixels using pyvips, like:
![image](https://user-images.githubusercontent.com/73845/32143983-dd33f700-bcec-11e7-921b-f84fa6d8e633.png)

Is there some vips function I can use to achieve this?

**Comment by jcupitt** [comment]
Hello @jindili, try `embed` with the 'copy' option.

```
$ python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> a = pyvips.Image.new_from_file("Gugg_coloured.jpg")
>>> b = a.embed(100, 100, a.width + 200, a.height + 200, extend='copy')
>>> a = a.join(b, 'horizontal', shim=100, expand=True, align='centre')
>>> a.write_to_file("x.jpg")
```

![x](https://user-images.githubusercontent.com/580843/32145844-bcb2d38c-bcc6-11e7-8811-e1280a7061c7.jpg)

Though it won't do arbitrary images, like your example, it just copies the edges of square images.

**Comment by jindili** [comment]
Hi John, That's quite near to what I want to get.  For the normal rectangular shaped image, that's exactly.

but for arbitrary shapes, is it possible to extend some vips' function to do it, or I have to use some other tools like OpenCV specified for the object recognition.

**Comment by jcupitt** [comment]
You'd need to write some C and add it to libvips -- it would be a few days work. You would probably be better off with opencv.

**Comment by jindili** [comment]
I would try the OpenCV way, seems there are some ready-made functions to detect the object shape.

**Comment by jcupitt** [comment]
In libvips, you'd use erode to find just the edge pixels, then for each edge pixel, draw a set of circles and take the minimum at each point. It'd be too slow in Python, I think :(

**Comment by jindili** [comment]
Hi, John, I don't quite understand the document on erode here
https://jcupitt.github.io/pyvips/vimage.html#pyvips.Image.erode

the code here:
https://github.com/jcupitt/libvips/blob/e241d1333926180c5258dbf6650d0c1af7538f7a/python/example/try16.py
work out just like an image color filter.

Can you provide some code snippets using pyvips to find the edge pixel?

**Comment by jcupitt** [comment]
I actually needed this today for a cell-counting program, so I added `VipsNearest`:

https://github.com/jcupitt/libvips/blob/master/libvips/morphology/nearest.c

It fills in zeros in an image with the nearest pixel value. For this test image:

![x](https://user-images.githubusercontent.com/580843/32276562-6dacb2ec-bf07-11e7-83eb-be16e2851b5f.png)

It generates this:

![y](https://user-images.githubusercontent.com/580843/32276570-758bc17e-bf07-11e7-87e1-09525f574230.png)

It'll be in 8.6.

**Comment by jcupitt** [comment]
Here's what it makes for your fish image: 

![fish-grow](https://user-images.githubusercontent.com/580843/32277631-fa1f0c2c-bf0a-11e7-940e-9b7a05c860dd.png)

**Comment by jindili** [comment]
That's great! Awesome work.

**Comment by jcupitt** [comment]
In master as `fill_nearest`, it should be in 8.6.
