### ISSUE TITLE
Use libvips to detect white image border

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#787]
Need to batch detect quite a lot of images whether they could be seamlessly tiled.

One common case is some image got a small white border (usually one pixel, sometimes might be several pixels wide,  could be placed on any side of the image, like below:

![image](https://user-images.githubusercontent.com/73845/32153021-bb9d58ea-bd62-11e7-95ed-7a5bd0b94a10.png)

Currently, I invert() the input image and use profile() to detect empty spaces in all four border of the image, and use min() to check the profile result to get white border size.

I want to know whether it's the right and performant way to do such a thing using pyvips.

**Comment by jindili** [comment]
Workable code here
```
def checkWhiteBorder(img):
    im = img.invert()

    left = im.profile()[1].min()
    right = im.flip("horizontal").profile()[1].min()
    top = im.profile()[0].min()
    bottom = im.flip("vertical").profile()[0].min()

    return left,right,top,bottom
```

and some step further, Is there some way to check left edge and the right edge is continuous, like this

![image](https://user-images.githubusercontent.com/73845/32154309-c2de55ca-bd6a-11e7-8ea9-dc96162e1b6e.png)

**Comment by jcupitt** [comment]
Hello, you can make it maybe 4x faster with `project`:

http://jcupitt.github.io/libvips/API/current/libvips-arithmetic.html#vips-project

It scans the image and returns a set of column sums and row sums. You can then use `profile` as before to searc the sums rather than the whole image.

Something like (untested):

```python
def checkWhiteBorder(img):
    column_sum, row_sum = img.invert().project()
    left = column_sum.profile()[1].min()
    right = column_sum.fliphor().profile()[1].min()
    top = row_sum.profile()[0].min()
    bottom = row_sum.flipver().profile()[0].min()

    return left,right,top,bottom
```

**Comment by jcupitt** [comment]
To check for continuity, I would extract the first and last columns, subtract, square, and find the average. 

If the image is continuous, the difference should be very small. You would need to experiment to find a good threshold.

**Comment by jindili** [comment]
project() works and much faster.
