### ISSUE TITLE
Pyramid tiiffs and nearest neighbour

### ISSUE THREAD

**Issue by Nik0l** [jcupitt/libvips#788]
What is the easiest way to enable nearest neighbour when producing `pyramid` tiffs with `tiffsave` command? ideally to do it from a command line... 

By default vips uses an averaging algorithm when downsampling tiff image while producing lower level images in a pyramid tiff. But I wonder if it is possible to use nearest neighbour instead.

**Comment by jcupitt** [comment]
Hello, it always does exact 2x2 averaging, you can't change it. There's a branch that adds lanczos3 downsampling as an option, but it hasn't been merged yet. 

What are you aiming to accomplish? Perhaps there's some other way to get there.

**Comment by Nik0l** [comment]
Hi. Let's say I have only white and black regions in my original tiff. When I convert my tiff to pyramid tiff then intermediate colours are introduced at lower levels due to the averaging. But I need to have only white and black regions as in the original tiff so I would like to figure out a way to have control over the downsampling process.

**Comment by Nik0l** [comment]
something like '--kernel nearest' in tiffsave would be awesome.

**Comment by jcupitt** [comment]
You could save as a one-bit tiff, so there were no intermediate values. Would that work?

Something like:

```
$ vips copy cramps.tif x.tif[pyramid,tile,squash,compression=ccittfax4]
```

Where `cramps.tif` is the standard one-band, 8-bit demo image.

**Comment by Nik0l** [comment]
But I need a pyramid tiff with a few levels. . . where each lower level is a downsampled by factor 2 original tiff.

**Comment by Nik0l** [comment]
well it is a good idea but I have more thsn two values, actually five values, not only 0 and 1 :-) My goal is not to introduce new values at lower levels.

**Comment by Nik0l** [comment]
so maybe having one bit tiffs with several layers or channels will solve my problem.

**Comment by jcupitt** [comment]
Oh heh. Hmm, I don't think ccittfax4 compression allows more than one band, unfortunately. You'd need a separate TIFF image for each band.

**Comment by jcupitt** [comment]
Sorry, I don't think this is going to be easily fixable. 

Perhaps you could run a second pass over the output image where you requantise back to the original 5 colours?
