### ISSUE TITLE
Does vips support layered image

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#792]
vips support multi-page tiff, see
https://github.com/jcupitt/libvips/issues/789

I also want to know whether vips can create layered image, like layers in Photoshop,
If that's possible, it would be great to have some contents in one layer, and some markups(texts, icons) in another transparent-background layer, That would be much convenient for later modification.

**Comment by jcupitt** [comment]
You could put each layer into a separate page, would that work?

Alternatively, you could make a (for example) 12-band image, with each set of three bands being a different image.

**Comment by jindili** [comment]
sad that Photoshop does not support multi-page tiff, and those who use my generated image know only potoshop.

**Comment by jcupitt** [comment]
Oh, you need to be able to load it into photoshop? Sorry, I think multi-page tiff is your only option.

You could try ImageMagick. It can probably write photoshop files: you could combine a set of images into one with that.

**Comment by jindili** [comment]
Yes, that's a good option.

I'll save to multiple output file, and compose later with ImageMagick command line.

**Comment by jindili** [comment]
I do some test with Multiple-Layered tiff today

create the file in PhotoShop 2018, Options to save to layered tiff:

![image](https://user-images.githubusercontent.com/73845/32401198-4a12a28e-c145-11e7-925d-c03ec5d2b9cc.png)

![image](https://user-images.githubusercontent.com/73845/32401196-46037380-c145-11e7-9d56-82ff167c1eec.png)

file size compare:
![image](https://user-images.githubusercontent.com/73845/32401195-2f9b973a-c145-11e7-8064-58d51730270f.png)

simple load and print info using pyvips
```
psd = pyvips.Image.new_from_file("tiff_multipleLayer.psd")
tiffM = pyvips.Image.new_from_file("tiff_multipleLayer.tif")
tiffS = pyvips.Image.new_from_file("tiff_singleLayer.tif")

print(psd)
print(tiffM)
print(tiffS)
```
get
```
<pyvips.Image 3000x1872 uchar, 3 bands, srgb>
<pyvips.Image 3000x1872 uchar, 3 bands, srgb>
<pyvips.Image 3000x1872 uchar, 3 bands, srgb>
```

Seems vips do support multiple-layered tiff, but layers are flattend on load.

**Comment by jcupitt** [comment]
Does the `page` parameter get the other layers?

Could you upload one of these multi-page tiffs somewhere? I could have a look at the structure they are using.

**Comment by jcupitt** [comment]
You could also try:

```python
tiffM = pyvips.Image.new_from_file("tiff_multipleLayer.tif", n=-1)
```

And see if the size changes.

**Comment by jindili** [comment]
Hi, John
Here is a multi-layer tiff, github comment does not support tif upload, so I ziped.
[tiff_multipleLayer.zip](https://github.com/jcupitt/libvips/files/1443322/tiff_multipleLayer.zip)

**Comment by jindili** [comment]
Trid
```
tiffM1 = pyvips.Image.new_from_file("tiff_multipleLayer.tif")
tiffM2= pyvips.Image.new_from_file("tiff_multipleLayer.tif", n=-1)
print(tiffM1)
print(tiffM2)
``

get:
```
<pyvips.Image 2048x1365 uchar, 3 bands, srgb>
<pyvips.Image 2048x1365 uchar, 3 bands, srgb>
```

when I change n to 0,1 or 2, get error:
```
pyvips.error.Error: unable to call VipsForeignLoadTiffFile
  tiff2vips: bad number of pages 0
```

**Comment by jcupitt** [comment]
I tried looking inside that image with `tiffinfo`. It seems to keep the other layers in private tags in the header, so I don't think vips has any chance of reading them or writing them.

**Comment by jcupitt** [comment]
You could try imagemagick:

```
convert 1.png 2.png 3.png layer.psd
```

and it should make a three-layer photoshop image.

**Comment by jcupitt** [comment]
I thnk this id done, I'll close.
