### ISSUE TITLE
Detect and split objects in image

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#793]
From an image with transparency
![image](https://user-images.githubusercontent.com/73845/32257152-64b5ffb8-beee-11e7-874a-87d22cf24fad.png)

to list of separated images

![image](https://user-images.githubusercontent.com/73845/32257169-749a4056-beee-11e7-8f86-f8ea3cbbae28.png)

use erode() to get object shapes
![image](https://user-images.githubusercontent.com/73845/32257191-8bb6f676-beee-11e7-910b-e93efbe2565c.png)

code from https://github.com/jcupitt/libvips/issues/786

```
x = pyvips.Image.new_from_file(sys.argv[1])

# get the alpha channel just as 0 / 255
if x.bands != 4:
    raise Exception('no alpha channel')
alpha = x[3] != 0

# alpha is 255 for solid, 0 for transparent

# erode with a 4-way connected mask ... 128 means "don't care", 255 means "white
# pixel"
mask = pyvips.Image.new_from_array([[128, 255, 128],
                                    [255, 255, 255],
                                    [128, 255, 128]])
eroded = alpha.erode(mask)
```

and I have no idea how to use the eroded image to continue.

**Comment by jcupitt** [comment]
Hello, are you trying to crop the separated objects from the original image?

You can use `labelregions` to segment the image, then `hist_find_indexed` with an xy image to find the position of each separate object. I'll make you an example.

**Comment by jindili** [comment]
Yes, I want to crop the separated objects.

**Comment by jindili** [comment]
Hi, John. I'm still waiting for your example.

**Comment by jcupitt** [comment]
I've had to add a feature to libvips to make finding the crop boxes possible, and it's become stuck in some other project. Maybe another week.

**Comment by jcupitt** [comment]
Sorry, I finally finished this. I added a `combine` mode to index histogram.

```python
import sys
import pyvips

x = pyvips.Image.new_from_file(sys.argv[1])

# take the final channel as alpha, then we want non-zero pixels to get 255 in
# all object areas
mask = x[x.bands - 1] != 0

# find connected areas ... each area of continuous pixels will be given a
# different numeric label
labelled, other = mask.labelregions(segments=True)
n_segments = other['segments']

# make a two-band image where band 0 is x coordinates and band 1 is y
# coordinates
coordinates = pyvips.Image.xyz(mask.width, mask.height)

# now use the labels to make a histogram of the coordinate image ... for each
# bin, pick the max and min to get the bounding box of the objects
maxes = coordinates.hist_find_indexed(labelled, combine='max')
mins = coordinates.hist_find_indexed(labelled, combine='min')

# loop, making an array of cropped objects
# object 0 is unused, object 1 is the background, so start at object 2
objects = []
for i in range(2, n_segments):
    left = mins(i, 0)[0]
    top = mins(i, 0)[1]
    width = maxes(i, 0)[0] - left + 1
    height = maxes(i, 0)[1] - top + 1

    objects.append(x.crop(left, top, width, height))
    
# and join all cropped objects to the output
joined = pyvips.Image.arrayjoin(objects, 
                                valign="centre", halign="centre", shim=50)
joined.write_to_file(sys.argv[2])
```

Run like this:

```
$ ./split.py ~/pics/objects.png x.png
```

And it generates `x.png`:

![x](https://user-images.githubusercontent.com/580843/33234917-63f66e78-d226-11e7-9204-65de19210b3a.png)

It needs git master libvips.

**Comment by jindili** [comment]
Great job! John.

**Comment by jcupitt** [comment]
I'll close -- please reopen if you can't get it working once 8.6 is out.
