### ISSUE TITLE
How to run vips on Ubuntu

### ISSUE THREAD

**Issue by connelevalsam** [jcupitt/libvips#794]
Good day,
I followed the steps on downloading and installing. But from the part of using `make` , Ubuntu don't see the files.
Any help on how to run vips on Ubuntu?
I'm using Ubuntu 16.04LTS

**Comment by jcupitt** [comment]
Hello, Ubuntu has libvips built in, you just `apt-get install libvips` and it should work.

**Comment by connelevalsam** [comment]
after that, is there any thing else? cos the project i clone requires libvips. But it throws an error.

**Comment by jcupitt** [comment]
It's a standard Debian package, so you need `libvips-dev` if you want the C headers, and `libvips-tools` if you need the command-line executables. 

What project are you building? It may need a minimum libvips version number. You should check the version that Ubuntu installs.

**Comment by connelevalsam** [comment]
`config/config.go:113: cannot use &opt (type *badger.Options) as type badger.Options in argument to badger.Open
# pkg-config --cflags vips vips vips vips
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
pkg-config: exit status 1
`
don't understand where this is coming from

**Comment by jcupitt** [comment]
It's looking for the `.pc` file. This is a standard way to find project headers, and is installed as part of the `-dev` package, like any library.

Try:

```
sudo apt-get install libvips-dev
```

**Comment by connelevalsam** [comment]
okay I'll. It made ma partner use windows on this project.

**Comment by jcupitt** [comment]
OK, I'll close then. Good luck!
