### ISSUE TITLE
File formats support issues (PDF, HDR, SVS) in last versions

### ISSUE THREAD

**Issue by yurykovshov** [jcupitt/libvips#796]
Hi John,

I just wanted to do an update to 8.5.9 version. Suddenly some formats stopped working, like HDR, SVS, PDF. I went and checked:
![image](https://user-images.githubusercontent.com/7525042/32442282-2a3e1274-c2fb-11e7-882d-f64735835ee9.png)

Then I decided, ok let's go for a beta 8.6. But there:
![image](https://user-images.githubusercontent.com/7525042/32442336-575141d2-c2fb-11e7-95b2-1af5eb1ddfa8.png)
PDF stopped working.

Then I tried 8.5.8:
![image](https://user-images.githubusercontent.com/7525042/32442356-6c146130-c2fb-11e7-96a9-f6824409198e.png)

In the end, I decided to stay with 8.5.2 for a while and report this behavior.
Hope it helps.

Best,
Yury

**Comment by jcupitt** [comment]
Hello Yury, which version did you download? 

The `web` version only includes common file formats with well-tested and commercially free load libraries, so it should be safe to use even with hostile files. The `all` version has all the loaders, including ones which are insecure or which should not be used commercially.

https://github.com/jcupitt/libvips/releases/download/v8.5.9/vips-dev-w64-all-8.5.9.zip

**Comment by yurykovshov** [comment]
Ok, I checked.
8.5.9, 8.6 - was `web` version.
8.5.8 - `all`
Seems 8.5.2 is also `all`.

Ok, thanks, I got it.
