### ISSUE TITLE
When trying to trim image with no extra params, a 0-size image is returned

### ISSUE THREAD

**Issue by tstm** [jcupitt/libvips#797]
I'm using the following image with white borders as a test: https://tstm.info/kuvat/image.jpg

When I call the vips_find_trim with no extra options, I get 0 as the height and 0 was the width, which obviously could not work.

I'm trying to use libvips through bimg, but this seems to be on the vips side, the image is not trimmed correctly.

**Comment by jcupitt** [comment]
Hello, I tried with git master:

```
$ vips find_trim image.jpg 
14
14
491
490
```

Which libvips version are you using? Perhaps your bimg is using an older version?

**Comment by tstm** [comment]
The vips version was 8.5.7

Upgrading to the current master (8.6.0) at least removed this issue, and trim works fine.

**Comment by jcupitt** [comment]
That's good. Yes, `find_trim` is an 8.6 feature, so the 0, 0, 0, 0 you saw was probably bimg failing to find the operator.
