### ISSUE TITLE
Automatic Image Rectification

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#799]
Try to do Rectification of image like this:

![image](https://user-images.githubusercontent.com/73845/32688103-ae691e46-c705-11e7-8cfb-ffea5aed0030.png)

![image](https://user-images.githubusercontent.com/73845/32688067-cadd908a-c704-11e7-96a4-104b49d407a9.png)

from (2) to (3): I can use profile() to get the top and bottom edge, calculate transform and scale of each column and generate an xyz() map, then mapim() back to the original image.

Now I stuck at Process (1) to (2), How to align the points A, B, C, and D.
Anyone got some idea.

**Comment by jcupitt** [comment]
Hello, the major distortion here is perspective. You need to make a transform like this:

x' = Ax + By + Cxy + D
y' = Ex + Fy + Gxy + H

where (x, y) are coordinates in the image of the can, and (x', y') are coordinates in the undistorted image. [[A .. D], [E .. H]] is a matrix T. You need to find three points (perhaps the corners) in the distorted image, put them into a big equation, and solve for T by inverting. 

I would consider removing the curvature separately. You might need to model lens distortion too, it depends on the camera,

**Comment by jcupitt** [comment]
nip2 has a thing called `Perspective Distort` which does this. Load an image and select Toolkits / Image / Transform / Perspective Distort, then drag the four points to the corners of the can. I get this result:

![can-perspective](https://user-images.githubusercontent.com/580843/32729953-6b5df2a6-c87d-11e7-8738-e7560797b4eb.jpg)

which now just needs the curvature removed.

**Comment by jindili** [comment]
Work as expected:
![image](https://user-images.githubusercontent.com/73845/32753252-1588fc7e-c907-11e7-9977-5a673de43380.png)

**Comment by jcupitt** [comment]
I'll close, though this isn't really very automatic.
