### ISSUE TITLE
Writing GIF-files?

### ISSUE THREAD

**Issue by UnitedMarsupials** [jcupitt/libvips#802]
Shouldn't I be able to _create_ GIF-files? The Compuserve patent expired over 10 years ago, yet, when I try to:`vips invert foo.jpg roo.gif`, I get: `VipsForeignSave: "roo.gif" is not a known file format`...

Is that a:
 - [ ] misconfigure/miscompile on my part,
 - [ ] a deliberate omission,
 - [ ] or simply a missing feature?

**Comment by jcupitt** [comment]
Hello, libvips supports GIF load, but not GIF save. There has been talk of adding it, but it's not happened yet.

https://github.com/jcupitt/libvips/issues/620

**Comment by jcupitt** [comment]
I'll close, 620 should probably be the issue for this feature.

**Comment by rroller** [comment]
Supported now https://github.com/libvips/libvips/issues/1167
