### ISSUE TITLE
Manipulating JPEGs without reencoding

### ISSUE THREAD

**Issue by UnitedMarsupials** [jcupitt/libvips#804]
Some of the operations on JPEG-files (such as rotations by 90, or cropping) can be done without the expensive and quality-reducing decoding of the original and re-encoding of the result.

To my knowledge, only the `jpegtran` command-line utility can currently do this.

Am I wrong, and is VIPS already able to do that as well? Am I right, and VIPS ought to implement this functionality?

**Comment by jcupitt** [comment]
My feeling is this is out of scope. Things like this depend on very detailed knowledge of the file format and are best left to specialist projects.

**Comment by UnitedMarsupials** [comment]
_Arguably_ the library can offer the back-end implementers hooks for such shortcuts... But, if that's not done currently by VIPS, we'll have to do it ourselves in our application...

**Comment by jcupitt** [comment]
If you look at the `jpegtran` source, I think you'll see it's not using libjpeg, there's a lot of very specialised code in there for this task. We'd need to copy-paste all that, and then maintain it :( 

I would shell out to `jpegtran`, I think that's probably the most maintainable way to do this.
