### ISSUE TITLE
Vipsthumbnail scale if larger

### ISSUE THREAD

**Issue by prohtex** [jcupitt/libvips#807]
I'm trying to use vipsthumbnail to batch generate thumbnails. I'd like to use the "scale if larger than" functionality described in the documentation

> $ vipsthumbnail shark.jpg --size 200x
> Will resize to 200 pixels across, no matter what the height of the input image is.
>
> You can append < or > to mean only resize if the image is smaller or larger than the target.

My command

` vipsthumbnail` *.png -o %s.jpg[Q=90,optimize_coding] -s <5000

Which obviously does not work because "<" is a bash operator. Please help!

**Comment by jcupitt** [comment]
Hello @prohtex, you can stop bash interpreting the <>! characters with quotes, for example:

```
vipsthumbnail *.png -o %s.jpg[Q=90,optimize_coding] -s "<5000"
```

**Comment by prohtex** [comment]
Hi John, thanks I tried that but get this error:

VipsJpeg: Maximum supported image dimension is 65500 pixels

**Comment by jcupitt** [comment]
I should have tested your command. The `<` goes at the end, try:

```
vipsthumbnail *.png -o %s.jpg[Q=90,optimize_coding] -s "5000<"
```

It should have rejected the leading `<` as invalid syntax, I'll check.

**Comment by jcupitt** [comment]
Hey, no problem, I'm glad it's useful.
