### ISSUE TITLE
Corrupt pages with gifsicle optimized gif

### ISSUE THREAD

**Issue by chregu** [jcupitt/libvips#812]
I have this image http://files.chregu.tv/gifsicle.gif, generate with gifsicle from http://files.chregu.tv/animated.gif

when I now do (in php, but I guess it's the underlying vips library, that's why I'm posting it here)

```
$image = \Jcupitt\Vips\Image::newFromFile("gifsicle.gif", ['n' => -1]);
$image->pngsave("flat.png");
```
Then the frames/pages look not correct.

![flat](https://user-images.githubusercontent.com/47106/33121152-3d7d3d80-cf74-11e7-99bd-236cfe47ba1d.png)

**Comment by jcupitt** [comment]
Fixed in master, thanks!
