### ISSUE TITLE
vips dzsave to .dzi via python binding

### ISSUE THREAD

**Issue by oak-tree** [jcupitt/libvips#814]
Hey,
Is it possible to use `python` binding to generate `deepzoom`(and any other supported format) pyramid? I I did not find anything in python doc

Thanks!

**Comment by jcupitt** [comment]
Hello, sure, try:

```
john@kiwi:~/pics$ python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("k2.jpg")
>>> x.dzsave("something")
>>>
```

Docs here:

https://jcupitt.github.io/pyvips/vimage.html#pyvips.Image.dzsave

Or a bit more detail here:

http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-dzsave

**Comment by oak-tree** [comment]
Cool, thanks! great work!
