### ISSUE TITLE
Add option to override Exif

### ISSUE THREAD

**Issue by monostefan** [jcupitt/libvips#817]
I think it would be nice if libvips had an option to define a custom Exif metadata blob when saving to JPEG. Currently, Exif is only parsed when loading form a JPEG file and exported when saving to JPEG again. However, there is no way to load another image format, set Exif data and export to JPEG. The option could be added to `vips_jpegsave()` and maybe called `override_exif`. When setting this to `true`, vips would then reparse Exif data defined in `VIPS_META_EXIF_NAME` instead of updating it.

**Comment by monostefan** [comment]
If that option existed, it would have made adding [Exif support for tifig](https://github.com/monostream/tifig/commit/e748bf47fffb49c75188d9cb877b7bb9ce521d5d)  a lot easier :)

**Comment by jcupitt** [comment]
Hello, woah, that was a lot of work.

You're supposed to be able to set any exif metadata. I'll test it.

**Comment by monostefan** [comment]
Well you did most of the work :smile:. I only had to figure out how it works :smirk:.

**Comment by jcupitt** [comment]
I think you should be able to set any exif field. For example:

```python
import sys
import pyvips

x = pyvips.Image.new_from_file(sys.argv[1])
x.set_type(pyvips.GValue.gstr_type, "exif-ifd2-ApertureValue", "262144/65536")
x.write_to_file(sys.argv[2])
```

If I run:

```
$ python ~/try/exif.py k2.tif x.jpg
```

ie. try to set exif on a tif image with no exif, I get:

```
$ vipsheader -a x.jpg | grep -i aper
exif-ifd2-ApertureValue: 262144/65536 (4.00 EV (f/4.0), Rational, 1 components, 8 bytes)
```

Though it will only work for SHORT, LONG and RATIONAL fields that libexif knows about. It should probably support ASCII as well.

What fields do you need to set?

**Comment by monostefan** [comment]
I need to set ALL of them ;). I meant something different: When you have Exif data in it's pure form, it would be cool if you can inject them into an image. Something like:

```
VipsImage* img;
vips_tiffload("some_image.tiff", img);
vips_image_get_blob(VIPS_META_EXIF_NAME, NULL, exifData, exifDataLength);
vips_jpegsave(img, "out.jpg", "override_exif", true, NULL)
```

**Comment by jcupitt** [comment]
Ah, OK. Yes, that's not supported: it'll see the EXIF block but no expanded exif tags and assume you wanted them all deleted.

The simplest solution would be to add something like `vips_image_set_exif(image, exif-data)`, to set the exif blob and also expand out all the tags. Would that work?

**Comment by monostefan** [comment]
That would be great!

**Comment by jcupitt** [comment]
I thought some more, and I think adding some magic to the thing to set metadata is a better solution. There's no new API, and it actually simplifies the webp and jpg loaders.

Now setting a field called `VIPS_META_EXIF_NAME` will automatically also create a lot of other fields and set the image resolution. Thanks for suggesting this improvement, it should be in 8.6.

https://github.com/jcupitt/libvips/commit/9c8790b40aa4de3a486608a0495836a91fc6b2b9

**Comment by monostefan** [comment]
Nice idea! This reflects exactly what I intuitively assumed should be working before diving deeper into it. Great job, thank you very much!
