### ISSUE TITLE
compile to wasm

### ISSUE THREAD

**Issue by salzhrani** [jcupitt/libvips#818]
Is it possible to compile libvips to wasm? If possible it might be beneficial to node and the web.

**Comment by jcupitt** [comment]
Hello, I've never tried, but it might be possible. You'd need to build all the dependencies as well, like libjpeg.

There's a node binding here:

https://github.com/jcupitt/node-vips

It uses node-ffi to call into the C shared library. And of course sharp uses libvips:

http://sharp.dimens.io/en/stable/

It has it's own C++ layer for calling libvips from node.
