### ISSUE TITLE
Question for making a standalone version

### ISSUE THREAD

**Issue by peterLaurence** [jcupitt/libvips#819]
Hi,

I would like to use libvips in a standalone way for linux and windows platforms (to be used in an [electron](https://electronjs.org/) application, without requiring the user to install libvips), but i'm wondering how i could do this, since libvips has numerous dependencies on libraries installed on the OS. I don't need the whole library, just `vips dzsave` and `vipsthumbnail`. 
I already have libvips 8.3 install on my Ubuntu. 

Is is possible to do this? If so, could you give me some hints?

Thanks,
Peter

**Comment by jcupitt** [comment]
Hello Peter,

The Windows binary has no external dependencies, could you just add that as a subdirectory of your electron app? I think you'd just need the bin area: add that to the PATH and that should (might?) be it. There's a node-vips binding that just uses FFI which would make it simple to call.

https://github.com/jcupitt/node-vips

eg.

```javascript
var vips = require('vips');

var image = vips.Image.newFromFile(process.argv[2], {access: 'sequential'});
image.dzsave('mypyr', {layout: 'google'});

var image = vips.Image.thumbnail('huge.tif', 128);
image.writeToFile('tiny.jpg', {
  async: (err, result) => {
    if (err) {
      throw err;
    }
  }
});
```

Making a portable Linux binary is more complex. I think I'd look at flatpak for packaging, though perhaps electron has it's own system for this. 

You can build libvips with very few dependencies, the README has some tips. The only required ones are `glib2.0-dev` and `libexpat1-dev`. You'll need to add things like libjpeg / libjpeg-turbo / mozjpeg  depending on your exact needs. 

John

**Comment by jcupitt** [comment]
... I've not done much with node-vips, and I've never even tried electron, but I'd think it would be simple to move it across, as long as electron has some sort of FFI mechanism.

**Comment by jcupitt** [comment]
And I've not tried node-vips on Windows either, you'd need to at least adapt the library names.

**Comment by peterLaurence** [comment]
Thanks for your feedback. I didn't know about your node-vips project.
I've just seen the code where Windows would need some modifications (`vipsobject.js`).
So, do you think it would work if, for each platform, i embed the required libraries (like `'libgobject-2.0` on linux) so it won't require any installation?

**Comment by peterLaurence** [comment]
But indeed for Windows it looks simple. My concern is for linux. 
I had in mind to use node's [childprocess](https://nodejs.org/api/child_process.html#child_process_child_process), to directly call vips binary.

**Comment by peterLaurence** [comment]
Ok i just did it for linux. I took the output of `ldd vips` and copied all `.so` files.
Then, in a fresh Ubuntu virtual machine (with nothing installed) i copied `vips` along with all `.so` files in a folder. In a terminal i set the environment variable `LD_LIBRARY_PATH` to that folder. 
Then i could successfully `vips dzsave` an image. Great!
Anyway, i will also give a try to your node-vips project.

Thanks for your help.
-Peter

**Comment by jcupitt** [comment]
I think you'll find just copying the `.so` will work across some Ubuntu versions, but not all. And it may not work on other linuxes :( You'll need something like flatpak if you want a single work-anywhere binary.

Yes, just change the lib names for Windows. That's all ruby-vips needed anyway, and I'd expect it to be very similar. If you can get it working with something like:

```javascript
var libname;
if (platform === 'Windows') {
  libname = 'libgobject-2.0-0';
} else {
  libname = 'libgobject-2.0';
}
var libgobject = ffi.Library(libname, {
```

And submit a PR, that would be great!

You might need to change some other stuff for electron I guess.

**Comment by jcupitt** [comment]
The equivalent code in ruby-vips is here, fwiw:

https://github.com/jcupitt/ruby-vips/blob/master/lib/vips.rb#L22
