### ISSUE TITLE
Maximum intensity projection on an image stack

### ISSUE THREAD

**Issue by zoranpopovic** [jcupitt/libvips#822]
what's the best way to compute per-pixel maximim intensity image from an array of images?  i couldn't find a pairwise max operator.

**Comment by jcupitt** [comment]
Hello @zoranpopovic, would `bandrank` work for you?

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-bandrank

Alternatively, you can make your own with `ifthenelse` and `more`.

**Comment by jcupitt** [comment]
... for example, in Python:

```python
a = pyvips.Image.new_from_file(sys.argv[1])
b = pyvips.Image.new_from_file(sys.argv[2])

# band 1 of XYZ is Y
a_Y = a.colourspace("xyz")[1]
b_Y = b.colourspace("xyz")[1]

max_intensity = (a_Y > b_Y).ifthenelse(a, b)
```

**Comment by zoranpopovic** [comment]
thanks both of those should work, but which one would be faster with stack
of k images.  bandrank would be k log k per pixel operations since it does
the sorting (while we just need the max), where the pairwise ifthenelse
would run k-1 ifthenelse operations.

**Comment by jcupitt** [comment]
`bandrank` has a fast path for max and min, so it should be quicker, as long as it does what you need.

**Comment by jcupitt** [comment]
I tried a benchmark:

```python
import sys
import pyvips

images = [pyvips.Image.new_from_file(x, access='sequential')
          for x in sys.argv[2:]]
x = reduce(lambda a, b: (a > b).ifthenelse(a, b), images)
x.write_to_file(sys.argv[1])
```

Then with ten 10k x 10k pixel jpg images:

```
$ mkdir samples
$ for i in {1..10}; do cp ~/pics/wtc.jpg samples/$i.jpg; done
$ time python sort.py x.jpg samples/*
real	0m7.246s
user	0m10.858s
sys	0m0.280s
```

With bandrank I see:

```
$ time vips bandrank "samples/10.jpg samples/1.jpg samples/2.jpg samples/3.jpg samples/4.jpg samples/5.jpg samples/6.jpg samples/7.jpg samples/8.jpg samples/9.jpg" x.jpg --index 9
real	0m4.244s
user	0m15.382s
sys	0m0.189s
```

So bandrank is quicker, but it's not dramatic.

**Comment by jcupitt** [comment]
(of course that'll include a lot of jpg decode, so the difference in operation time is larger)

**Comment by zoranpopovic** [comment]
thanks it worked very well.  btw any reason why bandrank call through pyvips seems a bit unnatural with special treatment of the first item

`    mip_tile = slice_tiles[0].bandrank(slice_tiles[1:], index=len(slice_tiles)-1)`

**Comment by jcupitt** [comment]
Things like `bandjoin` work like this too, for example:

```python
a = b.bandjoin(255)
```

Meaning, add a constant 255 band to the end. I think the ideas was that `bandrank` should follow this same pattern, even though it's perhaps less natural.

You could call it directly:

```python
ranked = pyvips.Operation.call('bandrank', images, index=len(images) - 1)
```

**Comment by zoranpopovic** [comment]
So close.  it turns out bandrank has a limit of 64 slices.  we have about 400 slices all very large images.  when we tried to bandrank a batch of 60 and then do a final bandrank in each of the results, it runs out of memory doing the last dzdave bit.  is there a way to deallocate images from within python to free memory.  clearing the array doesn't seem to do it, perhaps GC doesn't know about vips memory allocation.  Or increase the memory bounds.   ideally, every time in the loop most of the memory should be freed.

`import pyvips

mips = []
for i in range(0,6):
    print "mip of 60 slices, step {}".format(i)
    slices = []
    for n in range(i*60, i*60+60):
        image = pyvips.Image.new_from_file('ir-{}.tif'.format(n), access='sequential')
        slices.append(image)
    mip = slices[0].bandrank(slices[1:], index=len(slices)-1) 
    mips.append(mip)

print "final mip composition"
mip = mips[0].bandrank(mips[1:], index=len(mips)-1)
mip.tiffsave("full.tiff", compression="lzw")  # this is just for testing
mips=[]
print "Writing out a a complete MIP into a deep zoom structure..."
mip.dzsave("full", depth="onetile", suffix=".tiff[compression=lzw]")`

**Comment by jcupitt** [comment]
Woah that's a lot of slices. I'll fix the 64 limit, I had no idea anyone could want more. 

It shouldn't run out of memory, that's curious. How large are the images you are working with?

**Comment by jcupitt** [comment]
I can see a possible problem in your code: you are writing the image out twice, but you've set `sequential` as the access mode, which only allows a single sweep through the source images.

I reworked your program like this:

```python
import sys
import pyvips

images = [pyvips.Image.new_from_file(filename, access='sequential')
          for filename in sys.argv[2:]]

def chunks(array, chunk_size):
    for i in range(0, len(array), chunk_size):
        yield array[i : i + chunk_size]

mips = [x[0].bandrank(x[1:], index=len(x) - 1)
        for x in chunks(images, 60)]

final = mips[0].bandrank(mips[1:], index=len(mips) - 1)

final.write_to_file(sys.argv[1])
```

So it assembles all the images from arg 2 onwards and writes to arg 1. I can run it like this:

```
$ mkdir samples
$ for i in {1..40}; do cp ~/pics/wtc.jpg samples/$i.jpg; done
$ VIPS_PROGRESS=1 time python rank.py x.jpg samples/*
$ VIPS_PROGRESS=1 python rank.py x.jpg samples/*
rank.py temp-83: 9372 x 9372 pixels, 4 threads, 9372 x 16 tiles, 128 lines in buffer
rank.py temp-83: done in 29.6s         
```

So it's ranking 40 10k x 10k pixel images in 550MB of memory. I'd guess 400 should take around 5.5GB.

It does seem high. It would be less if it used SMALLTILE, I'll see if I can fix it.

**Comment by jcupitt** [comment]
As a temporary workaround, you can write our each intermediate stage to disc. For example:

```python
import sys
import pyvips

images = [pyvips.Image.new_from_file(filename, access='sequential')
          for filename in sys.argv[2:]]

def chunks(array, chunk_size):
    for i in range(0, len(array), chunk_size):
        yield array[i : i + chunk_size]

n_blocks = 0
for chunk in chunks(images, 20):
    mip = chunk[0].bandrank(chunk[1:], index=len(chunk) - 1)
    print 'writing block {0} ...'.format(n_blocks)
    mip.write_to_file('{0}.v'.format(n_blocks))
    n_blocks += 1

mips = [pyvips.Image.new_from_file('{0}.v'.format(i), access='sequential')
        for i in range(0, n_blocks)]

final = mips[0].bandrank(mips[1:], index=len(mips) - 1)

print 'final write ...'
final.write_to_file(sys.argv[1])
```

Now run as:

```
$ VIPS_PROGRESS=1 python rank.py x.jpg samples/*
writing block 0 ...
rank.py temp-40: 9372 x 9372 pixels, 4 threads, 9372 x 16 tiles, 128 lines in buffer
rank.py temp-40: done in 14.1s          
writing block 1 ...
rank.py temp-142: 9372 x 9372 pixels, 4 threads, 9372 x 16 tiles, 128 lines in buffer
rank.py temp-142: done in 14.3s          
rank.py temp-250: 9372 x 9372 pixels, 4 threads, 9372 x 1 tiles, 128 lines in buffer
rank.py temp-250: done in 1.41s          
```

And it runs in 400mb of memory. That's in chunks of 20 images at once, you'll need to adjust that. You should obviously remove the temp files afterwards.

You can write to a deepzoom like this:

```
$ VIPS_PROGRESS=1 python rank.py full.dz[depth=onetile,suffix=.tiff[compression=jpeg]] samples/*
```

**Comment by jcupitt** [comment]
Of course it's better to open the source images in the loop, then Python gets a chance to GC them away during chunk processing:

```python
import sys
import pyvips

def chunks(array, chunk_size):
    for i in range(0, len(array), chunk_size):
        yield array[i : i + chunk_size]

n_blocks = 0
for filenames in chunks(sys.argv[2:], 20):
    images = [pyvips.Image.new_from_file(filename, access='sequential')
              for filename in filenames]
    mip = images[0].bandrank(images[1:], index=len(images) - 1)
    print 'writing block {0} ...'.format(n_blocks)
    mip.write_to_file('{0}.v'.format(n_blocks))
    n_blocks += 1

mips = [pyvips.Image.new_from_file('{0}.v'.format(i), access='sequential')
        for i in range(0, n_blocks)]

print 'final write ...'
final = mips[0].bandrank(mips[1:], index=len(mips) - 1)

final.write_to_file(sys.argv[1])
```

**Comment by jcupitt** [comment]
git master libvips will now run this:

```python
import sys
import pyvips

images = [pyvips.Image.new_from_file(filename, access='sequential')
          for filename in sys.argv[2:]]
mips = images[0].bandrank(images[1:], index=len(images) - 1)

mips.write_to_file(sys.argv[1])
```

On 400 images without problems. I found turning down the concurrency was the most effective way to reduce memory use:

```
$ VIPS_CONCURRENCY=1 VIPS_PROGRESS=1 python rank.py x.jpg samples/*
```

Runs in about 4gb. Concurrency 1 is a bit slow, you could try 2 or 3, depending on how much RAM you have.

**Comment by zoranpopovic** [comment]
Awesome, it works with chunking, and pretty fast.  Thanks for being the most awesomely responsive and thoughtful project owner ever!

**Comment by jcupitt** [comment]
Glad it's working!

**Comment by marcoaaz** [comment]
hello, sorry to disturb but could you explain how "samples/*" part of the code line would work on Windows 11 Anaconda Prompt?

I am getting the VipsForeignLoad: file "...\*"  does not exist traceback. Thanks!

**Comment by jcupitt** [comment]
Hi @marcoaaz,

On windows you need to do the globbing yourself, so you have to import the python globber and generate the file list from the pattern.

https://docs.python.org/3/library/glob.html

Or run your code inside WSL2, of course.
