### ISSUE TITLE
How can I change brightness and saturation?  

### ISSUE THREAD

**Issue by ismailbaskin** [jcupitt/libvips#825]
I think it would be done with tonelut function but I couldn't. Anyone can show https://www.imagemagick.org/script/command-line-options.php#modulate equivalent example?

**Comment by jcupitt** [comment]
Hello, you can use `linear` to multiply and add constants to each pixel:

```
$ vips linear in.jpg out.jpg 1.2 50 
```

Will multiply each pixel by 1.2 and add 50. It's more useful in something like LCh colourspace, where bands are lightness, chroma and hue. For example:

```
$ vips colourspace in.jpg x.v lch
$ vips linear x.v out.jpg "1.2 2 1" "0 0 50"  
```

Will multiply L (lightness) by 1.2, C (chroma, or colourfullness) by 2 and add 50 to h (hue).

**Comment by jcupitt** [comment]
Or in Python:

```python
x = x.colourspace('lch') * [1.2, 2, 1] + [0, 0, 50]
```
