### ISSUE TITLE
How to extract tiles from tiff file?

### ISSUE THREAD

**Issue by qingchaozhang** [jcupitt/libvips#826]
The tiff files I am using are more the 1GB, so I am planning to extract each tile to form many images. Which command of API shall I use?

**Comment by jcupitt** [comment]
Hello, just open the image and crop the area you need.

```python
x = pyvips.Image.new_from_file("huge.tif")
area = x.crop(left, top, width, height)
area.write_to_file("small.png")
```

Will pull out a small part of a large image efficiently.
