### ISSUE TITLE
libvips-42.dll missing in windows builds

### ISSUE THREAD

**Issue by wessorh** [jcupitt/libvips#827]
On Windows builds are missing libvips-42.dll which is referenced but appears to be missing.  Tested 8.6-beta2 on win7

**Comment by jcupitt** [comment]
Hello, it seems to be there for me:

```
john@kiwi:~/Desktop$ unzip -qq vips-dev-w64-all-8.6.0-beta2.zip
john@kiwi:~/Desktop$ find vips-dev-8.6/ -name libvips-42.dll
vips-dev-8.6/bin/libvips-42.dll
```

Which zip did you download?

**Comment by wessorh** [comment]
Ahh, thanks for that. I'm not familiar with windows and thought they would be under lib/ not bin/

apologies for the bug report.

**Comment by jcupitt** [comment]
No problem. Yes, there's `libvips-42.dll.a` under `lib`, which is the library with the stubs that you link against, and `libvips-42.dll` which has the actual code that sits in `bin`. You need lib at compile time and bin at runtime.

It feels very, very crude, if you're coming from a modern *nix :( The DLL system dates from the late 80s, I think. There's no run-time linker.
