### ISSUE TITLE
vips_image_hasalpha from c++

### ISSUE THREAD

**Issue by jtorresfabra** [jcupitt/libvips#829]
Hi I'm new to the library. 
Probably I'm missing the point, but is there a way to call hasalpha from the C++ wrapper or should I do it manually? (similar to https://gist.github.com/jcupitt/15324d7cec7ece0c63439c518b191baa#file-trans-cpp-L27-L48 )

Thanks!

**Comment by jcupitt** [comment]
Hello @jtorresfabra, I would drop down to C, something like:

```C++
VImage myimage = ...;

if (vips_image_hasalpha( myimage.get_image()))
    ...;
```

I agree a member function would be neater.

Are you blending images? 8.6 (out yesterday) has a new operator for this: it can combine an array of images with the PDF blend modes:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-composite

```C++
VImage blended = base->composite(overlay, VIPS_BEND_MODE_OVER);
```

**Comment by jtorresfabra** [comment]
Hi @jcupitt, thanks for the quick reply.
I indeed finally gone with the C function, but was hoping the wrapper had something in place.

> Are you blending images?
Still not, just checking out the library to study a replacement. Anyway good to know we have a new release in place :)

Thanks!
