### ISSUE TITLE
vipsthumbnail fails with incorrectly tagged images

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/libvips#831]
It seems that `vips_thumbnail` has some issues with processing a tagged CMYK image (with an RGB embedded profile?).

[Input image](https://t0.nl/information-theory.jpg)
[Extracted ICC profile](https://t0.nl/information-theory.icc) (for investigation; MD5 hash corresponds to the `AdobeRGB1998.icc` profile)

Tested with these ICC profiles:
https://github.com/jcupitt/nip2/blob/master/share/nip2/data/sRGB.icm
https://github.com/jcupitt/nip2/blob/master/share/nip2/data/cmyk.icm

**Input image to sRGB jpg**
```bash
vipsthumbnail information-theory.jpg \
    -o %s_thumbnail_srgb.jpg \
    --eprofile sRGB.icm
````

Warnings:
```bash
(vipsthumbnail:5544): VIPS-WARNING **: embedded profile incompatible with image
vipsthumbnail: unable to thumbnail information-theory.jpg
icc_import: no input profile
```

**Input image with an CMYK input profile to sRGB jpg**
```bash
vipsthumbnail information-theory.jpg \
    -o %s_thumbnail_cmyk_srgb.jpg \
    --iprofile cmyk.icm \
    --eprofile sRGB.icm
````

Warning:
```bash
(vipsthumbnail:5713): VIPS-WARNING **: embedded profile incompatible with image
```

Output (wrong):
![information-theory_thumbnail_cmyk_srgb](https://user-images.githubusercontent.com/12746591/33881742-08f004d6-df36-11e7-9eec-4dfcaca3bb7f.jpg)

I've also done some tests without the `--eprofile` flag and with the `--delete` / `--intent perceptual` flag, but I'm unable to process this particular image properly.

Tested with libvips 8.6.0.

**Comment by jcupitt** [comment]
I agree, this should work:

```
vipsthumbnail information-theory.jpg --iprofile ~/vips/share/nip2/data/cmyk.icm
```

And obviously does not. Stupid thing. I'll have a look. Thanks!

**Comment by jcupitt** [comment]
I've investigated a bit, and I think `vipsthumbnail`is working correctly. The problem is that your image is using inverted CMYK.

Try this:

```
john@kiwi:~/pics$ vips copy information-theory.jpg x.jpg[strip]
john@kiwi:~/pics$ convert x.jpg -negate -profile ~/vips/share/nip2/data/cmyk.icm -profile ~/vips/share/nip2/data/sRGB.icm y.jpg
```

ie. strip off the incorrect embedded profile, then invert and use a standard cmyk/rgb pair. You get this:

![y](https://user-images.githubusercontent.com/580843/34470113-8d908ec6-ef22-11e7-835b-b98a26dc3b94.jpg)

Which I think is correct.

**Comment by jcupitt** [comment]
This also works:

```
john@kiwi:~/pics$ vips invert information-theory.jpg x.jpg
john@kiwi:~/pics$ vipsthumbnail x.jpg --iprofile ~/vips/share/nip2/data/cmyk.icm
(vipsthumbnail:29056): VIPS-WARNING **: embedded profile incompatible with image
```

Making:

![tn_x](https://user-images.githubusercontent.com/580843/34470210-75870e5c-ef24-11e7-9aa7-4f6edb8b828a.jpg)

**Comment by kleisauke** [comment]
Ah OK, thanks for investigating! Inverting the image before processing it indeed fixes this. I'll close this issue.
