### ISSUE TITLE
VIPS 8.6 installs wrapper script as vips-8.5

### ISSUE THREAD

**Issue by bgilbert** [jcupitt/libvips#834]
Hi John, it seems VIPS 8.6 is still installing its wrapper script as `vips-8.5`.

(I had hoped to test packaging bumps during beta, but time got away from me...)

**Comment by jcupitt** [comment]
Oh dear, I always forget that. I've added a test to catch this in future.

Thanks!

**Comment by Chaibolog** [comment]
how to use it ?

**Comment by jcupitt** [comment]
Hello @Chaibolog, I'm not certain what you mean. Could you expand your question?
