### ISSUE TITLE
Question: band shuffling

### ISSUE THREAD

**Issue by jtorresfabra** [jcupitt/libvips#838]
Hi @jcupitt, 
Noob question here:
Is there a built-in function to do channel shuffling? 
like copy one image to another but with channels in a different order. (I'm comming from oiio so I'm looking for something similar to https://github.com/OpenImageIO/oiio/blob/master/src/include/OpenImageIO/imagebufalgo.h#L212-L241, 
or maybe something to easily reorder bands?

Thanks!

**Comment by jcupitt** [comment]
Hello @jtorresfabra, there are several ways to do it. You can use a combination of `extract_band` and `bandjoin`:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-extract-band

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-bandjoin

For example, in Python:

```python
r, g, b = image.bandsplit()
result = b.bandjoin([g, r])
```

or perhaps:

```python
result = image[2].bandjoin([image[1], image[0]])
```

You can also use `recomb` to multiply an image bandwise through a matrix:

```python
image = image.recomb([[0, 0, 1],
                      [0, 1, 0],
                      [1, 0, 0]])
```

Which will also reverse the bands.

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-recomb

**Comment by jtorresfabra** [comment]
Thanks, it will do the trick :)
