### ISSUE TITLE
Multi-threading broken when using vips_resize()

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#840]
The current version of `vips_resize()` seems to interfere with proper multi-threading of the VIPS processing pipeline.

This [gist](https://gist.github.com/aferrero2707/76d8ddeab88dd46a468746ef792dae1b) provides a minimal example to show the problem. The program opens an image from disk, applies a gaussian blur (to have some relatively heavy processing and see the CPU usage with top during at least few seconds), and then scales down the image with `vips_resize()`.

On my system, the CPU usage goes only slightly above 100%, well below the 400% I normally get with my 4-cores machine.

The origin of the bad multi-threading performance seems to be the introduction of a call to `vips_sequential()` in [reducev.cpp](https://github.com/jcupitt/libvips/blob/master/libvips/resample/reducev.cpp#L894). If I comment out this call, the example program is able to make use of all available four cores. The decrease in processing time is even more pronounced, almost 10x.

**Comment by jcupitt** [comment]
Hello Andrea, resize will always be slow with sequential sources, unfortunately, since it has to make sure it doesn't demand pixels out of order. If you open the image without the sequential access hint it should be faster.

**Comment by aferrero2707** [comment]
Thanks for the explanation! Now I understand the logic... however something is still not clear: when I open a Jpeg file with `vips_image_new_from_file( filename, NULL )` the resulting image is created with the sequential hint assigned. The same happens if I explicitly set the access to random (which according to the documentation is the default), like this:
`vips_image_new_from_file( filename, "access", VIPS_ACCESS_RANDOM, NULL )`.

In order to get a faster processing I have to explicitly remove the sequential hint, like this:
`vips_image_remove(image, VIPS_META_SEQUENTIAL)`

Is this normal?

**Comment by jcupitt** [comment]
Oh dear! No, that sounds like a bug, I'll have a look.

**Comment by jcupitt** [comment]
Here's a slightly cleaned-up version of your test prog:

```c
/* Benchmark example for vips_resize().
 *
 * gcc resize.c -Wall `pkg-config vips --cflags --libs`
 */

#include <stdio.h>
#include <vips/vips.h>

int
main(int argc, char **argv)
{
  VipsImage* image;
  VipsImage* x;

  GTimer *timer;
  gdouble elapsed;
  gulong micros;

  if(VIPS_INIT(argv[0]))
    vips_error_exit(NULL);

  if(!(image = vips_image_new_from_file( argv[1], NULL )))   
    vips_error_exit(NULL);  

  if(vips_gaussblur(image, &x, 20, NULL))  
    vips_error_exit(NULL);  
  VIPS_UNREF(image);
  image = x;

  if(vips_resize(image, &x, 0.999, NULL))    
    vips_error_exit(NULL);  
  VIPS_UNREF(image);
  image = x;

  timer = g_timer_new ();
  if(vips_jpegsave(image, "test.jpg", NULL))
    vips_error_exit(NULL);
  elapsed = g_timer_elapsed (timer, &micros);
  g_timer_destroy (timer);
  printf("Jpeg image saved in %f\n", elapsed);

  return 0;
}
```

It seems to work for me now, and you're right, it's a huge speedup. Nice!

**Comment by aferrero2707** [comment]
Thanks! I confirm that the current git master behaves as expected: the resize operation uses all CPU cores also when the sequential access hint is not explicitly removed.

I guess we can close the issue. What should I do in my code until the fix gets propagated to the package repositories? Would it be safe to use
`vips_image_new_from_file( filename, "access", VIPS_ACCESS_RANDOM, NULL )`
and explicitly remove the sequential access hint with
`vips_image_remove(image, VIPS_META_SEQUENTIAL)`?

**Comment by jcupitt** [comment]
Sure, do that just after load if access is random.
