### ISSUE TITLE
Pixel normalization

### ISSUE THREAD

**Issue by jtorresfabra** [jcupitt/libvips#843]
Hi, 

I'm working with normal maps and I need to "normalize" the pixel values (meaning vector normalization). So I need to traverse all the pixels in the image to process them. 

What is the preferred way? I guess the way to go is getting the full image region with  `vips_region_prepare()` and then traverse using the pointer. Is this ok?

I also wondering if implementing a new operation would be good.

Sorry if the question is dumb, still getting used and I don't want to miss the point.

**Comment by jcupitt** [comment]
Could you explain exactly what you need to compute? Do you just need:

```
out = in / max in
```

Or are these complex values and you need the unit vectors?

In any case, you can just enter the equation and libvips will do the looping for you. For example, in Python:

```python
image = pyvips.Image.new_from_file(somefilename)
image = image / image.max()
```

**Comment by jtorresfabra** [comment]
Thanks for your ultrafast response @jcupitt  
I need to calculate the unitary vector as p'=p/|p|. being x a pixel with(x, y, z) values. So 
`x'= x/ sqrt(x*x + y*y +z*z) 
y' =...`
 I'm coding in C/C++ .

**Comment by jcupitt** [comment]
Ah OK. There's a thing to calculate the 2D unit vector, but not 3D.

I would implement as a simple C++ expression at first, then rewrite as a dedicated operator if you find you have performance problems. You could expect a dedicated operator to be about twice as fast.

If you have an image `p` with three bands, you can compute `pprime`, the image of unit vectors, with:

```
VImage square = p * p;
VImage magnitude = (square[0] + square[1] + square[2]).pow(0.5);
VImage pprime = p / magnitude;
```

`.pow(0.5)` will be a bit slow :-( it'd be better to have a dedicated `.sqrt()` method.

**Comment by jcupitt** [comment]
In case it's not obvious, the C++ above will build a libvips pipeline for you that computes the unit vectors. 

libvips pipelines pretty efficient -- you typically get only a 2x speedup if you rewrite in C++, and of course the dedicated operator version will be much larger and much more annoying to maintain.

**Comment by jtorresfabra** [comment]
Ok I see, 
so I can operate full bands instead of traverse pixels, it looks very good. I'm starting to love the library :). 

Thanks @jcupitt !

**Comment by jtorresfabra** [comment]
Still not sure how can I replace (0,0,0) values by (0,0,1)

**Comment by jtorresfabra** [comment]
@jcupitt works like a charm!

**Comment by jcupitt** [comment]
You want to find all (0, 0, 0) pixels and swap them for (0, 0, 1)?

**Comment by jtorresfabra** [comment]
Yes that's it.

**Comment by jcupitt** [comment]
You have to use `==` to look for zeros in each band, then AND the bands together (you want all bands zero), then use `ifthenelse` to switch between the image and the constant (0, 0, 1).

```C++
VImage zeros = (p == 0).bandbool(VIPS_OPERATION_BOOLEAN_AND);
std::vector<double> zerozeroone = to_vectorv(3, 0.0, 0.0, 1.0);
VImage swap = zeros.ifthenelse(zerozeroone, p);
```

It's a little cleaner in Python:

```python
swap = (p == 0).bandand().ifthenelse([0, 0, 1], p)
```

C++11 has much better support for constants like (0, 0, 1), but libvips C++ predates that, sadly.

**Comment by jtorresfabra** [comment]
ok  understood. thanks you very much!

**Comment by jcupitt** [comment]
No problem -- good luck!

**Comment by jtorresfabra** [comment]
I think I'm experimenting some kind of gamma correction when writting to jpeg, as the final image value pixels are not the expected ( I'm talking about the 0,0,1 values). 
Also I think for my needs I will really need to implement a dedicated operator. I need it to be as fast as possible (it will operate in cloud servers) and I'm getting a hard time to really get the expected values. So I think I really need to operate through pixel values. 
Where can I start to get inspiration to write my own operator?
Thanks

**Comment by jcupitt** [comment]
There's a chapter in the docs about writing new operators:

http://jcupitt.github.io/libvips/API/current/extending.html

And a gist here:

https://gist.github.com/jcupitt/d8a263171a9ad4e4416b7e313ed879bc

If that's any help.

The (0, 0, 1) thing should work. Post your code and I can have a look.

**Comment by jtorresfabra** [comment]
> If you have an image p with three bands, you can compute pprime, the image of unit vectors, with:
> 
> VImage square = p * p;
> VImage magnitude = (square[0] + square[1] + square[2]).pow(0.5);
> VImage pprime = p / magnitude;

Could it be that I'm getting undefined results when magnitude == 0?
