### ISSUE TITLE
Losing orientation after vips_copy()

### ISSUE THREAD

**Issue by surlac** [jcupitt/libvips#844]
After rotating an image with vips_autorot() and copying it with vips_copy(), we're losing an orientation on vips_jpegsave() of a new image. Is this expected?

**Comment by jcupitt** [comment]
Hello, do you mean you've lost the orientation tag, or the image has not rotated? autorot will flip the image upright and remove the orientation tag, so expected behaviour is a rectified image and no tag.

Could you post sample source code and a test image that shows the incorrect behaviour?

**Comment by surlac** [comment]
It was an issue in our logic. Thanks @jcupitt for the prompt response and sorry for bothering. Closing.
