### ISSUE TITLE
How to load image from an URL

### ISSUE THREAD

**Issue by sonyarianto** [jcupitt/libvips#845]
I already look at google but have no luck, can libvips load image from URL then process it later?

**Comment by jcupitt** [comment]
Hello, libvips can load from files on disc or from memory buffers. There's no support for loading from URIs.

You'd need to use your platform's URI-load function to load to a memory area, then use libvips to load from that.

**Comment by data-man** [comment]
@sonyarianto 
E.g. you can to use the [curl](https://github.com/curl/curl) library.
See [example](https://github.com/curl/curl/blob/master/docs/examples/getinmemory.c).

**Comment by sonyarianto** [comment]
@jcupitt Thanks :)
@data-man Thanks :)

I love VIPS :) From GD, Imagick now starts using VIPS
