### ISSUE TITLE
Could I use vips dzsave to create tiles like gdal2tiles ?

### ISSUE THREAD

**Issue by mdartic** [jcupitt/libvips#847]
I'm trying to find a way to create tiles from a GeoTIFF files (2000x2000 px), by generating zoom level from 0 to 16.
The aim is to display a radar image on a leaflet map, so to create png tiles (256x256) georeferenced.

I'm using gdal2tiles, but it's not as performant as I want, and vips is really fast, but I think it doesn't recognize projection inside geotiff ?

Could you tell me if there is an option in vips to create tiles with a projection system ?

(and big thanks for your lib ! really awesome !)

**Comment by jcupitt** [comment]
Hello @mdartic,

Sorry, there's nothing to interpret geotiff tags, you'd need to write it. It wouldn't be that hard: you just need to write a bit of Python (or whatever) that implemented the transform you want. Something like:

```python
def transform(x, y):
    return (x * 2 + y, y * 2 + x)
```

for example, ie. a coordinate transform function. There's a libvips operation called `mapim` which will map an image efficiently through something like that. 

You could also use gdal to apply the transform and generate a flat image, then use `dzsave` to make the pyramid. That might be simpler.

**Comment by mdartic** [comment]
Ok, thanks for your advice !
