### ISSUE TITLE
'Corrupted' Jpeg tiling

### ISSUE THREAD

**Issue by bender22** [jcupitt/libvips#848]
I've got an image (http://sources.smartinmedia.com/8b2efeb8-0a18-4776-8e36-8732712a3932.jpg) which seems to be corrupted and vips cannot tile or thumbnail it, giving the following warnings:

vips warning: VipsJpeg: read gave 1 warnings
vips warning: VipsJpeg: Corrupt JPEG data: 24242 extraneous bytes before marker 0xed

I don't know how the image was generated, but IrfanView shows the image easily. Any guesses how to fix it and process with vips (flags to ignore extra bytes etc)?

**Comment by jcupitt** [comment]
Hello @bender22,

Which libvips are you using? 8.6 revised the libvips policy on warnings vs. errors and how they are handled. If I try your image here, I see:

```
$ vipsthumbnail corrupt.jpg 

(vipsthumbnail:28024): VIPS-WARNING **: read gave 1 warnings

(vipsthumbnail:28024): VIPS-WARNING **: VipsJpeg: Corrupt JPEG data: 24242 extraneous bytes before marker 0xed


(vipsthumbnail:28024): VIPS-WARNING **: read gave 1 warnings

(vipsthumbnail:28024): VIPS-WARNING **: VipsJpeg: Corrupt JPEG data: 24242 extraneous bytes before marker 0xed
VipsJpeg: Corrupt JPEG data: 24242 extraneous bytes before marker 0xed


(vipsthumbnail:28024): VIPS-WARNING **: read gave 1 warnings

(vipsthumbnail:28024): VIPS-WARNING **: VipsJpeg: Corrupt JPEG data: 24242 extraneous bytes before marker 0xed
VipsJpeg: Corrupt JPEG data: 24242 extraneous bytes before marker 0xed
VipsJpeg: Corrupt JPEG data: 24242 extraneous bytes before marker 0xed

$ vipsthumbnail --vips-version
libvips 8.6.2-Thu Jan 11 11:53:03 UTC 2018
```

So lots of annoying warnings, but it does work.
