### ISSUE TITLE
vips 8.6.1 fails to read 16bit tiff with lab colour space

### ISSUE THREAD

**Issue by DaGaMs** [jcupitt/libvips#850]
I just tested the newest version of vips and I'm running into numerous issues. Here's one:

The attached image (zipped so it can be uploaded here) used to process fine with an older version of vips (8.5.0). But now, I get this:

    $> vipsthumbnail -s 120 -f test.png tiff_16-bit-lab_example.tiff 

    (vipsthumbnail:45520): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

    (vipsthumbnail:45520): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

    (vipsthumbnail:45520): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

    (vipsthumbnail:45520): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

    (vipsthumbnail:45520): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

    (vipsthumbnail:45520): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

    (vipsthumbnail:45520): VIPS-WARNING **: profile 'icc': 'Lab ': invalid ICC profile color space
    vipsthumbnail: unable to thumbnail tiff_16-bit-lab_example.tiff
    vips2png: unable to write "test.png"

[tiff_16-bit-lab_example.tiff.zip](https://github.com/jcupitt/libvips/files/1623349/tiff_16-bit-lab_example.tiff.zip)

**Comment by jcupitt** [comment]
Hello @DaGaMs, it seems to be working for me with git master 8.6:

```
$ vipsthumbnail tiff_16-bit-lab_example.tiff 

(vipsthumbnail:4735): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

(vipsthumbnail:4735): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

(vipsthumbnail:4735): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

(vipsthumbnail:4735): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

(vipsthumbnail:4735): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

(vipsthumbnail:4735): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

(vipsthumbnail:4735): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

(vipsthumbnail:4735): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
$ vipsthumbnail --vips-version
libvips 8.6.2-Thu Jan 11 11:53:03 UTC 2018
```

![tn_tiff_16-bit-lab_example](https://user-images.githubusercontent.com/580843/34836415-beb1ce8c-f6ef-11e7-9495-8d0f7b3e51a2.jpg)


I'll try with 8.6.1 as released.

**Comment by DaGaMs** [comment]
Maybe an issue with different `libtiff`? I installed using brew on mac, so my libtiff should be 4.0.9

**Comment by jcupitt** [comment]
I have:

```
john@yingna ~/GIT/libvips (8.6) $ pkg-config libtiff-4 --modversion
4.0.8
john@yingna ~/GIT/libvips (8.6) $ pkg-config lcms2 --modversion
2.7
```

I built the 8.6.1 tarball and that's working too. I'll try libtiff 4.0.9.

**Comment by jcupitt** [comment]
It's working for me with libtiff 4.0.9 as well.

I'll try on my mac at home tonight.

**Comment by DaGaMs** [comment]
I'm just trying a recompile from source via brew - maybe it was the bottled version that was built against a different libtiff?

**Comment by DaGaMs** [comment]
No, recompiling from source against the most recent libtiff (4.0.9_1) did not help, still getting the same error. I couldn't try an older libtiff, because of dependency hell. Could  you let me know if it works on your mac at home?

**Comment by jcupitt** [comment]
Sorry, I didn't get a chance to test last night, I'll try again tonight.

**Comment by DaGaMs** [comment]
ok, I finally managed to compile against an older version of libtiff (4.0.8) and that fixes the issue. I have no idea why the bottled version of libtiff 4.0.9 causes these problems.
