### ISSUE TITLE
dzsave *.szi results in *.zip

### ISSUE THREAD

**Issue by martinweihrauch** [jcupitt/libvips#852]
Dear John:
When executing dzsave <inputfile> <outputfile.szi>, the outputfile is always *.zip. Could you change that that the outcome is *.szi?
Thx
Martin

**Comment by jcupitt** [comment]
Hello @martinweihrauch, I'll try to get to these this week.

**Comment by jcupitt** [comment]
Hi again Martin, I fixed this one in a branch. Let's add the other szi features at the same time.
