### ISSUE TITLE
SZI new format support

### ISSUE THREAD

**Issue by martinweihrauch** [jcupitt/libvips#853]
Dear John:
Could you add support for the newly "refurbished" SZI format. In essence, it now also contains the "associated images" (which are also delivered by the OpenSlide library) and are urgently needed in digital pathology (e. g. to show the entire glass slide with label, etc).
If possible, it would be great, if you also support the new "scan-properties.xml", but if that's too much work, then vips-properties suffice. Enclosed is a ZIP archive with the complete description of SZI (PDF) and example files.

thx
Martin
[SZI_DESCRIPTION_1.0.zip](https://github.com/jcupitt/libvips/files/1625419/SZI_DESCRIPTION_1.0.zip)

**Comment by jcupitt** [comment]
Hello, sorry, I think this will be hard to support directly in libvips as part of dzsave. The problem is that dzsave just saves a single image. It does not have access to things like the associated images that the openslide loader can provide.

You'd need to write a short program in Python or whatever to put all the images out of openslide and write them into a zip container.

**Comment by jcupitt** [comment]
I've been thinking about this a little more:

1. I'll add the `scan-properties.xml`, that should be easy.

2. Are you sure you want LGPL for the file format? I would suggest one of the CC licences instead I think: https://en.wikipedia.org/wiki/Creative_Commons_license

3. For the associated images, I think we'd need to add a flag to the openslide reader to directly attach all associated images as metadata. You could then do something like:

```
vips copy x.svs[attach_associated] x.szi
```

and the szi file could be written with the associated images inside.

**Comment by jcupitt** [comment]
The layout of deepzoom tiles is a little more complex than your docs suggest, since they have two-pixel overlaps (or each tile has a one pixel margin, alternatively). Additionally, edge tiles are written even if they contain new pixels, which I find very confusing.

**Comment by jcupitt** [comment]
It writes a very basic scan-props now:

```
<?xml version="1.0"?>
<image xmlns="http://www.pathozoom.com/szi" date="2018-01-26T17:19:38.331508Z" v
ersion="1.0">
  <properties>
    <property>
      <name>Vendor</name>
      <value type="str">aperio</value>
    </property>
    <property>
      <name>ObjectiveMagnification</name>
      <value type="str">20</value>
    </property>
    <property>
      <name>MicronsPerPixelX</name>
      <value type="str">0.499</value>
    </property>
    <property>
      <name>MicronsPerPixelY</name>
      <value type="str">0.499</value>
    </property>
  </properties>
</image>
```

**Comment by jcupitt** [comment]
I fixed it up a bit more, scan-props is now:

```
<?xml version="1.0"?>
<image xmlns="http://www.pathozoom.com/szi" date="2018-01-27T12:42:39.468301Z" ve
rsion="1.0">
  <properties>
    <property>
      <name>Vendor</name>
      <value type="VipsRefString">aperio</value>
    </property>
    <property>
      <name>ObjectiveMagnification</name>
      <value type="VipsRefString">20</value>
    </property>
    <property>
      <name>MicronsPerPixelX</name>
      <value type="VipsRefString">0.499</value>
    </property>
    <property>
      <name>MicronsPerPixelY</name>
      <value type="VipsRefString">0.499</value>
    </property>
    <property>
      <name>ImageWidth</name>
      <value type="gint">46000</value>
    </property>
    <property>
      <name>ImageHeight</name>
      <value type="gint">32914</value>
    </property>
  </properties>
</image>
```

I think that's the best I can do. The other fields you have in the spec are not exposed by openslide.

I noticed you recommended overlap=0 in the spec. I think I would remove this advice: at least some deepzoom viewers will not work well with overlap=0, and maximum compatibility with deepzoom is important. I'd stick with the deepzoom default of overlap=1.

Next, I'll see if I can get openslide load to attach the associated images.

**Comment by jcupitt** [comment]
Oh, I used ISO 8601 date format everywhere, I hope that's OK.

**Comment by jcupitt** [comment]
I added associated images too, so I now see:

```
john@kiwi:~/pics/openslide/szi$ vips dzsave ../CMU-1.svs[attach-associated] x.szi
john@kiwi:~/pics/openslide/szi$ unzip -qq x.szi
john@kiwi:~/pics/openslide/szi$ ls x
associated_images  scan-properties.xml  x.dzi  x_files
john@kiwi:~/pics/openslide/szi$ ls x/associated_images/
label.jpg  macro.jpg  thumbnail.jpg
```

I'll make a test windows binary.

**Comment by jcupitt** [comment]
That's using the openslide names for the associated images rather than the names in your spec, by the way. I think it would probably be best to change the szi spec to match openslide.

**Comment by jcupitt** [comment]
Summary of suggested changes to the SZI spec:

* use ISO 8601 dates everywhere
* use the openslide names for the associated images (label.jpg,  macro.jpg,  thumbnail.jpg)
* follow the deepzoom spec and use overlap=1
* change the SZI spec licence to CC
* value nodes in XML should record value type

**Comment by jcupitt** [comment]
Win binary here:

https://github.com/jcupitt/libvips/releases/tag/v8.7.0

**Comment by jcupitt** [comment]
.. if you get a chance to test it, that would be great.

**Comment by martinweihrauch** [comment]
Dear John:
Thanks a lot for all your efforts! I really appreciate that as this adds great advances to the digital microscopy community!
We will implement everything as suggested by you except the overlap.
In our products, we currently use OpenLayers, which is a lot more powerful than the (weakly supported) OpenSeaDragon. OpenLayers does not support any overlap and even with SeaDragon I have NEVER seen any gaps with overlap=0. 

Again, thanks - I will contact you with the revised SZI document!

**Comment by harukizaemon** [comment]
@jcupitt Any idea why DZI supports an overlap? Do you think it's particularly useful for e.g. reducing artefacts caused by rounding on images with sizes that aren't a power of 2? Or is it for some other reason?

**Comment by jcupitt** [comment]
I think the is the explanation people usually link:

http://benvanik.tumblr.com/post/13978156533/tile-overlap

An overlap makes it possible for a viewer to implement smooth zooming with filtering and never have visible seams.

**Comment by martinweihrauch** [comment]
John:
Could you agree to make overlap=0 the default for vips? We have used this since 2013 now with different viewers and never had a problem with any of our slides and 10s of thousands of happy users (Smart Zoom and EasyZoom)?
This would be great!

I change the other stuff as recommended by you

**Comment by jcupitt** [comment]
Just for SZI format, you mean? Yes, we could do that, but there are two problems (in my opinion):

1. At the moment you can convert SZI to DeepZoom by just unzipping, which I think is a really nice feature. If you set overlap=0 for SZI, the pyramids will be less like a standard DeepZoom and you might see compatibility problems.

2. With overlap=0, you will see seams if you try to use smooth zoom (rather than zoom in fixed steps) with interpolation. I know you don't do this now, but overlap=0 would make it impossible to add smooth zoom to any SZI viewer in the future.

**Comment by jcupitt** [comment]
Hello, is this done? Please reopen if not.

**Comment by jrochkind** [comment]
Is there any currently available documentation specifying SZI format, is anyone maintaining that? @martinweihrauch ?

**Comment by jcupitt** [comment]
Yes, it's here: https://github.com/smartinmedia/SZI-Format
