### ISSUE TITLE
BC break in 8.6.1

### ISSUE THREAD

**Issue by remicollet** [jcupitt/libvips#854]
Diffing API between 8.6.0 to 8.6.1 show an ABI and API breakage

See https://rpms.remirepo.net/compat_reports/libvips/8.6.0_to_8.6.1/compat_report.html

```
- vips_window_ref ( struct _VipsImage* im, int top, int height )  
+ vips_window_ref ( struct VipsWindow* window, struct _VipsImage* im, int top, int height )
```

**Comment by jcupitt** [comment]
Hi Remi, thanks for the report!

`vips_window_ref()` is not supposed to be part of the public API. I'll see if I can move it outside the visible headers, though of course this would be a break too :-(

**Comment by remicollet** [comment]
Indeed, I notice this in the "private" header file (perhaps should not be istalled)
Need to check why the symbol is visible as not exported...

**Comment by jcupitt** [comment]
Hopefully that reverts the change. Thanks for pointing this out!

**Comment by jcupitt** [comment]
8.6.2 is out now with this fix (I hope). I'll close.
