### ISSUE TITLE
trouble with Zeiss multi-channel 12-bit file

### ISSUE THREAD

**Issue by DaGaMs** [jcupitt/libvips#855]
Here's another one of my test-cases that is failing with newer versions of libvips. This used to work back in version 8.4.6, afaik. Now, I'm getting:

    $ vipsthumbnail -s 120 -f test.png test/example_data/zeiss_710_3_channel_1024x1024_12bit.lsm 

    (vipsthumbnail:17819): VIPS-WARNING **: Unknown field with tag 34412 (0x866c) encountered

    (vipsthumbnail:17819): VIPS-WARNING **: Unknown field with tag 34412 (0x866c) encountered

    (vipsthumbnail:17819): VIPS-WARNING **: Unknown field with tag 34412 (0x866c) encountered

    (vipsthumbnail:17819): VIPS-WARNING **: Unknown field with tag 34412 (0x866c) encountered

    (vipsthumbnail:17819): VIPS-WARNING **: Unknown field with tag 34412 (0x866c) encountered

    (vipsthumbnail:17819): VIPS-WARNING **: Unknown field with tag 34412 (0x866c) encountered

    (vipsthumbnail:17819): VIPS-WARNING **: Unknown field with tag 34412 (0x866c) encountered

    (vipsthumbnail:17819): VIPS-WARNING **: Unknown field with tag 34412 (0x866c) encountered

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 0

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 0

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 0

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 10

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 20

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 30

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 40

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 50

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 60

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 70

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 80

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 90

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 100

    (vipsthumbnail:17819): VIPS-WARNING **: error in tile 0 x 110
    vipsthumbnail: unable to thumbnail test/example_data/zeiss_710_3_channel_1024x1024_12bit.lsm
    test/example_data/zeiss_710_3_channel_1024x1024_12bit.lsm: 65535: Sample out of range, max 3
    tiff2vips: read error
    vips2png: unable to write "test/example_data/test.png"

[zeiss_710_3_channel_1024x1024_12bit.lsm.zip](https://github.com/jcupitt/libvips/files/1626622/zeiss_710_3_channel_1024x1024_12bit.lsm.zip)

**Comment by DaGaMs** [comment]
I should say that I tested this on ubuntu with libtiff 4.0.6 and on my mac with libtiff 4.0.8, with the same result

**Comment by jcupitt** [comment]
8.6.2 is out now with this fix.
