### ISSUE TITLE
Collage Making Support

### ISSUE THREAD

**Issue by vikasjio** [jcupitt/libvips#856]
Does libvips supports collage making? (I searched but seems it does not support).
If yes, plz share some relevant links; else plz share the roadmap and kindly suggest some alternate libraries/tools for this purpose.

Context: We are using libvips for image transcoding to jpeg and now want to create collages for some statically or dynamically selected related images.

Regards,
Vikas

**Comment by jcupitt** [comment]
Hello, could you explain what you mean by collage support?

1. You can use `arrayjoin` to join many images into a regular 2D mosaic. I've joined 30,000 images this way. It has options for things like alignment, background and spacing. You can do this at the command-line.

2. You can use `insert` to place images at any position within a large canvas. You can use `composite` as well if you need alpha blending, though it's a little harder. You'd need to use something like pyvips for this.

I made an example for someone on stackoverflow a few weeks ago:

https://stackoverflow.com/questions/47852390/making-a-huge-image-mosaic-with-pyvips

That loads a few 100 images, resizes them down to 128 x 128 pixels, then analyzes the colour of each and assembles them into a large mosaic that looks (from a distance) like another image.

**Comment by vikasjio** [comment]
Thanks @jcupitt.

collage is like composing/creating a single (usually large) image from many diverse/similar images or clippings, text etc.

Will see these. Meanwhile I had stumbled upon ImageMagick's montage and composite.

Thanks,
Vikas

**Comment by jcupitt** [comment]
I guess `arrayjoin` then:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-arrayjoin

```
vips arrayjoin "big.jpg corrupt.jpg nina.jpg theo.jpg tn_corrupt.jpg tn_tiff_16-bit-lab_example.jpg x.jpg" y.tif --across 4
```
