### ISSUE TITLE
What is the vipsthumbnail equivalent for imagemagick resize like this...

### ISSUE THREAD

**Issue by volkan** [jcupitt/libvips#857]
Hi,

I want use resize function and fill own size box. But I can't.  

This function is very easy for imagemagic. How can I handle it? (python code)

```bash
convert logo: -resize 80x80\> \
          -size 80x80 xc:blue +swap -gravity center  -composite \
          space_resize.jpg
```

![resize](http://www.imagemagick.org/Usage/resize/space_resize.jpg "")

[resize](http://www.imagemagick.org/Usage/resize/)

Thanks

**Comment by jcupitt** [comment]
Hello @volkan, in pyvips you could do it like this:

```python
#!/usr/bin/python

import sys
import pyvips

# shrink image to fit within a 80x80 area ... after this, the longest side 
# will be 80 pixels; the other side may be smaller
image = pyvips.Image.thumbnail(sys.argv[1], 80, height=80)

# "gravity" places an image within a larger image ... it has various ways of
# creating the new pixels, but the simplest is just painting with a solid
# colour
image = image.gravity("centre", 80, 80,
                      extend="background",
                      background=[0, 0, 255])

image.write_to_file(sys.argv[2])
```

**Comment by volkan** [comment]
@jcupitt thank you. Very helpful. 
By the way I want to use transparent backround, is it possible?

**Comment by jcupitt** [comment]
Docs:

http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-gravity

I tried on this PC. With this test image:

http://www.rollthepotato.net/~john/theo.jpg

I see:

```
$ time convert ~/pics/theo.jpg -resize 80x80\> -size 80x80 xc:blue +swap -gravity center -composite x.jpg
real	0m0.535s
user	0m1.208s
sys	0m0.149s
peak mem 301mb
$ time ./resize.py ~/pics/theo.jpg x.jpg
real	0m0.178s
user	0m0.165s
sys	0m0.013s
peak mem 33mb
```

Though IM would speed up a lot with shrink-on-load enabled. Both make this jpg:

![x](https://user-images.githubusercontent.com/580843/34942522-e31c9f92-f9ef-11e7-8ad9-66bf8fc0ad08.jpg)

**Comment by jcupitt** [comment]
Sure, write as PNG and use something like `[0, 0, 128, 128]` for the background. The final number is transparency (the A from RGBA).

**Comment by jcupitt** [comment]
Actually, that doesn't work. Add an alpha to the image, then use gravity.

```
image = pyvips.Image.thumbnail(sys.argv[1], 80, height=80)
image = image.bandjoin(255)
image = image.gravity("centre", 80, 80,
                      extend="background",
                      background=[0, 0, 255, 50])
```

seems to work fine.

**Comment by jcupitt** [comment]
The `api` branch of pyvips is a bit quicker, fwiw:

```
$ time ./resize.py ~/pics/theo.jpg x.png
real	0m0.115s
user	0m0.107s
sys	0m0.008s
```

**Comment by volkan** [comment]
@jcupitt, I test  it is working perfectly.

**Comment by sonyarianto** [comment]
any sample for this in CLI ?
