### ISSUE TITLE
option for interpolator for dzsave

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#859]
So I have perhaps a rather obscure requirement and thus I would not be at all offended if you said "no way, you have to be kidding me!"

We have rather large segmented images we produce with between 2 an 8 phases. They images are exceptionally large (100s of MB) and so we are converting them to DZI (using .png) for display purposes using a custom DZI viewer that allows us to, among other things, apply custom colours to phases as well as turn specific phases on/off.

Unfortunately, once the tiles start being shrunk, it appears a 4x4 average of the pixel intensity values is used which means that those smaller tiles end up with intensity values outside the original range.

I was wondering if there was any chance you might consider allowing e.g. a "nearest neighbour" or similar option to DZI such that we could maintain the phases even at very low resolution. I realise there is already loss when shrinking but we of all the options we can think of, that would be the least worst :)

Thanks as always,

Simon

**Comment by jcupitt** [comment]
There was a branch on this issue that added high-quality downsampling to dzsave:

https://github.com/jcupitt/libvips/issues/659

though it was never merged. Other people have asked for a NN downsize too, though of course I can't find the issue now.

Let's tag this as an enhancement for 8.7.

**Comment by jcupitt** [comment]
Oh, that was for tiff pyramids rather than dzsave. Anyway, the downsize algorithm implementation would be the same.

**Comment by jcupitt** [comment]
It should be an easy change. In this macro:

https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/region.c#L1176

just swap:

```C
			int tot = tp[z] + tp[z + nb] +  \
				tp1[z] + tp1[z + nb]; \
			tq[z] = (tot + 2) >> 2; \
```

for:

```C
                         tq[z] = tp[z];
```

There are two other macros you could change in the same way, but that's probably the one you want.

**Comment by harukizaemon** [comment]
@jcupitt Perfect. Thanks.

**Comment by harukizaemon** [comment]
@jcupitt Hi, I had left this alone for a bit but am now getting back to it. Is it still something you feel you might add or am I better off making a fork/implementing something myself?

**Comment by jcupitt** [comment]
Hello again, I'm planning to do this for 8.7, but of course a PR with the code all done would be great!

**Comment by jcupitt** [comment]
`vips_region_shrink()` needs to take an enum saying what kind of shrink to do (box or nearest, I guess?):

https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/region.c#L1347

It probably needs to be a new enum. There's already `VipsKernel`:

https://github.com/jcupitt/libvips/blob/master/libvips/include/vips/resample.h#L41

But that includes kernels which will not work for the strict x2 shrink we need, and your nearest could be improved and would no longer be nearest then. Maybe call it `VIpsKernel2`, since it picks an exact x2 algorithm? 

Then the code needs to have a second path for your nearest-neighbour shrink. That should be simple, since you're not doing any arithmetic, just picking the pixel at (0, 0).

Next, `dzsave` needs a new optional parameter of type `VipsKernel2` defaulting to linear, and it needs to pass that down to `vips_region_shrink()` when it calls it. `tiffsave` uses `vips_region_shrink()` for pyramids too -- that should have a similar change made.

**Comment by jcupitt** [comment]
I was thinking about your case. Suppose your image has pixels with four values `a`, `b`, `c`, and `d`. If the x2 shrink sees a block like this:

```
a b
c d
```

Then picking `a` as the result is fine. But what if it's:

```
a b
b b
```

Now the result should probably be `b`. In other words, it ought to pick the mode (most common) value, rather than always picking the top-left. 

I've not come across this type of interpolator before, I'm not sure what the best implementation would be. Just a few `if()`s I guess.

**Comment by harukizaemon** [comment]
I agree it's probably the best approach to select the mode.

Another option I just imagined would be to take the average as it stands but then normalise it to one of the input values.

e.g.

```
 5  7
10 22
= 44 / 4
= 11
=> 10
```

or in the other case
```
 5 22
22 22
= 71 / 4
= 17.75
=> 22
```

**Comment by harukizaemon** [comment]
What about something as simple as:

```
typedef enum {
	VIPS_REGION_SHRINK_KERNEL_MEAN, // Default
	VIPS_REGION_SHRINK_KERNEL_MEDIAN,
	VIPS_REGION_SHRINK_KERNEL_MIN,
	VIPS_REGION_SHRINK_KERNEL_MAX,
	VIPS_REGION_SHRINK_KERNEL_MODE
} VipsRegionShrinkKernel;
```

**Comment by jcupitt** [comment]
Sure, that sounds good. If you're prepared to implement all those cases! 

They are not really kernels, so perhaps simply `VipsRegionShrink` / `VIPS_REGION_SHRINK_MODE` would be better.

**Comment by harukizaemon** [comment]
>They are not really kernels
Agreed.

>If you're prepared to implement all those cases!
Totally happy to implement. My question would be though given the 3 types (`alpha`, `uncoded`, and `labpack`) and the first two are implemented using macros, what would you like to see as the approach here?

* P.S. I appreciate that this may be getting to the point where you throw your arms in the air and take the controls away from my hands and fly the damn aeroplane yourself, but 30 years of s/w dev says I'd rather do it consistently and in keeping with your desired approach to things.

**Comment by jcupitt** [comment]
I think my feeling would be to get something working quickly, test it, and don't over-engineer. So just do MODE for now, only handle uncoded, leave the existing code mostly undisturbed, and check that you get the result you need at a reasonable speed.

The other shrink types need to do pixel arithmetic (eg. (a+b)/2) and they will need special paths for alpha. 

LABPACK is an ancient thing which (I think?) no one uses any more, so it's probably not worth implementing. 

I've been doing sw dev for decades as well. It's nice to meet another old-timer.

**Comment by harukizaemon** [comment]
>I think my feeling would be to get something working quickly, test it, and don't over-engineer. So just do MODE for now, only handle uncoded, leave the existing code mostly undisturbed, and check that you get the result you need at a reasonable speed.

Sounds like my kind of plan 👍

**Comment by harukizaemon** [comment]
So after much thought, I think `MEDIAN` is all I need right now and I believe this is good enough:

`tq[z] = MIN(MAX(tp[z], tp[z + nb]), MAX(tp1[z] + tp1[z + nb]));`

E.g.

```
#define SHRINK_MEDIAN( TYPE ) \
	for( x = 0; x < target->width; x++ ) { \
		TYPE *tp = (TYPE *) p; \
		TYPE *tp1 = (TYPE *) (p + ls); \
		TYPE *tq = (TYPE *) q; \
 		\
		for( z = 0; z < nb; z++ ) { \
            tq[z] = MIN(MAX(tp[z], tp[z + nb]), MAX(tp1[z] + tp1[z + nb]));
		} \
		\
		/* Move on two pels in input. \
		 */ \
		p += ps << 1; \
		q += ps; \
	}
```

The approach _seems_ intuitively wrong but that depends on how you define correct :). For my purposes, I'm OK with the result being deterministic based on the position of the values rather than a strict definition. Indeed, for my purposes that might actually be a nice way to give the result a sampling of the underlying values rather than tend towards a single value. However, YMMV :)

```
Values: [1, 3, 7, 11]
Median (high): 7
Median (low): 3

[1, 3, 7, 11] => 3
[1, 3, 11, 7] => 3
[1, 7, 3, 11] => 7
[1, 7, 11, 3] => 7
[1, 11, 3, 7] => 7
[1, 11, 7, 3] => 7
[3, 1, 7, 11] => 3
[3, 1, 11, 7] => 3
[3, 7, 1, 11] => 7
[3, 7, 11, 1] => 7
[3, 11, 1, 7] => 7
[3, 11, 7, 1] => 7
[7, 1, 3, 11] => 7
[7, 1, 11, 3] => 7
[7, 3, 1, 11] => 7
[7, 3, 11, 1] => 7
[7, 11, 1, 3] => 3
[7, 11, 3, 1] => 3
[11, 1, 3, 7] => 7
[11, 1, 7, 3] => 7
[11, 3, 1, 7] => 7
[11, 3, 7, 1] => 7
[11, 7, 1, 3] => 3
[11, 7, 3, 1] => 3
```

**Comment by jcupitt** [comment]
OK, this is merged to master and I've added some (very basic) tests to the test suite. Hopefully 8.7 won't be too much longer :(

Thank you again for your hard work on this, @harukizaemon !
