### ISSUE TITLE
vips_colourspace: no known route between 'cmyk' and 'srgb'

### ISSUE THREAD

**Issue by kgdev** [jcupitt/libvips#861]
```
wget  https://dzamqefpotdvf.cloudfront.net/p/images/22276162-b01f-4a97-8227-3527627db509_1.jpg
vipsthumbnail 22276162-b01f-4a97-8227-3527627db509_1.jpg

vipsthumbnail: unable to thumbnail 22276162-b01f-4a97-8227-3527627db509_1.jpg
vips_colourspace: no known route from 'cmyk' to 'srgb'
```

Could you please take a look? Thank you.

**Comment by jcupitt** [comment]
Hello @kgdev,

You have a CMYK image with no ICC profile:

```
$ vipsheader -a kgdev.jpg 
kgdev.jpg: 1651x991 uchar, 4 bands, cmyk, jpegload
width: 1651
height: 991
bands: 4
format: uchar
coding: none
interpretation: cmyk
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: kgdev.jpg
vips-loader: jpegload
jpeg-multiscan: 0
iptc-data: 42 bytes of binary data
ipct-data: 42 bytes of binary data
xmp-data: 27548 bytes of binary data
```

So libvips cannot convert to srgb.

You need to give vipsthumbnail a fallback profile to use in case the image profile is missing. Something like:

```
$ vipsthumbnail kgdev.jpg --iprofile /usr/share/color/icc/colord/FOGRA28L_webcoated.icc 
```

I like this profile best for unknown CMYK myself:

https://github.com/jcupitt/nip2/blob/master/share/nip2/data/cmyk.icm

It's a high-quality profile, produces good results for screen output, and is completely free.

**Comment by kgdev** [comment]
Thank you! @jcupitt I will have a try. Maybe we can add this instruction into README somehow?

**Comment by jcupitt** [comment]
The docs talk about this:

http://jcupitt.github.io/libvips/API/current/Using-vipsthumbnail.md.html

Though they don't mention that profile in particular. I'll add a note.

**Comment by jcupitt** [comment]
OK, note in docs. Thanks!
