### ISSUE TITLE
Raster to Vector Conversion

### ISSUE THREAD

**Issue by bubba-h57** [jcupitt/libvips#863]
I can not make out if or how libvips would do this, but it would be utterly awesome to start converting our raster images to vector images. Any pointers would be very much appreciated.

**Comment by jcupitt** [comment]
There are loads of ways to do this, it depends on the type of image.

This is a very neat thing for SVGing photographs:

https://github.com/fogleman/primitive

It's quite fast too: just a few secs for a low-res photo. There are some good examples here:

https://primitive.lol/

Something like a blueprint, where you want to generate high-quality line art from a scan, is harder. There are lots of tools for this too, but they tend to need some manual help. Inkscape has one built in, you could check which one they are using.
