### ISSUE TITLE
Question: Flip bands

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/libvips#866]
I have some images that are BGR but I need them in RGB. I'm using the C++ API. Can you recommend a way to flip/swap/reverse the bands?

Thanks,

Simon

**Comment by jcupitt** [comment]
Hello, did you see: https://github.com/jcupitt/libvips/issues/838 ?

You can do the same in C++, something like `im[2].bandjoin2(im[1], im[0])` (untested and from memory).

**Comment by harukizaemon** [comment]
Worked a treat, thanks!
