### ISSUE TITLE
Negative number in argument

### ISSUE THREAD

**Issue by petrst** [jcupitt/libvips#869]
Hi,

is there a way how to pass a negative number as command-line argument? For example:

> vips insert test.jpg  x.jpg test_x.jpg -10 0

gives error "Unknown option -10" on Windows platform.

Quotes seems not to help:>vips insert test.jpg  x.jpg test_x.jpg "-10.0" "0"
Unknown option -10.0

Neither this one:
>vips insert test.jpg  x.jpg test_x.jpg '-10.0' '0'
insert: ''-10.0'' is not an integer

Any idea?

Platform: windows 7
version: 8.7

Regards,
Petr

**Comment by jcupitt** [comment]
Hello, you can use `--` (double dash) to indicate the end of command-line options. So:

```
$ vips insert -- test.jpg x.jpg test_x.jpg -10 0
```

Should work.

**Comment by petrst** [comment]
Working. Thanks for help.
Petr
