### ISSUE TITLE
Random error in VipsJpeg

### ISSUE THREAD

**Issue by petrst** [jcupitt/libvips#870]
Hi,

playing with the 8.7.0 build (vips-dev-w64-all-8.7.0.zip) I am getting some random errors when reading a JPEG file. Here demonstrated on "stats" function:

```
C:\Temp\vips-dev-8.7\bin>vips stats test_inv.jpg test_inv.csv

(vips:6524): VIPS-WARNING **: error in tile 0 x 528

(vips:6524): VIPS-WARNING **: error in tile 0 x 536
VipsJpeg: out of order read at line 1101
VipsJpeg: out of order read at line 1101

C:\Temp\vips-dev-8.7\bin>vips stats test_inv.jpg test_inv.csv

C:\Temp\vips-dev-8.7\bin>vips stats test_inv.jpg test_inv.csv

(vips:10052): VIPS-WARNING **: error in tile 0 x 208

(vips:10052): VIPS-WARNING **: error in tile 0 x 216

VipsJpeg: out of order read at line 1101
VipsJpeg: out of order read at line 1101
```
Without any change of the image the very same command sometimes fails and sometimes passes.
Simply by repeating over and over I am getting error at different line, without any apparent logic.

Platform: Windows 7  64-bit
vips version: 8.7.0

Any idea?
Thanks,
Petr

**Comment by jcupitt** [comment]
Hello Petr, I just fixed this today in fact. There was a race with threaded read of sequential images to a non-image output. 

8.6.2 will have the fix, due in a few days. In the meantime, you can turn off threading and it should work. Try:

```
$ vips stats x.jpg x.csv --vips-concurrency=1
````

ie. run with threadpool size 1.

**Comment by jcupitt** [comment]
OK, 8.6.2 with this fix is out now and there's a win binary. Hopefully it's resolved!

https://github.com/jcupitt/libvips/releases/tag/v8.6.2
