### ISSUE TITLE
How to replace color from the image ?

### ISSUE THREAD

**Issue by arinkverma** [jcupitt/libvips#872]
Hi experts
I am developing an image's border customization app on vips. Earlier its on image-magic. All the operations are being mapped from Image-magic to vips. 

But I am stuck at image replace operation. In Image-magic, I used to copy alpha channel to achieve desireable color. Is similar possible in vips?

![1](https://user-images.githubusercontent.com/1556486/35800298-8a85dd94-0a8e-11e8-9284-bc83835c6d44.png)
![2](https://user-images.githubusercontent.com/1556486/35800300-8ab84464-0a8e-11e8-9683-906b3ca5ab70.png)
![3](https://user-images.githubusercontent.com/1556486/35800301-8ae47408-0a8e-11e8-92b8-15cd78d48185.png)
![4](https://user-images.githubusercontent.com/1556486/35800302-8b1398f0-0a8e-11e8-8435-99365e52efb2.png)

**Comment by jcupitt** [comment]
Hello, what language are you using? In Ruby you could write:

```ruby
require 'vips'

image = Vips::Image.new_from_file ARGV[0]

# the blue colour in the icon
border = [50, 126, 175, 255]

# a new colour ... dark yellowish
new_colour = [170, 170, 90, 255]

image = (image == border).bandand.ifthenelse(new_colour, image)

image.write_to_file ARGV[1]
```

`(image == border).bandand` finds all pixels equal to the blue in your first icon, `ifthenelse` swaps matching pixels for `new_colour` and leaves non-matches alone.

Running that on your first image makes this:

![x](https://user-images.githubusercontent.com/580843/35801130-02c3e1b0-0a63-11e8-8e70-f63cdc5e87b8.png)

**Comment by jcupitt** [comment]
Actually that looks poor on the edges. 

I would make your icon from two or three layers composited together. You need a mask for the frame, a mask for the content, a solid colour for the frame edges and an image for the frame content. Make them into a stack and render with the `composite` operator.

**Comment by arinkverma** [comment]
@jcupitt 
Thanks for quick reply.  Actually, its layer image only, where the frame is a layer above the icon. 
I am using bimg, in which `addband` api is not being exposed but black is exposed. Is similar is possible with layer images and black api?

**Comment by jcupitt** [comment]
Sorry, I don't know, you'd need to ask bimg.

Here's a better way to do it with `composite`:

```ruby
require 'vips'

# the frame alpha ... a one-band PNG with 255 for the solid parts of the frame
frame_alpha = Vips::Image.new_from_file "/home/john/pics/frame.png"

# content alpha ... a one-band PNG with 255 for the solid parts of the content
content_alpha = Vips::Image.new_from_file "/home/john/pics/content.png"

# a colour for the frame as RGB
frame_colour = [128, 70, 70]

# the thing we display in the frame ... size down to match the mask
content = Vips::Image.thumbnail "/home/john/pics/nina2.jpg", content_alpha.width

# make a constant RGB image from the frame colour
bg = frame_alpha.new_from_image(frame_colour).copy(interpretation: :srgb)

# and attach the frame alpha
frame = bg.bandjoin frame_alpha

# attach the content alpha
content = content.bandjoin content_alpha

# composite the two together
result = frame.composite content, 'over' 

result.write_to_file "x.png"
```

With this frame alpha:

![frame](https://user-images.githubusercontent.com/580843/35803394-973126e8-0a6b-11e8-840c-db73ab2c2a45.png)

This content alpha:

![content](https://user-images.githubusercontent.com/580843/35803402-9f3b6a2e-0a6b-11e8-828c-286abb9a1910.png)

And this test image:

![nina2](https://user-images.githubusercontent.com/580843/35803419-acc36566-0a6b-11e8-9d57-c768a32e767d.jpg)

I get this result:

![x](https://user-images.githubusercontent.com/580843/35803493-e5b83a0e-0a6b-11e8-921d-ec0836af1fb3.png)

So all the edges get antialiased and coloured nicely, and performance is good.

**Comment by gvincke** [comment]
> ```ruby
> require 'vips'
> 
> image = Vips::Image.new_from_file ARGV[0]
> 
> # the blue colour in the icon
> border = [50, 126, 175, 255]
> 
> # a new colour ... dark yellowish
> new_colour = [170, 170, 90, 255]
> 
> image = (image == border).bandand.ifthenelse(new_colour, image)
> 
> image.write_to_file ARGV[1]
> ```

Hi @jcupitt ,
Sorry for this python newbie level question, but how would you do the same with pyvips ?
Thank you so much.
Grégoire

**Comment by jcupitt** [comment]
Hi @gvincke,

In py it would be something like (untested):

```python
import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1])
border = [50, 126, 175, 255]
new_colour = [170, 170, 90, 255]
image = (image == border).bandand().ifthenelse(new_colour, image)
image.write_to_file(sys.argv[1])
```

**Comment by gvincke** [comment]
Thanks !
I do some testing, and i have an error like `relational_const: vector must have 1 or 3 elements` due to line `image = (image == border).bandand().ifthenelse(new_colour, image)`
Any idea ?

**Comment by jcupitt** [comment]
I used `[50, 126, 175, 255]`, so RGBA, like in a PNG image. Try eg. `[1, 2, 3]` for RGB.

**Comment by gvincke** [comment]
Thanks !
I realize that my main question is maybe out of this thread topic, so i opend a new question here : #1936

**Comment by LevitatingBusinessMan** [comment]
How would one do this in C or rust?

**Comment by jcupitt** [comment]
In C++ it's the same as Python, more or less. I've not been involved in the Rust bindings, I don't know how they've done it.

C is a little awkward, something like (untested):

```C
VipsObject *context = some scope object;
VipsImage *image = some input image;
const double old_colour[] = {50, 126, 175, 255};
const double new_colour[] = {170, 170, 90, 255};
VipsImage **t = (VipsImage **) vips_object_local_array( context, 4 );
VipsImage *out;

if( vips_equal_const( image, &t[0]. old_colour, VIPS_NUMBER( old_colour ), NULL ) ||
    vips_bandand( t[0], &t[1], NULL ) ||
    !(t[2] = vips_image_new_from_value( image, new_colour, VIPS_NUMBER( new_colour ) )) ||
    vips_ifthenelse( t[1], t[2], image, &out, NULL ) )
    return( -1 );
```

**Comment by futureweb** [comment]
May I ask if someone here maybe could give me a helping hand on how to implement this in PHP? (https://github.com/libvips/php-vips-ext)
Already trying some hours to implement this Function into my Workflow but struggling hard :-/
Thank you! :-)

**Comment by jcupitt** [comment]
In PHP it'd be perhaps (untested):

```php
$image = Vips\Image::newFromFile($argv[1], ['access' => 'sequential']);
$border = [50, 126, 175, 255];
$new_colour = [170, 170, 90, 255];
$image = $image->equal($border)->bandand()->ifthenelse($new_colour, $image);
image.writeToFile($argv[2]);
```

Please don't use php-vips-ext directly, that's just the binary module. The user API is defined by php-vips.

**Comment by larsmaxfield** [comment]
> Hi @gvincke,
> 
> In py it would be something like (untested):
> 
> ```python
> import sys
> import pyvips
> 
> image = pyvips.Image.new_from_file(sys.argv[1])
> border = [50, 126, 175, 255]
> new_colour = [170, 170, 90, 255]
> image = (image == border).bandand().ifthenelse(new_colour, image)
> image.write_to_file(sys.argv[1])
> ```

This indeed works. Very straightforward. Thanks.
