### ISSUE TITLE
ndpi tiling

### ISSUE THREAD

**Issue by bender22** [jcupitt/libvips#873]
Hi John
I'm trying to tile [this ndpi file](https://1drv.ms/u/s!AhuHvLqvJ4rHigGsY3kLLSW8D42G) and somehow it is different from what openslide2vips expects to see.

"vips-dev-8.5.2/bin/vips.exe" dzsave "eca7feee-53bb-4285-84b2-0c49e0cc8b19.ndpi"[autocrop] "picOutput/eca7feee-53bb-4285-84b2-0c49e0cc8b19.zip" --overlap=0 --suffix=.jpg[Q=85] --tile-width=256 --tile-height=256 --depth=onepixel --properties --vips-progress
openslide2vips: opening slide: No such value: directory 0, tag 278

So, it's a bug in openslide, right?

**Comment by jcupitt** [comment]
Hello!

I agree, looks like this is one for Benjamin. 

```
$ openslide-show-properties eca7feee-53bb-4285-84b2-0c49e0cc8b19.ndpi 
openslide-show-properties: eca7feee-53bb-4285-84b2-0c49e0cc8b19.ndpi: No such value: directory 0, tag 278
```

I'd open an issue on the operslide tracker.

https://github.com/openslide/openslide/issues
