### ISSUE TITLE
Documentation is not clear about how to compile with OpenSlide

### ISSUE THREAD

**Issue by thedrow** [jcupitt/libvips#874]
I have compiled OpenSlide but I'm not sure how to point configure at the outputted lib path.
Any help is appreciated...

**Comment by jcupitt** [comment]
Hello, assuming you are on linux and you have compiled openslide with the default arguments to configure, it will have installed to `/usr/local`. You need to add `/usr/local` to the list of areas searched by your shell, linker and compiler. It varies a bit between linuxes (of course), but you probably need to set `PATH`, `LD_LIBRARY_PATH` and `PKG_CONFIG_PATH`.

Are you sure you need to build your own version? Most linuxes come with libvips and openslide, so you might have a prebuilt version in the package repository.

**Comment by thedrow** [comment]
Alpine, unfortunately doesn't ship vips unfortunately.

**Comment by lovell** [comment]
@thedrow https://pkgs.alpinelinux.org/packages?name=vips&branch=edge&repo=testing

**Comment by thedrow** [comment]
It's in testing which is why I haven't found it.
That package is not compiled with openslide though:
```
vips openslideload --help
vips: unknown action "openslideload"
```

**Comment by jcupitt** [comment]
You need to point `PKG_CONFIG_PATH` at the directory containing the .pc file for openslide. Try setting it to `/tmp/openslide/lib/pkgconfig`.

You can test whether it's working with:

```
$ pkg-config openslide --modversion
3.4.1
```

**Comment by thedrow** [comment]
Yes that works. Thank you :)
We should document this somewhere.

**Comment by thedrow** [comment]
Now I'm getting the following error during link time:
```
**
GLib-GObject:ERROR:gtype.c:4356:g_type_init: assertion failed: (static_quark_type_flags)
Command '['./introspect', u'--introspect-dump=/tmp/tmp-introspectxpRE2T/functions.txt,/tmp/tmp-introspectxpRE2T/dump.xml']' returned non-zero exit status -6
make[3]: *** [/usr/share/gobject-introspection-1.0/Makefile.introspection:160: Vips-8.0.gir] Error 1
make[2]: *** [Makefile:856: install-recursive] Error 1
make[1]: *** [Makefile:637: install-recursive] Error 1
make: *** [Makefile:945: install-strip] Error 2

```

**Comment by jcupitt** [comment]
Sorry, I don't know, something funny about the alpine gobject-introspection package I guess.

**Comment by jcupitt** [comment]
Try giving the `--disable-introspection` switch to libvips configure. You probably don't need the .gir file.

**Comment by thedrow** [comment]
That helps to link it but I get a segfault now :(
```
GLib-GObject:ERROR:gtype.c:4356:g_type_init: assertion failed: (static_quark_type_flags)
```

**Comment by jcupitt** [comment]
I'm using goi 1.54.1 and glib 2.54.1 (the standard ubuntu 17.10 ones), if that's any help. 

Perhaps you could adapt the alpine package file from testing that Lovell linked?

**Comment by thedrow** [comment]
They are using the same parameters I'm using: https://git.alpinelinux.org/cgit/aports/tree/testing/vips/APKBUILD

I adjusted mine to match since the specified parameters are required for linking to succeed.

**Comment by jcupitt** [comment]
Is this resolved? Please reopen if not.

**Comment by thedrow** [comment]
No, the same error happens even if I apply the patch.

**Comment by jcupitt** [comment]
I'll try making you a dockerfile.

**Comment by jcupitt** [comment]
I think I have it working. 

There was a problem in openslide: it was calling `g_type_init()` explicitly (deprecated since glib 2.36). This is normally harmless, but it breaks with musl, the alpine libc. I'll make a PR.

With this Dockerfile:

```
# build with
#    docker build -t alpine-openslide-libvips:latest alpine-openslide-libvips

# run with
#    docker run -it alpine-openslide-libvips vips

# debug with
#    docker run \
#       --cap-add=SYS_PTRACE \
#       --security-opt seccomp=unconfined \
#       -it alpine-openslide-libvips bash
#    apk add gdb glib-dbg
#    gdb vips

FROM alpine:latest

ARG OPENSLIDE_VERSION=3.4.1
ARG OPENSLIDE_URL=https://github.com/openslide/openslide/releases/download

ARG VIPS_VERSION=8.6.3
ARG VIPS_URL=https://github.com/jcupitt/libvips/releases/download

RUN apk update && apk upgrade

RUN apk add build-base \
        autoconf \
        automake \
        libtool \
        zlib-dev \
        libxml2-dev \
        jpeg-dev \
        openjpeg-dev \
        tiff-dev \
        glib-dev \
        gdk-pixbuf-dev \
        sqlite-dev \
        libjpeg-turbo-dev \
        libexif-dev \
        lcms2-dev \
        fftw-dev \
        giflib-dev \
        libpng-dev \
        libwebp-dev \
        orc-dev \
        poppler-dev \
        librsvg-dev \
        libgsf-dev \
        openexr-dev \
        gtk-doc

COPY openslide-init.patch /tmp

RUN wget -O- ${OPENSLIDE_URL}/v${OPENSLIDE_VERSION}/openslide-${OPENSLIDE_VERSION}.tar.gz | tar xzC /tmp
RUN cd /tmp \
        && patch -p0 </tmp/openslide-init.patch \
        && cd openslide-${OPENSLIDE_VERSION} \
        && ./configure --prefix=/usr --disable-static \
        && make \ 
        && make install

RUN wget -O- ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz | tar xzC /tmp
RUN cd /tmp/vips-${VIPS_VERSION} \
        && ./configure --prefix=/usr --disable-static --disable-debug \
        && make V=0 \
        && make install
```

And this openslide patch:

```
$ more alpine-openslide-libvips/openslide-init.patch 
diff -Naur openslide-3.4.1-orig/src/openslide.c openslide-3.4.1/src/openslide.c
--- openslide-3.4.1-orig/src/openslide.c	2015-04-20 20:32:12.000000000 +0
100
+++ openslide-3.4.1/src/openslide.c	2018-03-23 16:47:13.788824940 +0000
@@ -61,7 +61,9 @@
     g_thread_init(NULL);
   }
   // initialize GObject
+#if !GLIB_CHECK_VERSION(2, 36, 0)
   g_type_init();
+#endif
   // init libxml2
   xmlInitParser();
   // parse debug options
```

I see:

```
john@yingna ~/Docker $ docker run -it alpine-openslide-libvips vips
Usage:
  vips [OPTION…] [ACTION] [OPTIONS] [PARAMETERS] - VIPS driver program
...
```
