### ISSUE TITLE
mac os Install with brew, problem

### ISSUE THREAD

**Issue by mymtw** [jcupitt/libvips#876]
Hey, maybe you know why libvips shows warning:
`ld: warning: /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation, ignoring unexpected dylib file`
I installed libvips exactly like in this issue: https://github.com/h2non/bimg/issues/219 
And  when running resize via `bimg` lib, `libvips` shows warning.
libvips version: `vips-8.6`
go: `1.8`
thx

**Comment by jcupitt** [comment]
Hello @mymtw, I'll test brew tonight. It was working a few days ago, but perhaps something has broken.

**Comment by jcupitt** [comment]
Sorry, it took a while to get on the Mac.

I updated homebrew and it all seems OK, as far as I can see. I tried:

```
$ vips --version
vips-8.6.2-Wed Jan 31 20:39:14 UTC 2018
$ gem install ruby-vips
Fetching: ruby-vips-2.0.9.gem (100%)
Successfully installed ruby-vips-2.0.9
Parsing documentation for ruby-vips-2.0.9
Installing ri documentation for ruby-vips-2.0.9
Done installing documentation for ruby-vips after 1 seconds
1 gem installed
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.new_from_file "/Users/john/pics/k2.jpg"
=> #<Image 1450x2048 uchar, 3 bands, srgb>
irb(main):003:0> x = x.invert
=> #<Image 1450x2048 uchar, 3 bands, srgb>
irb(main):004:0> x.write_to_file "y.png"
=> nil
irb(main):005:0> 
```

So I could install libvips and use it from another language ecosystem.

**Comment by mymtw** [comment]
Hi, thanks, seems trouble in bimg
