### ISSUE TITLE
Apply operation to part of the image

### ISSUE THREAD

**Issue by petrst** [jcupitt/libvips#881]
Guys,

is there any easy way how to apply libvips operation to part of the image? I mean something easier/faster than cropping, applying operation and embedding back to original image. Something like ROI in OpenCV.

Regards,
Petr

**Comment by jcupitt** [comment]
Hello @petrst, no, libvips is non-destructive (images can only be created, they cannot be modified), so you can't just change part of one.

You can write a simple method in Ruby or whatever to do the extract / operate / insert sequence for you. Something like (untested):

```ruby
class Image
    def region x, y, w, h, &block
        tile = self.crop x, y, w, h
        tile = block(tile)
        tile = tile.cast(self.format)
        return self.insert tile, x, y
    end
end
```

Then:

```ruby
image = image.region(10, 10, 100, 100) {|x| x + 100}
```

Would efficiently add 100 to every pixel in the box.
