### ISSUE TITLE
[nip2] Paint text with group in text argument

### ISSUE THREAD

**Issue by petrst** [jcupitt/libvips#885]
Hi,

in nip2, is there a way how to paint text from a group/list to an image?

What I am trying to do is to "label" my images with, for instance, applied "strength" of the algorithm and organize them into a mosaic. I start with one image (A1) and group of arguments [1,2,3,4] in A2.  I apply an algo to it. Let's say A3 = A1 *A2, which creates a group if images. So far so good. But if I do the same with Filter/Paint Text trying to pass group as "text" argument I am getting error "bad argument".

Is there a way how to achieve it?

Regards,
Petr

**Comment by jcupitt** [comment]
You can do it, but the menus don't really support it, so it's ugly :( 

I made you a sample ws:

https://gist.github.com/jcupitt/22c626b0bc56aaefbd30afd5d06158e5

* It makes 11 checkerboard patterns, each with brightness scaled by a percentage.
* It makes a group of strings "0" .. "10".
* Column B makes a group of label images from the group of strings. It calls the vips7 function `im_text` to do this -- it would be better to use the vips8 `text` operator really.
* It expands each label image up to the size of the checkerboards, then blends them.

**Comment by jcupitt** [comment]
You can change B6 to be:

```
Group (map (\t Image ((vips_call "text" [t] [$font => B1.value, $dpi => B4.expr]))?0) B5.expr)
```

to use the vips8 `text` operator, though it's no less ugly hehe
