### ISSUE TITLE
Mono/.NET bindings

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/libvips#887]
I had a quick go with making a full C# binding for libvips. It relies on [CppSharp](https://github.com/mono/CppSharp), which takes C/C++ header and library files and generates the necessary P/Invoke bindings.

Things that already work:
- Load an image from a file.
- Read properties of an image.
- Write an image to a file.

<sup>(see the [example program](https://github.com/kleisauke/net-vips/blob/master/NetVips.Samples/Program.cs))</sup>

There are still things that need to be fixed:
- Find a way to pass variadic arguments (maybe we need to include `VOption`?). I have added a string array parameter to all variadic functions just for example (see [here](https://github.com/kleisauke/net-vips/blob/8f908a9a8fd8af14f34e2acfefc0dccb5f61a73c/NetVips/Passes/AddOptionsParamForVariadicFuncs.cs#L12)).
- This should work:
   ```csharp
   VipsThumbnail("lichtenstein.jpg", out var thumbImage, 200);
   VipsImageWriteToFile(thumbImage, "lichtenstein_thumb.jpg");
   ````
   but doesn't. Investigate how we should use the out parameter modifier correctly.
- `image.Width` / `image.Height` needs to return the height and width of the image. Currently we need to use `VipsImageGetWidth(image)` / `VipsImageGetHeight(image)`.

And many more things need to be tested and worked out (such as .NET Core, Linux support, etc.). If someone wants to help me with this, that would be great.

I'd be very happy to hand the whole thing over to @jcupitt, if he wants to cooperate with this. 

Repository: https://github.com/kleisauke/net-vips

**Comment by jcupitt** [comment]
That is extremely cool! I'll help if I can, but I've just started a new full-time job, so my resources are a bit limited at the moment. 

@yurykovshov, I know you were interested in a .net binding, what do you think?

**Comment by jcupitt** [comment]
My feeling is that you should build this in four layers:

1. Use CppSharp to bind the core libvips API. You don't need any varadic stuff (phew). You'll need to wrap chunks of glib as well, especially GValue and GType.
2. Layer a thing on top of that that can call any libvips operation. It will need some kind of optional argument support and optional return value support. I've no idea how C# handles this -- hopefully you can do something better than the ugly `VOption` the C++ binding uses.
3. Write something in Ruby/Python/etc. that can statically generate C# methods for the operators. The C++ binding has a thing you can adapt, the PHP binding has one too.
4. And on top of that, you'll need some hand-written things, like NewFromFile() and operator overloads. Again, the C++ binding has some ideas.

**Comment by yurykovshov** [comment]
Nice developments. I would love to do it, but I am too overloaded at the moment. Definitely, there is an additional layer of abstraction needed on top of P/Invoke bindings.

**Comment by kleisauke** [comment]
I've worked on this for the last 4 days and it's now possible to call every libvips operation. :tada:

It's build in four layers (just what John has recommended):

1.  Use CppSharp to bind the core libvips API (see the output [here](https://github.com/kleisauke/net-vips/tree/master/NetVips/AutoGen)).
2. Call any libvips operation through `Operation.cs` (see [here](https://github.com/kleisauke/net-vips/blob/5cc65e3859912e92ad4d67d4ea899252aa5d3813/NetVips/Operation.cs#L189)).
3. Statically generate C# methods for libvips operators (see the [C# generator](https://github.com/kleisauke/net-vips/blob/5cc65e3859912e92ad4d67d4ea899252aa5d3813/NetVips/Operation.cs#L348) and the [output](https://github.com/kleisauke/net-vips/blob/5cc65e3859912e92ad4d67d4ea899252aa5d3813/NetVips/Image.cs#L750)).
3. Hand-written things (see for e.g. [`NewFromFile`](https://github.com/kleisauke/net-vips/blob/5cc65e3859912e92ad4d67d4ea899252aa5d3813/NetVips/Image.cs#L153), [`overloadable operators`](https://github.com/kleisauke/net-vips/blob/5cc65e3859912e92ad4d67d4ea899252aa5d3813/NetVips/Image.cs#L6921]), [`square-bracket operator`](https://github.com/kleisauke/net-vips/blob/5cc65e3859912e92ad4d67d4ea899252aa5d3813/NetVips/Image.cs#L7064)).

Most of the classes are inherited from pyvips and converted to C# in a proper way.

It's not yet ready for production, a few things have to be solved for that:
- More unit tests (there's now 1 unit test ([`GValueTests`](https://github.com/kleisauke/net-vips/blob/5cc65e3859912e92ad4d67d4ea899252aa5d3813/NetVips.Tests/GValueTests.cs)) which passes cleanly).
- Support non-ASCII characters in filenames. See [here](https://github.com/kleisauke/net-vips/blob/5cc65e3859912e92ad4d67d4ea899252aa5d3813/NetVips.Tests/Helper.cs#L16-L17).
- Investigate possible memory leaks.
- Investigate why it lingers on [`VipsCacheOperationBuild`](https://github.com/kleisauke/net-vips/blob/5cc65e3859912e92ad4d67d4ea899252aa5d3813/NetVips/Operation.cs#L279) when doing `WriteToFile` (maybe it's due to GC?). See [here](https://github.com/kleisauke/net-vips/blob/5cc65e3859912e92ad4d67d4ea899252aa5d3813/NetVips.Samples/Program.cs#L40-L42).
- Investigate why we can not do a `.Avg()` call after `memory += 10;` (memory corruption?). See [here](https://github.com/kleisauke/net-vips/blob/5cc65e3859912e92ad4d67d4ea899252aa5d3813/NetVips.Samples/Program.cs#L28-L30).
- How should we integrate `VipsInit`? It's kind of weird that we have to call it in every class.
- Cross-platform support with .NET Core.
- Documentation / auto generated docs (Doxygen?).
- Travis / AppVeyor integration.
- Benchmarks.
- Need to handle the libvips error buffer.

As always, if someone wants to help me with this, that would be great.

**Comment by jcupitt** [comment]
Kleis! You are a coding machine! That is very impressive. Come to London for the libvips meetup on the 22nd and I will buy you a series of beers!

**Comment by kleisauke** [comment]
Hi John, looking forward to drink some beers with you. Currently I'm quite busy (studying, GitHubbing, etc.) any idea when the next libvips meetup will be?

Also I've just pushed 5 days of work to NetVips: https://github.com/kleisauke/net-vips/commit/844cffa82ec2cc56d32aa40cbfb78fd6b5c38f73

Enjoy yourselves!

**Comment by kleisauke** [comment]
I've just pushed the last remaining unit tests. All 190 tests (which are inherited from pyvips) passed cleanly. 

Also created auto-generated method overloads for optional output arguments (libvips arguments tagged as `VIPS_ARGUMENT_OPTIONAL_OUTPUT`). So that users are able to do this:
```csharp
Image im = Image.NewFromFile("lichtenstein.jpg");
double max = im.Max(out int x, out int y);
Console.WriteLine($"max = {max}, x = {x}, y = {y}");
```
(to find the image maximum and the horizontal / vertical  position of maximum, see [source code](https://github.com/kleisauke/net-vips/blob/e2ec16760ba492dc66beeb8da7fdd12fbf906934/NetVips/Image.cs#L5086-L5129))

Version 1.0 is getting closer, I've made a TODO list for things that should be done before we could declare 1.0 (and publish as NuGet package). See: https://github.com/kleisauke/net-vips/issues/1.

**Comment by jcupitt** [comment]
That is so cool! 

What a shame about the `new Dictionary<string, object>`, is there no other way to do that? Could you make a typedef, perhaps, if C# has them?

As well as `Enums.Precision.Integer`, you could perhaps also allow a simple string for the enum value. Perhaps static compilation leans too much against that. 

I really don't like the naming convention :( but I guess if that's the .net standard, it's correct.

**Comment by kleisauke** [comment]
You're right, I also don't like the `new Dictionary<string, object>`. I switched to `VOption` in [this branch](https://github.com/kleisauke/net-vips/tree/drop-dictionary), let me know what you think.

The `Enums.Precision.Integer` is just a string constant to `"integer"` (see [here](https://github.com/kleisauke/net-vips/blob/e2ec16760ba492dc66beeb8da7fdd12fbf906934/NetVips/Enums.cs#L277)). You could also write this: 
```csharp
var im = Image.NewFromFile("image.jpg");

// put im at position (100, 100) in a 3000 x 3000 pixel image, 
// make the other pixels in the image by mirroring im up / down / 
// left / right, see
// https://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-embed
im = im.Embed(100, 100, 3000, 3000, new VOption
{
    {"extend", "mirror"}
});

// multiply the green (middle) band by 2, leave the other two alone
im *= new[] { 1, 2, 1 };

// make an image from an array constant, convolve with it
var mask = Image.NewFromArray(new[]
{
    new[] {-1, -1, -1},
    new[] {-1, 16, -1},
    new[] {-1, -1, -1}
}, 8);
im = im.Conv(mask, new VOption
{
    {"precision", "integer"}
});

// finally, write the result back to a file on disk
im.WriteToFile("output.jpg");
```
(or even `{"extend", 3}` and `{"precision", 0}`)

The naming convention is indeed the .NET standard (it's called `PascalCase`), I also have to get used to it.

**Comment by jcupitt** [comment]
Yes, I think that looks a bit nicer. Your choice though, of course!

**Comment by jcupitt** [comment]
Oh, how about this? Nullable types!

https://stackoverflow.com/a/29820290/894763

You could have:

```C#
im = im.Embed(100, 100, 3000, 3000, extend: "mirror");

public Image Embed(int x, int y, int width, int height, Enums.Extend? extend) 
{
    VOption options = new VOption;

    if (extend.HasValue)
        options.add({"extend", extend});

    return this.Call("embed", options, x, y, width, height) as Image;
}
```

I don't know any C# so I'm only guessing the syntax :(

**Comment by kleisauke** [comment]
Ah, I forgot that such things were possible in C#, thanks! Implemented in: https://github.com/kleisauke/net-vips/commit/8dc026c5d091bbe9540c4d37edf4b06a8bf734cf.

**Comment by kleisauke** [comment]
I've just added support for multidimensional arrays in `NewFromArray`. I agree, it's nicer syntax.

Unfortunately, this is [not preferred](https://docs.microsoft.com/nl-nl/visualstudio/code-quality/ca1814-prefer-jagged-arrays-over-multidimensional). Concerning performance, I don't think this would lead to huge differences because the array size is relatively small.

**Comment by kleisauke** [comment]
All things from the TODO list are done! :tada:

I will try to create a NuGet package in the course of next week. 

Changeset since last update:
- Continuous integration with Travis and AppVeyor (testing the vips test suite on Windows, macOS and Linux).
- Project ported to .NET Core.
- Fixed a few bugs found during stress/leak testing.
- Added [benchmarks](https://github.com/kleisauke/net-vips/tree/master/tests/NetVips.Benchmarks) (benching against Magick.NET and ImageSharp).
- Used a module initializer to init libvips.
- Added a [Dockerfile](https://github.com/kleisauke/net-vips/blob/master/Dockerfile) to quickly test under different circumstances.
- Added `VipsException` which handles the libvips error buffer.

Last but not least, I’ve added formatted/API docs here: https://kleisauke.github.io/net-vips/ (the API documentation is automatically generated with DocFX).

The benchmarks look pretty good. On my PC, NetVips is 13 times faster than Magick.NET and 5 times faster than ImageSharp.  I hope someone can verify this, because the *magick one seems somewhat slow in comparison with the other libvips bindings (it's benched under ImageMagick 7). The instructions on how to run the benchmark can be found here:
https://github.com/kleisauke/net-vips/tree/master/tests/NetVips.Benchmarks#do-it-yourself

I'm always happy to receive feedback.

**Comment by jcupitt** [comment]
IM7 is typically 2x slower than IM6, though it depends how it is configured. 13x slower does seem high, I'd expect 6x. I wonder if something is wrong? Could it be a configuration issue? Perhaps it's opening all files via disc?

**Comment by jcupitt** [comment]
Also, congratulations! Time to kick back and relax for the weekend.

**Comment by kleisauke** [comment]
There's now a NuGet package (a little later than expected):
https://www.nuget.org/packages/NetVips :tada:

I've contacted @dlemstra about the benchmark and he saw that there was something wrong with the NetVips benchmark. I used `similarity` instead of `reduce`. The new benchmark looks more reasonable now: https://github.com/kleisauke/net-vips/commit/62d5e459e505e7a1af6ac656df0ad8c374b02466
(I used the [ruby-vips benchmark](https://github.com/jcupitt/vips-benchmarks/blob/master/ruby/ruby-vips.rb#L9) that still had the `similarity` function)

The only thing that might need to be changed is the sharpen convolution mask precision. We might use floating point precision (`Enums.Precision.Float`) instead of integer precision (`Enums.Precision.Integer`) for the benchmarks because other libraries usually also work with floats. What do you think @jcupitt?

Anyways, I'll close this issue. I'll track support tickets, issues and feature requests at the [NetVips issue tracker](https://github.com/kleisauke/net-vips/issues).

**Comment by jcupitt** [comment]
I think it depends what you want the benchmark to show. 

The benchmark that Sharp uses tries to show the most common task (load large jpg, high-quality downsize to screen res, recompress) implemented in the fastest way on each of the libraries. It's a good way to show the performance a user might realistically expect.

The libvips "speed and memuse" one is a bit different because it's a general purpose library, with strengths and weaknesses, and there isn't really a single task you can test. The scenario was supposed to stress load, save, resample, convert and filter, the five (arguably?) most basic operations an image processing library needs to implement. The aim isn't to show typical performance, but to show something libvips does well. The take-away should be "if you need to do stuff like this, libvips is a good choice".

So given that, if you're using the libvips scenario, I think it's OK to implement the libvips version in way that shows it off, ie., using the int path. The results should be pretty much identical anyway for 8-bit images.

(assuming the int path is actually faster, hehe)

**Comment by jcupitt** [comment]
Agreed on swapping similarity for reduce, btw. I ought to update the ruby one too.
