### ISSUE TITLE
How to perform thresholding of images?

### ISSUE THREAD

**Issue by medakk** [jcupitt/libvips#888]
I'm like to apply a threshold to a single-band image, so that everything below the threshold is 0, and everything above is 255.
Like:
![1](https://user-images.githubusercontent.com/10536745/36630477-f4b572da-198c-11e8-8011-ad552ed77eb4.png)
![2](https://user-images.githubusercontent.com/10536745/36630478-f70915d2-198c-11e8-8836-ff18bf908ebf.jpg)

How can I achieve this in libvips?
I am using the C API.

**Comment by jcupitt** [comment]
Hello @medakk, use the relational operators:

http://jcupitt.github.io/libvips/API/current/libvips-arithmetic.html#vips-more-const1

for example:

```C
VipsImage *in = ...;
VipsImage *out;

if (vips_moreeq_const1(in, &out, 128, NULL))
   error();
```

You can combine results with the boolean operators to make complex thresholds.

**Comment by medakk** [comment]
That worked perfectly.

Thanks!
