### ISSUE TITLE
Strange artifacts with dsave

### ISSUE THREAD

**Issue by Paulico** [jcupitt/libvips#889]
Hey,
I use ligvips v8.6.2 with imagemagick to make a deep zoom image from a big PSB file.
I have changed several parameters, but still the same result. The last time I used:
vips dzsave bigphoto.psb mydz --tile-size 256 --overlap 8 --strip=false --suffix .jpg[Q=85,optimize_coding=true,no_subsample=true,interlace=true]

Result:
![schermafbeelding 2018-02-28 om 13 43 10](https://user-images.githubusercontent.com/5802704/36788595-ca496286-1c8e-11e8-9d77-adce8c039b41.png)

The original PSB:
![schermafbeelding 2018-02-28 om 13 44 40](https://user-images.githubusercontent.com/5802704/36788751-56596a46-1c8f-11e8-947c-a33d2060fe2b.png)

What causes this and how do I correct it?

**Comment by jcupitt** [comment]
Hello @Paulico,

I'd guess it's the PSB reader, perhaps? I think I would try using a TIFF image instead.

If you can share the PSB image somehow, I can try here.

**Comment by Paulico** [comment]
I have made a small example: https://www.dropbox.com/sh/nzsnusd31ctucct/AAANcxI66FRIvIgUhMTpgYXYa?dl=0

The real PSB file is 70gB. This is to large to handel with a tif file (max 4gb)

**Comment by jcupitt** [comment]
You can use bigtiff with huge images, though I'm not sure photoshop supports them very well.

I'll try your example.

**Comment by jcupitt** [comment]
I made a deepzoom from your pic:

http://www.rollthepotato.net/~john/bigphoto/

It seems to have worked for me. That's with:

```
$ vips dzsave bigphoto.psb bigphoto
```

to make the pyramid.

**Comment by jcupitt** [comment]
I meant to ask, what platform are you using? I'm using libvips 8.6.2 and imagemagick (to read the PSB file) 6.9.7-4 on Ubuntu 17.10.

**Comment by Paulico** [comment]
I'm working on a Macpro high sierra
I have just finished the export of a bigtiff file. I used an Avenza Photoshop plugin for the export. Now I have a 150gb file.  Let see what libvips makes of it. I tell you this in about a day..

Verstuurd vanaf mijn iPhone



Verstuurd vanaf mijn iPhone

**Comment by Paulico** [comment]
Libvips is much faster with tiff then with psb, and the artifact are gone. Thanks for the good advice.

**Comment by jcupitt** [comment]
Yes, PSB is loaded via libMagick. ImageMagick allocates a HUGE memory (or disc) file, then decompresses the entire PSB into it, unpacked to 16-bits per colour channel. It can be a bit wonky with very large objects, hence perhaps the artefacts you saw.

With a TIFF source, libvips will stream the image directly into dzsave, with no unpacking or conversion. You save the whole business of making the intermediate image, and TIFF is much faster (and more standard) than PSB too.

Anyway, I'm glad it's working!
