### ISSUE TITLE
write_to_memory missing from v8.7.0 (pyvips8)

### ISSUE THREAD

**Issue by Jondeen** [jcupitt/libvips#891]
Hi again!

I recently bumped my library up to 8.7.0 on one of my systems and it seems `write_to_memory` has been removed since the last version I had (8.2.2). Is this by intention?

I just need to pass some image data between libraries, so I can probably adapt to using `write_to_buffer` instead, however it seems `write_to_memory` is only missing from the python implementation (`vips_image_write_to_memory` still exists in `iofuncs/image.c`), and there are traces of it (previously) being handled automatically in `gi/overrides/Vips.py` ("`# we can use Vips.Image.write_to_memory() directly`").

Sincerely,
Jonas

**Comment by jcupitt** [comment]
Hi Jonas, the two (!!) py bindings included in libvips are both deprecated and only there for backwards compatibility.

The good one is here:

https://github.com/jcupitt/pyvips

It's on pypi, so just:

```
$ pip install pyvips
```

and it should work. It even has docs! https://jcupitt.github.io/pyvips/

**Comment by jcupitt** [comment]
It should have the same API as the previous version, see:

https://github.com/jcupitt/pyvips#converting-old-code

**Comment by Jondeen** [comment]
How did I miss this! This is great!

Thanks!
