### ISSUE TITLE
How to perform vips_composite at a given (x,y) coordinate?

### ISSUE THREAD

**Issue by medakk** [jcupitt/libvips#892]
I am using the C API.

How do I perform `vips_composite` while specifying x, y positions for the overlay images?
Like vips_insert, but I also want control over the blending options.

**Comment by jcupitt** [comment]
Hello, two easy ways:

1. Use vips_embed() to size the small image up to match the big image, placing it at a certain (x, y).

2. Extract an area from the large image, composite it, then insert back. This is a little more awkward, but perhaps slightly faster. 

For 1. in Ruby you'd do:

```ruby
im1 = Vips::Image.new_from_file "huge.png" 
im2 = Vips::Image.new_from_file "small.png"

im2 = im2.embed(x, y, im1.width, im2.height)
im3 = im1.composite(im2, "over")
```

It's an obvious missing feature, so there's a TODO to add optional x, y params to composite.

**Comment by jcupitt** [comment]
The embed thing sounds slow, I meant to say, but it should actually be fine. Extract/composite/insert would only be a bit quicker, and only for very large images.

**Comment by jcupitt** [comment]
That would be great!

`composite` takes an array of images to merge, so you'll need to pass an array of x and an array of y. 

`composite` already allows the images in the stack to differ in size: it just expands all the smaller ones up to the size of the largest using embed, aligning them at the top left. You just need to pass the x/y into the embed operation.

You could attempt to optimize this a bit. For each output region, it could calculate the set of input images which have real pixels at that point, and then only merge those. That could give a nice speedup for cases where you have many small images composited over a large background.

**Comment by sickrandir** [comment]
Came here just to ask the very same question and found it answered. Sweet! Thanks!

**Comment by medakk** [comment]
@jcupitt 

I'm having some trouble figuring out how the composite functions are being called.
I've added the x and y arrays to `struct VipsCompositeBase`:
```
typedef struct _VipsCompositeBase {
	/* Omitted */
	/* For N input images, 1 x coordinate or N - 1 x coordinates.
	 */
	VipsArrayInt *x;

	/* For N input images, 1 y coordinate or N - 1 y coordinates.
	 */
	VipsArrayInt *y;
}
```

and added the optional arguments in `vips_composite_base_class_init`:
```
	VIPS_ARG_BOXED( klass, "x", 12,
		_( "x coordinates" ),
		_( "Array of x coordinates to join at" ),
		VIPS_ARGUMENT_OPTIONAL_INPUT,
		G_STRUCT_OFFSET( VipsCompositeBase, x ),
		VIPS_TYPE_ARRAY_INT );

	VIPS_ARG_BOXED( klass, "y", 13,
		_( "y coordinates" ),
		_( "Array of y coordinates to join at" ),
		VIPS_ARGUMENT_OPTIONAL_INPUT,
		G_STRUCT_OFFSET( VipsCompositeBase, y ),
		VIPS_TYPE_ARRAY_INT );
```

Upon calling the function in my test code with:
```
    if(vips_composite(in, &out, 3, mode, "x", x, "y", y, NULL)) {
        printf("Error in composite\n");
        vips_error_exit(NULL);
    }
```
where all the arguments are correctly initialized, the function simply hangs, and I have to kill it with Ctrl+C. 


I'm not able to trace the flow of the code. `vips_compositev` calls `vips_call_split`, which eventually calls `result = vips_operation_set_valist_required( *operation, a ) ||
		vips_object_set_valist( VIPS_OBJECT( *operation ), b );`. Somewhere, it simply gets stuck.

What is the correct way to add and register new arguments?

**Comment by jcupitt** [comment]
Yes, that should work. 

For testing, it's easiest to use the CLI. I added those lines to my composite and ran it like this:

```
$ vips composite2 k2.jpg PNG_transparency_demonstration_1.png x.jpg over --x "1 2 3" --y "1 2 3"
```

If you run in gdb you can test the values:

```
$ gdb vips
Reading symbols from vips...done.
(gdb) break vips_composite_base_build
(gdb) run composite2 k2.jpg PNG_transparency_demonstration_1.png x.jpg over --x "1 2 3" --y "1 2 3"
Breakpoint 2, vips_composite_base_build (object=0x555555876010)
    at composite.cpp:1020
1020	{
(gdb)
```

Then step to get past the line where it chains up:

```
(gdb) n
1021		VipsObjectClass *klass = VIPS_OBJECT_GET_CLASS( object );
(gdb) 
1022		VipsConversion *conversion = VIPS_CONVERSION( object );
(gdb) 
1023		VipsCompositeBase *composite = (VipsCompositeBase *) object;
(gdb) 
1032		if( VIPS_OBJECT_CLASS( vips_composite_base_parent_class )->
(gdb) 
1033			build( object ) )
(gdb) 
1032		if( VIPS_OBJECT_CLASS( vips_composite_base_parent_class )->
(gdb) 
1036		composite->n = composite->in->area.n;
```

And now the args should all have been filled in:

```
(gdb) p *composite->x
$2 = {area = {data = 0x555555874bc0, length = 12, n = 3, count = 1, 
    lock = 0x555555874be0, free_fn = 0x7ffff722b660 <g_free>, type = 24, 
    sizeof_type = 4}}
(gdb) p ((int*)composite->x.area.data)[1]
$5 = 2
```


 p ((int*)composite->x.area.data)[1]

**Comment by medakk** [comment]
Enhancement merged by https://github.com/jcupitt/libvips/pull/934

I'm closing this issue.
