### ISSUE TITLE
Provide GObject introspection annotations for libvips/iofuncs/buf.c

### ISSUE THREAD

**Issue by dignati** [jcupitt/libvips#894]
They are currently missing but would be useful to generate bindings

**Comment by jcupitt** [comment]
Hello, I found I didn't need them for the GOI Python binding -- could you give an example of when they are useful to have? 

GIO Python binding here: 

https://github.com/jcupitt/libvips/blob/master/python/packages/gi/overrides/Vips.py

**Comment by dignati** [comment]
I'm trying to generate rust bindings with [gtk-rs/gir](https://github.com/gtk-rs/gir) and it fails for `vips_object_summary_class` because the parameter buf is of type VipsBuf* but VipsBuf has no corresponding type definition in the GIR file.

**Comment by jcupitt** [comment]
Do you need to call that function? I'm not sure it's not very useful for bindings.

It's true that if vips_object_summary_class() is in the GIR, VipsBuf proably should be too.

**Comment by dignati** [comment]
I don't need to call the function, at least AFAIK. Either removing all methods with VipsBuf arguments or including VipsBuf would be nice.

**Comment by jcupitt** [comment]
Ooop, dropped a !, sorry, try again.

**Comment by jcupitt** [comment]
Ooop, dropped a !, sorry, try again.

**Comment by jcupitt** [comment]
I had a closer look -- VipsBuf does things like allocate on the stack so it won't really work in anything except C. 

vips_object_summary_class() is tagged as `(skip)`, so I think gtk-rs ought not to generate a wrapper for it:

https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/object.c#L365

You can see in the GIR as well:

```
      <function name="summary_class"
                c:identifier="vips_object_summary_class"
                introspectable="0">
```

Perhaps rs-gtk is ignoring the `introspectable` property?

**Comment by dignati** [comment]
Indeed it is: https://github.com/gtk-rs/gir/pull/433#issuecomment-321387558. Thanks for looking into this. I'm now taking a different approach so feel free to close if you don't think this is an issue.

**Comment by jcupitt** [comment]
OK, thanks for checking your end. I'll close.
