### ISSUE TITLE
DeepZoom with existing tiles (libvips dzsave)

### ISSUE THREAD

**Issue by davidbirchwork** [jcupitt/libvips#896]
Hi there, 

I am looking to create a deepzoom tile pyramid. 
I have generated the lowest level of tiles (though they are each 8000px square) 

I understand i can do this using arrayjoin  to combine images to a single super large image then use dzsave to make a pyramid 

my question is whether this can be done without using arrayjoin to create a supermassivehuge tiff? 

e.g. can i just pass drsave a folder with tiles in it?

**Comment by jcupitt** [comment]
Hello David, yes, you can just use arrayjoin like this:

```
$ vips arrayjoin "a.tif b.tif c.tif d.tif" x.dz --across 2
```

And it'll join those four images up as a 2x2 mosaic, then save the result as a deepzoom image called `x`.

**Comment by jcupitt** [comment]
I meant to say, the files have to be given as a single argument, so you can't just use `"*.tif"` or whatever, since the glob won't expand inside quotes. Fortunately `$()` will, so you can do:

```
$ vips arrayjoin "$(echo somedir/*.jpg)" x.dz --across 3
```

To join all the jpg files in `somedir` as a deepzoom pyramid.

**Comment by davidbirchwork** [comment]
Hurrah! lets try that! how would I configure the .dz created? 
Thank you!

**Comment by jcupitt** [comment]
It's like any saver, you can just put options in square brackets. For example:

```
$ vips arrayjoin "$(echo somedir/*.jpg)" x.dz[overlap=0,tile-size=512] --across 3
```

**Comment by davidbirchwork** [comment]
Perfect, that's amazing :)

**Comment by jcupitt** [comment]
Related issue:

https://github.com/jcupitt/libvips/issues/904

There's a thing there to sort the filenames correctly:

```
$ vips arrayjoin "$(echo *.png | sort -t_ -k2g -k1g)" x.dz[overlap=0] --across 20
```
