### ISSUE TITLE
Extract area of tiff file Leica SCN

### ISSUE THREAD

**Issue by MarkusAnthony** [jcupitt/libvips#897]
I have a tiled tiff file (actually an scn file). I want to read, for example, 11201x19360 starting at 38765, 51978 on page 0.

Is this possible through vips?

-Markus

**Comment by MarkusAnthony** [comment]
Actually I just found this:

`vips extract_area myfile.scn partial.tif 38765 51978 11201 19360`

Is there anyway to compress it? It came from a 500mb tif (svn) and created a 13GB tif file.

-Markus

**Comment by jcupitt** [comment]
Hi Markus, yes, it should work fine. For example, at the command-line you could do:

```
$ vips crop huge.svn tiny.png 38765 51978 11201 19360
```

Where the numbers are left top width height.

**Comment by jcupitt** [comment]
Oh, or `extract_area`, they are synonyms.

You can control image write by putting options in square brackets after the filename. For example:

```
$ vips crop huge.scn tiny.tif[compression=jpeg,tile,bigtiff] 38765 51978 11201 19360
```

To make a tiled jpg output.

You can see all the options the tiff writer supports in the C docs:

http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-tiffsave

Or try `vips tiffsave` with no arguments at the command line for a summary.

**Comment by jcupitt** [comment]
I guess you mean an svs file, is that right?

**Comment by MarkusAnthony** [comment]
No, we are using the Leica SCN file which is also a tif-like file format.

Your solution worked great! Much appreciated!

**Comment by jcupitt** [comment]
Good, glad it's working. You can do the same thing in Python or whatever too, of course.

```python
import pyvips

image = pyvips.Image.new_from_file("huge.scn")
tile = image.crop(38765, 51978, 11201, 19360)
tile.write_to_file("small.tif", compression="jpeg", tile=True, bigtiff=True)
```

etc etc.
