### ISSUE TITLE
Is there a VIPS equivalent to Identify @ ImageMagick?

### ISSUE THREAD

**Issue by johnvoncolln** [jcupitt/libvips#899]
I need to retrieve pixel dimension and PPI/DPI of images - is this possible with VIPS?  I'm using Imagick with PHP currently and it's deathly slow...

**Comment by jcupitt** [comment]
Hello, sure, in PHP it's:

```
$ php -a
Interactive mode enabled

php > require 'vendor/autoload.php';
php > $image = Jcupitt\Vips\Image::newFromFile('/home/john/pics/k2.jpg');
php > echo $image;
{"width":1450,"height":2048,"bands":3,"format":"uchar","interpretation":"srgb"}
php > echo $image->width;
1450
php > echo $image->xres;
2.8346
```

`xres` and `yres` are always in pixels / mm. There are other properties you can get documented here:

https://jcupitt.github.io/php-vips/docs/classes/Jcupitt.Vips.Image.html#properties

You can read and set EXIF stuff too, for example:

```
php > echo $image->get("exif-ifd0-Orientation");
1 (Top-left, Short, 1 components, 2 bytes)
```

Try `vipsheader -a k2.jpg` on a file to see all the metadata libvips knows about.

**Comment by johnvoncolln** [comment]
Watch out, because if I ever see you in public, I'm going to give you the biggest, hardest hug ever!

I can't wait to try this out tonight!
