### ISSUE TITLE
Vips producing "violet" images [SOLVED]

### ISSUE THREAD

**Issue by lallori** [jcupitt/libvips#901]
Dear John,

I am using vips to create pyramid tiffs from different set of images uploaded by users.
90% of the images processed are fine but some of them when opened with iipimage are shown with "violet" colors (tiffs and some png formats).

Here is what i get:
![screenshotiniipimage](https://user-images.githubusercontent.com/16099406/37290413-7324e1f6-260c-11e8-9330-08e519165295.jpg)

Example:
Original tiff file:
https://drive.google.com/open?id=1uqXrXC7WlFxDgHrdx6R8YclQDmMcayCV

Command issued:
vips im_vips2tiff "${file}" pyramid/"${file}":jpeg:70,tile:128x128,pyramid

Result file:
https://drive.google.com/file/d/1Mtbuf8ifc-tXtq015z3pijKZtwn6jkLP/view?usp=sharing

Thanks a lot,

Lorenzo

**Comment by jcupitt** [comment]
Hello Lorenzo, 

Your `original.tif` is a four-band RGB image, so perhaps your libvips thinks the image is CMYK? What version are you using?

I tried with current libvips (8.6) and it seems to work OK.

There's a new interface to vips, by the way, your command can now be entered as:

```
vips tiffsave "${file}" "pyramid/${file}" --compression jpeg --Q 70 --tile --pyramid
```

You can see all the options here:

http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-tiffsave

**Comment by lallori** [comment]
Dear John, 

I am using vips 8.2.1.

Can you please send me the pyramid tiff you created to see it is an iipmoviewer issue then?

Thanks,
Lorenzo

**Comment by jcupitt** [comment]
Hi again, I tried in libvips 8.2, and it writes a 4-band sRGB image.:

```
$ tiffinfo pyr.tif 
TIFF Directory at offset 0x21bec (138220)
  Image Width: 800 Image Length: 1132
  Tile Width: 128 Tile Length: 128
  Resolution: 28.3465, 28.3465 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: RGB color
  Extra Samples: 1<assoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 4
  Planar Configuration: single image plane
  JPEG Tables: (289 bytes)
```

So I think iip is misinterpreting your image as CMYK.

libvips 8.6 writes a three-band sRGB image instead:

```
$ tiffinfo pyr.tif 
TIFF Directory at offset 0xb870 (47216)
  Image Width: 800 Image Length: 1132
  Tile Width: 128 Tile Length: 128
  Resolution: 28.3465, 28.3465 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
  JPEG Tables: (574 bytes)
```

So it should work better with iipimage.

I would recommend updating your libvips. 8.6 is noticably faster than 8.2, as well as writing smaller and simpler TIFFs.

**Comment by lallori** [comment]
Thanks John!!

I updated to 8.6, created the pyramid tiled tiff and the image is perfect.

Problem solved!!
