### ISSUE TITLE
Installing Brew with flags now fails to link to correct libjpeg

### ISSUE THREAD

**Issue by vibbix** [jcupitt/libvips#902]
If you try to run `brew install vips --with-jpeg-turbo --with-webp`, and then for example try to convert any image to a JPG using 
`vips copy in.webp out.jpg` you get the following error:
`VipsJpeg: Wrong JPEG library version: library is 90, caller expects 80`

When I ran Otool against libvips i got this:

otool -L $(which vips)
/usr/local/bin/vips:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1451.0.0)
	/usr/local/Cellar/vips/8.6.3/lib/libvips.42.dylib (compatibility version 51.0.0, current version 51.2.0)
	/usr/local/opt/libpng/lib/libpng16.16.dylib (compatibility version 51.0.0, current version 51.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/local/opt/libtiff/lib/libtiff.5.dylib (compatibility version 9.0.0, current version 9.0.0)
	/usr/local/opt/jpeg/lib/libjpeg.9.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/local/opt/glib/lib/libgmodule-2.0.0.dylib (compatibility version 5401.0.0, current version 5401.3.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/local/opt/pango/lib/libpangoft2-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.14.0)
	/usr/local/opt/pango/lib/libpango-1.0.0.dylib (compatibility version 4001.0.0, current version 4001.14.0)
	/usr/local/opt/fontconfig/lib/libfontconfig.1.dylib (compatibility version 12.0.0, current version 12.1.0)
	/usr/local/opt/freetype/lib/libfreetype.6.dylib (compatibility version 23.0.0, current version 23.0.0)
	/usr/local/opt/libgsf/lib/libgsf-1.114.dylib (compatibility version 115.0.0, current version 115.42.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/local/opt/fftw/lib/libfftw3.3.dylib (compatibility version 9.0.0, current version 9.7.0)
	/usr/local/opt/orc/lib/liborc-0.4.0.dylib (compatibility version 29.0.0, current version 29.0.0)
	/usr/local/opt/little-cms2/lib/liblcms2.2.dylib (compatibility version 3.0.0, current version 3.8.0)
	/usr/local/opt/giflib/lib/libgif.7.dylib (compatibility version 8.0.0, current version 8.0.0)
	/usr/local/opt/librsvg/lib/librsvg-2.2.dylib (compatibility version 45.0.0, current version 45.2.0)
	/usr/local/opt/glib/lib/libgio-2.0.0.dylib (compatibility version 5401.0.0, current version 5401.3.0)
	/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib (compatibility version 3603.0.0, current version 3603.0.0)
	/usr/local/opt/poppler/lib/libpoppler-glib.8.dylib (compatibility version 8.0.0, current version 8.9.0)
	/usr/local/opt/glib/lib/libgobject-2.0.0.dylib (compatibility version 5401.0.0, current version 5401.3.0)
	/usr/local/opt/glib/lib/libglib-2.0.0.dylib (compatibility version 5401.0.0, current version 5401.3.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/usr/local/opt/cairo/lib/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.12.0)
	/usr/local/opt/webp/lib/libwebpmux.3.dylib (compatibility version 4.0.0, current version 4.1.0)
	/usr/local/opt/webp/lib/libwebp.7.dylib (compatibility version 8.0.0, current version 8.1.0)
	/usr/local/opt/libexif/lib/libexif.12.dylib (compatibility version 16.0.0, current version 16.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

It looks like it links against LibJPEG instead of LibJPEG-Turbo. The latest version of Vips, 8.6.3, modified the build script to detect LibJPG via pkg-config, so that might have something to do with it.

**Comment by jcupitt** [comment]
Yes, I'd guess that's the cause. I'll have a look on my mac tonight.

Does the brew package for libjpeg-turbo not install a .pc file?

**Comment by vibbix** [comment]
Apparently it doesn't. To prevent LibJPEG conflicts, you need special paths for pkg-config apparently.
![image](https://user-images.githubusercontent.com/1731900/37301763-ea04760e-25ff-11e8-8537-433d936c3b81.png)

**Comment by jcupitt** [comment]
I tried adding this to `vips.rb` in the install section:

```ruby
    if build.with? "jpeg-turbo"
      ENV["JPEG_CFLAGS"] = "-I#{Formula["jpeg-turbo"].opt_include}"
      ENV["JPEG_LIBS"] = "-L#{Formula["jpeg-turbo"].opt_lib} -ljpeg"
    end
```

And it now seems to work for me:

```
$ vips copy ~/pics/1.webp 1.jpg
$ 
```

I'll open a PR.

**Comment by vibbix** [comment]
Ill verify it also works with MozJPEG

**Comment by vibbix** [comment]
Both MozJPEG & JPEG-turbo now work fine with the modifications, thanks!

**Comment by aried3r** [comment]
@vibbix, they just removed support for mozjpeg and libjpeg-turbo in homebrew:
https://github.com/Homebrew/homebrew-core/pull/25711
https://github.com/Homebrew/homebrew-core/pull/25682

[vips formula](https://github.com/Homebrew/homebrew-core/blob/a58c7b32c9ab679bc5f1afecc45f315710676ba1/Formula/vips.rb) as of today.

**Comment by jcupitt** [comment]
Yes, sorry, this is a very unfortunate situation. I'm not sure what the best way forward is.

**Comment by aried3r** [comment]
I know too little about image processing to offer any valuable input, but assuming that I'd have to use both vips and `cjpeg` provided by mozjpeg, I guess I'd have to pipe the output of vips into mozjpeg as a final step. I just wonder how much quality I sacrifice doing that and if that's even a sensible option.

Or I'll have to resort to building vips myself, which is certainly doable but just so much more uncomfortable than `brew install --with-turbo-jpeg --with-mozjpeg` and using `brew upgrade`, heh.

Anyway, thanks for your great work on libvips!

**Comment by jcupitt** [comment]
You could use a docker image for this I guess. It's very simple to make an Alpine (for example) container with all your stuff in configured exactly as you want. 

Development on macOS has become slowly more difficult over the last few years, sigh.

**Comment by jcupitt** [comment]
I think this is done, or as much as we can.
