### ISSUE TITLE
Convert Pyramid to normal image?

### ISSUE THREAD

**Issue by mgiacomelli** [jcupitt/libvips#903]
I have been using VIPS to make pyramidal images for online viewing and it works great.  Recently I found a situation where I would like to take an existing pyramid and recover the PNG/TIFF file used to create it.  Is there a way to do this?  I didn't see an obvious way to do it, but I may have missed something.

**Comment by jcupitt** [comment]
You can use `arrayjoin` to join up a set of tiles:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-arrayjoin

On Windows, it can't join more than 2000 tiles in one go, but it should work on linux or macOS. Something like:

```
vips arrayjoin "$(echo *.jpg)" x.tif --across 20
```

To join all jpg images in the current directory into a grid 20 tiles across. If your pyramid has an overlap, you'll need to check the size of the tiles and set `hspacing` and `vspacing`.

**Comment by mgiacomelli** [comment]
Thanks, but unless I'm missing something, arrayjoin and DZI pyramids generated by VIPS assume transposed ordering.  For example, looking at a pyramid, 0_0.jpg is the top left, 0_1.jpg is one frame below the top left, and so on. However, according to the documentation, arrayjoin stiches left to right, not up to down.  

Is there some way to transpose it short of rather painfully rewriting *.jpg to sort differently?

**Comment by mgiacomelli** [comment]
I wrote something to transpose the file list, but I do indeed run into path length limits on Windows.  Is there a way to pass in VIPS a text file with a list of files?  Some pyramidal images I have are enormous and have tens of thousands of tiles.

**Comment by jcupitt** [comment]
You can transpose the tiles on linux like this:

```
$ vips arrayjoin "$(ls *.jpg | sort -t_ -k2g -k1g)" x.tif --across 20
```

ie. sort numerically by field 2 then field 1, with `_` as a field separator. It should work for any number of files.

On Windows, there's a hard limit of 2,000 files at once, since no process can have more than 2,000 file handles. I think you'd need to assemble in sections, perhaps a few rows at a time, then join those rows up.

You could also use WSL and do it from linux within Windows. I don't know if that would get around the file handles limit.

**Comment by jcupitt** [comment]
I forgot to actually answer your question, sorry. 

No, there's no way to get arrayjoin to read a list of files directly from a file. You'd need to use Python / Ruby / Lua / node / etc. to do it. I use ruby-vips on Windows and it's pretty easy to set up: you just download a 64-bit Ruby, set `RUBY_DLL_PATH` to point to the folder containing `libvips.dll`, then `gem install vips`.

You can use `arrayjoin` from Ruby with something like:

```ruby
tiles = []
(0..tiles_down).each do |y|
    (0..tiles_across).each do |x|
        tiles << Vips::Image.new_from_file "#{x}_#{y}.jpg", access: :sequential
    end
end
huge = Vips::Image.arrayjoin tiles, across: 20
huge.write_to_file "x.tif"
```
