### ISSUE TITLE
Does libvips provide a simple way to convert an image to a 1 bit-per-pixel image using a threshold value?

### ISSUE THREAD

**Issue by Mike314** [jcupitt/libvips#908]
Hi, does libvips provide a simple way to convert an image to a 1 bit-per-pixel image (color depth = 1) using a threshold value? Better yet, is there a way to get the resize operation to NOT increase the image depth? Currently, using the resize operation a 1-bit image gets automatically converted to an 8-bit image.

**Comment by jcupitt** [comment]
Hello again @Mike314,

libvips does not support one-bit or palette images as a format that can be computed with. You have to unpack to something like 8-bit mono, then process, then pack down again on save.

The TIFF saver (for example) has a `squash` flag which enables one-bit write:

```
vips resize x.tif y.tif[squash,compression=ccittfax4] 0.1
```

That'll decode, shrink by 10, and recode. For conversion to 1-bit, it tests for pixel value >= 128, so you should get nice aliasing behaviour on edges.

**Comment by Mike314** [comment]
john,

Thank for the quick response! 

One more question: Is there a trick to resize a multi-page tiff in one call to the resize operation, instead of calling it for each page then re-assembling the results?

**Comment by jcupitt** [comment]
Yes, just load with n=-1 and resize. You’ll need to adjust the page height. I’ll post an example when I’m back on a laptop.

**Comment by jcupitt** [comment]
There was some stuff introducing multipage handling in the 8.5 release notes:

https://jcupitt.github.io/libvips/2017/03/16/What's-new-in-8.5.html#toilet-roll-images

The TIFF load and save (for example) docs have more detail:

http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-tiffload

http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-tiffsave

I made a tiny Ruby example:

```ruby
#!/usr/bin/env ruby

require 'vips'

a = Vips::Image.new_from_file ARGV[0]

# compound property names are hyphenated
page_height = "page-height"

# if the "page_height" property is present, we have a toilet roll image,
# otherwise it's a single page
height = a.get_typeof(page_height) ? a.get(page_height) : a.height

# calculate a shrink factor from the page size
target_height = 80
scale = target_height.to_f / height

a = a.resize scale

# page_height will still be set for the huge image ... adjust for our shrunk
# image
a.set page_height, target_height

# you can also give page_height as an argument to the saver, if that's easier
a.write_to_file ARGV[1], page_height: target_height
```

You can use it like this:

```
john@kiwi:~/try$ vips copy nipguide.pdf[n=-1] x.tif
john@kiwi:~/try$ vipsheader x.tif[n=-1]
x.tif: 595x48778 uchar, 4 bands, srgb, tiffload
john@kiwi:~/try$ ./resize.rb x.tif[n=-1] y.tif
john@kiwi:~/try$ vipsheader y.tif[n=-1]
y.tif: 57x4640 uchar, 4 bands, srgb, tiffload
john@kiwi:~/try$ vipsheader y.tif
y.tif: 57x80 uchar, 4 bands, srgb, tiffload
```

So `y.tif` is a version with each page shrunk to 80 pixels high. That's using TIFF, but it'll work in the same way for at least PDF and GIF as well.

**Comment by jcupitt** [comment]
If your multipage document has pages which differ in size, you'll probably need to find another library :(
