### ISSUE TITLE
glibconfig.h is nowhere in the include folder or subfolders

### ISSUE THREAD

**Issue by Mike314** [jcupitt/libvips#909]
gpoll.h #includes <glibconfig.h>. However, glibconfig.h is nowhere in the include folder or subfolders. 

Do you have a solution?

**Comment by jcupitt** [comment]
Hello @Mike314, it's in `lib/glib-2.0/include/glibconfig.h`. You'll need to add that to your compiler include path. 

This is the standard place for config includes. The reasoning is that most includes are architecture-independent (they will work equally well on 32- and 64-bit machines, for example), but the config header contains declarations such as endianness, which are very architecture-specific. They therefore go in with the compiler binaries they are generated for.

**Comment by jcupitt** [comment]
I meant to say, on *nix systems this is handled for you by `pkg-config`. Compile with something like:

```
cc myprog.c `pkg-config vips --cflags --libs`
```

On Windows you will need to set -I, -L and the list of libraries by hand.
