### ISSUE TITLE
Gaussian blur not working?

### ISSUE THREAD

**Issue by angelmixu** [jcupitt/libvips#910]
Hi!

We are using gaussian blur on vips 8.6.2 and looks like it is not working.
Here is the code we used:

```
int main(int argc, char* argv[])
{
	if (VIPS_INIT(argv[0]))
		vips_error_exit(NULL);

	VipsImage* in; 
	in = vips_image_new_from_file("checker_board.png", 0);
	if (!in)
		vips_error_exit(NULL);

	VipsImage* out = vips_image_new();

	double sigma = 0.6;
	double min_amplitude = 1.0;

	INTMASK* imask = im_gauss_imask("VIMask::gauss", sigma, min_amplitude);

	im_conv(in, out, imask);

	int result = vips_image_write_to_file(out, "checker_board_out.png", 0);
	if (result)
		vips_error_exit(NULL);
	
	g_object_unref(in);
	g_object_unref(out);

    return 0;
}
```
For any sigma value that we use (even for 3000) the output is the same.
If you take a look at the imask being generated it always has a size of 1x1 and an scale of 20, which is quite strange.
The resulting image is the same as before.

Debugging the code and comparing with vips v7.something we got to the point that if we changed some code it worked as was in vips 7.something.

The file we changed is gaussmat.c, line 132. Inside vips_gaussmat_build function there's a calculation for width like this:

`width = 2 * x - 1;`

And we changed it like this:

`width = 2 * x + 1;`

Now it generates a 3x3 matrix, and the output image is blurred.

Could anyone tell us if we are doing something wrong, or if this is a bug?

Thanks!

**Comment by jcupitt** [comment]
Hello, you are using a mixture of the vips7 and vips8 API. I would just switch to vips8, like this:

```C
/* compile with
 *
 *      gcc -g -Wall blur8.c `pkg-config vips --cflags --libs`
 *
 */

#include <vips/vips.h>

int main(int argc, char* argv[])
{
        double sigma = 3.0;

        VipsImage* in; 
        VipsImage* out;

        if (VIPS_INIT(argv[0]))
                vips_error_exit(NULL);

        if (!(in = vips_image_new_from_file(argv[1], NULL)))
                vips_error_exit(NULL);

        if (vips_gaussblur(in, &out, sigma, NULL))
                vips_error_exit(NULL);

        if (vips_image_write_to_file(out, argv[2], NULL))
                vips_error_exit(NULL);

        g_object_unref(in);
        g_object_unref(out);

        return 0;
}
```

Which runs like this:

```
$ ./a.out checkerboard.png x.png
```

![x](https://user-images.githubusercontent.com/580843/37711849-04ee03ca-2d0a-11e8-9784-dea3f9e0d3fb.png)

Having said that, I think your program ought to work. I'll investigate.

**Comment by jcupitt** [comment]
Oh heh, I think it's a typo, just set:

```
        double min_amplitude = 0.1;
```

`min_ampl` is the minimum amplitude of the generated mask, where 1.0 is the peak at the centre. If you set it to 0.1, you'll get a mask that stretches out to 10% of the maximum. If it's 1.0, you'll only ever get the single pixel in the centre.

Still, I would use `vips_gaussblur()`. It's much faster, and it'll handle things like that for you.

**Comment by angelmixu** [comment]
Woah! Thanks for the quick answer!!!

Your first example works perfect.
And if I adapt the code I had for using vips_gaussblur() also works correctly.

Funny thing is, we have this vips7 'big old legacy code', and we were using this for generating the VIMask:
```
double min_amplitude = 1.0;
VIMask gmask =	VIMask::gauss( sigma, min_amplitude );
```
It worked fine with vips 7.24 (I think, no one knows exactly which vips version is lol), and when migrating code to 8.6.2 it wasn't working.
We were even debugging side by side the old code with the new one.

Using min_amplitude to 0.1 works as intended in the legacy code.
Let's see if soon we can migrate to vips8 interface :'D

Thanks again!!! 
I owe you (or the company I'm working at) some beers :)

**Comment by jcupitt** [comment]
No problem, glad it's working.
