### ISSUE TITLE
Issue with converting mrxs to dzi

### ISSUE THREAD

**Issue by rgluskin** [jcupitt/libvips#911]
Hi,
I'm trying to convert a 22-level mrxs file to dzi, using this command:
`
vips dzsave 1.mrxs dz1 
`
The output comes out only as 12 levels.
I'm succesfully able to open the file in nip2 and it shows 103282x250596 8-bit unsigned integer, 4 bands, RGB, or using ASAP (and get down to the finest levels of zoom).

A partially functioning workaround:

`
vips openslideload --vips-concurrency=8 1.mrxs dz1.tiff[tile,compression=lzw] --level 1
vips dzsave dz1.tiff dz1 --vips-concurrency=8
`
The result output has 18 levels.
In both cases:
level 0 has 1 1x1 pixel image
level 1 has 1 1x2 pixel image
level 2 has 1 2x4 pixel image
level 3 has 1 4x8 pixel image
level 4 has 1 7x16 pixel image
level 5 has 1 13x31 pixel image
level 6 has 1 26x62 pixel image
level 7 has 1 51x123 pixel image
level 8 has 1 101x245 pixel image
level 9 has 2 202x255 pixel images
and the subsequent levels have the appropriate amounts of either 255x255 or 256x256 images.
But in one case it stops after level 11, and in another it continues upto level 17

As an aside, if I don't specify `--level 1 `, I get the following error message:
`TIFFAppendToStrip: Maximum TIFF file size exceeded `
`vips2tiff: TIFF write tile failed `
`wbuffer_write: write unix error: Unknown error -1`
`vips_region_prepare_to: dest too small `
`vips_region_prepare_to: dest too small `
`vips_region_prepare_to: dest too small `
`vips_region_prepare_to: dest too small `
`vips_region_prepare_to: dest too small `
`vips_region_prepare_to: dest too small `
`vips_region_prepare_to: dest too small `
`TIFFAppendToStrip: Maximum TIFF file size exceeded `

The tiff file is 4GB but seems to be corrupt. I'm unfamiliar with the tiff spec... It could be because I have it on a FAT32 drive... In either case, that's an aside and not the main problem.

Can you provide any suggestion for a straightforward conversion ?

Thanks,
Roman

**Comment by jcupitt** [comment]
I think FAT32 is causing your problems:

https://superuser.com/questions/446282/max-files-per-directory-on-ntfs-vol-vs-fat32

It does not allow more than 65,535 files in a directory, and it does not allow files larger than 4GB. Your image is 103282 x 250596 pixels, so with 256 x 256 tiles, that's 404 x 979 tiles, or almost 400,000 files in a directory.

Your best solution would probably be to convert your drive to NTFS and then write a zip file like this:

```
vips dzsave 1.mrxs mypyr.zip
```

Now dzsave will write the pyramid to a zip file called `mypyr.zip`. You can copy this around, then unzip on your server when you want to be able to share the image. It'll automatically make a zip64 if it has to.

As a bonus, creating a zip file is about 4 x faster than creating a big tree of files, since NTFS really struggles with large directories.

**Comment by jcupitt** [comment]
Hello, by the way :)

**Comment by jcupitt** [comment]
One more thing, you can use `--vips-progress` to get some simple progress feedback:

```
john@yingna ~/pics/openslide $ vips dzsave Mirax2.2-1.mrxs x.dz --vips-progress
vips temp-1: 101832 x 219976 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
vips temp-1: 100% complete
vips temp-1: done in 460s          
```

So it should be about 8 minutes for your image.

**Comment by rgluskin** [comment]
Hi John.
Thanks for your reply.
I reproduced the issue on NTFS, and another team member reproduced it on his MAC.

The zip file gets created successfully with 12 levels.
The progress log shows the following:
`root@cb54f8bc4567:/# vips dzsave --vips-concurrency=8 1.mrxs dz1.zip --vips-progress`
`vips temp-1: 808 x 1958 pixels, 8 threads, 808 x 16 tiles, 512 lines in buffer`
`vips temp-1: done in 0.177s`

Without the multithreading:
`root@cb54f8bc4567:/# vips dzsave 1.mrxs dz1.zip --vips-progress`
`vips temp-1: 808 x 1958 pixels, 2 threads, 808 x 16 tiles, 256 lines in buffer`
`vips temp-1: done in 0.0692s`

So it seems that the image dimensions are not correctly recognized in this flow...
Any suggestions are welcome.
Thanks,
Roman

**Comment by jcupitt** [comment]
Perhaps you are using a libvips without openslide support? 

Could you try running `vipsheader`. You should see something like:

```
$ vipsheader CMU-1.mrxs 
CMU-1.mrxs: 109240x220696 uchar, 4 bands, rgb, openslideload
```

If you don't see `openslideload` at the end, libvips is not configured correctly.

**Comment by jcupitt** [comment]
To get a libvips with openslide support on Windows, make sure you are using the `all` zip:

https://github.com/jcupitt/libvips/releases/download/v8.6.3/vips-dev-w64-all-8.6.3-1.zip

The `web` zip is a minimal libvips for web use and is missing things like openslide.

On macOS, install with homebrew and make sure you enable openslide. It's an optional extra. See:

https://jcupitt.github.io/libvips/install.html

**Comment by rgluskin** [comment]
I'm actually running in a docker...

indeed I see a wrong output:
`root@cb54f8bc4567:/# vipsheader 1.mrxs`
`1.mrxs: 808x1958 uchar, 3 bands, srgb, jpegload`

However:
`root@cb54f8bc4567:/# dpkg --list | grep openslide`
`ii  libopenslide0                   3.4.0-1build1                       amd64        library for reading whole slide image files`
So it is installed...
What am I missing ?

**Comment by jcupitt** [comment]
libvips has a chunk of code to connect it to openslide and this needs to be enabled when libvips configures itself. What linux are you using, and how did you get the libvips binary?

If it's Alpine, you'll need to build your own libvips, there's another issue about this:

https://github.com/jcupitt/libvips/issues/874#issuecomment-375643193

**Comment by rgluskin** [comment]
using ubuntu and installed using apt-get.
I see that I have version 8.2.2-1, so obviously my apt repository doesn't have the up to date...
What would you recommend as the best way to resolve this ?

**Comment by jcupitt** [comment]
I have Ubuntu 17.10 on my laptop and that has libvips configured with openslide support. I guess you are using 16.04, is that right?

You could either stick with 16.04 and build libvips yourself (it's not difficult, that Alpine dockerfile should have all the info you need), or update to a more recent Ubuntu. The advantage of building libvips yourself would be that you could disable the bits you don't need, which would help security, and build the latest version, which would also be good.

**Comment by rgluskin** [comment]
Very well, I will try that.

In either case I was able to successfully convert on windows now, so that confirms the root cause.

Thank you very much for your support!

**Comment by jcupitt** [comment]
I tried on my mac:

```
$ brew install vips --with-openslide
Updating Homebrew...
==> Installing dependencies for vips: openslide
==> Installing vips dependency: openslide
==> Downloading https://homebrew.bintray.com/bottles/openslide-3.4.1_4.high_sier
######################################################################## 100.0%
==> Pouring openslide-3.4.1_4.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/openslide/3.4.1_4: 16 files, 326KB
==> Installing vips --with-openslide
==> Downloading https://github.com/jcupitt/libvips/releases/download/v8.6.3/vips
Already downloaded: /Users/john/Library/Caches/Homebrew/vips-8.6.3.tar.gz
==> ./configure --prefix=/usr/local/Cellar/vips/8.6.3_1 --enable-pyvips8 PYTHON=
==> make install
Warning: vips dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/vips/8.6.3_1: 177 files, 10.8MB, built in 3 minutes 1 second
$ vipsheader CMU-1.svs 
CMU-1.svs: 46000x32914 uchar, 4 bands, rgb, openslideload
```

So that should work too.
