### ISSUE TITLE
RGB to CMYK using icc_export turn rgb(255,255,255) to cmyk(2%, 1%, 1%, 0%)

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#916]
pyvips code:

```python
out= in.icc_export(pcs="lab", intent="relative", output_profile="rgb2cmyk.icc")
out.tiffsave("cmyk.tif", compression ="lzw", predictor="horizontal")
```

check output file cmyk.tiff in Photoshop, color of rgb(255,255,255) is now cmyk(2%, 1%, 1%, 0%) 
which is expected to be cmyk(0%, 0%, 0%, 0%) .

Tried all intent options of icc_export,  get the same result.
The same icc profile use in Photoshop produce the right result which is cmyk(0%, 0%, 0%, 0%) .

I think there might be two directions to get over this

1. Maybe there are some ICC  convert options I didn't aware;
2. Find those color with cmyk(2%, 1%, 1%, 0%)  in the output image and replace them with cmyk(0%, 0%, 0%, 0%).

for method 1, I checkout the pyvips document here:
https://jcupitt.github.io/pyvips/vimage.html#pyvips.Image.icc_export
without any luck.

for method 2, I try use something like:

mask = outputFinal.subtract((2,1,1,0))
out= pyvips.Image.ifthenelse(mask, 0, out)

which is not yet tweak to work.

Any Suggestion, Thanks.

**Comment by jcupitt** [comment]
Hello @jindili,

libvips uses lcms2 for ICC transforms. It follows the spec very closely and is generally more accurate then photoshop. I'd expect any differences to be down to the exact profiles you used.

For example, using the profiles distributed with nip2:

https://github.com/jcupitt/nip2/tree/master/share/nip2/data

like this:

```
$ vips icc_transform white.jpg x.tif cmyk.icm --input-profile sRGB.icm
```

I see CMYK (0, 0, 0, 0) for RGB (255, 255, 255).

**Comment by jcupitt** [comment]
Oh, don't use `icc_export`:  that's to go from PCS to device space. 

You want to map from one device space (sRGB, I assume?) to another (CMYK), so you need to use `icc_transform` plus two profiles.

**Comment by jcupitt** [comment]
The main docs are here:

http://jcupitt.github.io/libvips/API/current/libvips-colour.html#vips-icc-transform

**Comment by jindili** [comment]
Hi, John,
Just use
```python
out = in.icc_transform("rgb2cmyk.icc")
```
or
```python
out = in.icc_transform("rgb2cmyk.icc",  input_profile="sRGB.icm")
```
produce correct result,

with or without the input_profile seems no obvious difference

**Comment by jindili** [comment]
@jcupitt 

In some other case, If I want to Find those color with cmyk(2%, 1%, 1%, 0%) or lighter in some image and clear them (replace them with cmyk(0%, 0%, 0%, 0%)).

which is the suggested way to do.
