### ISSUE TITLE
numpy float array to VIPS image (pyvips)

### ISSUE THREAD

**Issue by MatthiasKohl** [jcupitt/libvips#917]
Hi,
This is more intended as a question than a bug report, but I'd like to create a VIPS image from a numpy float array in pyvips. When working with one-byte datatypes, this works fine as per documentation:

```python
    a = np.array([[1, 2], [3, 4]], dtype=np.uint8)
    v = pyvips.Image.new_from_memory(a.flatten().data, a.shape[1], a.shape[0], 1, pyvips.BandFormat.UCHAR)
```

But this breaks (for me) with data-types that carry multiple bytes, i.e.
```python
    a = np.array([[1, 2], [3, 4]], dtype=np.float32)
    v = pyvips.Image.new_from_memory(a.flatten().data, a.shape[1], a.shape[0], 1, pyvips.BandFormat.FLOAT)
```

This may be because `numpy.ndarray.data` just returns a Python memoryview/buffer object that does not iterate over single bytes, but over sets of bytes according to the datatype (Python 3.5, numpy 1.14).
Are you aware of something that can be used in any (or most) versions of Python/numpy ? It seems like it's working with `numpy.ndarray.tobytes()` for me, although this creates a new buffer every time I think.

Anyway, thanks for your input !

**Comment by jcupitt** [comment]
Hello @MatthiasKohl,

Oh, interesting. Yes, I think `tobytes()` is your only way, which is disappointing. 

At the moment it's using `len(data)` to get the number of bytes, but it seems like `.nbytes` might be better:

```
$ python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Nov  9 2017, 00:19:18) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.array([[1, 2], [3, 4]], dtype=np.float32)
>>> a.data
<memory at 0x7f697e3a0b40>
>>> a.data.nbytes
16
>>> a.data.contiguous
True
```

You could potentially skip the `flatten()` as well, which would make it quite a bit quicker.

I don't suppose you know much about memoryview? I'm working in the dark :(

**Comment by MatthiasKohl** [comment]
Hi @jcupitt ,
Thanks for the quick answer. Unfortunately you're right, I'm not an expert about handling bytes in Python, and I don't know about the `memoryview` class (apart from seeing it in the debugger).
But it seems like `ffi.from_buffer` supports both APIs (python2 buffer and python3 memoryview), so if it's only about knowing the number of bytes, you could do something like this: `data.nbytes if hasattr(data, 'nbytes') else len(data)`.
Another consistent way of doing it would be `sys.getsizeof(data) // 8`.

And just in case anyone else is reading this, `flatten()` indeed creates a copy of the array, so it is quite slow here, but you could achieve the same with `a.reshape(reduce(operator.mul, a.shape))` or something similar, which only creates a new view on the array.

**Comment by jcupitt** [comment]
I made a branch with your suggested change, it seems to work! No `flatten` required either. 

With this test program:

```
import numpy as np
import pyvips

a = np.array([[1, 2], [3, 4]], dtype=np.uint8)
v = pyvips.Image.new_from_memory(a.data, a.shape[1], a.shape[0], 1, "uchar")

print("v(0, 0) =", v(0, 0))
print("v(1, 1) =", v(1, 1))

a = np.array([[1, 2], [3, 4]], dtype=np.float32)
v = pyvips.Image.new_from_memory(a.data, a.shape[1], a.shape[0], 1, "float")

print("v(0, 0) =", v(0, 0))
print("v(1, 1) =", v(1, 1))
```

I see:

```
john@yingna ~/try $ python x.py 
('v(0, 0) =', [1.0])
('v(1, 1) =', [4.0])
('v(0, 0) =', [1.0])
('v(1, 1) =', [4.0])
john@yingna ~/try $ python3 x.py 
v(0, 0) = [1.0]
v(1, 1) = [4.0]
v(0, 0) = [1.0]
v(1, 1) = [4.0]
```

**Comment by MatthiasKohl** [comment]
This looks great ! I will test the new branch as well and then close this issue.
Thanks for your help @jcupitt !

**Comment by jcupitt** [comment]
I've merged this to master pyvips -- other people were reporting similar issues, and the fix seems sensible.

**Comment by MatthiasKohl** [comment]
Thanks @jcupitt! Sorry for not getting back earlier
