### ISSUE TITLE
vips_affine creates wrong black pixels from an image with alpha channels

### ISSUE THREAD

**Issue by angelmixu** [jcupitt/libvips#918]
Hi again, it's me! (Sorry :p)

We are using affine for shrinking and cropping an image and after processing it, affine seems to put lots of black pixels.

In the attached zip, the file bikini.tif is the origin, and the output is bikini_full_out.jpeg
[testVipsAffine.zip](https://github.com/jcupitt/libvips/files/1855537/testVipsAffine.zip)

The minimum example we used is the following:

```
#include <vips/vips.h>
#include <vips/image.h>
#include <vips/transform.h>

int main(int argc, char* argv[])
{
	if (VIPS_INIT(argv[0]))
		vips_error_exit(NULL);

	VipsImage* in;

	in = vips_image_new_from_file("bikini.tif", 0);
	if (!in)
		vips_error_exit(NULL);

	VipsImage* out = vips_image_new();

	double a = 0.960177004;
	double b = 0;
	double c = 0;
	double d = 0.960444987;
	double dx = 0;
	double dy = 0;
	int x = 0;
	int y = 0;
	int w = 434;
	int h = 777;

	VipsInterpolate * interpolate = vips_interpolate_bilinear_static();
	
	VipsArea *oarea = VIPS_AREA( vips_array_int_newv( 4, 
		x, y, w, h ) );

	vips_affine(in, &out,
		a, b, c, d,
		"interpolate", interpolate,
		"oarea", oarea,
		"odx", 0,
		"ody", 0,
		NULL);

	int result = vips_image_write_to_file(out, "bikini_full_out.jpeg", 0);
	if (result)
		vips_error_exit(NULL);
	
	g_object_unref(in);
	g_object_unref(out);

    return 0;
}
```

We've also used affine on vips.exe commandline as this:
> vips affine bikini.tif affine_output.jpeg "2 0 0 2"
And the output is this one:
![affine_output](https://user-images.githubusercontent.com/2285977/38024411-35667908-3285-11e8-84f4-bd5b342e2ee2.jpeg)
The result is the same black pixels on the image, but twice the size.

BTW, on commandline with 'shrink' we get a warning and doesn't output any file:

> vips affine C:\testVipsAffine\testVipsAffine\bikini.tif affine_output.jpeg "0.1 0 0 0.1"
> 
> (vips:14212): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
> 
> (vips:14212): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
> 
> (vips:14212): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
> im_matinv: singular or near-singular matrix

Are we doing anything wrong?
We have got to the point that if the image has any alpha channel, it doesn't behave correctly. Without any alpha, the affine function works correctly.

Lots of thanks!

**Comment by jcupitt** [comment]
... so I think you were adding 0 for the alpha and not 255, and you are adding too many alphas. I would use `vips_bandjoin_const1(255)` to add the alpha channel:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-bandjoin-const1

**Comment by angelmixu** [comment]
Lots of thanks again :)

We use lots of images with several bands, also we are sent images like that all the time.
In this case some of the bands are 'Masked Areas' (the ones with alpha) from Adobe Photoshop, and on other cases are 'Spot Color' band.

So, in order to work correctly, we have to resize/crop/etc. the image with all its channels/bands.

As you suggested to extract the RGB from the image, we thought we could process the RGB and the masks (alpha bands) separatedly.

```
	VipsImage* in;
	in = vips_image_new_from_file("bikini.tif", 0); 
	if (!in)
		vips_error_exit(NULL);

	VipsImage* imageColor = vips_image_new();
	VipsImage* imageMasks = vips_image_new();

	int nbands = 3;
	vips_extract_band(in, &imageColor, 0,		"n", nbands,			0);
	vips_extract_band(in, &imageMasks, nbands,  "n", in->Bands-nbands,  0);
	
	double a = 0.960177004;
	double b = 0;
	double c = 0;
	double d = 0.960444987;
	double dx = 0;
	double dy = 0;

	VipsInterpolate * interpolate = vips_interpolate_bilinear_static();
	
	vips_affine(imageColor, &imageColor,
		a, b, c, d,
		"interpolate", interpolate,
		"odx", 0,
		"ody", 0,
		NULL);

	vips_affine(imageMasks, &imageMasks,
		a, b, c, d,
		"interpolate", interpolate,
		"odx", 0,
		"ody", 0,
		NULL);
	
	vips_bandjoin2(imageColor, imageMasks, &imageColor, 0);

	int result = vips_image_write_to_file(imageColor, "bikini_full_out.psd", 0);
	if (result)
		vips_error_exit(NULL);
	
	g_object_unref(in);
	g_object_unref(out);
```
This outputs a correct PSD file that we can see each alpha channel correctly resized. (we have a custom loader and saver for PSD files).
In the case for TIFF, the output can't be correctly interpreted in Photoshop because it applies the first alpha channel to the RGB image.

Is this a good solution?

**Comment by angelmixu** [comment]
I've found something 'strange'.
In the previous method I used, two of the converted layers had some black points on the alpha channels.
Here are two screenshots:
<img src="https://user-images.githubusercontent.com/2285977/38238264-9e8b7930-3729-11e8-8ad7-34c8980f9a51.png" width=250>  <img src="https://user-images.githubusercontent.com/2285977/38238265-9ea568e0-3729-11e8-876e-29137deeabcb.png" width=250>

If I apply the affine per band, black pixels don't appear.

Here is the code I used:

```
        VipsImage* in; 

	in = vips_image_new_from_file("bikini.tif", 0); 
	if (!in)
		vips_error_exit(NULL);

	double a = 0.960177004;
	double b = 0;
	double c = 0;
	double d = 0.960444987;
	double dx = 0;
	double dy = 0;

	VipsImage*	   imageColor  = vips_image_new();
	VipsInterpolate* interpolate   = vips_interpolate_bilinear_static();

	int colorBands = 3;

	vips_extract_band(in, &imageColor, 0, "n", colorBands, 0);

	vips_affine(imageColor, &imageColor,
		a, b, c, d,
		"interpolate", interpolate,
		"idx", dx,
		"idy", dy,
		"odx", 0,
		"ody", 0,
		NULL);

	for (int i = colorBands; i < in->Bands; ++i)
	{
		VipsImage* outTemp = vips_image_new();

		vips_extract_band(in, &outTemp, i, 0);

		vips_affine(outTemp, &outTemp,
			a, b, c, d,
			"interpolate", interpolate,
			"idx", dx,
			"idy", dy,
			"odx", 0,
			"ody", 0,
			NULL);

		vips_bandjoin2(imageColor, outTemp, &imageColor, 0);
	}

	int result = vips_image_write_to_file(imageColor, "bikini_full_out_affine_per_layer.psd", 0);
	if (result)
		vips_error_exit(NULL);
	
	g_object_unref(in);
```

**Comment by jcupitt** [comment]
Hello again @angelmixu,

If an image has more bands than it should (eg. a six-band RGB  image), then libvips assumes that the final band is an alpha. Affine pre-multiplies alpha so that interpolation works correctly across transparent edges, so any 0 pixels in your final band will become black holes in your output image. 

Therefore, if you have extra bands and you just want them processed through, you'll need to add an extra all-white band at the end as your alpha. I tried this:

```
$ vips bandjoin_const bikini.tif x.v 255
$ vips affine x.v x.jpg "1 0.5 -0.5 1"
```

So that's your 9 band original, made into 10 bands with the extra alpha, rotated, and saved as JPG. The save as JPG will flatten out any alpha and drop all but the first three bands. I get this:

![x](https://user-images.githubusercontent.com/580843/38240526-b830b550-3727-11e8-93c3-c2233d68eea2.jpg)

**Comment by angelmixu** [comment]
Oh ok! Now I understand.
So if I force the image type to MULTIBAND, how will it work?
Will it process each band individually?

**Comment by jcupitt** [comment]
8.7 should let you set multiband and stop alpha detection (just pushed a change), but 8.6 does not.

**Comment by angelmixu** [comment]
Oh cool!!! Lots of thanks! :)

**Comment by angelmixu** [comment]
I have another issue (sorry if I'm a little annoying).

This time, I'm using affine to transform an RGB image with different interpolators.
What I've found is that if I use a transformation using only a downscale, it won't apply the specified interpolator.

Here's the code:
```
	VipsImage* in = vips_image_new_from_file("TesterRGB.tif", 0); 
	if (!in)
		vips_error_exit(NULL);

	double a = 0.5;
	double b = 0;
	double c = 0;
	double d = 0.5;
	double dx = 0;
	double dy = 0;

	VipsImage*		 imageNearest		= vips_image_new();
	VipsInterpolate* interpolateNearest = vips_interpolate_nearest_static();
	VipsArrayDouble* background			= vips_array_double_newv( 3, 255.0, 255.0, 255.0 );

	vips_affine(in, &imageNearest,
		a, b, c, d,
		"interpolate", interpolateNearest,
		"idx", dx,
		"idy", dy,
		"odx", 0,
		"ody", 0,
		"extend", VIPS_EXTEND_BACKGROUND,
		"background", background,
		NULL);
	
	int result = vips_image_write_to_file(imageNearest, "affine_interpolation_nearest.tif", 0);
	if (result)
		vips_error_exit(NULL);

	VipsImage*		 imageBilinear  = vips_image_new();
	VipsInterpolate* interpolateBilinear = vips_interpolate_bilinear_static();

	vips_affine(in, &imageBilinear,
		a, b, c, d,
		"interpolate", interpolateBilinear,
		"idx", dx,
		"idy", dy,
		"odx", 0,
		"ody", 0,
		"extend", VIPS_EXTEND_BACKGROUND,
		"background", background,
		NULL);
	
	result = vips_image_write_to_file(imageBilinear, "affine_interpolation_bilinear.tif", 0);
	if (result)
		vips_error_exit(NULL);

	VipsImage*		 imageBicubic  = vips_image_new();
	VipsInterpolate* interpolateBicubic = vips_interpolate_new("bicubic");

	vips_affine(in, &imageBicubic,
		a, b, c, d,
		"interpolate", interpolateBicubic,
		"idx", dx,
		"idy", dy,
		"odx", 0,
		"ody", 0,
		"extend", VIPS_EXTEND_BACKGROUND,
		"background", background,
		NULL);
	
	result = vips_image_write_to_file(imageBicubic, "affine_interpolation_bicubic.tif", 0);
	if (result)
		vips_error_exit(NULL);
	
	g_object_unref(in);
	g_object_unref(interpolateBicubic);
	g_object_unref(imageNearest);
	g_object_unref(imageBilinear);
	g_object_unref(imageBicubic);
```
Here's the original image: [TesterRGB.zip](https://github.com/jcupitt/libvips/files/1879376/TesterRGB.zip)
And the result: [affine_not_interpolating.zip](https://github.com/jcupitt/libvips/files/1879387/affine_not_interpolating.zip)

If I change the indices of the matrix to the following, I can see that the interpolator has been used:
double a = 0.5;
double b = 0.9;
double c = 0;
double d = 0.5;
[affine_b_09.zip](https://github.com/jcupitt/libvips/files/1879403/affine_b_09.zip)

double a = 0.5;
double b = 0.1;
double c = 0;
double d = 0.5;
[affine_b01.zip](https://github.com/jcupitt/libvips/files/1879404/affine_b01.zip)

double a = 0.5;
double b = 0.1;
double c = 0.1;
double d = 0.5;
[affine_b01_c01.zip](https://github.com/jcupitt/libvips/files/1879406/affine_b01_c01.zip)

Apart from that, I read in https://jcupitt.github.io/libvips/API/current/libvips-resample.html that affine would produce some aliasing, and that must be why the squares are jagged.

Am I doing something wrong?
Should I use other function?

Thanks again :)

**Comment by jcupitt** [comment]
Yes, it's just the way it works. Try this:

```
$ vips affine TesterRGB.tif nearest.png "0.5 0 0 0.5" --interpolate nearest --vips-cache-trace
$ vips affine TesterRGB.tif bilinear.png "0.5 0 0 0.5" --interpolate bilinear --vips-cache-trace
```

And it'll show you all the operations that libvips is executing internally. You should see that the affine is executed with the correct option.

The reason they look the same is that's just the way that these interpolators work. Suppose you have a number line like:

Pixel | Value
---|---
0 | 10
1 | 20
2 | 15
4 | 25

If you need to interpolate the value at 1.5 with bilinear, it's (20 + 15) / 2 == 17.5. But what if you need to interpolate the value at 2? It's simply 15, there's no interpolation to do. All interpolators of this sort equal nearest at exact pixel boundaries.

For resizing images, you really need to use `vips_resize()`, it handles this for you.

**Comment by angelmixu** [comment]
I see.
I made a test with vips_resize and works perfect.
Thanks again!

**Comment by jcupitt** [comment]
You'll find `vips_thumbnail()` is even better: it can do tricks like shrink-on-load, so you get a very nice speed increase and lower memory use for many file types.
