### ISSUE TITLE
Find and clean out small color values

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#919]
In some case, If I want to Find those color with cmyk(2%, 1%, 1%, 0%) or smaller value in some image and clear them (replace them with cmyk(0%, 0%, 0%, 0%)).

which is the suggested way to do.

**Comment by jcupitt** [comment]
Hello, in pyvips you can do:

```python
cmyk = pyvips.Image.new_from_file("x.tif")
mask = cmyk < [5, 10, 3, 3]
```

And `mask` will be a four-band true / false (255 / 0) image which is true where the condition is true. You want to find all pixels where all four bands are true, so you need to AND them together:

```python
mask = (cmyk < [5, 10, 3, 3]).bandand()
```

That will now be a one-band image which is 255 for all pixels where C < 5, M < 10, Y < 3 and K < 3. Finally, you want to make a new image which is 0 where that condition is true, and unchanged elsewhere. 

```python
mask = (cmyk < [5, 10, 3, 3]).bandand().ifthenelse(0, cmyk)
```

**Comment by jindili** [comment]
Work Great, Thanks @jcupitt
