### ISSUE TITLE
Use O_TMPFILE for temporary files

### ISSUE THREAD

**Issue by Alexander--** [jcupitt/libvips#922]
`O_TMPFILE` is a Linux-specific flag for open(), that allows creation of already-unlinked temporary files, that don't need to be explicitly removed via `unlink`. It was added in Linux 3.11 (~5 years old).

Alternatively, you can accomplish the same with `memfd_create`, added Linux 3.17 (~4 years old). The created file is hosted in tmpfs and, unlike with `O_TMPFILE`, you don't need to specify a parent directory to use it.

**Comment by jcupitt** [comment]
Yes, we could have a configure test and use it here:

https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/vips.c#L184

libvips temp files can be very large, so tmpfs would probably not work.

**Comment by Alexander--** [comment]
@jcupitt tmpfs is backed by swap, so it should not be critical (besides, vips already tries to create it's files in /tmp). But having option to create temp files in specific filesystem is nice too.

**Comment by jcupitt** [comment]
It seems most glibc do not have support yet. On Ubuntu 17.10 (for example) I see:

```
vips.c:203:12: error: ‘O_TMPFILE’ undeclared (first use in this function); did you mean ‘__O_TMPFILE’?
   flags |= O_TMPFILE;
```

The `__O_TMPFILE` is the kernel bit, but I'm reluctant to use that until it's blessed by glibc. Let's leave this open as an enhancement and revisit when it's more widely supported. 

(unless I've misunderstood something!)

**Comment by Alexander--** [comment]
@jcupitt You forgot to define `_GNU_SOURCE` before including `fcntl.h`. See `man 2 open`:

````
The O_DIRECT, O_NOATIME, O_PATH, and O_TMPFILE flags are Linux-specific. One must define _GNU_SOURCE to obtain their definitions.
````

**Comment by jcupitt** [comment]
OK, this is in master now, I'll close.
