### ISSUE TITLE
Tif xres

### ISSUE THREAD

**Issue by bender22** [jcupitt/libvips#923]
Hi John,
[xresTest.zip](https://github.com/jcupitt/libvips/files/1863537/xresTest.zip)

vipsheader.exe xresTest.tif -a returns the followng:
..
xres: 6825.94
yres: 6825.94
..

These values seem to be incorrect (must be 10 times greater), I checked exif data in several online tools, got 68259.3828, windows explorer gives DPI 173379  (173379 / 2.54 = 68259.4488).
Also, when I use xres to measure the distance I get 10 times greater result than it should be. 
Could you confirm the bug?

**Comment by jcupitt** [comment]
Hello @bender22, libvips xres/yres are always pixels/mm, then there's a bit of extra metadata to say what units the file had on load. For example:

```
$ vipsheader -a xresTest.tif 
xresTest.tif: 1920x1152 uchar, 3 bands, srgb, tiffload
...
xres: 6825.94
yres: 6825.94
...
resolution-unit: cm
...
```

So it's 6825.94 pixels/mm, but it'll be saved as 68259.4 pixels/cm.

**Comment by jcupitt** [comment]
Oh and the design idea is that fixed res units make calculations simpler. Image formats use pixels / mm / cm / inch / point / pica, and having to check the units on two images on every calculations is awful. Pixels/mm may not be used much, but at least there's only one unit to consider.
