### ISSUE TITLE
Pyramid tiff with jpeg corrupt on IIPIMage and IIPMooviewer

### ISSUE THREAD

**Issue by modou33** [jcupitt/libvips#925]
Hello.

I'm actually testing Vips for generating tiled TIFF from jpeg file and I'll work then with IIPImage. I've to deal with a large warehouse of images. thus, I'm mainly interested by the optimization of images size's.

However, I've almost the same problem as described on this thread: #99. I've also started my tests with Vips 8.2.2 (Ubuntu 16.04). Then, as recommended I've built Vips V 8.6.3 but the problem is still there (screenshot here: http://pleade.com/sites/default/files/pleade-iipmooviewer.png
![pleade-iipmooviewer](https://user-images.githubusercontent.com/36034161/38250578-70e14728-374f-11e8-9c9f-a4941c1b99cd.png)
).

Yon can download a Tiled TIFF that I've build on this link http://pleade.com/sites/default/files/pleade01.jpg.tif 

I'm using command below for creating tiled TIFF from jpeg:

`vips tiffsave pleade01.jpg pleade01.jpg.tif --tile --pyramid --compression jpeg --tile-width 256 --tile-height 256 --Q 45`

For information, I'm working with iipsrv v0.9.9

Thanks !

**Comment by jcupitt** [comment]
Oh dear, @ruven, does current iipimage support YCbCr pyr tiffs, or do you have to build from master?

I think your options are:

1. Try building your own iipsrv from master, because I think this probably has this bug fixed.

2. Use the `--rgbjpeg` flag to tiffsave to disable YCbCr mode, eg.:

```
vips tiffsave pleade01.jpg pleade01.jpg.tif --tile --pyramid --compression jpeg --tile-width 256 --tile-height 256 --Q 45 --rgbjpeg
```

Your files will be 2x larger, unfortunately, but at least they'll be made quickly.

**Comment by ruven** [comment]
The latest stable release of iipsrv does indeed support YCbCr, so to fix your problem, make sure you are using iipsrv 1.0

**Comment by modou33** [comment]
hello @ruven and @jcupitt I did tests on iipsrv v1.0 and it works. Thank you for you replies.

**Comment by jcupitt** [comment]
Thanks @ruven !
