### ISSUE TITLE
ICC Profile Conversions: Web and Print

### ISSUE THREAD

**Issue by johnvoncolln** [jcupitt/libvips#926]
I'm hoping to use php-vips to generate thumbnails within the CMYK gamut, but they need to be in RGB for viewing on the web.

For CMYK images I can just use an RGB export profile and I'm done.

For RGB images, I need to convert to CMYK and then back to RGB for viewing on web.

Is there an easier way?  Or will I just need to create another instance of Image to do the second conversion?

Also - I appreciate your hard work on this project and you ability to help out people like me.  Thank you!

**Comment by jcupitt** [comment]
Hello @johnvoncolln,

You can convert RGB to CMYK with `icc_transform`:

http://jcupitt.github.io/libvips/API/current/libvips-colour.html#vips-icc-transform

For example:

```php
$cmyk = $rgb->icc_transform("/my/cmyk/profile.icm");
```

If you need to deal with untagged images, you'll need to supply a fall-back input profile as well. You can then thumbnail that image with `thumbnail_image`:

```php
$thumb = $cmyk->thumbnail_image(128, ["export-profile" => "/some/srgb/profile.icm"]);
```

Of course that'll be much, much slower than thumbnailing directly, and will look identical (I think). Perhaps I've misunderstood?

**Comment by johnvoncolln** [comment]
@jcupitt 

I just want to perform these transformations on a reduced size (thumbnail) image - the originally uploaded image will be preserved.  Would something like this be legit?
```php
$image = $uploadedImage->resize($scaleFactor);
$cmyk = $rgb->icc_transform("/my/cmyk/profile.icc");
$rgb = $cmyk->icc_transform("/my/rgb/profile.icc");
$rgb->writeToFile("/my/path/to/file.jpg");
```
Seems to work just fine...
___
Lastly - with ```icc_transform() ``` do I specify an input profile in an array as the second argument:
```php
$cmyk = $rgb->icc_transform("/my/cmyk/profile.icc", [
    "input_profile" => "/my/input/profile.icc"
]);
```

**Comment by jcupitt** [comment]
Ah OK I see. What's the purpose of the conversion to CMYK and back? To show gamut clipping?

The `"input_profile"` option gives a fallback profile in case the image does not have one embedded in it. Most images should have embedded profiles, but some CMYK images do not, since the profile itself can be very large. You usually have to guess the correct profile from the filename (eg. if they have `euroswop` in there).

**Comment by jcupitt** [comment]
I like this profile as a CMYK fallback:

https://github.com/jcupitt/nip2/blob/master/share/nip2/data/cmyk.icm

It's free and works well for most untagged CMYK images. You probably have something better.

**Comment by johnvoncolln** [comment]
@jcupitt - yes this is the purpose. The uploaded files will eventually printed via CMYK process. Of course web browsers don’t like CMYK images. Does this seem like the best way to do it?

**Comment by jcupitt** [comment]
Sorry for the delay.

Yes, I guess so. It should show gamut clipping anyway.
