### ISSUE TITLE
Find out if an image has an alpha channel, is interlaced etc

### ISSUE THREAD

**Issue by aried3r** [jcupitt/libvips#931]
Hey!

I am currently working on moving all of my imagemagick related code to vips, thanks so much for this project! However I am currently facing a few obstacles which I couldn't answer myself using the docs and issues.  
I'm using ruby-vips, but I think that's unrelated to my issues.

In the following, I used `convert -size 400x400 -interlace PNG canvas:transparent x.png` to generate an interlaced PNG with alpha (so I only have one sample input, but real input could either have alpha, or be interlaced or both).

I am trying to process some PNG files, if they contain an alpha channel, then I want to remove it (`vips flatten`) or if they are interlaced, I want to deinterlace them (`vips pngsave x.png x2.png`, although I get `(vips:63946): VIPS-WARNING **: 17:53:02.027: Interlace handling should be turned on when using png_read_image` which I think is from libpng)

So I would need some way to identify if the inputs have an alpha channel or are interlaced. With ImageMagick I had various ways (both using the JSON output), for example using the CLI:
```Shell
$ magick x.png json: | jq '.[0].image.interlace'
"PNG"
$ magick x.png json: | jq '.[0].image.channelDepth.alpha
1
```
or using the MiniMagick gem:
```Ruby
m = MiniMagick::Image.open('x.png')
m.data["interlace"]
=> "PNG"
m.data["channelDepth"]["alpha"]
=> "1"
```

For this I haven't found a solution in vips yet, using either ruby-vips or vips CLI I only found these outputs:
```
$ vipsheader -a x.png
x.png: 400x400 uchar, 1 band, b-w, pngload
width: 400
height: 400
bands: 1
format: uchar
coding: none
interpretation: b-w
xoffset: 0
yoffset: 0
xres: 2.834
yres: 2.834
filename: x.png
vips-loader: pngload
```

I found [your comment](https://github.com/jcupitt/libvips/issues/150#issuecomment-51814135) which – for alpha – suggest using the following:
```Python
# alpha is stored as an extra band at the end of the image: return the band
# number, or -1 for no alpha
def get_alpha_band(image):
    if image.Bands() == 2:
        # mono image with alpha
        return 1
    if image.Bands() == 4 and image.Type() != VImage.VImage.CMYK:
        # rgb image with alpha
        return 3
    if image.Bands() == 5 and image.Type() == VImage.VImage.CMYK:
        # cmyk image with alpha
        return 4

    return -1
```

But I haven't found anything similar for detecting if an image is interlaced. Maybe you could point me in the right direction on how to get more information about the image out of vips?

**Comment by jcupitt** [comment]
Hi @aried3r,

You're right, there should be a `#has_alpha?` method on `Image`. There's one in the C API, but it's not duplicated in ruby-vips, unfortunately. The C one is here:

https://github.com/jcupitt/libvips/blob/master/libvips/iofuncs/image.c#L2867

I'd suggest something like that. 

For interlaced (progressive) JPG images you can test for `jpeg-multiscan`:

```
$ vipsheader -f jpeg-multiscan progressive.jpg 
1
```

But there's no equivalent for PNG, you're right. Perhaps there should be a field called `interlaced` which is created for images from an interlaced source.

Why do you need to test for interlace, by the way? I hope we don't mean different thing by the term :(

**Comment by aried3r** [comment]
> You're right, there should be a #has_alpha? method on Image. There's one in the C API, but it's not duplicated in ruby-vips, unfortunately.

Thanks, I'll have a look at `ruby-vips`, maybe I can add it. Should be be the same as with other fields, so `.get 'alpha'`?

> For interlaced (progressive) JPG images you can test for jpeg-multiscan:

Ah, I didn't look for multiscan, is that available in the ruby-vips gem? Because I only saw the `fields` API to get metadata.

> But there's no equivalent for PNG, you're right. Perhaps there should be a field called interlaced which is created for images from an interlaced source.

That would be awesome!

> Why do you need to test for interlace, by the way?

Our customers sometimes upload PNGs which we use in a PDF report which we generate using prawn. But prawn is very slow with [images having an alpha channel](https://github.com/prawnpdf/prawn/issues/301#issuecomment-2966946).  
Interlaced PNGs are [even unsupported](https://github.com/prawnpdf/prawn/issues/992#issuecomment-254941918).

Since the report is a white document, removing interlacing and replacing the alpha channel for white is usually the way to go for us. But of course I'd love to leave PNGs that are neither interlaced nor have alpha untouched, which I couldn't do with imagemagick's `magick` command which always recoded the PNG (in my testing at least).  
That's why I'm interested in checking first.

**Comment by jcupitt** [comment]
It'd be great if you could cook up a PR with this in. The C function is:

```C
gboolean vips_image_hasalpha( VipsImage *image );
```

So I think in Ruby it should also be a method on the image object, perhaps `Image#hasalpha?`. You can use ffi to call the C function to do the work. 

`jpeg-multiscan` is an item of metadata set by the jpeg loader if it sees a progressive (interlaced) image, so in Ruby you can test for it with:

```ruby
image.get("jpeg-multiscan") != 0
```

I'll add something similar for PNG.

**Comment by jcupitt** [comment]
OK, look for a metadata item called `interlaced` with the value 1. It should work for PNG and JPG.

**Comment by aried3r** [comment]
Thanks, I guess this will be available in the next release?

> So I think in Ruby it should also be a method on the image object, perhaps Image#hasalpha?. You can use ffi to call the C function to do the work.

I tried this doing:
```Ruby
# image.rb
attach_function :vips_image_hasalpha, [:pointer], :int

def has_alpha?()
  return Vips::Image.vips_image_has_alpha self
end
```
```Ruby
x = Vips::Image.new_from_file './spec/samples/alpha.jpeg'
x.has_alpha?
```
where I get
```
Traceback (most recent call last):
       16: from .rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
       15: from .rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
       14: from .rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
       13: from .rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
       12: from .rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
       11: from .rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
       10: from .rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
        9: from .rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
        8: from .rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
        7: from .rbenv/versions/2.5.1/bin/irb:11:in `<top (required)>'
        6: from (irb):3
        5: from Development/ruby-vips/lib/vips/image.rb:698:in `has_alpha?'
        4: from Development/ruby-vips/lib/vips/image.rb:199:in `method_missing'
        3: from Development/ruby-vips/lib/vips/operation.rb:232:in `call'
        2: from Development/ruby-vips/lib/vips/operation.rb:232:in `new'
        1: from Development/ruby-vips/lib/vips/operation.rb:65:in `initialize'
Vips::Error (VipsOperation: class "vips_image_has_alpha" not found)
```

I have never worked with ruby-ffi before, so I am not sure where to look. I found your comment in https://github.com/jcupitt/ruby-vips/issues/168#issuecomment-376432806 which, if I read that correctly, suggests that I cannot call this method from Ruby. Is that correct?

**Comment by jcupitt** [comment]
Oh well done, you're almost there, try:

```ruby

def has_alpha?()
  return Vips::vips_image_has_alpha self
end
```

**Comment by jcupitt** [comment]
Ooop of course I mean:

```ruby
attach_function :vips_image_hasalpha, [:pointer], :int

def hasalpha?()
  return Vips::vips_image_hasalpha self
end
```

**Comment by aried3r** [comment]
I created a PR in ruby-vips. Thanks for your help!

I have one more question, would it make sense to have a metadata item called `alpha` as well for the CLI? Otherwise the only way remains the C API and the bindings (if they implement it).
