### ISSUE TITLE
c++ sample needs to be updated

### ISSUE THREAD

**Issue by fangqiao** [jcupitt/libvips#932]
hi @jcupitt finally I started with libvips by trying your C++ sample code .

And I found two problems immediately:
1. the code won't compile, as you have duplicated the code below:
```
  VImage in = VImage::new_from_file( argv[1],
    VImage::option()->
      set( "access", VIPS_ACCESS_SEQUENTIAL ) ); 
```
and when I fixed it, and ran it, the write to another file would throw 
```
avg = 142.221
width = 800

(test2:15761): VIPS-WARNING **: error in tile 0 x 0
terminate called after throwing an instance of 'vips::VError'
  what():  vipspng: out of order read at line 1200
vips2png: unable to write "1.png"
```

After I spent some time on your documentation, and also on similar older issues, found out the VIPS_ACCESS_SEQUENTIAL should to be changed to VIPS_ACCESS_RANDOM for it to work. 

Would suggest to fix it so new guys wouldn't lose faith in your excellent library. TBH I almost did.

**Comment by jcupitt** [comment]
Hello @fangqiao, thanks for pointing out this dumbness. You're right, a non-working example is awful.

I've updated it and tested here, would you be able to verify that it works now?

http://jcupitt.github.io/libvips/API/current/using-from-cpp.html

**Comment by fangqiao** [comment]
yes it works now.

**Comment by jcupitt** [comment]
Great! Thanks again for reporting this.
