### ISSUE TITLE
Q: Create PDF from multiple jpegs

### ISSUE THREAD

**Issue by jrochkind** [jcupitt/libvips#935]
Sorry, I spent some time looking through Issues and docs, but couldn't figure this out. 

I have a bunch of JPGs, and I want to convert them into a PDF, with one PDF page for each image. (Just raster images of some kind embedded in PDF). 

Is there any way to get libvips to do this?  With vips command line? With ruby-vips? 

Thanks!

**Comment by jcupitt** [comment]
Sorry, PDF save is not supported directly.

You can save to PDF via imagemagick, for example:

```
$ vips magicksave nip2guide.pdf[n=-1] x.pdf
```

or:

```ruby
image.magicksave "x.pdf"
```

But there's not much control. It'll do multipage documents at least.

**Comment by jrochkind** [comment]
okay, thanks, there are other tools I can use.
