### ISSUE TITLE
Can I do opacity with blending and/or lighting displacement maps with libvips?

### ISSUE THREAD

**Issue by wyatt121** [jcupitt/libvips#937]
Hi John,

I'm working on overlaying designs on apparel.  See attached example:

I'm looking at the blending modes in the docs. Is there a way to adjust the opacity of the overlay SVG to 80% easily? I read about the over and atop settings but did not see an option to adjust the opacity.

In addition, is there support for lighting displacement maps like used in Fred's T-shirt ImageMagick script?  Even if this was an option, I'm assuming it would take too much processing time, and it would not work for my solution... Guess, I'm just curious.
http://www.fmwconcepts.com/imagemagick/tshirt/index.php

Again, thank you for all your help! I'm super pumped to complete this project!

Wyatt

My current code:

`
require DIR . '/vendor/autoload.php';
use Jcupitt\Vips;

$apparel = ('blank-tshirt.jpg');
$design = ('GOSHEN.svg');
$design_width = 275;
$dx = 175;
$dy = 130;

$base = Vips\Image::newFromFile($apparel);
$overlay = Vips\Image::newFromFile($design);

$base_width = $overlay->width;
$scale = $design_width / $base_width;

$overlay = Vips\Image::newFromFile("$design", ["scale" => $scale]);
$overlay = $overlay->embed($dx, $dy, $base->width, $base->height);

$out = $base->composite2($overlay, "over");
$str = $out->writeToBuffer(".jpg");

header("Content-Type: image/jpeg");
echo $str;
exit();

`

![ts-p002-m-gr-d001-lt001-bl](https://user-images.githubusercontent.com/17152395/38632502-cba70d50-3d71-11e8-9621-e76f674508b1.jpg)

**Comment by jcupitt** [comment]
Hi again,

For opacity, just scale the alpha before you call composite. You want to leave RGB alone (multiply by 1), but scale alpha down by 0.8, so you need:

```php
$overlay = $overlay->multiply([1.0, 1.0, 1.0, 0.8]);
```

The argument to multiply can be a single number (multiply every band element by this), an array (multiply each band by the corresponding array element) or an image (multiply corresponding band elements). PHP does not have operator overloads, unfortunately, so the syntax is a bit ugly. 

Complete example:

```php
#!/usr/bin/php 
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

$apparel = 'blank-tshirt.jpg';
$design = 'GOSHEN.svg';

# the space for the design on the shirt as a percentage ... this way, these same
# params will work for any size version of the shirt photo
$shirt_vertical = 0.7;
$shirt_horizontal = 0.5;
$shirt_scale = 0.5;

$base = Vips\Image::newFromFile($apparel);
$overlay = Vips\Image::newFromFile($design);

$target_width = $base->width * $shirt_scale;
$scale = $target_width / $overlay->width;
$dx = ($base->width - $target_width) * $shirt_horizontal;
$dy = ($base->height - $overlay->height * $scale) * $shirt_vertical;

$overlay = Vips\Image::newFromFile($design, ["scale" => $scale]);
$overlay = $overlay->multiply([1.0, 1.0, 1.0, 0.8]);
$overlay = $overlay->embed($dx, $dy, $base->width, $base->height);

$out = $base->composite2($overlay, "over");

# $str = $out->writeToBuffer(".jpg");
# header("Content-Type: image/jpeg");
# echo $str;

$out->writeToFile("x.jpg");
```

**Comment by jcupitt** [comment]
Re. lighting and displacement, sure you can do it, and it should be faster then IM, though I don't know by how much. You'd need to implement it and experiment.

**Comment by wyatt121** [comment]
Hi John,

The opacity result is fantastic!   See attached.

The opacity setting works great to replicate a real-life design in which there is only 1 single pass of ink that bleeds through the cloth.  Not only does it look as if it's blended with the shirt, but the lighting from the shirt also blends through the design.  A+ for realism!

Most t-shirt designs are printed with an initial base layer of white laid down under the color layer resulting in no blending.  Therefore the opacity setting will not achieve a realistic result.  In this case, a lighting map must be created from the base t-shirt graphic and overlayed over the design.  I experimented with ImageMagick and not only was speed a major issue, but I also had mixed results.  Some of the output looked great and realistic.  Some of the output, not so much...  Therefore, I decided I could live without it, and moved forward in my project.  But this was before I discovered your super fast libraries...

If you are willing to guide me with some base code instruction on how to do lighting maps, I'm willing to experiment and publish my results.   Unfortunately, accomplishing this task myself is way outside my knowledge level of graphics/code to accomplish alone. 

Again, Thank you very much for all your help!  You have been extremely awesome!

Wyatt

![ts-p002-m-gr-d001-lt002-bl](https://user-images.githubusercontent.com/17152395/38632371-650fb66e-3d71-11e8-83de-5efe2cfff83b.jpg)

**Comment by jcupitt** [comment]
I'd guess it would be a day or two's work to get it working nicely for all your cases, and I don't really have the time at the moment, sorry. You'll probably need to pay someone to do it. Good luck with your project.

**Comment by wyatt121** [comment]
All is good John.  You have been extremely helpful!  Your libraries are amazing.  If I decide to move forward with the lighting displacement in the future, I will post my results.

Wyatt

**Comment by ttutuncu** [comment]
Hi,

I couldn't find this method in netvips:
$overlay = $overlay->multiply([1.0, 1.0, 1.0, 0.8]);
How can I achieve the same results with netvips?

Thanks

**Comment by jcupitt** [comment]
Hello, you should ask there:

https://github.com/kleisauke/net-vips/issues
