### ISSUE TITLE
Reduced grayscale png file size is larger than original png

### ISSUE THREAD

**Issue by fangqiao** [jcupitt/libvips#938]
I am testing libvips' resize API and found out it's really convenient. Great job.

But I found out when png is grayscale, that exported png file with smaller dimension is acutally larger than the original. When it is colorful, the reduced png size is proportional.

Why is it? Is there anyway to tune the code so png file with smalled dimensions is always smaller in term of file size?

Below is the code I used to resize then crop:

```            
in = in.resize(scale).smartcrop(w, h, VImage::option()->
                                            set( "interesting", VIPS_INTERESTING_ATTENTION));

```
And to export to png:
```
                in.pngsave( (char*) output.c_str(), VImage::option()
                            ->set("compression", 9)
                            ->set("strip", true)
                    );

```

Original png, width: 1024

![nike-logo](https://user-images.githubusercontent.com/17473990/38611591-b3edcfec-3db6-11e8-9cc8-0def3f0bec9a.png)

Resized, width: 900

![nike-logo png resized](https://user-images.githubusercontent.com/17473990/38611620-c8b955a4-3db6-11e8-9797-e5c9642921eb.png)

Thanks

**Comment by lovell** [comment]
This question is asked regularly of sharp - see https://github.com/lovell/sharp/issues/478 (and the linked issues).

**Comment by jcupitt** [comment]
Another factor is the shape of the edge. Your original has very sharp edges and will be easy to compress well -- after lanczo3 they will be smoother and have a bit of ringing. You could try using bilinear instead.

**Comment by jcupitt** [comment]
I see:

```
john@yingna ~/pics $ vips resize nike.png x.png[compression=9] 0.9 --kernel linear
john@yingna ~/pics $ ls -l x.png 
-rw-r--r-- 1 john john 15081 Apr 11 12:45 x.png
john@yingna ~/pics $ vips resize nike.png x.png[compression=9] 0.9 --kernel lanczos3
john@yingna ~/pics $ ls -l x.png 
-rw-r--r-- 1 john john 19446 Apr 11 12:45 x.png
```

**Comment by fangqiao** [comment]
Tried linear
```
in = in.resize(scale, VImage::option()->
                           set("kernel",VIPS_KERNEL_LINEAR) ).
                smartcrop(w, h, VImage::option()->
                          set( "interesting", cropMethod));
```
Output is smaller than the default kernel, I guess it is lanczos3 but still larger than the original.


![nike-logo png linear](https://user-images.githubusercontent.com/17473990/38649894-8b21c12a-3e2b-11e8-9d47-ca0c6cada5d8.png)
