### ISSUE TITLE
vips pdfload generating blank jpeg

### ISSUE THREAD

**Issue by munish-dhiman** [jcupitt/libvips#940]
I am using the following command to extract jpeg image: 

    `vips pdfload --dpi 600 --scale 6 --page 0 pdffile.pdf image.jpg --vips-tile-height=1024`

When I set **scale** value to greater than **2**, then it generate blank jpg image, till 2 it works fine. It only happening to some special set of pdfs. 

Here is a sample pdf https://owncloud.docu.solutions/index.php/s/M1hsKsyCMXnOj5h

**Comment by jcupitt** [comment]
This worked for me with your sample PDF:

```
$ vips pdfload --dpi 600 --scale 5 big.pdf image.jpg
$ vipsheader image.jpg 
image.jpg: 32600x12045 uchar, 3 bands, srgb, jpegload
```

(don't use `--vips-tile-height=1024` on libvips 8.6 or later, it'll slow it down)

And the image looks correct. Scale 6 fails however.

My guess would be that cairo (the rendering system that poppler uses) has a limit of 32768 pixels on an axis.

**Comment by munish-dhiman** [comment]
@jcupitt Thank you so much. It is working fine upto `--scale 5` and on some files upto `--scale 4`, it depends on width/height of loaded image from pdf.  Yes, `cairo has limit of 32768 pixels on an axis`  and definitely the issue is of the limit.
