### ISSUE TITLE
VipsFormat: file *.dzi not a known format

### ISSUE THREAD

**Issue by fordanic** [jcupitt/libvips#941]
Trying to use vips to convert a *.dzi to *.tif using:
``vips.exe` im_vips2tiff D:\image_data_original\temp.dzi D:\image_data_original\temp.tif:none,tile:256x256,pyramid``
But it fails with:
``VipsFormat: file "D:\image_data_original\temp.dzi" not a known format``

Running on windows with the latest full binary download.

Am I missing something or trying to do something that is not supported.

**Comment by jcupitt** [comment]
Hello, libvips can't load dzi images directly, but you can join up the tiles in the bottom layer. There was a recent issue on this: https://github.com/jcupitt/libvips/issues/903

It'll be a little harder on Windows -- you'll need a bit of powershell to transpose the files, and it'll fail if you have more than 2000 tiles in the layer.
