### ISSUE TITLE
Difference between PNG images when upscaling using different versions of vipsthumbnail

### ISSUE THREAD

**Issue by rnanwani** [jcupitt/libvips#943]
I used the following command to resize a PNG image using two versions of vips 8.6.3 and 8.5.6. 

vipsthumbnail -s 800x800 test2.png -o output.png

This is the test2.png image 
https://imgur.com/a/A7Qmb

On upscaling with the newer version of vips, I am getting unwanted pixels on the edges of the image (notice the greyish pixels around the "s" on the left, possibly semi-transparent pixels on a black background). 

![image](https://user-images.githubusercontent.com/4739557/38767269-c21bb420-3ffb-11e8-82b9-c53cb75547d7.png)

This can be replicated with other such images as well. I have observed it while upscaling the image till now, havent' encountered a difference while downscaling.

Any pointers on how does this happen and how this can be corrected?

**Comment by jcupitt** [comment]
From 8.6, libvips uses corner convention for downsizing and centre convention for upsizing. This means you get (in effect) a 0.5 pixel shift down and right for upsized images. 

You can see why this is needed with these examples. Here's a 3x3 pixel sample PNG:

![3x3-zoom](https://user-images.githubusercontent.com/580843/38767726-d9075526-3fde-11e8-94e3-5a261135f312.png)

If I upsize with 8.5 (corner convention) I get:

![3x3-8 5](https://user-images.githubusercontent.com/580843/38767731-eaece990-3fde-11e8-811b-5c1166a36ec3.png)

8.6 switched to centre, so you get:

![3x3-8 6](https://user-images.githubusercontent.com/580843/38767736-fa52f186-3fde-11e8-86ef-f5364b2ea270.png)

Which is pretty similar to what imagemagick makes:

![3x3-im](https://user-images.githubusercontent.com/580843/38767748-37a3ba2a-3fdf-11e8-8b53-e5006772b003.png)

Though they use a lower-quality upsize and seem to miss by a few percent.

**Comment by jcupitt** [comment]
Sorry, I didn't actually answer your question. In my opinion, the 8.6 behaviour is correct and not a bug.

If you want to do something different, you'll need to call `affine` yourself. For example:

```
$ vips affine 3x3.png 3x3-affine.png "20 0 0 20" --interpolate bicubic --extend copy
```

Makes:

![3x3-affine](https://user-images.githubusercontent.com/580843/38767809-53e47304-3fe0-11e8-8c5a-c6fcf71fc6fe.png)

The off-centre 8.5 behaviour.
