### ISSUE TITLE
fatal error: glib-object.h: No such file or directory

### ISSUE THREAD

**Issue by crb912** [jcupitt/libvips#945]
```
/usr/local/include/vips/vips8:35:25: fatal error: glib-object.h: No such file or directory
```

But I have install glib2.0-dev
```
$sudo apt-get install glib2.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libglib2.0-dev' for regex 'glib2.0-dev'
libglib2.0-dev is already the newest version (2.48.2-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
How do I fix the bug?

**Comment by jcupitt** [comment]
Sorry, I don't know, what did you do to produce this error message? I guess you are trying to compile some C++, is that right?

**Comment by jcupitt** [comment]
My guess from what you've said is that you have not set all the compiler flags. To compile C++, use something like:

```
$ g++ -g -Wall try236.cpp `pkg-config vips-cpp --cflags --libs`
```

**Comment by specious** [comment]
In case anyone lands here looking to solve the same situation but is using CMake, it comes with [pkg-config integration](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html#command:pkg_check_modules) which can be used like this in your `CMakeLists.txt`:

```cmake
# Load the `pkg-config` module
find_package(PkgConfig REQUIRED)

pkg_check_modules(vips REQUIRED IMPORTED_TARGET vips-cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE PkgConfig::vips)
```
