### ISSUE TITLE
How to use arithmetic to do arbitary blending correctly? 

### ISSUE THREAD

**Issue by fangqiao** [jcupitt/libvips#946]
I am further testing libvips. I tried to use libvips' arithmetic APIs to caculate pixels of blended image to do blending.

The algorithm is pretty simple:
calcualte the areas for overlay, extract the areas from background and overlay image, caculate blended image pixels, and insert back to backgroun image. 

The code is as below:

```
extractedOverlay = extractedOverlay.bands() == 4 ? extractedOverlay.flatten() : extractedOverlay;
extractedBkg = extractedBkg + ( 1 - alpha ) * extractedOverlay;
in = in.insert(extractedBkg, wx, wy);
```
where alpha is the blend factor for overlay image, 1 is no blend at all. 

First I tested with a png background image and a png overlay image. It worked pretty well. Then I tested it with jpg. The blend area has a background like this:

![huaban1 jpg libvips 0 5](https://user-images.githubusercontent.com/17473990/38856634-92bc012a-4259-11e8-929a-807f5065f40e.jpg)

I tested it with my custom built program with opencv and pixel caculation by loops. The output is :
 
![huaban1 opencv custom 0 5](https://user-images.githubusercontent.com/17473990/38856682-b01e2f0e-4259-11e8-9c19-5684dde2b638.jpg)

which is what I wanted. 

My guess is that when openvips did the pixel calculation for extractedBkg = extractedBkg + ( 1 - alpha ) * extractedOverlay, if the extractedOverlay rgb value is 0,0,0, which is black, it 'intellegiently' calculated a grayscale value for the 'multiply' operation, then used the grayscale value for the 'add' operation. When the background image is png, it didn't do this. Thus a overlay pixel of '0,0,0' to be added on top of the background png image will not have effects, which is the desired operation, while on jpg it will add grayscale.

@jcupitt  correct me if i am wrong.

And please let me know how this could be done correctly for jpg. I really liked your library. This is one major issue I need to address.

**Comment by jcupitt** [comment]
It should work. You need to share a complete program and sample images so I can reproduce any problem.

I had a go at an example:

```python
#!/usr/bin/python

import sys
import pyvips

background = pyvips.Image.new_from_file(sys.argv[1])
if background.bands != 3:
    print "bg not RGB"
    sys.exit()
    
overlay = pyvips.Image.new_from_file(sys.argv[2])
if overlay.bands != 4:
    print "overlay not RGBA"
    sys.exit()

left = (background.width - overlay.width) / 2 
top = (background.height - overlay.height) / 2 
if left < 0 or top < 0:
    print "overlay not smaller than bg"
    sys.exit()

snip = background.crop(left, top, overlay.width, overlay.height)

alpha = overlay.extract_band(3)
rgb = overlay.extract_band(0, n=3)

# scale the alpha to 0 - 1
alpha /= 255

# and make it very transparent 
alpha *= 0.5

mix = (1 - alpha) * snip + alpha * rgb

# mix will be float after that calculation: cast it back to the same format
# as the background for reinsertion
new = background.insert(mix.cast(background.format), left, top)

new.write_to_file(sys.argv[3])
```

With this background image:

![cramps](https://user-images.githubusercontent.com/580843/38859528-1f2ea59c-4226-11e8-8ee0-e8ad36432144.jpg)

And this overlay:

![png_transparency_demonstration_1](https://user-images.githubusercontent.com/580843/38859547-2b9835c8-4226-11e8-9db2-604e1945c0dd.png)

I run like this:

```
$ ./overlay.py cramps.jpg PNG_transparency_demonstration_1.png x.jpg
```

And get this:

![x](https://user-images.githubusercontent.com/580843/38860155-7276bf68-4227-11e8-9fa3-83f7bb80428d.jpg)

Which I think is correct.

Of course, this would be faster using `composite`, but I guess you want to do the pixel calculation yourself.

**Comment by fangqiao** [comment]
@jcupitt  I did some tuning and figured it out how to do it with my approach. 

The trick is to do the alpha caculation on overlay image first, then do alpha channel flatten, then do the blend with background image. The code is as below:

```
extractedOverlay = extractedOverlay.bands() == 4 ? ( ( 1 - alpha ) * extractedOverlay ).flatten() : ( 1 - alpha ) * extractedOverlay;
extractedBkg = extractedBkg + extractedOverlay;
```
This works. Don't know why.

![huaban1 jpg libvips correct](https://user-images.githubusercontent.com/17473990/38861622-987af5b0-4265-11e8-88bc-e0e44f3353a4.jpg)

I'd like to use composite but I didn't figure out how to set a custom blend factor for the overlay image, i.e. how much it should dissolve to the background image with it. Does composite support this setting?

**Comment by jcupitt** [comment]
I think that'll be slower that the simple thing I posted. You don't need to use flatten, I don't think, unless I misunderstood. You are just doing arithmetic on big arrays, it shouldn't do anything intelligently or behind your back. 

You can scale the alpha before you pass the image into composite. For example:

```python
overlay *= [1, 1, 1, 0.5]
```

Will halve the alpha and make it more transparent. 

libvips tries to keep operations simple, but make them easy to compose.

**Comment by fangqiao** [comment]
The fatten is for the overlay png's own alpha. If my understanding to your api is correct, png with alpha channel should be flattened first to make it 3 channels for blending with three channel jpg. 

The varaible alpha here is an extra blend factor, maybe I should use blendFactor as its name.

Would try your approach as well.

**Comment by fangqiao** [comment]
Thanks. Feel free to close it.
