### ISSUE TITLE
Compile from git on archlinux fails due to autogen.sh error

### ISSUE THREAD

**Issue by fangqiao** [jcupitt/libvips#947]
I tried to compile from git the latest version.

Autogen.sh generated following messages:

```
testing for glibtoolize ... using libtoolize
configure.ac:254: installing './compile'
configure.ac:130: installing './config.guess'
configure.ac:130: installing './config.sub'
configure.ac:13: installing './install-sh'
configure.ac:13: installing './missing'
cplusplus/Makefile.am: installing './depcomp'
libvips/Makefile.am:79: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
python/packages/gi/overrides/Makefile.am:2: installing './py-compile'
parallel-tests: installing './test-driver'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
./configure: line 3566: syntax error near unexpected token `1.30.0'
./configure: line 3566: `GOBJECT_INTROSPECTION_CHECK(1.30.0)'
```

**Comment by jcupitt** [comment]
Hello, you probably need gobject-introspection-dev, or whatever arch calls it.

**Comment by fangqiao** [comment]
After I installed this package, autogen.sh worked but make gave such error:

./.libs/libvips.so: undefined reference to `InitializeMagick'

Searched stackoverflow and found this.

[](https://stackoverflow.com/questions/28149392/compile-c-code-using-magick-and-openmpi)

> ImageMagick ships with config utilities. For Magick++ this utility is Magick++-config. See the Usage sub-section under the API docs.
`LDFLAGS=$(Magick++-config --ldflags)
CXXFLAGS=$(Magick++-config --cxxflags)
$(CC) $CXXFLAGS openmpi_project.cc $LDFLAGS -o openmpi_project`

Jump over to the MPI compiling/linking docs, and integrate Magick++'s additional flags to mpiCC

`LDFLAGS=$(Magick++-config --ldflags)
CXXFLAGS=$(Magick++-config --cxxflags)
mpiCC --with-wrapper-cxxflags=$CXXFLAGS openmpi_project.cc \
      --with-wrapper-ldflags=$LDFLAGS -o openmpi_project`

**Comment by jcupitt** [comment]
Hello, this should be fixed in git master libvips.

**Comment by ioquatix** [comment]
I just tried 8.7.0 and had this issue.

```
libtool: link: gcc -g -O2 -o .libs/introspect introspect.o -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -pthread -fopenmp -I/usr/lib/glib-2.0/include -I/usr/include/uuid -I/usr/include/poppler/glib -I/usr/include/poppler -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/orc-0.4 -I/usr/include/libxml2 -I/usr/include/librsvg-2.0 -I/usr/include/libpng16 -I/usr/include/libgsf-1 -I/usr/include/libdrm -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/OpenEXR -I/usr/include/ImageMagick-7 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 -Wl,--export-dynamic -pthread -pthread  -lgirepository-1.0 ./.libs/libvips.so -lMagickCore-7.Q16HDRI -lpng16 -lz -ltiff -ljpeg -lgmodule-2.0 -lexpat -lpangoft2-1.0 -lpango-1.0 -lfribidi -lfontconfig -lfreetype -lgsf-1 -lxml2 -lfftw3 -lorc-0.4 -llcms2 -lgif -lrsvg-2 -lgio-2.0 -lgdk_pixbuf-2.0 -lpoppler-glib -lgobject-2.0 -lglib-2.0 -lcairo -lIlmImf -lImath -lHalf -lIex -lIexMath -lIlmThread -lwebpmux -lwebp -lexif -lm -fopenmp -pthread -Wl,-rpath -Wl,/home/samuel/.rvm/gems/ruby-2.5.0/gems/vips-8.7.0/lib
./.libs/libvips.so: undefined reference to `InitializeMagick'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:740: introspect] Error 1
make[2]: Leaving directory '/home/samuel/.rvm/gems/ruby-2.5.0/gems/vips-8.7.0/ext/vips-8.7.0/libvips'
make[1]: *** [Makefile:857: install-recursive] Error 1
make[1]: Leaving directory '/home/samuel/.rvm/gems/ruby-2.5.0/gems/vips-8.7.0/ext/vips-8.7.0/libvips'
make: *** [Makefile:638: install-recursive] Error 1
```

**Comment by ioquatix** [comment]
I didn't have this issue with 8.6.3 for some reason.. well I am trying it again now.

**Comment by jcupitt** [comment]
Hello @ioquatix, what IM version are you using? I tried with 6.9 and 7.0 and both worked for me. I guess you used git master libvips?

**Comment by ioquatix** [comment]
```
% MagickCore-config --version
7.0.7 Q16 HDRI
```

Just the version tagged `v8.7.0`

**Comment by jcupitt** [comment]
Ah, sorry, that tag is confusing, that was an experimental alpha from a while ago. 

The code that will be 8.7.0 (when it's done) is the head of git master.

**Comment by ioquatix** [comment]
Okay that’s super confusing :( can you please rm the tag and the next release can be 8.8.0 ?

**Comment by jcupitt** [comment]
I renamed the tag to `v8.7.0-alpha1`.

 I don't think we can easily change the version number -- downstream packages are already preparing for 8.7.

**Comment by jcupitt** [comment]
Yes, sorry, I should have used the `-alpha` suffix. I think the tag was made by github when I did this test version:

https://github.com/jcupitt/libvips/releases/tag/untagged-8aad4b4a5b6e9d0552b7

**Comment by ioquatix** [comment]
Yes, I believe I saw that release and that's why I thought 8.7.0 was out.
