### ISSUE TITLE
Rotation center for similarity transform ?

### ISSUE THREAD

**Issue by s-sajid-ali** [jcupitt/libvips#948]
(Not an issue with the package itself but more of question to it's usage.)

What's the convention for the center of the rotation ?

Is there an equivalent of the ['center'](http://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.rotate) argument for skimage.transform.rotate?
(The skimage implements the rotate as a sum of three similarity transforms[[1](https://github.com/scikit-image/scikit-image/blob/master/skimage/transform/_warps.py#L285)] but I was not able to get the same behavior by applying three similarity transforms using vips.) 

Also, is there an option to preserve the shape of the image assuming that the user has taken care of the zero padding to ensure that there is no overflow ?

**Comment by jcupitt** [comment]
Hello, the page for affine tries to document this:

http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-affine

So rotation is around (0, 0) (the top left corner), but the output area is the bounding box of the transformed corners, so the origin moves. You can use xoffset / yoffset in the output image to find the position of the old origin. 

If you set the output area yourself, the transform should be clearer.

**Comment by jcupitt** [comment]
(argh accidental close, stupid touchpad)

**Comment by s-sajid-ali** [comment]
Got it, I think what I was looking for was : 
```
rows, cols = a.shape[0], a.shape[1]
c_ = np.array((cols, rows)) / 2
angle_rad = angle_*(np.pi/180)
tc = np.cos(angle_rad)
ts = np.sin(angle_rad)
im = im.affine([tc, ts, -ts, tc],idx=-c_[0],idy=-c_[1],odx=c_[0],ody=c_[1],oarea=[0, 0, im.width, im.height])
```
where a is a numpy array which was converted to im using the new_from_memory method.

Don't know why the order of shift is reversed from skimage.transform.rotate, but the vips version is much faster and uses a similar amount of memory as the skimage method.  Another thing I've noticed is that the amount of time taken for the transform is always on the order of microseconds irrespective of whether the side length of the 2D array is 500 or 25000.
