### ISSUE TITLE
Tiles images quality

### ISSUE THREAD

**Issue by mercelsantos** [jcupitt/libvips#949]
Hi all,

I've installed and tried libvips to make google-maps tiles. It is awesome because it is super faster than imageMagick. However, the tiles quality generated by libvips is lower than imageMagick. Do you have any idea how to improve the tiles quality generated by libvips? I've used the following command to generate my tiles:

vips dzsave largeFile.png ./ --layout google --suffix .jpg[Q=100]

**Comment by jcupitt** [comment]
Hello!

Could you explain what you mean by lower quality? Post an example of a tile from IM, a tile from dzsave, say how they were made, and say what diferences you don't like.

**Comment by mercelsantos** [comment]
Hello jcupitt,

I  hope you're doing well.
Thank you for the fast replay.

So, in the below links you can see tiles generated by ImageMagick and dzsave in this sequence. The contrast of the image in the first link (generated by the ImageMagick) is better than that generated in dzsave. The black lines in the ImageMagick tile are clearer than those created by the dzsave.

is there a way to improve the image quality generated by dzsave ?

best regards.

https://www.dropbox.com/s/5p3wmcmqusb2yrl/map_25_16.png?dl=0

https://www.dropbox.com/s/9ab3sqwlzd9z6v7/25.jpg?dl=0
