### ISSUE TITLE
Is input data constant

### ISSUE THREAD

**Issue by elbaro** [jcupitt/libvips#951]
Many vips C functions have func(in, out, options..) interface.
They usually miss 'const' keyword for input data.
Can I assume they are actually constant, or they are internally mutated?

```
int
vips_thumbnail_buffer (void *buf, // is buf constant?
                       size_t len,
                       VipsImage **out,
                       int width,
                       ...);

int
vips_thumbnail_image (VipsImage *in, // is in constant?
                      VipsImage **out,
                      int width,
                      ...);
```

**Comment by jcupitt** [comment]
Oh, interesting.

I've done quite a few language bindings now and I think this is the best approach:

- Bind just the libvips core: GValue, GObject, VipsImage and VipsOperation.
- On top of those classes, implement a general `call` function. For example, `output_image = Vips::call("thumbnail_image", input_image, 200, option_array);`. libvips has quite a bit of introspection machinery and it's not difficult to find out the number, types and options for all operations and their arguments. 
- Link that `call` method to the `Image` class in your binding. Languages like Python and Ruby have hooks so you can make `result = image.thumbnail_image(200)` call the `Vips::call` function internally. I guess Rust won't allow that kind of craziness, but you could perhaps still allow something like `image.call("thumbnail_image", 200);`.
- Add a layer over that in Rust to make an nice API: operator overloads, convenience functions etc.
- You can write a tiny bit of Python or whatever to auto-generate most of your API documentation.

I guess the C++ binding would be closest to Rust, though you should be able to make something better than that. The Python binding works this way too: it uses FFI to wrap the bottom chunk of libvips, then everything else is just written in pure Python. It's less than 1000 lines of code to wrap the whole of libvips, including operator overloads, convenience methods, expansions, etc. etc.

C functions like `vips_thumbnail_image()` are actually implemented this way too -- they also introspect at runtime. However, the C binding makes heavy use of varargs and it's just terrible to try to use from another language. You'd be much better off targeting the layer below.

The best thing about doing the binding at runtime via introspection is that it self-updates. When libvips 8.7 comes out, you shouldn't need to do any maintenance: all the new features will just appear.

**Comment by elbaro** [comment]
Thank you for the through answer. I didn't know about the introspect system.

The low level binding generation from the header was quick, thanks to already existing generators:
https://elbaro.github.io/vips-sys/vips_sys/

Now for high-level APIs, I have a question about ownership:
Consider `vips_image_new_from_memory(&my_data)`.
From docs,

> VIPS has a set of mechanisms to copy image areas by just adjusting pointers

is it possible that `my_data` is shared between multiple VipsImages after operations?
When can I free my_data?
```
img1 = vips_image_new_from_memory(&my_data) // 1024x1024
img2 = draw_small_rect(img1, blue, [0,0,3,3]) // 3x3 rect. not copying 1024x1024
// img1 is destroyed, but img2 is alive and references some part of my_data
// Is it safe to free &my_data here?
```

**Comment by jcupitt** [comment]
Hello again, 

That's right, `new_from_memory` will not copy the memory area, so you must only free it when libvips is finished with it. 

A simple way is to attach a postclose callback to the image:

http://jcupitt.github.io/libvips/API/current/VipsObject.html#VipsObject-postclose

This is guaranteed to fire once during object finalization, so it's a good place to free things. You use `g_signal_connect()` to attach a callback:

https://developer.gnome.org/gobject/stable/gobject-Signals.html#g-signal-connect

**Comment by elbaro** [comment]
I am not sure If I understood the mechanism.

In the scenario above, [1024x1024] data is given to img1. Some cheap operation like drawing a [3x3] rectangle is performed to create img2, and img2 only allocates small amount of memory and most of [1024x1024] are shared with img1. (This is what I expect from what docs said) Otherwise img2 needs to copy the entire 1024x1024. Now if img1 is going to be destroyed (closed) while img2 is alive. If the data is freed in img1's postclose callback, the data img2 has will point to invalid memory.

What am I missing here? Does img1 make a copy of given data, instead of keeping a pointer? Does img2 make a copy of 1024x1024 from img1 (which is expensive)?

**Comment by jcupitt** [comment]
libvips keeps references between images while they need each other's resources, so img1 will only be finalized when img2 no longer needs it.

**Comment by elbaro** [comment]
I see. Designing a RAII interface seems trickier than I thought.  I will do more research.

**Comment by jcupitt** [comment]
It should be easy, I hope. It's like any reference-counted library, so in your constructor you are given a ref to hold by libvips, and in your destuctor you g_obejct_unref() it. In copy, you make a new ref.

The C++ binding does all that in the `VObject` class:

https://github.com/jcupitt/libvips/blob/master/cplusplus/include/vips/VImage8.h#L57

I think you just need to copy-paste that into rust as your base class for all libvips objects.

**Comment by elbaro** [comment]
Thanks for the pointer. I saw that code too, but the problem is specific to Rust.
(I didn't want to bother you with Rust specific problems)

If it was C++, I would write
```cpp
void f() {
    auto pixels = new uint8_t[100];
    auto img = vips_image_new_from_memory(&pixels);
    /* do something */
    img.finalization_listener.add_callback( /* free pixels */ );
    // we return here. &pixels is alive somewhere, but callback will take care of it later
}
```

In Rust, when I get the pointer to pixels, it should be clear that pixel data outlives the pointer.
```rust
fn f() {
    let pixels:Vec<u8> = vec![0,255,255,0,255]; // allocate on heap
    let img:Image = vips_image_new_from_memory(&pixels); // &pixels means borrowing
    // As we return, (1) the local variable img is destroyed,
    // (2) g_obejct_unref() is called in destructor.
    // (3) pixel Vector is destroyed. (4) heap memory is freed. 

    // However, somewhere inside libvips the reference to &pixels is held.
    // This is a violation of Rust's safe borrow system.
}
```
Even when I hold pixel data outside of f, 
```rust
fn f(&pixels) {
    let img:Image = vips_image_new_from_memory(pixels);
}

fn main() {
    let pixels:Vec<u8> = vec![0,255,255,0,255];
    f(&pixels);
    // now pixel data is destroyed.
    // There is no guarantee that libvips has no reference to the data at this point.
    // The Rust compiler gives an error. (this is not safe)
}
```
I have a few ideas that need to develop, for example, having `VipsInstance` (which does `vips_init` and `vips_shutdown` with RAII) own the buffer and manage callbacks.

**Comment by jcupitt** [comment]
Ah OK, you're well ahead of me. I should read some more about Rust's memory model. Isn't there an equivalent of the copy constructor to pass lifetime on to a new object? I'm obviously missing something.

Good luck!
