### ISSUE TITLE
Check page count of a multi-page TIFF

### ISSUE THREAD

**Issue by woolite64** [jcupitt/libvips#953]
I'm looking for a way to check page counts on multi-page TIFF's using sharp+libvips in Node.js. The bit of code that I'm looking to expose is [here](https://github.com/jcupitt/libvips/blob/5176b4a17ec9ca5151f1b8b503b2f237f3c83b27/libvips/foreign/tiff2vips.c#L495-L512).

Is there a libvips-compatible way to return this value? The function is only called during a "full read" in [rtiff_header_read_all](https://github.com/jcupitt/libvips/blob/5176b4a17ec9ca5151f1b8b503b2f237f3c83b27/libvips/foreign/tiff2vips.c#L2168-L2171), which enforces other restrictions on header contents.

I'm open to submitting a PR, but not sure where to start. Any guidance here would be appreciated.

**Comment by jcupitt** [comment]
Hello @woolite64,

You'd need new API to expose that directly, and there isn't an obvious libvipsy way. Are you sure a full header read is out of the question? Can you give an example of an image you'd like to be able to read but can't? Perhaps we could just extend the tiff reader to cover another tiff feature.

Another solution would be to reimplement that loop in sharp -- it should be simple.

**Comment by jcupitt** [comment]
Ah I see, yes, I'd forgotten that n-pages was only read for "toilet-roll" images. 

I've added a new metadata item called `n-pages` for tiff, magick and pdf load which reports the number of pages in the original file. Would you be able to test it?

**Comment by jcupitt** [comment]
OK, closing. It'll be in 8.7 anyway.
