### ISSUE TITLE
Exposing h_samp_factor and v_samp_factor in read_jpeg_header

### ISSUE THREAD

**Issue by rnanwani** [jcupitt/libvips#954]
Continuing the discussion [here](https://github.com/lovell/sharp/issues/1186#issuecomment-380395281), to determine the subsampling used in a JPEG image, would exposing the above two factors help. If yes, then can we add this as an enhancement to libvips?

**Comment by rnanwani** [comment]
![test_444](https://user-images.githubusercontent.com/4739557/39302539-9c7d7c66-4970-11e8-8126-a7a58e1fa040.jpeg)
![test_420](https://user-images.githubusercontent.com/4739557/39302540-9cbd88ce-4970-11e8-9cc0-2b660357d1e5.jpeg)


Tested with the above two images, the first has subsampling 4:4:4 the second 4:2:0. Verified against `identify` command which reports `1x1,1x1,1x1` and `2x2,1x1,1x1` in these cases.

**Comment by jcupitt** [comment]
Great! I'll close.
