### ISSUE TITLE
supports NanoZoomer S360?? tif image shows all black image

### ISSUE THREAD

**Issue by yusuke0324** [jcupitt/libvips#955]
Hi, I've successfully dealt with WSI which are taken several whole slide scanners, leica and hamamatsu using python Vips package but I just noticed my code bellow didn't with NanoZoomer S360.
The tif file show a whole back image, even though this codes work well with other old NanoZoomer.

Is there anyone who had same problem and know the solution?

~~~
import gi
gi.require_version('Vips', '8.0')
from gi.repository import Vips

wsi_path = '/home/wsi_data/data.ndpi'
im = Vips.Image.new_from_file(wsi_path, access=Vips.Access.RANDOM)
im = im.similarity(scale = 0.01)
im.write_to_file("./test.tif")
~~~

The 'test.tif' shows black image.

**Comment by jcupitt** [comment]
Hello @yusuke0324,

It should work with ndpi images. Can you upload the image that fails somewhere? It might be an openslide problem. 

I would write your code as:

```python
import pyvips


wsi_path = '/home/wsi_data/data.ndpi'
im = pyvips.Image.new_from_file(wsi_path)
im = im.resize(0.01)
im.write_to_file("./test.tif")
```

`pyvips` is the new libvips binding for Python, it's quite a bit better than the old `Vips` one. Install with

```
$ pip install pyvips
```

Documentation here:

https://github.com/jcupitt/pyvips/

Don't use `similarity` for large size changes -- you will see bad aliasing artifacts. `resize` should give much better results.

**Comment by yusuke0324** [comment]
Hi, @jcupitt 

Thanks for the codes. Looks it doesn't work as well.
I'm going to upload the file and share it with you later. Let me inform you after uploading.

Thanks

**Comment by jcupitt** [comment]
There are some ndpi issues with openslide:

https://github.com/openslide/openslide/issues?utf8=%E2%9C%93&q=is%3Aissue+ndpi

I would check that list as well.

**Comment by jcupitt** [comment]
Please reopen if this is not resolved.
