### ISSUE TITLE
vips rotate throwing error no space left on device

### ISSUE THREAD

**Issue by munish-dhiman** [jcupitt/libvips#958]
I am using a Virtual Machine that has 3002 MB Ram and 512MB temp storage.The AWS Lambda Machine. I am using temp storage to store original and rotated files.
The command I running to rotate images is
`vips rot original.jpg rotated.jpg d90`

It throwing the following error

> Exit Code: 1, Error Output: ERROR: wbuffer_write: write failed unix error: No space left on device

image is here https://owncloud.docu.solutions/index.php/s/sY99fLYwGRpJf1n

**Comment by jcupitt** [comment]
Answered here:

https://stackoverflow.com/questions/50098215/libvips-rotate-is-throwing-no-space-left-on-device
