### ISSUE TITLE
Use Vips under a Visual studio project

### ISSUE THREAD

**Issue by abenchaaben** [jcupitt/libvips#961]
Hi, 

I want to use VIPS in my Visual studio C++ project. I downloaded the Windows development zip and i linked the the lib as explained in this subject 
https://github.com/jcupitt/libvips/issues/683
But I'm getting the following error when starting my application, **"The procedure
entry point cairo_ft_font_face_create_for_pattern could not be located in
the dynamic link library libcairo-2.dll"**. I dont know what this does mean.

 Any Help please§

**Comment by abenchaaben** [comment]
Hi, 
Yes i used the 8..6.3 version. I have the same error with the libpoppler.lib too. Do you advise me to use a previous version for the moment?

thank's in advance.

**Comment by jcupitt** [comment]
I checked and the vips-all binaries in 8.6.3 are built with:

```
        -lMagickCore-6.Q16 -lpng16 -ltiff -ljpeg -lgmodule-2.0 -lexpat 
        -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lgsf-1 
        -lxml2 -lfftw3 -llcms2 -lgif -lrsvg-2 -lgdk_pixbuf-2.0 
        -lpoppler-glib -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lcairo 
        -lopenslide -lwebpmux -lwebp -lmatio -lz -lexif
```

**Comment by abenchaaben** [comment]
Thank's. It worked when i copied all the dll to my application folder.

**Comment by abenchaaben** [comment]
Sorry for asking again. But my application crash when i called vips_openslideload:
VipsImage** out;
vips_openslideload("test.ndpi",out,0);

Did i pass the right argument to the function?

Thank's a lot.

**Comment by jcupitt** [comment]
To read and save level 2, try:

```C
VipsImage *out;

if (vips_openslideload("test.ndpi", &out, "level", 2, NULL) ||
    vips_image_write_to_file("level.png", NULL)) {
    printf("error: %s\n", vips_error_buffer());
    exit(1);
}
g_object_unref(out);
```

There's a chapter in the docs introducing the API:

http://jcupitt.github.io/libvips/API/current/using-from-c.html

**Comment by abenchaaben** [comment]
Thank's a lot. That work. If i undersyand, for evry optional argument, i have to put the tag before : like for level i have to put "level" before the value?

**Comment by jcupitt** [comment]
That's right. All operations take a set of NULL-terminated name/value pairs. In Python (for example) the syntax is:

```python
image = pyvips.Image.openslideload(filename, level=2)
```

or Ruby:

```ruby
image = Vips::Image.openslideload filename, level: 2
```

or PHP:

```php
image = Vips\Image::openslideload(filename, ["level" => 2]);
```

etc. etc.
