### ISSUE TITLE
vips resize produces nonsense values on multichannel float or double images containing negative values

### ISSUE THREAD

**Issue by erdmann** [jcupitt/libvips#962]
`vips resize` is producing dramatically wrong values when it operates on multiband images in float or double format, but, as far as I can tell, the problem only arises when the source image contains negative values.

The following demonstrates the problem for me:

```
$ vips --version
vips-8.7.0-Sun Jan 28 17:23:05 UTC 2018
$ vips xyz xyz.v 3 3 # make a 2-band image with values from 0 to 2
$ vips linear -- xyz.v neg_multi.v 1.3487539487593485 -1.238473261033847095 # has neg. values
$ vips min neg_multi.v
-1.238473
$ vips max neg_multi.v
1.459035
$ vips resize neg_multi.v big_neg_multi.v 1000 --kernel linear 
$ vips min big_neg_multi.v # I'm expecting something close to -1.238
-121.671860
$ vips max big_neg_multi.v # expecting something close to 1.459.  Off by a factor of ~100
143.341965
$ vips resize neg_multi.v bigger_neg_multi.v 2000 --kernel linear
$ vips min bigger_neg_multi.v # The problem grows worse.  A clue?
-351.210815
$ vips max bigger_neg_multi.v # Worse.  A factor of 3
413.766998
$ vips linear -- xyz.v neg_multi_2.v 2 -1
$ vips min neg_multi_2.v
-1.000000
$ vips max neg_multi_2.v
3.000000
$ vips resize neg_multi.v big_neg_multi_2.v 1000 --kernel linear
$ vips max big_neg_multi_2.v # rather unexpected
1610612736.000000
$ vips min big_neg_multi_2.v # not entirely satisfactory
-2251799813685248.000000
```
If we transform the original 2-band image to make it contain only non-negative values, things get better:
```
$ vips linear neg_multi.v pos_multi.v 1 10
$ vips min pos_multi.v 
8.761527
$ vips max pos_multi.v 
11.459035
$ vips resize pos_multi.v big_pos_multi.v 1000 --kernel linear
$ vips min big_pos_multi.v 
8.761524
$ vips max big_pos_multi.v 
11.459039
```

Also, note that the problem seems to go away when operating on single-channel images:
```
$ vips extract_band neg_multi.v neg_single.v 0
$ vips resize neg_single.v big_neg_single.v 1000 --kernel linear
$ vips min big_neg_single.v 
-1.238474
$ vips max big_neg_single.v
1.459035
```

Note also that `nearest` works fine but that `linear`, `cubic`, `lanczos2`, and `lanczos3` all seem to have the problem:

```
$ vips resize neg_multi.v big_neg_multi_2.v 1000 --kernel nearest
$ vips min big_neg_multi_2.v 
-1.238473
$ vips max big_neg_multi_2.v 
1.459035
$ vips resize neg_multi.v big_neg_multi_2.v 1000 --kernel cubic
$ vips min big_neg_multi_2.v 
-72.325836
$ vips max big_neg_multi_2.v 
84.245094
$ vips resize neg_multi.v big_neg_multi_2.v 1000 --kernel lanczos2
$ vips min big_neg_multi_2.v 
-72.325836
$ vips max big_neg_multi_2.v
84.245094
$ vips resize neg_multi.v big_neg_multi_2.v 1000 --kernel lanczos3
$ vips min big_neg_multi_2.v 
-72.325836
$ vips max big_neg_multi_2.v
84.245094
```

As a side note (possibly another bug?), it appears that `cubic`, `lanczos2`, and `lanczos3` all map to the same kernel.

Many thanks in advance.

**Comment by erdmann** [comment]
I'm running from git tag 8.7.0.  I ran the build tests I could find and got the following passing results (irrelevant parts removed):
```
libvips-8.7.0$ make check
...
PASS: test_cli.sh
PASS: test_formats.sh
PASS: test_seq.sh
PASS: test_threading.sh
============================================================================
Testsuite summary for vips 8.7.0
============================================================================
# TOTAL: 4
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
...
```

**Comment by jcupitt** [comment]
Hello Rob, that sounds bad, I'll have a look. Thanks for the report!

The main test suite is written in Python and is part of pyvips. I guess it's not testing resize with negative float values.

https://github.com/jcupitt/pyvips/tree/master/tests

**Comment by jcupitt** [comment]
It looks like this was a problem in an older 8.7 caused by alpha premultiplication. 

The problem was that `xyz` was tagging images as `b-w` (ie. monochrome), although they had two bands. When `resize` saw the image, it assumed it was GA (ie. grey plus alpha) and premultiplied the image before resize so as to keep transparent edges correct.

For a few weeks now, 8.7 has tagged images produced by things like `xyz` as `multiband` instead. This is a generic multiband image type with no alpha, so resize in git master 8.7 should work as you'd expect.

I tried your example in git master 8.7:

```
john@kiwi:~/pics$ vips xyz xyz.v 3 3
john@kiwi:~/pics$ vips linear -- xyz.v neg_multi.v 1.3487539487593485 -1.238473261033847095
john@kiwi:~/pics$ vips min neg_multi.v
-1.238473
john@kiwi:~/pics$ vips max neg_multi.v
1.459035
john@kiwi:~/pics$ vips resize neg_multi.v big_neg_multi.v 1000 --kernel linear
john@kiwi:~/pics$ vips min big_neg_multi.v
-1.238474
john@kiwi:~/pics$ vips max big_neg_multi.v
1.459035
john@kiwi:~/pics$ vipsheader xyz.v 
xyz.v: 3x3 uint, 2 bands, multiband
```

Could you try building git master?

**Comment by erdmann** [comment]
Many thanks, John!  It works for me now.  Is it generally true that I should worry about how an image is tagged in terms of how it's processed by `vips`?

I can now verify that `cubic`, `lanczos2`, and `lanczos3` map to the same kernel in git master 8.7.  I'll file a new bug with some evidence shortly.

**Comment by jcupitt** [comment]
libvips used to just use the tag as a hint for display programs, but you're right, it does indeed control some aspects of processing now. It's a good and a bad thing :(
