### ISSUE TITLE
Add mitchell kernel

### ISSUE THREAD

**Issue by Daiz** [jcupitt/libvips#966]
Hi, as someone who uses ImageMagick currently for a lot of image processing needs, I would be interested in improving the performance of it all and I've been looking into using VIPS as a potential option. However, there's one major stopper for me right now, which boils down to the fact that I really, really want to use [Mitchell-Netravali Cubic Filter](http://www.imagemagick.org/Usage/filter/#mitchell) for my scaling needs, as the material I deal with is very sensitive to scaling (basically I'm downscaling pure black & white comics that use lots of [screentones](https://en.wikipedia.org/wiki/Screentone), and selecting an unsuitable filter for this use case can produce a lot of very nasty moire - Lanczos for example does not do a good job here).

So the question is, what exactly is the "Cubic" resize kernel that VIPS uses? And if it's not Mitchell-Netravali, would it be possible to have that as an option?

**Comment by jcupitt** [comment]
Hello, it's straight Catmull-Rom. I'll have a look at Mitchell.

**Comment by jcupitt** [comment]
I added Mitchell to git master, it should be in 8.7, when it finally comes out. Thanks for the suggestion!

**Comment by Daiz** [comment]
Thank you! I look forward to trying it out down the line.
