### ISSUE TITLE
Calculate pixel

### ISSUE THREAD

**Issue by audreylim** [jcupitt/libvips#967]
Hi, what is the best way to calculate the brightness of an image with this formula:

brightness  =  sqrt( .299*R^2 + .587*G^2 + .114*B^2 )

http://alienryderflex.com/hsp.html

**Comment by jcupitt** [comment]
Hello, in Python you can just write:

```python
r, g, b = image.bandsplit()
grey = (.299 * r ** 2 + .587 * g ** 2 + .114 * b ** 2) ** 0.5
```

But I don't think that's a very good idea. I think his HSP is roughly equivalent to gamma-correct greyscaling, which libvips does already, so I would simply use:

```python
grey = image.colourspace("b-w")
```

**Comment by audreylim** [comment]
Cool, I think I can work with these APIs. Thanks for your quick response, and great work!
