### ISSUE TITLE
Slow Performance when rotating after pdfload.

### ISSUE THREAD

**Issue by codecitizen** [jcupitt/libvips#972]
I'm trying to load a PDF file (large vectorized PDF with scale 6), rotate it and then generate a image pyramid from it.

In the c the code basically looks like:

```c
VipsImage* in;
// load PDF
vips_pdfload(argv[1], &in, "scale", 6.0, "memory", TRUE, NULL);
// rotate
VipsImage* rotated;
vips_rot90(in, &rotated, NULL);
// Generate image pyramid
vips_dzsave( rotated, argv[2], "layout", VIPS_FOREIGN_DZ_LAYOUT_GOOGLE, "tile_size", 256, "container", VIPS_FOREIGN_DZ_CONTAINER_ZIP, NULL );

// Cleanup and complete ...
``` 

Running this code with angle `d0` or `d180` no issues, but `d90` (calling `vips_rot90` directly in example code) takes very long.

Interestingly when I write the `in` image to the disk (after PDF conversion) and then load it again via `vips_jpegload` I experience an enormous performance gain.

Am I doing something wrong here, or missing some options in `vips_rot`? I'm basically calling `vips_rot(in, &rotated, angle, NULL)`.

Thanks in advance for your help and answers!
codecitzein

**Comment by jcupitt** [comment]
Hello @codecitizen,

I had a look inside and the `memory=True` option does nothing if the image loader supports random access (as the PDF loader does). I guess it ought to copy even random access images to memory. 

How large is the PDF you are rendering? Can you fit the whole thing in memory?

**Comment by jcupitt** [comment]
Sorry I should have said, do you know the size in pixels? You may not have enough memory for a complete memory copy.

Because of the rot90, the PDF loader has to render the whole page for every output strip (128 lines). If it's 12,800 pixels high, that's 100 renders :-(

**Comment by jcupitt** [comment]
I made the `memory` option always force a memory load, it's probably clearer behaviour. Your program should run fast now, though it will need bucketloads of RAM (obviously), perhaps more than the 3GB you have on AWS.

To keep memory down, you'd need to load to a disc tempfile, but you may not have that much disc space :(

**Comment by codecitizen** [comment]
Most of our PDFs are very close to the limit poppler/cairo imposes, which is around `32767` x `32767`. 
Since AWS Lambda is limited with 3GB, it's porbably wise to stick to the solution with having a temporary file between PDF conversion and rotation.

**Comment by codecitizen** [comment]
Disk Space could also be an issue on AWS Lambda, but I'll figure that out by testing. We're already doing the rotation there via CLI and never ran into these problems yet. Otherwise my only remaining option seems to be to rotate the PDF before.

To use the vips format, I'm just need to use the `.v` extension, right? [1]

[1] https://jcupitt.github.io/libvips/API/current/file-format.html

**Comment by jcupitt** [comment]
That's it. Something like:

```C
VipsImage *temp = vips_image_new_temp_file(".v");
VipsImage *pdf;
vips_pdfload("something.pdf", &pdf, NULL);
vips_image_write(pdf, temp);

// now use temp as the input to rot90
```

The temp file will be allocated in `TMPDIR`, so usually `/tmp`, and auto-deleted for you.

**Comment by codecitizen** [comment]
Okay,

`vips_image_new_temp_file` is really handy, thanks!

The performance hit, when not rotating at all, but still writing to disk, is not that hard. We tested and everything works within lambda limits. 

Thanks!

**Comment by jcupitt** [comment]
Good, glad it's working!

I'd only go via disc if you have to rotate, but up to you, of course.
