### ISSUE TITLE
photoshop metadata is preserved but not updated

### ISSUE THREAD

**Issue by jindili** [jcupitt/libvips#974]
pyvips snippets
``` python
img = pyvips.Image.new_from_file("ps_72dpi.tif")
output = img.copy(xres=8.66141, yres=8.66141)
output.write_to_file("output_220dpi.tif")
```

The output image should be 220dpi but remains 72dpi in Photoshop, 
This troubles me for some while,  now got it, vips just copy the Photoshop metadata including resolution info from the input file to output file without update it to the new value set by copy()

So now my workaround is use ExifTool to batch remove all EXIF tags from my input image before processing using vips.

**Comment by jcupitt** [comment]
Yes, libvips can't process the photoshop data, it just copies it. 

You could just remove the `"photoshop-data"` tag, you don't need to remove all metadata.
