### ISSUE TITLE
Windows CLI Composite Blend Mode

### ISSUE THREAD

**Issue by sleman** [jcupitt/libvips#977]
`vips-dev-8.6\bin>vips.exe composite "1.jpg 2.png" out.jpg multiply`

`vipstype: unable to convert "multiply" to int`
`composite: must be 1 or 1 blend modes`

I tried `VIPS_BLEND_MODE_MULTIPLY` as well but I get:
`composite: too many arguments`

**Comment by sleman** [comment]
I was able to get `composite2` to work, I think it's the way I'm putting in the array as an argument.

**Comment by jcupitt** [comment]
Hello, unfortunately `composite` takes an array of int for the set of blending modes, not an enum, so you have to use the int form. 

For example:

```
vips composite "k2.jpg Opera-icon-high-res.png" x.png 2
```

Will put the PNG on top of the JPG. The two input image files also need to be a single argument, hence the quotes.

`composite2` is much easier to use, as you found!
