### ISSUE TITLE
support for standard streams

### ISSUE THREAD

**Issue by dineshkannaa** [jcupitt/libvips#979]
does libvips permits image data to be read and written from the standard streams via command  ? if so how to do it?

**Comment by jcupitt** [comment]
You can write to `/dev/stdout`, for example:

```
vips jpegsave x.tif /dev/stdout > x.jpg
```

But that's it, sadly. There are some issues discussing this, for example:

https://github.com/jcupitt/libvips/issues/803

https://github.com/jcupitt/libvips/issues/921

https://github.com/lovell/sharp/issues/30

**Comment by jcupitt** [comment]
This is now being added in https://github.com/libvips/libvips/pull/1443

**Comment by dineshkannaa** [comment]
Hi John,
 Can I use both input and output streams at the same time . 
 For eg.,
>  vips rot stdin .jpg d90

**Comment by jcupitt** [comment]
Sure, eg.

**Comment by jcupitt** [comment]
(of 90 degree rotate won't be able to stream, it'll have to buffer the whole image)

**Comment by dineshkannaa** [comment]
> Sure, eg.:
> 
> ```
> aws s3 cp s3://mybucket/input.jpg - | \
>   vips thumbnail_source [descriptor=0] .jpg 128 | \
>     aws s3 cp - s3://mybucket/output.jpg
> ```
> 
> See:
> 
> https://libvips.github.io/libvips/2019/12/11/What's-new-in-8.9.html

@jcupitt  I dont have a source file here , all I have is stream which can be attached to stdin of the process and want the output as stream too . I want to do two operations    
                1. generate thumbnail of size "s" with properties like VIPS_INTERESTING_CENTRE , 
                2. generate blurred image 

Please suggest how I can achieve this . could two vips operations chained in this case ?

**Comment by jcupitt** [comment]
Yes, you could chain two operations, though it would be better to use something like Python.

```
cat k2.jpg | \
    vips thumbnail_source [descriptor=0] .jpg 128 | \
    vips gaussblur stdin .jpg 2 | \
    cat >x.jpg
```

**Comment by jcupitt** [comment]
For Python:

```python
import pyvips

# 0 is stdin, 1 is stdout
src = pyvips.Source.new_from_descriptor(0)
tgt = pyvips.Target.new_to_descriptor(1)

x = pyvips.Image.thumbnail_source(src, 128)
x = x.gaussblur(2)
x.write_to_target(tgt, ".jpg")
```

**Comment by dineshkannaa** [comment]
@jcupitt  Some clarifications :

Im using vips command through java , I need to get the image headers . Java can send the image to the command process using streams .So, Is there any way to get the Image headers through standard streams . 

> cat image.jpg | vipsheader -a stdin

 is not working here. Please help.

**Comment by jcupitt** [comment]
`vipsheader` doesn't know about the stream stuff, you're right, it should.

I made an enhancement issue: https://github.com/libvips/libvips/issues/1594

**Comment by jcupitt** [comment]
In the meantime, you'd need to write a small Python program to implement this.

**Comment by jcupitt** [comment]
I should have said, if you read the header off a stream with `vipsheader`, you won't be able to process it afterwards, since you'll have already read some bytes fro the front of the stream.

If you want to read the header, make some choices, and then do some processing, all on the same stream, you'll need to use a full libvips binding, eg. Python, Ruby, C#, C/C++, etc.

**Comment by dineshkannaa** [comment]
> If you want to read the header, make some choices, and then do some processing, all on the same stream, you'll need to use a full libvips binding, eg. Python, Ruby, C#, C/C++, etc.
      We were first using vips c API using JNI in java , since it crashes the JVM sometimes even in vips 8.9.0 , we planned to move to vips command through java (like im4java in ImageMagick) , as it supports standard streams . Our primary target is to use vips headers,thumbnail,gauss operations  from Java and there should not be any JVM crash. 

> I should have said, if you read the header off a stream with vipsheader, you won't be able to process it afterwards, since you'll have already read some bytes from the front of the stream.
     Its not a problem for me . We can send a separate stream for thumbnail operations.

**Comment by dineshkannaa** [comment]
> In the meantime, you'd need to write a small Python program to implement this.

If it is possible , it would be great . Please help me in implementing this

**Comment by jcupitt** [comment]
It's really easy.

```python
import pyvips

source = pyvips.Source.new_from_descriptor(0)
image = pyvips.Image.new_from_source(source)
# you can test the header now, eg. 
if image.width > 100:
    print("it's wide!")
thumb = pyvips.Image.thumbnail_source(source, 100)
blur = thumb.gaussblur(2)
blur.write_to_fie("x.png")
```

**Comment by dineshkannaa** [comment]
will this command support multiple threads ? 

> vips thumbnail_source [descriptor=0] .jpg 128 | \
>     vips gaussblur stdin .jpg 2

**Comment by jcupitt** [comment]
Yes, although you'd get better scaling with Python, I think.

**Comment by Gautamji** [comment]
> Sure, eg.:
> 
> ```
> aws s3 cp s3://mybucket/input.jpg - | \
>   vips thumbnail_source [descriptor=0] .jpg 128 | \
>     aws s3 cp - s3://mybucket/output.jpg
> ```
> 
> See:
> 
> https://libvips.github.io/libvips/2019/12/11/What's-new-in-8.9.html

Hi, is there some way to use this to stream and upload dzi files to s3? I mean the main .dzi file as well as all the files that are saved in the _files folder.

Or do I need to first save them all in a temp dir and then upload files from that directory?

**Comment by jcupitt** [comment]
libvips 8.13 adds DZI save to stream. You can now do eg.:

```
vips copy k2.jpg .dz | \
  aws s3 cp - s3://mybucket/output.zip
```

And it'll write a ZIP file containting the deepzoom image to s3.
