### ISSUE TITLE
Getting a crash when reading a grayscale tga

### ISSUE THREAD

**Issue by jtorresfabra** [jcupitt/libvips#980]
Hi @jcupitt, 

Just to let you know:
I'm getting a crash here https://github.com/jcupitt/libvips/blob/master/libvips/foreign/magick2vips.c#L338 when trying to load a greyscale tga, but if I use vips_magickload it works without problem. RGB tga works as expected. 

Sadly I cannot share the source image, but maybe I can create one to make it easier to reproduce. 

Thanks.

**Comment by jtorresfabra** [comment]
Update:

Using UndefinedChannel instead of AllChannels fixed it for me.

**Comment by jcupitt** [comment]
Huh weird. I tried here:

```
vips colourspace Gugg_coloured.jpg x.png b-w
convert x.png x.tga
identify -verbose x.tga
vipsheader x.tga
vips copy x.tga x.png
```

And with git master libvips and IM 6.9.7-4 (the ubuntu one) it seems OK. Let me know if you find a good test case you can share.

**Comment by jtorresfabra** [comment]
Ook, it seems there is something different in the image, so:
vips copy metallic.tga new.png
Segmentation fault (core dumped)
jtorres@panetone:~/Projects/libvips/product/bin$ identify metallic.tga metallic.tga TGA 2048x2048 2048x2048+0+0 8-bit sRGB 256c 4.195MB 0.000u 0:00.000

**Comment by jcupitt** [comment]
My working one is:

```
john@yingna ~/pics $ identify x.tga
x.tga TGA 972x1296 972x1296+0+0 8-bit sRGB 256c 1.26MB 0.000u 0:00.000
```

So I guess something in your image, or a bug in your imagemagick. Which version are you using?

**Comment by jtorresfabra** [comment]
Closed as it seems is related to a single image, will reopen if I get more crashes.

**Comment by jtorresfabra** [comment]
So I don't get a crash, it only happens with vips. :disappointed:

**Comment by jcupitt** [comment]
Thanks for the image. Yes, I see a crash here too. The TGA loader seems to be making an image with a NULL colormap, I've no idea why. I'll keep digging.

**Comment by jcupitt** [comment]
I think I found it --- it seems to work in git master now. The problem was that `PingImage()` was not setting `image->colormap`, and that made `GetImageChannelDepth()` crash.

It's awkward to backport to 8.6 because of the changes to the way that imagemagick load has changed.

**Comment by jcupitt** [comment]
Oh, as a workaround, you could use GraphicsMagick instead of ImageMagick. That'll fix the crash with libvips 8.6:

```
./configure --with-magickpackage=GraphicsMagick
```

**Comment by jtorresfabra** [comment]
Hey @jcupitt,

Confirmed the fix work in my end too.. the weird part was that it only happened to me with this image so far. And we do process tons of images. 

Thank you very much for the fast fix.

**Comment by jcupitt** [comment]
Yes, strange isn't it. We'd need to dig into the imagemagick internals I think to get a better understanding.

I pushed a version to 8.6 as well, so 8.6.4 should have this too.

Thanks for reporting the problem!
