### ISSUE TITLE
Banding in gradient images

### ISSUE THREAD

**Issue by rehankhan1217** [jcupitt/libvips#981]
When converting a gradient image from JPG to WebP, bands start appearing in the output file. Even if we increase the quality level to 90. 

![gradient](https://user-images.githubusercontent.com/4739557/40408802-5d7b7894-5e86-11e8-8740-d73bf94c298e.jpg)
![image](https://user-images.githubusercontent.com/4739557/40408823-6eafc304-5e86-11e8-9ced-6ee79c57a331.png)

Is there a way to avoid this banding? Would something similar to `-pre` in `cwebp` help with this?

**Comment by jcupitt** [comment]
Hello, I tried this:

```
john@kiwi:~/pics$ vips grey x.png 256 256 --uchar
john@kiwi:~/pics$ vips copy x.png x.webp
john@kiwi:~/pics$ vips copy x.webp y.png
john@kiwi:~/pics$ vips subtract x.png y.png x.v
john@kiwi:~/pics$ vips max x.v
2.000000
john@kiwi:~/pics$ vips min x.v
-2.000000
```

So the maximum error from webp compression is 2, which is rather small for a lossy compressor. 

You could try adding a little noise to hide the banding, though this would push file size up, of course, or you could use webp in lossless mode.

```
john@kiwi:~/pics$ vips copy x.png xl.webp[lossless]
john@kiwi:~/pics$ ls -l x.webp xl.webp 
-rw-r--r-- 1 john john 282 May 23 09:06 xl.webp
-rw-r--r-- 1 john john 502 May 23 09:03 x.webp
```

So with something simple like a gradient, a lossless webp is actually smaller than a lossy one.
