### ISSUE TITLE
png saved in zero sized files

### ISSUE THREAD

**Issue by ncauderan-cgin** [jcupitt/libvips#982]
I try to make a thumbnail from a png file, the thumbnail being also a png :
> vipsthumbnail.exe girafe.png --size 200 --format tnx_%s.tiff
works as aexpected
but 
> vipsthumbnail.exe girafe.png --size 200 --format tnx_%s.png
produces an empty png

I tried other pngs with the same result. I also made a C program directly using libvips, with the same results.
I am using 8.6.3 version on windows.

**Comment by jcupitt** [comment]
Hello @ncauderan-cgin, that's strange. I see:

```
john@katamata:~/pics$ vipsthumbnail nina.jpg --size 200 --format tnx_%s.png
john@katamata:~/pics$ ls -l tnx_nina.png 
-rw-r--r--  1 john  staff  41762 24 May 10:51 tnx_nina.png
```

I'll try on Windows. I guess this is win10?

**Comment by jcupitt** [comment]
I tried 8.6.3-1 on win10 and it worked too. How did you install vips? Did you add it to your PATH, or did you run the exe from within the vips download area?

Could there be spaces in any of your paths? It used to fail if there were non-ASCII characters in paths, but I thought that had been fixed.

**Comment by jcupitt** [comment]
Is this 8.6.3-1? The first 8.6.3 had a build problem. 

You need to unzip, then cd into the bin folder. You can delete everything except bin, but if you do that internationalisation will stop working.

**Comment by ncauderan-cgin** [comment]
This was 8.6.3, installing 8.6.3-1 solved the problem !
Thank you for your time John
