### ISSUE TITLE
Add "const" keyword e.g. to getters (VImage/C++ bindings)

### ISSUE THREAD

**Issue by Fingolfin1196** [jcupitt/libvips#983]
It would be nice if member functions of `VImage` like `int width()` or `int height()` were defined as `const`, since they don't modify the `VImage`, so they can be used on `const VImage`s. This extends to filters as well, as these don't change the `VImage`, either.

**Comment by jcupitt** [comment]
Hello @Fingolfin1196, I agree, it would be a nice improvement. A PR would be very welcome, if you have time.

**Comment by jcupitt** [comment]
I had some free time, so I made almost all members const. I suppose most operators should be const too. Would that be useful?

**Comment by jcupitt** [comment]
@lovell hopefully this won't mean any extra work for you.

**Comment by lovell** [comment]
This change makes sense and I guess the worst that will happen is a few compiler warnings. I should be able to test for further impact, if any, later this week.

**Comment by lovell** [comment]
Finally got round to looking at this - all good with sharp, thanks for checking.
