### ISSUE TITLE
re-size image buffer?

### ISSUE THREAD

**Issue by wyatt121** [jcupitt/libvips#984]
Hi John,

I hope all is well.  I'm trying to re-size my output image after the overlay.  

Here is my code.  All works but the thumbnail_buffer line...  

 ```
	$base = Vips\Image::newFromFile($apparel_image);
    	$overlay = Vips\Image::newFromFile($design_image);

        $base_width = $overlay->width;
        $scale = $design_width / $base_width;

        $overlay = Vips\Image::newFromFile("$design_image", ["scale" => $scale]);
        $overlay = $overlay->multiply([1.0, 1.0, 1.0, 0.6]);
        $overlay = $overlay->embed($dx, $dy, $base->width, $base->height);

        $out = $base->composite2($overlay, "over");

        $image = Vips\Image::thumbnail_buffer($out, 200, ["height" => 200]);

        $str = $image->writeToBuffer(".jpg");



// Display image to the browser

    header("Content-Type: image/jpeg");
    echo $str;
    exit();
```

I'm getting this error:  "Uncaught Jcupitt\Vips\Exception: VipsForeignLoad: buffer is not in a known format
 in /var/www/html/build/vendor/jcupitt/vips/src/Image.php:664"

Do I need the thumbnail or the thumbnail_buffer function for this?  

Any help is much appreciated.

Wyatt

**Comment by jcupitt** [comment]
Hello @wyatt121, try:

```php
       $out = $base->composite2($overlay, "over");

       $thumb = $out->thumbnail_image(200, ["height" => 200]);

       $str = $thumb->writeToBuffer(".jpg");
```

`thumbnail_buffer` thumbnails an image held as a formatted image in a string.

**Comment by wyatt121** [comment]
Hi John,

Your code above worked perfectly.  No problems.  Thank you very much!

Wyatt
