### ISSUE TITLE
Link error when extending vips on Windows using VS2017

### ISSUE THREAD

**Issue by angelmixu** [jcupitt/libvips#985]
Hi!

We are extending the functionality of vips and took the base example on the web: http://jcupitt.github.io/libvips/API/current/extending.html
When linking with the release binaries from 8.6.3 there's a link error:

```
1>------ Build started: Project: testVipsExtend, Configuration: Debug x64 ------
1>Negative.cpp
1>testVipsExtend.cpp
1>Generating Code...
1>Negative.obj : error LNK2001: unresolved external symbol _vips__argument_id
1>C:\testVipsExtend\testVipsExtend\x64\Debug\testVipsExtend.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "testVipsExtend.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

As I have read, global variables in DLL's cannot be exported as is using the .def file and must be exported using __declspec(dllexport/import). When using .def files it only exports the pointer to the variable inside a table in the DLL:
https://docs.microsoft.com/en-gb/cpp/build/importing-data-using-declspec-dllimport

In object.h file I can find:

`extern int _vips__argument_id;`

So we should change it for exporting it with __declspec.

Here there are the source files of the test: 
[testVipsExtend.zip](https://github.com/jcupitt/libvips/files/2044284/testVipsExtend.zip)

Testing the same code on macOS works fine, there's no link error and the output is correct. I've used homebrew for getting the libvips libraries.

I'm preparing a VS2017 project for building vips and I've found some compiling errors.
I've cloned the repo and I'm fixing them at the same time I'm creating the project, I'll soon send you a PR  for if you want to merge it.

BTW, I'm creating the vs2017 project outside the libvips repository, would you prefer it to be inside a directory?
I'm preparing it having in mind I have all the dependencies installed using vcpkg.

**Comment by jcupitt** [comment]
Hello @angelmixu, you're right, we should change that variable. I think it would be best to add some new API, perhaps:

```
int vips__argument_get_id( void );
```

to generate a new argument id. The macros would need updating as well.

Sure, I'm very happy to accept a PR with compile fixes!

i would not be able to maintain a vs2017 project file, so it's probably better outside libvips, if that's OK with you.

**Comment by angelmixu** [comment]
Wow! Thas was quick!
I think you're awesome :P
With the example above now it builds and runs correctly.
Thanks! :)

Regarding the project I'm building, what preprocessor definitions should I use?

At this moment I'm using the following, as it looks like it's the minimum for having something working:
`HAVE_CONFIG_H;HAVE_ANALYZE;HAVE_RADIANCE;HAVE_PPM;HAVE_PNG;HAVE_TIFF;HAVE_EXIF;HAVE_JPEG;OS_WIN32;_CRT_SUPPRESS_RESTRICT;VIPS_CPLUSPLUS_EXPORTS;VIPS_CC_EXPORTS;`

VIPS_CC_EXPORTS is for libvipsCC vips7 interface exporting symbols (they're missing).

There are three defines I'm not sure to use as it looks like enabling them uses a deprecated api of glib:
`HAVE_THREAD_NEW; HAVE_COND_INIT; HAVE_MUTEX_INIT`

Should I enable other libraries support like HAVE_GIFLIB, webp support, svg, csv, etc. ?

**Comment by jcupitt** [comment]
Oh don't be impressed, it was a tiny thing!

If you run `./configure` it'll make you a config.h with a documented set of options. For native win64 I get:

https://gist.github.com/jcupitt/e62801e02edb8180b5b0f9cf20c94c31

So I'd just copy-paste that, I think.

**Comment by jcupitt** [comment]
... and `build-win64` compiles each file with:

```
x86_64-w64-mingw32-gcc-win32 -DHAVE_CONFIG_H -I. -I../.. -I../../libvips/include -DG_DISABLE_ASSERT -DG_DISABLE_CHECKS -mms-bitfields -I/home/john/GIT/build-win64/8.6/inst/lib/glib-2.0/include -I/home/john/GIT/build-win64/8.6/inst/include/poppler/glib -I/home/john/GIT/build-win64/8.6/inst/include/poppler -I/home/john/GIT/build-win64/8.6/inst/include/pixman-1 -I/home/john/GIT/build-win64/8.6/inst/include/pango-1.0 -I/home/john/GIT/build-win64/8.6/inst/include/openslide -I/home/john/GIT/build-win64/8.6/inst/include/libxml2 -I/home/john/GIT/build-win64/8.6/inst/include/librsvg-2.0 -I/home/john/GIT/build-win64/8.6/inst/include/libpng16 -I/home/john/GIT/build-win64/8.6/inst/include/libgsf-1 -I/home/john/GIT/build-win64/8.6/inst/include/harfbuzz -I/home/john/GIT/build-win64/8.6/inst/include/glib-2.0 -I/home/john/GIT/build-win64/8.6/inst/include/gdk-pixbuf-2.0 -I/home/john/GIT/build-win64/8.6/inst/include/freetype2 -I/home/john/GIT/build-win64/8.6/inst/include/cairo -I/home/john/GIT/build-win64/8.6/inst/include/ImageMagick-6 -D_DLL -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -I/home/john/GIT/build-win64/8.6/inst/include -mms-bitfields -march=x86-64 -I/home/john/GIT/build-win64/8.6/inst/include -O2 -MT add.lo -MD -MP -MF .deps/add.Tpo -c add.c  -DDLL_EXPORT -DPIC -o .libs/add.o
```

Removing the -I and -L lines and some other cruft, it's doing:

`-DHAVE_CONFIG_H` I guess you define this already.

`-DG_DISABLE_ASSERT`, `-DG_DISABLE_CHECKS` these make glib go a little quicker. You should use them for a release build, but leave them off for a debug build.

`-mms-bitfields` gcc needs this to lay out structs in the same way was MSVC, so you don't need it. 

`-D_DLL`, `-DMAGICKCORE_QUANTUM_DEPTH=16`,  `-DMAGICKCORE_HDRI_ENABLE=0` you must define these just before including the ImageMagick headers. 

`-DDLL_EXPORT`, `-DPIC` you must have these for anything building a DLL, I guess you have them already.

**Comment by angelmixu** [comment]
Thanks!

About config.h, I looked for macros and their implications in code on windows and visual studio, here's a list that aren't needed or have no use:

* HAVE_BIND_TEXTDOMAIN_CODESET looks like there's no macro on vips code, as is, seems to get 
 bind_textdomain_codeset functions from libintl.h dependency
* HAVE_CONTEXT_GET_HELP there's no macro on vips code
* HAVE_DCGETTEXT no macro on vips
* HAVE_DIRENT_H no macro on vips, but dirent.h exists in dependencies
* HAVE_ERRNO_H no macro on vips, but errno.h exists in WinSDK
* HAVE_FCNTL_H no macro no vips, but fcntl.h exists in WinSDK
* HAVE_GETPAGESIZE no macro in vips, getpagesize doesn't appear to be in my WinSDK nor dependencies, in vips code the reference is only when not defined OS_WIN32 on function vips_getpagesize
* HAVE_GETTEXT no macro in vips, gettext functions are on libintl.h dependency
* HAVE_GETTIMEOFDAY no macro in vips, gettimeofday() is not in dependencies or WinSDK
* HAVE_GETVIRTUALPIXELS only used if ENABLE_MAGICKLOAD and HAVE_MAGICK6 are defined (I have to test including magick dependencies)
* HAVE_G_WIN32_GET_COMMAND_LINE no use in vips, g_win32_get_command_line already in dependencies
* HAVE_INTTYPES_H no use in vips, inttypes.h not present in any dependency nor WinSDK
* HAVE_LIMITS_H no use in vips, but limits.h is present in VS2017 SDK
* HAVE_LOCALE_H no use in vips, but locale.h is present in WinSDK
* HAVE_MATH_H no use in vips, but math.h is present on WinSDK
* HAVE_MEMORY_H no use in vips, but memory.h is present on vips includes, memory include for c++ is present on VS2017 SDK
* HAVE_MEMSET no use in vips, but memset is present on VS2017 SDK
* HAVE_MKSTEMP no use in vips, mkstemp not found
* HAVE_MKTEMP no use in vips, mktemp present in WinSDK
* HAVE_NUMBER_SCENES no use in vips
* HAVE_PUTENV no use in vips, putenv() is present in WinSDK
* HAVE_RAND no use in vips, rand() is present in stdlib.h from WinSDK
* HAVE_SETIMAGEOPTION no use in vips, 
* HAVE_STDINT_H no use in vips, stdin.h present in VS2017 SDK
* HAVE_STDLIB_H is defined in jconfig.h from dependencies, undef at vips foreign/jpeg.h, stdlib.h is present in WinSDK
* HAVE_STRCASECMP no use in vips, strcasecmp is not present in windows, I had to define it as stricmp in my own config.h for compiling on VS2017
* HAVE_STRCHR no use in vips, strchr is present in WinSDK
[... some more pending to review ...]

There's a lot more defines to test/look at, I'll update the post when I finish.

One important define is HAVE_UNISTD_H, in Windows ecosystem there's no unistd.h file, although there are unistd.h files mimicking the functionality of it for using on Visual Studio.
For compiling vips I only needed setting the following instead of using a complete unistd.h file:
```
#define restrict 	__restrict  // this is already defined in your config.h

// in windows the following doesn't exist so we have to use other equivalent function
#define strcasecmp 	stricmp

// used for g_access mode in vips_existsf, it is usually set as 4
#define R_OK    4       /* Test for read permission.  */

// in stat.h of WinSDK st_mode from stat struct is an unsigned short, but in vips_tracked_open function 
// says it is promoted to int and gets it as int
typedef int mode_t; 

// in windows ssize_t is not defined, usual unistd.h in macOS and Linux declares it as long
typedef long ssize_t;
```

Also, PIC macro doesn't seem to be used in vips code, as I have googled, it's a GCC-only compiler flag.

I'll go compile vips with that config.h and see what I find :)

**Comment by angelmixu** [comment]
@jcupitt just sent a pull request for the fixes I've made: https://github.com/jcupitt/libvips/pull/988
There's all the info there, freel free to contact me about any issue/suggestion.

**Comment by jcupitt** [comment]
OK, merged so I'll close. Thanks again!
