### ISSUE TITLE
How to use extract_area with the tiffsave command

### ISSUE THREAD

**Issue by AndreasSchmid1** [jcupitt/libvips#986]
I am currently converting svs files with tiffsave to a generic tiled tiff. ("tiffsave --compression jpeg --Q " + "75" + " --bigtiff --tile --tile-width 256 --tile-height 256 --pyramid")

I found a document about using extract_area to save a region of interest to a deepzoom pyramid. https://jcupitt.github.io/libvips/API/current/Making-image-pyramids.md.html

Can one utilize extract_area for tiffsave as well?

Thank you very much for help in advance.

**Comment by jcupitt** [comment]
Hello @AndreasSchmid1, sure, try:

```
vips crop huge.svs area.tiff[compression=jpeg,Q=75,bigtiff,tile,tile-width=256,tile-height=256,pyramid] 100 200 1000 2000
```

Are you using PHP or Python? You could call libvips directly instead of shelling out, it might be a bit quicker and safer.

**Comment by AndreasSchmid1** [comment]
Thank you very much for your fast help! No i am using Progress Start from my C# App.

**Comment by AndreasSchmid1** [comment]
I didn't know that. Great news! Thanks!
