### ISSUE TITLE
feature request - b/w based on HSV

### ISSUE THREAD

**Issue by jeremychone** [jcupitt/libvips#990]
I had a quick look and did not find a way to have a BW based on Saturation (as it is possible with OpenCV). 

(from opencv site)
![image](https://user-images.githubusercontent.com/74671/40891364-f5da92ea-6738-11e8-9315-28b7cd52e67c.png)

I am using the Node Sharp binding, so I might be missing something.

**Comment by jcupitt** [comment]
It has HSV and LCh:

http://jcupitt.github.io/libvips/API/current/libvips-colour.html#libvips-colour.description

But i don't know how sharp exposes this, you'd need to ask there.

In Ruby, for example, you can write:

```ruby
H, S, V = image.colourspace(:hsv).bandsplit
```

(though of course you shouldn't use HSV)

**Comment by jeremychone** [comment]
@jcupitt Sorry for my late reply, and thanks for your quick response. This is what I needed.

My next question is more on the node-sharp side (which I will log there) and see if they have a way to chain the colorspace to a save b/w without having to retrieve the buffer on the JS side (which they have a great model for). 

node-sharp with libvips is amazingly fast and concurrent. We can pipe 7K images at once, and all works as expected and fully multi-threaded. Very impressive work, thanks!

BTW, it's for some ML project I am working on.

**Comment by jcupitt** [comment]
Heh, thanks!

For ML, you should look at LCh and use the C band:

https://en.wikipedia.org/wiki/CIELAB_color_space#Cylindrical_representation:_CIELCh_or_CIEHLC

It should work quite a bit better than HSV.

**Comment by jeremychone** [comment]
Interesting, I was thinking about the same thing (I am not not a color expert). Cool, we will start with LCh, and use the C band and see how it goes.
