### ISSUE TITLE
best large multi-band image format

### ISSUE THREAD

**Issue by imagolive** [jcupitt/libvips#991]
We're looking at using vips to work on some hyperspectral data.

What do you suggest as the best format to convert the data into? The images can have up to 138 bands with width x height of more than 30,000px x 30,000px.

Thx,

Michael

**Comment by jcupitt** [comment]
Gosh, that's huge. 

I think it would probably have to be tiff. It supports any number of bands, and in tiled mode you can read efficiently and still have some compression (deflate). 

I use vips format for hyperspectral stuff, but of course that's not going to work well for interoperability, and there's no compression.

**Comment by jcupitt** [comment]
I made a tiny test program:

```python
#!/usr/bin/env python

import sys
import pyvips

# replicate our source image up to this size
target_size = 30000

# and bands up to this 
target_bands = 138

im = pyvips.Image.new_from_file(sys.argv[1])

im = im.replicate(1 + target_size / im.width, 1 + target_size / im.height)
im = im.crop(0, 0, target_size, target_size)

# double bands repeatedly to get past bands, then cut down
while im.bands < target_bands:
    im = im.bandjoin(im)
im = im.extract_band(0, n=target_bands)

im.write_to_file(sys.argv[2])
```

You could use it to experiment with various formats and codings. I tried:

```
john@yingna ~/try $ VIPS_PROGRESS=1 ./hyper.py ~/pics/theo.jpg x.tif[tile,compression=deflate,bigtiff]
hyper.py temp-21: 30000 x 30000 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
hyper.py /home/john/pics/theo.jpg: 6048 x 4032 pixels, 8 threads, 6048 x 16 tiles, 256 lines in buffer
hyper.py /home/john/pics/theo.jpg: done in 0.163s          
hyper.py temp-21: done in 1.48e+03s          
john@yingna ~/try $ ls -l x.tif 
-rw-r--r-- 1 john john 1954010026 Jun  4 13:26 x.tif
```

A 30k x 30k 138 band 8-bit image should be ~120gb, so deflate does well in this case, I think. That's just with a photo as sample data, you might have quite different stuff in your images. 25m is rather slow, sadly -- the deflate compression in libtiff is of course single-threaded. 

TIFF also support pyramids, which might be handy for on-line viewing, if that's one of your interests. iipimage at least can serve tiles to seadragon from pyramidal tiff, and I think Ruven has hyperspectral support in there. 

```
john@yingna ~/try $ VIPS_PROGRESS=1 ./hyper.py ~/pics/theo.jpg x.tif[tile,compression=deflate,bigtiff,pyramid]
hyper.py temp-21: 30000 x 30000 pixels, 8 threads, 128 x 128 tiles, 256 lines in buffer
hyper.py /home/john/pics/theo.jpg: 6048 x 4032 pixels, 8 threads, 6048 x 16 tiles, 256 lines in buffer
hyper.py /home/john/pics/theo.jpg: done in 0.162s          
hyper.py temp-21: done in 2.16e+03s          
john@yingna ~/try $ ls -l x.tif 
-rw-r--r-- 1 john john 2753017040 Jun  4 14:26 x.tif
```

**Comment by imagolive** [comment]
Thx. We suspected tiff but wanted to check if there was a better option.

The script will come in handy.
