### ISSUE TITLE
Reduce size of JPG

### ISSUE THREAD

**Issue by sonyarianto** [jcupitt/libvips#993]
![whitening mask](https://user-images.githubusercontent.com/333051/41019975-47f94acc-698b-11e8-8f65-16503689cdb6.jpg)

Hi @jcupitt 
Sorry this I ask here. I have this JPG and has 500KB+ size, I want to reduce/compress the file size to lower size. I tried online compression service and it can compressed to 12 KB or something.

I use command `vips jpegsave a.jpg b.jpg` command but the output still large (around 500KB)

Any help are appreciated.

**Comment by jcupitt** [comment]
Hello, that jpg has a huge CMYK ICC profile inside. Just strip it out:

```
$ vips copy ak.jpg x.jpg[strip]
```

**Comment by sonyarianto** [comment]
@jcupitt Wowww that's cool, thank you very much, you save my day ;)
