### ISSUE TITLE
Custom Fonts - Question

### ISSUE THREAD

**Issue by DerekJarvis** [jcupitt/libvips#994]
First off - thanks for this tool! There was no way I could approach VIPS or ImageMagick without this.

I'm trying to do an Annotate action but I can't seem to select a font that is installed on my system in the drop down. Can you explain how to add a font?

**Comment by jcupitt** [comment]
Hello @DerekJarvis,

You need to give more information: what system are you using (mac, win, linux), what libvips version, what command are you running, what error message do you see.

**Comment by DerekJarvis** [comment]
Thanks for the quick response!

I'm using nip2 8.6.0 on Windows. In the "Annotate" action > Font > Family" area I only see a small set of fonts. Interesting enough, when I go to the Preferences in nip2 > Paintbox > Default Paintbox Font, I can see the font I would like to embed into a picture. I tried to manually type it into the family field but it seemed to break the action.

Also, I have another question about how I could batch my workspace 100 times using a different text and source image for each iteration. Would this be better asked in a separate Issue?

**Comment by jcupitt** [comment]
Huh curious. I have a Windows machine at home, I'll have a look tonight.

Yes, a separate issue for nip2 batching would be helpful, thanks.

**Comment by DerekJarvis** [comment]
Thanks. I tried this, and it does indeed show in the menu, but the image
does not update with this font. It also highlights this action in Red
indicating there is an error, but I can't seem to see the specific error
message. I also tried manually changing the "Item" field, but no luck.

In other ImageMagick forums I saw that there is a special script that needs
to be ran in order to index / convert fonts for it to be able to use them.
Could this be the case?

**Comment by DerekJarvis** [comment]
I tested again, this time focusing on ImageMagick. If I call out the specific font path, IM is able to generate the image just fine. All other commands show that it's having trouble loading the type.xml file.

I also noticed that I corrupted my "local.conf" file, so I re-installed.

nip2-8.6.0\bin>convert -font "Adobe Thai Normal" label:"test text" test.png
Fontconfig error: "local.conf", line 1: no element found

-- Before resetting, I noticed that the "Adobe Thai" font did make it into type-windows.xml

-- After resetting, I look at the font list and see it's there

convert -list font
Font: Adobe-Thai
    family: Adobe Thai
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: C:/WINDOWS/fonts/Adobe Thai Regular.otf
	

convert -pointsize 32 -font "Adobe-Thai" label:"test text" test.png
convert.exe: UnableToOpenConfigureFile `type.xml' @ warning/configure.c/GetConfigureOptions/706.

nip2-8.6.0\bin>convert -pointsize 32 -font "C:/WINDOWS/fonts/Adobe Thai Regular.otf" label:"test text" test.png
-- successful

-- Look in type-windows.xml , Adobe-Thai is missing

-- Manually add "Adobe Thai" in options in UI
-- Still missing from type-windows.xml

-- Select "Adobe Thai" in options in UI
-- Still missing from type-windows.xml

-- Manually add "Adobe-Thai" in options in UI
-- Still missing from type-windows.xml

-- Select "Adobe-Thai" in options in UI
-- Still missing from type-windows.xml

-- Image still not generating

-- Notice that the end of convert -list font shows:
convert.exe: UnableToOpenConfigureFile `type.xml' @ warning/configure.c/GetConfigureOptions/706


At this point, if I can't figure it out in the UI it's OK. I can write a script to generate all the text images by specifying the full path and then use that as an action in the image.

**Comment by DerekJarvis** [comment]
I found that manually changing the "Command" of the action fixed it:
`Magick.command [    "\"%s\"",    "-pointsize 32 -font \"C:/WINDOWS/fonts/Adobe Thai Regular.otf\"",    antialias._flag,    gravity._flag,    foreground._flag,    undercol._flag,    "-annotate",     geometry._flag,     "\"" ++ text.value ++ "\"",    "\"%s\""   ]`

**Comment by jcupitt** [comment]
Glad you got it working.

nip2 has it's own text tool: Toolkits / Image / Patterns / Text. You could see if your font is available there.

If it is, you can also annotate with the nip2 tools. You have to put the steps together yourself, but it's not that complicated, and the result would be a lot quicker.

![screenshot from 2018-06-08 17-51-07](https://user-images.githubusercontent.com/580843/41170556-b2229c04-6b44-11e8-9535-22434526116f.png)

The steps would be:

1. Load an image to render the text on top of.
2. Use Image / Patterns / Text to make a text image.
3. Use Image / Transform / Resize / Canvas to resize your text canvas to match the image. For `New width`, enter `A1.width`, the size of the input image. Same for new height. You can use the position menu to decide how to position the text within the expanded image.
4. Use Colour / New / Colour to make a new colour object (the colour the text will be painted with).
5. Finally, click on A3 (the expanded text image) and ctrl-click on A1 and A3 (the background image and the colour swatch) and select Filter / Blend / Image. It'll use the first thing you select (the mask) to pick between the image and the colour. You might need to flip the sense of the mask.

Here's a workspace that does this:

https://gist.github.com/jcupitt/3edf3580a8b9d768c660cf9e77babe71

Start nip2, drag in annotate.ws to load it, then drag some image into the top cell to load that and annotate it.
