### ISSUE TITLE
Support transparent backgrounds when using PDFium

### ISSUE THREAD

**Issue by tropperstyle** [jcupitt/libvips#995]
I was able to run `vips pdfload input.pdf output.png` using PDFium after following #689 - however the output PNG renders a white background. When using pdftocairo, the -transp flag enabled this. Is this possible to achieve with the vips command line?

**Comment by jcupitt** [comment]
Hello, I'll have a look. Do you have an sample PDF with transparent elements?

**Comment by tropperstyle** [comment]
[test.pdf](https://github.com/jcupitt/libvips/files/2081426/test.pdf)

![test-convert](https://user-images.githubusercontent.com/28314/41115214-afe70ab0-6a3b-11e8-8e16-68a364d8d559.png)
![test-vips](https://user-images.githubusercontent.com/28314/41115215-b002084c-6a3b-11e8-92b6-b2c0fac2ba3b.png)

**Comment by jcupitt** [comment]
I had a go with a `background` option, for example:

```
vips copy transparent.pdf[background=0] x.png
```

To set a black (transparent) background. Would you be able to test it?

**Comment by jcupitt** [comment]
It'll be in 8.7, closing.
