### ISSUE TITLE
Export batch command feature?

### ISSUE THREAD

**Issue by DerekJarvis** [jcupitt/libvips#996]
NIP2 does an amazing job at building up a set of operations - and I want to use that to make do a big job of them. Is there way to automate running a workspace with a few variables changed, or to generate the corresponding VIPS / IM commands from a workspace?

**Comment by jcupitt** [comment]
Hello again,

There are two main ways of doing this: you can group operations and loop within nip2, or you can use a regular batch script to execute the nip2 binary over a set of inputs. 

## Groups

nip2 groups are arrays of objects which it will automatically iterate over. For example, click File / Open, select the first file, then shift-click on the last and press OK. You'll load the set of image files as a group, perhaps A1.

Now enter `A1 * 2` and you'll get a new group where each image has been doubled in brightness. RIght-click on the new group name (A2 I guess), select Ungroup, and you can see them. You can right-click on a group name and select Save As to save them as a set of files. If you enter `fred.jpg` in the save box, they will be saved as `fred1.jpg`, `fred2.jpg` and so on.

You can use the Magick menu like this too. Load a group of images, select Magick / Annotate, and you'll get a new group of images where each one has been annotated. You can't change the annotate properties for each image though, so the same text will be rendered on each one.

## Batching

This is a little more complex. You have to write a batch script (a .bat file on Windows) that runs nip2 on each image you want to process. You give a workspace, but use the `--set` option to change the value of cells, and to set which cell is written to the output.

There's a section in the manual. Press F1 and have a look at section 4.5.

**Comment by DerekJarvis** [comment]
Thanks again for the help. I've tried many different things, but I can't seem to change the text for an Annotate action.

Is there a reference to show what variables can be changed? I've tried:
--set Workspaces.tab2.A2="123"
--set Workspaces.tab2.A2.text="123"
--set Workspaces.tab2.A2.text.String="123"
--set Workspaces.tab2.A2.text.String.value="123"
--set Workspaces.tab2.A2=123
--set Workspaces.tab2.A2.text=123
--set Workspaces.tab2.A2.text.String=123
--set Workspaces.tab2.A2.text.String.value=123

https://gist.github.com/DerekJarvis/57587cb9641133040d656a077e614dca

**Comment by jcupitt** [comment]
I would make a couple of changes to your workspace:

- make a new row (it's A3 in my example) which just has the string you want to draw
- make A2.text.value use that
- add a row called "main" (this is the thing nip2 writes to the output)

https://gist.github.com/jcupitt/da7dde6e3a215c145c5d764e32e7e0b8

Now if I run nip2 like this:

```
nip2 -b annotate.ws -o x.png --set Workspaces.tab2.A3=\"pear\"
```

I get this:

![x](https://user-images.githubusercontent.com/580843/41193958-2a1149dc-6c0c-11e8-9650-2479435c468e.png)

On Windows you'll need to use `nip2-cli.exe` rather than nip2, and you might need more or fewer backslashes to get the quotes passed into the command.

**Comment by DerekJarvis** [comment]
Ah, the new structure of the workspace makes a lot of sense. Thanks. I've modified my main workspace, but I still can't get this sample workspace to replace values.

Here's some things I tried:

> nip2-cli -bpV test2.ws -o test2.png --set Workspaces.tab2.A3=3
>  no-value
> 
> nip2-cli -bpV test2.ws -o x.png --set Workspaces.tab2.A3=\"pear\"
>  no-value
> 
> nip2-cli -bpV test2.ws -o x.png --set Workspaces.tab2.A3=pear
>  no-value
> 
> nip2-cli -bpV test2.ws -o x.png --set Workspaces.tab2.A3="pear"
>  no-value
> 
> nip2-cli -bpV test2.ws -o x.png --set Workspaces.tab2.A3="\"pear\""
>  no-value
> 
> nip2-cli -bpV test2.ws -o x.png --set Workspaces.tab2.A3=\"\"pear\"\"
>  no-value
> 
> nip2-cli -bpV test2.ws -o x.png --set Workspaces.tab2.A3='pear'
>  no-value
> 
> nip2-cli -bpV test2.ws -o x.png --set Workspaces.tab2.A3=^"pear^"
>  no-value
> 
> nip2-cli -bpV test2.ws -o x.png --set Workspaces.tab2.A3=\""pear"\"
>  no-value
> 
> nip2-cli -bpV test2.ws -o x.png
>  C:\Users\docsa\AppData\Roaming\nip2-8.6.0\tmp\untitled-nip2-73-X5E12JZ.v
>  output successful

So it only works when not modifying anything.

**Comment by jcupitt** [comment]
My son has been playing fortnite for days and I've not been able to get on the PC. I'll kick him off and see if I can make it work there.

**Comment by DerekJarvis** [comment]
That's funny, I've been playing Fortnite in between trying to export unique invitations. XD
I appreciate the help!

**Comment by jcupitt** [comment]
If you see a player called "teca" please shoot him in the face for me :(

**Comment by jcupitt** [comment]
I had a go but couldn't find the right combination of `"^'\` to escape the quotes. I did get this working last year at my previous job, but of course I can't remember exactly what I did.

I'll add a little more debugging output to nip2 with `-V`.

**Comment by jcupitt** [comment]
Ah found it, try:

```
nip2-cli -b annotate2.ws --set Workspaces.tab2.A3=\\\"pear\\\" -o x.png
```

So three backslashes before the double quote works *rolls-eyes*.

**Comment by DerekJarvis** [comment]
This worked perfectly! Thanks so much.
