### ISSUE TITLE
Pango Markup fgcolor not working

### ISSUE THREAD

**Issue by t1n1wall** [jcupitt/libvips#997]
Hi,

I've been trying to make some images with text, and pango markup seems like the right way to go.  However the first step was to make a greyish text on white background, and the background is indeed white, but the so is the text.  I took a sample pango markup structure from imagick, and get quite different results.  Is this a bug ?

imagick output  [http://www.imagemagick.org/Usage/text/pango_test.png](url)
imagick source pango markup [http://www.imagemagick.org/Usage/text/pango_test.txt](url)

**Command** 
```
vips text foo.png "<span size='49152'>Pango Markup Demo</span>Size: <small><
small><small>smallest</small> smaller</small> small</small>  normal  <big>big <big>bigger <big>biggest</big></big></big>
Styles: <b>bold</b> <i>italic</i> <u>underlined</u> <s>strikethrough</s> <tt>monospaced</tt><sup>superscript</sup> --nor
mal-- <sub>subscript</sub>Underline: <span underline='single'>single</span> <span underline='double'>double</span> <span
 underline='low'>low</span> <span underline='error'>error</span>Colors: <span fgcolor='red'>red</span> <span fgcolor='bl
ue'>blue</span> --  <span bgcolor='yellow'>yellow bg</span> <span bgcolor='skyblue'>skyblue bg</span> --  <span underlin
e_color='blue'><u>underline</u></span> <span strikethrough_color='red'><s>strikethrough</s></span>Rise: ---<span rise='1
0240'>-</span><span rise='20480'>---</span><span rise='10240'>-</span><span rise='-10240'>-</span><span rise='-20480'>--
-</span><span rise='-10240'>-</span>"
```

**Comment by t1n1wall** [comment]
output from the command

![foo](https://user-images.githubusercontent.com/15526172/41150989-4d98f356-6b07-11e8-96cc-6fe1f9c95807.png)

**Comment by jcupitt** [comment]
Hello, vips `text` just renders a one-band mask image with 0 for transparent and 255 for solid, so the output is more like an alpha channel. You need to combine it with other operations to render coloured text. 

For example, in Python you could write:

```python
im = pyvips.Image.text("hello world").ifthenelse([255,0,0], [0,255,0])
```

To render red text on a green background (argh!).

**Comment by t1n1wall** [comment]
Thanks !

So if I want a sentence with different colors for different words I need to make separate images and combine them ?

**Comment by jcupitt** [comment]
Yes, sorry :(
