### ISSUE TITLE
Convert PNG or JPEG to JP2000

### ISSUE THREAD

**Issue by proyb6** [jcupitt/libvips#998]
I couldn't find any info on which command to save as JP2 format despite had VIPS, OpenJP2000 and OpenSlide compiled.

Does it mean OpenSlide will be doing the converting? How do I execute from VIPS the command from side?

**Comment by jcupitt** [comment]
Hello, vips 8.6 does not support writing jp2k images. OpenSlide uses the jp2 decoder to read some slide formats, but libvips does not use it itself.

8.7, the version in git master, supports writing via imagemagick, so you can do:

```
vips magicksave k2.tif x.jp2 --format JP2
```

provided your imagemagick has been built with jp2k support.

**Comment by proyb6** [comment]
That's great, will do.

**Comment by jcupitt** [comment]
.. I should have said, 8.7 isn't out yet, so you'll need to build yourself from libvips git master :(

**Comment by proyb6** [comment]
No worry, I had use the build today.
